/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gantt.GanttProjectItem"]||(dojo._hasResource["dojox.gantt.GanttProjectItem"]=!0,dojo.provide("dojox.gantt.GanttProjectItem"),dojo.require("dojox.gantt.GanttTaskItem"),dojo.require("dojo.date.locale"),dojo.declare("dojox.gantt.GanttProjectControl",null,{constructor:function(a,c){this.project=c;this.ganttChart=a;this.projectNameItem=this.projectItem=this.descrProject=null;this.posX=this.posY=0;this.previousProject=this.nextProject=null;this.arrTasks=[];this.duration=this.percentage=
0},checkWidthProjectNameItem:function(){if(this.projectNameItem.offsetWidth+this.projectNameItem.offsetLeft>this.ganttChart.maxWidthTaskNames){var a=this.project.name.substring(0,this.projectNameItem.firstChild.length-Math.round((this.projectNameItem.offsetWidth+this.projectNameItem.offsetLeft-this.ganttChart.maxWidthTaskNames)/(this.projectNameItem.offsetWidth/this.projectNameItem.firstChild.length))-3);a+="...";this.projectNameItem.innerHTML=a}},refreshProjectItem:function(a){this.percentage=this.getPercentCompleted();
dojo.style(a,{left:this.posX+"px",width:this.duration*this.ganttChart.pixelsPerWorkHour+"px"});var c=a.firstChild,b=this.duration*this.ganttChart.pixelsPerWorkHour;c.width=(b==0?1:b)+"px";c.style.width=(b==0?1:b)+"px";c=c.rows[0];if(this.percentage!=-1){if(this.percentage!=0)b=c.firstChild,b.width=this.percentage+"%",b=b.firstChild,dojo.style(b,{width:(!this.duration?1:this.percentage*this.duration*this.ganttChart.pixelsPerWorkHour/100)+"px",height:this.ganttChart.heightTaskItem+"px"});if(this.percentage!=
100)b=c.lastChild,b.width=100-this.percentage+"%",b=b.firstChild,dojo.style(b,{width:(!this.duration?1:(100-this.percentage)*this.duration*this.ganttChart.pixelsPerWorkHour/100)+"px",height:this.ganttChart.heightTaskItem+"px"})}else b=c.firstChild,b.width="1px",b=b.firstChild,dojo.style(b,{width:"1px",height:this.ganttChart.heightTaskItem+"px"});c=a.lastChild.firstChild;dojo.style(c,{height:this.ganttChart.heightTaskItem+"px",width:(!this.duration?1:this.duration*this.ganttChart.pixelsPerWorkHour)+
"px"});c.rows[0].firstChild.height=this.ganttChart.heightTaskItem+"px";if(this.project.parentTasks.length==0)a.style.display="none";return a},refreshDescrProject:function(a){dojo.style(a,{left:this.posX+this.duration*this.ganttChart.pixelsPerWorkHour+10+"px"});if(this.project.parentTasks.length==0)this.descrProject.style.visibility="hidden";return a},postLoadData:function(){},refresh:function(){this.posX=(this.project.startDate-this.ganttChart.startDate)/36E5*this.ganttChart.pixelsPerHour;this.refreshProjectItem(this.projectItem[0]);
this.refreshDescrProject(this.projectItem[0].nextSibling);return this},create:function(){var a=this.ganttChart.contentData.firstChild;this.posX=(this.project.startDate-this.ganttChart.startDate)/36E5*this.ganttChart.pixelsPerHour;if(this.previousProject)if(this.previousProject.arrTasks.length>0){var c=this.ganttChart.getLastChildTask(this.previousProject.arrTasks[this.previousProject.arrTasks.length-1]);this.posY=parseInt(c.cTaskItem[0].style.top)+this.ganttChart.heightTaskItem+this.ganttChart.heightTaskItemExtra}else this.posY=
parseInt(this.previousProject.projectItem[0].style.top)+this.ganttChart.heightTaskItem+this.ganttChart.heightTaskItemExtra;else this.posY=6;c=this.ganttChart.panelNames.firstChild;this.projectNameItem=this.createProjectNameItem();c.appendChild(this.projectNameItem);this.checkWidthProjectNameItem();this.projectItem=[this.createProjectItem(),[]];a.appendChild(this.projectItem[0]);a.appendChild(this.createDescrProject());this.adjustPanelTime()},getTaskById:function(a){for(var c=0;c<this.arrTasks.length;c++){var b=
this.searchTaskInTree(this.arrTasks[c],a);if(b)return b}return null},searchTaskInTree:function(a,c){if(a.taskItem.id==c)return a;else for(var b=0;b<a.childTask.length;b++){var d=a.childTask[b];if(d.taskItem.id==c)return d;else if(d.childTask.length>0&&(d=this.searchTaskInTree(d,c)))return d}return null},shiftProjectItem:function(){var a=null,c=null,b=parseInt(this.projectItem[0].style.left);parseInt(this.projectItem[0].firstChild.style.width);parseInt(this.projectItem[0].style.left);parseInt(this.projectItem[0].firstChild.style.width);
for(var d=0;d<this.arrTasks.length;d++){var i=this.arrTasks[d],e=parseInt(i.cTaskItem[0].style.left),i=parseInt(i.cTaskItem[0].style.left)+parseInt(i.cTaskItem[0].firstChild.firstChild.width);a||(a=e);c||(c=i);a>e&&(a=e);c<i&&(c=i)}if(a!=b)this.project.startDate=new Date(this.ganttChart.startDate),this.project.startDate.setHours(this.project.startDate.getHours()+a/this.ganttChart.pixelsPerHour);this.projectItem[0].style.left=a+"px";this.resizeProjectItem(c-a);this.duration=Math.round(parseInt(this.projectItem[0].firstChild.width)/
this.ganttChart.pixelsPerWorkHour);this.shiftDescrProject();this.adjustPanelTime()},adjustPanelTime:function(){var a=this.projectItem[0],a=parseInt(a.style.left)+parseInt(a.firstChild.style.width)+this.ganttChart.panelTimeExpandDelta;a+=this.descrProject.offsetWidth;this.ganttChart.adjustPanelTime(a)},resizeProjectItem:function(a){var c=this.percentage,b=this.projectItem[0];if(c>0&&c<100){b.firstChild.style.width=a+"px";b.firstChild.width=a+"px";b.style.width=a+"px";var d=b.firstChild.rows[0];d.cells[0].firstChild.style.width=
Math.round(a*c/100)+"px";d.cells[0].firstChild.style.height=this.ganttChart.heightTaskItem+"px";d.cells[1].firstChild.style.width=Math.round(a*(100-c)/100)+"px";d.cells[1].firstChild.style.height=this.ganttChart.heightTaskItem+"px";b.lastChild.firstChild.width=a+"px"}else if(c==0||c==100)b.firstChild.style.width=a+"px",b.firstChild.width=a+"px",b.style.width=a+"px",d=b.firstChild.rows[0],d.cells[0].firstChild.style.width=a+"px",d.cells[0].firstChild.style.height=this.ganttChart.heightTaskItem+"px",
b.lastChild.firstChild.width=a+"px"},shiftDescrProject:function(){this.descrProject.style.left=parseInt(this.projectItem[0].style.left)+this.duration*this.ganttChart.pixelsPerWorkHour+10+"px";this.descrProject.innerHTML=this.getDescStr()},showDescrProject:function(){this.descrProject.style.left=parseInt(this.projectItem[0].style.left)+this.duration*this.ganttChart.pixelsPerWorkHour+10+"px";this.descrProject.style.visibility="visible";this.descrProject.innerHTML=this.getDescStr()},hideDescrProject:function(){this.descrProject.style.visibility=
"hidden"},getDescStr:function(){return this.duration/this.ganttChart.hsPerDay+" days,  "+this.duration+" hours"},createDescrProject:function(){var a=this.posX+this.duration*this.ganttChart.pixelsPerWorkHour+10,c=dojo.create("div",{innerHTML:this.getDescStr(),className:"ganttDescProject"});dojo.style(c,{left:a+"px",top:this.posY+"px"});this.descrProject=c;if(this.project.parentTasks.length==0)this.descrProject.style.visibility="hidden";return c},createProjectItem:function(){this.percentage=this.getPercentCompleted();
this.duration=this.getDuration();var a=dojo.create("div",{id:this.project.id,className:"ganttProjectItem"});dojo.style(a,{left:this.posX+"px",top:this.posY+"px",width:this.duration*this.ganttChart.pixelsPerWorkHour+"px"});var c=dojo.create("table",{cellPadding:"0",cellSpacing:"0",className:"ganttTblProjectItem"},a),b=this.duration*this.ganttChart.pixelsPerWorkHour;c.width=(b==0?1:b)+"px";c.style.width=(b==0?1:b)+"px";c=c.insertRow(c.rows.length);if(this.percentage!=-1){if(this.percentage!=0)b=dojo.create("td",
{width:this.percentage+"%"},c),b.style.lineHeight="1px",b=dojo.create("div",{className:"ganttImageProgressFilled"},b),dojo.style(b,{width:this.percentage*this.duration*this.ganttChart.pixelsPerWorkHour/100+"px",height:this.ganttChart.heightTaskItem+"px"});if(this.percentage!=100)b=dojo.create("td",{width:100-this.percentage+"%"},c),b.style.lineHeight="1px",b=dojo.create("div",{className:"ganttImageProgressBg"},b),dojo.style(b,{width:(100-this.percentage)*this.duration*this.ganttChart.pixelsPerWorkHour/
100+"px",height:this.ganttChart.heightTaskItem+"px"})}else b=dojo.create("td",{width:"1px"},c),b.style.lineHeight="1px",b=dojo.create("div",{className:"ganttImageProgressBg"},b),dojo.style(b,{width:"1px",height:this.ganttChart.heightTaskItem+"px"});c=dojo.create("div",{className:"ganttDivTaskInfo"});b=dojo.create("table",{cellPadding:"0",cellSpacing:"0",height:this.ganttChart.heightTaskItem+"px",width:(this.duration*this.ganttChart.pixelsPerWorkHour==0?1:this.duration*this.ganttChart.pixelsPerWorkHour)+
"px"},c).insertRow(0);dojo.create("td",{align:"center",vAlign:"top",height:this.ganttChart.heightTaskItem+"px",className:"ganttMoveInfo"},b);a.appendChild(c);if(this.project.parentTasks.length==0)a.style.display="none";return a},createProjectNameItem:function(){var a=dojo.create("div",{className:"ganttProjectNameItem",innerHTML:this.project.name,title:this.project.name});dojo.style(a,{left:"5px",top:this.posY+"px"});dojo.attr(a,"tabIndex",0);this.ganttChart.isShowConMenu&&(this.ganttChart._events.push(dojo.connect(a,
"onmouseover",this,function(c){dojo.addClass(a,"ganttProjectNameItemHover");clearTimeout(this.ganttChart.menuTimer);this.ganttChart.tabMenu.clear();this.ganttChart.tabMenu.show(c.target,this)})),this.ganttChart._events.push(dojo.connect(a,"onkeydown",this,function(a){a.keyCode==dojo.keys.ENTER&&(this.ganttChart.tabMenu.clear(),this.ganttChart.tabMenu.show(a.target,this));this.ganttChart.tabMenu.isShow&&(a.keyCode==dojo.keys.LEFT_ARROW||a.keyCode==dojo.keys.RIGHT_ARROW)&&dijit.focus(this.ganttChart.tabMenu.menuPanel.firstChild.rows[0].cells[0]);
this.ganttChart.tabMenu.isShow&&a.keyCode==dojo.keys.ESCAPE&&this.ganttChart.tabMenu.hide()})),this.ganttChart._events.push(dojo.connect(a,"onmouseout",this,function(){dojo.removeClass(a,"ganttProjectNameItemHover");clearTimeout(this.ganttChart.menuTimer);this.ganttChart.menuTimer=setTimeout(dojo.hitch(this,function(){this.ganttChart.tabMenu.hide()}),200)})),this.ganttChart._events.push(dojo.connect(this.ganttChart.tabMenu.menuPanel,"onmouseover",this,function(){clearTimeout(this.ganttChart.menuTimer)})),
this.ganttChart._events.push(dojo.connect(this.ganttChart.tabMenu.menuPanel,"onkeydown",this,function(a){this.ganttChart.tabMenu.isShow&&a.keyCode==dojo.keys.ESCAPE&&this.ganttChart.tabMenu.hide()})),this.ganttChart._events.push(dojo.connect(this.ganttChart.tabMenu.menuPanel,"onmouseout",this,function(){clearTimeout(this.ganttChart.menuTimer);this.ganttChart.menuTimer=setTimeout(dojo.hitch(this,function(){this.ganttChart.tabMenu.hide()}),200)})));return a},getPercentCompleted:function(){var a=0;dojo.forEach(this.project.parentTasks,
function(c){a+=parseInt(c.percentage)},this);return this.project.parentTasks.length!=0?Math.round(a/this.project.parentTasks.length):-1},getDuration:function(){var a=0,c=0;return this.project.parentTasks.length>0?(dojo.forEach(this.project.parentTasks,function(b){c=b.duration*24/this.ganttChart.hsPerDay+(b.startTime-this.ganttChart.startDate)/36E5;c>a&&(a=c)},this),(a-this.posX)/24*this.ganttChart.hsPerDay):0},deleteTask:function(a){if(a=this.getTaskById(a))this.deleteChildTask(a),this.ganttChart.checkPosition()},
setName:function(a){if(a)this.project.name=a,this.projectNameItem.innerHTML=a,this.projectNameItem.title=a,this.checkWidthProjectNameItem(),this.descrProject.innerHTML=this.getDescStr(),this.adjustPanelTime()},setPercentCompleted:function(a){a=parseInt(a);if(isNaN(a)||a>100||a<0)return!1;var c=this.projectItem[0].firstChild.rows[0],b=c.cells[0],d=c.cells[1];if(a>0&&a<100&&this.percentage>0&&this.percentage<100)b.width=parseInt(a)+"%",b.firstChild.style.width=a*this.duration*this.ganttChart.pixelsPerWorkHour/
100+"px",d.width=100-parseInt(a)+"%",d.firstChild.style.width=(100-a)*this.duration*this.ganttChart.pixelsPerWorkHour/100+"px";else if((a==0||a==100)&&this.percentage>0&&this.percentage<100)if(a==0)b.parentNode.removeChild(b),d.width="100%",d.firstChild.style.width=this.duration*this.ganttChart.pixelsPerWorkHour+"px";else{if(a==100)d.parentNode.removeChild(d),b.width="100%",b.firstChild.style.width=this.duration*this.ganttChart.pixelsPerWorkHour+"px"}else if((a==0||a==100)&&(this.percentage==0||this.percentage==
100))a==0&&this.percentage==100?(dojo.removeClass(b.firstChild,"ganttImageProgressFilled"),dojo.addClass(b.firstChild,"ganttImageProgressBg")):a==100&&this.percentage==0&&(dojo.removeClass(b.firstChild,"ganttImageProgressBg"),dojo.addClass(b.firstChild,"ganttImageProgressFilled"));else if((a>0||a<100)&&(this.percentage==0||this.percentage==100))b.parentNode.removeChild(b),b=dojo.create("td",{width:a+"%"},c),b.style.lineHeight="1px",b=dojo.create("div",{className:"ganttImageProgressFilled"},b),dojo.style(b,
{width:a*this.duration*this.ganttChart.pixelsPerWorkHour/100+"px",height:this.ganttChart.heightTaskItem+"px"}),b=dojo.create("td",{width:100-a+"%"},c),b.style.lineHeight="1px",b=dojo.create("div",{className:"ganttImageProgressBg"},b),dojo.style(b,{width:(100-a)*this.duration*this.ganttChart.pixelsPerWorkHour/100+"px",height:this.ganttChart.heightTaskItem+"px"});else if(this.percentage==-1)if(a==100)dojo.removeClass(b.firstChild,"ganttImageProgressBg"),dojo.addClass(b.firstChild,"ganttImageProgressFilled");
else if(a<100&&a>0)b.parentNode.removeChild(b),b=dojo.create("td",{width:a+"%"},c),b.style.lineHeight="1px",b=dojo.create("div",{className:"ganttImageProgressFilled"},b),dojo.style(b,{width:a*this.duration*this.ganttChart.pixelsPerWorkHour/100+"px",height:this.ganttChart.heightTaskItem+"px"}),b=dojo.create("td",{width:100-a+"%"},c),b.style.lineHeight="1px",b=dojo.create("div",{className:"ganttImageProgressBg"},b),dojo.style(b,{width:(100-a)*this.duration*this.ganttChart.pixelsPerWorkHour/100+"px",
height:this.ganttChart.heightTaskItem+"px"});this.percentage=a;this.descrProject.innerHTML=this.getDescStr();return!0},deleteChildTask:function(a){if(a){var c=a.cTaskItem[0],b=a.cTaskNameItem[0],d=a.cTaskItem[1],i=a.cTaskNameItem[1],e=a.cTaskNameItem[2];c.style.display=="none"&&this.ganttChart.openTree(a.parentTask);if(a.childPredTask.length>0)for(var f=0;f<a.childPredTask.length;f++){for(var j=a.childPredTask[f],g=0;g<j.cTaskItem[1].length;g++)j.cTaskItem[1][g].parentNode.removeChild(j.cTaskItem[1][g]);
j.cTaskItem[1]=[];j.predTask=null}if(a.childTask.length>0)for(;a.childTask.length>0;)this.deleteChildTask(a.childTask[0]);f=this.ganttChart.heightTaskItem+this.ganttChart.heightTaskItemExtra;c.style.display!="none"&&a.shiftCurrentTasks(a,-f);this.project.deleteTask(a.taskItem.id);c&&c.parentNode.removeChild(c);a.descrTask.parentNode.removeChild(a.descrTask);if(d.length>0)for(f=0;f<d.length;f++)d[f].parentNode.removeChild(d[f]);b&&b.parentNode.removeChild(b);if(a.cTaskNameItem[1])for(f=0;f<i.length;f++)i[f].parentNode.removeChild(i[f]);
e&&e.parentNode&&e.parentNode.removeChild(e);if(a.taskIdentifier)a.taskIdentifier.parentNode.removeChild(a.taskIdentifier),a.taskIdentifier=null;if(a.parentTask){if(a.previousChildTask)a.previousChildTask.nextChildTask=a.nextChildTask?a.nextChildTask:null;b=a.parentTask;for(f=0;f<b.childTask.length;f++)if(b.childTask[f].taskItem.id==a.taskItem.id){b.childTask[f]=null;b.childTask.splice(f,1);break}b.childTask.length==0&&b.cTaskNameItem[2]&&(b.cTaskNameItem[2].parentNode.removeChild(b.cTaskNameItem[2]),
b.cTaskNameItem[2]=null)}else{if(a.previousParentTask)a.previousParentTask.nextParentTask=a.nextParentTask?a.nextParentTask:null;b=a.project;for(f=0;f<b.arrTasks.length;f++)b.arrTasks[f].taskItem.id==a.taskItem.id&&b.arrTasks.splice(f,1)}if(a.predTask){b=a.predTask;for(f=0;f<b.childPredTask.length;f++)b.childPredTask[f].taskItem.id==a.taskItem.id&&(b.childPredTask[f]=null,b.childPredTask.splice(f,1))}a.project.arrTasks.length!=0?a.project.shiftProjectItem():(a.project.projectItem[0].style.display=
"none",this.hideDescrProject());this.ganttChart.contentDataHeight-=this.ganttChart.heightTaskItemExtra+this.ganttChart.heightTaskItem}},insertTask:function(a,c,b,d,i,e,f,j){var g=null,h=null;if(this.project.getTaskById(a))return!1;if(!d||d<this.ganttChart.minWorkLength)d=this.ganttChart.minWorkLength;if(!c||c=="")c=a;if(!i||i=="")i=0;else if(i=parseInt(i),i<0||i>100)return!1;if(j&&j!=""){h=this.project.getTaskById(j);if(!h)return!1;b=b||h.startTime;if(b<h.startTime)return!1;g=new dojox.gantt.GanttTaskItem({id:a,
name:c,startTime:b,duration:d,percentage:i,previousTaskId:e,taskOwner:f});if(!this.ganttChart.checkPosParentTask(h,g))return!1;g.parentTask=h;a=this.getTaskById(h.id);c=!1;a.cTaskItem[0].style.display=="none"?c=!0:a.cTaskNameItem[2]&&(a.isExpanded||(c=!0));c&&(a.childTask.length==0?this.ganttChart.openTree(a.parentTask):this.ganttChart.openTree(a));if(e!=""){e=this.project.getTaskById(e);if(!e)return!1;if(e.parentTask){if(e.parentTask.id!=g.parentTask.id)return!1}else return!1;this.ganttChart.checkPosPreviousTask(e,
g)||this.ganttChart.correctPosPreviousTask(e,g);g.previousTask=e}if(h.cldTasks.length>0)h.cldTasks[h.cldTasks.length-1].nextChildTask=g,g.previousChildTask=h.cldTasks[h.cldTasks.length-1];h.cldTasks.push(g);h.cldTasks.length==1&&(e=a.createTreeImg(),a.cTaskNameItem[2]=e);h=new dojox.gantt.GanttTaskControl(g,this,this.ganttChart);h.create();if(g.nextChildTask)h.nextChildTask=h.project.getTaskById(g.nextChildTask.id);h.adjustPanelTime();g=this.ganttChart.heightTaskItem+this.ganttChart.heightTaskItemExtra;
h.shiftCurrentTasks(h,g)}else{b=b||this.project.startDate;g=new dojox.gantt.GanttTaskItem({id:a,name:c,startTime:b,duration:d,percentage:i,previousTaskId:e,taskOwner:f});if(g.startTime<=this.ganttChart.startDate)return!1;if(e!=""){e=this.project.getTaskById(e);if(!e)return!1;this.ganttChart.checkPosPreviousTask(e,g)||this.ganttChart.correctPosPreviousTask(e,g);if(e.parentTask)return!1;g.previousTask=e}if(this.project.parentTasks.length>0)this.project.parentTasks[this.project.parentTasks.length-1].nextParentTask=
g,g.previousParentTask=this.project.parentTasks[this.project.parentTasks.length-1];this.project.parentTasks.push(g);h=new dojox.gantt.GanttTaskControl(g,this,this.ganttChart);h.create();if(g.nextParentTask)h.nextParentTask=h.project.getTaskById(g.nextParentTask.id);h.adjustPanelTime();this.arrTasks.push(h);g=this.ganttChart.heightTaskItem+this.ganttChart.heightTaskItemExtra;h.shiftCurrentTasks(h,g);this.projectItem[0].style.display="inline";this.setPercentCompleted(this.getPercentCompleted());this.shiftProjectItem();
this.showDescrProject()}this.ganttChart.checkHeighPanelTasks();this.ganttChart.checkPosition();return h},shiftNextProject:function(a,c){a.nextProject&&(a.nextProject.shiftProject(c),this.shiftNextProject(a.nextProject,c))},shiftProject:function(a){this.posY+=a;this.projectItem[0].style.top=parseInt(this.projectItem[0].style.top)+a+"px";this.descrProject.style.top=parseInt(this.descrProject.style.top)+a+"px";this.projectNameItem.style.top=parseInt(this.projectNameItem.style.top)+a+"px";this.arrTasks.length>
0&&this.shiftNextParentTask(this.arrTasks[0],a)},shiftTask:function(a,c){a.posY+=c;var b=a.cTaskNameItem[0],d=a.cTaskNameItem[1],i=a.cTaskNameItem[2],e=a.cTaskItem[1];b.style.top=parseInt(b.style.top)+c+"px";if(i)i.style.top=parseInt(i.style.top)+c+"px";if(a.parentTask)d[0].style.top=parseInt(d[0].style.top)+c+"px",d[1].style.top=parseInt(d[1].style.top)+c+"px";a.cTaskItem[0].style.top=parseInt(a.cTaskItem[0].style.top)+c+"px";a.descrTask.style.top=parseInt(a.descrTask.style.top)+c+"px";if(e[0])e[0].style.top=
parseInt(e[0].style.top)+c+"px",e[1].style.top=parseInt(e[1].style.top)+c+"px",e[2].style.top=parseInt(e[2].style.top)+c+"px"},shiftNextParentTask:function(a,c){this.shiftTask(a,c);this.shiftChildTasks(a,c);a.nextParentTask&&this.shiftNextParentTask(a.nextParentTask,c)},shiftChildTasks:function(a,c){dojo.forEach(a.childTask,function(a){this.shiftTask(a,c);a.childTask.length>0&&this.shiftChildTasks(a,c)},this)}}),dojo.declare("dojox.gantt.GanttProjectItem",null,{constructor:function(a){this.id=a.id;
this.name=a.name||this.id;this.startDate=a.startDate||new Date;this.parentTasks=[]},getTaskById:function(a){for(var c=0;c<this.parentTasks.length;c++){var b=this.getTaskByIdInTree(this.parentTasks[c],a);if(b)return b}return null},getTaskByIdInTree:function(a,c){if(a.id==c)return a;else for(var b=0;b<a.cldTasks.length;b++){var d=a.cldTasks[b];if(d.id==c)return d;if(d.cldTasks.length>0&&d.cldTasks.length>0&&(d=this.getTaskByIdInTree(d,c)))return d}return null},addTask:function(a){this.parentTasks.push(a);
a.setProject(this)},deleteTask:function(a){var c=this.getTaskById(a);if(c)if(c.parentTask)for(var b=c.parentTask,c=0;c<b.cldTasks.length;c++){var d=b.cldTasks[c];if(d.id==a){if(d.nextChildTask)d.previousChildTask?(d.previousChildTask.nextChildTask=d.nextChildTask,d.nextChildTask.previousChildTask=d.previousChildTask):d.nextChildTask.previousChildTask=null;else if(d.previousChildTask)d.previousChildTask.nextChildTask=null;b.cldTasks.splice(c,1);break}}else for(c=0;c<this.parentTasks.length;c++)if(b=
this.parentTasks[c],b.id==a){if(b.nextParentTask)b.previousParentTask?(b.previousParentTask.nextParentTask=b.nextParentTask,b.nextParentTask.previousParentTask=b.previousParentTask):b.nextParentTask.previousParentTask=null;else if(b.previousParentTask)b.previousParentTask.nextParentTask=null;this.parentTasks.splice(c,1);break}}}));