/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gantt.GanttResourceItem"]||(dojo._hasResource["dojox.gantt.GanttResourceItem"]=!0,dojo.provide("dojox.gantt.GanttResourceItem"),dojo.require("dojo.date.locale"),dojo.declare("dojox.gantt.GanttResourceItem",null,{constructor:function(a){this.ganttChart=a;this.ownerItem=[];this.ownerNameItem=[];this.ownerTaskNodeMapping={};this.ownerTaskNodeMapping_time={};this.resourceInfo={};this.ownerTimeConsume={}},clearAll:function(){this.clearData();this.clearItems()},clearData:function(){this.ownerItem=
[];this.ownerNameItem=[];this.ownerTaskNodeMapping={};this.ownerTaskNodeMapping_time={};this.resourceInfo={};this.ownerTimeConsume={}},clearItems:function(){dojo.destroy(this.content.firstChild)},buildResource:function(){var a={};dojo.forEach(this.ganttChart.arrProjects,function(b){dojo.forEach(b.arrTasks,function(b){b.buildResourceInfo(a)},this)},this);return a},buildOwnerTimeConsume:function(){var a={},b;for(b in this.resourceInfo){for(var c=this.resourceInfo[b],d={},e=0;e<c.length;e++){var f=c[e],
g=f.taskItem.startTime.getTime(),f=f.taskItem.duration*864E5/this.ganttChart.hsPerDay;d.min=d.min?Math.min(d.min,g):g;d.max=d.max?Math.max(d.max,g+f):g+f}d.dur=(d.max-d.min)*this.ganttChart.hsPerDay/864E5;d.min=new Date(d.min);d.max=new Date(d.max);a[b]=d}return a},refresh:function(){this.ownerTimeConsume=this.buildOwnerTimeConsume();this.contentData.firstChild.style.width=Math.max(1200,this.ganttChart.pixelsPerDay*this.ganttChart.totalDays)+"px";for(var a in this.resourceInfo)this.refreshOwnerEntry(a)},
reConstruct:function(){this.clearAll();this.resourceInfo=this.buildResource();this.ownerTimeConsume=this.buildOwnerTimeConsume();this.tableControl=dojo.create("table",{cellPadding:"0",cellSpacing:"0",className:"ganttResourceTableControl"});var a=this.tableControl.insertRow(this.tableControl.rows.length);this.contentHeight=this.content.offsetHeight;this.contentWidth=this.content.offsetWidth;this.content.appendChild(this.tableControl);this.contentData=dojo.create("div",{className:"ganttResourceContentDataContainer"});
this.contentData.appendChild(this.createPanelOwners());dojo.style(this.contentData,"height",this.contentHeight-this.ganttChart.panelTimeHeight+"px");var b=dojo.create("td",{vAlign:"top"});this.panelNames=dojo.create("div",{className:"ganttResourcePanelNames"});this.panelNames.appendChild(this.createPanelNamesOwners());b.appendChild(this.panelNames);a.appendChild(b);var b=dojo.create("td",{vAlign:"top"}),c=dojo.create("div",{className:"ganttResourceDivCell"});c.appendChild(this.contentData);b.appendChild(c);
a.appendChild(b);dojo.style(this.panelNames,{height:this.contentHeight-this.ganttChart.panelTimeHeight-this.ganttChart.scrollBarWidth+"px",width:this.ganttChart.maxWidthPanelNames+"px"});this.contentData.style.width=this.contentWidth-this.ganttChart.maxWidthPanelNames+"px";this.contentData.firstChild.style.width=this.ganttChart.pixelsPerDay*this.ganttChart.panelTime.firstChild.firstChild.rows[3].cells.length+"px";var d=this;this.contentData.onscroll=function(){if(d.panelNames)d.panelNames.scrollTop=
this.scrollTop};this.contentData.scrollLeft=this.ganttChart.contentData.scrollLeft;for(var e in this.resourceInfo)this.createOwnerEntry(e);this.postAdjustment()},create:function(){var a=dojo.create("div",{innerHTML:"Resource Chart:",className:"ganttResourceHeader"},this.ganttChart.content,"after");dojo.style(a,"width",this.ganttChart.contentWidth+"px");a=dojo.create("div",{className:"ganttResourceContent"},a,"after");dojo.style(a,{width:this.ganttChart.contentWidth+"px",height:(this.ganttChart.resourceChartHeight||
this.ganttChart.contentHeight*0.8)+"px"});this.content=a||this.content;this.reConstruct()},postAdjustment:function(){this.contentData.firstChild.style.height=this.ownerItem.length*23+"px";this.panelNames.firstChild.style.height=this.ownerItem.length*23+"px"},refreshOwnerEntry:function(a){this.refreshOwnerItem(a);dojo.forEach(this.resourceInfo[a],function(b,c){this.refreshDetailedTaskEntry(a,this.ownerTaskNodeMapping[a].tasks[c][0],b)},this)},createOwnerEntry:function(a){var b=this.contentData.firstChild,
c=this.ownerItem[this.ownerItem.length-1];this.ownerTaskNodeMapping[a]={};this.ownerTaskNodeMapping[a][a]=[];dojo.position(b);var c=(c?parseInt(c.style.top):-17)+this.ganttChart.heightTaskItem+11,d=this.createOwnerItem(a,c);b.appendChild(d);this.ownerItem.push(d);this.ownerTaskNodeMapping[a][a].push(d);this.panelNames&&(b=this.createOwnerNameItem(a,c),this.panelNames.firstChild.appendChild(b),this.ownerNameItem.push(b),this.ownerTaskNodeMapping[a][a].push(b));var e=this.ownerNameItem[this.ownerNameItem.length-
1];this.panelNames&&(this.checkWidthTaskNameItem(e),b=this.createTreeImg(e),this.panelNames.firstChild.appendChild(b),this.ownerTaskNodeMapping[a][a].push(b));this.ownerTaskNodeMapping[a].taskCount=this.resourceInfo[a].length;this.ownerTaskNodeMapping[a].isOpen=!1;this.ownerTaskNodeMapping[a].tasks=[];dojo.forEach(this.resourceInfo[a],function(b){this.ownerTaskNodeMapping[a].tasks.push(this.createDetailedTaskEntry(a,e,b))},this);return this},createOwnerNameItem:function(a,b){var c=dojo.create("div",
{id:a,title:a,innerHTML:a,className:"ganttOwnerNameItem"});dojo.style(c,"top",b+"px");return c},refreshOwnerItem:function(a){var b=this.ownerTaskNodeMapping[a][a][0],c=this.ownerTimeConsume[a].dur,d=this.ganttChart.getPosOnDate(this.ownerTimeConsume[a].min);b.style.left=d+"px";b.style.width=c*this.ganttChart.pixelsPerWorkHour+"px";dojo.forEach(this.resourceInfo[a],function(a,c){var g=this.ganttChart.getPosOnDate(a.taskItem.startTime);dojo.style(b.childNodes[c],{left:g-d+"px",width:a.taskItem.duration*
this.ganttChart.pixelsPerWorkHour+"px"})},this)},createOwnerItem:function(a,b){var c=this.ownerTimeConsume[a].dur,d=this.ganttChart.getPosOnDate(this.ownerTimeConsume[a].min),e=dojo.create("div",{id:a,owner:!0,className:"ganttOwnerBar"});dojo.style(e,{left:d+"px",top:b+"px",width:c*this.ganttChart.pixelsPerWorkHour+"px",height:this.ganttChart.heightTaskItem+"px"});dojo.forEach(this.resourceInfo[a],function(b){var c=dojo.create("div",{id:a,className:"ganttOwnerTaskBar"},e),h=this.ganttChart.getPosOnDate(b.taskItem.startTime);
dojo.style(c,{left:h-d+"px",width:b.taskItem.duration*this.ganttChart.pixelsPerWorkHour+"px",height:this.ganttChart.heightTaskItem+"px"})},this);return e},refreshDetailedTaskEntry:function(a,b,c){this.refreshTaskItem(b,c)},createDetailedTaskEntry:function(a,b,c){var a=[],d=this.contentData.firstChild,e=parseInt(b.style.top),f=this.createTaskItem(c,e);f.style.display="none";d.appendChild(f);this.ownerItem.push(f);a.push(f);if(this.panelNames)c=this.createTaskNameItem(c.taskItem.name,e),this.panelNames.firstChild.appendChild(c),
c.style.display="none",this.ownerNameItem.push(c),a.push(c);if(this.panelNames)this.ownerNameItem[this.ownerNameItem.length-1].style.left=dojo.style(b,"left")+15+"px",b=this.createConnectingLinesPN(b,this.ownerNameItem[this.ownerNameItem.length-1]),dojo.forEach(b,function(a){a.style.display="none"},this),a.push({v:b[0],h:b[1]}),this.checkWidthTaskNameItem(this.ownerNameItem[this.ownerNameItem.length-1]);return a},createTaskNameItem:function(a,b){var c=dojo.create("div",{id:a,className:"ganttTaskNameItem",
title:a,innerHTML:a});dojo.style(c,"top",b+"px");return c},refreshTaskItem:function(a,b){var c=this.ganttChart.getPosOnDate(b.taskItem.startTime);dojo.style(a,{left:c+"px",width:b.taskItem.duration*this.ganttChart.pixelsPerWorkHour+"px"})},createTaskItem:function(a,b){var c=this.ganttChart.getPosOnDate(a.taskItem.startTime),d=dojo.create("div",{id:a.taskItem.name,className:"ganttTaskBar"});dojo.style(d,{left:c+"px",top:b+"px",width:a.taskItem.duration*this.ganttChart.pixelsPerWorkHour+"px",height:this.ganttChart.heightTaskItem+
"px"});return d},createConnectingLinesPN:function(a,b){var c=[],d=dojo.create("div",{innerHTML:"&nbsp;",className:"ganttResourceLineVerticalLeft"},this.panelNames.firstChild);d.cNode=b;d.pNode=a;var e=dojo.create("div",{noShade:!0,color:"#000000",className:"ganttResourceLineHorizontalLeft"},this.panelNames.firstChild);e.cNode=b;e.pNode=a;this.panelNames.firstChild.appendChild(e);c.push(d);c.push(e);return c},createTreeImg:function(a){var b=dojo.create("div",{id:a.id,className:"ganttImageTreeExpand"});
dojo.attr(b,"tabIndex",0);var c=this.ownerTaskNodeMapping[a.id];dojo.forEach(["onclick","onkeydown"],function(d){this.ganttChart._events.push(dojo.connect(b,d,this,function(e){if(!(d=="onkeydown"&&e.keyCode!=dojo.keys.ENTER))if(c.isOpen){dojo.removeClass(b,"ganttImageTreeCollapse");dojo.addClass(b,"ganttImageTreeExpand");var e=c.isOpen=!1,f;for(f in this.ownerTaskNodeMapping){var g=this.ownerTaskNodeMapping[f];e?(dojo.forEach(g[f],function(a){dojo.style(a,"top",dojo.style(a,"top")-c.taskCount*23+
"px")},this),dojo.forEach(g.tasks,function(a){dojo.forEach(a,function(a){dojo.forEach(!a.v&&!a.h?[a]:[a.v,a.h],function(a){dojo.style(a,"top",dojo.style(a,"top")-c.taskCount*23+"px")},this)},this)},this)):f==a.id&&(e=!0,dojo.forEach(g.tasks,function(a){dojo.forEach(a,function(a){this.styleOwnerItem(a,g[f][0],"none",0)},this)},this))}}else for(f in dojo.removeClass(b,"ganttImageTreeExpand"),dojo.addClass(b,"ganttImageTreeCollapse"),c.isOpen=!0,e=!1,this.ownerTaskNodeMapping)g=this.ownerTaskNodeMapping[f],
e?(dojo.forEach(g[f],function(a){dojo.style(a,"top",dojo.style(a,"top")+c.taskCount*23+"px")},this),dojo.forEach(g.tasks,function(a){dojo.forEach(a,function(a){dojo.forEach(!a.v&&!a.h?[a]:[a.v,a.h],function(a){dojo.style(a,"top",dojo.style(a,"top")+c.taskCount*23+"px")},this)},this)},this)):f==a.id&&(e=!0,dojo.forEach(g.tasks,function(a,b){dojo.forEach(a,function(a){this.styleOwnerItem(a,g[f][0],"inline",(b+1)*23)},this)},this))}))},this);dojo.addClass(b,"ganttResourceTreeImage");dojo.style(b,{left:dojo.style(a,
"left")-12+"px",top:dojo.style(a,"top")+3+"px"});return b},styleOwnerItem:function(a,b,c,d){a.v||a.h?(dojo.style(a.v,{height:Math.max(1,a.v.cNode.offsetTop-a.v.pNode.offsetTop)+"px",top:a.v.pNode.offsetTop+5+"px",left:a.v.pNode.offsetLeft-9+"px",display:c}),dojo.style(a.h,{width:Math.max(1,a.h.cNode.offsetLeft-a.h.pNode.offsetLeft+4)+"px",top:a.h.cNode.offsetTop+5+"px",left:a.h.pNode.offsetLeft-9+"px",display:c})):dojo.style(a,{display:c,top:parseInt(b.style.top)+d+"px"})},checkWidthTaskNameItem:function(a){if(a&&
a.offsetWidth+a.offsetLeft>this.ganttChart.maxWidthPanelNames){var b=a.id.substring(0,a.firstChild.length-Math.round((a.offsetWidth+a.offsetLeft-this.ganttChart.maxWidthPanelNames)/(a.offsetWidth/a.firstChild.length))-3);b+="...";a.innerHTML=b}},createPanelOwners:function(){var a=dojo.create("div",{className:"ganttOwnerPanel"});dojo.style(a,{height:this.contentHeight-this.ganttChart.panelTimeHeight-this.ganttChart.scrollBarWidth+"px"});return a},createPanelNamesOwners:function(){var a=dojo.create("div",
{innerHTML:"&nbsp;",className:"ganttResourcePanelNamesOwners"});dojo.style(a,{height:this.contentHeight-this.ganttChart.panelTimeHeight-this.ganttChart.scrollBarWidth+"px",width:this.ganttChart.maxWidthPanelNames+"px"});return a}}));