/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gantt.GanttChart"]||(dojo._hasResource["dojox.gantt.GanttChart"]=!0,dojo.provide("dojox.gantt.GanttChart"),dojo.require("dijit.Tooltip"),dojo.require("dojox.gantt.GanttProjectItem"),dojo.require("dojox.gantt.GanttResourceItem"),dojo.require("dojox.gantt.TabMenu"),dojo.require("dojo.date.locale"),function(){dojo.declare("dojox.gantt.GanttChart",null,{constructor:function(b,a){this.resourceChartHeight=b.resourceChartHeight!==void 0?b.resourceChartHeight:!1;this.withResource=
b.withResource!==void 0?b.withResource:!0;this.correctError=b.autoCorrectError!==void 0?b.autoCorrectError:!1;this.isShowConMenu=this.isContentEditable=!b.readOnly;this.withTaskId=b.withTaskId!==void 0?b.withTaskId:!b.readOnly;this.animation=b.animation!==void 0?b.animation:!0;this.saveProgramPath=b.saveProgramPath||"saveGanttData.php";this.dataFilePath=b.dataFilePath||"gantt_default.json";this.contentHeight=b.height||400;this.contentWidth=b.width||600;this.content=dojo.byId(a);this.scrollBarWidth=
18;this.panelTimeHeight=102;this.maxWidthTaskNames=this.maxWidthPanelNames=150;this.minWorkLength=8;this.heightTaskItem=12;this.heightTaskItemExtra=11;this.pixelsPerDay=24;this.hsPerDay=8;this.pixelsPerWorkHour=this.pixelsPerDay/this.hsPerDay;this.pixelsPerHour=this.pixelsPerDay/24;this.totalDays=this.countDays=0;this.startDate=null;this.contentDataHeight=this.initialPos=0;this.panelTimeExpandDelta=20;this.tabMenu=this.contentData=this.panelTime=this.panelNames=this.divTimeInfo=null;this.project=
[];this.arrProjects=[];this.xmlLoader=null;this.isResizing=this.isMoving=!1;this.animationNodes=[];this.scale=1;this.tempDayInPixels=0;this.resource=null;this.months=dojo.date.locale.getNames("months","wide");this._events=[]},getProject:function(b){return dojo.filter(this.arrProjects,function(a){return a.project.id==b},this)[0]},checkPosPreviousTask:function(b,a){var c=this.getWidthOnDuration(b.duration),d=this.getPosOnDate(b.startTime),e=this.getPosOnDate(a.startTime);return c+d>e?!1:!0},correctPosPreviousTask:function(b,
a,c){var d=new Date(b.startTime);d.setHours(d.getHours()+b.duration/this.hsPerDay*24);d.getHours()>0&&(d.setHours(0),d.setDate(d.getDate()+1));c?c.setStartTime(d,!0):a.startTime=d;if(a.parentTask&&!this.checkPosParentTask(a.parentTask,a))b=new Date(a.parentTask.startTime),b.setHours(b.getHours()+a.parentTask.duration/this.hsPerDay*24),a.duration=parseInt(parseInt((b-a.startTime)/36E5)*this.hsPerDay/24)},correctPosParentTask:function(b,a){if(a.previousTask)this.correctPosPreviousTask(a.previousTask,
a);else{if(b.startTime>a.startTime)a.startTime=new Date(b.startTime);if(!this.checkPosParentTask(b,a))a.duration=b.duration}},checkPosParentTaskInTree:function(b){for(var a=!1,c=0;c<b.cldTasks.length;c++){var d=b.cldTasks[c];if(!this.checkPosParentTask(b,d))if(this.correctError)this.correctPosParentTask(b,d);else return!0;if(b.startTime>d.startTime)if(this.correctError)this.correctPosParentTask(b,d);else return!0;d.cldTasks.length>0&&(a=this.checkPosParentTaskInTree(d))}return a},setPreviousTask:function(b){for(var a=
!1,c=0;c<b.parentTasks.length;c++){a=b.parentTasks[c];if(a.previousTaskId){a.previousTask=b.getTaskById(a.previousTaskId);if(!a.previousTask&&!this.correctError)return!0;a.previousTask.cldPreTasks.push(a)}if(a.previousTask&&!this.checkPosPreviousTask(a.previousTask,a))if(this.correctError)this.correctPosPreviousTask(a.previousTask,a);else return!0;a=this.setPreviousTaskInTree(a)}return a},setPreviousTaskInTree:function(b){for(var a=!1,c=0;c<b.cldTasks.length;c++){var d=b.cldTasks[c];if(d.previousTaskId){d.previousTask=
b.project.getTaskById(d.previousTaskId);if(!d.previousTask&&!this.correctError)return!0;if(!this.checkPosPreviousTask(d.previousTask,d))if(this.correctError)this.correctPosPreviousTask(d.previousTask,d);else return!0;d.previousTask.cldPreTasks.push(d)}d.cldTasks.length>0&&(a=this.setPreviousTaskInTree(d))}return a},checkPosParentTask:function(b,a){var c=this.getWidthOnDuration(b.duration),d=this.getPosOnDate(b.startTime),e=this.getPosOnDate(a.startTime),f=this.getWidthOnDuration(a.duration);return c+
d>=e+f},addProject:function(b){this.project.push(b)},deleteProject:function(b){var a=this.getProject(b);if(a){if(a.arrTasks.length>0)for(;a.arrTasks.length>0;)a.deleteChildTask(a.arrTasks[0]);var c=this.heightTaskItemExtra+this.heightTaskItem;a.nextProject&&a.shiftNextProject(a,-c);this.project=dojo.filter(this.project,function(b){return b.id!=a.project.id},this);if(a.previousProject&&a.nextProject)c=a.previousProject,c.nextProject=a.nextProject;if(a.previousProject&&!a.nextProject)c=a.previousProject,
c.nextProject=null;if(!a.previousProject&&a.nextProject)a.nextProject.previousProject=null;for(c=0;c<this.arrProjects.length;c++)this.arrProjects[c].project.id==b&&this.arrProjects.splice(c,1);a.projectItem[0].parentNode.removeChild(a.projectItem[0]);a.descrProject.parentNode.removeChild(a.descrProject);a.projectNameItem.parentNode.removeChild(a.projectNameItem);this.contentDataHeight-=this.heightTaskItemExtra+this.heightTaskItem;this.project.length==0&&(b=new Date(this.startDate),b=new Date(b.setDate(b.getDate()+
1)),b=new dojox.gantt.GanttProjectItem({id:1,name:"New Project",startDate:b}),this.project.push(b),a=new dojox.gantt.GanttProjectControl(this,b),a.create(),this.arrProjects.push(a),this.contentDataHeight+=this.heightTaskItemExtra+this.heightTaskItem);this.checkPosition()}},insertProject:function(b,a,c){if(this.startDate>=c)return!1;if(this.getProject(b))return!1;this.checkHeighPanelTasks();b=new dojox.gantt.GanttProjectItem({id:b,name:a,startDate:c});this.project.push(b);b=new dojox.gantt.GanttProjectControl(this,
b);for(a=0;a<this.arrProjects.length;a++){var d=this.arrProjects[a-1],e=this.arrProjects[a+1];if(c<this.arrProjects[a].project.startDate){this.arrProjects.splice(a,0,b);if(a>0)b.previousProject=d,d.nextProject=b;if(a+1<=this.arrProjects.length)b.nextProject=e,e.previousProject=b,b.shiftNextProject(b,this.heightTaskItem+this.heightTaskItemExtra);b.create();b.hideDescrProject();this.checkPosition();return b}}if(this.arrProjects.length>0)this.arrProjects[this.arrProjects.length-1].nextProject=b,b.previousProject=
this.arrProjects[this.arrProjects.length-1];this.arrProjects.push(b);b.create();b.hideDescrProject();this.checkPosition();return b},openTree:function(b){var a=this.getLastCloseParent(b);this.openNode(a);b.taskItem.id!=a.taskItem.id&&this.openTree(b)},openNode:function(b){if(!b.isExpanded)dojo.removeClass(b.cTaskNameItem[2],"ganttImageTreeExpand"),dojo.addClass(b.cTaskNameItem[2],"ganttImageTreeCollapse"),b.isExpanded=!0,b.shiftCurrentTasks(b,b.hideTasksHeight),b.showChildTasks(b,b.isExpanded),b.hideTasksHeight=
0},getLastCloseParent:function(b){return b.parentTask?!b.parentTask.isExpanded||b.parentTask.cTaskNameItem[2].style.display=="none"?this.getLastCloseParent(b.parentTask):b:b},getProjectItemById:function(b){return dojo.filter(this.project,function(a){return a.id==b},this)[0]},clearAll:function(){this.contentDataHeight=0;this.startDate=null;this.clearData();this.clearItems();this.clearEvents()},clearEvents:function(){dojo.forEach(this._events,dojo.disconnect);this._events=[]},clearData:function(){this.project=
[];this.arrProjects=[]},clearItems:function(){this.contentData.removeChild(this.contentData.firstChild);this.contentData.appendChild(this.createPanelTasks());this.panelNames.removeChild(this.panelNames.firstChild);this.panelNames.appendChild(this.createPanelNamesTasks());this.panelTime.removeChild(this.panelTime.firstChild)},buildUIContent:function(){this.project.sort(this.sortProjStartDate);this.startDate=this.getStartDate();this.panelTime.appendChild(this.createPanelTime());for(var b=0;b<this.project.length;b++){for(var a=
this.project[b],c=0;c<a.parentTasks.length;c++){var d=a.parentTasks[c];if(d.startTime)this.setStartTimeChild(d);else return;if(this.setPreviousTask(a))return}for(c=0;c<a.parentTasks.length;c++){d=a.parentTasks[c];if(d.startTime<a.startDate)return;if(this.checkPosParentTaskInTree(d))return}this.sortTasksByStartTime(a)}for(b=0;b<this.project.length;b++){a=this.project[b];a=new dojox.gantt.GanttProjectControl(this,a);if(this.arrProjects.length>0)c=this.arrProjects[this.arrProjects.length-1],a.previousProject=
c,c.nextProject=a;a.create();this.checkHeighPanelTasks();this.arrProjects.push(a);this.createTasks(a)}this.resource&&this.resource.reConstruct();this.postLoadData();this.postBindEvents()},loadJSONData:function(b){var a=this;a.dataFilePath=b||a.dataFilePath;dojo.xhrGet({url:a.dataFilePath,sync:!0,load:function(b){a.loadJSONString(b);a.buildUIContent();alert("Successfully! Loaded data from: "+a.dataFilePath)},error:function(){alert("Failed! Load error: "+a.dataFilePath)}})},loadJSONString:function(b){if(b)this.clearAll(),
b=dojo.fromJson(b).items,dojo.forEach(b,function(a){var b=a.startdate.split("-"),d=new dojox.gantt.GanttProjectItem({id:a.id,name:a.name,startDate:new Date(b[0],parseInt(b[1])-1,b[2])});dojo.forEach(a.tasks,function(a){var b=a.id,c=a.name,h=a.starttime.split("-");duration=a.duration;percentage=a.percentage;previousTaskId=a.previousTaskId;taskOwner=a.taskOwner;b=new dojox.gantt.GanttTaskItem({id:b,name:c,startTime:new Date(h[0],parseInt(h[1])-1,h[2]),duration:duration,percentage:percentage,previousTaskId:previousTaskId,
taskOwner:taskOwner});a=a.children;a.length!=0&&this.buildChildTasksData(b,a);d.addTask(b)},this);this.addProject(d)},this)},buildChildTasksData:function(b,a){a&&dojo.forEach(a,function(a){var d=a.id,e=a.name,f=a.starttime.split("-"),g=a.duration,h=a.percentage,i=a.previousTaskId,j=a.taskOwner,d=new dojox.gantt.GanttTaskItem({id:d,name:e,startTime:new Date(f[0],parseInt(f[1])-1,f[2]),duration:g,percentage:h,previousTaskId:i,taskOwner:j});d.parentTask=b;b.addChildTask(d);a=a.children;a.length!=0&&
this.buildChildTasksData(d,a)},this)},getJSONData:function(){var b={identifier:"id",items:[]};dojo.forEach(this.project,function(a){var c={id:a.id,name:a.name,startdate:a.startDate.getFullYear()+"-"+(a.startDate.getMonth()+1)+"-"+a.startDate.getDate(),tasks:[]};b.items.push(c);dojo.forEach(a.parentTasks,function(a){a={id:a.id,name:a.name,starttime:a.startTime.getFullYear()+"-"+(a.startTime.getMonth()+1)+"-"+a.startTime.getDate(),duration:a.duration,percentage:a.percentage,previousTaskId:a.previousTaskId||
"",taskOwner:a.taskOwner||"",children:this.getChildTasksData(a.cldTasks)};c.tasks.push(a)},this)},this);return b},getChildTasksData:function(b){var a=[];b&&b.length>0&&dojo.forEach(b,function(b){b={id:b.id,name:b.name,starttime:b.startTime.getFullYear()+"-"+(b.startTime.getMonth()+1)+"-"+b.startTime.getDate(),duration:b.duration,percentage:b.percentage,previousTaskId:b.previousTaskId||"",taskOwner:b.taskOwner||"",children:this.getChildTasksData(b.cldTasks)};a.push(b)},this);return a},saveJSONData:function(b){var a=
this;a.dataFilePath=b&&dojo.trim(b).length>0?b:this.dataFilePath;try{dojo.xhrPost({url:a.saveProgramPath,content:{filename:a.dataFilePath,data:dojo.toJson(a.getJSONData())},handle:function(b,c){dojo._isDocumentOk(c.xhr)||c.xhr.status==405?alert("Successfully! Saved data to "+a.dataFilePath):alert("Failed! Saved error")}})}catch(c){alert("exception: "+c.message)}},sortTaskStartTime:function(b,a){return b.startTime<a.startTime?-1:b.startTime>a.startTime?1:0},sortProjStartDate:function(b,a){return b.startDate<
a.startDate?-1:b.startDate>a.startDate?1:0},setStartTimeChild:function(b){dojo.forEach(b.cldTasks,function(a){if(!a.startTime)a.startTime=b.startTime;a.cldTasks.length!=0&&this.setStartTimeChild(a)},this)},createPanelTasks:function(){var b=dojo.create("div",{className:"ganttTaskPanel"});dojo.style(b,{height:this.contentHeight-this.panelTimeHeight-this.scrollBarWidth+"px"});return b},refreshParams:function(b){this.pixelsPerDay=b;this.pixelsPerWorkHour=this.pixelsPerDay/this.hsPerDay;this.pixelsPerHour=
this.pixelsPerDay/24},createPanelNamesTasksHeader:function(){var b=dojo.create("div",{className:"ganttPanelHeader"}),a=dojo.create("table",{cellPadding:"0px",border:"0px",cellSpacing:"0px",bgColor:"#FFFFFF",className:"ganttToolbar"},b),c=a.insertRow(a.rows.length),d=a.insertRow(a.rows.length),e=a.insertRow(a.rows.length);a.insertRow(a.rows.length);var a=dojo.create("td",{align:"center",vAlign:"middle",className:"ganttToolbarZoomIn"},c),f=dojo.hitch(this,function(){this.scale*2>5||(this.scale*=2,this.switchTeleMicroView(this.pixelsPerDay*
this.scale))});dojo.disconnect(this.zoomInClickEvent);this.zoomInClickEvent=dojo.connect(a,"onclick",this,f);dojo.disconnect(this.zoomInKeyEvent);this.zoomInKeyEvent=dojo.connect(a,"onkeydown",this,function(a){a.keyCode==dojo.keys.ENTER&&f()});dojo.attr(a,"tabIndex",0);var c=dojo.create("td",{align:"center",vAlign:"middle",className:"ganttToolbarZoomOut"},c),g=dojo.hitch(this,function(){this.scale*0.5<0.2||(this.scale*=0.5,this.switchTeleMicroView(this.pixelsPerDay*this.scale))});dojo.disconnect(this.zoomOutClickEvent);
this.zoomOutClickEvent=dojo.connect(c,"onclick",this,g);dojo.disconnect(this.zoomOutKeyEvent);this.zoomOutKeyEvent=dojo.connect(c,"onkeydown",this,function(a){a.keyCode==dojo.keys.ENTER&&g()});dojo.attr(c,"tabIndex",0);var h=dojo.create("td",{align:"center",vAlign:"middle",className:"ganttToolbarMicro"},d);dojo.disconnect(this.microClickEvent);this.microClickEvent=dojo.connect(h,"onclick",this,dojo.hitch(this,this.refresh,this.animation?15:1,0,2));dojo.disconnect(this.microKeyEvent);this.microKeyEvent=
dojo.connect(h,"onkeydown",this,function(a){a.keyCode==dojo.keys.ENTER&&(h.blur(),this.refresh(this.animation?15:1,0,2))});dojo.attr(h,"tabIndex",0);var i=dojo.create("td",{align:"center",vAlign:"middle",className:"ganttToolbarTele"},d);dojo.disconnect(this.teleClickEvent);this.teleClickEvent=dojo.connect(i,"onclick",this,dojo.hitch(this,this.refresh,this.animation?15:1,0,0.5));dojo.disconnect(this.teleKeyEvent);this.teleKeyEvent=dojo.connect(i,"onkeydown",this,function(a){a.keyCode==dojo.keys.ENTER&&
(i.blur(),this.refresh(this.animation?15:1,0,0.5))});dojo.attr(i,"tabIndex",0);d=dojo.create("td",{align:"center",vAlign:"middle",className:"ganttToolbarSave"},e);dojo.disconnect(this.saveClickEvent);this.saveClickEvent=dojo.connect(d,"onclick",this,dojo.hitch(this,this.saveJSONData,""));dojo.disconnect(this.saveKeyEvent);this.saveKeyEvent=dojo.connect(d,"onkeydown",this,function(a){a.keyCode==dojo.keys.ENTER&&this.saveJSONData("")});dojo.attr(d,"tabIndex",0);e=dojo.create("td",{align:"center",vAlign:"middle",
className:"ganttToolbarLoad"},e);dojo.disconnect(this.loadClickEvent);this.loadClickEvent=dojo.connect(e,"onclick",this,dojo.hitch(this,this.loadJSONData,""));dojo.disconnect(this.loadKeyEvent);this.loadKeyEvent=dojo.connect(e,"onkeydown",this,function(a){a.keyCode==dojo.keys.ENTER&&this.loadJSONData("")});dojo.attr(e,"tabIndex",0);var j=["Enlarge timeline","Shrink timeline","Zoom in time zone(microscope view)","Zoom out time zone(telescope view)","Save gantt data to json file","Load gantt data from json file"];
dojo.forEach([a,c,h,i,d,e],function(a,b){var c=j[b],d=function(){dojo.addClass(a,"ganttToolbarActionHover");dijit.showTooltip(c,a,["above","below"])};a.onmouseover=d;a.onfocus=d;d=function(){dojo.removeClass(a,"ganttToolbarActionHover");a&&dijit.hideTooltip(a)};a.onmouseout=d;a.onblur=d},this);return b},createPanelNamesTasks:function(){var b=dojo.create("div",{innerHTML:"&nbsp;",className:"ganttPanelNames"});dojo.style(b,{height:this.contentHeight-this.panelTimeHeight-this.scrollBarWidth+"px",width:this.maxWidthPanelNames+
"px"});return b},createPanelTime:function(){var b=dojo.create("div",{className:"ganttPanelTime"}),a=dojo.create("table",{cellPadding:"0px",border:"0px",cellSpacing:"0px",bgColor:"#FFFFFF",className:"ganttTblTime"},b);this.totalDays=this.countDays;for(var c=a.insertRow(a.rows.length),d=oldYear=(new Date(this.startDate)).getFullYear(),e=0,f=0;f<this.countDays;f++,e++)d=new Date(this.startDate),d.setDate(d.getDate()+f),d=d.getFullYear(),d!=oldYear&&(this.addYearInPanelTime(c,e,oldYear),e=0,oldYear=d);
this.addYearInPanelTime(c,e,d);dojo.style(c,"display","none");for(var e=a.insertRow(a.rows.length),g=oldMonth=(new Date(this.startDate)).getMonth(),c=0,d=1970,f=0;f<this.countDays;f++,c++)d=new Date(this.startDate),d.setDate(d.getDate()+f),g=d.getMonth(),d=d.getFullYear(),g!=oldMonth&&(this.addMonthInPanelTime(e,c,oldMonth,d),c=0,oldMonth=g);this.addMonthInPanelTime(e,c,g,d);e=a.insertRow(a.rows.length);d=oldWeek=dojo.date.locale._getWeekOfYear(new Date(this.startDate));for(f=c=0;f<this.countDays;f++,
c++)d=new Date(this.startDate),d.setDate(d.getDate()+f),d=dojo.date.locale._getWeekOfYear(d),d!=oldWeek&&(this.addWeekInPanelTime(e,c,oldWeek),c=0,oldWeek=d);this.addWeekInPanelTime(e,c,d);d=a.insertRow(a.rows.length);for(f=0;f<this.countDays;f++)this.addDayInPanelTime(d);a=a.insertRow(a.rows.length);for(f=0;f<this.countDays;f++)this.addHourInPanelTime(a);dojo.style(a,"display","none");return b},adjustPanelTime:function(){var b=dojo.map(this.arrProjects,function(a){return parseInt(a.projectItem[0].style.left)+
parseInt(a.projectItem[0].firstChild.style.width)+a.descrProject.offsetWidth+this.panelTimeExpandDelta},this).sort(function(a,b){return b-a})[0];if(this.maxTaskEndPos!=b){for(var a=this.panelTime.firstChild.firstChild.rows,c=0;c<=4;c++)this.removeCell(a[c]);var d=Math.round((b+this.panelTimeExpandDelta)/this.pixelsPerDay);this.totalDays=d;for(var e=oldYear=(new Date(this.startDate)).getFullYear(),f=0,c=0;c<d;c++,f++)e=new Date(this.startDate),e.setDate(e.getDate()+c),e=e.getFullYear(),e!=oldYear&&
(this.addYearInPanelTime(a[0],f,oldYear),f=0,oldYear=e);this.addYearInPanelTime(a[0],f,e);for(var g=oldMonth=(new Date(this.startDate)).getMonth(),f=0,e=1970,c=0;c<d;c++,f++)e=new Date(this.startDate),e.setDate(e.getDate()+c),g=e.getMonth(),e=e.getFullYear(),g!=oldMonth&&(this.addMonthInPanelTime(a[1],f,oldMonth,e),f=0,oldMonth=g);this.addMonthInPanelTime(a[1],f,g,e);e=oldWeek=dojo.date.locale._getWeekOfYear(new Date(this.startDate));for(c=f=0;c<d;c++,f++)e=new Date(this.startDate),e.setDate(e.getDate()+
c),e=dojo.date.locale._getWeekOfYear(e),e!=oldWeek&&(this.addWeekInPanelTime(a[2],f,oldWeek),f=0,oldWeek=e);this.addWeekInPanelTime(a[2],f,e);for(c=0;c<d;c++)this.addDayInPanelTime(a[3]);for(c=0;c<d;c++)this.addHourInPanelTime(a[4]);this.panelTime.firstChild.firstChild.style.width=this.pixelsPerDay*a[3].cells.length+"px";this.contentData.firstChild.style.width=this.pixelsPerDay*a[3].cells.length+"px";this.maxTaskEndPos=b}},addYearInPanelTime:function(b,a,c){c="Year   "+c;b=dojo.create("td",{colSpan:a,
align:"center",vAlign:"middle",className:"ganttYearNumber",innerHTML:this.pixelsPerDay*a>20?c:"",innerHTMLData:c},b);dojo.style(b,"width",this.pixelsPerDay*a+"px")},addMonthInPanelTime:function(b,a,c,d){c=this.months[c]+(d?" of "+d:"");b=dojo.create("td",{colSpan:a,align:"center",vAlign:"middle",className:"ganttMonthNumber",innerHTML:this.pixelsPerDay*a>30?c:"",innerHTMLData:c},b);dojo.style(b,"width",this.pixelsPerDay*a+"px")},addWeekInPanelTime:function(b,a,c){c="Week   "+c;b=dojo.create("td",{colSpan:a,
align:"center",vAlign:"middle",className:"ganttWeekNumber",innerHTML:this.pixelsPerDay*a>20?c:"",innerHTMLData:c},b);dojo.style(b,"width",this.pixelsPerDay*a+"px")},addDayInPanelTime:function(b){var a=new Date(this.startDate);a.setDate(a.getDate()+parseInt(b.cells.length));var c=dojo.create("td",{align:"center",vAlign:"middle",className:"ganttDayNumber",innerHTML:this.pixelsPerDay>20?a.getDate():"",innerHTMLData:String(a.getDate()),data:b.cells.length},b);dojo.style(c,"width",this.pixelsPerDay+"px");
a.getDay()>=5&&dojo.addClass(c,"ganttDayNumberWeekend");this._events.push(dojo.connect(c,"onmouseover",this,function(a){var a=a.target||a.srcElement,b=new Date(this.startDate.getTime());b.setDate(b.getDate()+parseInt(dojo.attr(a,"data")));dijit.showTooltip(b.getFullYear()+"."+(b.getMonth()+1)+"."+b.getDate(),c,["above","below"])}));this._events.push(dojo.connect(c,"onmouseout",this,function(a){(a=a.target||a.srcElement)&&dijit.hideTooltip(a)}))},addHourInPanelTime:function(b){b=dojo.create("td",{align:"center",
vAlign:"middle",className:"ganttHourNumber",data:b.cells.length},b);dojo.style(b,"width",this.pixelsPerDay+"px");for(var b=dojo.create("table",{cellPadding:"0",cellSpacing:"0"},b),b=b.insertRow(b.rows.length),a=0;a<this.hsPerDay;a++){var c=dojo.create("td",{className:"ganttHourClass"},b);dojo.style(c,"width",this.pixelsPerDay/this.hsPerDay+"px");dojo.attr(c,"innerHTMLData",String(9+a));this.pixelsPerDay/this.hsPerDay>5&&dojo.attr(c,"innerHTML",String(9+a));dojo.addClass(c,a<=3?"ganttHourNumberAM":
"ganttHourNumberPM")}},incHeightPanelTasks:function(b){var a=this.contentData.firstChild;a.style.height=parseInt(a.style.height)+b+"px"},incHeightPanelNames:function(b){var a=this.panelNames.firstChild;a.style.height=parseInt(a.style.height)+b+"px"},checkPosition:function(){dojo.forEach(this.arrProjects,function(b){dojo.forEach(b.arrTasks,function(a){a.checkPosition()},this)},this)},checkHeighPanelTasks:function(){this.contentDataHeight+=this.heightTaskItemExtra+this.heightTaskItem;parseInt(this.contentData.firstChild.style.height)<=
this.contentDataHeight&&(this.incHeightPanelTasks(this.heightTaskItem+this.heightTaskItemExtra),this.incHeightPanelNames(this.heightTaskItem+this.heightTaskItemExtra))},sortTasksByStartTime:function(b){b.parentTasks.sort(this.sortTaskStartTime);for(var a=0;a<b.parentTasks.length;a++)b.parentTasks[a]=this.sortChildTasks(b.parentTasks[a])},sortChildTasks:function(b){b.cldTasks.sort(this.sortTaskStartTime);for(var a=0;a<b.cldTasks.length;a++)b.cldTasks[a].cldTasks.length>0&&this.sortChildTasks(b.cldTasks[a]);
return b},refresh:function(b,a,c){if(!(this.arrProjects.length<=0)&&!(this.arrProjects[0].arrTasks.length<=0))if(!b||a>b)this.refreshController(),this.resource&&this.resource.refresh(),this.tempDayInPixels=0,this.panelNameHeadersCover&&dojo.style(this.panelNameHeadersCover,"display","none");else{if(this.tempDayInPixels==0)this.tempDayInPixels=this.pixelsPerDay;this.panelNameHeadersCover&&dojo.style(this.panelNameHeadersCover,"display","");this.refreshParams(this.tempDayInPixels+this.tempDayInPixels*
(c-1)*Math.pow(a/b,2));dojo.forEach(this.arrProjects,function(a){dojo.forEach(a.arrTasks,function(a){a.refresh()},this);a.refresh()},this);setTimeout(dojo.hitch(this,function(){this.refresh(b,++a,c)}),15)}},switchTeleMicroView:function(b){for(var a=this.panelTime.firstChild.firstChild,c=0;c<5;c++)b>40?dojo.style(a.rows[c],"display",c==0||c==1?"none":""):b<20?dojo.style(a.rows[c],"display",c==2||c==4?"none":""):dojo.style(a.rows[c],"display",c==0||c==4?"none":"")},refreshController:function(){this.contentData.firstChild.style.width=
Math.max(1200,this.pixelsPerDay*this.totalDays)+"px";this.panelTime.firstChild.style.width=this.pixelsPerDay*this.totalDays+"px";this.panelTime.firstChild.firstChild.style.width=this.pixelsPerDay*this.totalDays+"px";this.switchTeleMicroView(this.pixelsPerDay);dojo.forEach(this.panelTime.firstChild.firstChild.rows,function(b){dojo.forEach(b.childNodes,function(a){var b=parseInt(dojo.attr(a,"colSpan")||1),d=dojo.trim(dojo.attr(a,"innerHTMLData")||"");d.length>0?dojo.attr(a,"innerHTML",this.pixelsPerDay*
b<20?"":d):dojo.forEach(a.firstChild.rows[0].childNodes,function(a){var b=dojo.trim(dojo.attr(a,"innerHTMLData")||"");dojo.attr(a,"innerHTML",this.pixelsPerDay/this.hsPerDay>10?b:"")},this);b==1&&(dojo.style(a,"width",this.pixelsPerDay*b+"px"),d.length<=0&&dojo.forEach(a.firstChild.rows[0].childNodes,function(a){dojo.style(a,"width",this.pixelsPerDay*b/this.hsPerDay+"px")},this))},this)},this)},init:function(){this.startDate=this.getStartDate();dojo.style(this.content,{width:this.contentWidth+"px",
height:this.contentHeight+"px"});this.tableControl=dojo.create("table",{cellPadding:"0",cellSpacing:"0",className:"ganttTabelControl"});var b=this.tableControl.insertRow(this.tableControl.rows.length);this.content.appendChild(this.tableControl);this.countDays=this.getCountDays();this.panelTime=dojo.create("div",{className:"ganttPanelTimeContainer"});dojo.style(this.panelTime,"height",this.panelTimeHeight+"px");this.panelTime.appendChild(this.createPanelTime());this.contentData=dojo.create("div",{className:"ganttContentDataContainer"});
dojo.style(this.contentData,"height",this.contentHeight-this.panelTimeHeight+"px");this.contentData.appendChild(this.createPanelTasks());var a=dojo.create("td",{vAlign:"top"});this.panelNameHeaders=dojo.create("div",{className:"ganttPanelNameHeaders"},a);dojo.style(this.panelNameHeaders,{height:this.panelTimeHeight+"px",width:this.maxWidthPanelNames+"px"});this.panelNameHeaders.appendChild(this.createPanelNamesTasksHeader());this.panelNames=dojo.create("div",{className:"ganttPanelNamesContainer"},
a);this.panelNames.appendChild(this.createPanelNamesTasks());b.appendChild(a);var a=dojo.create("td",{vAlign:"top"}),c=dojo.create("div",{className:"ganttDivCell"});c.appendChild(this.panelTime);c.appendChild(this.contentData);a.appendChild(c);b.appendChild(a);dojo.style(this.panelNames,"height",this.contentHeight-this.panelTimeHeight-this.scrollBarWidth+"px");dojo.style(this.panelNames,"width",this.maxWidthPanelNames+"px");dojo.style(this.contentData,"width",this.contentWidth-this.maxWidthPanelNames+
"px");dojo.style(this.contentData.firstChild,"width",this.pixelsPerDay*this.countDays+"px");dojo.style(this.panelTime,"width",this.contentWidth-this.maxWidthPanelNames-this.scrollBarWidth+"px");dojo.style(this.panelTime.firstChild,"width",this.pixelsPerDay*this.countDays+"px");if(this.isShowConMenu)this.tabMenu=new dojox.gantt.TabMenu(this);var d=this;this.contentData.onscroll=function(){d.panelTime.scrollLeft=this.scrollLeft;if(d.panelNames)d.panelNames.scrollTop=this.scrollTop,d.isShowConMenu&&
d.tabMenu.hide();if(d.resource)d.resource.contentData.scrollLeft=this.scrollLeft};this.project.sort(this.sortProjStartDate);for(b=0;b<this.project.length;b++){a=this.project[b];for(c=0;c<a.parentTasks.length;c++){var e=a.parentTasks[c];if(!e.startTime)e.startTime=a.startDate;this.setStartTimeChild(e);if(this.setPreviousTask(a))return}for(c=0;c<a.parentTasks.length;c++){e=a.parentTasks[c];if(e.startTime<a.startDate)if(this.correctError)e.startTime=a.startDate;else return;if(this.checkPosParentTaskInTree(e))return}this.sortTasksByStartTime(a)}for(b=
0;b<this.project.length;b++){a=this.project[b];a=new dojox.gantt.GanttProjectControl(this,a);if(this.arrProjects.length>0)c=this.arrProjects[this.arrProjects.length-1],a.previousProject=c,c.nextProject=a;a.create();this.checkHeighPanelTasks();this.arrProjects.push(a);this.createTasks(a)}if(this.withResource)this.resource=new dojox.gantt.GanttResourceItem(this),this.resource.create();this.postLoadData();this.postBindEvents();return this},postLoadData:function(){dojo.forEach(this.arrProjects,function(a){dojo.forEach(a.arrTasks,
function(a){a.postLoadData()},this);a.postLoadData()},this);var b=dojo.coords(this.panelNameHeaders);if(!this.panelNameHeadersCover)this.panelNameHeadersCover=dojo.create("div",{className:"ganttHeaderCover"},this.panelNameHeaders.parentNode),dojo.style(this.panelNameHeadersCover,{left:b.l+"px",top:b.t+"px",height:b.h+"px",width:b.w+"px",display:"none"})},postBindEvents:function(){var b=dojo.position(this.tableControl,!0);!dojo.isIE&&this._events.push(dojo.connect(this.tableControl,"onmousemove",this,
function(a){var c=a.srcElement||a.target;if(c==this.panelNames.firstChild||c==this.contentData.firstChild){c=this.heightTaskItem+this.heightTaskItemExtra;a=parseInt(a.layerY/c)*c+this.panelTimeHeight-this.contentData.scrollTop;if(a!=this.oldHLTop&&a<b.h-50)this.highLightDiv?dojo.style(this.highLightDiv,"top",b.y+a+"px"):(this.highLightDiv=dojo.create("div",{className:"ganttRowHighlight"},dojo.body()),dojo.style(this.highLightDiv,{top:b.y+a+"px",left:b.x+"px",width:b.w-20+"px",height:c+"px"}));this.oldHLTop=
a}}))},getStartDate:function(){dojo.forEach(this.project,function(b){if(this.startDate){if(b.startDate<this.startDate)this.startDate=new Date(b.startDate)}else this.startDate=new Date(b.startDate)},this);this.initialPos=24*this.pixelsPerHour;return this.startDate?new Date(this.startDate.setHours(this.startDate.getHours()-24)):new Date},getCountDays:function(){return parseInt((this.contentWidth-this.maxWidthPanelNames)/(this.pixelsPerHour*24))},createTasks:function(b){dojo.forEach(b.project.parentTasks,
function(a,c){if(c>0)b.project.parentTasks[c-1].nextParentTask=a,a.previousParentTask=b.project.parentTasks[c-1];var d=new dojox.gantt.GanttTaskControl(a,b,this);b.arrTasks.push(d);d.create();this.checkHeighPanelTasks();a.cldTasks.length>0&&this.createChildItemControls(a.cldTasks,b)},this)},createChildItemControls:function(b,a){b&&dojo.forEach(b,function(c,d){if(d>0)c.previousChildTask=b[d-1],b[d-1].nextChildTask=c;(new dojox.gantt.GanttTaskControl(c,a,this)).create();this.checkHeighPanelTasks();
c.cldTasks.length>0&&this.createChildItemControls(c.cldTasks,a)},this)},getPosOnDate:function(b){return(b-this.startDate)/36E5*this.pixelsPerHour},getWidthOnDuration:function(b){return Math.round(this.pixelsPerWorkHour*b)},getLastChildTask:function(b){return b.childTask.length>0?this.getLastChildTask(b.childTask[b.childTask.length-1]):b},removeCell:function(b){for(;b.cells[0];)b.deleteCell(b.cells[0])}})}());