/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._editor.plugins.AlwaysShowToolbar"]||(dojo._hasResource["dijit._editor.plugins.AlwaysShowToolbar"]=!0,dojo.provide("dijit._editor.plugins.AlwaysShowToolbar"),dojo.require("dijit._editor._Plugin"),dojo.declare("dijit._editor.plugins.AlwaysShowToolbar",dijit._editor._Plugin,{_handleScroll:!0,setEditor:function(b){b.iframe?(this.editor=b,b.onLoadDeferred.addCallback(dojo.hitch(this,this.enable))):console.log("Port AlwaysShowToolbar plugin to work with Editor without iframe")},
enable:function(b){this._updateHeight();this.connect(window,"onscroll","globalOnScrollHandler");this.connect(this.editor,"onNormalizedDisplayChanged","_updateHeight");return b},_updateHeight:function(){var b=this.editor;if(b.isLoaded&&!b.height){var a=dojo._getMarginSize(b.editNode).h;if(dojo.isOpera)a=b.editNode.scrollHeight;if(!a)a=dojo._getMarginSize(b.document.body).h;if(a==0)console.debug("Can not figure out the height of the editing area!");else{if(dojo.isIE<=7&&this.editor.minHeight){var d=
parseInt(this.editor.minHeight);a<d&&(a=d)}if(a!=this._lastHeight)this._lastHeight=a,dojo.marginBox(b.iframe,{h:this._lastHeight})}}},_lastHeight:0,globalOnScrollHandler:function(){var b=dojo.isIE<7;if(this._handleScroll){var a=this.editor.header;if(!this._scrollSetUp)this._scrollSetUp=!0,this._scrollThreshold=dojo.position(a,!0).y;var d=dojo._docScroll().y,c=a.style;if(d>this._scrollThreshold&&d<this._scrollThreshold+this._lastHeight){if(!this._fixEnabled){var e=dojo._getMarginSize(a);this.editor.iframe.style.marginTop=
e.h+"px";b?(c.left=dojo.position(a).x,this._IEOriginalPos=a.previousSibling?["after",a.previousSibling]:a.nextSibling?["before",a.nextSibling]:["last",a.parentNode],dojo.body().appendChild(a),dojo.addClass(a,"dijitIEFixedToolbar")):(c.position="fixed",c.top="0px");dojo.marginBox(a,{w:e.w});c.zIndex=2E3;this._fixEnabled=!0}b=this.height?parseInt(this.editor.height):this.editor._lastHeight;c.display=d>this._scrollThreshold+b?"none":""}else if(this._fixEnabled){this.editor.iframe.style.marginTop="";
c.position="";c.top="";c.zIndex="";c.display="";if(b)c.left="",dojo.removeClass(a,"dijitIEFixedToolbar"),this._IEOriginalPos?(dojo.place(a,this._IEOriginalPos[1],this._IEOriginalPos[0]),this._IEOriginalPos=null):dojo.place(a,this.editor.iframe,"before");c.width="";this._fixEnabled=!1}}},destroy:function(){this._IEOriginalPos=null;this._handleScroll=!1;dojo.forEach(this._connects,dojo.disconnect);dojo.isIE<7&&dojo.removeClass(this.editor.header,"dijitIEFixedToolbar")}}));