/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._editor.plugins.EnterKeyHandling"]||(dojo._hasResource["dijit._editor.plugins.EnterKeyHandling"]=!0,dojo.provide("dijit._editor.plugins.EnterKeyHandling"),dojo.require("dojo.window"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit._editor.range"),dojo.declare("dijit._editor.plugins.EnterKeyHandling",dijit._editor._Plugin,{blockNodeForEnter:"BR",constructor:function(a){if(a){if("blockNodeForEnter"in a)a.blockNodeForEnter=a.blockNodeForEnter.toUpperCase();dojo.mixin(this,
a)}},setEditor:function(a){if(this.editor!==a)if(this.editor=a,this.blockNodeForEnter=="BR")this.editor.customUndo=!0,a.onLoadDeferred.addCallback(dojo.hitch(this,function(b){this.connect(a.document,"onkeypress",function(a){if(a.charOrCode==dojo.keys.ENTER){var b=dojo.mixin({},a);b.shiftKey=!0;this.handleEnterKey(b)||dojo.stopEvent(a)}});return b}));else if(this.blockNodeForEnter){var b=dojo.hitch(this,this.handleEnterKey);a.addKeyHandler(13,0,0,b);a.addKeyHandler(13,0,1,b);this.connect(this.editor,
"onKeyPressed","onKeyPressed")}},onKeyPressed:function(){if(this._checkListLater){if(dojo.withGlobal(this.editor.window,"isCollapsed",dijit)){var a=dojo.withGlobal(this.editor.window,"getAncestorElement",dijit._editor.selection,["LI"]);if(a){if(dojo.isMoz&&a.parentNode.parentNode.nodeName=="LI")a=a.parentNode.parentNode;var b=a.firstChild;if(b&&b.nodeType==1&&(b.nodeName=="UL"||b.nodeName=="OL"))a.insertBefore(b.ownerDocument.createTextNode("\u00a0"),b),b=dijit.range.create(this.editor.window),b.setStart(a.firstChild,
0),a=dijit.range.getSelection(this.editor.window,!0),a.removeAllRanges(),a.addRange(b)}else dijit._editor.RichText.prototype.execCommand.call(this.editor,"formatblock",this.blockNodeForEnter),(a=dojo.withGlobal(this.editor.window,"getAncestorElement",dijit._editor.selection,[this.blockNodeForEnter]))?(a.innerHTML=this.bogusHtmlContent,dojo.isIE&&(a=this.editor.document.selection.createRange(),a.move("character",-1),a.select())):console.error("onKeyPressed: Cannot find the new block node")}this._checkListLater=
!1}this._pressedEnterInBlock&&(this._pressedEnterInBlock.previousSibling&&this.removeTrailingBr(this._pressedEnterInBlock.previousSibling),delete this._pressedEnterInBlock)},bogusHtmlContent:"&nbsp;",blockNodes:/^(?:P|H1|H2|H3|H4|H5|H6|LI)$/,handleEnterKey:function(a){var t;var b,e,d,k,i,q,j=this.editor.document,l,f,m;if(a.shiftKey){l=dojo.withGlobal(this.editor.window,"getParentElement",dijit._editor.selection);if(a=dijit.range.getAncestor(l,this.blockNodes)){if(a.tagName=="LI")return!0;b=dijit.range.getSelection(this.editor.window);
e=b.getRangeAt(0);e.collapsed||(e.deleteContents(),b=dijit.range.getSelection(this.editor.window),e=b.getRangeAt(0));if(dijit.range.atBeginningOfContainer(a,e.startContainer,e.startOffset))l=j.createElement("br"),d=dijit.range.create(this.editor.window),a.insertBefore(l,a.firstChild),d.setStartBefore(l.nextSibling),b.removeAllRanges(),b.addRange(d);else if(dijit.range.atEndOfContainer(a,e.startContainer,e.startOffset))d=dijit.range.create(this.editor.window),l=j.createElement("br"),a.appendChild(l),
a.appendChild(j.createTextNode("\u00a0")),d.setStart(a.lastChild,0),b.removeAllRanges(),b.addRange(d);else return(f=e.startContainer)&&f.nodeType==3?(m=f.nodeValue,dojo.withGlobal(this.editor.window,function(){k=j.createTextNode(m.substring(0,e.startOffset));i=j.createTextNode(m.substring(e.startOffset));q=j.createElement("br");i.nodeValue==""&&dojo.isWebKit&&(i=j.createTextNode("\u00a0"));dojo.place(k,f,"after");dojo.place(q,k,"after");dojo.place(i,q,"after");dojo.destroy(f);d=dijit.range.create(dojo.gobal);
d.setStart(i,0);b.removeAllRanges();b.addRange(d)}),!1):!0}else if(b=dijit.range.getSelection(this.editor.window),b.rangeCount){if((e=b.getRangeAt(0))&&e.startContainer)e.collapsed||(e.deleteContents(),b=dijit.range.getSelection(this.editor.window),e=b.getRangeAt(0)),(f=e.startContainer)&&f.nodeType==3?dojo.withGlobal(this.editor.window,dojo.hitch(this,function(){var a=!1,c=e.startOffset;if(f.length<c)o=this._adjustNodeAndOffset(f,c),f=o.node,c=o.offset;m=f.nodeValue;k=j.createTextNode(m.substring(0,
c));i=j.createTextNode(m.substring(c));q=j.createElement("br");i.length||(i=j.createTextNode("\u00a0"),a=!0);k.length?dojo.place(k,f,"after"):k=f;dojo.place(q,k,"after");dojo.place(i,q,"after");dojo.destroy(f);d=dijit.range.create(dojo.gobal);d.setStart(i,0);d.setEnd(i,i.length);b.removeAllRanges();b.addRange(d);a&&!dojo.isWebKit?dijit._editor.selection.remove():dijit._editor.selection.collapse(!0)})):dojo.withGlobal(this.editor.window,dojo.hitch(this,function(){var a=j.createElement("br");f.appendChild(a);
a=j.createTextNode("\u00a0");f.appendChild(a);d=dijit.range.create(dojo.global);d.setStart(a,0);d.setEnd(a,a.length);b.removeAllRanges();b.addRange(d);dijit._editor.selection.collapse(!0)}))}else dijit._editor.RichText.prototype.execCommand.call(this.editor,"inserthtml","<br>");return!1}var n=!0;b=dijit.range.getSelection(this.editor.window);e=b.getRangeAt(0);e.collapsed||(e.deleteContents(),b=dijit.range.getSelection(this.editor.window),e=b.getRangeAt(0));var a=dijit.range.getBlockAncestor(e.endContainer,
null,this.editor.editNode),c=a.blockNode;if(this._checkListLater=c&&(c.nodeName=="LI"||c.parentNode.nodeName=="LI")){if(dojo.isMoz)this._pressedEnterInBlock=c;if(/^(\s|&nbsp;|\xA0|<span\b[^>]*\bclass=['"]Apple-style-span['"][^>]*>(\s|&nbsp;|\xA0)<\/span>)?(<br>)?$/.test(c.innerHTML))c.innerHTML="",dojo.isWebKit&&(d=dijit.range.create(this.editor.window),d.setStart(c,0),b.removeAllRanges(),b.addRange(d)),this._checkListLater=!1;return!0}if(!a.blockNode||a.blockNode===this.editor.editNode){try{dijit._editor.RichText.prototype.execCommand.call(this.editor,
"formatblock",this.blockNodeForEnter)}catch(s){}a={blockNode:dojo.withGlobal(this.editor.window,"getAncestorElement",dijit._editor.selection,[this.blockNodeForEnter]),blockContainer:this.editor.editNode};if(a.blockNode){if(a.blockNode!=this.editor.editNode&&!(a.blockNode.textContent||a.blockNode.innerHTML).replace(/^\s+|\s+$/g,"").length)return this.removeTrailingBr(a.blockNode),!1}else a.blockNode=this.editor.editNode;b=dijit.range.getSelection(this.editor.window);e=b.getRangeAt(0)}c=j.createElement(this.blockNodeForEnter);
c.innerHTML=this.bogusHtmlContent;this.removeTrailingBr(a.blockNode);var g=e.endOffset,n=e.endContainer;if(n.length<g)var o=this._adjustNodeAndOffset(n,g),n=o.node,g=o.offset;if(dijit.range.atEndOfContainer(a.blockNode,n,g))a.blockNode===a.blockContainer?a.blockNode.appendChild(c):dojo.place(c,a.blockNode,"after"),n=!1,d=dijit.range.create(this.editor.window),d.setStart(c,0),b.removeAllRanges(),b.addRange(d),this.editor.height&&dojo.window.scrollIntoView(c);else if(dijit.range.atBeginningOfContainer(a.blockNode,
e.startContainer,e.startOffset))dojo.place(c,a.blockNode,a.blockNode===a.blockContainer?"first":"before"),c.nextSibling&&this.editor.height&&(d=dijit.range.create(this.editor.window),d.setStart(c.nextSibling,0),b.removeAllRanges(),b.addRange(d),dojo.window.scrollIntoView(c.nextSibling)),n=!1;else{a.blockNode===a.blockContainer?a.blockNode.appendChild(c):dojo.place(c,a.blockNode,"after");n=!1;if(a.blockNode.style&&c.style&&a.blockNode.style.cssText)c.style.cssText=a.blockNode.style.cssText;f=e.startContainer;
var h;if(f&&f.nodeType==3){var r,g=e.endOffset;if(f.length<g)o=this._adjustNodeAndOffset(f,g),f=o.node,g=o.offset;m=f.nodeValue;k=j.createTextNode(m.substring(0,g));i=j.createTextNode(m.substring(g,m.length));dojo.place(k,f,"before");dojo.place(i,f,"after");dojo.destroy(f);for(h=k.parentNode;h!==a.blockNode;){var p=j.createElement(h.tagName);if(h.style&&p.style&&h.style.cssText)p.style.cssText=h.style.cssText;if(h.tagName==="FONT"){if(h.color)p.color=h.color;if(h.face)p.face=h.face;if(h.size)p.size=
h.size}for(g=i;g;)r=g.nextSibling,p.appendChild(g),g=r;dojo.place(p,h,"after");k=h;i=p;h=h.parentNode}g=i;if(g.nodeType==1||g.nodeType==3&&g.nodeValue)c.innerHTML="";for(h=g;g;)r=g.nextSibling,c.appendChild(g),g=r}d=dijit.range.create(this.editor.window);if(this.blockNodeForEnter!=="BR"){for(;h;)l=h,t=r=h.firstChild,h=t;if(l&&l.parentNode){if(c=l.parentNode,d.setStart(c,0),b.removeAllRanges(),b.addRange(d),this.editor.height&&dijit.scrollIntoView(c),dojo.isMoz)this._pressedEnterInBlock=a.blockNode}else n=
!0}else if(d.setStart(c,0),b.removeAllRanges(),b.addRange(d),this.editor.height&&dijit.scrollIntoView(c),dojo.isMoz)this._pressedEnterInBlock=a.blockNode}return n},_adjustNodeAndOffset:function(a,b){for(;a.length<b&&a.nextSibling&&a.nextSibling.nodeType==3;)b-=a.length,a=a.nextSibling;return{node:a,offset:b}},removeTrailingBr:function(a){if(a=/P|DIV|LI/i.test(a.tagName)?a:dijit._editor.selection.getParentOfType(a,["P","DIV","LI"]))if(a.lastChild&&(a.childNodes.length>1&&a.lastChild.nodeType==3&&/^[\s\xAD]*$/.test(a.lastChild.nodeValue)||
a.lastChild.tagName=="BR")&&dojo.destroy(a.lastChild),!a.childNodes.length)a.innerHTML=this.bogusHtmlContent}}));