/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._editor.plugins.FullScreen"]||(dojo._hasResource["dijit._editor.plugins.FullScreen"]=!0,dojo.provide("dijit._editor.plugins.FullScreen"),dojo.require("dojo.window"),dojo.require("dojo.i18n"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.form.Button"),dojo.requireLocalization("dijit._editor","commands",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dijit._editor.plugins.FullScreen",dijit._editor._Plugin,
{zIndex:500,_origState:null,_origiFrameState:null,_resizeHandle:null,isFullscreen:!1,toggle:function(){this.button.set("checked",!this.button.get("checked"))},_initButton:function(){var a=dojo.i18n.getLocalization("dijit._editor","commands"),c=this.editor;this.button=new dijit.form.ToggleButton({label:a.fullScreen,dir:c.dir,lang:c.lang,showLabel:!1,iconClass:this.iconClassPrefix+" "+this.iconClassPrefix+"FullScreen",tabIndex:"-1",onChange:dojo.hitch(this,"_setFullScreen")})},setEditor:function(a){this.editor=
a;this._initButton();this.editor.addKeyHandler(dojo.keys.F11,!0,!0,dojo.hitch(this,function(a){this.toggle();dojo.stopEvent(a);setTimeout(dojo.hitch(this,function(){this.editor.focus()}),250);return!0}));this.connect(this.editor.domNode,"onkeydown","_containFocus")},_containFocus:function(a){if(this.isFullscreen){var c=this.editor;if(!c.isTabIndent&&c._fullscreen_oldOnKeyDown&&a.keyCode===dojo.keys.TAB){var b=dijit.getFocus(),e=this._getAltViewNode();b.node==c.iframe||e&&b.node===e?setTimeout(dojo.hitch(this,
function(){c.toolbar.focus()}),10):e&&dojo.style(c.iframe,"display")==="none"?setTimeout(dojo.hitch(this,function(){dijit.focus(e)}),10):setTimeout(dojo.hitch(this,function(){c.focus()}),10);dojo.stopEvent(a)}else c._fullscreen_oldOnKeyDown&&c._fullscreen_oldOnKeyDown(a)}},_resizeEditor:function(){var a=dojo.window.getBox();dojo.marginBox(this.editor.domNode,{w:a.w,h:a.h});var c=this.editor.getHeaderHeight(),b=this.editor.getFooterHeight(),e=dojo._getPadBorderExtents(this.editor.domNode),d=dojo._getPadBorderExtents(this.editor.iframe.parentNode),
g=dojo._getMarginExtents(this.editor.iframe.parentNode),c=a.h-(c+e.h+b);dojo.marginBox(this.editor.iframe.parentNode,{h:c,w:a.w});dojo.marginBox(this.editor.iframe,{h:c-(d.h+g.h)})},_getAltViewNode:function(){},_setFullScreen:function(a){var c=dojo.window.getBox(),b=this.editor,e=dojo.body(),d=b.domNode.parentNode;if(this.isFullscreen=a){for(;d&&d!==dojo.body();)dojo.addClass(d,"dijitForceStatic"),d=d.parentNode;this._editorResizeHolder=this.editor.resize;b.resize=function(){};b._fullscreen_oldOnKeyDown=
b.onKeyDown;b.onKeyDown=dojo.hitch(this,this._containFocus);this._origState={};this._origiFrameState={};d=(a=b.domNode)&&a.style||{};this._origState={width:d.width||"",height:d.height||"",top:dojo.style(a,"top")||"",left:dojo.style(a,"left")||"",position:dojo.style(a,"position")||"static",marginBox:dojo.marginBox(b.domNode)};a=(a=b.iframe)&&a.style||{};d=dojo.style(b.iframe,"backgroundColor");this._origiFrameState={backgroundColor:d||"transparent",width:a.width||"auto",height:a.height||"auto",zIndex:a.zIndex||
""};dojo.style(b.domNode,{position:"absolute",top:"0px",left:"0px",zIndex:this.zIndex,width:c.w+"px",height:c.h+"px"});dojo.style(b.iframe,{height:"100%",width:"100%",zIndex:this.zIndex,backgroundColor:d!=="transparent"&&d!=="rgba(0, 0, 0, 0)"?d:"white"});dojo.style(b.iframe.parentNode,{height:"95%",width:"100%"});this._oldOverflow=e.style&&e.style.overflow?dojo.style(e,"overflow"):"";if(dojo.isIE&&!dojo.isQuirks){if(e.parentNode&&e.parentNode.style&&e.parentNode.style.overflow)this._oldBodyParentOverflow=
e.parentNode.style.overflow;else try{this._oldBodyParentOverflow=dojo.style(e.parentNode,"overflow")}catch(g){this._oldBodyParentOverflow="scroll"}dojo.style(e.parentNode,"overflow","hidden")}dojo.style(e,"overflow","hidden");this._resizeHandle=dojo.connect(window,"onresize",this,function(){var a=dojo.window.getBox();if("_prevW"in this&&"_prevH"in this){if(a.w===this._prevW&&a.h===this._prevH)return}else this._prevW=a.w,this._prevH=a.h;this._resizer&&(clearTimeout(this._resizer),delete this._resizer);
this._resizer=setTimeout(dojo.hitch(this,function(){delete this._resizer;this._resizeEditor()}),10)});this._resizeHandle2=dojo.connect(b,"resize",dojo.hitch(this,function(){this._resizer&&(clearTimeout(this._resizer),delete this._resizer);this._resizer=setTimeout(dojo.hitch(this,function(){delete this._resizer;this._resizeEditor()}),10)}));this._resizeEditor();var h=this.editor.toolbar.domNode;setTimeout(function(){dojo.window.scrollIntoView(h)},250)}else{if(this._resizeHandle)dojo.disconnect(this._resizeHandle),
this._resizeHandle=null;if(this._resizeHandle2)dojo.disconnect(this._resizeHandle2),this._resizeHandle2=null;if(this._rst)clearTimeout(this._rst),this._rst=null;for(;d&&d!==dojo.body();)dojo.removeClass(d,"dijitForceStatic"),d=d.parentNode;if(this._editorResizeHolder)this.editor.resize=this._editorResizeHolder;if(this._origState||this._origiFrameState){if(b._fullscreen_oldOnKeyDown)b.onKeyDown=b._fullscreen_oldOnKeyDown,delete b._fullscreen_oldOnKeyDown;var f=this;setTimeout(function(){var a=f._origState.marginBox,
d=f._origState.height;if(dojo.isIE&&!dojo.isQuirks)e.parentNode.style.overflow=f._oldBodyParentOverflow,delete f._oldBodyParentOverflow;dojo.style(e,"overflow",f._oldOverflow);delete f._oldOverflow;dojo.style(b.domNode,f._origState);dojo.style(b.iframe.parentNode,{height:"",width:""});dojo.style(b.iframe,f._origiFrameState);delete f._origState;delete f._origiFrameState;var c=dijit.getEnclosingWidget(b.domNode.parentNode);c&&c.resize?c.resize():(!d||d.indexOf("%")<0)&&setTimeout(dojo.hitch(this,function(){b.resize({h:a.h})}),
0);dojo.window.scrollIntoView(f.editor.toolbar.domNode)},100)}}},updateState:function(){this.button.set("disabled",this.get("disabled"))},destroy:function(){if(this._resizeHandle)dojo.disconnect(this._resizeHandle),this._resizeHandle=null;if(this._resizeHandle2)dojo.disconnect(this._resizeHandle2),this._resizeHandle2=null;if(this._resizer)clearTimeout(this._resizer),this._resizer=null;this.inherited(arguments)}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()===
"fullscreen")a.plugin=new dijit._editor.plugins.FullScreen({zIndex:"zIndex"in a.args?a.args.zIndex:500})}));