/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._editor.plugins.LinkDialog"]||(dojo._hasResource["dijit._editor.plugins.LinkDialog"]=!0,dojo.provide("dijit._editor.plugins.LinkDialog"),dojo.require("dijit._Widget"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.TooltipDialog"),dojo.require("dijit.form.DropDownButton"),dojo.require("dijit.form.ValidationTextBox"),dojo.require("dijit.form.Select"),dojo.require("dijit._editor.range"),dojo.require("dojo.i18n"),dojo.require("dojo.string"),dojo.requireLocalization("dijit",
"common",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.requireLocalization("dijit._editor","LinkDialog",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dijit._editor.plugins.LinkDialog",dijit._editor._Plugin,{buttonClass:dijit.form.DropDownButton,useDefaultCommand:!1,urlRegExp:"((https?|ftps?|file)\\://|./|/|)(/[a-zA-Z]{1,1}:/|)(((?:(?:[\\da-zA-Z](?:[-\\da-zA-Z]{0,61}[\\da-zA-Z])?)\\.)*(?:[a-zA-Z](?:[-\\da-zA-Z]{0,80}[\\da-zA-Z])?)\\.?)|(((\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])|(0[xX]0*[\\da-fA-F]?[\\da-fA-F]\\.){3}0[xX]0*[\\da-fA-F]?[\\da-fA-F]|(0+[0-3][0-7][0-7]\\.){3}0+[0-3][0-7][0-7]|(0|[1-9]\\d{0,8}|[1-3]\\d{9}|4[01]\\d{8}|42[0-8]\\d{7}|429[0-3]\\d{6}|4294[0-8]\\d{5}|42949[0-5]\\d{4}|429496[0-6]\\d{3}|4294967[01]\\d{2}|42949672[0-8]\\d|429496729[0-5])|0[xX]0*[\\da-fA-F]{1,8}|([\\da-fA-F]{1,4}\\:){7}[\\da-fA-F]{1,4}|([\\da-fA-F]{1,4}\\:){6}((\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])))(\\:\\d+)?(/(?:[^?#\\s/]+/)*(?:[^?#\\s/]{0,}(?:\\?[^?#\\s/]*)?(?:#.*)?)?)?",
emailRegExp:"<?(mailto\\:)([!#-'*+\\-\\/-9=?A-Z^-~]+[.])*[!#-'*+\\-\\/-9=?A-Z^-~]+@((?:(?:[\\da-zA-Z](?:[-\\da-zA-Z]{0,61}[\\da-zA-Z])?)\\.)+(?:[a-zA-Z](?:[-\\da-zA-Z]{0,6}[\\da-zA-Z])?)\\.?)|localhost|^[^-][a-zA-Z0-9_-]*>?",htmlTemplate:'<a href="${urlInput}" _djrealurl="${urlInput}" target="${targetSelect}">${textInput}</a>',tag:"a",_hostRxp:/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,_userAtRxp:/^([!#-'*+\-\/-9=?A-Z^-~]+[.])*[!#-'*+\-\/-9=?A-Z^-~]+@/i,linkDialogTemplate:"<table><tr><td><label for='${id}_urlInput'>${url}</label></td><td><input dojoType='dijit.form.ValidationTextBox' required='true' id='${id}_urlInput' name='urlInput' intermediateChanges='true'/></td></tr><tr><td><label for='${id}_textInput'>${text}</label></td><td><input dojoType='dijit.form.ValidationTextBox' required='true' id='${id}_textInput' name='textInput' intermediateChanges='true'/></td></tr><tr><td><label for='${id}_targetSelect'>${target}</label></td><td><select id='${id}_targetSelect' name='targetSelect' dojoType='dijit.form.Select'><option selected='selected' value='_self'>${currentWindow}</option><option value='_blank'>${newWindow}</option><option value='_top'>${topWindow}</option><option value='_parent'>${parentWindow}</option></select></td></tr><tr><td colspan='2'><button dojoType='dijit.form.Button' type='submit' id='${id}_setButton'>${set}</button><button dojoType='dijit.form.Button' type='button' id='${id}_cancelButton'>${buttonCancel}</button></td></tr></table>",
_initButton:function(){var a=this;this.tag=this.command=="insertImage"?"img":"a";var b=dojo.mixin(dojo.i18n.getLocalization("dijit","common",this.lang),dojo.i18n.getLocalization("dijit._editor","LinkDialog",this.lang)),c=this.dropDown=new dijit.TooltipDialog({title:b[this.command+"Title"],execute:dojo.hitch(this,"setValue"),onOpen:function(){a._onOpenDialog();dijit.TooltipDialog.prototype.onOpen.apply(this,arguments)},onCancel:function(){setTimeout(dojo.hitch(a,"_onCloseDialog"),0)}});b.urlRegExp=
this.urlRegExp;b.id=dijit.getUniqueId(this.editor.id);this._uniqueId=b.id;this._setContent(c.title+"<div style='border-bottom: 1px black solid;padding-bottom:2pt;margin-bottom:4pt'></div>"+dojo.string.substitute(this.linkDialogTemplate,b));c.startup();this._urlInput=dijit.byId(this._uniqueId+"_urlInput");this._textInput=dijit.byId(this._uniqueId+"_textInput");this._setButton=dijit.byId(this._uniqueId+"_setButton");this.connect(dijit.byId(this._uniqueId+"_cancelButton"),"onClick",function(){this.dropDown.onCancel()});
this._urlInput&&this.connect(this._urlInput,"onChange","_checkAndFixInput");this._textInput&&this.connect(this._textInput,"onChange","_checkAndFixInput");this._urlRegExp=RegExp("^"+this.urlRegExp+"$","i");this._emailRegExp=RegExp("^"+this.emailRegExp+"$","i");this._urlInput.isValid=dojo.hitch(this,function(){var a=this._urlInput.get("value");return this._urlRegExp.test(a)||this._emailRegExp.test(a)});this._connectTagEvents();this.inherited(arguments)},_checkAndFixInput:function(){var a=this,b=this._urlInput.get("value");
if(this._delayedCheck)clearTimeout(this._delayedCheck),this._delayedCheck=null;this._delayedCheck=setTimeout(function(){var c=b,d=!1,e=!1;c&&c.length>1&&(c=dojo.trim(c),c.indexOf("mailto:")!==0&&(c.indexOf("/")>0?c.indexOf("://")===-1&&c.charAt(0)!=="/"&&c.indexOf("./")!==0&&a._hostRxp.test(c)&&(d=!0):a._userAtRxp.test(c)&&(e=!0)));d&&a._urlInput.set("value","http://"+c);e&&a._urlInput.set("value","mailto:"+c);a._setButton.set("disabled",!a._isValid())},250)},_connectTagEvents:function(){this.editor.onLoadDeferred.addCallback(dojo.hitch(this,
function(){this.connect(this.editor.editNode,"ondblclick",this._onDblClick)}))},_isValid:function(){return this._urlInput.isValid()&&this._textInput.isValid()},_setContent:function(a){this.dropDown.set({parserScope:"dojo",content:a})},_checkValues:function(a){if(a&&a.urlInput)a.urlInput=a.urlInput.replace(/"/g,"&quot;");return a},setValue:function(a){this._onCloseDialog();if(dojo.isIE<9){var b=dijit.range.getSelection(this.editor.window).getRangeAt(0).endContainer;if(b.nodeType===3)b=b.parentNode;
b&&b.nodeName&&b.nodeName.toLowerCase()!==this.tag&&(b=dojo.withGlobal(this.editor.window,"getSelectedElement",dijit._editor.selection,[this.tag]));b&&b.nodeName&&b.nodeName.toLowerCase()===this.tag&&this.editor.queryCommandEnabled("unlink")&&(dojo.withGlobal(this.editor.window,"selectElementChildren",dijit._editor.selection,[b]),this.editor.execCommand("unlink"))}a=this._checkValues(a);this.editor.execCommand("inserthtml",dojo.string.substitute(this.htmlTemplate,a))},_onCloseDialog:function(){this.editor.focus()},
_getCurrentValues:function(a){var b,c,d;a&&a.tagName.toLowerCase()===this.tag?(b=a.getAttribute("_djrealurl")||a.getAttribute("href"),d=a.getAttribute("target")||"_self",c=a.textContent||a.innerText,dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[a,!0])):c=dojo.withGlobal(this.editor.window,dijit._editor.selection.getSelectedText);return{urlInput:b||"",textInput:c||"",targetSelect:d||""}},_onOpenDialog:function(){var a;if(dojo.isIE<9){a=dijit.range.getSelection(this.editor.window).getRangeAt(0).endContainer;
if(a.nodeType===3)a=a.parentNode;a&&a.nodeName&&a.nodeName.toLowerCase()!==this.tag&&(a=dojo.withGlobal(this.editor.window,"getSelectedElement",dijit._editor.selection,[this.tag]))}else a=dojo.withGlobal(this.editor.window,"getAncestorElement",dijit._editor.selection,[this.tag]);this.dropDown.reset();this._setButton.set("disabled",!0);this.dropDown.set("value",this._getCurrentValues(a))},_onDblClick:function(a){if(a&&a.target&&(a=a.target,(a.tagName?a.tagName.toLowerCase():"")===this.tag&&dojo.attr(a,
"href")))dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[a]),this.editor.onDisplayChanged(),setTimeout(dojo.hitch(this,function(){this.button.set("disabled",!1);this.button.openDropDown()}),10)}}),dojo.declare("dijit._editor.plugins.ImgLinkDialog",[dijit._editor.plugins.LinkDialog],{linkDialogTemplate:"<table><tr><td><label for='${id}_urlInput'>${url}</label></td><td><input dojoType='dijit.form.ValidationTextBox' regExp='${urlRegExp}' required='true' id='${id}_urlInput' name='urlInput' intermediateChanges='true'/></td></tr><tr><td><label for='${id}_textInput'>${text}</label></td><td><input dojoType='dijit.form.ValidationTextBox' required='false' id='${id}_textInput' name='textInput' intermediateChanges='true'/></td></tr><tr><td></td><td></td></tr><tr><td colspan='2'><button dojoType='dijit.form.Button' type='submit' id='${id}_setButton'>${set}</button><button dojoType='dijit.form.Button' type='button' id='${id}_cancelButton'>${buttonCancel}</button></td></tr></table>",
htmlTemplate:'<img src="${urlInput}" _djrealurl="${urlInput}" alt="${textInput}" />',tag:"img",_getCurrentValues:function(a){var b,c;a&&a.tagName.toLowerCase()===this.tag?(b=a.getAttribute("_djrealurl")||a.getAttribute("src"),c=a.getAttribute("alt"),dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[a,!0])):c=dojo.withGlobal(this.editor.window,dijit._editor.selection.getSelectedText);return{urlInput:b||"",textInput:c||""}},_isValid:function(){return this._urlInput.isValid()},
_connectTagEvents:function(){this.inherited(arguments);this.editor.onLoadDeferred.addCallback(dojo.hitch(this,function(){this.connect(this.editor.editNode,"onmousedown",this._selectTag)}))},_selectTag:function(a){if(a&&a.target)a=a.target,(a.tagName?a.tagName.toLowerCase():"")===this.tag&&dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[a])},_checkValues:function(a){if(a&&a.urlInput)a.urlInput=a.urlInput.replace(/"/g,"&quot;");if(a&&a.textInput)a.textInput=a.textInput.replace(/"/g,
"&quot;");return a},_onDblClick:function(a){if(a&&a.target&&(a=a.target,(a.tagName?a.tagName.toLowerCase():"")===this.tag&&dojo.attr(a,"src")))dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[a]),this.editor.onDisplayChanged(),setTimeout(dojo.hitch(this,function(){this.button.set("disabled",!1);this.button.openDropDown()}),10)}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin)switch(a.args.name){case "createLink":a.plugin=new dijit._editor.plugins.LinkDialog({command:a.args.name});
break;case "insertImage":a.plugin=new dijit._editor.plugins.ImgLinkDialog({command:a.args.name})}}));