/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._editor.plugins.ViewSource"]||(dojo._hasResource["dijit._editor.plugins.ViewSource"]=!0,dojo.provide("dijit._editor.plugins.ViewSource"),dojo.require("dojo.window"),dojo.require("dojo.i18n"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.form.Button"),dojo.requireLocalization("dijit._editor","commands",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dijit._editor.plugins.ViewSource",dijit._editor._Plugin,
{stripScripts:!0,stripComments:!0,stripIFrames:!0,readOnly:!1,_fsPlugin:null,toggle:function(){if(dojo.isWebKit)this._vsFocused=!0;this.button.set("checked",!this.button.get("checked"))},_initButton:function(){var a=dojo.i18n.getLocalization("dijit._editor","commands"),b=this.editor;this.button=new dijit.form.ToggleButton({label:a.viewSource,dir:b.dir,lang:b.lang,showLabel:!1,iconClass:this.iconClassPrefix+" "+this.iconClassPrefix+"ViewSource",tabIndex:"-1",onChange:dojo.hitch(this,"_showSource")});
if(dojo.isIE==7)this._ieFixNode=dojo.create("div",{style:{opacity:"0",zIndex:"-1000",position:"absolute",top:"-1000px"}},dojo.body());this.button.set("readOnly",!1)},setEditor:function(a){this.editor=a;this._initButton();this.editor.addKeyHandler(dojo.keys.F12,!0,!0,dojo.hitch(this,function(a){this.button.focus();this.toggle();dojo.stopEvent(a);setTimeout(dojo.hitch(this,function(){this.editor.focus()}),100)}))},_showSource:function(a){var b=this.editor,d=b._plugins,c;this._sourceShown=a;var e=this;
try{this.sourceArea||this._createSourceView();if(a){b._sourceQueryCommandEnabled=b.queryCommandEnabled;b.queryCommandEnabled=function(a){return a.toLowerCase()==="viewsource"?!0:!1};this.editor.onDisplayChanged();c=b.get("value");c=this._filter(c);b.set("value",c);this._pluginList=[];dojo.forEach(d,function(a){a instanceof dijit._editor.plugins.ViewSource||a.set("disabled",!0)});if(this._fsPlugin)this._fsPlugin._getAltViewNode=function(){return e.sourceArea};this.sourceArea.value=c;var h=dojo._getMarginSize(b.iframe.parentNode);
dojo.marginBox(this.sourceArea,{w:h.w,h:h.h});dojo.style(b.iframe,"display","none");dojo.style(this.sourceArea,{display:"block"});this._resizeHandle=dojo.connect(window,"onresize",this,function(){var a=dojo.window.getBox();if("_prevW"in this&&"_prevH"in this)if(a.w===this._prevW&&a.h===this._prevH)return;else this._prevW=a.w,this._prevH=a.h;else this._prevW=a.w,this._prevH=a.h;this._resizer&&(clearTimeout(this._resizer),delete this._resizer);this._resizer=setTimeout(dojo.hitch(this,function(){delete this._resizer;
this._resize()}),10)});setTimeout(dojo.hitch(this,this._resize),100);this.editor.onNormalizedDisplayChanged();this.editor.__oldGetValue=this.editor.getValue;this.editor.getValue=dojo.hitch(this,function(){var a=this.sourceArea.value;return a=this._filter(a)})}else{if(!b._sourceQueryCommandEnabled)return;dojo.disconnect(this._resizeHandle);delete this._resizeHandle;if(this.editor.__oldGetValue)this.editor.getValue=this.editor.__oldGetValue,delete this.editor.__oldGetValue;b.queryCommandEnabled=b._sourceQueryCommandEnabled;
if(!this._readOnly)c=this.sourceArea.value,c=this._filter(c),b.beginEditing(),b.set("value",c),b.endEditing();dojo.forEach(d,function(a){a.set("disabled",!1)});dojo.style(this.sourceArea,"display","none");dojo.style(b.iframe,"display","block");delete b._sourceQueryCommandEnabled;this.editor.onDisplayChanged()}setTimeout(dojo.hitch(this,function(){var a=b.domNode.parentNode;a&&(a=dijit.getEnclosingWidget(a))&&a.resize&&a.resize();b.resize()}),300)}catch(f){console.log(f)}},updateState:function(){this.button.set("disabled",
this.get("disabled"))},_resize:function(){var a=this.editor,b=a.getHeaderHeight(),d=a.getFooterHeight(),c=dojo.position(a.domNode),e=dojo._getPadBorderExtents(a.iframe.parentNode),h=dojo._getMarginExtents(a.iframe.parentNode),f=dojo._getPadBorderExtents(a.domNode),g=dojo._getMarginExtents(a.domNode),c={w:c.w-(f.w+g.w),h:c.h-(b+f.h+g.h+d)};if(this._fsPlugin&&this._fsPlugin.isFullscreen)g=dojo.window.getBox(),c.w=g.w-f.w,c.h=g.h-(b+f.h+d);dojo.isIE&&(c.h-=2);if(this._ieFixNode)b=-this._ieFixNode.offsetTop/
1E3,c.w=Math.floor((c.w+0.9)/b),c.h=Math.floor((c.h+0.9)/b);dojo.marginBox(this.sourceArea,{w:c.w-(e.w+h.w),h:c.h-(e.h+h.h)});dojo.marginBox(a.iframe.parentNode,{h:c.h})},_createSourceView:function(){var a=this.editor,b=a._plugins;this.sourceArea=dojo.create("textarea");if(this.readOnly)dojo.attr(this.sourceArea,"readOnly",!0),this._readOnly=!0;dojo.style(this.sourceArea,{padding:"0px",margin:"0px",borderWidth:"0px",borderStyle:"none"});dojo.place(this.sourceArea,a.iframe,"before");dojo.isIE&&a.iframe.parentNode.lastChild!==
a.iframe&&dojo.style(a.iframe.parentNode.lastChild,{width:"0px",height:"0px",padding:"0px",margin:"0px",borderWidth:"0px",borderStyle:"none"});a._viewsource_oldFocus=a.focus;var d=this;a.focus=function(){if(d._sourceShown)d.setSourceAreaCaret();else try{this._vsFocused?(delete this._vsFocused,dijit.focus(a.editNode)):a._viewsource_oldFocus()}catch(b){console.log(b)}};var c,e;for(c=0;c<b.length;c++)if((e=b[c])&&(e.declaredClass==="dijit._editor.plugins.FullScreen"||e.declaredClass===dijit._scopeName+
"._editor.plugins.FullScreen")){this._fsPlugin=e;break}if(this._fsPlugin)this._fsPlugin._viewsource_getAltViewNode=this._fsPlugin._getAltViewNode,this._fsPlugin._getAltViewNode=function(){return d._sourceShown?d.sourceArea:this._viewsource_getAltViewNode()};this.connect(this.sourceArea,"onkeydown",dojo.hitch(this,function(b){this._sourceShown&&b.keyCode==dojo.keys.F12&&b.ctrlKey&&b.shiftKey&&(this.button.focus(),this.button.set("checked",!1),setTimeout(dojo.hitch(this,function(){a.focus()}),100),
dojo.stopEvent(b))}))},_stripScripts:function(a){a&&(a=a.replace(/<\s*script[^>]*>((.|\s)*?)<\\?\/\s*script\s*>/ig,""),a=a.replace(/<\s*script\b([^<>]|\s)*>?/ig,""),a=a.replace(/<[^>]*=(\s|)*[("|')]javascript:[^$1][(\s|.)]*[$1][^>]*>/ig,""));return a},_stripComments:function(a){a&&(a=a.replace(/<\!--(.|\s){1,}?--\>/g,""));return a},_stripIFrames:function(a){a&&(a=a.replace(/<\s*iframe[^>]*>((.|\s)*?)<\\?\/\s*iframe\s*>/ig,""));return a},_filter:function(a){a&&(this.stripScripts&&(a=this._stripScripts(a)),
this.stripComments&&(a=this._stripComments(a)),this.stripIFrames&&(a=this._stripIFrames(a)));return a},setSourceAreaCaret:function(){var a=dojo.global,b=this.sourceArea;dijit.focus(b);this._sourceShown&&!this.readOnly&&(dojo.isIE?this.sourceArea.createTextRange&&(a=b.createTextRange(),a.collapse(!0),a.moveStart("character",-99999),a.moveStart("character",0),a.moveEnd("character",0),a.select()):a.getSelection&&b.setSelectionRange&&b.setSelectionRange(0,0))},destroy:function(){this._ieFixNode&&dojo.body().removeChild(this._ieFixNode);
this._resizer&&(clearTimeout(this._resizer),delete this._resizer);this._resizeHandle&&(dojo.disconnect(this._resizeHandle),delete this._resizeHandle);this.inherited(arguments)}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="viewsource")a.plugin=new dijit._editor.plugins.ViewSource({readOnly:"readOnly"in a.args?a.args.readOnly:!1,stripComments:"stripComments"in a.args?a.args.stripComments:!0,stripScripts:"stripScripts"in a.args?a.args.stripScripts:
!0,stripIFrames:"stripIFrames"in a.args?a.args.stripIFrames:!0})}));