/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.drawing.manager.Canvas"]||(dojo._hasResource["dojox.drawing.manager.Canvas"]=!0,dojo.provide("dojox.drawing.manager.Canvas"),function(){dojox.drawing.manager.Canvas=dojox.drawing.util.oo.declare(function(a){dojo.mixin(this,a);var b=dojo.contentBox(this.srcRefNode);this.height=this.parentHeight=b.h;this.width=this.parentWidth=b.w;this.domNode=dojo.create("div",{id:"canvasNode"},this.srcRefNode);dojo.style(this.domNode,{width:this.width,height:"auto"});dojo.setSelectable(this.domNode,
!1);this.id=this.id||this.util.uid("surface");console.info("create canvas");this.gfxSurface=dojox.gfx.createSurface(this.domNode,this.width,this.height);this.gfxSurface.whenLoaded(this,function(){setTimeout(dojo.hitch(this,function(){this.surfaceReady=!0;if(!dojo.isIE&&dojox.gfx.renderer=="silverlight")this.id=this.domNode.firstChild.id;this.underlay=this.gfxSurface.createGroup();this.surface=this.gfxSurface.createGroup();this.overlay=this.gfxSurface.createGroup();this.surface.setTransform({dx:0,
dy:0,xx:1,yy:1});this.gfxSurface.getDimensions=dojo.hitch(this.gfxSurface,"getDimensions");a.callback&&a.callback(this.domNode)}),500)});this._mouseHandle=this.mouse.register(this)},{zoom:1,useScrollbars:!0,baseClass:"drawingCanvas",resize:function(a,b){this.parentWidth=a;this.parentHeight=b;this.setDimensions(a,b)},setDimensions:function(a,b,c,e){var d=this.getScrollWidth();this.width=Math.max(a,this.parentWidth);this.height=Math.max(b,this.parentHeight);this.height>this.parentHeight&&(this.width-=
d);this.width>this.parentWidth&&(this.height-=d);this.mouse.resize(this.width,this.height);this.gfxSurface.setDimensions(this.width,this.height);this.domNode.parentNode.scrollTop=e||0;this.domNode.parentNode.scrollLeft=c||0;this.useScrollbars?dojo.style(this.domNode.parentNode,{overflowY:this.height>this.parentHeight?"scroll":"hidden",overflowX:this.width>this.parentWidth?"scroll":"hidden"}):dojo.style(this.domNode.parentNode,{overflowY:"hidden",overflowX:"hidden"})},setZoom:function(a){this.zoom=
a;this.surface.setTransform({xx:a,yy:a});this.setDimensions(this.width*a,this.height*a)},onScroll:function(){},getScrollOffset:function(){return{top:this.domNode.parentNode.scrollTop,left:this.domNode.parentNode.scrollLeft}},getScrollWidth:function(){var a=dojo.create("div");a.innerHTML='<div style="width:50px;height:50px;overflow:hidden;position:absolute;top:0;left:-1000px;"><div style="height:100px;"></div>';a=a.firstChild;dojo.body().appendChild(a);var b=dojo.contentBox(a).h;dojo.style(a,"overflow",
"scroll");var c=b-dojo.contentBox(a).h;dojo.destroy(a);this.getScrollWidth=function(){return c};return c}})}());