/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.date.hebrew.locale"])dojo._hasResource["dojox.date.hebrew.locale"]=!0,dojo.provide("dojox.date.hebrew.locale"),dojo.require("dojox.date.hebrew.Date"),dojo.require("dojox.date.hebrew.numerals"),dojo.require("dojo.regexp"),dojo.require("dojo.string"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojo.cldr","hebrew",null,"ROOT,ar,el,fi,he"),function(){function l(a,e,c,h,i){return i.replace(/([a-z])\1*/ig,function(f){var b,d,g=f.charAt(0),f=f.length,h=["abbr","wide",
"narrow"];switch(g){case "y":b=c.match(/^he(?:-.+)?$/)?dojox.date.hebrew.numerals.getYearHebrewLetters(a.getFullYear()):String(a.getFullYear());break;case "M":b=a.getMonth();f<3?(!a.isLeapYear(a.getFullYear())&&b>5&&b--,c.match(/^he(?:-.+)?$/)?b=dojox.date.hebrew.numerals.getMonthHebrewLetters(b):(b+=1,d=!0)):b=dojox.date.hebrew.locale.getNames("months",h[f-3],"format",c,a)[b];break;case "d":c.match(/^he(?:-.+)?$/)?b=a.getDateLocalized(c):(b=a.getDate(),d=!0);break;case "E":b=a.getDay();f<3?(b+=1,
d=!0):(g=["days-format",h[f-3]].join("-"),b=e[g][b]);break;case "a":b=a.getHours()<12?"am":"pm";b=e["dayPeriods-format-wide-"+b];break;case "h":case "H":case "K":case "k":d=a.getHours();switch(g){case "h":b=d%12||12;break;case "H":b=d;break;case "K":b=d%12;break;case "k":b=d||24}d=!0;break;case "m":b=a.getMinutes();d=!0;break;case "s":b=a.getSeconds();d=!0;break;case "S":b=Math.round(a.getMilliseconds()*Math.pow(10,f-3));d=!0;break;case "z":b="";break;default:throw Error("dojox.date.hebrew.locale.formatPattern: invalid pattern char: "+
i);}d&&(b=dojo.string.pad(b,f));return b})}function k(a,e,c,h){var i=function(b){return b},e=e||i,c=c||i,h=h||i,f=a.match(/(''|[^'])+/g),b=a.charAt(0)=="'";dojo.forEach(f,function(a,g){a?(f[g]=(b?c:e)(a),b=!b):f[g]=""});return h(f.join(""))}function j(a,e,c,h){var h=dojo.regexp.escapeString(h),i=dojo.i18n.normalizeLocale(c.locale);return h.replace(/([a-z])\1*/ig,function(f){var b;b=f.charAt(0);var d=f.length,g="";c.strict?d>1&&(g="0{"+(d-1)+"}"):g="0?";switch(b){case "y":b="\\S+";break;case "M":b=
i.match("^he(?:-.+)?$")?d>2?"\\S+ ?\\S+":"\\S{1,4}":d>2?"\\S+ ?\\S+":g+"[1-9]|1[0-2]";break;case "d":b=i.match("^he(?:-.+)?$")?"\\S['\"'\u05f3]{1,2}\\S?":"[12]\\d|"+g+"[1-9]|30";break;case "E":b=i.match("^he(?:-.+)?$")?d>3?"\\S+ ?\\S+":"\\S":"\\S+";break;case "h":b=g+"[1-9]|1[0-2]";break;case "k":b=g+"\\d|1[01]";break;case "H":b=g+"\\d|1\\d|2[0-3]";break;case "K":b=g+"[1-9]|1\\d|2[0-4]";break;case "m":case "s":b=g+"\\d|[0-5]\\d";break;case "S":b="\\d{"+d+"}";break;case "a":d=c.am||e["dayPeriods-format-wide-am"];
g=c.pm||e["dayPeriods-format-wide-pm"];c.strict?b=d+"|"+g:(b=d+"|"+g,d!=d.toLowerCase()&&(b+="|"+d.toLowerCase()),g!=g.toLowerCase()&&(b+="|"+g.toLowerCase()));break;default:b=".*"}a&&a.push(f);return"("+b+")"}).replace(/[\xa0 ]/g,"[\\s\\xa0]")}dojox.date.hebrew.locale.format=function(a,e){var e=e||{},c=dojo.i18n.normalizeLocale(e.locale),h=e.formatLength||"short",i=dojox.date.hebrew.locale._getHebrewBundle(c),f=[],b=dojo.hitch(this,l,a,i,c,e.fullYear);if(e.selector=="year")return f=a.getFullYear(),
c.match(/^he(?:-.+)?$/)?dojox.date.hebrew.numerals.getYearHebrewLetters(f):f;e.selector!="time"&&(c=e.datePattern||i["dateFormat-"+h])&&f.push(k(c,b));e.selector!="date"&&(c=e.timePattern||i["timeFormat-"+h])&&f.push(k(c,b));return f.join(" ")};dojox.date.hebrew.locale.regexp=function(a){return dojox.date.hebrew.locale._parseInfo(a).regexp};dojox.date.hebrew.locale._parseInfo=function(a){var a=a||{},e=dojo.i18n.normalizeLocale(a.locale),e=dojox.date.hebrew.locale._getHebrewBundle(e),c=a.formatLength||
"short",h=a.datePattern||e["dateFormat-"+c],c=a.timePattern||e["timeFormat-"+c],i=[];return{regexp:k(a.selector=="date"?h:a.selector=="time"?c:c===void 0?h:h+" "+c,dojo.hitch(this,j,i,e,a)),tokens:i,bundle:e}};dojox.date.hebrew.locale.parse=function(a,e){a=a.replace(/[\u200E\u200F\u202A-\u202E]/g,"");e||(e={});var c=dojox.date.hebrew.locale._parseInfo(e),h=c.tokens,i=c.bundle,c=RegExp("^"+c.regexp+"$"),f=c.exec(a),b=dojo.i18n.normalizeLocale(e.locale);if(!f)return console.debug("dojox.date.hebrew.locale.parse: value  "+
a+" doesn't match pattern   "+c),null;var d=[5730,3,23,0,0,0,0],g="",j=0,k=["abbr","wide","narrow"];dojo.every(f,function(a,c){if(!c)return!0;var f=h[c-1],m=f.length;switch(f.charAt(0)){case "y":d[0]=b.match(/^he(?:-.+)?$/)?dojox.date.hebrew.numerals.parseYearHebrewLetters(a):Number(a);break;case "M":if(m>2){var f=dojox.date.hebrew.locale.getNames("months",k[m-3],"format",b,new dojox.date.hebrew.Date(5769,1,1)),l=dojox.date.hebrew.locale.getNames("months",k[m-3],"format",b,new dojox.date.hebrew.Date(5768,
1,1));e.strict||(a=a.replace(".","").toLowerCase(),f=dojo.map(f,function(a){return a?a.replace(".","").toLowerCase():a}),l=dojo.map(l,function(a){return a?a.replace(".","").toLowerCase():a}));var n=a,a=dojo.indexOf(f,n);if(a==-1&&(a=dojo.indexOf(l,n),a==-1))return!1;j=m}else b.match(/^he(?:-.+)?$/)?a=dojox.date.hebrew.numerals.parseMonthHebrewLetters(a):a--;d[1]=Number(a);break;case "D":d[1]=0;case "d":d[2]=b.match(/^he(?:-.+)?$/)?dojox.date.hebrew.numerals.parseDayHebrewLetters(a):Number(a);break;
case "a":m=e.am||i["dayPeriods-format-wide-am"];f=e.pm||i["dayPeriods-format-wide-pm"];e.strict||(l=/\./g,a=a.replace(l,"").toLowerCase(),m=m.replace(l,"").toLowerCase(),f=f.replace(l,"").toLowerCase());if(e.strict&&a!=m&&a!=f)return!1;g=a==f?"p":a==m?"a":"";break;case "K":a==24&&(a=0);case "h":case "H":case "k":d[3]=Number(a);break;case "m":d[4]=Number(a);break;case "s":d[5]=Number(a);break;case "S":d[6]=Number(a)}return!0});c=+d[3];g==="p"&&c<12?d[3]=c+12:g==="a"&&c==12&&(d[3]=0);c=new dojox.date.hebrew.Date(d[0],
d[1],d[2],d[3],d[4],d[5],d[6]);j<3&&d[1]>=5&&!c.isLeapYear(c.getFullYear())&&c.setMonth(d[1]+1);return c}}(),function(){var l=[];dojox.date.hebrew.locale.addCustomFormats=function(k,j){l.push({pkg:k,name:j})};dojox.date.hebrew.locale._getHebrewBundle=function(k){var j={};dojo.forEach(l,function(a){a=dojo.i18n.getLocalization(a.pkg,a.name,k);j=dojo.mixin(j,a)},this);return j}}(),dojox.date.hebrew.locale.addCustomFormats("dojo.cldr","hebrew"),dojox.date.hebrew.locale.getNames=function(l,k,j,a,e){var c,
a=dojox.date.hebrew.locale._getHebrewBundle(a),k=[l,j,k];j=="standAlone"&&(j=k.join("-"),c=a[j],c[0]==1&&(c=void 0));k[1]="format";j=(c||a[k.join("-")]).concat();l=="months"&&(e.isLeapYear(e.getFullYear())?(k.push("leap"),j[6]=a[k.join("-")]):delete j[5]);return j};