/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dijit._editor.range"]&&(dojo._hasResource["dijit._editor.range"]=!0,dojo.provide("dijit._editor.range"),dijit.range={},dijit.range.getIndex=function(a,b){for(var c=[],d=[],e=a,f,g;a!=b;){var h=0;for(f=a.parentNode;g=f.childNodes[h++];)if(g===a){--h;break}c.unshift(h);d.unshift(h-f.childNodes.length);a=f}if(c.length>0&&e.nodeType==3){for(g=e.previousSibling;g&&g.nodeType==3;)c[c.length-1]--,g=g.previousSibling;for(g=e.nextSibling;g&&g.nodeType==3;)d[d.length-1]++,g=g.nextSibling}return{o:c,
r:d}},dijit.range.getNode=function(a,b){if(!dojo.isArray(a)||a.length==0)return b;var c=b;dojo.every(a,function(a){if(a>=0&&a<c.childNodes.length)c=c.childNodes[a];else return c=null,!1;return!0});return c},dijit.range.getCommonAncestor=function(a,b,c){for(var c=c||a.ownerDocument.body,d=function(a){for(var b=[];a;)if(b.unshift(a),a!==c)a=a.parentNode;else break;return b},a=d(a),b=d(b),d=Math.min(a.length,b.length),e=a[0],f=1;f<d;f++)if(a[f]===b[f])e=a[f];else break;return e},dijit.range.getAncestor=
function(a,b,c){for(c=c||a.ownerDocument.body;a&&a!==c;){var d=a.nodeName.toUpperCase();if(b.test(d))return a;a=a.parentNode}return null},dijit.range.BlockTagNames=/^(?:P|DIV|H1|H2|H3|H4|H5|H6|ADDRESS|PRE|OL|UL|LI|DT|DE)$/,dijit.range.getBlockAncestor=function(a,b,c){for(var c=c||a.ownerDocument.body,b=b||dijit.range.BlockTagNames,d=null,e;a&&a!==c;){var f=a.nodeName.toUpperCase();!d&&b.test(f)&&(d=a);!e&&/^(?:BODY|TD|TH|CAPTION)$/.test(f)&&(e=a);a=a.parentNode}return{blockNode:d,blockContainer:e||
a.ownerDocument.body}},dijit.range.atBeginningOfContainer=function(a,b,c){var d=!1,e=c==0;!e&&b.nodeType==3&&/^[\s\xA0]+$/.test(b.nodeValue.substr(0,c))&&(e=!0);if(e)for(d=!0;b&&b!==a;){if(b.previousSibling){d=!1;break}b=b.parentNode}return d},dijit.range.atEndOfContainer=function(a,b,c){var d=!1,e=c==(b.length||b.childNodes.length);!e&&b.nodeType==3&&/^[\s\xA0]+$/.test(b.nodeValue.substr(c))&&(e=!0);if(e)for(d=!0;b&&b!==a;){if(b.nextSibling){d=!1;break}b=b.parentNode}return d},dijit.range.adjacentNoneTextNode=
function(a,b){for(var c=a,d=0-a.length||0,e=b?"nextSibling":"previousSibling";c;){if(c.nodeType!=3)break;d+=c.length;c=c[e]}return[c,d]},dijit.range._w3c=Boolean(window.getSelection),dijit.range.create=function(a){return dijit.range._w3c?(a||dojo.global).document.createRange():new dijit.range.W3CRange},dijit.range.getSelection=function(a,b){if(dijit.range._w3c)return a.getSelection();else{var c=new dijit.range.ie.selection(a);b||c._getCurrentSelection();return c}},!dijit.range._w3c))dijit.range.ie=
{cachedSelection:{},selection:function(a){this._ranges=[];this.addRange=function(a,c){this._ranges.push(a);c||a._select();this.rangeCount=this._ranges.length};this.removeAllRanges=function(){this._ranges=[];this.rangeCount=0};this.getRangeAt=function(a){return this._ranges[a]};this._getCurrentSelection=function(){this.removeAllRanges();var b;b=a.document.selection.createRange();(b=a.document.selection.type.toUpperCase()=="CONTROL"?new dijit.range.W3CRange(dijit.range.ie.decomposeControlRange(b)):
new dijit.range.W3CRange(dijit.range.ie.decomposeTextRange(b)))&&this.addRange(b,!0)}},decomposeControlRange:function(a){var b=a.item(0),c=a.item(a.length-1),a=b.parentNode,d=c.parentNode,b=dijit.range.getIndex(b,a).o,c=dijit.range.getIndex(c,d).o+1;return[a,b,d,c]},getEndPoint:function(a,b){var c=a.duplicate();c.collapse(!b);var d="EndTo"+(b?"End":"Start"),e=c.parentElement(),f,g,h;e.childNodes.length>0?dojo.every(e.childNodes,function(b,j){var i;if(b.nodeType!=3)if(c.moveToElementText(b),c.compareEndPoints(d,
a)>0)if(h&&h.nodeType==3)f=h,i=!0;else return f=e,g=j,!1;else{if(j==e.childNodes.length-1)return f=e,g=e.childNodes.length,!1}else j==e.childNodes.length-1&&(f=b,i=!0);if(i&&f){f=(i=dijit.range.adjacentNoneTextNode(f)[0])?i.nextSibling:e.firstChild;var k=dijit.range.adjacentNoneTextNode(f);i=k[0];k=k[1];i?(c.moveToElementText(i),c.collapse(!1)):c.moveToElementText(e);c.setEndPoint(d,a);g=c.text.length-k;return!1}h=b;return!0}):(f=e,g=0);if(!b&&f.nodeType==1&&g==f.childNodes.length){var j=f.nextSibling;
j&&j.nodeType==3&&(f=j,g=0)}return[f,g]},setEndPoint:function(a,b,c){var a=a.duplicate(),d;if(b.nodeType!=3)if(c>0){if(d=b.childNodes[c-1])if(d.nodeType==3)b=d,c=d.length;else if(d.nextSibling&&d.nextSibling.nodeType==3)b=d.nextSibling,c=0;else{a.moveToElementText(d.nextSibling?d:b);var e=d.parentNode;d=e.insertBefore(d.ownerDocument.createTextNode(" "),d.nextSibling);a.collapse(!1);e.removeChild(d)}}else a.moveToElementText(b),a.collapse(!0);b.nodeType==3&&(d=dijit.range.adjacentNoneTextNode(b),
e=d[0],d=d[1],e?(a.moveToElementText(e),a.collapse(!1),e.contentEditable!="inherit"&&d++):(a.moveToElementText(b.parentNode),a.collapse(!0)),c+=d,c>0&&a.move("character",c)!=c&&console.error("Error when moving!"));return a},decomposeTextRange:function(a){var b=dijit.range.ie.getEndPoint(a),c=b[0],d=b[1],e=b[0],b=b[1];a.htmlText.length&&(a.htmlText==a.text?b=d+a.text.length:(b=dijit.range.ie.getEndPoint(a,!0),e=b[0],b=b[1]));return[c,d,e,b]},setRange:function(a,b,c,d,e,f){b=dijit.range.ie.setEndPoint(a,
b,c);a.setEndPoint("StartToStart",b);if(!f)var g=dijit.range.ie.setEndPoint(a,d,e);a.setEndPoint("EndToEnd",g||b);return a}},dojo.declare("dijit.range.W3CRange",null,{constructor:function(){arguments.length>0?(this.setStart(arguments[0][0],arguments[0][1]),this.setEnd(arguments[0][2],arguments[0][3])):(this.startContainer=this.commonAncestorContainer=null,this.startOffset=0,this.endContainer=null,this.endOffset=0,this.collapsed=!0)},_updateInternal:function(){this.commonAncestorContainer=this.startContainer!==
this.endContainer?dijit.range.getCommonAncestor(this.startContainer,this.endContainer):this.startContainer;this.collapsed=this.startContainer===this.endContainer&&this.startOffset==this.endOffset},setStart:function(a,b){b=parseInt(b);if(!(this.startContainer===a&&this.startOffset==b))delete this._cachedBookmark,this.startContainer=a,this.startOffset=b,this.endContainer?this._updateInternal():this.setEnd(a,b)},setEnd:function(a,b){b=parseInt(b);if(!(this.endContainer===a&&this.endOffset==b))delete this._cachedBookmark,
this.endContainer=a,this.endOffset=b,this.startContainer?this._updateInternal():this.setStart(a,b)},setStartAfter:function(a,b){this._setPoint("setStart",a,b,1)},setStartBefore:function(a,b){this._setPoint("setStart",a,b,0)},setEndAfter:function(a,b){this._setPoint("setEnd",a,b,1)},setEndBefore:function(a,b){this._setPoint("setEnd",a,b,0)},_setPoint:function(a,b,c,d){c=dijit.range.getIndex(b,b.parentNode).o;this[a](b.parentNode,c.pop()+d)},_getIERange:function(){var a=(this._body||this.endContainer.ownerDocument.body).createTextRange();
dijit.range.ie.setRange(a,this.startContainer,this.startOffset,this.endContainer,this.endOffset,this.collapsed);return a},getBookmark:function(){this._getIERange();return this._cachedBookmark},_select:function(){this._getIERange().select()},deleteContents:function(){this._getIERange().pasteHTML("");this.endContainer=this.startContainer;this.endOffset=this.startOffset;this.collapsed=!0},cloneRange:function(){var a=new dijit.range.W3CRange([this.startContainer,this.startOffset,this.endContainer,this.endOffset]);
a._body=this._body;return a},detach:function(){this.startContainer=this.commonAncestorContainer=this._body=null;this.startOffset=0;this.endContainer=null;this.endOffset=0;this.collapsed=!0}});