/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dijit._editor.RichText"]){dojo._hasResource["dijit._editor.RichText"]=!0;dojo.provide("dijit._editor.RichText");dojo.require("dijit._Widget");dojo.require("dijit._CssStateMixin");dojo.require("dijit._editor.selection");dojo.require("dijit._editor.range");dojo.require("dijit._editor.html");if(!dojo.config.useXDomain||dojo.config.allowXdRichTextSave)if(dojo._postLoad)(function(){var a=dojo.doc.createElement("textarea");a.id=dijit._scopeName+"._editor.RichText.value";dojo.style(a,
{display:"none",position:"absolute",top:"-100px",height:"3px",width:"3px"});dojo.body().appendChild(a)})();else try{dojo.doc.write('<textarea id="'+dijit._scopeName+'._editor.RichText.value" style="display:none;position:absolute;top:-100px;left:-100px;height:3px;width:3px;overflow:hidden;"></textarea>')}catch(e){}dojo.declare("dijit._editor.RichText",[dijit._Widget,dijit._CssStateMixin],{constructor:function(a){this.contentPreFilters=[];this.contentPostFilters=[];this.contentDomPreFilters=[];this.contentDomPostFilters=
[];this.editingAreaStyleSheets=[];this.events=[].concat(this.events);this._keyHandlers={};if(a&&dojo.isString(a.value))this.value=a.value;this.onLoadDeferred=new dojo.Deferred},baseClass:"dijitEditor",inheritWidth:!1,focusOnLoad:!1,name:"",styleSheets:"",height:"300px",minHeight:"1em",isClosed:!0,isLoaded:!1,_SEPARATOR:"@@**%%__RICHTEXTBOUNDRY__%%**@@",_NAME_CONTENT_SEP:"@@**%%:%%**@@",onLoadDeferred:null,isTabIndent:!1,disableSpellCheck:!1,postCreate:function(){"textarea"==this.domNode.tagName.toLowerCase()&&
console.warn("RichText should not be used with the TEXTAREA tag.  See dijit._editor.RichText docs.");this.contentPreFilters=[dojo.hitch(this,"_preFixUrlAttributes")].concat(this.contentPreFilters);if(dojo.isMoz)this.contentPreFilters=[this._normalizeFontStyle].concat(this.contentPreFilters),this.contentPostFilters=[this._removeMozBogus].concat(this.contentPostFilters);if(dojo.isWebKit)this.contentPreFilters=[this._removeWebkitBogus].concat(this.contentPreFilters),this.contentPostFilters=[this._removeWebkitBogus].concat(this.contentPostFilters);
if(dojo.isIE)this.contentPostFilters=[this._normalizeFontStyle].concat(this.contentPostFilters);this.inherited(arguments);dojo.publish(dijit._scopeName+"._editor.RichText::init",[this]);this.open();this.setupDefaultShortcuts()},setupDefaultShortcuts:function(){var a=dojo.hitch(this,function(a,b){return function(){return!this.execCommand(a,b)}}),b={b:a("bold"),i:a("italic"),u:a("underline"),a:a("selectall"),s:function(){this.save(!0)},m:function(){this.isTabIndent=!this.isTabIndent},1:a("formatblock",
"h1"),2:a("formatblock","h2"),3:a("formatblock","h3"),4:a("formatblock","h4"),"\\":a("insertunorderedlist")};if(!dojo.isIE)b.Z=a("redo");for(var c in b)this.addKeyHandler(c,!0,!1,b[c])},events:["onKeyPress","onKeyDown","onKeyUp"],captureEvents:[],_editorCommandsLocalized:!1,_localizeEditorCommands:function(){if(dijit._editor._editorCommandsLocalized)this._local2NativeFormatNames=dijit._editor._local2NativeFormatNames,this._native2LocalFormatNames=dijit._editor._native2LocalFormatNames;else{dijit._editor._editorCommandsLocalized=
!0;dijit._editor._local2NativeFormatNames={};dijit._editor._native2LocalFormatNames={};this._local2NativeFormatNames=dijit._editor._local2NativeFormatNames;this._native2LocalFormatNames=dijit._editor._native2LocalFormatNames;for(var a=["div","p","pre","h1","h2","h3","h4","h5","h6","ol","ul","address"],b="",c,d=0;c=a[d++];)b+=c.charAt(1)!=="l"?"<"+c+"><span>content</span></"+c+"><br/>":"<"+c+"><li>content</li></"+c+"><br/>";var f=dojo.create("div",{style:{position:"absolute",top:"0px",zIndex:10,opacity:0.01},
innerHTML:b});dojo.body().appendChild(f);a=dojo.hitch(this,function(){for(var a=f.firstChild;a;)try{dijit._editor.selection.selectElement(a.firstChild);var b=a.tagName.toLowerCase();this._local2NativeFormatNames[b]=document.queryCommandValue("formatblock");this._native2LocalFormatNames[this._local2NativeFormatNames[b]]=b;a=a.nextSibling.nextSibling}catch(c){}f.parentNode.removeChild(f);f.innerHTML=""});setTimeout(a,0)}},open:function(a){if(!this.onLoadDeferred||this.onLoadDeferred.fired>=0)this.onLoadDeferred=
new dojo.Deferred;this.isClosed||this.close();dojo.publish(dijit._scopeName+"._editor.RichText::open",[this]);if(arguments.length==1&&a.nodeName)this.domNode=a;var b=this.domNode,c;if(dojo.isString(this.value))c=this.value,delete this.value,b.innerHTML="";else if(b.nodeName&&b.nodeName.toLowerCase()=="textarea"){var d=this.textarea=b;this.name=d.name;c=d.value;b=this.domNode=dojo.doc.createElement("div");b.setAttribute("widgetId",this.id);d.removeAttribute("widgetId");b.cssText=d.cssText;b.className+=
" "+d.className;dojo.place(b,d,"before");var f=dojo.hitch(this,function(){dojo.style(d,{display:"block",position:"absolute",top:"-1000px"});if(dojo.isIE){var a=d.style;this.__overflow=a.overflow;a.overflow="hidden"}});dojo.isIE?setTimeout(f,10):f();if(d.form){var i=d.value;this.reset=function(){this.getValue()!=i&&this.replaceValue(i)};dojo.connect(d.form,"onsubmit",this,function(){dojo.attr(d,"disabled",this.disabled);d.value=this.getValue()})}}else c=dijit._editor.getChildrenHtml(b),b.innerHTML=
"";f=dojo.contentBox(b);this._oldHeight=f.h;this._oldWidth=f.w;this.value=c;if(b.nodeName&&b.nodeName=="LI")b.innerHTML=" <br>";this.header=b.ownerDocument.createElement("div");b.appendChild(this.header);this.editingArea=b.ownerDocument.createElement("div");b.appendChild(this.editingArea);this.footer=b.ownerDocument.createElement("div");b.appendChild(this.footer);if(!this.name)this.name=this.id+"_AUTOGEN";if(this.name!==""&&(!dojo.config.useXDomain||dojo.config.allowXdRichTextSave)){if((f=dojo.byId(dijit._scopeName+
"._editor.RichText.value"))&&f.value!=="")for(var g=f.value.split(this._SEPARATOR),k=0,j;j=g[k++];)if(j=j.split(this._NAME_CONTENT_SEP),j[0]==this.name){c=j[1];g=g.splice(k,1);f.value=g.join(this._SEPARATOR);break}if(!dijit._editor._globalSaveHandler)dijit._editor._globalSaveHandler={},dojo.addOnUnload(function(){for(var a in dijit._editor._globalSaveHandler){var b=dijit._editor._globalSaveHandler[a];dojo.isFunction(b)&&b()}});dijit._editor._globalSaveHandler[this.id]=dojo.hitch(this,"_saveContent")}this.isClosed=
!1;var h=this.editorObject=this.iframe=dojo.doc.createElement("iframe");h.id=this.id+"_iframe";this._iframeSrc=this._getIframeDocTxt();h.style.border="none";h.style.width="100%";if(this._layoutMode)h.style.height="100%";else if(dojo.isIE>=7){if(this.height)h.style.height=this.height;if(this.minHeight)h.style.minHeight=this.minHeight}else h.style.height=this.height?this.height:this.minHeight;h.frameBorder=0;h._loadFunc=dojo.hitch(this,function(a){this.window=a;this.document=this.window.document;dojo.isIE&&
this._localizeEditorCommands();this.onLoad(c)});var l="javascript:parent."+dijit._scopeName+'.byId("'+this.id+'")._iframeSrc';h.setAttribute("src",l);this.editingArea.appendChild(h);dojo.isSafari<=4&&(f=h.getAttribute("src"),(!f||f.indexOf("javascript")==-1)&&setTimeout(function(){h.setAttribute("src",l)},0));if(b.nodeName=="LI")b.lastChild.style.marginTop="-1.2em";dojo.addClass(this.domNode,this.baseClass)},_local2NativeFormatNames:{},_native2LocalFormatNames:{},_getIframeDocTxt:function(){var a=
dojo.getComputedStyle(this.domNode),b="",c=!0;if(dojo.isIE||dojo.isWebKit||!this.height&&!dojo.isMoz)b="<div id='dijitEditorBody'></div>",c=!1;else if(dojo.isMoz)this._cursorToStart=!0,b="&nbsp;";var d=[a.fontWeight,a.fontSize,a.fontFamily].join(" "),f=a.lineHeight,f=f.indexOf("px")>=0?parseFloat(f)/parseFloat(a.fontSize):f.indexOf("em")>=0?parseFloat(f):"normal",i="",g=this;this.style.replace(/(^|;)\s*(line-|font-?)[^;]+/ig,function(a){var a=a.replace(/^;/ig,"")+";",b=a.split(":")[0];if(b){var b=
dojo.trim(b),b=b.toLowerCase(),c,d="";for(c=0;c<b.length;c++){var f=b.charAt(c);switch(f){case "-":c++,f=b.charAt(c).toUpperCase();default:d+=f}}dojo.style(g.domNode,d,"")}i+=a+";"});a=dojo.query('label[for="'+this.id+'"]');return[this.isLeftToRight()?"<html>\n<head>\n":"<html dir='rtl'>\n<head>\n",dojo.isMoz&&a.length?"<title>"+a[0].innerHTML+"</title>\n":"","<meta http-equiv='Content-Type' content='text/html'>\n<style>\n\tbody,html {\n\t\tbackground:transparent;\n\t\tpadding: 1px 0 0 0;\n\t\tmargin: -1px 0 0 0;\n",
dojo.isWebKit?"\t\twidth: 100%;\n":"",dojo.isWebKit?"\t\theight: 100%;\n":"","\t}\n\tbody{\n\t\ttop:0px;\n\t\tleft:0px;\n\t\tright:0px;\n\t\tfont:",d,";\n",this.height||dojo.isOpera?"":"\t\tposition: fixed;\n","\t\tmin-height:",this.minHeight,";\n\t\tline-height:",f,";\n\t}\n\tp{ margin: 1em 0; }\n",!c&&!this.height?"\tbody,html {overflow-y: hidden;}\n":"","\t#dijitEditorBody{overflow-x: auto; overflow-y:"+(this.height?"auto;":"hidden;")+" outline: 0px;}\n","\tli > ul:-moz-first-node, li > ol:-moz-first-node{ padding-top: 1.2em; }\n",
!dojo.isIE?"\tli{ min-height:1.2em; }\n":"","</style>\n",this._applyEditingAreaStyleSheets(),"\n</head>\n<body ",c?"id='dijitEditorBody' ":"","onload='frameElement._loadFunc(window,document)' style='"+i+"'>",b,"</body>\n</html>"].join("")},_applyEditingAreaStyleSheets:function(){var a=[];if(this.styleSheets)a=this.styleSheets.split(";"),this.styleSheets="";a=a.concat(this.editingAreaStyleSheets);this.editingAreaStyleSheets=[];for(var b="",c=0,d;d=a[c++];)d=(new dojo._Url(dojo.global.location,d)).toString(),
this.editingAreaStyleSheets.push(d),b+='<link rel="stylesheet" type="text/css" href="'+d+'"/>';return b},addStyleSheet:function(a){var b=a.toString();if(b.charAt(0)=="."||b.charAt(0)!="/"&&!a.host)b=(new dojo._Url(dojo.global.location,b)).toString();dojo.indexOf(this.editingAreaStyleSheets,b)>-1||(this.editingAreaStyleSheets.push(b),this.onLoadDeferred.addCallback(dojo.hitch(this,function(){if(this.document.createStyleSheet)this.document.createStyleSheet(b);else{var a=this.document.getElementsByTagName("head")[0],
d=this.document.createElement("link");d.rel="stylesheet";d.type="text/css";d.href=b;a.appendChild(d)}})))},removeStyleSheet:function(a){var b=a.toString();if(b.charAt(0)=="."||b.charAt(0)!="/"&&!a.host)b=(new dojo._Url(dojo.global.location,b)).toString();a=dojo.indexOf(this.editingAreaStyleSheets,b);a!=-1&&(delete this.editingAreaStyleSheets[a],dojo.withGlobal(this.window,"query",dojo,['link:[href="'+b+'"]']).orphan())},disabled:!1,_mozSettingProps:{styleWithCSS:!1},_setDisabledAttr:function(a){a=
!!a;this._set("disabled",a);if(this.isLoaded){if(dojo.isIE||dojo.isWebKit||dojo.isOpera){var b=dojo.isIE&&(this.isLoaded||!this.focusOnLoad);if(b)this.editNode.unselectable="on";this.editNode.contentEditable=!a;if(b){var c=this;setTimeout(function(){c.editNode.unselectable="off"},0)}}else{try{this.document.designMode=a?"off":"on"}catch(d){return}if(!a&&this._mozSettingProps)for(b in a=this._mozSettingProps,a)if(a.hasOwnProperty(b))try{this.document.execCommand(b,!1,a[b])}catch(f){}}this._disabledOK=
!0}},onLoad:function(a){if(!this.window.__registeredWindow)this.window.__registeredWindow=!0,this._iframeRegHandle=dijit.registerIframe(this.iframe);if(!dojo.isIE&&!dojo.isWebKit&&(this.height||dojo.isMoz))this.editNode=this.document.body;else{this.editNode=this.document.body.firstChild;var b=this;if(dojo.isIE)this.tabStop=dojo.create("div",{tabIndex:-1},this.editingArea),this.iframe.onfocus=function(){b.editNode.setActive()}}this.focusNode=this.editNode;var c=this.events.concat(this.captureEvents),
d=this.iframe?this.document:this.editNode;dojo.forEach(c,function(a){this.connect(d,a.toLowerCase(),a)},this);this.connect(d,"onmouseup","onClick");dojo.isIE?(this.connect(this.document,"onmousedown","_onIEMouseDown"),this.editNode.style.zoom=1):this.connect(this.document,"onmousedown",function(){delete this._cursorToStart});if(dojo.isWebKit)this._webkitListener=this.connect(this.document,"onmouseup","onDisplayChanged"),this.connect(this.document,"onmousedown",function(a){(a=a.target)&&(a===this.document.body||
a===this.document)&&setTimeout(dojo.hitch(this,"placeCursorAtEnd"),0)});if(dojo.isIE)try{this.document.execCommand("RespectVisibilityInDesign",!0,null)}catch(f){}this.isLoaded=!0;this.set("disabled",this.disabled);c=dojo.hitch(this,function(){this.setValue(a);this.onLoadDeferred&&this.onLoadDeferred.callback(!0);this.onDisplayChanged();this.focusOnLoad&&dojo.addOnLoad(dojo.hitch(this,function(){setTimeout(dojo.hitch(this,"focus"),this.updateInterval)}));this.value=this.getValue(!0)});this.setValueDeferred?
this.setValueDeferred.addCallback(c):c()},onKeyDown:function(a){if(a.keyCode===dojo.keys.TAB&&this.isTabIndent&&(dojo.stopEvent(a),this.queryCommandEnabled(a.shiftKey?"outdent":"indent")))this.execCommand(a.shiftKey?"outdent":"indent");if(dojo.isIE)if(a.keyCode==dojo.keys.TAB&&!this.isTabIndent)a.shiftKey&&!a.ctrlKey&&!a.altKey?this.iframe.focus():!a.shiftKey&&!a.ctrlKey&&!a.altKey&&this.tabStop.focus();else if(a.keyCode===dojo.keys.BACKSPACE&&this.document.selection.type==="Control")dojo.stopEvent(a),
this.execCommand("delete");else if(65<=a.keyCode&&a.keyCode<=90||a.keyCode>=37&&a.keyCode<=40)a.charCode=a.keyCode,this.onKeyPress(a);return!0},onKeyUp:function(){},setDisabled:function(a){dojo.deprecated("dijit.Editor::setDisabled is deprecated",'use dijit.Editor::attr("disabled",boolean) instead',2);this.set("disabled",a)},_setValueAttr:function(a){this.setValue(a)},_setDisableSpellCheckAttr:function(a){this.document?dojo.attr(this.document.body,"spellcheck",!a):this.onLoadDeferred.addCallback(dojo.hitch(this,
function(){dojo.attr(this.document.body,"spellcheck",!a)}));this._set("disableSpellCheck",a)},onKeyPress:function(a){var b=this._keyHandlers[a.keyChar&&a.keyChar.toLowerCase()||a.keyCode],c=arguments;b&&!a.altKey&&dojo.some(b,function(b){if(!(b.shift^a.shiftKey)&&!(b.ctrl^(a.ctrlKey||a.metaKey)))return b.handler.apply(this,c)||a.preventDefault(),!0},this);if(!this._onKeyHitch)this._onKeyHitch=dojo.hitch(this,"onKeyPressed");setTimeout(this._onKeyHitch,1);return!0},addKeyHandler:function(a,b,c,d){dojo.isArray(this._keyHandlers[a])||
(this._keyHandlers[a]=[]);this._keyHandlers[a].push({shift:c||!1,ctrl:b||!1,handler:d})},onKeyPressed:function(){this.onDisplayChanged()},onClick:function(a){this.onDisplayChanged(a)},_onIEMouseDown:function(){!this._focused&&!this.disabled&&this.focus()},_onBlur:function(a){this.inherited(arguments);var b=this.getValue(!0);if(b!=this.value)this.onChange(b);this._set("value",b)},_onFocus:function(a){this.disabled||(this._disabledOK||this.set("disabled",!1),this.inherited(arguments))},blur:function(){!dojo.isIE&&
this.window.document.documentElement&&this.window.document.documentElement.focus?this.window.document.documentElement.focus():dojo.doc.body.focus&&dojo.doc.body.focus()},focus:function(){if(this.isLoaded){if(this._cursorToStart&&(delete this._cursorToStart,this.editNode.childNodes)){this.placeCursorAtStart();return}dojo.isIE?this.editNode&&this.editNode.focus&&this.iframe.fireEvent("onfocus",document.createEventObject()):dijit.focus(this.iframe)}else this.focusOnLoad=!0},updateInterval:200,_updateTimer:null,
onDisplayChanged:function(){this._updateTimer&&clearTimeout(this._updateTimer);if(!this._updateHandler)this._updateHandler=dojo.hitch(this,"onNormalizedDisplayChanged");this._updateTimer=setTimeout(this._updateHandler,this.updateInterval)},onNormalizedDisplayChanged:function(){delete this._updateTimer},onChange:function(){},_normalizeCommand:function(a,b){var c=a.toLowerCase();c=="formatblock"?dojo.isSafari&&b===void 0&&(c="heading"):c=="hilitecolor"&&!dojo.isMoz&&(c="backcolor");return c},_qcaCache:{},
queryCommandAvailable:function(a){var b=this._qcaCache[a];return b!==void 0?b:this._qcaCache[a]=this._queryCommandAvailable(a)},_queryCommandAvailable:function(a){function b(a){return{ie:Boolean(a&c),mozilla:Boolean(a&d),webkit:Boolean(a&f),opera:Boolean(a&i)}}var c=1,d=2,f=4,i=8,g=null;switch(a.toLowerCase()){case "bold":case "italic":case "underline":case "subscript":case "superscript":case "fontname":case "fontsize":case "forecolor":case "hilitecolor":case "justifycenter":case "justifyfull":case "justifyleft":case "justifyright":case "delete":case "selectall":case "toggledir":g=
b(d|c|f|i);break;case "createlink":case "unlink":case "removeformat":case "inserthorizontalrule":case "insertimage":case "insertorderedlist":case "insertunorderedlist":case "indent":case "outdent":case "formatblock":case "inserthtml":case "undo":case "redo":case "strikethrough":case "tabindent":g=b(d|c|i|f);break;case "blockdirltr":case "blockdirrtl":case "dirltr":case "dirrtl":case "inlinedirltr":case "inlinedirrtl":g=b(c);break;case "cut":case "copy":case "paste":g=b(c|d|f);break;case "inserttable":g=
b(d|c);break;case "insertcell":case "insertcol":case "insertrow":case "deletecells":case "deletecols":case "deleterows":case "mergecells":case "splitcell":g=b(c|d);break;default:return!1}return dojo.isIE&&g.ie||dojo.isMoz&&g.mozilla||dojo.isWebKit&&g.webkit||dojo.isOpera&&g.opera},execCommand:function(a,b){var c;this.focus();a=this._normalizeCommand(a,b);if(b!==void 0)if(a=="heading")throw Error("unimplemented");else a=="formatblock"&&dojo.isIE&&(b="<"+b+">");var d="_"+a+"Impl";if(this[d])c=this[d](b);
else if((b=arguments.length>1?b:null)||a!="createlink")c=this.document.execCommand(a,!1,b);this.onDisplayChanged();return c},queryCommandEnabled:function(a){if(this.disabled||!this._disabledOK)return!1;a=this._normalizeCommand(a);if(dojo.isMoz||dojo.isWebKit)if(a=="unlink")return this._sCall("hasAncestorElement",["a"]);else if(a=="inserttable")return!0;if(dojo.isWebKit)if(a=="cut"||a=="copy")return(a=this.window.getSelection())&&(a=a.toString()),!!a;else if(a=="paste")return!0;var b=dojo.isIE?this.document.selection.createRange():
this.document;try{return b.queryCommandEnabled(a)}catch(c){return!1}},queryCommandState:function(a){if(this.disabled||!this._disabledOK)return!1;a=this._normalizeCommand(a);try{return this.document.queryCommandState(a)}catch(b){return!1}},queryCommandValue:function(a){if(this.disabled||!this._disabledOK)return!1;a=this._normalizeCommand(a);if(dojo.isIE&&a=="formatblock")a=this._native2LocalFormatNames[this.document.queryCommandValue(a)];else if(dojo.isMoz&&a==="hilitecolor"){var b;try{b=this.document.queryCommandValue("styleWithCSS")}catch(c){b=
!1}this.document.execCommand("styleWithCSS",!1,!0);a=this.document.queryCommandValue(a);this.document.execCommand("styleWithCSS",!1,b)}else a=this.document.queryCommandValue(a);return a},_sCall:function(a,b){return dojo.withGlobal(this.window,a,dijit._editor.selection,b)},placeCursorAtStart:function(){this.focus();var a=!1;if(dojo.isMoz)for(var b=this.editNode.firstChild;b;){if(b.nodeType==3){if(b.nodeValue.replace(/^\s+|\s+$/g,"").length>0){a=!0;this._sCall("selectElement",[b]);break}}else if(b.nodeType==
1){a=!0;/br|input|img|base|meta|area|basefont|hr|link/.test(b.tagName?b.tagName.toLowerCase():"")?this._sCall("selectElement",[b]):this._sCall("selectElementChildren",[b]);break}b=b.nextSibling}else a=!0,this._sCall("selectElementChildren",[this.editNode]);a&&this._sCall("collapse",[!0])},placeCursorAtEnd:function(){this.focus();var a=!1;if(dojo.isMoz)for(var b=this.editNode.lastChild;b;){if(b.nodeType==3){if(b.nodeValue.replace(/^\s+|\s+$/g,"").length>0){a=!0;this._sCall("selectElement",[b]);break}}else if(b.nodeType==
1){a=!0;b.lastChild?this._sCall("selectElement",[b.lastChild]):this._sCall("selectElement",[b]);break}b=b.previousSibling}else a=!0,this._sCall("selectElementChildren",[this.editNode]);a&&this._sCall("collapse",[!1])},getValue:function(a){return this.textarea&&(this.isClosed||!this.isLoaded)?this.textarea.value:this._postFilterContent(null,a)},_getValueAttr:function(){return this.getValue(!0)},setValue:function(a){if(this.isLoaded){this._cursorToStart=!0;if(this.textarea&&(this.isClosed||!this.isLoaded))this.textarea.value=
a;else{var a=this._preFilterContent(a),b=this.isClosed?this.domNode:this.editNode;a&&dojo.isMoz&&a.toLowerCase()=="<p></p>"&&(a="<p>&nbsp;</p>");!a&&dojo.isWebKit&&(a="&nbsp;");b.innerHTML=a;this._preDomFilterContent(b)}this.onDisplayChanged();this._set("value",this.getValue(!0))}else this.onLoadDeferred.addCallback(dojo.hitch(this,function(){this.setValue(a)}))},replaceValue:function(a){if(this.isClosed)this.setValue(a);else if(this.window&&this.window.getSelection&&!dojo.isMoz)this.setValue(a);
else if(this.window&&this.window.getSelection){a=this._preFilterContent(a);this.execCommand("selectall");if(!a)this._cursorToStart=!0,a="&nbsp;";this.execCommand("inserthtml",a);this._preDomFilterContent(this.editNode)}else this.document&&this.document.selection&&this.setValue(a);this._set("value",this.getValue(!0))},_preFilterContent:function(a){var b=a;dojo.forEach(this.contentPreFilters,function(a){a&&(b=a(b))});return b},_preDomFilterContent:function(a){a=a||this.editNode;dojo.forEach(this.contentDomPreFilters,
function(b){b&&dojo.isFunction(b)&&b(a)},this)},_postFilterContent:function(a,b){var c;dojo.isString(a)?c=a:(a=a||this.editNode,this.contentDomPostFilters.length&&(b&&(a=dojo.clone(a)),dojo.forEach(this.contentDomPostFilters,function(b){a=b(a)})),c=dijit._editor.getChildrenHtml(a));dojo.trim(c.replace(/^\xA0\xA0*/,"").replace(/\xA0\xA0*$/,"")).length||(c="");dojo.forEach(this.contentPostFilters,function(a){c=a(c)});return c},_saveContent:function(){var a=dojo.byId(dijit._scopeName+"._editor.RichText.value");
a.value&&(a.value+=this._SEPARATOR);a.value+=this.name+this._NAME_CONTENT_SEP+this.getValue(!0)},escapeXml:function(a,b){a=a.replace(/&/gm,"&amp;").replace(/</gm,"&lt;").replace(/>/gm,"&gt;").replace(/"/gm,"&quot;");b||(a=a.replace(/'/gm,"&#39;"));return a},getNodeHtml:function(a){dojo.deprecated("dijit.Editor::getNodeHtml is deprecated","use dijit._editor.getNodeHtml instead",2);return dijit._editor.getNodeHtml(a)},getNodeChildrenHtml:function(a){dojo.deprecated("dijit.Editor::getNodeChildrenHtml is deprecated",
"use dijit._editor.getChildrenHtml instead",2);return dijit._editor.getChildrenHtml(a)},close:function(a){if(!this.isClosed){arguments.length||(a=!0);a&&this._set("value",this.getValue(!0));this.interval&&clearInterval(this.interval);this._webkitListener&&(this.disconnect(this._webkitListener),delete this._webkitListener);if(dojo.isIE)this.iframe.onfocus=null;this.iframe._loadFunc=null;this._iframeRegHandle&&(dijit.unregisterIframe(this._iframeRegHandle),delete this._iframeRegHandle);if(this.textarea){var b=
this.textarea.style;b.position="";b.left=b.top="";if(dojo.isIE)b.overflow=this.__overflow,this.__overflow=null;this.textarea.value=this.value;dojo.destroy(this.domNode);this.domNode=this.textarea}else this.domNode.innerHTML=this.value;delete this.iframe;dojo.removeClass(this.domNode,this.baseClass);this.isClosed=!0;this.isLoaded=!1;delete this.editNode;delete this.focusNode;if(this.window&&this.window._frameElement)this.window._frameElement=null;this.editorObject=this.editingArea=this.document=this.window=
null}},destroy:function(){this.isClosed||this.close(!1);this.inherited(arguments);dijit._editor._globalSaveHandler&&delete dijit._editor._globalSaveHandler[this.id]},_removeMozBogus:function(a){return a.replace(/\stype="_moz"/gi,"").replace(/\s_moz_dirty=""/gi,"").replace(/_moz_resizing="(true|false)"/gi,"")},_removeWebkitBogus:function(a){a=a.replace(/\sclass="webkit-block-placeholder"/gi,"");a=a.replace(/\sclass="apple-style-span"/gi,"");return a=a.replace(/<meta charset=\"utf-8\" \/>/gi,"")},_normalizeFontStyle:function(a){return a.replace(/<(\/)?strong([ \>])/gi,
"<$1b$2").replace(/<(\/)?em([ \>])/gi,"<$1i$2")},_preFixUrlAttributes:function(a){return a.replace(/(?:(<a(?=\s).*?\shref=)("|')(.*?)\2)|(?:(<a\s.*?href=)([^"'][^ >]+))/gi,"$1$4$2$3$5$2 _djrealurl=$2$3$5$2").replace(/(?:(<img(?=\s).*?\ssrc=)("|')(.*?)\2)|(?:(<img\s.*?src=)([^"'][^ >]+))/gi,"$1$4$2$3$5$2 _djrealurl=$2$3$5$2")},_inserthorizontalruleImpl:function(a){return dojo.isIE?this._inserthtmlImpl("<hr>"):this.document.execCommand("inserthorizontalrule",!1,a)},_unlinkImpl:function(a){return this.queryCommandEnabled("unlink")&&
(dojo.isMoz||dojo.isWebKit)?(this._sCall("selectElement",[this._sCall("getAncestorElement",["a"])]),this.document.execCommand("unlink",!1,null)):this.document.execCommand("unlink",!1,a)},_hilitecolorImpl:function(a){dojo.isMoz?(this.document.execCommand("styleWithCSS",!1,!0),a=this.document.execCommand("hilitecolor",!1,a),this.document.execCommand("styleWithCSS",!1,!1)):a=this.document.execCommand("hilitecolor",!1,a);return a},_backcolorImpl:function(a){dojo.isIE&&(a=a?a:null);return this.document.execCommand("backcolor",
!1,a)},_forecolorImpl:function(a){dojo.isIE&&(a=a?a:null);return this.document.execCommand("forecolor",!1,a)},_inserthtmlImpl:function(a){var a=this._preFilterContent(a),b=!0;if(dojo.isIE){var c=this.document.selection.createRange();if(this.document.selection.type.toUpperCase()=="CONTROL"){for(var d=c.item(0);c.length;)c.remove(c.item(0));d.outerHTML=a}else c.pasteHTML(a);c.select()}else dojo.isMoz&&!a.length?this._sCall("remove"):b=this.document.execCommand("inserthtml",!1,a);return b},_boldImpl:function(a){dojo.isIE&&
this._adaptIESelection();return this.document.execCommand("bold",!1,a)},_italicImpl:function(a){dojo.isIE&&this._adaptIESelection();return this.document.execCommand("italic",!1,a)},_underlineImpl:function(a){dojo.isIE&&this._adaptIESelection();return this.document.execCommand("underline",!1,a)},_strikethroughImpl:function(a){dojo.isIE&&this._adaptIESelection();return this.document.execCommand("strikethrough",!1,a)},getHeaderHeight:function(){return this._getNodeChildrenHeight(this.header)},getFooterHeight:function(){return this._getNodeChildrenHeight(this.footer)},
_getNodeChildrenHeight:function(a){var b=0;if(a&&a.childNodes){var c;for(c=0;c<a.childNodes.length;c++){var d=dojo.position(a.childNodes[c]);b+=d.h}}return b},_isNodeEmpty:function(a,b){if(a.nodeType==1)return a.childNodes.length>0?this._isNodeEmpty(a.childNodes[0],b):!0;else if(a.nodeType==3)return a.nodeValue.substring(b)=="";return!1},_removeStartingRangeFromRange:function(a,b){if(a.nextSibling)b.setStart(a.nextSibling,0);else{for(var c=a.parentNode;c&&c.nextSibling==null;)c=c.parentNode;c&&b.setStart(c.nextSibling,
0)}return b},_adaptIESelection:function(){var a=dijit.range.getSelection(this.window);if(a&&a.rangeCount&&!a.isCollapsed){for(var b=a.getRangeAt(0),c=b.startContainer,d=b.startOffset;c.nodeType==3&&d>=c.length&&c.nextSibling;)d-=c.length,c=c.nextSibling;for(var f=null;this._isNodeEmpty(c,d)&&c!=f;)f=c,b=this._removeStartingRangeFromRange(c,b),c=b.startContainer,d=0;a.removeAllRanges();a.addRange(b)}}})};