/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._editor.selection"]||(dojo._hasResource["dijit._editor.selection"]=!0,dojo.provide("dijit._editor.selection"),dojo.getObject("_editor.selection",!0,dijit),dojo.mixin(dijit._editor.selection,{getType:function(){if(dojo.isIE<9)return dojo.doc.selection.type.toLowerCase();else{var a="text",b;try{b=dojo.global.getSelection()}catch(d){}b&&b.rangeCount==1&&(b=b.getRangeAt(0),b.startContainer==b.endContainer&&b.endOffset-b.startOffset==1&&b.startContainer.nodeType!=3&&(a="control"));
return a}},getSelectedText:function(){if(dojo.isIE<9)return dijit._editor.selection.getType()=="control"?null:dojo.doc.selection.createRange().text;else{var a=dojo.global.getSelection();if(a)return a.toString()}return""},getSelectedHtml:function(){if(dojo.isIE<9)return dijit._editor.selection.getType()=="control"?null:dojo.doc.selection.createRange().htmlText;else{var a=dojo.global.getSelection();if(a&&a.rangeCount){var b,d="";for(b=0;b<a.rangeCount;b++){var c=a.getRangeAt(b).cloneContents(),e=dojo.doc.createElement("div");
e.appendChild(c);d+=e.innerHTML}return d}return null}},getSelectedElement:function(){if(dijit._editor.selection.getType()=="control")if(dojo.isIE<9){var a=dojo.doc.selection.createRange();if(a&&a.item)return dojo.doc.selection.createRange().item(0)}else return a=dojo.global.getSelection(),a.anchorNode.childNodes[a.anchorOffset];return null},getParentElement:function(){if(dijit._editor.selection.getType()=="control"){var a=this.getSelectedElement();if(a)return a.parentNode}else if(dojo.isIE<9)return a=
dojo.doc.selection.createRange(),a.collapse(!0),a.parentElement();else if(a=dojo.global.getSelection()){for(a=a.anchorNode;a&&a.nodeType!=1;)a=a.parentNode;return a}return null},hasAncestorElement:function(a){return this.getAncestorElement.apply(this,arguments)!=null},getAncestorElement:function(a){return this.getParentOfType(this.getSelectedElement()||this.getParentElement(),arguments)},isTag:function(a,b){if(a&&a.tagName)for(var d=a.tagName.toLowerCase(),c=0;c<b.length;c++){var e=String(b[c]).toLowerCase();
if(d==e)return e}return""},getParentOfType:function(a,b){for(;a;){if(this.isTag(a,b).length)return a;a=a.parentNode}return null},collapse:function(a){if(window.getSelection){var b=dojo.global.getSelection();b.removeAllRanges?a?b.collapseToStart():b.collapseToEnd():b.collapse(a)}else dojo.isIE&&(b=dojo.doc.selection.createRange(),b.collapse(a),b.select())},remove:function(){var a=dojo.doc.selection;dojo.isIE<9?a.type.toLowerCase()!="none"&&a.clear():(a=dojo.global.getSelection(),a.deleteFromDocument());
return a},selectElementChildren:function(a,b){var d=dojo.global,c=dojo.doc,a=dojo.byId(a);if(c.selection&&dojo.isIE<9&&dojo.body().createTextRange){if(c=a.ownerDocument.body.createTextRange(),c.moveToElementText(a),!b)try{c.select()}catch(e){}}else d.getSelection&&(d=dojo.global.getSelection(),dojo.isOpera?(c=d.rangeCount?d.getRangeAt(0):c.createRange(),c.setStart(a,0),c.setEnd(a,a.nodeType==3?a.length:a.childNodes.length),d.addRange(c)):d.selectAllChildren(a))},selectElement:function(a,b){var d,
c=dojo.doc,e=dojo.global,a=dojo.byId(a);if(dojo.isIE<9&&dojo.body().createTextRange)try{var f=a.tagName?a.tagName.toLowerCase():"";d=f==="img"||f==="table"?dojo.body().createControlRange():dojo.body().createRange();d.addElement(a);b||d.select()}catch(g){this.selectElementChildren(a,b)}else dojo.global.getSelection&&(e=e.getSelection(),d=c.createRange(),e.removeAllRanges&&(dojo.isOpera&&e.getRangeAt(0)&&(d=e.getRangeAt(0)),d.selectNode(a),e.removeAllRanges(),e.addRange(d)))},inSelection:function(a){if(a){var b,
d=dojo.doc,c;if(dojo.global.getSelection){var e=dojo.global.getSelection();e&&e.rangeCount>0&&(c=e.getRangeAt(0));if(c&&c.compareBoundaryPoints&&d.createRange)try{if(b=d.createRange(),b.setStart(a,0),c.compareBoundaryPoints(c.START_TO_END,b)===1)return!0}catch(f){}}else if(d.selection){c=d.selection.createRange();try{(b=a.ownerDocument.body.createControlRange())&&b.addElement(a)}catch(g){try{b=a.ownerDocument.body.createTextRange(),b.moveToElementText(a)}catch(h){}}if(c&&b&&c.compareEndPoints("EndToStart",
b)===1)return!0}}return!1}}));