/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.DataChart"]||(dojo._hasResource["dojox.charting.DataChart"]=!0,dojo.provide("dojox.charting.DataChart"),dojo.require("dojox.charting.Chart2D"),dojo.require("dojox.charting.themes.PlotKit.blue"),dojo.experimental("dojox.charting.DataChart"),function(){var g={vertical:!0,min:0,max:10,majorTickStep:5,minorTickStep:1,natural:!1,stroke:"black",majorTick:{stroke:"black",length:8},minorTick:{stroke:"gray",length:2},majorLabels:!0},h={natural:!0,majorLabels:!0,includeZero:!1,
majorTickStep:1,majorTick:{stroke:"black",length:8},fixUpper:"major",stroke:"black",htmlLabels:!0,from:1},d={markers:!0,tension:2,gap:2};dojo.declare("dojox.charting.DataChart",[dojox.charting.Chart2D],{scroll:!0,comparative:!1,query:"*",queryOptions:"",fieldName:"value",chartTheme:dojox.charting.themes.PlotKit.blue,displayRange:0,stretchToFit:!0,minWidth:200,minHeight:100,showing:!0,label:"name",constructor:function(a,b){this.domNode=dojo.byId(a);dojo.mixin(this,b);this.xaxis=dojo.mixin(dojo.mixin({},
h),b.xaxis);if(this.xaxis.labelFunc=="seriesLabels")this.xaxis.labelFunc=dojo.hitch(this,"seriesLabels");this.yaxis=dojo.mixin(dojo.mixin({},g),b.yaxis);if(this.yaxis.labelFunc=="seriesLabels")this.yaxis.labelFunc=dojo.hitch(this,"seriesLabels");this._events=[];this.convertLabels(this.yaxis);this.convertLabels(this.xaxis);this.onSetItems={};this.dataLength=this.onSetInterval=0;this.seriesData={};this.seriesDataBk={};this.firstRun=!0;this.dataOffset=0;this.chartTheme.plotarea.stroke={color:"gray",
width:3};this.setTheme(this.chartTheme);if(this.displayRange)this.stretchToFit=!1;if(!this.stretchToFit)this.xaxis.to=this.displayRange;this.addAxis("x",this.xaxis);this.addAxis("y",this.yaxis);d.type=b.type||"Markers";this.addPlot("default",dojo.mixin(d,b.chartPlot));this.addPlot("grid",dojo.mixin(b.grid||{},{type:"Grid",hMinorLines:!0}));this.showing&&this.render();b.store&&this.setStore(b.store,b.query,b.fieldName,b.queryOptions)},destroy:function(){dojo.forEach(this._events,dojo.disconnect);this.inherited(arguments)},
setStore:function(a,b,c,f){this.firstRun=!0;this.store=a||this.store;this.query=b||this.query;this.fieldName=c||this.fieldName;this.label=this.store.getLabelAttributes();this.queryOptions=f||f;dojo.forEach(this._events,dojo.disconnect);this._events=[dojo.connect(this.store,"onSet",this,"onSet"),dojo.connect(this.store,"onError",this,"onError")];this.fetch()},show:function(){if(!this.showing)dojo.style(this.domNode,"display",""),this.showing=!0,this.render()},hide:function(){if(this.showing)dojo.style(this.domNode,
"display","none"),this.showing=!1},onSet:function(a){var b=this.getProperty(a,this.label);if(b in this.runs||this.comparative)clearTimeout(this.onSetInterval),this.onSetItems[b]||(this.onSetItems[b]=a),this.onSetInterval=setTimeout(dojo.hitch(this,function(){clearTimeout(this.onSetInterval);var b=[],a;for(a in this.onSetItems)b.push(this.onSetItems[a]);this.onData(b);this.onSetItems={}}),200)},onError:function(a){console.error("DataChart Error:",a)},onDataReceived:function(){},getProperty:function(a,
b){if(b==this.label)return this.store.getLabel(a);if(b=="id")return this.store.getIdentity(a);var c=this.store.getValues(a,b);c.length<2&&(c=this.store.getValue(a,b));return c},onData:function(a){if(a&&a.length){if(this.items&&this.items.length!=a.length)dojo.forEach(a,function(b){var a=this.getProperty(b,"id");dojo.forEach(this.items,function(b,c){this.getProperty(b,"id")==a&&(this.items[c]=b)},this)},this),a=this.items;if(this.stretchToFit)this.displayRange=a.length;this.onDataReceived(a);this.items=
a;if(this.comparative){var b="default";this.seriesData[b]=[];this.seriesDataBk[b]=[];dojo.forEach(a,function(a){a=this.getProperty(a,this.fieldName);this.seriesData[b].push(a)},this)}else dojo.forEach(a,function(a,b){var c=this.store.getLabel(a);this.seriesData[c]||(this.seriesData[c]=[],this.seriesDataBk[c]=[]);var e=this.getProperty(a,this.fieldName);if(dojo.isArray(e))this.seriesData[c]=e;else{if(this.scroll)this.seriesDataBk[c].length>this.seriesData[c].length&&(this.seriesData[c]=this.seriesDataBk[c]),
this.seriesData[c].push(Number(e));else{var d=dojo.map(Array(b+1),function(){return 0});d.push(Number(e));this.seriesData[c]=d}this.seriesDataBk[c].push(Number(e))}},this);var c;if(this.firstRun)for(b in this.firstRun=!1,this.seriesData)this.addSeries(b,this.seriesData[b]),c=this.seriesData[b];else for(b in this.seriesData){c=this.seriesData[b];if(this.scroll&&c.length>this.displayRange)this.dataOffset=c.length-this.displayRange-1,c=c.slice(c.length-this.displayRange,c.length);this.updateSeries(b,
c)}this.dataLength=c.length;this.showing&&this.render()}},fetch:function(){this.store&&this.store.fetch({query:this.query,queryOptions:this.queryOptions,start:this.start,count:this.count,sort:this.sort,onComplete:dojo.hitch(this,function(a){setTimeout(dojo.hitch(this,function(){this.onData(a)}),0)}),onError:dojo.hitch(this,"onError")})},convertLabels:function(a){if(!a.labels||dojo.isObject(a.labels[0]))return null;a.labels=dojo.map(a.labels,function(a,c){return{value:c,text:a}});return null},seriesLabels:function(a){a--;
if(this.series.length<1||!this.comparative&&a>this.series.length)return"-";if(this.comparative)return this.store.getLabel(this.items[a]);else for(var b=0;b<this.series.length;b++)if(this.series[b].data[a]>0)return this.series[b].name;return"-"},resizeChart:function(a){this.resize(Math.max(a.w,this.minWidth),Math.max(a.h,this.minHeight))}})}());