//>>built
define("phpr/nls/main_ROOT",{"dijit/nls/loading":{loadingState:"Loading...",errorState:"Sorry, an error occurred"},"dojo/cldr/nls/gregorian":{"months-format-abbr":"1,2,3,4,5,6,7,8,9,10,11,12".split(","),"months-format-narrow":"1,2,3,4,5,6,7,8,9,10,11,12".split(","),"months-format-wide":"1,2,3,4,5,6,7,8,9,10,11,12".split(","),"months-standAlone-abbr":"1,2,3,4,5,6,7,8,9,10,11,12".split(","),"months-standAlone-narrow":"1,2,3,4,5,6,7,8,9,10,11,12".split(","),"months-standAlone-wide":"1,2,3,4,5,6,7,8,9,10,11,12".split(","),
"days-format-abbr":"1,2,3,4,5,6,7".split(","),"days-format-narrow":"1,2,3,4,5,6,7".split(","),"days-format-wide":"1,2,3,4,5,6,7".split(","),"days-standAlone-abbr":"1,2,3,4,5,6,7".split(","),"days-standAlone-narrow":"1,2,3,4,5,6,7".split(","),"days-standAlone-wide":"1,2,3,4,5,6,7".split(","),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["Q1","Q2","Q3","Q4"],"quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-narrow":["1",
"2","3","4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM","dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"PM","dayPeriods-format-wide-am":"AM","dayPeriods-format-wide-pm":"PM",eraNames:["BCE","CE"],eraAbbr:["BCE","CE"],eraNarrow:["BCE","CE"],"dateFormat-full":"EEEE, y MMMM dd","dateFormat-long":"y MMMM d","dateFormat-medium":"y MMM d","dateFormat-short":"yyyy-MM-dd","timeFormat-full":"HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z",
"timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d","dateFormatItem-Ed":"d E","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-M":"L","dateFormatItem-Md":"M-d","dateFormatItem-MEd":"E, M-d","dateFormatItem-MMM":"LLL",
"dateFormatItem-MMMd":"MMM d","dateFormatItem-MMMEd":"E MMM d","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yM":"y-M","dateFormatItem-yMd":"y-M-d","dateFormatItem-yMEd":"E, y-M-d","dateFormatItem-yMMM":"y MMM","dateFormatItem-yMMMd":"y MMM d","dateFormatItem-yMMMEd":"E, y MMM d","dateFormatItem-yQ":"y Q","dateFormatItem-yQQQ":"y QQQ","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}",
"dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"Era","field-year":"Year","field-month":"Month","field-week":"Week","field-day":"Day",
"field-day-relative+-1":"Yesterday","field-day-relative+0":"Today","field-day-relative+1":"Tomorrow","field-weekday":"Day of the Week","field-dayperiod":"Dayperiod","field-hour":"Hour","field-minute":"Minute","field-second":"Second","field-zone":"Zone"},"dojo/cldr/nls/number":{decimal:".",group:",",list:";",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"NaN",decimalFormat:"#,##0.###","decimalFormat-short":"000T",scientificFormat:"#E0",percentFormat:"#,##0%",
"currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"\u00a4\u00a0#,##0.00"},"dijit/form/nls/validate":{invalidMessage:"The value entered is not valid.",missingMessage:"This value is required.",
rangeMessage:"This value is out of range."},"dijit/form/nls/ComboBox":{previousMessage:"Previous choices",nextMessage:"More choices"}});