//>>built
define("phpr/nls/main_da",{"dijit/nls/loading":{loadingState:"Indl\u00e6ser...",errorState:"Der er opst\u00e5et en fejl"},"dojo/cldr/nls/gregorian":{"months-format-abbr":"jan.,feb.,mar.,apr.,maj,jun.,jul.,aug.,sep.,okt.,nov.,dec.".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-format-wide":"januar,februar,marts,april,maj,juni,juli,august,september,oktober,november,december".split(","),"months-standAlone-abbr":"jan,feb,mar,apr,maj,jun,jul,aug,sep,okt,nov,dec".split(","),
"months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-standAlone-wide":"januar,februar,marts,april,maj,juni,juli,august,september,oktober,november,december".split(","),"days-format-abbr":"s\u00f8n,man,tir,ons,tor,fre,l\u00f8r".split(","),"days-format-narrow":"S,M,T,O,T,F,L".split(","),"days-format-wide":"s\u00f8ndag,mandag,tirsdag,onsdag,torsdag,fredag,l\u00f8rdag".split(","),"days-standAlone-abbr":"s\u00f8n,man,tir,ons,tor,fre,l\u00f8r".split(","),"days-standAlone-narrow":"S,M,T,O,T,F,L".split(","),
"days-standAlone-wide":"s\u00f8ndag,mandag,tirsdag,onsdag,torsdag,fredag,l\u00f8rdag".split(","),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"quarters-standAlone-abbr":["K1","K2","K3","K4"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM",
"dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"PM","dayPeriods-format-wide-am":"f.m.","dayPeriods-format-wide-pm":"e.m.",eraNames:["f.Kr.","e.Kr."],eraAbbr:["f.Kr.","e.Kr."],eraNarrow:["f.Kr.","e.Kr."],"dateFormat-full":"EEEE 'den' d. MMMM y","dateFormat-long":"d. MMM y","dateFormat-medium":"dd/MM/yyyy","dateFormat-short":"dd/MM/yy","timeFormat-full":"HH.mm.ss zzzz","timeFormat-long":"HH.mm.ss z","timeFormat-medium":"HH.mm.ss","timeFormat-short":"HH.mm","dateTimeFormat-full":"{1} {0}",
"dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d.","dateFormatItem-Ed":"E d.","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h.mm a","dateFormatItem-Hm":"HH.mm","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-Hms":"HH.mm.ss","dateFormatItem-M":"M","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E. d/M","dateFormatItem-MMM":"MMM","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MMMEd":"E d. MMM","dateFormatItem-ms":"mm.ss",
"dateFormatItem-y":"y","dateFormatItem-yM":"M/y","dateFormatItem-yMd":"d/M/y","dateFormatItem-yMEd":"E. d/M/y","dateFormatItem-yMMM":"MMM y","dateFormatItem-yMMMd":"d. MMM y","dateFormatItem-yMMMEd":"E. d. MMM y","dateFormatItem-yQ":"Q yyyy","dateFormatItem-yQQQ":"QQQ y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"\u00e6ra","field-year":"\u00e5r","field-month":"m\u00e5ned","field-week":"uge","field-day":"dag","field-day-relative+-1":"i g\u00e5r","field-day-relative+0":"i dag","field-day-relative+1":"i morgen",
"field-weekday":"ugedag","field-dayperiod":"dagtid","field-hour":"time","field-minute":"minut","field-second":"sekund","field-zone":"tidszone","dayPeriods-format-abbr-noon":"middag","dayPeriods-format-narrow-noon":"middag","dayPeriods-format-wide-noon":"middag","dateFormatItem-MMdd":"dd/MM","dateFormatItem-MMMMEd":"E d. MMMM","dateFormatItem-yyMM":"MM/yy","dateFormatItem-yyMMM":"MMM yy","dateFormatItem-yyQ":"Q. 'kvartal' yy","dateFormatItem-yyyy":"y","dateFormatItem-yyyyMM":"MM/yyyy","dateFormatItem-yyyyMMM":"MMM y",
"field-year-relative+-1":"Sidste \u00e5r","field-year-relative+0":"I \u00e5r","field-year-relative+1":"N\u00e6ste \u00e5r","field-month-relative+-1":"Sidste m\u00e5ned","field-month-relative+0":"Denne m\u00e5ned","field-month-relative+1":"N\u00e6ste m\u00e5ned","field-week-relative+-1":"Sidste uge","field-week-relative+0":"Denne uge","field-week-relative+1":"N\u00e6ste uge","field-day-relative+-2":"i forg\u00e5rs","field-day-relative+2":"i overmorgen"},"dojo/cldr/nls/number":{decimal:",",group:".",
list:",",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"NaN",decimalFormat:"#,##0.###","decimalFormat-short":"000\u00a0bill",scientificFormat:"#E0",percentFormat:"#,##0\u00a0%","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]",
"currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"#,##0.00\u00a0\u00a4"},"dijit/form/nls/validate":{invalidMessage:"Den angivne v\u00e6rdi er ugyldig.",missingMessage:"V\u00e6rdien er p\u00e5kr\u00e6vet.",rangeMessage:"V\u00e6rdien er uden for intervallet."},"dijit/form/nls/ComboBox":{previousMessage:"Forrige valg",nextMessage:"Flere valg"}});