//>>built
define("phpr/nls/main_sk",{"dijit/nls/loading":{loadingState:"Zav\u00e1dza sa...",errorState:"\u013dutujeme, ale vyskytla sa chyba"},"dojo/cldr/nls/gregorian":{"months-format-abbr":"jan,feb,mar,apr,m\u00e1j,j\u00fan,j\u00fal,aug,sep,okt,nov,dec".split(","),"months-format-narrow":"j,f,m,a,m,j,j,a,s,o,n,d".split(","),"months-format-wide":"janu\u00e1ra,febru\u00e1ra,marca,apr\u00edla,m\u00e1ja,j\u00fana,j\u00fala,augusta,septembra,okt\u00f3bra,novembra,decembra".split(","),"months-standAlone-abbr":"jan,feb,mar,apr,m\u00e1j,j\u00fan,j\u00fal,aug,sep,okt,nov,dec".split(","),
"months-standAlone-narrow":"j,f,m,a,m,j,j,a,s,o,n,d".split(","),"months-standAlone-wide":"janu\u00e1r,febru\u00e1r,marec,apr\u00edl,m\u00e1j,j\u00fan,j\u00fal,august,september,okt\u00f3ber,november,december".split(","),"days-format-abbr":"ne,po,ut,st,\u0161t,pi,so".split(","),"days-format-narrow":"N,P,U,S,\u0160,P,S".split(","),"days-format-wide":"nede\u013ea,pondelok,utorok,streda,\u0161tvrtok,piatok,sobota".split(","),"days-standAlone-abbr":"ne,po,ut,st,\u0161t,pi,so".split(","),"days-standAlone-narrow":"N,P,U,S,\u0160,P,S".split(","),
"days-standAlone-wide":"nede\u013ea,pondelok,utorok,streda,\u0161tvrtok,piatok,sobota".split(","),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["1. \u0161tvr\u0165rok","2. \u0161tvr\u0165rok","3. \u0161tvr\u0165rok","4. \u0161tvr\u0165rok"],"quarters-standAlone-abbr":["1Q","2Q","3Q","4Q"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["1. \u0161tvr\u0165rok","2. \u0161tvr\u0165rok","3. \u0161tvr\u0165rok",
"4. \u0161tvr\u0165rok"],"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM","dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"PM","dayPeriods-format-wide-am":"dopoludnia","dayPeriods-format-wide-pm":"popoludn\u00ed",eraNames:["pred n.l.","n.l."],eraAbbr:["pred n.l.","n.l."],eraNarrow:["pred n.l.","n.l."],"dateFormat-full":"EEEE, d. MMMM y","dateFormat-long":"d. MMMM y","dateFormat-medium":"d.M.yyyy","dateFormat-short":"d.M.yyyy","timeFormat-full":"H:mm:ss zzzz","timeFormat-long":"H:mm:ss z",
"timeFormat-medium":"H:mm:ss","timeFormat-short":"H:mm","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d.","dateFormatItem-Ed":"E, d.","dateFormatItem-h":"h a","dateFormatItem-H":"H","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"H:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"H:mm:ss","dateFormatItem-M":"L.","dateFormatItem-Md":"d.M.","dateFormatItem-MEd":"E, d.M.","dateFormatItem-MMM":"LLL",
"dateFormatItem-MMMd":"d. MMM","dateFormatItem-MMMEd":"E, d. MMM","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yM":"M.yyyy","dateFormatItem-yMd":"d.M.yyyy","dateFormatItem-yMEd":"E, d.M.yyyy","dateFormatItem-yMMM":"LLL y","dateFormatItem-yMMMd":"d.M.yyyy","dateFormatItem-yMMMEd":"E, d. MMM y","dateFormatItem-yQ":"Q yyyy","dateFormatItem-yQQQ":"QQQ y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}",
"dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"\u00c9ra","field-year":"Rok","field-month":"Mesiac","field-week":"T\u00fd\u017ede\u0148",
"field-day":"De\u0148","field-day-relative+-1":"V\u010dera","field-day-relative+0":"Dnes","field-day-relative+1":"Zajtra","field-weekday":"De\u0148 v t\u00fd\u017edni","field-dayperiod":"\u010cas\u0165 d\u0148a","field-hour":"Hodina","field-minute":"Min\u00fata","field-second":"Sekunda","field-zone":"P\u00e1smo","dateFormatItem-MMMMd":"d. MMMM","dateFormatItem-MMMMEd":"E, d. MMMM","dateFormatItem-mmss":"mm:ss","dateFormatItem-yMMMM":"LLLL y","dateFormatItem-yyQ":"Q yy","dateFormatItem-yyQQQQ":"QQQQ yy",
"dateFormatItem-yyyyM":"M.yyyy","dateFormatItem-yyyyMMMM":"LLLL y","field-year-relative+-1":"Minul\u00fd rok","field-year-relative+0":"Tento rok","field-year-relative+1":"Bud\u00faci rok","field-month-relative+-1":"Posledn\u00fd mesiac","field-month-relative+0":"Tento mesiac","field-month-relative+1":"Bud\u00faci mesiac","field-week-relative+-1":"Minul\u00fd t\u00fd\u017ede\u0148","field-week-relative+0":"Tento t\u00fd\u017ede\u0148","field-week-relative+1":"Bud\u00faci t\u00fd\u017ede\u0148","field-day-relative+-2":"Predv\u010derom",
"field-day-relative+2":"Pozajtra"},"dojo/cldr/nls/number":{decimal:",",group:"\u00a0",list:",",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"NaN",decimalFormat:"#,##0.###","decimalFormat-short":"000\u00a0bil'.'",scientificFormat:"#E0",percentFormat:"#,##0\u00a0%","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]",
"currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"#,##0.00\u00a0\u00a4"},"dijit/form/nls/validate":{invalidMessage:"Zadan\u00e1 hodnota nie je platn\u00e1.",missingMessage:"T\u00e1to hodnota je povinn\u00e1.",rangeMessage:"T\u00e1to hodnota je mimo rozsah."},"dijit/form/nls/ComboBox":{previousMessage:"Predch\u00e1dzaj\u00face mo\u017enosti",nextMessage:"Viac mo\u017enost\u00ed"}});