//>>built
define("phpr/nls/main_pl",{"dijit/nls/loading":{loadingState:"\u0141adowanie...",errorState:"Niestety, wyst\u0105pi\u0142 b\u0142\u0105d"},"dojo/cldr/nls/gregorian":{"months-format-abbr":"sty,lut,mar,kwi,maj,cze,lip,sie,wrz,pa\u017a,lis,gru".split(","),"months-format-narrow":"s,l,m,k,m,c,l,s,w,p,l,g".split(","),"months-format-wide":"stycznia,lutego,marca,kwietnia,maja,czerwca,lipca,sierpnia,wrze\u015bnia,pa\u017adziernika,listopada,grudnia".split(","),"months-standAlone-abbr":"sty,lut,mar,kwi,maj,cze,lip,sie,wrz,pa\u017a,lis,gru".split(","),
"months-standAlone-narrow":"s,l,m,k,m,c,l,s,w,p,l,g".split(","),"months-standAlone-wide":"stycze\u0144,luty,marzec,kwiecie\u0144,maj,czerwiec,lipiec,sierpie\u0144,wrzesie\u0144,pa\u017adziernik,listopad,grudzie\u0144".split(","),"days-format-abbr":"niedz.,pon.,wt.,\u015br.,czw.,pt.,sob.".split(","),"days-format-narrow":"N,P,W,\u015a,C,P,S".split(","),"days-format-wide":"niedziela,poniedzia\u0142ek,wtorek,\u015broda,czwartek,pi\u0105tek,sobota".split(","),"days-standAlone-abbr":"niedz.,pon.,wt.,\u015br.,czw.,pt.,sob.".split(","),
"days-standAlone-narrow":"N,P,W,\u015a,C,P,S".split(","),"days-standAlone-wide":"niedziela,poniedzia\u0142ek,wtorek,\u015broda,czwartek,pi\u0105tek,sobota".split(","),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["I kwarta\u0142","II kwarta\u0142","III kwarta\u0142","IV kwarta\u0142"],"quarters-standAlone-abbr":["1 kw.","2 kw.","3 kw.","4 kw."],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["I kwarta\u0142",
"II kwarta\u0142","III kwarta\u0142","IV kwarta\u0142"],"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM","dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"PM","dayPeriods-format-wide-am":"AM","dayPeriods-format-wide-pm":"PM",eraNames:["p.n.e.","n.e."],eraAbbr:["p.n.e.","n.e."],eraNarrow:["p.n.e.","n.e."],"dateFormat-full":"EEEE, d MMMM y","dateFormat-long":"d MMMM y","dateFormat-medium":"d MMM y","dateFormat-short":"dd.MM.yyyy","timeFormat-full":"HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z",
"timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d","dateFormatItem-Ed":"E, d","dateFormatItem-h":"hh a","dateFormatItem-H":"HH","dateFormatItem-hm":"hh:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"hh:mm:ss a","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-M":"L","dateFormatItem-Md":"d.MM","dateFormatItem-MEd":"E, d.MM","dateFormatItem-MMM":"LLL",
"dateFormatItem-MMMd":"d MMM","dateFormatItem-MMMEd":"E, d MMM","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yM":"MM.yyyy","dateFormatItem-yMd":"d.MM.yyyy","dateFormatItem-yMEd":"E, d.MM.yyyy","dateFormatItem-yMMM":"LLL y","dateFormatItem-yMMMd":"d MMM y","dateFormatItem-yMMMEd":"E, d MMM y","dateFormatItem-yQ":"yyyy Q","dateFormatItem-yQQQ":"y QQQ","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}",
"dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"Era","field-year":"Rok","field-month":"Miesi\u0105c","field-week":"Tydzie\u0144","field-day":"Dzie\u0144",
"field-day-relative+-1":"Wczoraj","field-day-relative+0":"Dzisiaj","field-day-relative+1":"Jutro","field-weekday":"Dzie\u0144 tygodnia","field-dayperiod":"Dayperiod","field-hour":"Godzina","field-minute":"Minuta","field-second":"Sekunda","field-zone":"Strefa","dayPeriods-format-wide-afternoon":"po po\u0142udniu","dayPeriods-format-wide-earlyMorning":"nad ranem","dayPeriods-format-wide-evening":"wieczorem","dayPeriods-format-wide-lateMorning":"przed po\u0142udniem","dayPeriods-format-wide-morning":"rano",
"dayPeriods-format-wide-night":"w nocy","dayPeriods-format-wide-noon":"w po\u0142udnie","dateFormatItem-MMdd":"d.MM","dateFormatItem-MMMMd":"d MMMM","dateFormatItem-yMMMM":"LLLL y","dateFormatItem-yyMMM":"LLL yy","dateFormatItem-yyQ":"Q yy","dateFormatItem-yyyyMM":"MM.yyyy","dateFormatItem-yyyyMMMM":"LLLL y","field-year-relative+-1":"Zesz\u0142y rok","field-year-relative+0":"Bie\u017c\u0105cy rok","field-year-relative+1":"Przysz\u0142y rok","field-month-relative+-1":"Zesz\u0142y miesi\u0105c","field-month-relative+0":"Bie\u017c\u0105cy miesi\u0105c",
"field-month-relative+1":"Przysz\u0142y miesi\u0105c","field-week-relative+-1":"Zesz\u0142y tydzie\u0144","field-week-relative+0":"Bie\u017c\u0105cy tydzie\u0144","field-week-relative+1":"Przysz\u0142y tydzie\u0144","field-day-relative+-2":"Przedwczoraj","field-day-relative+2":"Pojutrze"},"dojo/cldr/nls/number":{decimal:",",group:"\u00a0",list:";",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"NaN",decimalFormat:"#,##0.###","decimalFormat-short":"000\u00a0bln",
scientificFormat:"#E0",percentFormat:"#,##0%","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"#,##0.00\u00a0\u00a4"},"dijit/form/nls/validate":{invalidMessage:"Wprowadzona warto\u015b\u0107 jest nieprawid\u0142owa.",
missingMessage:"Ta warto\u015b\u0107 jest wymagana.",rangeMessage:"Ta warto\u015b\u0107 jest spoza zakresu."},"dijit/form/nls/ComboBox":{previousMessage:"Poprzednie wybory",nextMessage:"Wi\u0119cej wybor\u00f3w"}});