//>>built
define("phpr/nls/main_fr-fr",{"dijit/nls/loading":{loadingState:"Chargement...",errorState:"Une erreur est survenue"},"dojo/cldr/nls/gregorian":{"months-format-abbr":"janv.,f\u00e9vr.,mars,avr.,mai,juin,juil.,ao\u00fbt,sept.,oct.,nov.,d\u00e9c.".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-format-wide":"janvier,f\u00e9vrier,mars,avril,mai,juin,juillet,ao\u00fbt,septembre,octobre,novembre,d\u00e9cembre".split(","),"months-standAlone-abbr":"janv.,f\u00e9vr.,mars,avr.,mai,juin,juil.,ao\u00fbt,sept.,oct.,nov.,d\u00e9c.".split(","),
"months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-standAlone-wide":"janvier,f\u00e9vrier,mars,avril,mai,juin,juillet,ao\u00fbt,septembre,octobre,novembre,d\u00e9cembre".split(","),"days-format-abbr":"dim.,lun.,mar.,mer.,jeu.,ven.,sam.".split(","),"days-format-narrow":"D,L,M,M,J,V,S".split(","),"days-format-wide":"dimanche,lundi,mardi,mercredi,jeudi,vendredi,samedi".split(","),"days-standAlone-abbr":"dim.,lun.,mar.,mer.,jeu.,ven.,sam.".split(","),"days-standAlone-narrow":"D,L,M,M,J,V,S".split(","),
"days-standAlone-wide":"dimanche,lundi,mardi,mercredi,jeudi,vendredi,samedi".split(","),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-format-narrow":["T1","T2","T3","T4"],"quarters-format-wide":["1er trimestre","2e trimestre","3e trimestre","4e trimestre"],"quarters-standAlone-abbr":["T1","T2","T3","T4"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["1er trimestre","2e trimestre","3e trimestre","4e trimestre"],"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM",
"dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"p","dayPeriods-format-wide-am":"AM","dayPeriods-format-wide-pm":"PM",eraNames:["avant J\u00e9sus-Christ","apr\u00e8s J\u00e9sus-Christ"],eraAbbr:["av. J.-C.","ap. J.-C."],eraNarrow:["av. J.-C.","ap. J.-C."],"dateFormat-full":"EEEE d MMMM y","dateFormat-long":"d MMMM y","dateFormat-medium":"d MMM y","dateFormat-short":"dd/MM/yy","timeFormat-full":"HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z","timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm",
"dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d","dateFormatItem-Ed":"E d","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-M":"L","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E d/M","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"d MMM","dateFormatItem-MMMEd":"E d MMM",
"dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yM":"M/yyyy","dateFormatItem-yMd":"d/M/yyyy","dateFormatItem-yMEd":"E d/M/yyyy","dateFormatItem-yMMM":"MMM y","dateFormatItem-yMMMd":"d MMM y","dateFormatItem-yMMMEd":"E d MMM y","dateFormatItem-yQ":"'T'Q y","dateFormatItem-yQQQ":"QQQ y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"\u00e8re","field-year":"ann\u00e9e","field-month":"mois","field-week":"semaine","field-day":"jour","field-day-relative+-1":"hier","field-day-relative+0":"aujourd\u2019hui","field-day-relative+1":"demain",
"field-weekday":"jour de la semaine","field-dayperiod":"cadran","field-hour":"heure","field-minute":"minute","field-second":"seconde","field-zone":"fuseau horaire","dayPeriods-format-wide-afternoon":"apr\u00e8s-midi","dayPeriods-format-wide-morning":"matin","dayPeriods-format-wide-night":"soir","dayPeriods-format-wide-noon":"midi","dateFormatItem-MMd":"d/MM","dateFormatItem-MMdd":"dd/MM","dateFormatItem-MMMdd":"dd MMM","dateFormatItem-MMMMEd":"E d MMMM","dateFormatItem-yyMM":"MM/yy","dateFormatItem-yyMMM":"MMM yy",
"dateFormatItem-yyMMMd":"d MMM yy","dateFormatItem-yyMMMEd":"E d MMM yy","dateFormatItem-yyQ":"'T'Q yy","dateFormatItem-yyQQQQ":"QQQQ yy","dateFormatItem-yyyyMMMM":"MMMM y","field-year-relative+-1":"l\u2019ann\u00e9e derni\u00e8re","field-year-relative+0":"cette ann\u00e9e","field-year-relative+1":"l\u2019ann\u00e9e prochaine","field-month-relative+-1":"le mois dernier","field-month-relative+0":"ce mois-ci","field-month-relative+1":"le mois prochain","field-week-relative+-1":"la semaine derni\u00e8re",
"field-week-relative+0":"cette semaine","field-week-relative+1":"la semaine prochaine","field-day-relative+-2":"avant-hier","field-day-relative+2":"apr\u00e8s-demain"},"dojo/cldr/nls/number":{decimal:",",group:"\u00a0",list:";",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"NaN",decimalFormat:"#,##0.###","decimalFormat-short":"000\u00a0Bn",scientificFormat:"#E0",percentFormat:"#,##0\u00a0%","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]",
"currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"#,##0.00\u00a0\u00a4"},"dijit/form/nls/validate":{invalidMessage:"La valeur indiqu\u00e9e n'est pas correcte.",missingMessage:"Cette valeur est requise.",rangeMessage:"Cette valeur n'est pas comprise dans la plage autoris\u00e9e."},
"dijit/form/nls/ComboBox":{previousMessage:"Choix pr\u00e9c\u00e9dents",nextMessage:"Plus de choix"}});