//>>built
define("phpr/nls/main_fi-fi",{"dijit/nls/loading":{loadingState:"Lataus on meneill\u00e4\u00e4n...",errorState:"On ilmennyt virhe."},"dojo/cldr/nls/gregorian":{"months-format-abbr":"tammikuuta,helmikuuta,maaliskuuta,huhtikuuta,toukokuuta,kes\u00e4kuuta,hein\u00e4kuuta,elokuuta,syyskuuta,lokakuuta,marraskuuta,joulukuuta".split(","),"months-format-narrow":"T,H,M,H,T,K,H,E,S,L,M,J".split(","),"months-format-wide":"tammikuuta,helmikuuta,maaliskuuta,huhtikuuta,toukokuuta,kes\u00e4kuuta,hein\u00e4kuuta,elokuuta,syyskuuta,lokakuuta,marraskuuta,joulukuuta".split(","),
"months-standAlone-abbr":"tammi,helmi,maalis,huhti,touko,kes\u00e4,hein\u00e4,elo,syys,loka,marras,joulu".split(","),"months-standAlone-narrow":"T,H,M,H,T,K,H,E,S,L,M,J".split(","),"months-standAlone-wide":"tammikuu,helmikuu,maaliskuu,huhtikuu,toukokuu,kes\u00e4kuu,hein\u00e4kuu,elokuu,syyskuu,lokakuu,marraskuu,joulukuu".split(","),"days-format-abbr":"su,ma,ti,ke,to,pe,la".split(","),"days-format-narrow":"S,M,T,K,T,P,L".split(","),"days-format-wide":"sunnuntaina,maanantaina,tiistaina,keskiviikkona,torstaina,perjantaina,lauantaina".split(","),
"days-standAlone-abbr":"su,ma,ti,ke,to,pe,la".split(","),"days-standAlone-narrow":"S,M,T,K,T,P,L".split(","),"days-standAlone-wide":"sunnuntai,maanantai,tiistai,keskiviikko,torstai,perjantai,lauantai".split(","),"quarters-format-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"quarters-standAlone-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],
"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"dayPeriods-format-abbr-am":"ap.","dayPeriods-format-abbr-pm":"ip.","dayPeriods-format-narrow-am":"ap.","dayPeriods-format-narrow-pm":"ip.","dayPeriods-format-wide-am":"ap.","dayPeriods-format-wide-pm":"ip.",eraNames:["ennen Kristuksen syntym\u00e4\u00e4","j\u00e4lkeen Kristuksen syntym\u00e4n"],eraAbbr:["eKr.","jKr."],eraNarrow:["eK","jK"],"dateFormat-full":"cccc, d. MMMM y",
"dateFormat-long":"d. MMMM y","dateFormat-medium":"d.M.yyyy","dateFormat-short":"d.M.yyyy","timeFormat-full":"H.mm.ss zzzz","timeFormat-long":"H.mm.ss z","timeFormat-medium":"H.mm.ss","timeFormat-short":"H.mm","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d","dateFormatItem-Ed":"ccc d.","dateFormatItem-h":"h a","dateFormatItem-H":"H","dateFormatItem-hm":"h.mm a","dateFormatItem-Hm":"H.mm","dateFormatItem-hms":"h.mm.ss a",
"dateFormatItem-Hms":"H.mm.ss","dateFormatItem-M":"L","dateFormatItem-Md":"d.M.","dateFormatItem-MEd":"E d.M.","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MMMEd":"E d. MMM","dateFormatItem-ms":"mm.ss","dateFormatItem-y":"y","dateFormatItem-yM":"L.yyyy","dateFormatItem-yMd":"d.M.yyyy","dateFormatItem-yMEd":"E d.M.yyyy","dateFormatItem-yMMM":"LLL y","dateFormatItem-yMMMd":"d. MMM y","dateFormatItem-yMMMEd":"E d. MMM y","dateFormatItem-yQ":"Q/yyyy","dateFormatItem-yQQQ":"QQQ y",
"dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"aikakausi","field-year":"vuosi","field-month":"kuukausi","field-week":"viikko","field-day":"p\u00e4iv\u00e4","field-day-relative+-1":"eilen","field-day-relative+0":"t\u00e4n\u00e4\u00e4n","field-day-relative+1":"huomenna","field-weekday":"viikonp\u00e4iv\u00e4","field-dayperiod":"vuorokaudenaika","field-hour":"tunti","field-minute":"minuutti","field-second":"sekunti","field-zone":"aikavy\u00f6hyke","dayPeriods-standAlone-wide-am":"ap.","dayPeriods-standAlone-wide-pm":"ip.",
"dateFormatItem-yMMMMccccd":"cccc, d. MMMM y","dateFormatItem-yyMM":"M/yy","dateFormatItem-yyMMM":"LLLL yy","dateFormatItem-yyQ":"Q/yy","dateFormatItem-yyyyM":"M/yyyy","dateFormatItem-yyyyMEd":"E d.M.yyyy","dateFormatItem-yyyyMMMM":"LLLL y","dateFormatItem-yyyyQQQQ":"QQQQ y","field-year-relative+-1":"viime vuonna","field-year-relative+0":"t\u00e4n\u00e4 vuonna","field-year-relative+1":"ensi vuonna","field-month-relative+-1":"viime kuussa","field-month-relative+0":"t\u00e4ss\u00e4 kuussa","field-month-relative+1":"ensi kuussa",
"field-week-relative+-1":"viime viikolla","field-week-relative+0":"t\u00e4ll\u00e4 viikolla","field-week-relative+1":"ensi viikolla","field-day-relative+-2":"toissap\u00e4iv\u00e4n\u00e4","field-day-relative+2":"ylihuomenna"},"dojo/cldr/nls/number":{decimal:",",group:"\u00a0",list:";",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"ep\u00e4luku",decimalFormat:"#,##0.###","decimalFormat-short":"000\u00a0b",scientificFormat:"#E0",percentFormat:"#,##0\u00a0%",
"currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"#,##0.00\u00a0\u00a4"},"dijit/form/nls/validate":{invalidMessage:"Annettu arvo ei kelpaa.",missingMessage:"T\u00e4m\u00e4 arvo on pakollinen.",
rangeMessage:"T\u00e4m\u00e4 arvo on sallitun alueen ulkopuolella."},"dijit/form/nls/ComboBox":{previousMessage:"Edelliset valinnat",nextMessage:"Lis\u00e4\u00e4 valintoja"}});