//>>built
define("phpr/nls/main_pt-pt",{"dijit/nls/loading":{loadingState:"A carregar...",errorState:"Lamentamos, mas ocorreu um erro"},"dojo/cldr/nls/gregorian":{"months-format-abbr":"Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-format-wide":"Janeiro,Fevereiro,Mar\u00e7o,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro".split(","),"months-standAlone-abbr":"Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez".split(","),
"months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-standAlone-wide":"Janeiro,Fevereiro,Mar\u00e7o,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro".split(","),"days-format-abbr":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),"days-format-narrow":"D,S,T,Q,Q,S,S".split(","),"days-format-wide":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),"days-standAlone-abbr":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),
"days-standAlone-narrow":"D,S,T,Q,Q,S,S".split(","),"days-standAlone-wide":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),"quarters-format-abbr":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-standAlone-abbr":["1.\u00ba trimestre","2.\u00ba trimestre",
"3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"dayPeriods-format-abbr-am":"a.m.","dayPeriods-format-abbr-pm":"p.m.","dayPeriods-format-narrow-am":"a.m.","dayPeriods-format-narrow-pm":"p.m.","dayPeriods-format-wide-am":"a.m.","dayPeriods-format-wide-pm":"p.m.",eraNames:["Antes de Cristo","Ano do Senhor"],eraAbbr:["a.C.","d.C."],eraNarrow:["a.C.",
"d.C."],"dateFormat-full":"EEEE, d 'de' MMMM 'de' y","dateFormat-long":"d 'de' MMMM 'de' y","dateFormat-medium":"dd/MM/yyyy","dateFormat-short":"dd/MM/yy","timeFormat-full":"H:mm:ss zzzz","timeFormat-long":"H:mm:ss z","timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d","dateFormatItem-Ed":"E, d","dateFormatItem-h":"h a","dateFormatItem-H":"HH",
"dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-M":"L","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E, dd/MM","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"d/MM","dateFormatItem-MMMEd":"E, d/MM","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yM":"MM/yyyy","dateFormatItem-yMd":"dd/MM/yyyy","dateFormatItem-yMEd":"E, dd/MM/yyyy","dateFormatItem-yMMM":"MM/y","dateFormatItem-yMMMd":"d/MM/y",
"dateFormatItem-yMMMEd":"E, d/MM/y","dateFormatItem-yQ":"QQQ 'de' yyyy","dateFormatItem-yQQQ":"QQQ 'de' y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"Era","field-year":"Ano","field-month":"M\u00eas","field-week":"Semana","field-day":"Dia","field-day-relative+-1":"Ontem","field-day-relative+0":"Hoje","field-day-relative+1":"Amanh\u00e3","field-weekday":"Dia da semana","field-dayperiod":"Per\u00edodo do dia","field-hour":"Hora","field-minute":"Minuto","field-second":"Segundo","field-zone":"Fuso",
"dayPeriods-format-wide-afternoon":"tarde","dayPeriods-format-wide-morning":"manh\u00e3","dayPeriods-format-wide-night":"noite","dayPeriods-format-wide-noon":"meio-dia","dateFormatItem-HHmm":"HH:mm","dateFormatItem-HHmmss":"HH:mm:ss","dateFormatItem-MMdd":"dd/MM","dateFormatItem-yyMM":"MM/yy","dateFormatItem-yyMMM":"MM/yy","dateFormatItem-yyMMMd":"d/MM/yy","dateFormatItem-yyMMMEd":"E, d/MM/yy","dateFormatItem-yyQ":"QQQ 'de' yy","dateFormatItem-yyyyMM":"MM/yyyy","dateFormatItem-yyyyMMM":"MMM 'de' y",
"field-year-relative+-1":"\u00daltimo ano","field-year-relative+0":"Este ano","field-year-relative+1":"Pr\u00f3ximo ano","field-month-relative+-1":"\u00daltimo m\u00eas","field-month-relative+0":"Este m\u00eas","field-month-relative+1":"Pr\u00f3ximo m\u00eas","field-week-relative+-1":"\u00daltima semana","field-week-relative+0":"Esta semana","field-week-relative+1":"Pr\u00f3xima semana","field-day-relative+-2":"Anteontem","field-day-relative+2":"Depois de amanh\u00e3","dayPeriods-standAlone-abbr-am":"a.m.",
"dayPeriods-standAlone-abbr-pm":"p.m.","dayPeriods-standAlone-wide-am":"a.m.","dayPeriods-standAlone-wide-pm":"p.m.","dateFormatItem-MMMMd":"d 'de' MMMM","dateFormatItem-MMMMEd":"E, d 'de' MMMM","dateFormatItem-yMMMM":"MMMM 'de' y","dateFormatItem-yMMMMd":"d 'de' MMMM 'de' y","dateFormatItem-yMMMMEd":"E, d 'de' MMMM 'de' y"},"dojo/cldr/nls/number":{decimal:",",group:"\u00a0",list:";",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"NaN",decimalFormat:"#,##0.###",
"decimalFormat-short":"000\u00a0Bi",scientificFormat:"#E0",percentFormat:"#,##0%","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"#,##0.00\u00a0\u00a4"},"dijit/form/nls/validate":{invalidMessage:"O valor introduzido n\u00e3o \u00e9 v\u00e1lido.",
missingMessage:"Este valor \u00e9 requerido.",rangeMessage:"Este valor encontra-se fora do intervalo."},"dijit/form/nls/ComboBox":{previousMessage:"Op\u00e7\u00f5es anteriores",nextMessage:"Mais op\u00e7\u00f5es"}});