//>>built
define("phpr/nls/main_en-gb",{"dijit/nls/loading":{loadingState:"Loading...",errorState:"Sorry, an error occurred"},"dojo/cldr/nls/gregorian":{"months-format-abbr":"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-format-wide":"January,February,March,April,May,June,July,August,September,October,November,December".split(","),"months-standAlone-abbr":"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),"months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),
"months-standAlone-wide":"January,February,March,April,May,June,July,August,September,October,November,December".split(","),"days-format-abbr":"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),"days-format-narrow":"S,M,T,W,T,F,S".split(","),"days-format-wide":"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),"days-standAlone-abbr":"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),"days-standAlone-narrow":"S,M,T,W,T,F,S".split(","),"days-standAlone-wide":"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),
"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM","dayPeriods-format-narrow-am":"a","dayPeriods-format-narrow-pm":"p","dayPeriods-format-wide-am":"AM",
"dayPeriods-format-wide-pm":"PM",eraNames:["Before Christ","Anno Domini"],eraAbbr:["BC","AD"],eraNarrow:["B","A"],"dateFormat-full":"EEEE, d MMMM y","dateFormat-long":"d MMMM y","dateFormat-medium":"d MMM y","dateFormat-short":"dd/MM/yyyy","timeFormat-full":"HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z","timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d",
"dateFormatItem-Ed":"d E","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-M":"L","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E, d/M","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"d MMM","dateFormatItem-MMMEd":"E d MMM","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yM":"M/y","dateFormatItem-yMd":"d/M/yyyy","dateFormatItem-yMEd":"E, d/M/yyyy",
"dateFormatItem-yMMM":"MMM y","dateFormatItem-yMMMd":"d MMM y","dateFormatItem-yMMMEd":"E, d MMM y","dateFormatItem-yQ":"Q y","dateFormatItem-yQQQ":"QQQ y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"Era","field-year":"Year","field-month":"Month","field-week":"Week","field-day":"Day","field-day-relative+-1":"Yesterday","field-day-relative+0":"Today","field-day-relative+1":"Tomorrow","field-weekday":"Day of the Week","field-dayperiod":"AM/PM","field-hour":"Hour","field-minute":"Minute","field-second":"Second",
"field-zone":"Time Zone","dayPeriods-format-narrow-noon":"n","dayPeriods-format-wide-noon":"noon","field-year-relative+-1":"Last year","field-year-relative+0":"This year","field-year-relative+1":"Next year","field-month-relative+-1":"Last month","field-month-relative+0":"This month","field-month-relative+1":"Next month","field-week-relative+-1":"Last week","field-week-relative+0":"This week","field-week-relative+1":"Next week","dateFormatItem-MMdd":"dd/MM","dateFormatItem-MMMMd":"d MMMM","dateFormatItem-yyMMM":"MMM yy",
"dateFormatItem-yyyyMM":"MM/yyyy","dateFormatItem-yyyyMMMM":"MMMM y"},"dojo/cldr/nls/number":{decimal:".",group:",",list:";",percentSign:"%",plusSign:"+",minusSign:"-",exponential:"E",perMille:"\u2030",infinity:"\u221e",nan:"NaN",decimalFormat:"#,##0.###","decimalFormat-short":"000T",scientificFormat:"#E0",percentFormat:"#,##0%","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0",
"currencySpacing-afterCurrency-currencyMatch":"[:letter:]","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"\u00a4#,##0.00"},"dijit/form/nls/validate":{invalidMessage:"The value entered is not valid.",missingMessage:"This value is required.",rangeMessage:"This value is out of range."},"dijit/form/nls/ComboBox":{previousMessage:"Previous choices",nextMessage:"More choices"}});