//>>built
define("phpr/nls/main_sv",{"dijit/nls/loading":{loadingState:"L\u00e4ser in...",errorState:"Det har intr\u00e4ffat ett fel."},"dojo/cldr/nls/gregorian":{"months-format-abbr":"jan,feb,mar,apr,maj,jun,jul,aug,sep,okt,nov,dec".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-format-wide":"januari,februari,mars,april,maj,juni,juli,augusti,september,oktober,november,december".split(","),"months-standAlone-abbr":"jan,feb,mar,apr,maj,jun,jul,aug,sep,okt,nov,dec".split(","),
"months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"months-standAlone-wide":"januari,februari,mars,april,maj,juni,juli,augusti,september,oktober,november,december".split(","),"days-format-abbr":"s\u00f6n,m\u00e5n,tis,ons,tors,fre,l\u00f6r".split(","),"days-format-narrow":"S,M,T,O,T,F,L".split(","),"days-format-wide":"s\u00f6ndag,m\u00e5ndag,tisdag,onsdag,torsdag,fredag,l\u00f6rdag".split(","),"days-standAlone-abbr":"s\u00f6n,m\u00e5n,tis,ons,tor,fre,l\u00f6r".split(","),"days-standAlone-narrow":"S,M,T,O,T,F,L".split(","),
"days-standAlone-wide":"s\u00f6ndag,m\u00e5ndag,tisdag,onsdag,torsdag,fredag,l\u00f6rdag".split(","),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["1:a kvartalet","2:a kvartalet","3:e kvartalet","4:e kvartalet"],"quarters-standAlone-abbr":["K1","K2","K3","K4"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["1:a kvartalet","2:a kvartalet","3:e kvartalet","4:e kvartalet"],"dayPeriods-format-abbr-am":"FM","dayPeriods-format-abbr-pm":"EM",
"dayPeriods-format-narrow-am":"f","dayPeriods-format-narrow-pm":"e","dayPeriods-format-wide-am":"fm","dayPeriods-format-wide-pm":"em",eraNames:["f\u00f6re Kristus","efter Kristus"],eraAbbr:["f.Kr.","e.Kr."],eraNarrow:["f.Kr.","e.Kr."],"dateFormat-full":"EEEE'en' 'den' d:'e' MMMM y","dateFormat-long":"d MMMM y","dateFormat-medium":"d MMM y","dateFormat-short":"yyyy-MM-dd","timeFormat-full":"'kl'. HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z","timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm",
"dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-d":"d","dateFormatItem-Ed":"E d","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-M":"L","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E d/M","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"d MMM","dateFormatItem-MMMEd":"E d MMM",
"dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yM":"yyyy-MM","dateFormatItem-yMd":"yyyy-MM-dd","dateFormatItem-yMEd":"E, yyyy-MM-dd","dateFormatItem-yMMM":"MMM y","dateFormatItem-yMMMd":"d MMM y","dateFormatItem-yMMMEd":"E d MMM y","dateFormatItem-yQ":"yyyy Q","dateFormatItem-yQQQ":"y QQQ","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{0} {1}","field-era":"era","field-year":"\u00e5r","field-month":"m\u00e5nad","field-week":"vecka","field-day":"dag","field-day-relative+-1":"i g\u00e5r","field-day-relative+0":"i dag",
"field-day-relative+1":"i morgon","field-weekday":"veckodag","field-dayperiod":"fm/em","field-hour":"timme","field-minute":"minut","field-second":"sekund","field-zone":"tidszon","dateFormatItem-MMd":"d/M","dateFormatItem-MMdd":"dd/MM","dateFormatItem-MMMMd":"d:'e' MMMM","dateFormatItem-MMMMEd":"E d:'e' MMMM","dateFormatItem-yyMM":"yy-MM","dateFormatItem-yyMMM":"MMM -yy","dateFormatItem-yyQ":"Q yy","dateFormatItem-yyyyMM":"yyyy-MM","dateFormatItem-yyyyMMM":"MMM y","dateFormatItem-yyyyQQQQ":"QQQQ y",
"field-year-relative+-1":"i fjol","field-year-relative+0":"i \u00e5r","field-year-relative+1":"n\u00e4sta \u00e5r","field-month-relative+-1":"f\u00f6rra m\u00e5naden","field-month-relative+0":"denna m\u00e5nad","field-month-relative+1":"n\u00e4sta m\u00e5nad","field-week-relative+-1":"f\u00f6rra veckan","field-week-relative+0":"denna vecka","field-week-relative+1":"n\u00e4sta vecka","field-day-relative+-2":"i f\u00f6rrg\u00e5r","field-day-relative+2":"i \u00f6vermorgon"},"dojo/cldr/nls/number":{decimal:",",
group:"\u00a0",list:";",percentSign:"%",plusSign:"+",minusSign:"\u2212",exponential:"\u00d710^",perMille:"\u2030",infinity:"\u221e",nan:"\u00a4\u00a4\u00a4",decimalFormat:"#,##0.###","decimalFormat-short":"000\u00a0trl",scientificFormat:"#E0",percentFormat:"#,##0\u00a0%","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-insertBetween":"\u00a0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]",
"currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-afterCurrency-insertBetween":"\u00a0",currencyFormat:"#,##0.00\u00a0\u00a4"},"dijit/form/nls/validate":{invalidMessage:"Angivet v\u00e4rde \u00e4r inte giltigt.",missingMessage:"V\u00e4rdet kr\u00e4vs.",rangeMessage:"V\u00e4rdet ligger utanf\u00f6r intervallet."},"dijit/form/nls/ComboBox":{previousMessage:"Tidigare val",nextMessage:"Fler val"}});