/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.filter._FilterExpr"]||(dojo._hasResource["dojox.grid.enhanced.plugins.filter._FilterExpr"]=!0,dojo.provide("dojox.grid.enhanced.plugins.filter._FilterExpr"),dojo.require("dojox.grid.enhanced.plugins.filter._DataExprs"),dojo.require("dojo.date"),function(){function f(a,b,c,d){a=a.applyRow(c,d);b=b.applyRow(c,d);c=a.getValue();b=b.getValue();return a instanceof e.TimeExpr?dojo.date.compare(c,b,"time"):a instanceof e.DateExpr?dojo.date.compare(c,b,"date"):
(a instanceof e.StringExpr&&(c=c.toLowerCase(),b=String(b).toLowerCase()),c==b?0:c<b?-1:1)}var e=dojox.grid.enhanced.plugins.filter;dojo.declare("dojox.grid.enhanced.plugins.filter.LogicAND",e._BiOpExpr,{_name:"and",_calculate:function(a,b,c,d){a=a.applyRow(c,d).getValue()&&b.applyRow(c,d).getValue();return new e.BooleanExpr(a)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LogicOR",e._BiOpExpr,{_name:"or",_calculate:function(a,b,c,d){a=a.applyRow(c,d).getValue()||b.applyRow(c,d).getValue();
return new e.BooleanExpr(a)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LogicXOR",e._BiOpExpr,{_name:"xor",_calculate:function(a,b,c,d){a=a.applyRow(c,d).getValue();b=b.applyRow(c,d).getValue();return new e.BooleanExpr(!!a!=!!b)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LogicNOT",e._UniOpExpr,{_name:"not",_calculate:function(a,b,c){return new e.BooleanExpr(!a.applyRow(b,c).getValue())}});dojo.declare("dojox.grid.enhanced.plugins.filter.LogicALL",e._OperatorExpr,{_name:"all",applyRow:function(a,
b){for(var c=0,d=!0;d&&this._operands[c]instanceof e._ConditionExpr;++c)d=this._operands[c].applyRow(a,b).getValue();return new e.BooleanExpr(d)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LogicANY",e._OperatorExpr,{_name:"any",applyRow:function(a,b){for(var c=0,d=!1;!d&&this._operands[c]instanceof e._ConditionExpr;++c)d=this._operands[c].applyRow(a,b).getValue();return new e.BooleanExpr(d)}});dojo.declare("dojox.grid.enhanced.plugins.filter.EqualTo",e._BiOpExpr,{_name:"equal",_calculate:function(a,
b,c,d){a=f(a,b,c,d);return new e.BooleanExpr(a===0)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LessThan",e._BiOpExpr,{_name:"less",_calculate:function(a,b,c,d){a=f(a,b,c,d);return new e.BooleanExpr(a<0)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LessThanOrEqualTo",e._BiOpExpr,{_name:"lessEqual",_calculate:function(a,b,c,d){a=f(a,b,c,d);return new e.BooleanExpr(a<=0)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LargerThan",e._BiOpExpr,{_name:"larger",_calculate:function(a,
b,c,d){a=f(a,b,c,d);return new e.BooleanExpr(a>0)}});dojo.declare("dojox.grid.enhanced.plugins.filter.LargerThanOrEqualTo",e._BiOpExpr,{_name:"largerEqual",_calculate:function(a,b,c,d){a=f(a,b,c,d);return new e.BooleanExpr(a>=0)}});dojo.declare("dojox.grid.enhanced.plugins.filter.Contains",e._BiOpExpr,{_name:"contains",_calculate:function(a,b,c,d){a=String(a.applyRow(c,d).getValue()).toLowerCase();b=String(b.applyRow(c,d).getValue()).toLowerCase();return new e.BooleanExpr(a.indexOf(b)>=0)}});dojo.declare("dojox.grid.enhanced.plugins.filter.StartsWith",
e._BiOpExpr,{_name:"startsWith",_calculate:function(a,b,c,d){a=String(a.applyRow(c,d).getValue()).toLowerCase();b=String(b.applyRow(c,d).getValue()).toLowerCase();return new e.BooleanExpr(a.substring(0,b.length)==b)}});dojo.declare("dojox.grid.enhanced.plugins.filter.EndsWith",e._BiOpExpr,{_name:"endsWith",_calculate:function(a,b,c,d){a=String(a.applyRow(c,d).getValue()).toLowerCase();b=String(b.applyRow(c,d).getValue()).toLowerCase();return new e.BooleanExpr(a.substring(a.length-b.length)==b)}});
dojo.declare("dojox.grid.enhanced.plugins.filter.Matches",e._BiOpExpr,{_name:"matches",_calculate:function(a,b,c,d){a=String(a.applyRow(c,d).getValue());b=RegExp(b.applyRow(c,d).getValue());return new e.BooleanExpr(a.search(b)>=0)}});dojo.declare("dojox.grid.enhanced.plugins.filter.IsEmpty",e._UniOpExpr,{_name:"isEmpty",_calculate:function(a,b,c){a=a.applyRow(b,c).getValue();return new e.BooleanExpr(a===""||a==null)}})}());