/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.filter.FilterDefDialog"]||(dojo._hasResource["dojox.grid.enhanced.plugins.filter.FilterDefDialog"]=!0,dojo.provide("dojox.grid.enhanced.plugins.filter.FilterDefDialog"),dojo.require("dijit.dijit"),dojo.require("dijit.Tooltip"),dojo.require("dojox.grid.enhanced.plugins.Dialog"),dojo.require("dijit.form.ComboBox"),dojo.require("dijit.form.Select"),dojo.require("dijit.form.TextBox"),dojo.require("dijit.form.CheckBox"),dojo.require("dijit.form.NumberTextBox"),
dojo.require("dijit.form.DateTextBox"),dojo.require("dijit.form.TimeTextBox"),dojo.require("dijit.form.Button"),dojo.require("dijit.layout.AccordionContainer"),dojo.require("dijit.layout.ContentPane"),dojo.require("dojo.date.locale"),dojo.require("dojo.string"),dojo.require("dojox.grid.enhanced.plugins.filter.FilterBuilder"),dojo.require("dojox.grid.cells.dijit"),dojo.require("dojox.html.ellipsis"),dojo.require("dojox.html.metrics"),dojo.require("dojo.window"),function(){var i=dojox.grid.enhanced.plugins.filter,
h={relSelect:60,accordionTitle:70,removeCBoxBtn:-1,colSelect:90,condSelect:95,valueBox:10,addCBoxBtn:20,filterBtn:30,clearBtn:40,cancelBtn:50};dojo.declare("dojox.grid.enhanced.plugins.filter.FilterDefDialog",null,{curColIdx:-1,_relOpCls:"logicall",_savedCriterias:null,plugin:null,constructor:function(a){var b;b=this.plugin=a.plugin,a=b;this.builder=new i.FilterBuilder;this._setupData();this._cboxes=[];this.defaultType=a.args.defaultType||"string";(this.filterDefPane=new i.FilterDefPane({dlg:this})).startup();
(this._defPane=new dojox.grid.enhanced.plugins.Dialog({refNode:this.plugin.grid.domNode,title:a.nls.filterDefDialogTitle,"class":"dojoxGridFDTitlePane",iconClass:"dojoxGridFDPaneIcon",content:this.filterDefPane})).startup();this._defPane.connect(a.grid.layer("filter"),"filterDef",dojo.hitch(this,"_onSetFilter"));a.grid.setFilter=dojo.hitch(this,"setFilter");a.grid.getFilter=dojo.hitch(this,"getFilter");a.grid.getFilterRelation=dojo.hitch(this,function(){return this._relOpCls});a.connect(a.grid.layout,
"moveColumn",dojo.hitch(this,"onMoveColumn"))},onMoveColumn:function(a,c,b,d,f){if(this._savedCriterias&&b!=d){f&&--d;var e=b<d?b:d,g=b<d?d:b,j=d>e?1:-1;dojo.forEach(this._savedCriterias,function(a){var c=parseInt(a.column,10);if(!isNaN(c)&&c>=e&&c<=g)a.column=String(c==b?c+(g-e)*j:c-j)})}},destroy:function(){this._defPane.destroyRecursive();this._cboxes=this._dataTypeMap=this.builder=this.filterDefPane=this._defPane=null;var a=this.plugin.grid;a.setFilter=null;a.getFilter=null;this.plugin=a.getFilterRelation=
null},_setupData:function(){var a=this.plugin.nls;this._dataTypeMap={number:{valueBoxCls:{dft:dijit.form.NumberTextBox},conditions:[{label:a.conditionEqual,value:"equalto",selected:!0},{label:a.conditionNotEqual,value:"notequalto"},{label:a.conditionLess,value:"lessthan"},{label:a.conditionLessEqual,value:"lessthanorequalto"},{label:a.conditionLarger,value:"largerthan"},{label:a.conditionLargerEqual,value:"largerthanorequalto"},{label:a.conditionIsEmpty,value:"isempty"}]},string:{valueBoxCls:{dft:dijit.form.TextBox,
ac:i.UniqueComboBox},conditions:[{label:a.conditionContains,value:"contains",selected:!0},{label:a.conditionIs,value:"equalto"},{label:a.conditionStartsWith,value:"startswith"},{label:a.conditionEndWith,value:"endswith"},{label:a.conditionNotContain,value:"notcontains"},{label:a.conditionIsNot,value:"notequalto"},{label:a.conditionNotStartWith,value:"notstartswith"},{label:a.conditionNotEndWith,value:"notendswith"},{label:a.conditionIsEmpty,value:"isempty"}]},date:{valueBoxCls:{dft:dijit.form.DateTextBox},
conditions:[{label:a.conditionIs,value:"equalto",selected:!0},{label:a.conditionBefore,value:"lessthan"},{label:a.conditionAfter,value:"largerthan"},{label:a.conditionRange,value:"range"},{label:a.conditionIsEmpty,value:"isempty"}]},time:{valueBoxCls:{dft:dijit.form.TimeTextBox},conditions:[{label:a.conditionIs,value:"equalto",selected:!0},{label:a.conditionBefore,value:"lessthan"},{label:a.conditionAfter,value:"largerthan"},{label:a.conditionRange,value:"range"},{label:a.conditionIsEmpty,value:"isempty"}]},
"boolean":{valueBoxCls:{dft:i.BooleanValueBox},conditions:[{label:a.conditionIs,value:"equalto",selected:!0},{label:a.conditionIsEmpty,value:"isempty"}]}}},setFilter:function(a,c){a=a||[];dojo.isArray(a)||(a=[a]);var b=function(){if(a.length){this._savedCriterias=dojo.map(a,function(a){var b=a.type||this.defaultType;return{type:b,column:String(a.column),condition:a.condition,value:a.value,colTxt:this.getColumnLabelByValue(String(a.column)),condTxt:this.getConditionLabelByValue(b,a.condition),formattedVal:a.formattedVal||
a.value}},this);this._criteriasChanged=!0;if(c==="logicall"||c==="logicany")this._relOpCls=c;var b=dojo.map(a,this.getExprForCriteria,this),b=this.builder.buildExpression(b.length==1?b[0]:{op:this._relOpCls,data:b});this.plugin.grid.layer("filter").filterDef(b);this.plugin.filterBar.toggleClearFilterBtn(!1)}this._closeDlgAndUpdateGrid()};if(this._savedCriterias){this._clearWithoutRefresh=!0;var d=dojo.connect(this,"clearFilter",this,function(){dojo.disconnect(d);this._clearWithoutRefresh=!1;b.apply(this)});
this.onClearFilter()}else b.apply(this)},getFilter:function(){return dojo.clone(this._savedCriterias)||[]},getColumnLabelByValue:function(a){var c=this.plugin.nls;return a.toLowerCase()=="anycolumn"?c.anyColumnOption:(a=this.plugin.grid.layout.cells[parseInt(a,10)])?a.name||a.field:""},getConditionLabelByValue:function(a,c){for(var b=this._dataTypeMap[a].conditions,d=b.length-1;d>=0;--d){var f=b[d];if(f.value==c.toLowerCase())return f.label}return""},addCriteriaBoxes:function(a){if(!(typeof a!="number"||
a<=0)){var c=this._cboxes,b=this.filterDefPane.cboxContainer,d=this.plugin.args.ruleCount,f=c.length;for(d>0&&f+a>d&&(a=d-f);a>0;--a)d=new i.CriteriaBox({dlg:this}),c.push(d),b.addChild(d);b.startup();this._updatePane();this._updateCBoxTitles();b.selectChild(c[c.length-1]);this.filterDefPane.criteriaPane.scrollTop=1E6;if(c.length===4)dojo.isIE<=6&&!this.__alreadyResizedForIE6?(a=dojo.position(b.domNode),a.w-=dojox.html.metrics.getScrollbar().w,b.resize(a),this.__alreadyResizedForIE6=!0):b.resize()}},
removeCriteriaBoxes:function(a,c){var b=this._cboxes,d=this.filterDefPane.cboxContainer,f=b.length,e=f-a,g=f-1,j=dojo.indexOf(b,d.selectedChildWidget.content);if(dojo.isArray(a)){g=a;g.sort();a=g.length;for(e=f-1;e>=0&&dojo.indexOf(g,e)>=0;--e);if(e>=0){e!=j&&d.selectChild(b[e]);for(e=a-1;e>=0;--e)g[e]>=0&&g[e]<f&&(d.removeChild(b[g[e]]),b.splice(g[e],1))}}else{if(c===!0)if(a>=0&&a<f)e=g=a,a=1;else return;else if(a instanceof i.CriteriaBox)f=a,a=1,e=g=dojo.indexOf(b,f);else if(typeof a!="number"||
a<=0)return;else a>=f&&(a=g,e=1);if(g<e)return;for(j>=e&&j<=g&&d.selectChild(b[e?e-1:g+1]);g>=e;--g)d.removeChild(b[g]);b.splice(e,a)}this._updatePane();this._updateCBoxTitles();b.length===3&&d.resize()},getCriteria:function(a){return typeof a!="number"?this._savedCriterias?this._savedCriterias.length:0:this._savedCriterias&&this._savedCriterias[a]?dojo.mixin({relation:this._relOpCls=="logicall"?this.plugin.nls.and:this.plugin.nls.or},this._savedCriterias[a]):null},getExprForCriteria:function(a){if(a.column==
"anycolumn"){var c=dojo.filter(this.plugin.grid.layout.cells,function(a){return!(a.filterable===!1||a.hidden)});return{op:"logicany",data:dojo.map(c,function(b){return this.getExprForColumn(a.value,b.index,a.type,a.condition)},this)}}else return this.getExprForColumn(a.value,a.column,a.type,a.condition)},getExprForColumn:function(a,c,b,d){var c=parseInt(c,10),f=this.plugin.grid.layout.cells[c],e=f.field||f.name,c={datatype:b||this.getColumnType(c),args:f.dataTypeArgs,isColumn:!0},f=[dojo.mixin({data:this.plugin.args.isServerSide?
e:f},c)];c.isColumn=!1;d=="range"?f.push(dojo.mixin({data:a.start},c),dojo.mixin({data:a.end},c)):d!="isempty"&&f.push(dojo.mixin({data:a},c));return{op:d,data:f}},getColumnType:function(a){a=this.plugin.grid.layout.cells[parseInt(a,10)];if(!a||!a.datatype)return this.defaultType;a=String(a.datatype).toLowerCase();return this._dataTypeMap[a]?a:this.defaultType},clearFilter:function(a){if(this._savedCriterias){this._savedCriterias=null;this.plugin.grid.layer("filter").filterDef(null);try{this.plugin.filterBar.toggleClearFilterBtn(!0),
this.filterDefPane._clearFilterBtn.set("disabled",!0),this.removeCriteriaBoxes(this._cboxes.length-1),this._cboxes[0].load({})}catch(c){}a?this.closeDialog():this._closeDlgAndUpdateGrid()}},showDialog:function(a){this._defPane.show();this.plugin.filterStatusTip.closeDialog();this._prepareDialog(a)},closeDialog:function(){this._defPane.hide()},onFilter:function(){this.canFilter()&&(this._defineFilter(),this._closeDlgAndUpdateGrid(),this.plugin.filterBar.toggleClearFilterBtn(!1))},onClearFilter:function(){this._savedCriterias&&
(this._savedCriterias.length>1?this.plugin.clearFilterDialog.show():this.clearFilter(this._clearWithoutRefresh))},onCancel:function(){var a=this._savedCriterias,c=this._cboxes;a?(this.addCriteriaBoxes(a.length-c.length),this.removeCriteriaBoxes(c.length-a.length),dojo.forEach(a,function(a,d){c[d].load(a)})):(this.removeCriteriaBoxes(c.length-1),c[0].load({}));this.closeDialog()},onRendered:function(a){dojo.isFF?(a=this._defPane,a._getFocusItems(a.domNode),dijit.focus(a._firstFocusItem)):(a=dijit._getTabNavigable(dojo.byId(a.domNode)),
dijit.focus(a.lowest||a.first))},_onSetFilter:function(a){a===null&&this._savedCriterias&&this.clearFilter()},_prepareDialog:function(a){var c=this._savedCriterias,b=this._cboxes;this.curColIdx=a;if(c){if(this._criteriasChanged)if(this.filterDefPane._relSelect.set("value",this._relOpCls==="logicall"?"0":"1"),this._criteriasChanged=!1,a=c.length>b.length,this.addCriteriaBoxes(c.length-b.length),this.removeCriteriaBoxes(b.length-c.length),this.filterDefPane._clearFilterBtn.set("disabled",!1),a)dojo.forEach(c,
function(a,c){var e=dojo.connect(this,"onRendered",function(g){g==b[c]&&(dojo.disconnect(e),g.load(a))})},this);else for(a=0;a<c.length;++a)b[a].load(c[a])}else if(b.length===0)this.addCriteriaBoxes(1);else for(a=0;c=b[a];++a)c.changeCurrentColumn();this.filterDefPane.cboxContainer.resize()},_defineFilter:function(){var a=this._cboxes,c=function(b){return dojo.filter(dojo.map(a,function(a){return a[b]()}),function(a){return!!a})},b=c("getExpr");this._savedCriterias=c("save");b=b.length==1?b[0]:{op:this._relOpCls,
data:b};b=this.builder.buildExpression(b);this.plugin.grid.layer("filter").filterDef(b);this.filterDefPane._clearFilterBtn.set("disabled",!1)},_updateCBoxTitles:function(){for(var a=this._cboxes,c=a.length;c>0;--c)a[c-1].updateRuleIndex(c),a[c-1].setAriaInfo(c)},_updatePane:function(){var a=this.filterDefPane;a._addCBoxBtn.set("disabled",this._cboxes.length==this.plugin.args.ruleCount);a._filterBtn.set("disabled",!this.canFilter())},canFilter:function(){return dojo.filter(this._cboxes,function(a){return!a.isEmpty()}).length>
0},_closeDlgAndUpdateGrid:function(){this.closeDialog();var a=this.plugin.grid;a.showMessage(a.loadingMessage);setTimeout(dojo.hitch(a,a._refresh),this._defPane.duration+10)}});dojo.declare("dojox.grid.enhanced.plugins.filter.FilterDefPane",[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.grid","enhanced/templates/FilterDefPane.html",'<div class="dojoxGridFDPane">\n\t<div class="dojoxGridFDPaneRelation">${_relMsgFront}\n\t<span class="dojoxGridFDPaneModes" dojoAttachPoint="criteriaModeNode">\n\t\t<select dojoAttachPoint="_relSelect" dojoType="dijit.form.Select" dojoAttachEvent="onChange: _onRelSelectChange">\n\t\t\t<option value="0">${_relAll}</option>\n\t\t\t<option value="1">${_relAny}</option>\n\t\t</select>\n\t</span>\n\t${_relMsgTail}\n\t</div>\n\t<div dojoAttachPoint="criteriaPane" class="dojoxGridFDPaneRulePane"></div>\n\t<div dojoAttachPoint="_addCBoxBtn" dojoType="dijit.form.Button" \n\t\tclass="dojoxGridFDPaneAddCBoxBtn" iconClass="dojoxGridFDPaneAddCBoxBtnIcon"\n\t\tdojoAttachEvent="onClick:_onAddCBox" label="${_addRuleBtnLabel}" showLabel="false">\n\t</div>\n\t<div class="dojoxGridFDPaneBtns" dojoAttachPoint="buttonsPane">\n\t\t<span dojoAttachPoint="_cancelBtn" dojoType="dijit.form.Button" \n\t\t\tdojoAttachEvent="onClick:_onCancel" label="${_cancelBtnLabel}">\n\t\t</span>\n\t\t<span dojoAttachPoint="_clearFilterBtn" dojoType="dijit.form.Button" \n\t\t\tdojoAttachEvent="onClick:_onClearFilter" label="${_clearBtnLabel}" disabled="true">\n\t\t</span>\n\t\t<span dojoAttachPoint="_filterBtn" dojoType="dijit.form.Button" \n\t\t\tdojoAttachEvent="onClick:_onFilter" label="${_filterBtnLabel}" disabled="true">\n\t\t</span>\n\t</div>\n</div>\n'),
widgetsInTemplate:!0,dlg:null,postMixInProperties:function(){this.plugin=this.dlg.plugin;var a=this.plugin.nls;this._addRuleBtnLabel=a.addRuleButton;this._cancelBtnLabel=a.cancelButton;this._clearBtnLabel=a.clearButton;this._filterBtnLabel=a.filterButton;this._relAll=a.relationAll;this._relAny=a.relationAny;this._relMsgFront=a.relationMsgFront;this._relMsgTail=a.relationMsgTail},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onkeypress","_onKey");(this.cboxContainer=new i.AccordionContainer({nls:this.plugin.nls})).placeAt(this.criteriaPane);
this._relSelect.set("tabIndex",h.relSelect);this._addCBoxBtn.set("tabIndex",h.addCBoxBtn);this._cancelBtn.set("tabIndex",h.cancelBtn);this._clearFilterBtn.set("tabIndex",h.clearBtn);this._filterBtn.set("tabIndex",h.filterBtn);var a=this.plugin.nls;dijit.setWaiState(this._relSelect.domNode,"label",a.waiRelAll);dijit.setWaiState(this._addCBoxBtn.domNode,"label",a.waiAddRuleButton);dijit.setWaiState(this._cancelBtn.domNode,"label",a.waiCancelButton);dijit.setWaiState(this._clearFilterBtn.domNode,"label",
a.waiClearButton);dijit.setWaiState(this._filterBtn.domNode,"label",a.waiFilterButton);this._relSelect.set("value",this.dlg._relOpCls==="logicall"?"0":"1")},uninitialize:function(){this.cboxContainer.destroyRecursive();this.dlg=this.plugin=null},_onRelSelectChange:function(a){this.dlg._relOpCls=a=="0"?"logicall":"logicany";dijit.setWaiState(this._relSelect.domNode,"label",this.plugin.nls[a=="0"?"waiRelAll":"waiRelAny"])},_onAddCBox:function(){this.dlg.addCriteriaBoxes(1)},_onCancel:function(){this.dlg.onCancel()},
_onClearFilter:function(){this.dlg.onClearFilter()},_onFilter:function(){this.dlg.onFilter()},_onKey:function(a){if(a.keyCode==dojo.keys.ENTER)this.dlg.onFilter()}});dojo.declare("dojox.grid.enhanced.plugins.filter.CriteriaBox",[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.grid","enhanced/templates/CriteriaBox.html",'<div class="dojoxGridFCBox">\n\t<div class="dojoxGridFCBoxSelCol" dojoAttachPoint="selColNode">\n\t\t<span class="dojoxGridFCBoxField">${_colSelectLabel}</span>\n\t\t<select dojoAttachPoint="_colSelect" dojoType="dijit.form.Select" \n\t\t\tclass="dojoxGridFCBoxColSelect"\n\t\t\tdojoAttachEvent="onChange:_onChangeColumn">\n\t\t</select>\n\t</div>\n\t<div class="dojoxGridFCBoxCondition" dojoAttachPoint="condNode">\n\t\t<span class="dojoxGridFCBoxField">${_condSelectLabel}</span>\n\t\t<select dojoAttachPoint="_condSelect" dojoType="dijit.form.Select" \n\t\t\tclass="dojoxGridFCBoxCondSelect"\n\t\t\tdojoAttachEvent="onChange:_onChangeCondition">\n\t\t</select>\n\t\t<div class="dojoxGridFCBoxCondSelectAlt" dojoAttachPoint="_condSelectAlt" style="display:none;"></div>\n\t</div>\n\t<div class="dojoxGridFCBoxValue" dojoAttachPoint="valueNode">\n\t\t<span class="dojoxGridFCBoxField">${_valueBoxLabel}</span>\n\t</div>\n</div>\n'),
widgetsInTemplate:!0,dlg:null,postMixInProperties:function(){this.plugin=this.dlg.plugin;this._curValueBox=null;var a=this.plugin.nls;this._colSelectLabel=a.columnSelectLabel;this._condSelectLabel=a.conditionSelectLabel;this._valueBoxLabel=a.valueBoxLabel;this._anyColumnOption=a.anyColumnOption},postCreate:function(){var a=this.dlg,c=this.plugin.grid;this._colSelect.set("tabIndex",h.colSelect);this._colOptions=this._getColumnOptions();this._colSelect.addOption([{label:this.plugin.nls.anyColumnOption,
value:"anycolumn",selected:a.curColIdx<0},{value:""}].concat(this._colOptions));this._condSelect.set("tabIndex",h.condSelect);this._condSelect.addOption(this._getUsableConditions(a.getColumnType(a.curColIdx)));this._showSelectOrLabel(this._condSelect,this._condSelectAlt);this.connect(c.layout,"moveColumn","onMoveColumn")},_getColumnOptions:function(){var a=this.dlg.curColIdx>=0?String(this.dlg.curColIdx):"anycolumn";return dojo.map(dojo.filter(this.plugin.grid.layout.cells,function(a){return!(a.filterable===
!1||a.hidden)}),function(c){return{label:c.name||c.field,value:String(c.index),selected:a==String(c.index)}})},onMoveColumn:function(){var a=this._onChangeColumn;this._onChangeColumn=function(){};var c=this._colSelect.get("selectedOptions");this._colSelect.removeOption(this._colOptions);this._colOptions=this._getColumnOptions();this._colSelect.addOption(this._colOptions);for(var b=0;b<this._colOptions.length;++b)if(this._colOptions[b].label==c.label)break;b<this._colOptions.length&&this._colSelect.set("value",
this._colOptions[b].value);var d=this;setTimeout(function(){d._onChangeColumn=a},0)},onRemove:function(){this.dlg.removeCriteriaBoxes(this)},uninitialize:function(){if(this._curValueBox)this._curValueBox.destroyRecursive(),this._curValueBox=null;this.dlg=this.plugin=null},_showSelectOrLabel:function(a,c){var b=a.getOptions();b.length==1?(c.innerHTML=b[0].label,dojo.style(a.domNode,"display","none"),dojo.style(c,"display","")):(dojo.style(a.domNode,"display",""),dojo.style(c,"display","none"))},_onChangeColumn:function(a){this._checkValidCriteria();
a=this.dlg.getColumnType(a);this._setConditionsByType(a);this._setValueBoxByType(a);this._updateValueBox()},_onChangeCondition:function(a){this._checkValidCriteria();a=a=="range";if(a^this._isRange)this._isRange=a,this._setValueBoxByType(this.dlg.getColumnType(this._colSelect.get("value")));this._updateValueBox()},_updateValueBox:function(){this._curValueBox.set("disabled",this._condSelect.get("value")=="isempty")},_checkValidCriteria:function(){setTimeout(dojo.hitch(this,function(){this.updateRuleTitle();
this.dlg._updatePane()}),0)},_createValueBox:function(a,c){var b=dojo.hitch(c.cbox,"_checkValidCriteria");return new a(dojo.mixin(c,{tabIndex:h.valueBox,onKeyPress:b,onChange:b,"class":"dojoxGridFCBoxValueBox"}))},_createRangeBox:function(a,c){var b=dojo.hitch(c.cbox,"_checkValidCriteria");dojo.mixin(c,{tabIndex:h.valueBox,onKeyPress:b,onChange:b});var b=dojo.create("div",{"class":"dojoxGridFCBoxValueBox"}),d=new a(c),f=dojo.create("span",{"class":"dojoxGridFCBoxRangeValueTxt",innerHTML:this.plugin.nls.rangeTo}),
e=new a(c);dojo.addClass(d.domNode,"dojoxGridFCBoxStartValue");dojo.addClass(e.domNode,"dojoxGridFCBoxEndValue");b.appendChild(d.domNode);b.appendChild(f);b.appendChild(e.domNode);b.domNode=b;b.set=function(a,b){dojo.isObject(b)&&(d.set("value",b.start),e.set("value",b.end))};b.get=function(){var a=d.get("value"),b=e.get("value");return a&&b?{start:a,end:b}:""};return b},changeCurrentColumn:function(){var a=this.dlg.curColIdx;this._colSelect.removeOption(this._colOptions);this._colOptions=this._getColumnOptions();
this._colSelect.addOption(this._colOptions);this._colSelect.set("value",a>=0?String(a):"anycolumn");this.updateRuleTitle(!0)},curColumn:function(){return this._colSelect.getOptions(this._colSelect.get("value")).label},curCondition:function(){return this._condSelect.getOptions(this._condSelect.get("value")).label},curValue:function(){return this._condSelect.get("value")=="isempty"?"":this._curValueBox?this._curValueBox.get("value"):""},save:function(){if(this.isEmpty())return null;var a=this._colSelect.get("value"),
c=this.dlg.getColumnType(a),b=this.curValue(),d=this._condSelect.get("value");return{column:a,condition:d,value:b,formattedVal:this.formatValue(c,d,b),type:c,colTxt:this.curColumn(),condTxt:this.curCondition()}},load:function(a){var c=[this._onChangeColumn,this._onChangeCondition];this._onChangeColumn=this._onChangeCondition=function(){};a.column&&this._colSelect.set("value",a.column);a.condition&&this._condSelect.set("value",a.condition);a.type?this._setValueBoxByType(a.type):a.type=this.dlg.getColumnType(this._colSelect.get("value"));
var b=a.value||"";(b||a.type!="date"&&a.type!="time")&&this._curValueBox.set("value",b);this._updateValueBox();setTimeout(dojo.hitch(this,function(){this._onChangeColumn=c[0];this._onChangeCondition=c[1]}),0)},getExpr:function(){if(this.isEmpty())return null;var a=this._colSelect.get("value");return this.dlg.getExprForCriteria({type:this.dlg.getColumnType(a),column:a,condition:this._condSelect.get("value"),value:this.curValue()})},isEmpty:function(){if(this._condSelect.get("value")=="isempty")return!1;
var a=this.curValue();return a===""||a===null||typeof a=="undefined"||typeof a=="number"&&isNaN(a)},updateRuleTitle:function(a){var c=this._pane._buttonWidget.titleTextNode,b=["<div class='dojoxEllipsis'>"];if(a||this.isEmpty())c.title=dojo.string.substitute(this.plugin.nls.ruleTitleTemplate,[this._ruleIndex||1]),b.push(c.title);else{var d=this.dlg.getColumnType(this._colSelect.get("value")),a=this.curColumn(),f=this.curCondition(),d=this.formatValue(d,this._condSelect.get("value"),this.curValue());
b.push(a,"&nbsp;<span class='dojoxGridRuleTitleCondition'>",f,"</span>&nbsp;",d);c.title=[a," ",f," ",d].join("")}c.innerHTML=b.join("");if(dojo.isMoz)dojo.create("div",{style:"width: 100%; height: 100%; position: absolute; top: 0; left: 0; z-index: 9999;"},c).title=c.title},updateRuleIndex:function(a){if(this._ruleIndex!=a)this._ruleIndex=a,this.isEmpty()&&this.updateRuleTitle()},setAriaInfo:function(a){var c=dojo.string.substitute,b=this.plugin.nls;dijit.setWaiState(this._colSelect.domNode,"label",
c(b.waiColumnSelectTemplate,[a]));dijit.setWaiState(this._condSelect.domNode,"label",c(b.waiConditionSelectTemplate,[a]));dijit.setWaiState(this._pane._removeCBoxBtn.domNode,"label",c(b.waiRemoveRuleButtonTemplate,[a]));this._index=a},_getUsableConditions:function(a){var c=this.dlg._dataTypeMap[a].conditions,a=(this.plugin.args.disabledConditions||{})[a],b=parseInt(this._colSelect.get("value"),10),b=isNaN(b)?(this.plugin.args.disabledConditions||{}).anycolumn:this.plugin.grid.layout.cells[b].disabledConditions;
dojo.isArray(a)||(a=[]);dojo.isArray(b)||(b=[]);a=a.concat(b);if(a.length){var d={};dojo.forEach(a,function(a){dojo.isString(a)&&(d[a.toLowerCase()]=!0)});return dojo.filter(c,function(a){return!(a.value in d)})}return c},_setConditionsByType:function(a){var c=this._condSelect;c.removeOption(c.options);c.addOption(this._getUsableConditions(a));this._showSelectOrLabel(this._condSelect,this._condSelectAlt)},_setValueBoxByType:function(a){if(this._curValueBox){this.valueNode.removeChild(this._curValueBox.domNode);
try{this._curValueBox.destroyRecursive()}catch(c){}delete this._curValueBox}var b=this.dlg._dataTypeMap[a].valueBoxCls[this._getValueBoxClsInfo(this._colSelect.get("value"),a)],a=this._getValueBoxArgByType(a);this._curValueBox=this[this._isRange?"_createRangeBox":"_createValueBox"](b,a);this.valueNode.appendChild(this._curValueBox.domNode);dijit.setWaiState(this._curValueBox.domNode,"label",dojo.string.substitute(this.plugin.nls.waiValueBoxTemplate,[this._index]));this.dlg.onRendered(this)},_getValueBoxArgByType:function(a){var c=
this.plugin.grid,b=c.layout.cells[parseInt(this._colSelect.get("value"),10)],d={cbox:this};if(a=="string"){if(b&&(b.suggestion||b.autoComplete))dojo.mixin(d,{store:c.store,searchAttr:b.field||b.name,fetchProperties:{sort:[{attribute:b.field||b.name}]}})}else a=="boolean"&&dojo.mixin(d,this.dlg.builder.defaultArgs["boolean"]);b&&b.dataTypeArgs&&dojo.mixin(d,b.dataTypeArgs);return d},formatValue:function(a,c,b){if(c=="isempty")return"";if(a=="date"||a=="time"){var a={selector:a},d=dojo.date.locale.format;
return c=="range"?dojo.string.substitute(this.plugin.nls.rangeTemplate,[d(b.start,a),d(b.end,a)]):d(b,a)}else if(a=="boolean")return b?this._curValueBox._lblTrue:this._curValueBox._lblFalse;return b},_getValueBoxClsInfo:function(a,c){var b=this.plugin.grid.layout.cells[parseInt(a,10)];return c=="string"?b&&(b.suggestion||b.autoComplete)?"ac":"dft":"dft"}});dojo.declare("dojox.grid.enhanced.plugins.filter.AccordionContainer",dijit.layout.AccordionContainer,{nls:null,addChild:function(a,c){var b=arguments[0]=
a._pane=new dijit.layout.ContentPane({content:a});this.inherited(arguments);this._modifyChild(b)},removeChild:function(a){var c=a,b=!1;if(a._pane)b=!0,c=arguments[0]=a._pane;this.inherited(arguments);b&&(this._hackHeight(!1,this._titleHeight),b=this.getChildren(),b.length===1&&dojo.style(b[0]._removeCBoxBtn.domNode,"display","none"));c.destroyRecursive()},selectChild:function(a){if(a._pane)arguments[0]=a._pane;this.inherited(arguments)},resize:function(){this.inherited(arguments);dojo.forEach(this.getChildren(),
this._setupTitleDom)},startup:function(){this._started||(this.inherited(arguments),parseInt(dojo.isIE,10)==7&&dojo.some(this._connects,function(a){if(a[0][1]=="onresize")return this.disconnect(a),!0},this),dojo.forEach(this.getChildren(),function(a){this._modifyChild(a,!0)},this))},_onKeyPress:function(a,c){if(!this.disabled&&!(a.altKey||!c&&!a.ctrlKey)){var b=dojo.keys,d=a.charOrCode,f=dojo._isBodyLtr(),e=null;if(c&&d==b.UP_ARROW||a.ctrlKey&&d==b.PAGE_UP)e=!1;else if(c&&d==b.DOWN_ARROW||a.ctrlKey&&
(d==b.PAGE_DOWN||d==b.TAB))e=!0;else if(d==(f?b.LEFT_ARROW:b.RIGHT_ARROW))e=this._focusOnRemoveBtn?null:!1,this._focusOnRemoveBtn=!this._focusOnRemoveBtn;else if(d==(f?b.RIGHT_ARROW:b.LEFT_ARROW))e=this._focusOnRemoveBtn?!0:null,this._focusOnRemoveBtn=!this._focusOnRemoveBtn;else return;e!==null&&this._adjacent(e)._buttonWidget._onTitleClick();dojo.stopEvent(a);dojo.window.scrollIntoView(this.selectedChildWidget._buttonWidget.domNode.parentNode);dojo.isIE&&this.selectedChildWidget._removeCBoxBtn.focusNode.setAttribute("tabIndex",
this._focusOnRemoveBtn?h.accordionTitle:-1);dijit.focus(this.selectedChildWidget[this._focusOnRemoveBtn?"_removeCBoxBtn":"_buttonWidget"].focusNode)}},_modifyChild:function(a,c){if(a&&this._started){dojo.style(a.domNode,"overflow","hidden");a._buttonWidget.connect(a._buttonWidget,"_setSelectedAttr",function(){this.focusNode.setAttribute("tabIndex",this.selected?h.accordionTitle:"-1")});var b=this;a._buttonWidget.connect(a._buttonWidget.domNode,"onclick",function(){b._focusOnRemoveBtn=!1});(a._removeCBoxBtn=
new dijit.form.Button({label:this.nls.removeRuleButton,showLabel:!1,iconClass:"dojoxGridFCBoxRemoveCBoxBtnIcon",tabIndex:h.removeCBoxBtn,onClick:dojo.hitch(a.content,"onRemove"),onKeyPress:function(c){b._onKeyPress(c,a._buttonWidget.contentWidget)}})).placeAt(a._buttonWidget.domNode);var d,f=this.getChildren();if(f.length===1)a._buttonWidget.set("selected",!0),dojo.style(a._removeCBoxBtn.domNode,"display","none");else for(d=0;d<f.length;++d)f[d]._removeCBoxBtn&&dojo.style(f[d]._removeCBoxBtn.domNode,
"display","");this._setupTitleDom(a);if(!this._titleHeight)for(d=0;d<f.length;++d)if(f[d]!=this.selectedChildWidget){this._titleHeight=dojo.marginBox(f[d]._buttonWidget.domNode.parentNode).h;break}c||this._hackHeight(!0,this._titleHeight)}},_hackHeight:function(a,c){var b=this.getChildren(),d=this.domNode,f=dojo.style(d,"height");if(a)if(b.length>1)d.style.height=f+c+"px";else return;else d.style.height=f-c+"px";this.resize()},_setupTitleDom:function(a){var c=dojo.contentBox(a._buttonWidget.titleNode).w;
dojo.isIE<8&&(c-=8);dojo.style(a._buttonWidget.titleTextNode,"width",c+"px")}});dojo.declare("dojox.grid.enhanced.plugins.filter.UniqueComboBox",dijit.form.ComboBox,{_openResultList:function(a){var c={},b=this.store,d=this.searchAttr;arguments[0]=dojo.filter(a,function(a){var a=b.getValue(a,d),e=c[a];c[a]=!0;return!e});this.inherited(arguments)},_onKey:function(a){a.charOrCode===dojo.keys.ENTER&&this._opened&&dojo.stopEvent(a);this.inherited(arguments)}});dojo.declare("dojox.grid.enhanced.plugins.filter.BooleanValueBox",
[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.grid","enhanced/templates/FilterBoolValueBox.html",'<div class="dojoxGridBoolValueBox">\n\t<div class="dojoxGridTrueBox">\n\t\t<input dojoType="dijit.form.RadioButton" type=\'radio\' name=\'a1\' id=\'${_baseId}_rbTrue\' checked="true" \n\t\t\tdojoAttachPoint="rbTrue" dojoAttachEvent="onChange: onChange"/>\n\t\t<div class="dojoxGridTrueLabel" for=\'${_baseId}_rbTrue\'>${_lblTrue}</div>\n\t</div>\n\t<div class="dojoxGridFalseBox">\n\t\t<input dojoType="dijit.form.RadioButton" dojoAttachPoint="rbFalse" type=\'radio\' name=\'a1\' id=\'${_baseId}_rbFalse\'/>\n\t\t<div class="dojoxGridTrueLabel" for=\'${_baseId}_rbFalse\'>${_lblFalse}</div>\n\t</div>\n</div>\n'),
widgetsInTemplate:!0,constructor:function(a){var c=a.cbox.plugin.nls;this._baseId=a.cbox.id;this._lblTrue=a.trueLabel||c.trueLabel||"true";this._lblFalse=a.falseLabel||c.falseLabel||"false";this.args=a},postCreate:function(){this.onChange()},onChange:function(){},get:function(){return this.rbTrue.get("checked")},set:function(a,c){this.inherited(arguments);a=="value"&&(this.rbTrue.set("checked",!!c),this.rbFalse.set("checked",!c))}})}());