/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.filter.FilterStatusTip"]||(dojo._hasResource["dojox.grid.enhanced.plugins.filter.FilterStatusTip"]=!0,dojo.provide("dojox.grid.enhanced.plugins.filter.FilterStatusTip"),dojo.requireLocalization("dojox.grid.enhanced","Filter",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hr,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.require("dijit.TooltipDialog"),dojo.require("dijit._base.popup"),dojo.require("dijit.form.Button"),dojo.require("dojo.string"),
dojo.require("dojo.date.locale"),function(){dojo.declare("dojox.grid.enhanced.plugins.filter.FilterStatusTip",null,{constructor:function(a){var b;b=this.plugin=a.plugin,a=b;this._statusHeader=["<table border='0' cellspacing='0' class=''><thead><tr class=''><th class=''><div>",a.nls.statusTipHeaderColumn,"</div></th><th class=' lastColumn'><div>",a.nls.statusTipHeaderCondition,"</div></th></tr></thead><tbody>"].join("");this._removedCriterias=[];this._rules=[];this.statusPane=new dojox.grid.enhanced.plugins.filter.FilterStatusPane;
this._dlg=new dijit.TooltipDialog({"class":"dojoxGridFStatusTipDialog",content:this.statusPane,autofocus:!1,onMouseLeave:dojo.hitch(this,function(){this.closeDialog()})});this._dlg.connect(this._dlg.domNode,"click",dojo.hitch(this,this._modifyFilter))},destroy:function(){this._dlg.destroyRecursive()},showDialog:function(a,b,e){this._pos={x:a,y:b};dijit.popup.close(this._dlg);this._removedCriterias=[];this._rules=[];this._updateStatus(e);dijit.popup.open({popup:this._dlg,parent:this.plugin.filterBar,
x:a-12,y:b-3})},closeDialog:function(){dijit.popup.close(this._dlg);if(this._removedCriterias.length)this.plugin.filterDefDialog.removeCriteriaBoxes(this._removedCriterias),this._removedCriterias=[],this.plugin.filterDefDialog.onFilter()},_updateStatus:function(a){var b,e=this.plugin,c=e.nls,d=this.statusPane;b=e.filterDefDialog;if(b.getCriteria()===0)d.statusTitle.innerHTML=c.statusTipTitleNoFilter,d.statusRel.innerHTML=d.statusRelPre.innerHTML=d.statusRelPost.innerHTML="",b=e.grid.layout.cells[a],
b=dojo.string.substitute(c.statusTipMsg,[b?"'"+(b.name||b.field)+"'":c.anycolumn]);else{d.statusTitle.innerHTML=c.statusTipTitleHasFilter;d.statusRelPre.innerHTML=c.statusTipRelPre+"&nbsp;";d.statusRelPost.innerHTML="&nbsp;"+c.statusTipRelPost;d.statusRel.innerHTML=b._relOpCls=="logicall"?c.all:c.any;this._rules=[];c=0;for(a=b.getCriteria(c++);a;)a.index=c-1,this._rules.push(a),a=b.getCriteria(c++);b=this._createStatusDetail()}d.statusDetailNode.innerHTML=b;this._addButtonForRules()},_createStatusDetail:function(){return this._statusHeader+
dojo.map(this._rules,function(a,b){return this._getCriteriaStr(a,b)},this).join("")+"</tbody></table>"},_addButtonForRules:function(){this._rules.length>1&&dojo.query(".dojoxGridFStatusTipHandle",this.statusPane.statusDetailNode).forEach(dojo.hitch(this,function(a,b){(new dijit.form.Button({label:this.plugin.nls.removeRuleButton,showLabel:!1,iconClass:"dojoxGridFStatusTipDelRuleBtnIcon",onClick:dojo.hitch(this,function(a){a.stopPropagation();this._removedCriterias.push(this._rules[b].index);this._rules.splice(b,
1);this.statusPane.statusDetailNode.innerHTML=this._createStatusDetail();this._addButtonForRules()})})).placeAt(a,"last")}))},_getCriteriaStr:function(a,b){return["<tr class=' ",b%2?"dojoxGridFStatusTipOddRow":"","'><td class=''>",a.colTxt,"</td><td class=''><div class='dojoxGridFStatusTipHandle'><span class='dojoxGridFStatusTipCondition'>",a.condTxt,"&nbsp;</span>",a.formattedVal,"</div></td></tr>"].join("")},_modifyFilter:function(){this.closeDialog();var a=this.plugin;a.filterDefDialog.showDialog(a.filterBar.getColumnIdx(this._pos.x))}});
dojo.declare("dojox.grid.enhanced.plugins.filter.FilterStatusPane",[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.grid","enhanced/templates/FilterStatusPane.html",'<div class="dojoxGridFStatusTip">\n\t<div class="dojoxGridFStatusTipHead">\n\t\t<span class="dojoxGridFStatusTipTitle" dojoAttachPoint="statusTitle"></span\n\t\t><span class="dojoxGridFStatusTipRelPre" dojoAttachPoint="statusRelPre"></span\n\t\t><span class="dojoxGridFStatusTipRel" dojoAttachPoint="statusRel"></span\n\t\t><span class="dojoxGridFStatusTipRelPost" dojoAttachPoint="statusRelPost"></span>\n\t</div>\n\t<div class="dojoxGridFStatusTipDetail" dojoAttachPoint="statusDetailNode"></div>\n</div>\n')})}());