/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.filter.FilterLayer"]||(dojo._hasResource["dojox.grid.enhanced.plugins.filter.FilterLayer"]=!0,dojo.provide("dojox.grid.enhanced.plugins.filter.FilterLayer"),dojo.require("dojox.grid.enhanced.plugins.filter._FilterExpr"),dojo.require("dojox.grid.enhanced.plugins._StoreLayer"),function(){var f=dojox.grid.enhanced.plugins,g=function(a,b){return b?dojo.hitch(a||dojo.global,b):function(){}},j=function(a){var b={};if(a&&dojo.isObject(a))for(var d in a)b[d]=
a[d];return b};dojo.declare("dojox.grid.enhanced.plugins.filter._FilterLayerMixin",null,{tags:["sizeChange"],name:function(){return"filter"},onFilterDefined:function(){},onFiltered:function(){}});dojo.declare("dojox.grid.enhanced.plugins.filter.ServerSideFilterLayer",[f._ServerSideLayer,f.filter._FilterLayerMixin],{constructor:function(a){this._onUserCommandLoad=a.setupFilterQuery||this._onUserCommandLoad;this.filterDef(null)},filterDef:function(a){if(a){this._filter=a;var b=a.toObject();this.command("filter",
this._isStateful?dojo.toJson(b):b);this.command("clear",null);this.useCommands(!0);this.onFilterDefined(a)}else if(a===null)this._filter=null,this.command("filter",null),this.command("clear",!0),this.useCommands(!0),this.onFilterDefined(null);return this._filter},onCommandLoad:function(a,b){this.inherited(arguments);var d=b.onBegin;if(this._isStateful){var c;if(a){this.command("filter",null);this.command("clear",null);this.useCommands(!1);var e=a.split(",");if(e.length>=2)c=this._filteredSize=parseInt(e[0],
10),this.onFiltered(c,parseInt(e[1],10));else return}else c=this._filteredSize;if(this.enabled())b.onBegin=function(a,e){g(b.scope,d)(c,e)}}else{var h=this;b.onBegin=function(a,c){if(!h._filter)h._storeSize=a;h.onFiltered(a,h._storeSize||a);c.onBegin=d;g(b.scope,d)(a,c)}}}});dojo.declare("dojox.grid.enhanced.plugins.filter.ClientSideFilterLayer",[f._StoreLayer,f.filter._FilterLayerMixin],{_storeSize:-1,_fetchAll:!0,constructor:function(a){this.filterDef(null);a=dojo.isObject(a)?a:{};this.fetchAllOnFirstFilter(a.fetchAll);
this._getter=dojo.isFunction(a.getter)?a.getter:this._defaultGetter},_defaultGetter:function(a,b,d,c){return c.getValue(a,b)},filterDef:function(a){if(a!==void 0)this._filter=a,this.invalidate(),this.onFilterDefined(a);return this._filter},setGetter:function(a){if(dojo.isFunction(a))this._getter=a},fetchAllOnFirstFilter:function(a){if(a!==void 0)this._fetchAll=!!a;return this._fetchAll},invalidate:function(){this._items=[];this._nextUnfetchedIdx=0;this._result=[];this._indexMap=[];this._resultStartIdx=
0},_fetch:function(a,b){if(!this._filter){var d=a.onBegin,c=this;a.onBegin=function(b,e){g(a.scope,d)(b,e);c.onFiltered(b,b)};this.originFetch(a);return a}try{var e=b?b._nextResultItemIdx:a.start,e=e||0;if(!b){this._result=[];this._resultStartIdx=e;var h;if(dojo.isArray(a.sort)&&a.sort.length>0&&(h=dojo.toJson(a.sort))!=this._lastSortInfo)this.invalidate(),this._lastSortInfo=h}var i=typeof a.count=="number"?e+a.count-this._result.length:this._items.length;this._result=this._result.length?this._result.concat(this._items.slice(e,
i)):this._items.slice(a.start,typeof a.count=="number"?a.start+a.count:this._items.length);if(this._result.length>=a.count||this._hasReachedStoreEnd())this._completeQuery(a);else{if(!b)b=j(a),b.onBegin=dojo.hitch(this,this._onFetchBegin),b.onComplete=dojo.hitch(this,function(b,c){this._nextUnfetchedIdx+=b.length;this._doFilter(b,c.start,a);this._fetch(a,c)});b.start=this._nextUnfetchedIdx;this._fetchAll&&delete b.count;b._nextResultItemIdx=i<this._items.length?i:this._items.length;this.originFetch(b)}}catch(f){if(a.onError)g(a.scope,
a.onError)(f,a);else throw f;}return a},_hasReachedStoreEnd:function(){return this._storeSize>=0&&this._nextUnfetchedIdx>=this._storeSize},_applyFilter:function(a,b){var d=this._getter,c=this._store;try{return!!this._filter.applyRow(a,function(a,e){return d(a,e,b,c)}).getValue()}catch(e){return console.warn("FilterLayer._applyFilter() error: ",e),!1}},_doFilter:function(a,b,d){for(var c=0,e=0;c<a.length;++c)this._applyFilter(a[c],b+c)&&(g(d.scope,d.onItem)(a[c],d),e+=this._addCachedItems(a[c],this._items.length),
this._indexMap.push(b+c))},_onFetchBegin:function(a){this._storeSize=a},_completeQuery:function(a){var b=this._items.length;this._nextUnfetchedIdx<this._storeSize&&b++;g(a.scope,a.onBegin)(b,a);this.onFiltered(this._items.length,this._storeSize);g(a.scope,a.onComplete)(this._result,a)},_addCachedItems:function(a,b){dojo.isArray(a)||(a=[a]);for(var d=0;d<a.length;++d)this._items[b+d]=a[d];return a.length},onRowMappingChange:function(a){if(this._filter){var b=dojo.clone(a),d={},c;for(c in b)c=parseInt(c,
10),a[this._indexMap[c]]=this._indexMap[b[c]],d[this._indexMap[c]]||(d[this._indexMap[c]]=!0),d[c]||(d[c]=!0,delete a[c])}}})}());