/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gfx._base"]||(dojo._hasResource["dojox.gfx._base"]=!0,dojo.provide("dojox.gfx._base"),function(){var a=dojox.gfx,b=a._base;a._hasClass=function(a,b){var c=a.getAttribute("className");return c&&(" "+c+" ").indexOf(" "+b+" ")>=0};a._addClass=function(a,c){var b=a.getAttribute("className")||"";if(!b||(" "+b+" ").indexOf(" "+c+" ")<0)a.setAttribute("className",b+(b?" ":"")+c)};a._removeClass=function(a,b){var c=a.getAttribute("className");c&&a.setAttribute("className",c.replace(RegExp("(^|\\s+)"+
b+"(\\s+|$)"),"$1$2"))};b._getFontMeasurements=function(){var a={"1em":0,"1ex":0,"100%":0,"12pt":0,"16px":0,"xx-small":0,"x-small":0,small:0,medium:0,large:0,"x-large":0,"xx-large":0};if(dojo.isIE)dojo.doc.documentElement.style.fontSize="100%";var b=dojo.create("div",{style:{position:"absolute",left:"0",top:"-100px",width:"30px",height:"1000em",borderWidth:"0",margin:"0",padding:"0",outline:"none",lineHeight:"1",overflow:"hidden"}},dojo.body()),c;for(c in a)b.style.fontSize=c,a[c]=Math.round(b.offsetHeight*
12/16)*16/12/1E3;dojo.body().removeChild(b);return a};var c=null;b._getCachedFontMeasurements=function(a){if(a||!c)c=b._getFontMeasurements();return c};var d=null,i={};b._getTextBox=function(a,b,c){var e,f,h=arguments.length;d||(d=dojo.create("div",{style:{position:"absolute",top:"-10000px",left:"0"}},dojo.body()));e=d;e.className="";f=e.style;f.borderWidth="0";f.margin="0";f.padding="0";f.outline="0";if(h>1&&b)for(var g in b)g in i||(f[g]=b[g]);if(h>2&&c)e.className=c;e.innerHTML=a;return e.getBoundingClientRect?
(e=e.getBoundingClientRect(),{l:e.left,t:e.top,w:e.width||e.right-e.left,h:e.height||e.bottom-e.top}):dojo.marginBox(e)};var j=0;b._getUniqueId=function(){var a;do a=dojo._scopeName+"Unique"+ ++j;while(dojo.byId(a));return a}}(),dojo.mixin(dojox.gfx,{defaultPath:{type:"path",path:""},defaultPolyline:{type:"polyline",points:[]},defaultRect:{type:"rect",x:0,y:0,width:100,height:100,r:0},defaultEllipse:{type:"ellipse",cx:0,cy:0,rx:200,ry:100},defaultCircle:{type:"circle",cx:0,cy:0,r:100},defaultLine:{type:"line",
x1:0,y1:0,x2:100,y2:100},defaultImage:{type:"image",x:0,y:0,width:0,height:0,src:""},defaultText:{type:"text",x:0,y:0,text:"",align:"start",decoration:"none",rotated:!1,kerning:!0},defaultTextPath:{type:"textpath",text:"",align:"start",decoration:"none",rotated:!1,kerning:!0},defaultStroke:{type:"stroke",color:"black",style:"solid",width:1,cap:"butt",join:4},defaultLinearGradient:{type:"linear",x1:0,y1:0,x2:100,y2:100,colors:[{offset:0,color:"black"},{offset:1,color:"white"}]},defaultRadialGradient:{type:"radial",
cx:0,cy:0,r:100,colors:[{offset:0,color:"black"},{offset:1,color:"white"}]},defaultPattern:{type:"pattern",x:0,y:0,width:0,height:0,src:""},defaultFont:{type:"font",style:"normal",variant:"normal",weight:"normal",size:"10pt",family:"serif"},getDefault:function(){var a={};return function(b){var c=a[b];if(c)return new c;c=a[b]=new Function;c.prototype=dojox.gfx["default"+b];return new c}}(),normalizeColor:function(a){return a instanceof dojo.Color?a:new dojo.Color(a)},normalizeParameters:function(a,
b){if(b){var c={},d;for(d in a)d in b&&!(d in c)&&(a[d]=b[d])}return a},makeParameters:function(a,b){if(!b)return dojo.delegate(a);var c={},d;for(d in a)d in c||(c[d]=dojo.clone(d in b?b[d]:a[d]));return c},formatNumber:function(a,b){var c=a.toString();if(c.indexOf("e")>=0)c=a.toFixed(4);else{var d=c.indexOf(".");d>=0&&c.length-d>5&&(c=a.toFixed(4))}return a<0?c:b?" "+c:c},makeFontString:function(a){return a.style+" "+a.variant+" "+a.weight+" "+a.size+" "+a.family},splitFontString:function(a){var b=
dojox.gfx.getDefault("Font"),a=a.split(/\s+/);if(!(a.length<5)){b.style=a[0];b.variant=a[1];b.weight=a[2];var c=a[3].indexOf("/");b.size=c<0?a[3]:a[3].substring(0,c);var d=4;c<0&&(a[4]=="/"?d=6:a[4].charAt(0)=="/"&&(d=5));if(d<a.length)b.family=a.slice(d).join(" ")}return b},cm_in_pt:72/2.54,mm_in_pt:7.2/2.54,px_in_pt:function(){return dojox.gfx._base._getCachedFontMeasurements()["12pt"]/12},pt2px:function(a){return a*dojox.gfx.px_in_pt()},px2pt:function(a){return a/dojox.gfx.px_in_pt()},normalizedLength:function(a){if(a.length==
0)return 0;if(a.length>2){var b=dojox.gfx.px_in_pt(),c=parseFloat(a);switch(a.slice(-2)){case "px":return c;case "pt":return c*b;case "in":return c*72*b;case "pc":return c*12*b;case "mm":return c*dojox.gfx.mm_in_pt*b;case "cm":return c*dojox.gfx.cm_in_pt*b}}return parseFloat(a)},pathVmlRegExp:/([A-Za-z]+)|(\d+(\.\d+)?)|(\.\d+)|(-\d+(\.\d+)?)|(-\.\d+)/g,pathSvgRegExp:/([A-Za-z])|(\d+(\.\d+)?)|(\.\d+)|(-\d+(\.\d+)?)|(-\.\d+)/g,equalSources:function(a,b){return a&&b&&a==b},switchTo:function(a){var b=
dojox.gfx[a];b&&dojo.forEach(["Group","Rect","Ellipse","Circle","Line","Polyline","Image","Text","Path","TextPath","Surface","createSurface"],function(a){dojox.gfx[a]=b[a]})}}));