/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gfx.canvas"]||(dojo._hasResource["dojox.gfx.canvas"]=!0,dojo.provide("dojox.gfx.canvas"),dojo.require("dojox.gfx._base"),dojo.require("dojox.gfx.shape"),dojo.require("dojox.gfx.path"),dojo.require("dojox.gfx.arc"),dojo.require("dojox.gfx.decompose"),dojo.experimental("dojox.gfx.canvas"),function(){var h=dojo,f=dojox.gfx,g=f.shape,r=f.arc,e=f.canvas,m=f.matrix,j=m.multiplyPoint,n=Math.PI,u=2*n,q=n/2,k=null;h.declare("dojox.gfx.canvas.Shape",g.Shape,{_render:function(c){c.save();
this._renderTransform(c);this._renderShape(c);this._renderFill(c,!0);this._renderStroke(c,!0);c.restore()},_renderTransform:function(c){if("canvasTransform"in this){var a=this.canvasTransform;c.translate(a.dx,a.dy);c.rotate(a.angle2);c.scale(a.sx,a.sy);c.rotate(a.angle1)}},_renderShape:function(){},_renderFill:function(c,a){if("canvasFill"in this){var b=this.fillStyle;if("canvasFillImage"in this){var d=b.width,e=b.height,o=this.canvasFillImage.width,f=this.canvasFillImage.height,h=Math.min(d==o?1:
d/o,e==f?1:e/f),g=(d-h*o)/2,j=(e-h*f)/2;k.width=d;k.height=e;var i=k.getContext("2d");i.clearRect(0,0,d,e);i.drawImage(this.canvasFillImage,0,0,o,f,g,j,h*o,h*f);this.canvasFill=c.createPattern(k,"repeat");delete this.canvasFillImage}c.fillStyle=this.canvasFill;a&&(b.type==="pattern"&&(b.x!==0||b.y!==0)&&c.translate(b.x,b.y),c.fill())}else c.fillStyle="rgba(0,0,0,0.0)"},_renderStroke:function(c,a){var b=this.strokeStyle;if(b)c.strokeStyle=b.color.toString(),c.lineWidth=b.width,c.lineCap=b.cap,typeof b.join==
"number"?(c.lineJoin="miter",c.miterLimit=b.join):c.lineJoin=b.join,a&&c.stroke();else if(!a)c.strokeStyle="rgba(0,0,0,0.0)"},getEventSource:function(){return null},connect:function(){},disconnect:function(){}});var l=function(c,a,b){var d=c.prototype[a];c.prototype[a]=b?function(){this.surface.makeDirty();d.apply(this,arguments);b.call(this);return this}:function(){this.surface.makeDirty();return d.apply(this,arguments)}};l(e.Shape,"setTransform",function(){this.matrix?this.canvasTransform=f.decompose(this.matrix):
delete this.canvasTransform});l(e.Shape,"setFill",function(){var c=this.fillStyle,a;if(c){if(typeof c=="object"&&"type"in c){var b=this.surface.rawNode.getContext("2d");switch(c.type){case "linear":case "radial":a=c.type=="linear"?b.createLinearGradient(c.x1,c.y1,c.x2,c.y2):b.createRadialGradient(c.cx,c.cy,0,c.cx,c.cy,c.r);h.forEach(c.colors,function(b){a.addColorStop(b.offset,f.normalizeColor(b.color).toString())});break;case "pattern":k||(k=document.createElement("canvas")),b=new Image,this.surface.downloadImage(b,
c.src),this.canvasFillImage=b}}else a=c.toString();this.canvasFill=a}else delete this.canvasFill});l(e.Shape,"setStroke");l(e.Shape,"setShape");dojo.declare("dojox.gfx.canvas.Group",e.Shape,{constructor:function(){g.Container._init.call(this)},_render:function(c){c.save();this._renderTransform(c);for(var a=0;a<this.children.length;++a)this.children[a]._render(c);c.restore()}});dojo.declare("dojox.gfx.canvas.Rect",[e.Shape,g.Rect],{_renderShape:function(c){var a=this.shape,b=Math.min(a.r,a.height/
2,a.width/2),d=a.x,e=d+a.width,f=a.y,a=f+a.height,h=d+b,g=e-b,i=f+b,j=a-b;c.beginPath();c.moveTo(h,f);b?(c.arc(g,i,b,-q,0,!1),c.arc(g,j,b,0,q,!1),c.arc(h,j,b,q,n,!1),c.arc(h,i,b,n,n+q,!1)):(c.lineTo(g,f),c.lineTo(e,j),c.lineTo(h,a),c.lineTo(d,i));c.closePath()}});var i=[];(function(){var c=r.curvePI4;i.push(c.s,c.c1,c.c2,c.e);for(var a=45;a<360;a+=45){var b=m.rotateg(a);i.push(j(b,c.c1),j(b,c.c2),j(b,c.e))}})();dojo.declare("dojox.gfx.canvas.Ellipse",[e.Shape,g.Ellipse],{setShape:function(){this.inherited(arguments);
var c=this.shape,a,b,d=[],e=m.normalize([m.translate(c.cx,c.cy),m.scale(c.rx,c.ry)]),c=j(e,i[0]);d.push([c.x,c.y]);for(var f=1;f<i.length;f+=3)a=j(e,i[f]),b=j(e,i[f+1]),c=j(e,i[f+2]),d.push([a.x,a.y,b.x,b.y,c.x,c.y]);this.canvasEllipse=d;return this},_renderShape:function(c){var a=this.canvasEllipse;c.beginPath();c.moveTo.apply(c,a[0]);for(var b=1;b<a.length;++b)c.bezierCurveTo.apply(c,a[b]);c.closePath()}});dojo.declare("dojox.gfx.canvas.Circle",[e.Shape,g.Circle],{_renderShape:function(c){var a=
this.shape;c.beginPath();c.arc(a.cx,a.cy,a.r,0,u,1)}});dojo.declare("dojox.gfx.canvas.Line",[e.Shape,g.Line],{_renderShape:function(c){var a=this.shape;c.beginPath();c.moveTo(a.x1,a.y1);c.lineTo(a.x2,a.y2)}});dojo.declare("dojox.gfx.canvas.Polyline",[e.Shape,g.Polyline],{setShape:function(){this.inherited(arguments);var c=this.shape.points,a=c[0],b=[],d;if(c.length){typeof a=="number"?(b.push(a,c[1]),d=2):(b.push(a.x,a.y),d=1);for(;d<c.length;++d)a=c[d],typeof a=="number"?b.push(a,c[++d]):b.push(a.x,
a.y)}this.canvasPolyline=b;return this},_renderShape:function(c){var a=this.canvasPolyline;if(a.length){c.beginPath();c.moveTo(a[0],a[1]);for(var b=2;b<a.length;b+=2)c.lineTo(a[b],a[b+1])}}});dojo.declare("dojox.gfx.canvas.Image",[e.Shape,g.Image],{setShape:function(){this.inherited(arguments);var c=new Image;this.surface.downloadImage(c,this.shape.src);this.canvasImage=c;return this},_renderShape:function(c){var a=this.shape;c.drawImage(this.canvasImage,a.x,a.y,a.width,a.height)}});dojo.declare("dojox.gfx.canvas.Text",
[e.Shape,g.Text],{_setFont:function(){this.fontStyle?this.canvasFont=f.makeFontString(this.fontStyle):delete this.canvasFont},getTextWidth:function(){var c=this.shape,a=0,b;if(c.text&&c.text.length>0){b=this.surface.rawNode.getContext("2d");b.save();this._renderTransform(b);this._renderFill(b,!1);this._renderStroke(b,!1);if(this.canvasFont)b.font=this.canvasFont;a=b.measureText(c.text).width;b.restore()}return a},_render:function(c){c.save();this._renderTransform(c);this._renderFill(c,!1);this._renderStroke(c,
!1);this._renderShape(c);c.restore()},_renderShape:function(c){var a=this.shape;if(a.text&&a.text.length!=0){c.textAlign=a.align==="middle"?"center":a.align;if(this.canvasFont)c.font=this.canvasFont;this.canvasFill&&c.fillText(a.text,a.x,a.y);this.strokeStyle&&(c.beginPath(),c.strokeText(a.text,a.x,a.y),c.closePath())}}});l(e.Text,"setFont");typeof dojo.doc.createElement("canvas").getContext("2d").fillText!="function"&&e.Text.extend({getTextWidth:function(){return 0},_renderShape:function(){}});var v=
{M:"_moveToA",m:"_moveToR",L:"_lineToA",l:"_lineToR",H:"_hLineToA",h:"_hLineToR",V:"_vLineToA",v:"_vLineToR",C:"_curveToA",c:"_curveToR",S:"_smoothCurveToA",s:"_smoothCurveToR",Q:"_qCurveToA",q:"_qCurveToR",T:"_qSmoothCurveToA",t:"_qSmoothCurveToR",A:"_arcTo",a:"_arcTo",Z:"_closePath",z:"_closePath"};dojo.declare("dojox.gfx.canvas.Path",[e.Shape,f.path.Path],{constructor:function(){this.lastControl={}},setShape:function(){this.canvasPath=[];return this.inherited(arguments)},_updateWithSegment:function(c){var a=
h.clone(this.last);this[v[c.action]](this.canvasPath,c.action,c.args);this.last=a;this.inherited(arguments)},_renderShape:function(c){var a=this.canvasPath;c.beginPath();for(var b=0;b<a.length;b+=2)c[a[b]].apply(c,a[b+1])},_moveToA:function(c,a,b){c.push("moveTo",[b[0],b[1]]);for(a=2;a<b.length;a+=2)c.push("lineTo",[b[a],b[a+1]]);this.last.x=b[b.length-2];this.last.y=b[b.length-1];this.lastControl={}},_moveToR:function(c,a,b){"x"in this.last?c.push("moveTo",[this.last.x+=b[0],this.last.y+=b[1]]):
c.push("moveTo",[this.last.x=b[0],this.last.y=b[1]]);for(a=2;a<b.length;a+=2)c.push("lineTo",[this.last.x+=b[a],this.last.y+=b[a+1]]);this.lastControl={}},_lineToA:function(c,a,b){for(a=0;a<b.length;a+=2)c.push("lineTo",[b[a],b[a+1]]);this.last.x=b[b.length-2];this.last.y=b[b.length-1];this.lastControl={}},_lineToR:function(c,a,b){for(a=0;a<b.length;a+=2)c.push("lineTo",[this.last.x+=b[a],this.last.y+=b[a+1]]);this.lastControl={}},_hLineToA:function(c,a,b){for(a=0;a<b.length;++a)c.push("lineTo",[b[a],
this.last.y]);this.last.x=b[b.length-1];this.lastControl={}},_hLineToR:function(c,a,b){for(a=0;a<b.length;++a)c.push("lineTo",[this.last.x+=b[a],this.last.y]);this.lastControl={}},_vLineToA:function(c,a,b){for(a=0;a<b.length;++a)c.push("lineTo",[this.last.x,b[a]]);this.last.y=b[b.length-1];this.lastControl={}},_vLineToR:function(c,a,b){for(a=0;a<b.length;++a)c.push("lineTo",[this.last.x,this.last.y+=b[a]]);this.lastControl={}},_curveToA:function(c,a,b){for(a=0;a<b.length;a+=6)c.push("bezierCurveTo",
b.slice(a,a+6));this.last.x=b[b.length-2];this.last.y=b[b.length-1];this.lastControl.x=b[b.length-4];this.lastControl.y=b[b.length-3];this.lastControl.type="C"},_curveToR:function(c,a,b){for(a=0;a<b.length;a+=6)c.push("bezierCurveTo",[this.last.x+b[a],this.last.y+b[a+1],this.lastControl.x=this.last.x+b[a+2],this.lastControl.y=this.last.y+b[a+3],this.last.x+b[a+4],this.last.y+b[a+5]]),this.last.x+=b[a+4],this.last.y+=b[a+5];this.lastControl.type="C"},_smoothCurveToA:function(c,a,b){for(a=0;a<b.length;a+=
4){var d=this.lastControl.type=="C";c.push("bezierCurveTo",[d?2*this.last.x-this.lastControl.x:this.last.x,d?2*this.last.y-this.lastControl.y:this.last.y,b[a],b[a+1],b[a+2],b[a+3]]);this.lastControl.x=b[a];this.lastControl.y=b[a+1];this.lastControl.type="C"}this.last.x=b[b.length-2];this.last.y=b[b.length-1]},_smoothCurveToR:function(c,a,b){for(a=0;a<b.length;a+=4){var d=this.lastControl.type=="C";c.push("bezierCurveTo",[d?2*this.last.x-this.lastControl.x:this.last.x,d?2*this.last.y-this.lastControl.y:
this.last.y,this.last.x+b[a],this.last.y+b[a+1],this.last.x+b[a+2],this.last.y+b[a+3]]);this.lastControl.x=this.last.x+b[a];this.lastControl.y=this.last.y+b[a+1];this.lastControl.type="C";this.last.x+=b[a+2];this.last.y+=b[a+3]}},_qCurveToA:function(c,a,b){for(a=0;a<b.length;a+=4)c.push("quadraticCurveTo",b.slice(a,a+4));this.last.x=b[b.length-2];this.last.y=b[b.length-1];this.lastControl.x=b[b.length-4];this.lastControl.y=b[b.length-3];this.lastControl.type="Q"},_qCurveToR:function(c,a,b){for(a=
0;a<b.length;a+=4)c.push("quadraticCurveTo",[this.lastControl.x=this.last.x+b[a],this.lastControl.y=this.last.y+b[a+1],this.last.x+b[a+2],this.last.y+b[a+3]]),this.last.x+=b[a+2],this.last.y+=b[a+3];this.lastControl.type="Q"},_qSmoothCurveToA:function(c,a,b){for(a=0;a<b.length;a+=2){var d=this.lastControl.type=="Q";c.push("quadraticCurveTo",[this.lastControl.x=d?2*this.last.x-this.lastControl.x:this.last.x,this.lastControl.y=d?2*this.last.y-this.lastControl.y:this.last.y,b[a],b[a+1]]);this.lastControl.type=
"Q"}this.last.x=b[b.length-2];this.last.y=b[b.length-1]},_qSmoothCurveToR:function(c,a,b){for(a=0;a<b.length;a+=2){var d=this.lastControl.type=="Q";c.push("quadraticCurveTo",[this.lastControl.x=d?2*this.last.x-this.lastControl.x:this.last.x,this.lastControl.y=d?2*this.last.y-this.lastControl.y:this.last.y,this.last.x+b[a],this.last.y+b[a+1]]);this.lastControl.type="Q";this.last.x+=b[a];this.last.y+=b[a+1]}},_arcTo:function(c,a,b){for(var a=a=="a",d=0;d<b.length;d+=7){var e=b[d+5],f=b[d+6];a&&(e+=
this.last.x,f+=this.last.y);var g=r.arcAsBezier(this.last,b[d],b[d+1],b[d+2],b[d+3]?1:0,b[d+4]?1:0,e,f);h.forEach(g,function(a){c.push("bezierCurveTo",a)});this.last.x=e;this.last.y=f}this.lastControl={}},_closePath:function(c){c.push("closePath",[]);this.lastControl={}}});h.forEach(["moveTo","lineTo","hLineTo","vLineTo","curveTo","smoothCurveTo","qCurveTo","qSmoothCurveTo","arcTo","closePath"],function(c){l(e.Path,c)});dojo.declare("dojox.gfx.canvas.TextPath",[e.Shape,f.path.TextPath],{_renderShape:function(){},
_setText:function(){},_setFont:function(){}});dojo.declare("dojox.gfx.canvas.Surface",g.Surface,{constructor:function(){g.Container._init.call(this);this.pendingImageCount=0;this.makeDirty()},setDimensions:function(c,a){this.width=f.normalizedLength(c);this.height=f.normalizedLength(a);if(!this.rawNode)return this;this.rawNode.width=c;this.rawNode.height=a;this.makeDirty();return this},getDimensions:function(){return this.rawNode?{width:this.rawNode.width,height:this.rawNode.height}:null},_render:function(){if(!this.pendingImageCount){var c=
this.rawNode.getContext("2d");c.save();c.clearRect(0,0,this.rawNode.width,this.rawNode.height);for(var a=0;a<this.children.length;++a)this.children[a]._render(c);c.restore();"pendingRender"in this&&(clearTimeout(this.pendingRender),delete this.pendingRender)}},makeDirty:function(){if(!this.pendingImagesCount&&!("pendingRender"in this))this.pendingRender=setTimeout(h.hitch(this,this._render),0)},downloadImage:function(c,a){var b=h.hitch(this,this.onImageLoad);!this.pendingImageCount++&&"pendingRender"in
this&&(clearTimeout(this.pendingRender),delete this.pendingRender);c.onload=b;c.onerror=b;c.onabort=b;c.src=a},onImageLoad:function(){--this.pendingImageCount||this._render()},getEventSource:function(){return null},connect:function(){},disconnect:function(){}});e.createSurface=function(c,a,b){if(!a&&!b)var d=h.position(c),a=a||d.w,b=b||d.h;typeof a=="number"&&(a+="px");typeof b=="number"&&(b+="px");var d=new e.Surface,c=h.byId(c),g=c.ownerDocument.createElement("canvas");g.width=f.normalizedLength(a);
g.height=f.normalizedLength(b);c.appendChild(g);d.rawNode=g;d._parent=c;return d.surface=d};var p=g.Container,s={add:function(c){this.surface.makeDirty();return p.add.apply(this,arguments)},remove:function(c,a){this.surface.makeDirty();return p.remove.apply(this,arguments)},clear:function(){this.surface.makeDirty();return p.clear.apply(this,arguments)},_moveChildToFront:function(c){this.surface.makeDirty();return p._moveChildToFront.apply(this,arguments)},_moveChildToBack:function(c){this.surface.makeDirty();
return p._moveChildToBack.apply(this,arguments)}},t={createObject:function(c,a){var b=new c;b.surface=this.surface;b.setShape(a);this.add(b);return b}};h.extend(e.Group,s);h.extend(e.Group,g.Creator);h.extend(e.Group,t);h.extend(e.Surface,s);h.extend(e.Surface,g.Creator);h.extend(e.Surface,t);f.loadAndSwitch==="canvas"&&(f.switchTo("canvas"),delete f.loadAndSwitch)}());