/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gfx.fx"]||(dojo._hasResource["dojox.gfx.fx"]=!0,dojo.provide("dojox.gfx.fx"),dojo.require("dojox.gfx.matrix"),function(){function k(b,a){this.start=b;this.end=a}function m(b,a,d){this.start=b;this.end=a;this.units=d}function n(b,a){this.start=b;this.end=a;this.temp=new dojo.Color}function g(b){this.values=b;this.length=b.length}function l(b,a){this.values=b;this.def=a?a:{}}function o(b,a){this.stack=b;this.original=a}function p(b,a,d,f){if(b.values)return new g(b.values);
var e,q;q=b.start?h.normalizeColor(b.start):e=a?d?a[d]:a:f;b.end?b=h.normalizeColor(b.end):(e||(e=a?d?a[d]:a:f),b=e);return new n(q,b)}var c=dojo,h=dojox.gfx,j=h.matrix;k.prototype.getValue=function(b){return(this.end-this.start)*b+this.start};m.prototype.getValue=function(b){return(this.end-this.start)*b+this.start+this.units};n.prototype.getValue=function(b){return c.blendColors(this.start,this.end,b,this.temp)};g.prototype.getValue=function(b){return this.values[Math.min(Math.floor(b*this.length),
this.length-1)]};l.prototype.getValue=function(b){var a=dojo.clone(this.def),d;for(d in this.values)a[d]=this.values[d].getValue(b);return a};o.prototype.getValue=function(b){var a=[];dojo.forEach(this.stack,function(d){if(d instanceof j.Matrix2D)a.push(d);else if(d.name=="original"&&this.original)a.push(this.original);else if(d.name in j){var f=j[d.name];if(typeof f!="function")a.push(f);else{var e=dojo.map(d.start,function(e,a){return(d.end[a]-e)*b+e}),f=f.apply(j,e);f instanceof j.Matrix2D&&a.push(f)}}},
this);return a};var r=new c.Color(0,0,0,0);h.fx.animateStroke=function(b){if(!b.easing)b.easing=c._defaultEasing;var a=new c.Animation(b),d=b.shape,f;c.connect(a,"beforeBegin",a,function(){f=d.getStroke();var e=b.color,a={},c;if(e)a.color=p(e,f,"color",r);if((e=b.style)&&e.values)a.style=new g(e.values);if(e=b.width){var i=e;i.values?c=new g(i.values):(e=i.start?i.start:c=f?f.width:1,i.end?c=i.end:typeof c!="number"&&(c=f?f.width:1),c=new k(e,c));a.width=c}if((e=b.cap)&&e.values)a.cap=new g(e.values);
if(e=b.join)if(e.values)a.join=new g(e.values);else if(c=e.start?e.start:f&&f.join||0,e=e.end?e.end:f&&f.join||0,typeof c=="number"&&typeof e=="number")a.join=new k(c,e);this.curve=new l(a,f)});c.connect(a,"onAnimate",d,"setStroke");return a};h.fx.animateFill=function(b){if(!b.easing)b.easing=c._defaultEasing;var a=new c.Animation(b),d=b.shape,f;c.connect(a,"beforeBegin",a,function(){f=d.getFill();var a=b.color;if(a)this.curve=p(a,f,"",r)});c.connect(a,"onAnimate",d,"setFill");return a};h.fx.animateFont=
function(b){if(!b.easing)b.easing=c._defaultEasing;var a=new c.Animation(b),d=b.shape,f;c.connect(a,"beforeBegin",a,function(){f=d.getFont();var a=b.style,c={},h,i;if(a&&a.values)c.style=new g(a.values);if((a=b.variant)&&a.values)c.variant=new g(a.values);if((a=b.weight)&&a.values)c.weight=new g(a.values);if((a=b.family)&&a.values)c.family=new g(a.values);if((a=b.size)&&a.units)h=parseFloat(a.start?a.start:d.font&&d.font.size||"0"),i=parseFloat(a.end?a.end:d.font&&d.font.size||"0"),c.size=new m(h,
i,a.units);this.curve=new l(c,f)});c.connect(a,"onAnimate",d,"setFont");return a};h.fx.animateTransform=function(b){if(!b.easing)b.easing=c._defaultEasing;var a=new c.Animation(b),d=b.shape,f;c.connect(a,"beforeBegin",a,function(){f=d.getTransform();this.curve=new o(b.transform,f)});c.connect(a,"onAnimate",d,"setTransform");return a}}());