/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.gfx.matrix"])dojo._hasResource["dojox.gfx.matrix"]=!0,dojo.provide("dojox.gfx.matrix"),function(){var c=dojox.gfx.matrix,h={};c._degToRad=function(a){return h[a]||(h[a]=Math.PI*a/180)};c._radToDeg=function(a){return a/Math.PI*180};c.Matrix2D=function(a){if(a)if(typeof a=="number")this.xx=this.yy=a;else if(a instanceof Array){if(a.length>0){for(var b=c.normalize(a[0]),d=1;d<a.length;++d){var e=b,f=dojox.gfx.matrix.normalize(a[d]),b=new c.Matrix2D;b.xx=e.xx*f.xx+e.xy*f.yx;
b.xy=e.xx*f.xy+e.xy*f.yy;b.yx=e.yx*f.xx+e.yy*f.yx;b.yy=e.yx*f.xy+e.yy*f.yy;b.dx=e.xx*f.dx+e.xy*f.dy+e.dx;b.dy=e.yx*f.dx+e.yy*f.dy+e.dy}dojo.mixin(this,b)}}else dojo.mixin(this,a)};dojo.extend(c.Matrix2D,{xx:1,xy:0,yx:0,yy:1,dx:0,dy:0});dojo.mixin(c,{identity:new c.Matrix2D,flipX:new c.Matrix2D({xx:-1}),flipY:new c.Matrix2D({yy:-1}),flipXY:new c.Matrix2D({xx:-1,yy:-1}),translate:function(a,b){return arguments.length>1?new c.Matrix2D({dx:a,dy:b}):new c.Matrix2D({dx:a.x,dy:a.y})},scale:function(a,b){return arguments.length>
1?new c.Matrix2D({xx:a,yy:b}):typeof a=="number"?new c.Matrix2D({xx:a,yy:a}):new c.Matrix2D({xx:a.x,yy:a.y})},rotate:function(a){var b=Math.cos(a),a=Math.sin(a);return new c.Matrix2D({xx:b,xy:-a,yx:a,yy:b})},rotateg:function(a){return c.rotate(c._degToRad(a))},skewX:function(a){return new c.Matrix2D({xy:Math.tan(a)})},skewXg:function(a){return c.skewX(c._degToRad(a))},skewY:function(a){return new c.Matrix2D({yx:Math.tan(a)})},skewYg:function(a){return c.skewY(c._degToRad(a))},reflect:function(a,b){if(arguments.length==
1)b=a.y,a=a.x;var d=a*a,e=b*b,f=d+e,g=2*a*b/f;return new c.Matrix2D({xx:2*d/f-1,xy:g,yx:g,yy:2*e/f-1})},project:function(a,b){if(arguments.length==1)b=a.y,a=a.x;var d=a*a,e=b*b,f=d+e,g=a*b/f;return new c.Matrix2D({xx:d/f,xy:g,yx:g,yy:e/f})},normalize:function(a){return a instanceof c.Matrix2D?a:new c.Matrix2D(a)},clone:function(a){var b=new c.Matrix2D,d;for(d in a)typeof a[d]=="number"&&typeof b[d]=="number"&&b[d]!=a[d]&&(b[d]=a[d]);return b},invert:function(a){var a=c.normalize(a),b=a.xx*a.yy-a.xy*
a.yx;return a=new c.Matrix2D({xx:a.yy/b,xy:-a.xy/b,yx:-a.yx/b,yy:a.xx/b,dx:(a.xy*a.dy-a.yy*a.dx)/b,dy:(a.yx*a.dx-a.xx*a.dy)/b})},_multiplyPoint:function(a,b,c){return{x:a.xx*b+a.xy*c+a.dx,y:a.yx*b+a.yy*c+a.dy}},multiplyPoint:function(a,b,d){a=c.normalize(a);return typeof b=="number"&&typeof d=="number"?c._multiplyPoint(a,b,d):c._multiplyPoint(a,b.x,b.y)},multiply:function(a){for(var b=c.normalize(a),d=1;d<arguments.length;++d){var e=b,f=c.normalize(arguments[d]),b=new c.Matrix2D;b.xx=e.xx*f.xx+e.xy*
f.yx;b.xy=e.xx*f.xy+e.xy*f.yy;b.yx=e.yx*f.xx+e.yy*f.yx;b.yy=e.yx*f.xy+e.yy*f.yy;b.dx=e.xx*f.dx+e.xy*f.dy+e.dx;b.dy=e.yx*f.dx+e.yy*f.dy+e.dy}return b},_sandwich:function(a,b,d){return c.multiply(c.translate(b,d),a,c.translate(-b,-d))},scaleAt:function(a,b,d,e){switch(arguments.length){case 4:return c._sandwich(c.scale(a,b),d,e);case 3:return typeof d=="number"?c._sandwich(c.scale(a),b,d):c._sandwich(c.scale(a,b),d.x,d.y)}return c._sandwich(c.scale(a),b.x,b.y)},rotateAt:function(a,b,d){return arguments.length>
2?c._sandwich(c.rotate(a),b,d):c._sandwich(c.rotate(a),b.x,b.y)},rotategAt:function(a,b,d){return arguments.length>2?c._sandwich(c.rotateg(a),b,d):c._sandwich(c.rotateg(a),b.x,b.y)},skewXAt:function(a,b,d){return arguments.length>2?c._sandwich(c.skewX(a),b,d):c._sandwich(c.skewX(a),b.x,b.y)},skewXgAt:function(a,b,d){return arguments.length>2?c._sandwich(c.skewXg(a),b,d):c._sandwich(c.skewXg(a),b.x,b.y)},skewYAt:function(a,b,d){return arguments.length>2?c._sandwich(c.skewY(a),b,d):c._sandwich(c.skewY(a),
b.x,b.y)},skewYgAt:function(a,b,d){return arguments.length>2?c._sandwich(c.skewYg(a),b,d):c._sandwich(c.skewYg(a),b.x,b.y)}})}(),dojox.gfx.Matrix2D=dojox.gfx.matrix.Matrix2D;