/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.gfx.shape"])dojo._hasResource["dojox.gfx.shape"]=!0,dojo.provide("dojox.gfx.shape"),dojo.require("dojox.gfx._base"),dojo.declare("dojox.gfx.shape.Shape",null,{constructor:function(){this.parentMatrix=this.parent=this.bbox=this.strokeStyle=this.fillStyle=this.matrix=this.shape=this.rawNode=null},getNode:function(){return this.rawNode},getShape:function(){return this.shape},getTransform:function(){return this.matrix},getFill:function(){return this.fillStyle},getStroke:function(){return this.strokeStyle},
getParent:function(){return this.parent},getBoundingBox:function(){return this.bbox},getTransformedBoundingBox:function(){var a=this.getBoundingBox();if(!a)return null;var b=this._getRealMatrix();gm=dojox.gfx.matrix;return[gm.multiplyPoint(b,a.x,a.y),gm.multiplyPoint(b,a.x+a.width,a.y),gm.multiplyPoint(b,a.x+a.width,a.y+a.height),gm.multiplyPoint(b,a.x,a.y+a.height)]},getEventSource:function(){return this.rawNode},setShape:function(a){this.shape=dojox.gfx.makeParameters(this.shape,a);this.bbox=null;
return this},setFill:function(a){if(!a)return this.fillStyle=null,this;var b=null;if(typeof a=="object"&&"type"in a)switch(a.type){case "linear":b=dojox.gfx.makeParameters(dojox.gfx.defaultLinearGradient,a);break;case "radial":b=dojox.gfx.makeParameters(dojox.gfx.defaultRadialGradient,a);break;case "pattern":b=dojox.gfx.makeParameters(dojox.gfx.defaultPattern,a)}else b=dojox.gfx.normalizeColor(a);this.fillStyle=b;return this},setStroke:function(a){if(!a)return this.strokeStyle=null,this;if(typeof a==
"string"||dojo.isArray(a)||a instanceof dojo.Color)a={color:a};a=this.strokeStyle=dojox.gfx.makeParameters(dojox.gfx.defaultStroke,a);a.color=dojox.gfx.normalizeColor(a.color);return this},setTransform:function(a){this.matrix=dojox.gfx.matrix.clone(a?dojox.gfx.matrix.normalize(a):dojox.gfx.matrix.identity);return this._applyTransform()},_applyTransform:function(){return this},moveToFront:function(){var a=this.getParent();a&&(a._moveChildToFront(this),this._moveToFront());return this},moveToBack:function(){var a=
this.getParent();a&&(a._moveChildToBack(this),this._moveToBack());return this},_moveToFront:function(){},_moveToBack:function(){},applyRightTransform:function(a){return a?this.setTransform([this.matrix,a]):this},applyLeftTransform:function(a){return a?this.setTransform([a,this.matrix]):this},applyTransform:function(a){return a?this.setTransform([this.matrix,a]):this},removeShape:function(a){this.parent&&this.parent.remove(this,a);return this},_setParent:function(a,b){this.parent=a;return this._updateParentMatrix(b)},
_updateParentMatrix:function(a){this.parentMatrix=a?dojox.gfx.matrix.clone(a):null;return this._applyTransform()},_getRealMatrix:function(){for(var a=this.matrix,b=this.parent;b;)b.matrix&&(a=dojox.gfx.matrix.multiply(b.matrix,a)),b=b.parent;return a}}),dojox.gfx.shape._eventsProcessing={connect:function(a,b,c){return arguments.length>2?dojo.connect(this.getEventSource(),a,b,c):dojo.connect(this.getEventSource(),a,b)},disconnect:function(a){dojo.disconnect(a)}},dojo.extend(dojox.gfx.shape.Shape,dojox.gfx.shape._eventsProcessing),
dojox.gfx.shape.Container={_init:function(){this.children=[]},openBatch:function(){},closeBatch:function(){},add:function(a){var b=a.getParent();b&&b.remove(a,!0);this.children.push(a);return a._setParent(this,this._getRealMatrix())},remove:function(a,b){for(var c=0;c<this.children.length;++c)if(this.children[c]==a){if(!b)a.parent=null,a.parentMatrix=null;this.children.splice(c,1);break}return this},clear:function(){this.children=[];return this},_moveChildToFront:function(a){for(var b=0;b<this.children.length;++b)if(this.children[b]==
a){this.children.splice(b,1);this.children.push(a);break}return this},_moveChildToBack:function(a){for(var b=0;b<this.children.length;++b)if(this.children[b]==a){this.children.splice(b,1);this.children.unshift(a);break}return this}},dojo.declare("dojox.gfx.shape.Surface",null,{constructor:function(){this._parent=this.rawNode=null;this._nodes=[];this._events=[]},destroy:function(){dojo.forEach(this._nodes,dojo.destroy);this._nodes=[];dojo.forEach(this._events,dojo.disconnect);this._events=[];this.rawNode=
null;if(dojo.isIE)for(;this._parent.lastChild;)dojo.destroy(this._parent.lastChild);else this._parent.innerHTML="";this._parent=null},getEventSource:function(){return this.rawNode},_getRealMatrix:function(){return null},isLoaded:!0,onLoad:function(){},whenLoaded:function(a,b){var c=dojo.hitch(a,b);if(this.isLoaded)c(this);else var d=dojo.connect(this,"onLoad",function(a){dojo.disconnect(d);c(a)})}}),dojo.extend(dojox.gfx.shape.Surface,dojox.gfx.shape._eventsProcessing),dojo.declare("dojox.gfx.Point",
null,{}),dojo.declare("dojox.gfx.Rectangle",null,{}),dojo.declare("dojox.gfx.shape.Rect",dojox.gfx.shape.Shape,{constructor:function(a){this.shape=dojox.gfx.getDefault("Rect");this.rawNode=a},getBoundingBox:function(){return this.shape}}),dojo.declare("dojox.gfx.shape.Ellipse",dojox.gfx.shape.Shape,{constructor:function(a){this.shape=dojox.gfx.getDefault("Ellipse");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.rx,y:a.cy-a.ry,width:2*a.rx,height:2*a.ry}}return this.bbox}}),
dojo.declare("dojox.gfx.shape.Circle",dojox.gfx.shape.Shape,{constructor:function(a){this.shape=dojox.gfx.getDefault("Circle");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r}}return this.bbox}}),dojo.declare("dojox.gfx.shape.Line",dojox.gfx.shape.Shape,{constructor:function(a){this.shape=dojox.gfx.getDefault("Line");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:Math.min(a.x1,
a.x2),y:Math.min(a.y1,a.y2),width:Math.abs(a.x2-a.x1),height:Math.abs(a.y2-a.y1)}}return this.bbox}}),dojo.declare("dojox.gfx.shape.Polyline",dojox.gfx.shape.Shape,{constructor:function(a){this.shape=dojox.gfx.getDefault("Polyline");this.rawNode=a},setShape:function(a,b){a&&a instanceof Array?(this.inherited(arguments,[{points:a}]),b&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):this.inherited(arguments,[a]);return this},_normalizePoints:function(){var a=this.shape.points,
b=a&&a.length;if(b&&typeof a[0]=="number"){for(var c=[],d=0;d<b;d+=2)c.push({x:a[d],y:a[d+1]});this.shape.points=c}},getBoundingBox:function(){if(!this.bbox&&this.shape.points.length){for(var a=this.shape.points,b=a.length,c=a[0],d={l:c.x,t:c.y,r:c.x,b:c.y},e=1;e<b;++e){c=a[e];if(d.l>c.x)d.l=c.x;if(d.r<c.x)d.r=c.x;if(d.t>c.y)d.t=c.y;if(d.b<c.y)d.b=c.y}this.bbox={x:d.l,y:d.t,width:d.r-d.l,height:d.b-d.t}}return this.bbox}}),dojo.declare("dojox.gfx.shape.Image",dojox.gfx.shape.Shape,{constructor:function(a){this.shape=
dojox.gfx.getDefault("Image");this.rawNode=a},getBoundingBox:function(){return this.shape},setStroke:function(){return this},setFill:function(){return this}}),dojo.declare("dojox.gfx.shape.Text",dojox.gfx.shape.Shape,{constructor:function(a){this.fontStyle=null;this.shape=dojox.gfx.getDefault("Text");this.rawNode=a},getFont:function(){return this.fontStyle},setFont:function(a){this.fontStyle=typeof a=="string"?dojox.gfx.splitFontString(a):dojox.gfx.makeParameters(dojox.gfx.defaultFont,a);this._setFont();
return this}}),dojox.gfx.shape.Creator={createShape:function(a){var b=dojox.gfx;switch(a.type){case b.defaultPath.type:return this.createPath(a);case b.defaultRect.type:return this.createRect(a);case b.defaultCircle.type:return this.createCircle(a);case b.defaultEllipse.type:return this.createEllipse(a);case b.defaultLine.type:return this.createLine(a);case b.defaultPolyline.type:return this.createPolyline(a);case b.defaultImage.type:return this.createImage(a);case b.defaultText.type:return this.createText(a);
case b.defaultTextPath.type:return this.createTextPath(a)}return null},createGroup:function(){return this.createObject(dojox.gfx.Group)},createRect:function(a){return this.createObject(dojox.gfx.Rect,a)},createEllipse:function(a){return this.createObject(dojox.gfx.Ellipse,a)},createCircle:function(a){return this.createObject(dojox.gfx.Circle,a)},createLine:function(a){return this.createObject(dojox.gfx.Line,a)},createPolyline:function(a){return this.createObject(dojox.gfx.Polyline,a)},createImage:function(a){return this.createObject(dojox.gfx.Image,
a)},createText:function(a){return this.createObject(dojox.gfx.Text,a)},createPath:function(a){return this.createObject(dojox.gfx.Path,a)},createTextPath:function(a){return this.createObject(dojox.gfx.TextPath,{}).setText(a)},createObject:function(){return null}};