/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gfx.silverlight"]||(dojo._hasResource["dojox.gfx.silverlight"]=!0,dojo.provide("dojox.gfx.silverlight"),dojo.require("dojox.gfx._base"),dojo.require("dojox.gfx.shape"),dojo.require("dojox.gfx.path"),dojo.experimental("dojox.gfx.silverlight"),function(){function o(a){var b=d.normalizeColor(a),a=b.toHex(),b=Math.round(b.a*255),b=(b<0?0:b>255?255:b).toString(16);return"#"+(b.length<2?"0"+b:b)+a.slice(1)}function j(a,b){var c={target:a,currentTarget:a,preventDefault:function(){},
stopPropagation:function(){}};try{if(b.source)c.target=b.source}catch(d){}if(b)try{c.ctrlKey=b.ctrl;c.shiftKey=b.shift;var e=b.getPosition(null);c.x=c.offsetX=c.layerX=e.x;c.y=c.offsetY=c.layerY=e.y;var g=n[a.getHost().content.root.name],k=f.position(g);c.clientX=k.x+e.x;c.clientY=k.y+e.y}catch(i){}return c}function p(a,b){var c={keyCode:b.platformKeyCode,ctrlKey:b.ctrl,shiftKey:b.shift};try{if(b.source)c.target=b.source}catch(d){}return c}var f=dojo,d=dojox.gfx,i=d.shape,g=d.silverlight,q={solid:"none",
shortdash:[4,1],shortdot:[1,1],shortdashdot:[4,1,1,1],shortdashdotdot:[4,1,1,1,1,1],dot:[1,3],dash:[4,3],longdash:[8,3],dashdot:[4,3,1,3],longdashdot:[8,3,1,3],longdashdotdot:[8,3,1,3,1,3]},r={normal:400,bold:700},v={butt:"Flat",round:"Round",square:"Square"},w={bevel:"Bevel",round:"Round"},s={serif:"Times New Roman",times:"Times New Roman","sans-serif":"Arial",helvetica:"Arial",monotone:"Courier New",courier:"Courier New"};f.declare("dojox.gfx.silverlight.Shape",i.Shape,{setFill:function(a){var b=
this.rawNode.getHost().content;if(!a)return this.fillStyle=null,this._setFillAttr(null),this;if(typeof a=="object"&&"type"in a){switch(a.type){case "linear":this.fillStyle=a=d.makeParameters(d.defaultLinearGradient,a);var c=b.createFromXaml("<LinearGradientBrush/>");c.mappingMode="Absolute";c.startPoint=a.x1+","+a.y1;c.endPoint=a.x2+","+a.y2;f.forEach(a.colors,function(a){var e=b.createFromXaml("<GradientStop/>");e.offset=a.offset;e.color=o(a.color);c.gradientStops.add(e)});this._setFillAttr(c);break;
case "radial":this.fillStyle=a=d.makeParameters(d.defaultRadialGradient,a);var h=b.createFromXaml("<RadialGradientBrush/>"),e=d.matrix.multiplyPoint(d.matrix.invert(this._getAdjustedMatrix()),a.cx,a.cy),e=e.x+","+e.y;h.mappingMode="Absolute";h.gradientOrigin=e;h.center=e;h.radiusX=h.radiusY=a.r;f.forEach(a.colors,function(a){var c=b.createFromXaml("<GradientStop/>");c.offset=a.offset;c.color=o(a.color);h.gradientStops.add(c)});this._setFillAttr(h);break;case "pattern":this.fillStyle=null,this._setFillAttr(null)}return this}this.fillStyle=
a=d.normalizeColor(a);e=b.createFromXaml("<SolidColorBrush/>");e.color=a.toHex();e.opacity=a.a;this._setFillAttr(e);return this},_setFillAttr:function(a){this.rawNode.fill=a},setStroke:function(a){var b=this.rawNode.getHost().content,c=this.rawNode;if(!a)return this.strokeStyle=null,c.stroke=null,this;if(typeof a=="string"||f.isArray(a)||a instanceof f.Color)a={color:a};a=this.strokeStyle=d.makeParameters(d.defaultStroke,a);a.color=d.normalizeColor(a.color);if(a)if(b=b.createFromXaml("<SolidColorBrush/>"),
b.color=a.color.toHex(),b.opacity=a.color.a,c.stroke=b,c.strokeThickness=a.width,c.strokeStartLineCap=c.strokeEndLineCap=c.strokeDashCap=v[a.cap],typeof a.join=="number"?(c.strokeLineJoin="Miter",c.strokeMiterLimit=a.join):c.strokeLineJoin=w[a.join],b=a.style.toLowerCase(),b in q&&(b=q[b]),b instanceof Array){b=f.clone(b);if(a.cap!="butt"){for(a=0;a<b.length;a+=2)--b[a],b[a]<1&&(b[a]=1);for(a=1;a<b.length;a+=2)++b[a]}c.strokeDashArray=b.join(",")}else c.strokeDashArray=null;return this},_getParentSurface:function(){for(var a=
this.parent;a&&!(a instanceof d.Surface);a=a.parent);return a},_applyTransform:function(){var a=this._getAdjustedMatrix(),b=this.rawNode;if(a){var c=this.rawNode.getHost().content,d=c.createFromXaml("<MatrixTransform/>"),c=c.createFromXaml("<Matrix/>");c.m11=a.xx;c.m21=a.xy;c.m12=a.yx;c.m22=a.yy;c.offsetX=a.dx;c.offsetY=a.dy;d.matrix=c;b.renderTransform=d}else b.renderTransform=null;return this},setRawNode:function(a){a.fill=null;a.stroke=null;this.rawNode=a},_moveToFront:function(){var a=this.parent.rawNode.children,
b=this.rawNode;a.remove(b);a.add(b);return this},_moveToBack:function(){var a=this.parent.rawNode.children,b=this.rawNode;a.remove(b);a.insert(0,b);return this},_getAdjustedMatrix:function(){return this.matrix}});f.declare("dojox.gfx.silverlight.Group",g.Shape,{constructor:function(){i.Container._init.call(this)},setRawNode:function(a){this.rawNode=a}});g.Group.nodeType="Canvas";f.declare("dojox.gfx.silverlight.Rect",[g.Shape,i.Rect],{setShape:function(a){this.shape=d.makeParameters(this.shape,a);
this.bbox=null;var a=this.rawNode,b=this.shape;a.width=b.width;a.height=b.height;a.radiusX=a.radiusY=b.r;return this._applyTransform()},_getAdjustedMatrix:function(){var a=this.matrix,b=this.shape,b={dx:b.x,dy:b.y};return new d.Matrix2D(a?[a,b]:b)}});g.Rect.nodeType="Rectangle";f.declare("dojox.gfx.silverlight.Ellipse",[g.Shape,i.Ellipse],{setShape:function(a){this.shape=d.makeParameters(this.shape,a);this.bbox=null;var a=this.rawNode,b=this.shape;a.width=2*b.rx;a.height=2*b.ry;return this._applyTransform()},
_getAdjustedMatrix:function(){var a=this.matrix,b=this.shape,b={dx:b.cx-b.rx,dy:b.cy-b.ry};return new d.Matrix2D(a?[a,b]:b)}});g.Ellipse.nodeType="Ellipse";f.declare("dojox.gfx.silverlight.Circle",[g.Shape,i.Circle],{setShape:function(a){this.shape=d.makeParameters(this.shape,a);this.bbox=null;a=this.rawNode;a.width=a.height=2*this.shape.r;return this._applyTransform()},_getAdjustedMatrix:function(){var a=this.matrix,b=this.shape,b={dx:b.cx-b.r,dy:b.cy-b.r};return new d.Matrix2D(a?[a,b]:b)}});g.Circle.nodeType=
"Ellipse";f.declare("dojox.gfx.silverlight.Line",[g.Shape,i.Line],{setShape:function(a){this.shape=d.makeParameters(this.shape,a);this.bbox=null;var a=this.rawNode,b=this.shape;a.x1=b.x1;a.y1=b.y1;a.x2=b.x2;a.y2=b.y2;return this}});g.Line.nodeType="Line";f.declare("dojox.gfx.silverlight.Polyline",[g.Shape,i.Polyline],{setShape:function(a,b){a&&a instanceof Array?(this.shape=d.makeParameters(this.shape,{points:a}),b&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):this.shape=
d.makeParameters(this.shape,a);this.bbox=null;this._normalizePoints();for(var c=this.shape.points,h=[],e=0;e<c.length;++e)h.push(c[e].x,c[e].y);this.rawNode.points=h.join(",");return this}});g.Polyline.nodeType="Polyline";f.declare("dojox.gfx.silverlight.Image",[g.Shape,i.Image],{setShape:function(a){this.shape=d.makeParameters(this.shape,a);this.bbox=null;var a=this.rawNode,b=this.shape;a.width=b.width;a.height=b.height;a.source=b.src;return this._applyTransform()},_getAdjustedMatrix:function(){var a=
this.matrix,b=this.shape,b={dx:b.x,dy:b.y};return new d.Matrix2D(a?[a,b]:b)},setRawNode:function(a){this.rawNode=a}});g.Image.nodeType="Image";f.declare("dojox.gfx.silverlight.Text",[g.Shape,i.Text],{setShape:function(a){this.shape=d.makeParameters(this.shape,a);this.bbox=null;var a=this.rawNode,b=this.shape;a.text=b.text;a.textDecorations=b.decoration==="underline"?"Underline":"None";a["Canvas.Left"]=-1E4;a["Canvas.Top"]=-1E4;if(!this._delay)this._delay=window.setTimeout(f.hitch(this,"_delayAlignment"),
10);return this},_delayAlignment:function(){var a=this.rawNode,b=this.shape,c,d;try{c=a.actualWidth,d=a.actualHeight}catch(e){return}var f=b.x;d=b.y-d*0.75;switch(b.align){case "middle":f-=c/2;break;case "end":f-=c}this._delta={dx:f,dy:d};a["Canvas.Left"]=0;a["Canvas.Top"]=0;this._applyTransform();delete this._delay},_getAdjustedMatrix:function(){var a=this.matrix,b=this._delta;return new d.Matrix2D(a?b?[a,b]:a:b?b:{})},setStroke:function(){return this},_setFillAttr:function(a){this.rawNode.foreground=
a},setRawNode:function(a){this.rawNode=a},getTextWidth:function(){return this.rawNode.actualWidth}});g.Text.nodeType="TextBlock";f.declare("dojox.gfx.silverlight.Path",[g.Shape,d.path.Path],{_updateWithSegment:function(a){this.inherited(arguments);var b=this.shape.path;if(typeof b=="string")this.rawNode.data=b?b:null},setShape:function(a){this.inherited(arguments);var b=this.shape.path;this.rawNode.data=b?b:null;return this}});g.Path.nodeType="Path";f.declare("dojox.gfx.silverlight.TextPath",[g.Shape,
d.path.TextPath],{_updateWithSegment:function(){},setShape:function(){},_setText:function(){}});g.TextPath.nodeType="text";var n={},x=new Function;f.declare("dojox.gfx.silverlight.Surface",i.Surface,{constructor:function(){i.Container._init.call(this)},destroy:function(){window[this._onLoadName]=x;delete n[this._nodeName];this.inherited(arguments)},setDimensions:function(a,b){this.width=d.normalizedLength(a);this.height=d.normalizedLength(b);var c=this.rawNode&&this.rawNode.getHost();if(c)c.width=
a,c.height=b;return this},getDimensions:function(){var a=this.rawNode&&this.rawNode.getHost(),a=a?{width:a.content.actualWidth,height:a.content.actualHeight}:null;if(a.width<=0)a.width=this.width;if(a.height<=0)a.height=this.height;return a}});g.createSurface=function(a,b,c){if(!b&&!c)var h=f.position(a),b=b||h.w,c=c||h.h;typeof b=="number"&&(b+="px");typeof c=="number"&&(c+="px");var e=new g.Surface,a=f.byId(a);e._parent=a;e._nodeName=d._base._getUniqueId();h=a.ownerDocument.createElement("script");
h.type="text/xaml";h.id=d._base._getUniqueId();h.text="<?xml version='1.0'?><Canvas xmlns='http://schemas.microsoft.com/client/2007' Name='"+e._nodeName+"'/>";a.parentNode.insertBefore(h,a);e._nodes.push(h);var i=d._base._getUniqueId(),k="__"+d._base._getUniqueId()+"_onLoad";e._onLoadName=k;window[k]=function(){if(!e.rawNode)e.rawNode=f.byId(i).content.root,n[e._nodeName]=a,e.onLoad(e)};a.innerHTML=f.isSafari?"<embed type='application/x-silverlight' id='"+i+"' width='"+b+"' height='"+c+" background='transparent' source='#"+
h.id+"' windowless='true' maxFramerate='60' onLoad='"+k+"' onError='__dojoSilverlightError' /><iframe style='visibility:hidden;height:0;width:0'/>":"<object type='application/x-silverlight' data='data:application/x-silverlight,' id='"+i+"' width='"+b+"' height='"+c+"'><param name='background' value='transparent' /><param name='source' value='#"+h.id+"' /><param name='windowless' value='true' /><param name='maxFramerate' value='60' /><param name='onLoad' value='"+k+"' /><param name='onError' value='__dojoSilverlightError' /></object>";
h=f.byId(i);h.content&&h.content.root?(e.rawNode=h.content.root,n[e._nodeName]=a):(e.rawNode=null,e.isLoaded=!1);e._nodes.push(h);e.width=d.normalizedLength(b);e.height=d.normalizedLength(c);return e};__dojoSilverlightError=function(){};var l=i.Container,m={add:function(a){this!=a.getParent()&&(l.add.apply(this,arguments),this.rawNode.children.add(a.rawNode));return this},remove:function(a,b){if(this==a.getParent()){var c=a.rawNode.getParent();c&&c.children.remove(a.rawNode);l.remove.apply(this,arguments)}return this},
clear:function(){this.rawNode.children.clear();return l.clear.apply(this,arguments)},_moveChildToFront:l._moveChildToFront,_moveChildToBack:l._moveChildToBack},t={createObject:function(a,b){if(!this.rawNode)return null;var c=new a,d=this.rawNode.getHost().content.createFromXaml("<"+a.nodeType+"/>");c.setRawNode(d);c.setShape(b);this.add(c);return c}};f.extend(g.Text,{_setFont:function(){var a=this.fontStyle,b=this.rawNode,c=a.family.toLowerCase();b.fontStyle=a.style=="italic"?"Italic":"Normal";b.fontWeight=
a.weight in r?r[a.weight]:a.weight;b.fontSize=d.normalizedLength(a.size);b.fontFamily=c in s?s[c]:a.family;if(!this._delay)this._delay=window.setTimeout(f.hitch(this,"_delayAlignment"),10)}});f.extend(g.Group,m);f.extend(g.Group,i.Creator);f.extend(g.Group,t);f.extend(g.Surface,m);f.extend(g.Surface,i.Creator);f.extend(g.Surface,t);var u={onclick:{name:"MouseLeftButtonUp",fix:j},onmouseenter:{name:"MouseEnter",fix:j},onmouseleave:{name:"MouseLeave",fix:j},onmouseover:{name:"MouseEnter",fix:j},onmouseout:{name:"MouseLeave",
fix:j},onmousedown:{name:"MouseLeftButtonDown",fix:j},onmouseup:{name:"MouseLeftButtonUp",fix:j},onmousemove:{name:"MouseMove",fix:j},onkeydown:{name:"KeyDown",fix:p},onkeyup:{name:"KeyUp",fix:p}},m={connect:function(a,b,c){var d,e=a in u?u[a]:{name:a,fix:function(){return{}}};d=arguments.length>2?this.getEventSource().addEventListener(e.name,function(a,d){f.hitch(b,c)(e.fix(a,d))}):this.getEventSource().addEventListener(e.name,function(a,c){b(e.fix(a,c))});return{name:e.name,token:d}},disconnect:function(a){try{this.getEventSource().removeEventListener(a.name,
a.token)}catch(b){}}};f.extend(g.Shape,m);f.extend(g.Surface,m);d.equalSources=function(a,b){return a&&b&&a.equals(b)};d.loadAndSwitch==="silverlight"&&(d.switchTo("silverlight"),delete d.loadAndSwitch)}());