/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.gfx.utils"]||(dojo._hasResource["dojox.gfx.utils"]=!0,dojo.provide("dojox.gfx.utils"),dojo.require("dojox.gfx"),function(){var e=dojo,f=dojox.gfx,d=f.utils;dojo.mixin(d,{forEach:function(a,b,c){c=c||e.global;b.call(c,a);(a instanceof f.Surface||a instanceof f.Group)&&e.forEach(a.children,function(a){d.forEach(a,b,c)})},serialize:function(a){var b={},c;if((c=a instanceof f.Surface)||a instanceof f.Group){if(b.children=e.map(a.children,d.serialize),c)return b.children}else b.shape=
a.getShape();if(a.getTransform&&(c=a.getTransform()))b.transform=c;if(a.getStroke&&(c=a.getStroke()))b.stroke=c;if(a.getFill&&(c=a.getFill()))b.fill=c;if(a.getFont&&(c=a.getFont()))b.font=c;return b},toJson:function(a,b){return e.toJson(d.serialize(a),b)},deserialize:function(a,b){if(b instanceof Array)return e.map(b,e.hitch(null,d.deserialize,a));var c="shape"in b?a.createShape(b.shape):a.createGroup();"transform"in b&&c.setTransform(b.transform);"stroke"in b&&c.setStroke(b.stroke);"fill"in b&&c.setFill(b.fill);
"font"in b&&c.setFont(b.font);"children"in b&&e.forEach(b.children,e.hitch(null,d.deserialize,c));return c},fromJson:function(a,b){return d.deserialize(a,e.fromJson(b))},toSvg:function(a){var b=new dojo.Deferred;if(dojox.gfx.renderer==="svg")try{var c=d._cleanSvg(d._innerXML(a.rawNode));b.callback(c)}catch(e){b.errback(e)}else{d._initSvgSerializerDeferred||d._initSvgSerializer();var f=dojox.gfx.utils.toJson(a),c=function(){try{var c=a.getDimensions(),e=c.width,h=c.height,g=d._gfxSvgProxy.document.createElement("div");
d._gfxSvgProxy.document.body.appendChild(g);dojo.withDoc(d._gfxSvgProxy.document,function(){dojo.style(g,"width",e);dojo.style(g,"height",h)},this);d._gfxSvgProxy[dojox._scopeName].gfx.createSurface(g,e,h).whenLoaded(null,function(a){try{d._gfxSvgProxy[dojox._scopeName].gfx.utils.fromJson(a,f);var c=d._cleanSvg(g.innerHTML);a.clear();a.destroy();d._gfxSvgProxy.document.body.removeChild(g);b.callback(c)}catch(e){b.errback(e)}})}catch(i){b.errback(i)}};d._initSvgSerializerDeferred.fired>0?c():d._initSvgSerializerDeferred.addCallback(c)}return b},
_gfxSvgProxy:null,_initSvgSerializerDeferred:null,_svgSerializerInitialized:function(){d._initSvgSerializerDeferred.callback(!0)},_initSvgSerializer:function(){if(!d._initSvgSerializerDeferred){d._initSvgSerializerDeferred=new dojo.Deferred;var a=dojo.doc.createElement("iframe");dojo.style(a,{display:"none",position:"absolute",width:"1em",height:"1em",top:"-10000px"});var b;dojo.isIE?a.onreadystatechange=function(){if(a.contentWindow.document.readyState=="complete")a.onreadystatechange=function(){},
b=setInterval(function(){if(a.contentWindow[dojo._scopeName]&&a.contentWindow[dojox._scopeName].gfx&&a.contentWindow[dojox._scopeName].gfx.utils)clearInterval(b),a.contentWindow.parent[dojox._scopeName].gfx.utils._gfxSvgProxy=a.contentWindow,a.contentWindow.parent[dojox._scopeName].gfx.utils._svgSerializerInitialized()},50)}:a.onload=function(){a.onload=function(){};b=setInterval(function(){if(a.contentWindow[dojo._scopeName]&&a.contentWindow[dojox._scopeName].gfx&&a.contentWindow[dojox._scopeName].gfx.utils)clearInterval(b),
a.contentWindow.parent[dojox._scopeName].gfx.utils._gfxSvgProxy=a.contentWindow,a.contentWindow.parent[dojox._scopeName].gfx.utils._svgSerializerInitialized()},50)};var c=dojo.config.dojoxGfxSvgProxyFrameUrl||dojo.moduleUrl("dojox","gfx/resources/gfxSvgProxyFrame.html");a.setAttribute("src",c);dojo.body().appendChild(a)}},_innerXML:function(a){if(a.innerXML)return a.innerXML;else if(a.xml)return a.xml;else if(typeof XMLSerializer!="undefined")return(new XMLSerializer).serializeToString(a);return null},
_cleanSvg:function(a){a&&(a.indexOf('xmlns="http://www.w3.org/2000/svg"')==-1&&(a=a.substring(4,a.length),a='<svg xmlns="http://www.w3.org/2000/svg"'+a),a=a.replace(/\bdojoGfx\w*\s*=\s*(['"])\w*\1/g,""));return a}})}());