/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.xml.DomParser"])dojo._hasResource["dojox.xml.DomParser"]=!0,dojo.provide("dojox.xml.DomParser"),dojox.xml.DomParser=new function(){function A(){return new function(){var a={};this.nodeType=j.DOCUMENT;this.nodeName="#document";this.namespaces={};this._nsPaths={};this.childNodes=[];this.documentElement=null;this._add=function(b){typeof b.id!="undefined"&&(a[b.id]=b)};this._remove=function(b){a[b]&&delete a[b]};this.byId=this.getElementById=function(b){return a[b]};this.byName=
this.getElementsByTagName=p;this.byNameNS=this.getElementsByTagNameNS=q;this.childrenByName=r;this.childrenByNameNS=s}}function p(a){function b(a,e,c){dojo.forEach(a.childNodes,function(a){a.nodeType==j.ELEMENT&&(e=="*"?c.push(a):a.nodeName==e&&c.push(a),b(a,e,c))})}var c=[];b(this,a,c);return c}function q(a,b){function c(a,b,d,i){dojo.forEach(a.childNodes,function(a){a.nodeType==j.ELEMENT&&(b=="*"&&a.ownerDocument._nsPaths[d]==a.namespace?i.push(a):a.localName==b&&a.ownerDocument._nsPaths[d]==a.namespace&&
i.push(a),c(a,b,d,i))})}b||(b=l);var d=[];c(this,a,b,d);return d}function r(a){var b=[];dojo.forEach(this.childNodes,function(c){c.nodeType==j.ELEMENT&&(a=="*"?b.push(c):c.nodeName==a&&b.push(c))});return b}function s(a,b){var c=[];dojo.forEach(this.childNodes,function(d){d.nodeType==j.ELEMENT&&(a=="*"&&d.ownerDocument._nsPaths[b]==d.namespace?c.push(d):d.localName==a&&d.ownerDocument._nsPaths[b]==d.namespace&&c.push(d))});return c}function t(a){return{nodeType:j.TEXT,nodeName:"#text",nodeValue:a.replace(u,
" ").replace(v,">").replace(w,"<").replace(x,"'").replace(y,'"').replace(z,"&")}}function B(a){for(var b=0;b<this.attributes.length;b++)if(this.attributes[b].nodeName==a)return this.attributes[b].nodeValue;return null}function C(a,b){for(var c=0;c<this.attributes.length;c++)if(this.ownerDocument._nsPaths[b]==this.attributes[c].namespace&&this.attributes[c].localName==a)return this.attributes[c].nodeValue;return null}function D(a,b){for(var c=null,d=0;d<this.attributes.length;d++)if(this.attributes[d].nodeName==
a){c=this.attributes[d].nodeValue;this.attributes[d].nodeValue=b;break}a=="id"&&(c!=null&&this.ownerDocument._remove(c),this.ownerDocument._add(this))}function E(a,b,c){for(var d=0;d<this.attributes.length;d++)if(this.ownerDocument._nsPaths[c]==this.attributes[d].namespace&&this.attributes[d].localName==a){this.attributes[d].nodeValue=b;break}}function F(){var a=this.parentNode;if(a)for(var b=0;b<a.childNodes.length;b++)if(a.childNodes[b]==this&&b>0)return a.childNodes[b-1];return null}function G(){var a=
this.parentNode;if(a)for(var b=0;b<a.childNodes.length;b++)if(a.childNodes[b]==this&&b+1<a.childNodes.length)return a.childNodes[b+1];return null}var j={ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9},H=/<([^>\/\s+]*)([^>]*)>([^<]*)/g,I=/([^=]*)=(("([^"]*)")|('([^']*)'))/g,n=/<!ENTITY\s+([^"]*)\s+"([^"]*)">/g,J=/<!\[CDATA\[([\u0001-\uFFFF]*?)\]\]>/g,K=/<\!--([\u0001-\uFFFF]*?)--\>/g,m=/^\s+|\s+$/g,u=/\s+/g,v=/\&gt;/g,w=/\&lt;/g,y=/\&quot;/g,x=/\&apos;/g,
z=/\&amp;/g,l="_def_";this.parse=function(a){var b=A();if(a==null)return b;if(a.length==0)return b;if(a.indexOf("<!ENTITY")>0){var c,d=[];if(n.test(a)){for(n.lastIndex=0;(c=n.exec(a))!=null;)d.push({entity:"&"+c[1].replace(m,"")+";",expression:c[2]});for(var e=0;e<d.length;e++)a=a.replace(RegExp(d[e].entity,"g"),d[e].expression)}}for(d=[];(c=J.exec(a))!=null;)d.push(c[1]);for(e=0;e<d.length;e++)a=a.replace(d[e],e);for(c=[];(e=K.exec(a))!=null;)c.push(e[1]);for(e=0;e<c.length;e++)a=a.replace(c[e],
e);for(var g,e=b;(g=H.exec(a))!=null;)if(g[2].charAt(0)=="/"&&g[2].replace(m,"").length>1){if(e.parentNode)e=e.parentNode;var h=(g[3]||"").replace(m,"");h.length>0&&e.childNodes.push(t(h))}else if(g[1].length>0)if(g[1].charAt(0)=="?")h=g[1].substr(1),g=g[2].substr(0,g[2].length-2),e.childNodes.push({nodeType:j.PROCESSING_INSTRUCTION,nodeName:h,nodeValue:g});else if(g[1].charAt(0)=="!")if(g[1].indexOf("![CDATA[")==0){var i=parseInt(g[1].replace("![CDATA[","").replace("]]",""));e.childNodes.push({nodeType:j.CDATA_SECTION,
nodeName:"#cdata-section",nodeValue:d[i]})}else g[1].substr(0,3)=="!--"&&(i=parseInt(g[1].replace("!--","").replace("--","")),e.childNodes.push({nodeType:j.COMMENT,nodeName:"#comment",nodeValue:c[i]}));else{var h=g[1].replace(m,""),f={nodeType:j.ELEMENT,nodeName:h,localName:h,namespace:l,ownerDocument:b,attributes:[],parentNode:null,childNodes:[]};if(h.indexOf(":")>-1){var k=h.split(":");f.namespace=k[0];f.localName=k[1]}f.byName=f.getElementsByTagName=p;f.byNameNS=f.getElementsByTagNameNS=q;f.childrenByName=
r;f.childrenByNameNS=s;f.getAttribute=B;f.getAttributeNS=C;f.setAttribute=D;f.setAttributeNS=E;f.previous=f.previousSibling=F;for(f.next=f.nextSibling=G;(i=I.exec(g[2]))!=null;)if(i.length>0)if(h=i[1].replace(m,""),i=(i[4]||i[6]||"").replace(u," ").replace(v,">").replace(w,"<").replace(x,"'").replace(y,'"').replace(z,"&"),h.indexOf("xmlns")==0)h.indexOf(":")>0?(k=h.split(":"),b.namespaces[k[1]]=i,b._nsPaths[i]=k[1]):(b.namespaces[l]=i,b._nsPaths[i]=l);else{var o=h,k=l;h.indexOf(":")>0&&(k=h.split(":"),
o=k[1],k=k[0]);f.attributes.push({nodeType:j.ATTRIBUTE,nodeName:h,localName:o,namespace:k,nodeValue:i});if(o=="id")f.id=i}b._add(f);if(e)e.childNodes.push(f),f.parentNode=e,g[2].charAt(g[2].length-1)!="/"&&(e=f);h=g[3];h.length>0&&e.childNodes.push(t(h))}for(e=0;e<b.childNodes.length;e++)if(a=b.childNodes[e],a.nodeType==j.ELEMENT){b.documentElement=a;break}return b}};