/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.embed.Quicktime"]||(dojo._hasResource["dojox.embed.Quicktime"]=!0,dojo.provide("dojox.embed.Quicktime"),function(d){function i(a){a=d.mixin(d.clone(l),a||{});if(!("path"in a)&&!a.testing)return console.error("dojox.embed.Quicktime(ctor):: no path reference to a QuickTime movie was provided."),null;if(a.testing)a.path="";if(!("id"in a))a.id=m+n++;return a}var f,j={major:0,minor:0,rev:0},e,l={width:320,height:240,redirect:null},m="dojox-embed-quicktime-",n=0;d.isIE?(e=function(){try{var a=
new ActiveXObject("QuickTimeCheckObject.QuickTimeCheck.1");if(a!==void 0){var b=a.QuickTimeVersion.toString(16);j={major:b.substring(0,1)-0||0,minor:b.substring(1,2)-0||0,rev:b.substring(2,3)-0||0};return a.IsQuickTimeAvailable(0)}}catch(c){}return!1}(),f=function(a){if(!e)return{id:null,markup:'This content requires the <a href="http://www.apple.com/quicktime/download/" title="Download and install QuickTime.">QuickTime plugin</a>.'};a=i(a);if(!a)return null;var b='<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab#version=6,0,2,0" id="'+
a.id+'" width="'+a.width+'" height="'+a.height+'"><param name="src" value="'+a.path+'"/>',c;for(c in a.params||{})b+='<param name="'+c+'" value="'+a.params[c]+'"/>';b+="</object>";return{id:a.id,markup:b}}):(e=function(){for(var a=0,b=navigator.plugins,c=b.length;a<c;a++)if(b[a].name.indexOf("QuickTime")>-1)return!0;return!1}(),f=function(a){if(!e)return{id:null,markup:'This content requires the <a href="http://www.apple.com/quicktime/download/" title="Download and install QuickTime.">QuickTime plugin</a>.'};
a=i(a);if(!a)return null;var b='<embed type="video/quicktime" src="'+a.path+'" id="'+a.id+'" name="'+a.id+'" pluginspage="www.apple.com/quicktime/download" enablejavascript="true" width="'+a.width+'" height="'+a.height+'"',c;for(c in a.params||{})b+=" "+c+'="'+a.params[c]+'"';b+="></embed>";return{id:a.id,markup:b}});dojox.embed.Quicktime=function(a,b){return dojox.embed.Quicktime.place(a,b)};d.mixin(dojox.embed.Quicktime,{minSupported:6,available:e,supported:e,version:j,initialized:!1,onInitialize:function(){dojox.embed.Quicktime.initialized=
!0},place:function(a,b){var c=f(a);if(!(b=d.byId(b)))b=d.create("div",{id:c.id+"-container"},d.body());return c&&(b.innerHTML=c.markup,c.id)?d.isIE?d.byId(c.id):document[c.id]:null}});if(d.isIE)d.isIE&&e&&setTimeout(function(){dojox.embed.Quicktime.onInitialize()},10);else{var g=f({testing:!0,width:4,height:4}),h=10,k=function(){setTimeout(function(){var a=document[g.id],b=d.byId("-qt-version-test");if(a)try{var c=a.GetQuickTimeVersion().split(".");dojox.embed.Quicktime.version={major:parseInt(c[0]||
0),minor:parseInt(c[1]||0),rev:parseInt(c[2]||0)};if(dojox.embed.Quicktime.supported=c[0])dojox.embed.Quicktime.onInitialize();h=0}catch(e){h--&&k()}!h&&b&&d.destroy(b)},20)};d._initFired?d.create("div",{innerHTML:g.markup,id:"-qt-version-test",style:{top:"-1000px",left:0,width:"1px",height:"1px",overflow:"hidden",position:"absolute"}},d.body()):document.write('<div style="top:-1000px;left:0;width:1px;height:1px;overflow:hidden;position:absolute" id="-qt-version-test">'+g.markup+"</div>");k()}}(dojo));