/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.dtl.tag.misc"]||(dojo._hasResource["dojox.dtl.tag.misc"]=!0,dojo.provide("dojox.dtl.tag.misc"),dojo.require("dojox.dtl._base"),function(){var f=dojox.dtl,e=f.tag.misc;e.DebugNode=dojo.extend(function(a){this.text=a},{render:function(a,b){for(var c=a.getKeys(),d=[],e={},f=0,g;g=c[f];f++)e[g]=a[g],d+="["+g+": "+typeof a[g]+"]\n";console.debug(e);return this.text.set(d).render(a,b,this)},unrender:function(a,b){return b},clone:function(a){return new this.constructor(this.text.clone(a))},
toString:function(){return"ddtm.DebugNode"}});e.FilterNode=dojo.extend(function(a,b){this._varnode=a;this._nodelist=b},{render:function(a,b){var c=this._nodelist.render(a,new dojox.string.Builder),a=a.update({"var":c.toString()});this._varnode.render(a,b);a.pop();return b},unrender:function(a,b){return b},clone:function(a){return new this.constructor(this._expression,this._nodelist.clone(a))}});e.FirstOfNode=dojo.extend(function(a,b){this._vars=a;this.vars=dojo.map(a,function(a){return new dojox.dtl._Filter(a)});
this.contents=b},{render:function(a,b){for(var c=0,d;d=this.vars[c];c++)if(d=d.resolve(a),typeof d!="undefined")return d===null&&(d="null"),this.contents.set(d),this.contents.render(a,b);return this.contents.unrender(a,b)},unrender:function(a,b){return this.contents.unrender(a,b)},clone:function(a){return new this.constructor(this._vars,this.contents.clone(a))}});e.SpacelessNode=dojo.extend(function(a,b){this.nodelist=a;this.contents=b},{render:function(a,b){if(b.getParent){var c=[dojo.connect(b,
"onAddNodeComplete",this,"_watch"),dojo.connect(b,"onSetParent",this,"_watchParent")],b=this.nodelist.render(a,b);dojo.disconnect(c[0]);dojo.disconnect(c[1])}else this.contents.set(this.nodelist.dummyRender(a).replace(/>\s+</g,"><")),b=this.contents.render(a,b);return b},unrender:function(a,b){return this.nodelist.unrender(a,b)},clone:function(a){return new this.constructor(this.nodelist.clone(a),this.contents.clone(a))},_isEmpty:function(a){return a.nodeType==3&&!a.data.match(/[^\s\n]/)},_watch:function(a){if(this._isEmpty(a))a.parentNode.firstChild==
a&&a.parentNode.removeChild(a);else{var b=a.parentNode.childNodes;if(a.nodeType==1&&b.length>2)for(var c=2;b[c];c++)if(b[c-2].nodeType==1&&this._isEmpty(b[c-1])){a.parentNode.removeChild(b[c-1]);break}}},_watchParent:function(a){if(a.childNodes.length)for(;a.childNodes.length;){var b=a.childNodes[a.childNodes.length-1];if(!this._isEmpty(b))break;a.removeChild(b)}}});e.TemplateTagNode=dojo.extend(function(a,b){this.tag=a;this.contents=b},{mapping:{openblock:"{%",closeblock:"%}",openvariable:"{{",closevariable:"}}",
openbrace:"{",closebrace:"}",opencomment:"{#",closecomment:"#}"},render:function(a,b){this.contents.set(this.mapping[this.tag]);return this.contents.render(a,b)},unrender:function(a,b){return this.contents.unrender(a,b)},clone:function(a){return new this.constructor(this.tag,this.contents.clone(a))}});e.WidthRatioNode=dojo.extend(function(a,b,c,d){this.current=new f._Filter(a);this.max=new f._Filter(b);this.width=c;this.contents=d},{render:function(a,b){var c=+this.current.resolve(a),d=+this.max.resolve(a);
typeof c!="number"||typeof d!="number"||!d?this.contents.set(""):this.contents.set(""+Math.round(c/d*this.width));return this.contents.render(a,b)},unrender:function(a,b){return this.contents.unrender(a,b)},clone:function(a){return new this.constructor(this.current.getExpression(),this.max.getExpression(),this.width,this.contents.clone(a))}});e.WithNode=dojo.extend(function(a,b,c){this.target=new f._Filter(a);this.alias=b;this.nodelist=c},{render:function(a,b){var c=this.target.resolve(a),a=a.push();
a[this.alias]=c;b=this.nodelist.render(a,b);a.pop();return b},unrender:function(a,b){return b},clone:function(a){return new this.constructor(this.target.getExpression(),this.alias,this.nodelist.clone(a))}});dojo.mixin(e,{comment:function(a){a.skip_past("endcomment");return f._noOpNode},debug:function(a){return new e.DebugNode(a.create_text_node())},filter:function(a,b){var c=b.contents.split(null,1)[1],c=a.create_variable_node("var|"+c),d=a.parse(["endfilter"]);a.next_token();return new e.FilterNode(c,
d)},firstof:function(a,b){var c=b.split_contents().slice(1);if(!c.length)throw Error("'firstof' statement requires at least one argument");return new e.FirstOfNode(c,a.create_text_node())},spaceless:function(a){var b=a.parse(["endspaceless"]);a.delete_first_token();return new e.SpacelessNode(b,a.create_text_node())},templatetag:function(a,b){var c=b.contents.split();if(c.length!=2)throw Error("'templatetag' statement takes one argument");var c=c[1],d=e.TemplateTagNode.prototype.mapping;if(!d[c]){var f=
[],h;for(h in d)f.push(h);throw Error("Invalid templatetag argument: '"+c+"'. Must be one of: "+f.join(", "));}return new e.TemplateTagNode(c,a.create_text_node())},widthratio:function(a,b){var c=b.contents.split();if(c.length!=4)throw Error("widthratio takes three arguments");var d=+c[3];if(typeof d!="number")throw Error("widthratio final argument must be an integer");return new e.WidthRatioNode(c[1],c[2],d,a.create_text_node())},with_:function(a,b){var c=b.split_contents();if(c.length!=4||c[2]!=
"as")throw Error("do_width expected format as 'with value as name'");var d=a.parse(["endwith"]);a.next_token();return new e.WithNode(c[1],c[3],d)}})}());