<div class="prepend-0">
<h2>Step 2 - Set the database</h2>
Below you should enter your database connection details.<br />
If you're not sure about these, please contact your server administrator.<br />
<br />
<?php
include ("serverFeedback.phtml");
?>

<table class="form"
style="width: auto;">
<col class="col1" />
<tr>
    <td colspan="2">
        <button dojoType="dijit.form.Button" baseClass="positive" type="button" iconClass="tick"
        onClick="
        phprSend({
            url:       '<?php echo $this->webPath; ?>' + 'setup.php/index/jsonUsersForm',
            onSuccess: dojo.hitch(this, function(data) {
                dijit.byId('formContent').attr('content', data.template);
                changeStep(2, 3);
            })
        });">
            Continue with the users
        </button>
    </td>
</tr>
</table>
</div>
