<div class="prepend-0">
<h2>Step 4 - Create private folders for save user data</h2>
Phprojekt 6 will create a private folder to store sensitiv data.<br />
We recommend to use a path outside your document root.<br />
Please provide the path of this folder, and the setup will try to create it.<br />
<br />
<?php
include ("serverFeedback.phtml");
?>

<table class="form"
style="width: auto;">
<col class="col1" />
<tr>
    <td colspan="2">
        <button dojoType="dijit.form.Button" baseClass="positive" type="button" iconClass="tick"
        onClick="
        phprSend({
            url:       '<?php echo $this->webPath; ?>' + 'setup.php/index/jsonTablesForm',
            onSuccess: dojo.hitch(this, function(data) {
                dijit.byId('formContent').attr('content', data.template);
                changeStep(4, 5);
            })
        });">
            Continue with the tables
        </button>
    </td>
</tr>
</table>
</div>
