<form dojoType="dijit.form.Form" id="loginForm" name="frm" method="post" enctype="multipart/form-data"
action="<?php echo $this->url(array('action' => 'install')); ?>">
<table class="form"
style="width: 100%;">
<col class="col1"
style="width: 20%;" />
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="serverType">Server type</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <select id="serverType" name="serverType" dojoType="dijit.form.FilteringSelect"
        required="true" autocomplete="true" value="pdo_mysql" searchAttr="name" invalidMessage="You must select one">
            <option value="pdo_mysql">MySQL</option>
        </select>
    </td>
</tr>
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="dbHost">Database server:</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <input type="text" id="dbHost" name="dbHost" dojoType="dijit.form.TextBox"
        required="true" value="<?php echo $this->dbHost; ?>" invalidMessage="" />
    </td>
</tr>
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="dbUser">Database username:</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <input type="text" id="dbUser" name="dbUser" dojoType="dijit.form.TextBox"
        required="true" value="<?php echo $this->dbUser; ?>" invalidMessage="" />
    </td>
</tr>
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="dbPass">Database password:</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <input type="password" id="dbPass" name="dbPass" dojoType="dijit.form.TextBox"
        required="true" value="<?php echo $this->dbPass; ?>" invalidMessage="" />
    </td>
</tr>
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="dbName">Database name:</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <input type="text" id="dbName" name="dbName" dojoType="dijit.form.TextBox"
        required="true" value="<?php echo $this->dbName; ?>" invalidMessage="" />
    </td>
</tr>
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="adminPass">Admin user pass:</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <input type="password" id="adminPass" name="adminPass" dojoType="dijit.form.TextBox"
        required="true" value="<?php echo $this->adminPass; ?>" invalidMessage="" />
    </td>
</tr>
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="adminPassConfirm">Admin pass confirm:</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <input type="password" id="adminPassConfirm" name="adminPassConfirm" dojoType="dijit.form.TextBox"
        required="required" value="<?php echo $this->adminPassConfirm; ?>" invalidMessage="" />
    </td>
</tr>
<tr>
    <td class="label"
    style="padding: 0 0 4px 5px;">
        <label for="extraData">Install example data:</label>
    </td>
    <td
    style="padding: 0 0 4px 5px;">
        <input type="checkbox" dojotype="dijit.form.CheckBox" id="useExtraData" name="useExtraData"
        <?php
        if ($this->useExtraData) {
            echo 'checked="checked"';
        }
        ?>
        value="1" />
    </td>
</tr>
<tr>
    <td class="label">
        <h3>Migration</h3>
    </td>
    <td
    style="padding: 0 0 0 5px;">
        Please, provide the path to the config.inc.php file of your old PHProjekt 5.x.<br />
        <u>Notes</u>:<br />
        <ul style="margin: 0 1.5em">
            <li><b>Choose a different database from the one used in Phprojekt 5 so that you don't lose your data.</b>
            </li>
            <li>The process could take several minutes depending on the number of projects to be migrated.</li>
            <li>The config.inc.php needs to be on the same server where you are installing PHProjekt 6</li>
            <li><b>If you want to know more about the migration routine, please read the
            <a href="#" onclick="window.open('<?php echo $this->webPath; ?>Setup/Docs/Migration.html', 'Migration',
            'status=0,menubar=0,resizable=1,top=200px,left=400px,width=700px,height=600px,scrollbars=1,addressbar=0');
            return false;">Migration</a> file.</b></li>
        </ul>
    </td>
</tr>
<tr>
    <td class="label">
        <label for="migration_config">Configuration file:</label>
    </td>
    <td>
        <input dojoType="dijit.form.TextBox" type="text" name="migrationConfigFile"
        value="<?php echo $this->migrationConfigFile; ?>" />
        <br />File path (e.g. /var/www/html/config.inc.php)
   </td>
</tr>
<tr>
    <td class="label">
        &nbsp;
    </td>
    <td>
        <button dojoType="dijit.form.Button" baseClass="positive" id="submitButton" type="submit" iconClass="tick">
            Install
        </button>
    </td>
</tr>
</table>
</form>
