<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>PHProjekt</title>
    <link rel="shortcut icon" href="<?php echo $this->webPath; ?>img/favicon.ico" type="image/x-icon" />
    <style type="text/css">
        @import "<?php echo $this->webPath; ?>css/themes/phprojekt/phprojektCssCompiler.php";
    </style>
    <script type="text/javascript">
        var djConfig = {isDebug: false, parseOnLoad: false, bindEncoding: "utf-8",
                        locale: 'en', useCommentedJson: true};
    </script>
    <script type="text/javascript" src="<?php echo $this->webPath; ?>dojo/dojo/dojo.js"></script>
    <script type="text/javascript" src="<?php echo $this->webPath; ?>dojo/dojo/mydojo.js"></script>
    <script type="text/javascript">
        function getMaxHeight() {
            var availHeight = 0;

            if (document.layers) {
                availHeight = window.innerHeight + window.pageYOffset;
            } else if (document.all) {
                availHeight = document.documentElement.clientHeight + document.documentElement.scrollTop;
            } else if (document.getElementById) {
                availHeight = window.innerHeight + window.pageYOffset;
            }

            return availHeight;
        }

        function init() {
            availHeight = getMaxHeight();

            dojo.style(dojo.byId('completeContent'), "height", availHeight + "px");
            if (dijit.byId('completeContent')) {
                dijit.byId('completeContent').resize();
            }

            if (dojo.byId('completeCenterContent')) {
                dojo.style(dojo.byId('completeCenterContent'), "height", (availHeight - 55) + "px");
                if (dijit.byId('completeCenterContent')) {
                    dijit.byId('completeCenterContent').resize();
                }
            }
        }

        dojo.addOnLoad(function() {
            dojo.parser.parse();
            init();
            hideLoading();
        });

        window.onresize = function() {
            init();
        };

        hideLoading = function() {
            if (dojo.byId('initLoading') && dojo.byId('completeContent')) {
                dojo.style("initLoading", "display", "none");
                dojo.style("completeContent", "opacity", 1);
            }
        }
    </script>
</head>
<body class="phprojekt">

<div id="completeContent" dojoType="dijit.layout.BorderContainer" persist="true"
 style="width: 100%; height: 1000px;">
    <!-- Left Content -->
    <div id="navigation-container" dojoType="dijit.layout.ContentPane" region="left" splitter="false" minSize="180"
    maxSize="300"
    style="width: 15%; overflow: hidden;">
        <div region="center" dojoType="dijit.layout.ContentPane">
            <div id="tree-navigation">
                <div dojoType="dijit.layout.ContentPane" id="treeBox"
                 style="height: 100%;">
                </div>
            </div>
        </div>
    </div>

    <!-- Top Bar menu -->
    <div dojoType="dijit.layout.ContentPane" region="top" id="header"
    style="height: 55px; overflow: hidden;">
        <img class="left" src="<?php echo $this->webPath; ?>img/logo.png" alt="PHProjekt 6" />
        <div id="mainNavigation"  class="right align-right" dojoType="dijit.Toolbar">
        </div>
    </div>

    <!-- Center Content -->
    <div id="completeCenterContent" dojoType="dijit.layout.ContentPane" region="center"
    style="height: 1000px;">
        <div dojoType="dijit.layout.BorderContainer" design="sidebar"
        style="height: 100%;">
            <!-- Second Top Bar -->
            <div dojoType="dijit.layout.ContentPane" region="top" class="block" splitter="false"
            style="height: 100%;">
                <div class="column">
                    <img src="<?php echo $this->webPath; ?>img/subheaderborder.png" alt="" />
                </div>
                <div dojoType="dijit.layout.ContentPane" region="top" class="block"
                style="height: 2%;" splitter="false">
                </div>
                <!-- Exception Form -->
                <div id="serverFeedback" class="prepend-1 append-1">
                <?php
                if ($this->error) {
                    echo '<div class="error">' . $this->error . '</div>';
                    ?>
                    <script type="text/javascript">
                        hideLoading();
                    </script>
                    <?php
                }
                ?>
                <?php
                if ($this->message) {
                    echo '<div class="error">' . $this->message . '</div>';
                    ?>
                    <script type="text/javascript">
                        hideLoading();
                    </script>
                    <?php
                }
                ?>
                <?php
                if ($this->success) {
                    echo '<div class="success">' . $this->success . '</div>';
                    ?>
                    <script type="text/javascript">
                        hideLoading();
                    </script>
                    <?php
                }
                ?>
                </div>
                <!-- Main Content -->
                <div dojoType="dijit.layout.ContentPane" region="center" id="centerMainContent">
                    <?php
                    if (empty($this->success) && null === $this->error) {
                        include ("form.phtml");
                    } else if (empty($this->error)) {
                        include ("finish.phtml");
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="initLoading"
style="position: absolute; top: 45%; left: 45%; display: none;">
    <center>
    <img src="<?php echo $this->webPath; ?>img/ajax-init-loader.gif" alt="Loadding" />
    <br /><br />
    Installing PHProjekt 6<br />
    The process could take several minutes, please wait...
    </center>
</div>
</body>
</html>
