<div class="prepend-0">
<h2>Step 3 - Set the users</h2>
Below you should set your first users.<br />
Please define the admin and test passwords.<br />
<br />
<?php
include ("serverFeedback.phtml");
?>

<table class="form"
style="width: auto;">
<col class="col1" />
<tr>
    <td colspan="2">
        <button dojoType="dijit.form.Button" baseClass="positive" type="button" iconClass="tick"
        onClick="
        phprSend({
            url:       '<?php echo $this->webPath; ?>' + 'setup.php/index/jsonFoldersForm',
            onSuccess: dojo.hitch(this, function(data) {
                dijit.byId('formContent').attr('content', data.template);
                changeStep(3, 4);
            })
        });">
            Continue with the folders
        </button>
    </td>
</tr>
</table>
</div>
