/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.string.BidiComplex"]||(dojo._hasResource["dojox.string.BidiComplex"]=!0,dojo.provide("dojox.string.BidiComplex"),dojo.experimental("dojox.string.BidiComplex"),function(){var h=[];dojox.string.BidiComplex.attachInput=function(a,b){a.alt=b;dojo.connect(a,"onkeydown",this,"_ceKeyDown");dojo.connect(a,"onkeyup",this,"_ceKeyUp");dojo.connect(a,"oncut",this,"_ceCutText");dojo.connect(a,"oncopy",this,"_ceCopyText");a.value=dojox.string.BidiComplex.createDisplayString(a.value,a.alt)};
dojox.string.BidiComplex.createDisplayString=function(a,b){var a=dojox.string.BidiComplex.stripSpecialCharacters(a),d=dojox.string.BidiComplex._parse(a,b),c="\u202a"+a,f=1;dojo.forEach(d,function(a){if(a!=null){var b=c.substring(0,a+f),a=c.substring(a+f,c.length);c=b+"\u200e"+a;f++}});return c};dojox.string.BidiComplex.stripSpecialCharacters=function(a){return a.replace(/[\u200E\u200F\u202A-\u202E]/g,"")};dojox.string.BidiComplex._ceKeyDown=function(a){h=(dojo.isIE?a.srcElement:a.target).value};dojox.string.BidiComplex._ceKeyUp=
function(a){var b=dojo.isIE?a.srcElement:a.target,d=b.value,c=a.keyCode;if(!(c==dojo.keys.HOME||c==dojo.keys.END||c==dojo.keys.SHIFT)){var f,e;if(a=dojox.string.BidiComplex._getCaretPos(a,b))f=a[0],e=a[1];if(dojo.isIE){var a=f,g=e;if(c==dojo.keys.LEFT_ARROW){d.charAt(e-1)=="\u200e"&&f==e&&dojox.string.BidiComplex._setSelectedRange(b,f-1,e-1);return}if(c==dojo.keys.RIGHT_ARROW){d.charAt(e-1)=="\u200e"&&(g=e+1,f==e&&(a=f+1));dojox.string.BidiComplex._setSelectedRange(b,a,g);return}}else{if(c==dojo.keys.LEFT_ARROW){d.charAt(e-
1)=="\u200e"&&dojox.string.BidiComplex._setSelectedRange(b,f-1,e-1);return}if(c==dojo.keys.RIGHT_ARROW){d.charAt(e-1)=="\u200e"&&dojox.string.BidiComplex._setSelectedRange(b,f+1,e+1);return}}a=dojox.string.BidiComplex.createDisplayString(d,b.alt);if(d!=a){window.status=d+" c="+e;b.value=a;if(c==dojo.keys.DELETE&&a.charAt(e)=="\u200e")b.value=a.substring(0,e)+a.substring(e+2,a.length);c==dojo.keys.DELETE?dojox.string.BidiComplex._setSelectedRange(b,f,e):c==dojo.keys.BACKSPACE?h.length>=e&&h.charAt(e-
1)=="\u200e"?dojox.string.BidiComplex._setSelectedRange(b,f-1,e-1):dojox.string.BidiComplex._setSelectedRange(b,f,e):b.value.charAt(e)!="\u200e"&&dojox.string.BidiComplex._setSelectedRange(b,f+1,e+1)}}};dojox.string.BidiComplex._processCopy=function(a,b){b==null&&(b=dojo.isIE?document.selection.createRange().text:a.value.substring(a.selectionStart,a.selectionEnd));var d=dojox.string.BidiComplex.stripSpecialCharacters(b);dojo.isIE&&window.clipboardData.setData("Text",d);return!0};dojox.string.BidiComplex._ceCopyText=
function(a){if(dojo.isIE)a.returnValue=!1;return dojox.string.BidiComplex._processCopy(a,null,!1)};dojox.string.BidiComplex._ceCutText=function(a){if(!dojox.string.BidiComplex._processCopy(a,null,!1))return!1;if(dojo.isIE)document.selection.clear();else{var b=a.selectionStart;a.value=a.value.substring(0,b)+a.value.substring(a.selectionEnd);a.setSelectionRange(b,b)}return!0};dojox.string.BidiComplex._getCaretPos=function(a,b){if(dojo.isIE){var d=0,c=document.selection.createRange().duplicate(),f=c.duplicate(),
e=c.text.length;for(b.type=="textarea"?f.moveToElementText(b):f.expand("textedit");c.compareEndPoints("StartToStart",f)>0;)c.moveStart("character",-1),++d;return[d,d+e]}return[a.target.selectionStart,a.target.selectionEnd]};dojox.string.BidiComplex._setSelectedRange=function(a,b,d){if(dojo.isIE){var c=a.createTextRange();c&&(a.type=="textarea"?c.moveToElementText(a):c.expand("textedit"),c.collapse(),c.moveEnd("character",d),c.moveStart("character",b),c.select())}else a.selectionStart=b,a.selectionEnd=
d};var i=function(a,b,d){for(;b>0;){if(b==d)break;b--;var c=a.charAt(b);if(c>="0"&&c<="9"||c>"\u00ff")return!0;c=a.charAt(b);if(c>="A"&&c<="Z"||c>="a"&&c<="z")break}return!1};dojox.string.BidiComplex._parse=function(a,b){var d=-1,c=[],f={FILE_PATH:"/\\:.",URL:"/:.?=&#",XPATH:"/\\:.<>=[]",EMAIL:"<>@.,;"}[b];switch(b){case "FILE_PATH":case "URL":case "XPATH":dojo.forEach(a,function(b,g){f.indexOf(b)>=0&&i(a,g,d)&&(d=g,c.push(g))});break;case "EMAIL":dojo.forEach(a,function(b,g){if(b=='"'){i(a,g,d)&&
(d=g,c.push(g));g++;var h=a.indexOf('"',g);h>=g&&(g=h);i(a,g,d)&&(d=g,c.push(g))}f.indexOf(b)>=0&&i(a,g,d)&&(d=g,c.push(g))})}return c}}());