/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.string.sprintf"])dojo._hasResource["dojox.string.sprintf"]=!0,dojo.provide("dojox.string.sprintf"),dojo.require("dojox.string.tokenize"),dojox.string.sprintf=function(a,c){for(var d=[],e=1;e<arguments.length;e++)d.push(arguments[e]);e=new dojox.string.sprintf.Formatter(a);return e.format.apply(e,d)},dojox.string.sprintf.Formatter=function(a){this._mapped=!1;this._format=a;this._tokens=dojox.string.tokenize(a,this._re,this._parseDelim,this)},dojo.extend(dojox.string.sprintf.Formatter,
{_re:/\%(?:\(([\w_]+)\)|([1-9]\d*)\$)?([0 +\-\#]*)(\*|\d+)?(\.)?(\*|\d+)?[hlL]?([\%scdeEfFgGiouxX])/g,_parseDelim:function(a,c,d,e,b,f,g){if(a)this._mapped=!0;return{mapping:a,intmapping:c,flags:d,_minWidth:e,period:b,_precision:f,specifier:g}},_specifiers:{b:{base:2,isInt:!0},o:{base:8,isInt:!0},x:{base:16,isInt:!0},X:{extend:["x"],toUpper:!0},d:{base:10,isInt:!0},i:{extend:["d"]},u:{extend:["d"],isUnsigned:!0},c:{setArg:function(a){if(!isNaN(a.arg)){var c=parseInt(a.arg);if(c<0||c>127)throw Error("invalid character code passed to %c in sprintf");
a.arg=isNaN(c)?""+c:String.fromCharCode(c)}}},s:{setMaxWidth:function(a){a.maxWidth=a.period=="."?a.precision:-1}},e:{isDouble:!0,doubleNotation:"e"},E:{extend:["e"],toUpper:!0},f:{isDouble:!0,doubleNotation:"f"},F:{extend:["f"]},g:{isDouble:!0,doubleNotation:"g"},G:{extend:["g"],toUpper:!0}},format:function(a){if(this._mapped&&typeof a!="object")throw Error("format requires a mapping");for(var c="",d=0,e=0,b;e<this._tokens.length;e++)if(b=this._tokens[e],typeof b=="string")c+=b;else{if(this._mapped){if(typeof a[b.mapping]==
"undefined")throw Error("missing key "+b.mapping);b.arg=a[b.mapping]}else{b.intmapping&&(d=parseInt(b.intmapping)-1);if(d>=arguments.length)throw Error("got "+arguments.length+" printf arguments, insufficient for '"+this._format+"'");b.arg=arguments[d++]}if(!b.compiled){b.compiled=!0;b.sign="";b.zeroPad=!1;b.rightJustify=!1;b.alternative=!1;for(var f={},g=b.flags.length;g--;){var h=b.flags.charAt(g);f[h]=!0;switch(h){case " ":b.sign=" ";break;case "+":b.sign="+";break;case "0":b.zeroPad=f["-"]?!1:
!0;break;case "-":b.rightJustify=!0;b.zeroPad=!1;break;case "#":b.alternative=!0;break;default:throw Error("bad formatting flag '"+b.flags.charAt(g)+"'");}}b.minWidth=b._minWidth?parseInt(b._minWidth):0;b.maxWidth=-1;b.toUpper=!1;b.isUnsigned=!1;b.isInt=!1;b.isDouble=!1;b.precision=1;if(b.period==".")b.precision=b._precision?parseInt(b._precision):0;f=this._specifiers[b.specifier];if(typeof f=="undefined")throw Error("unexpected specifier '"+b.specifier+"'");f.extend&&(dojo.mixin(f,this._specifiers[f.extend]),
delete f.extend);dojo.mixin(b,f)}typeof b.setArg=="function"&&b.setArg(b);typeof b.setMaxWidth=="function"&&b.setMaxWidth(b);if(b._minWidth=="*"){if(this._mapped)throw Error("* width not supported in mapped formats");b.minWidth=parseInt(arguments[d++]);if(isNaN(b.minWidth))throw Error("the argument for * width at position "+d+" is not a number in "+this._format);if(b.minWidth<0)b.rightJustify=!0,b.minWidth=-b.minWidth}if(b._precision=="*"&&b.period=="."){if(this._mapped)throw Error("* precision not supported in mapped formats");
b.precision=parseInt(arguments[d++]);if(isNaN(b.precision))throw Error("the argument for * precision at position "+d+" is not a number in "+this._format);if(b.precision<0)b.precision=1,b.period=""}if(b.isInt){if(b.period==".")b.zeroPad=!1;this.formatInt(b)}else if(b.isDouble){if(b.period!=".")b.precision=6;this.formatDouble(b)}this.fitField(b);c+=""+b.arg}return c},_zeros10:"0000000000",_spaces10:"          ",formatInt:function(a){var c=parseInt(a.arg);if(!isFinite(c)){if(typeof a.arg!="number")throw Error("format argument '"+
a.arg+"' not an integer; parseInt returned "+c);c=0}if(c<0&&(a.isUnsigned||a.base!=10))c=4294967295+c+1;if(c<0)a.arg=(-c).toString(a.base),this.zeroPad(a),a.arg="-"+a.arg;else if(a.arg=c.toString(a.base),!c&&!a.precision?a.arg="":this.zeroPad(a),a.sign)a.arg=a.sign+a.arg;if(a.base==16){if(a.alternative)a.arg="0x"+a.arg;a.arg=a.toUpper?a.arg.toUpperCase():a.arg.toLowerCase()}if(a.base==8&&a.alternative&&a.arg.charAt(0)!="0")a.arg="0"+a.arg},formatDouble:function(a){var c=parseFloat(a.arg);if(!isFinite(c)){if(typeof a.arg!=
"number")throw Error("format argument '"+a.arg+"' not a float; parseFloat returned "+c);c=0}switch(a.doubleNotation){case "e":a.arg=c.toExponential(a.precision);break;case "f":a.arg=c.toFixed(a.precision);break;case "g":a.arg=Math.abs(c)<1.0E-4?c.toExponential(a.precision>0?a.precision-1:a.precision):c.toPrecision(a.precision);if(!a.alternative)a.arg=a.arg.replace(/(\..*[^0])0*/,"$1"),a.arg=a.arg.replace(/\.0*e/,"e").replace(/\.0$/,"");break;default:throw Error("unexpected double notation '"+a.doubleNotation+
"'");}a.arg=a.arg.replace(/e\+(\d)$/,"e+0$1").replace(/e\-(\d)$/,"e-0$1");if(dojo.isOpera)a.arg=a.arg.replace(/^\./,"0.");if(a.alternative)a.arg=a.arg.replace(/^(\d+)$/,"$1."),a.arg=a.arg.replace(/^(\d+)e/,"$1.e");if(c>=0&&a.sign)a.arg=a.sign+a.arg;a.arg=a.toUpper?a.arg.toUpperCase():a.arg.toLowerCase()},zeroPad:function(a,c){c=arguments.length==2?c:a.precision;if(typeof a.arg!="string")a.arg=""+a.arg;for(var d=c-10;a.arg.length<d;)a.arg=a.rightJustify?a.arg+this._zeros10:this._zeros10+a.arg;d=c-
a.arg.length;a.arg=a.rightJustify?a.arg+this._zeros10.substring(0,d):this._zeros10.substring(0,d)+a.arg},fitField:function(a){if(a.maxWidth>=0&&a.arg.length>a.maxWidth)return a.arg.substring(0,a.maxWidth);a.zeroPad?this.zeroPad(a,a.minWidth):this.spacePad(a)},spacePad:function(a,c){c=arguments.length==2?c:a.minWidth;if(typeof a.arg!="string")a.arg=""+a.arg;for(var d=c-10;a.arg.length<d;)a.arg=a.rightJustify?a.arg+this._spaces10:this._spaces10+a.arg;d=c-a.arg.length;a.arg=a.rightJustify?a.arg+this._spaces10.substring(0,
d):this._spaces10.substring(0,d)+a.arg}});