<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>PHProjekt</title>
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
    <style>
        @import "<?php echo $this->webpath; ?>scripts/src/dojo/resources/dojo.css";
        @import "<?php echo $this->webpath; ?>css/themes/phprojekt/phprojekt.css";
        @import "<?php echo $this->webpath; ?>scripts/src/dijit/themes/dijit.css";
        @import "<?php echo $this->webpath; ?>scripts/src/dijit/themes/dijit_rtl.css";
    </style>
    <script type="text/javascript">
        var djConfig = {isDebug: true, parseOnLoad: false, preventBackButtonFix: false,
                        bindEncoding: "utf-8", dojoIframeHistoryUrl: '../resources/iframe_history.html',
                        locale: '<?php echo $this->language; ?>', useCommentedJson: true};
    </script>
    <script type="text/javascript" src="<?php echo $this->webpath; ?>scripts/src/dojo/dojo.js"></script>

    <script type="text/javascript" src="<?php echo $this->webpath; ?>scripts/phpr/phpr.js"></script>
</head>
<body class="phprojekt">
    <script>
    	dojo.require("phpr.Main");
        var main = new phpr.Main("<?php echo $this->webpath; ?>","Project",1);
    </script>
</body>
</html>
<!-- template: index.phml -->