/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.date.islamic.Date"])dojo._hasResource["dojox.date.islamic.Date"]=!0,dojo.provide("dojox.date.islamic.Date"),dojo.require("dojo.date"),dojo.requireLocalization("dojo.cldr","islamic",null,"ROOT,ar,da,de,en,en-gb,es,fi,he,zh-hant"),dojo.declare("dojox.date.islamic.Date",null,{_date:0,_month:0,_year:0,_hours:0,_minutes:0,_seconds:0,_milliseconds:0,_day:0,_GREGORIAN_EPOCH:1721425.5,_ISLAMIC_EPOCH:1948439.5,constructor:function(){var a=arguments.length;a?a==1?(a=arguments[0],
typeof a=="number"&&(a=new Date(a)),a instanceof Date?this.fromGregorian(a):a==""?this._date=new Date(""):(this._year=a._year,this._month=a._month,this._date=a._date,this._hours=a._hours,this._minutes=a._minutes,this._seconds=a._seconds,this._milliseconds=a._milliseconds)):a>=3&&(this._year+=arguments[0],this._month+=arguments[1],this._date+=arguments[2],this._hours+=arguments[3]||0,this._minutes+=arguments[4]||0,this._seconds+=arguments[5]||0,this._milliseconds+=arguments[6]||0):this.fromGregorian(new Date)},
getDate:function(){return this._date},getMonth:function(){return this._month},getFullYear:function(){return this._year},getDay:function(){return this.toGregorian().getDay()},getHours:function(){return this._hours},getMinutes:function(){return this._minutes},getSeconds:function(){return this._seconds},getMilliseconds:function(){return this._milliseconds},setDate:function(a){a=parseInt(a);if(!(a>0&&a<=this.getDaysInIslamicMonth(this._month,this._year))){var b;if(a>0)for(b=this.getDaysInIslamicMonth(this._month,
this._year);a>b;a-=b,b=this.getDaysInIslamicMonth(this._month,this._year))this._month++,this._month>=12&&(this._year++,this._month-=12);else for(b=this.getDaysInIslamicMonth(this._month-1>=0?this._month-1:11,this._month-1>=0?this._year:this._year-1);a<=0;b=this.getDaysInIslamicMonth(this._month-1>=0?this._month-1:11,this._month-1>=0?this._year:this._year-1))this._month--,this._month<0&&(this._year--,this._month+=12),a+=b}this._date=a;return this},setFullYear:function(a){this._year=+a},setMonth:function(a){this._year+=
Math.floor(a/12);this._month=a>0?Math.floor(a%12):Math.floor((a%12+12)%12)},setHours:function(){var a=arguments.length,b=0;a>=1&&(b=parseInt(arguments[0]));if(a>=2)this._minutes=parseInt(arguments[1]);if(a>=3)this._seconds=parseInt(arguments[2]);if(a==4)this._milliseconds=parseInt(arguments[3]);for(;b>=24;)this._date++,a=this.getDaysInIslamicMonth(this._month,this._year),this._date>a&&(this._month++,this._month>=12&&(this._year++,this._month-=12),this._date-=a),b-=24;this._hours=b},setMinutes:function(a){for(;a>=
60;){this._hours++;if(this._hours>=24){this._date++;this._hours-=24;var b=this.getDaysInIslamicMonth(this._month,this._year);this._date>b&&(this._month++,this._month>=12&&(this._year++,this._month-=12),this._date-=b)}a-=60}this._minutes=a},setSeconds:function(a){for(;a>=60;){this._minutes++;if(this._minutes>=60&&(this._hours++,this._minutes-=60,this._hours>=24)){this._date++;this._hours-=24;var b=this.getDaysInIslamicMonth(this._month,this._year);this._date>b&&(this._month++,this._month>=12&&(this._year++,
this._month-=12),this._date-=b)}a-=60}this._seconds=a},setMilliseconds:function(a){for(;a>=1E3;){this.setSeconds++;if(this.setSeconds>=60&&(this._minutes++,this.setSeconds-=60,this._minutes>=60&&(this._hours++,this._minutes-=60,this._hours>=24))){this._date++;this._hours-=24;var b=this.getDaysInIslamicMonth(this._month,this._year);this._date>b&&(this._month++,this._month>=12&&(this._year++,this._month-=12),this._date-=b)}a-=1E3}this._milliseconds=a},toString:function(){var a=new Date;a.setHours(this._hours);
a.setMinutes(this._minutes);a.setSeconds(this._seconds);a.setMilliseconds(this._milliseconds);return this._month+" "+this._date+" "+this._year+" "+a.toTimeString()},toGregorian:function(){var a=this._year,a=Math.floor(this._date+Math.ceil(29.5*this._month)+(a-1)*354+Math.floor((3+11*a)/30)+this._ISLAMIC_EPOCH-1-0.5)+0.5,b=a-this._GREGORIAN_EPOCH,c=Math.floor(b/146097),d=this._mod(b,146097),b=Math.floor(d/36524),e=this._mod(d,36524),d=Math.floor(e/1461),e=this._mod(e,1461),e=Math.floor(e/365),c=c*
400+b*100+d*4+e;b==4||e==4||c++;b=a-(this._GREGORIAN_EPOCH+365*(c-1)+Math.floor((c-1)/4)-Math.floor((c-1)/100)+Math.floor((c-1)/400));d=this._GREGORIAN_EPOCH-1+365*(c-1)+Math.floor((c-1)/4)-Math.floor((c-1)/100)+Math.floor((c-1)/400)+Math.floor(739/12+(dojo.date.isLeapYear(new Date(c,3,1))?-1:-2)+1);d=a<d?0:dojo.date.isLeapYear(new Date(c,3,1))?1:2;b=Math.floor(((b+d)*12+373)/367);d=this._GREGORIAN_EPOCH-1+365*(c-1)+Math.floor((c-1)/4)-Math.floor((c-1)/100)+Math.floor((c-1)/400)+Math.floor((367*b-
362)/12+(b<=2?0:dojo.date.isLeapYear(new Date(c,b,1))?-1:-2)+1);return new Date(c,b-1,a-d+1,this._hours,this._minutes,this._seconds,this._milliseconds)},fromGregorian:function(a){var a=new Date(a),b=a.getFullYear(),c=a.getMonth(),d=a.getDate(),b=this._GREGORIAN_EPOCH-1+365*(b-1)+Math.floor((b-1)/4)+-Math.floor((b-1)/100)+Math.floor((b-1)/400)+Math.floor((367*(c+1)-362)/12+(c+1<=2?0:dojo.date.isLeapYear(a)?-1:-2)+d),b=Math.floor(b)+0.5;b-=this._ISLAMIC_EPOCH;c=Math.floor((30*b+10646)/10631);d=Math.ceil((b-
29-this._yearStart(c))/29.5);d=Math.min(d,11);this._date=Math.ceil(b-this._monthStart(c,d))+1;this._month=d;this._year=c;this._hours=a.getHours();this._minutes=a.getMinutes();this._seconds=a.getSeconds();this._milliseconds=a.getMilliseconds();this._day=a.getDay();return this},valueOf:function(){return this.toGregorian().valueOf()},_yearStart:function(a){return(a-1)*354+Math.floor((3+11*a)/30)},_monthStart:function(a,b){return Math.ceil(29.5*b)+(a-1)*354+Math.floor((3+11*a)/30)},_civilLeapYear:function(a){return(14+
11*a)%30<11},getDaysInIslamicMonth:function(a,b){var c=0,c=29+(a+1)%2;a==11&&this._civilLeapYear(b)&&c++;return c},_mod:function(a,b){return a-b*Math.floor(a/b)}}),dojox.date.islamic.Date.getDaysInIslamicMonth=function(a){return(new dojox.date.islamic.Date).getDaysInIslamicMonth(a.getMonth(),a.getFullYear())};