/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.date.islamic.locale"])dojo._hasResource["dojox.date.islamic.locale"]=!0,dojo.provide("dojox.date.islamic.locale"),dojo.require("dojox.date.islamic.Date"),dojo.require("dojo.regexp"),dojo.require("dojo.string"),dojo.require("dojo.i18n"),dojo.require("dojo.date"),dojo.requireLocalization("dojo.cldr","islamic",null,"ROOT,ar,da,de,en,en-gb,es,fi,he,zh-hant"),function(){function i(b,e,d,h,g){return g.replace(/([a-z])\1*/ig,function(c){var a,f,d=c.charAt(0),c=c.length,l=["abbr",
"wide","narrow"];switch(d){case "G":a=e.eraAbbr[0];break;case "y":a=String(b.getFullYear());break;case "M":a=b.getMonth();c<3?(a+=1,f=!0):(d=["months-format",l[c-3]].join("-"),a=e[d][a]);break;case "d":a=b.getDate(!0);f=!0;break;case "E":a=b.getDay();c<3?(a+=1,f=!0):(d=["days-format",l[c-3]].join("-"),a=e[d][a]);break;case "a":a=b.getHours()<12?"am":"pm";a=e["dayPeriods-format-wide-"+a];break;case "h":case "H":case "K":case "k":f=b.getHours();switch(d){case "h":a=f%12||12;break;case "H":a=f;break;
case "K":a=f%12;break;case "k":a=f||24}f=!0;break;case "m":a=b.getMinutes();f=!0;break;case "s":a=b.getSeconds();f=!0;break;case "S":a=Math.round(b.getMilliseconds()*Math.pow(10,c-3));f=!0;break;case "z":if(a=dojo.date.getTimezoneName(b.toGregorian()))break;c=4;case "Z":a=b.toGregorian().getTimezoneOffset();a=[a<=0?"+":"-",dojo.string.pad(Math.floor(Math.abs(a)/60),2),dojo.string.pad(Math.abs(a)%60,2)];c==4&&(a.splice(0,0,"GMT"),a.splice(3,0,":"));a=a.join("");break;default:throw Error("dojox.date.islamic.locale.formatPattern: invalid pattern char: "+
g);}f&&(a=dojo.string.pad(a,c));return a})}function k(b,e,d,h){var g=function(a){return a},e=e||g,d=d||g,h=h||g,c=b.match(/(''|[^'])+/g),a=b.charAt(0)=="'";dojo.forEach(c,function(b,g){b?(c[g]=(a?d:e)(b),a=!a):c[g]=""});return h(c.join(""))}function j(b,e,d,h){h=dojo.regexp.escapeString(h);dojo.i18n.normalizeLocale(d.locale);return h.replace(/([a-z])\1*/ig,function(g){var c;c=g.charAt(0);var a=g.length,f="";d.strict?a>1&&(f="0{"+(a-1)+"}"):f="0?";switch(c){case "y":c="\\d+";break;case "M":c=a>2?"\\S+ ?\\S+":
f+"[1-9]|1[0-2]";break;case "d":c="[12]\\d|"+f+"[1-9]|3[01]";break;case "E":c="\\S+";break;case "h":c=f+"[1-9]|1[0-2]";break;case "k":c=f+"\\d|1[01]";break;case "H":c=f+"\\d|1\\d|2[0-3]";break;case "K":c=f+"[1-9]|1\\d|2[0-4]";break;case "m":case "s":c=f+"\\d|[0-5]\\d";break;case "S":c="\\d{"+a+"}";break;case "a":a=d.am||e["dayPeriods-format-wide-am"];f=d.pm||e["dayPeriods-format-wide-pm"];d.strict?c=a+"|"+f:(c=a+"|"+f,a!=a.toLowerCase()&&(c+="|"+a.toLowerCase()),f!=f.toLowerCase()&&(c+="|"+f.toLowerCase()));
break;default:c=".*"}b&&b.push(g);return"("+c+")"}).replace(/[\xa0 ]/g,"[\\s\\xa0]")}dojox.date.islamic.locale.format=function(b,e){var e=e||{},d=dojo.i18n.normalizeLocale(e.locale),h=e.formatLength||"short",g=dojox.date.islamic.locale._getIslamicBundle(d),c=[],d=dojo.hitch(this,i,b,g,d,e.fullYear);if(e.selector=="year")return b.getFullYear();if(e.selector!="time"){var a=e.datePattern||g["dateFormat-"+h];a&&c.push(k(a,d))}e.selector!="date"&&(h=e.timePattern||g["timeFormat-"+h])&&c.push(k(h,d));return c.join(" ")};
dojox.date.islamic.locale.regexp=function(b){return dojox.date.islamic.locale._parseInfo(b).regexp};dojox.date.islamic.locale._parseInfo=function(b){var b=b||{},e=dojo.i18n.normalizeLocale(b.locale),e=dojox.date.islamic.locale._getIslamicBundle(e),d=b.formatLength||"short",h=b.datePattern||e["dateFormat-"+d],d=b.timePattern||e["timeFormat-"+d],g=[];return{regexp:k(b.selector=="date"?h:b.selector=="time"?d:typeof d=="undefined"?h:h+" "+d,dojo.hitch(this,j,g,e,b)),tokens:g,bundle:e}};dojox.date.islamic.locale.parse=
function(b,e){b=b.replace(/[\u200E\u200F\u202A\u202E]/g,"");e||(e={});var d=dojox.date.islamic.locale._parseInfo(e),h=d.tokens,g=d.bundle,d=d.regexp.replace(/[\u200E\u200F\u202A\u202E]/g,""),d=RegExp("^"+d+"$"),c=d.exec(b);dojo.i18n.normalizeLocale(e.locale);if(!c)return console.debug("dojox.date.islamic.locale.parse: value  "+b+" doesn't match pattern   "+d),null;var a=[1389,0,1,0,0,0,0],f="",j=["abbr","wide","narrow"];dojo.every(c,function(b,d){if(!d)return!0;var c=h[d-1],i=c.length;switch(c.charAt(0)){case "y":a[0]=
Number(b);break;case "M":if(i>2){if(c=g["months-format-"+j[i-3]].concat(),e.strict||(b=b.replace(".","").toLowerCase(),c=dojo.map(c,function(a){return a?a.replace(".","").toLowerCase():a})),b=dojo.indexOf(c,b),b==-1)return!1}else b--;a[1]=Number(b);break;case "D":a[1]=0;case "d":a[2]=Number(b);break;case "a":c=e.am||g["dayPeriods-format-wide-am"];i=e.pm||g["dayPeriods-format-wide-pm"];if(!e.strict)var k=/\./g,b=b.replace(k,"").toLowerCase(),c=c.replace(k,"").toLowerCase(),i=i.replace(k,"").toLowerCase();
if(e.strict&&b!=c&&b!=i)return!1;f=b==i?"p":b==c?"a":"";break;case "K":b==24&&(b=0);case "h":case "H":case "k":a[3]=Number(b);break;case "m":a[4]=Number(b);break;case "s":a[5]=Number(b);break;case "S":a[6]=Number(b)}return!0});d=+a[3];f==="p"&&d<12?a[3]=d+12:f==="a"&&d==12&&(a[3]=0);return new dojox.date.islamic.Date(a[0],a[1],a[2],a[3],a[4],a[5],a[6])}}(),function(){var i=[];dojox.date.islamic.locale.addCustomFormats=function(k,j){i.push({pkg:k,name:j})};dojox.date.islamic.locale._getIslamicBundle=
function(k){var j={};dojo.forEach(i,function(b){b=dojo.i18n.getLocalization(b.pkg,b.name,k);j=dojo.mixin(j,b)},this);return j}}(),dojox.date.islamic.locale.addCustomFormats("dojo.cldr","islamic"),dojox.date.islamic.locale.getNames=function(i,k,j,b){var e,b=dojox.date.islamic.locale._getIslamicBundle(b),i=[i,j,k];j=="standAlone"&&(j=i.join("-"),e=b[j],e[0]==1&&(e=void 0));i[1]="format";return(e||b[i.join("-")]).concat()},dojox.date.islamic.locale.weekDays=dojox.date.islamic.locale.getNames("days",
"wide","format"),dojox.date.islamic.locale.months=dojox.date.islamic.locale.getNames("months","wide","format");