/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.axis2d.Invisible"]||(dojo._hasResource["dojox.charting.axis2d.Invisible"]=!0,dojo.provide("dojox.charting.axis2d.Invisible"),dojo.require("dojox.charting.scaler.linear"),dojo.require("dojox.charting.axis2d.common"),dojo.require("dojox.charting.axis2d.Base"),dojo.require("dojo.string"),dojo.require("dojox.gfx"),dojo.require("dojox.lang.functional"),dojo.require("dojox.lang.utils"),function(){var g=dojox.lang.functional,h=dojox.lang.utils,j=dojox.gfx,i=dojox.charting.scaler.linear;
dojo.declare("dojox.charting.axis2d.Invisible",dojox.charting.axis2d.Base,{defaultParams:{vertical:!1,fixUpper:"none",fixLower:"none",natural:!1,leftBottom:!0,includeZero:!1,fixed:!0,majorLabels:!0,minorTicks:!0,minorLabels:!0,microTicks:!1,rotation:0},optionalParams:{min:0,max:1,from:0,to:1,majorTickStep:4,minorTickStep:2,microTickStep:1,labels:[],labelFunc:null,maxLabelSize:0,maxLabelCharCount:0,trailingSymbol:null},constructor:function(c,d){this.opt=dojo.clone(this.defaultParams);h.updateWithObject(this.opt,
d);h.updateWithPattern(this.opt,d,this.optionalParams)},dependOnData:function(){return!("min"in this.opt)||!("max"in this.opt)},clear:function(){delete this.scaler;delete this.ticks;this.dirty=!0;return this},initialized:function(){return"scaler"in this&&!(this.dirty&&this.dependOnData())},setWindow:function(c,d){this.scale=c;this.offset=d;return this.clear()},getWindowScale:function(){return"scale"in this?this.scale:1},getWindowOffset:function(){return"offset"in this?this.offset:0},_groupLabelWidth:function(c,
d,f){if(!c.length)return 0;dojo.isObject(c[0])&&(c=g.map(c,function(b){return b.text}));f&&(c=g.map(c,function(b){return dojo.trim(b).length==0?"":b.substring(0,f)+this.trailingSymbol},this));c=c.join("<br>");return dojox.gfx._base._getTextBox(c,{font:d}).w||0},calculate:function(c,d,f,b){if(this.initialized())return this;var a=this.opt;this.labels="labels"in a?a.labels:b;this.scaler=i.buildScaler(c,d,f,a);b=this.scaler.bounds;if("scale"in this){a.from=b.lower+this.offset;a.to=(b.upper-b.lower)/this.scale+
a.from;if(!isFinite(a.from)||isNaN(a.from)||!isFinite(a.to)||isNaN(a.to)||a.to-a.from>=b.upper-b.lower)delete a.from,delete a.to,delete this.scale,delete this.offset;else{if(a.from<b.lower)a.to+=b.lower-a.from,a.from=b.lower;else if(a.to>b.upper)a.from+=b.upper-a.to,a.to=b.upper;this.offset=a.from-b.lower}this.scaler=i.buildScaler(c,d,f,a);b=this.scaler.bounds;this.scale==1&&this.offset==0&&(delete this.scale,delete this.offset)}var d=this.chart.theme.axis,e=0,c=a.rotation%360,f=(d=a.font||d.majorTick&&
d.majorTick.font||d.tick&&d.tick.font)?j.normalizedLength(j.splitFontString(d).size):0,g=Math.abs(Math.cos(c*Math.PI/180)),h=Math.abs(Math.sin(c*Math.PI/180));c<0&&(c+=360);if(f){if(this.vertical?c!=0&&c!=180:c!=90&&c!=270){if(this.labels)e=this._groupLabelWidth(this.labels,d,a.maxLabelCharCount);else{var k=Math.ceil(Math.log(Math.max(Math.abs(b.from),Math.abs(b.to)))/Math.LN10),e=[];(b.from<0||b.to<0)&&e.push("-");e.push(dojo.string.rep("9",k));b=Math.floor(Math.log(b.to-b.from)/Math.LN10);b>0&&
(e.push("."),e.push(dojo.string.rep("9",b)));e=dojox.gfx._base._getTextBox(e.join(""),{font:d}).w}e=a.maxLabelSize?Math.min(a.maxLabelSize,e):e}else e=f;switch(c){case 0:case 90:case 180:case 270:break;default:e=Math.min(Math.sqrt(e*e+f*f),this.vertical?f*g+e*h:e*g+f*h)}}this.scaler.minMinorStep=e+4;this.ticks=i.buildTicks(this.scaler,a);return this},getScaler:function(){return this.scaler},getTicks:function(){return this.ticks}})}());