/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._HasDropDown"]||(dojo._hasResource["dijit._HasDropDown"]=!0,dojo.provide("dijit._HasDropDown"),dojo.require("dijit._Widget"),dojo.declare("dijit._HasDropDown",null,{_buttonNode:null,_arrowWrapperNode:null,_popupStateNode:null,_aroundNode:null,dropDown:null,autoWidth:!0,forceWidth:!1,maxHeight:0,dropDownPosition:["below","above"],_stopClickEvents:!0,_onDropDownMouseDown:function(a){if(!this.disabled&&!this.readOnly)dojo.stopEvent(a),this._docHandler=this.connect(dojo.doc,"onmouseup",
"_onDropDownMouseUp"),this.toggleDropDown()},_onDropDownMouseUp:function(a){a&&this._docHandler&&this.disconnect(this._docHandler);var d=this.dropDown,f=!1;if(a&&this._opened){var b=dojo.position(this._buttonNode,!0);if(!(a.pageX>=b.x&&a.pageX<=b.x+b.w)||!(a.pageY>=b.y&&a.pageY<=b.y+b.h)){for(b=a.target;b&&!f;)dojo.hasClass(b,"dijitPopup")?f=!0:b=b.parentNode;if(f){b=a.target;if(d.onItemClick){for(var c;b&&!(c=dijit.byNode(b));)b=b.parentNode;if(c&&c.onClick&&c.getParent)c.getParent().onItemClick(c,
a)}return}}}this._opened&&d.focus&&d.autoFocus!==!1&&window.setTimeout(dojo.hitch(d,"focus"),1)},_onDropDownClick:function(a){this._stopClickEvents&&dojo.stopEvent(a)},buildRendering:function(){this.inherited(arguments);this._buttonNode=this._buttonNode||this.focusNode||this.domNode;this._popupStateNode=this._popupStateNode||this.focusNode||this._buttonNode;var a={after:this.isLeftToRight()?"Right":"Left",before:this.isLeftToRight()?"Left":"Right",above:"Up",below:"Down",left:"Left",right:"Right"}[this.dropDownPosition[0]]||
this.dropDownPosition[0]||"Down";dojo.addClass(this._arrowWrapperNode||this._buttonNode,"dijit"+a+"ArrowButton")},postCreate:function(){this.inherited(arguments);this.connect(this._buttonNode,"onmousedown","_onDropDownMouseDown");this.connect(this._buttonNode,"onclick","_onDropDownClick");this.connect(this.focusNode,"onkeypress","_onKey");this.connect(this.focusNode,"onkeyup","_onKeyUp")},destroy:function(){this.dropDown&&(this.dropDown._destroyed||this.dropDown.destroyRecursive(),delete this.dropDown);
this.inherited(arguments)},_onKey:function(a){if(!this.disabled&&!this.readOnly){var d=this.dropDown,f=a.target;if(d&&this._opened&&d.handleKey&&d.handleKey(a)===!1)dojo.stopEvent(a);else if(d&&this._opened&&a.charOrCode==dojo.keys.ESCAPE)this.closeDropDown(),dojo.stopEvent(a);else if(!this._opened&&(a.charOrCode==dojo.keys.DOWN_ARROW||(a.charOrCode==dojo.keys.ENTER||a.charOrCode==" ")&&((f.tagName||"").toLowerCase()!=="input"||f.type&&f.type.toLowerCase()!=="text")))this._toggleOnKeyUp=!0,dojo.stopEvent(a)}},
_onKeyUp:function(){if(this._toggleOnKeyUp){delete this._toggleOnKeyUp;this.toggleDropDown();var a=this.dropDown;a&&a.focus&&setTimeout(dojo.hitch(a,"focus"),1)}},_onBlur:function(){this.closeDropDown(dijit._curFocus&&this.dropDown&&dojo.isDescendant(dijit._curFocus,this.dropDown.domNode));this.inherited(arguments)},isLoaded:function(){return!0},loadDropDown:function(a){a()},toggleDropDown:function(){!this.disabled&&!this.readOnly&&(this._opened?this.closeDropDown():this.isLoaded()?this.openDropDown():
this.loadDropDown(dojo.hitch(this,"openDropDown")))},openDropDown:function(){var a=this.dropDown,d=a.domNode,f=this._aroundNode||this.domNode,b=this;if(!this._preparedNode){this._preparedNode=!0;if(d.style.width)this._explicitDDWidth=!0;if(d.style.height)this._explicitDDHeight=!0}if(this.maxHeight||this.forceWidth||this.autoWidth){var c={display:"",visibility:"hidden"};if(!this._explicitDDWidth)c.width="";if(!this._explicitDDHeight)c.height="";dojo.style(d,c);c=this.maxHeight;if(c==-1)var c=dojo.window.getBox(),
e=dojo.position(f,!1),c=Math.floor(Math.max(e.y,c.h-(e.y+e.h)));a.startup&&!a._started&&a.startup();dijit.popup.moveOffScreen(a);var e=dojo._getMarginSize(d),g=c&&e.h>c;dojo.style(d,{overflowX:"hidden",overflowY:g?"auto":"hidden"});g?(e.h=c,"w"in e&&(e.w+=16)):delete e.h;this.forceWidth?e.w=f.offsetWidth:this.autoWidth?e.w=Math.max(e.w,f.offsetWidth):delete e.w;dojo.isFunction(a.resize)?a.resize(e):dojo.marginBox(d,e)}a=dijit.popup.open({parent:this,popup:a,around:f,orient:dijit.getPopupAroundAlignment(this.dropDownPosition&&
this.dropDownPosition.length?this.dropDownPosition:["below"],this.isLeftToRight()),onExecute:function(){b.closeDropDown(!0)},onCancel:function(){b.closeDropDown(!0)},onClose:function(){dojo.attr(b._popupStateNode,"popupActive",!1);dojo.removeClass(b._popupStateNode,"dijitHasDropDownOpen");b._opened=!1}});dojo.attr(this._popupStateNode,"popupActive","true");dojo.addClass(b._popupStateNode,"dijitHasDropDownOpen");this._opened=!0;return a},closeDropDown:function(a){if(this._opened)a&&this.focus(),dijit.popup.close(this.dropDown),
this._opened=!1}}));