/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._WidgetBase"]||(dojo._hasResource["dijit._WidgetBase"]=!0,dojo.provide("dijit._WidgetBase"),dojo.require("dijit._base.manager"),dojo.require("dojo.Stateful"),function(){dojo.declare("dijit._WidgetBase",dojo.Stateful,{id:"",lang:"",dir:"","class":"",style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,attributeMap:{id:"",dir:"",lang:"","class":"",style:"",title:""},_blankGif:(dojo.config.blankGif||dojo.moduleUrl("dojo","resources/blank.gif")).toString(),
postscript:function(a,b){this.create(a,b)},create:function(a,b){this.srcNodeRef=dojo.byId(b);this._connects=[];this._subscribes=[];if(this.srcNodeRef&&typeof this.srcNodeRef.id=="string")this.id=this.srcNodeRef.id;if(a)this.params=a,dojo._mixin(this,a);this.postMixInProperties();if(!this.id)this.id=dijit.getUniqueId(this.declaredClass.replace(/\./g,"_"));dijit.registry.add(this);this.buildRendering();if(this.domNode){this._applyAttributes();var c=this.srcNodeRef;c&&c.parentNode&&this.domNode!==c&&
c.parentNode.replaceChild(this.domNode,c)}this.domNode&&this.domNode.setAttribute("widgetId",this.id);this.postCreate();this.srcNodeRef&&!this.srcNodeRef.parentNode&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a=function(a,b){(b.params&&a in b.params||b[a])&&b.set(a,b[a])},b;for(b in this.attributeMap)a(b,this);dojo.forEach(this._getSetterAttributes(),function(b){b in this.attributeMap||a(b,this)},this)},_getSetterAttributes:function(){var a=this.constructor;if(!a._setterAttrs){var b=
a._setterAttrs=[],c,e=a.prototype,d;for(d in e)dojo.isFunction(e[d])&&(c=d.match(/^_set([a-zA-Z]*)Attr$/))&&c[1]&&b.push(c[1].charAt(0).toLowerCase()+c[1].substr(1))}return a._setterAttrs},postMixInProperties:function(){},buildRendering:function(){if(!this.domNode)this.domNode=this.srcNodeRef||dojo.create("div");if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(dojo.map(a,function(a){return a+"Rtl"})));dojo.addClass(this.domNode,a)}},postCreate:function(){},startup:function(){this._started=
!0},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){this._beingDestroyed=!0;this.uninitialize();var b=dojo,c=b.forEach,e=b.unsubscribe;c(this._connects,function(a){c(a,b.disconnect)});c(this._subscribes,function(a){e(a)});c(this._supportingWidgets||[],function(a){a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy()});this.destroyRendering(a);dijit.registry.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&
(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?dojo.removeAttr(this.domNode,"widgetId"):dojo.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||dojo.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){dojo.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setClassAttr:function(a){dojo.replaceClass(this[this.attributeMap["class"]||"domNode"],a,this["class"]);this._set("class",
a)},_setStyleAttr:function(a){var b=this[this.attributeMap.style||"domNode"];dojo.isObject(a)?dojo.style(b,a):b.style.cssText?b.style.cssText+="; "+a:b.style.cssText=a;this._set("style",a)},_attrToDom:function(a,b){var c=this.attributeMap[a];dojo.forEach(dojo.isArray(c)?c:[c],function(c){var d=this[c.node||c||"domNode"];switch(c.type||"attribute"){case "attribute":dojo.isFunction(b)&&(b=dojo.hitch(this,b));c=c.attribute?c.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;dojo.attr(d,c,b);break;
case "innerText":d.innerHTML="";d.appendChild(dojo.doc.createTextNode(b));break;case "innerHTML":d.innerHTML=b;break;case "class":dojo.replaceClass(d,b,this[a])}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?this[b.g]():this[a]},set:function(a,b){if(typeof a==="object"){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);if(this[c.s])var e=this[c.s].apply(this,Array.prototype.slice.call(arguments,1));else a in this.attributeMap&&this._attrToDom(a,b),this._set(a,
b);return e||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.charAt(0).toUpperCase()+a.substr(1);return b[a]={n:a+"Node",s:"_set"+c+"Attr",g:"_get"+c+"Attr"}},_set:function(a,b){var c=this[a];this[a]=b;this._watchCallbacks&&this._created&&b!==c&&this._watchCallbacks(a,c,b)},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getDescendants:function(){return this.containerNode?dojo.query("[widgetId]",this.containerNode).map(dijit.byNode):
[]},getChildren:function(){return this.containerNode?dijit.findWidgets(this.containerNode):[]},connect:function(a,b,c){a=[dojo._connect(a,b,this,c)];this._connects.push(a);return a},disconnect:function(a){for(var b=0;b<this._connects.length;b++)if(this._connects[b]==a){dojo.forEach(a,dojo.disconnect);this._connects.splice(b,1);break}},subscribe:function(a,b){var c=dojo.subscribe(a,this,b);this._subscribes.push(c);return c},unsubscribe:function(a){for(var b=0;b<this._subscribes.length;b++)if(this._subscribes[b]==
a){dojo.unsubscribe(a);this._subscribes.splice(b,1);break}},isLeftToRight:function(){return this.dir?this.dir=="ltr":dojo._isBodyLtr()},placeAt:function(a,b){a.declaredClass&&a.addChild?a.addChild(this,b):dojo.place(this.domNode,a,b);return this}})}());