/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.Calendar"]||(dojo._hasResource["dijit.Calendar"]=!0,dojo.provide("dijit.Calendar"),dojo.require("dojo.cldr.supplemental"),dojo.require("dojo.date"),dojo.require("dojo.date.locale"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit._CssStateMixin"),dojo.require("dijit.form.DropDownButton"),dojo.declare("dijit.Calendar",[dijit._Widget,dijit._Templated,dijit._CssStateMixin],{templateString:dojo.cache("dijit","templates/Calendar.html",'<table cellspacing="0" cellpadding="0" class="dijitCalendarContainer" role="grid" dojoAttachEvent="onkeypress: _onKeyPress" aria-labelledby="${id}_year">\n\t<thead>\n\t\t<tr class="dijitReset dijitCalendarMonthContainer" valign="top">\n\t\t\t<th class=\'dijitReset dijitCalendarArrow\' dojoAttachPoint="decrementMonth">\n\t\t\t\t<img src="${_blankGif}" alt="" class="dijitCalendarIncrementControl dijitCalendarDecrease" role="presentation"/>\n\t\t\t\t<span dojoAttachPoint="decreaseArrowNode" class="dijitA11ySideArrow">-</span>\n\t\t\t</th>\n\t\t\t<th class=\'dijitReset\' colspan="5">\n\t\t\t\t<div dojoType="dijit.form.DropDownButton" dojoAttachPoint="monthDropDownButton"\n\t\t\t\t\tid="${id}_mddb" tabIndex="-1">\n\t\t\t\t</div>\n\t\t\t</th>\n\t\t\t<th class=\'dijitReset dijitCalendarArrow\' dojoAttachPoint="incrementMonth">\n\t\t\t\t<img src="${_blankGif}" alt="" class="dijitCalendarIncrementControl dijitCalendarIncrease" role="presentation"/>\n\t\t\t\t<span dojoAttachPoint="increaseArrowNode" class="dijitA11ySideArrow">+</span>\n\t\t\t</th>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th class="dijitReset dijitCalendarDayLabelTemplate" role="columnheader"><span class="dijitCalendarDayLabel"></span></th>\n\t\t</tr>\n\t</thead>\n\t<tbody dojoAttachEvent="onclick: _onDayClick, onmouseover: _onDayMouseOver, onmouseout: _onDayMouseOut, onmousedown: _onDayMouseDown, onmouseup: _onDayMouseUp" class="dijitReset dijitCalendarBodyContainer">\n\t\t<tr class="dijitReset dijitCalendarWeekTemplate" role="row">\n\t\t\t<td class="dijitReset dijitCalendarDateTemplate" role="gridcell"><span class="dijitCalendarDateLabel"></span></td>\n\t\t</tr>\n\t</tbody>\n\t<tfoot class="dijitReset dijitCalendarYearContainer">\n\t\t<tr>\n\t\t\t<td class=\'dijitReset\' valign="top" colspan="7">\n\t\t\t\t<h3 class="dijitCalendarYearLabel">\n\t\t\t\t\t<span dojoAttachPoint="previousYearLabelNode" class="dijitInline dijitCalendarPreviousYear"></span>\n\t\t\t\t\t<span dojoAttachPoint="currentYearLabelNode" class="dijitInline dijitCalendarSelectedYear" id="${id}_year"></span>\n\t\t\t\t\t<span dojoAttachPoint="nextYearLabelNode" class="dijitInline dijitCalendarNextYear"></span>\n\t\t\t\t</h3>\n\t\t\t</td>\n\t\t</tr>\n\t</tfoot>\n</table>\n'),
widgetsInTemplate:!0,value:new Date(""),datePackage:"dojo.date",dayWidth:"narrow",tabIndex:"0",currentFocus:new Date,baseClass:"dijitCalendar",cssStateNodes:{decrementMonth:"dijitCalendarArrow",incrementMonth:"dijitCalendarArrow",previousYearLabelNode:"dijitCalendarPreviousYear",nextYearLabelNode:"dijitCalendarNextYear"},_isValidDate:function(a){return a&&!isNaN(a)&&typeof a=="object"&&a.toString()!=this.constructor.prototype.value.toString()},setValue:function(a){dojo.deprecated("dijit.Calendar:setValue() is deprecated.  Use set('value', ...) instead.",
"","2.0");this.set("value",a)},_getValueAttr:function(){var a=new this.dateClassObj(this.value);a.setHours(0,0,0,0);a.getDate()<this.value.getDate()&&(a=this.dateFuncObj.add(a,"hour",1));return a},_setValueAttr:function(a,b){a&&(a=new this.dateClassObj(a));if(this._isValidDate(a)){if(!this._isValidDate(this.value)||this.dateFuncObj.compare(a,this.value))if(a.setHours(1,0,0,0),!this.isDisabledDate(a,this.lang)&&(this._set("value",a),this.set("currentFocus",a),b||typeof b=="undefined"))this.onChange(this.get("value")),
this.onValueSelected(this.get("value"))}else this._set("value",null),this.set("currentFocus",this.currentFocus)},_setText:function(a,b){for(;a.firstChild;)a.removeChild(a.firstChild);a.appendChild(dojo.doc.createTextNode(b))},_populateGrid:function(){var a=new this.dateClassObj(this.currentFocus);a.setDate(1);var b=a.getDay(),c=this.dateFuncObj.getDaysInMonth(a),d=this.dateFuncObj.getDaysInMonth(this.dateFuncObj.add(a,"month",-1)),g=new this.dateClassObj,l=dojo.cldr.supplemental.getFirstDayOfWeek(this.lang);
l>b&&(l-=7);dojo.query(".dijitCalendarDateTemplate",this.domNode).forEach(function(i,h){h+=l;var e=new this.dateClassObj(a),j,f="dijitCalendar",k=0;h<b?(j=d-b+h+1,k=-1,f+="Previous"):h>=b+c?(j=h-b-c+1,k=1,f+="Next"):(j=h-b+1,f+="Current");k&&(e=this.dateFuncObj.add(e,"month",k));e.setDate(j);this.dateFuncObj.compare(e,g,"date")||(f="dijitCalendarCurrentDate "+f);this._isSelectedDate(e,this.lang)&&(f="dijitCalendarSelectedDate "+f);this.isDisabledDate(e,this.lang)&&(f="dijitCalendarDisabledDate "+
f);(j=this.getClassForDate(e,this.lang))&&(f=j+" "+f);i.className=f+"Month dijitCalendarDateTemplate";i.dijitDateValue=e.valueOf();dojo.attr(i,"dijitDateValue",e.valueOf());f=dojo.query(".dijitCalendarDateLabel",i)[0];e=e.getDateLocalized?e.getDateLocalized(this.lang):e.getDate();this._setText(f,e)},this);var i=this.dateLocaleModule.getNames("months","wide","standAlone",this.lang,a);this.monthDropDownButton.dropDown.set("months",i);this.monthDropDownButton.containerNode.innerHTML=(dojo.isIE==6?"":
"<div class='dijitSpacer'>"+this.monthDropDownButton.dropDown.domNode.innerHTML+"</div>")+"<div class='dijitCalendarMonthLabel dijitCalendarCurrentMonthLabel'>"+i[a.getMonth()]+"</div>";var h=a.getFullYear()-1,m=new this.dateClassObj;dojo.forEach(["previous","current","next"],function(a){m.setFullYear(h++);this._setText(this[a+"YearLabelNode"],this.dateLocaleModule.format(m,{selector:"year",locale:this.lang}))},this)},goToToday:function(){this.set("value",new this.dateClassObj)},constructor:function(a){this.dateClassObj=
dojo.getObject(a.datePackage&&a.datePackage!="dojo.date"?a.datePackage+".Date":"Date",!1);this.datePackage=a.datePackage||this.datePackage;this.dateFuncObj=dojo.getObject(this.datePackage,!1);this.dateLocaleModule=dojo.getObject(this.datePackage+".locale",!1)},postMixInProperties:function(){isNaN(this.value)&&delete this.value;this.inherited(arguments)},buildRendering:function(){this.inherited(arguments);dojo.setSelectable(this.domNode,!1);var a=dojo.hitch(this,function(a,b){for(var c=dojo.query(a,
this.domNode)[0],d=0;d<b;d++)c.parentNode.appendChild(c.cloneNode(!0))});a(".dijitCalendarDayLabelTemplate",6);a(".dijitCalendarDateTemplate",6);a(".dijitCalendarWeekTemplate",5);var b=this.dateLocaleModule.getNames("days",this.dayWidth,"standAlone",this.lang),c=dojo.cldr.supplemental.getFirstDayOfWeek(this.lang);dojo.query(".dijitCalendarDayLabel",this.domNode).forEach(function(a,d){this._setText(a,b[(d+c)%7])},this);a=new this.dateClassObj(this.currentFocus);this.monthDropDownButton.dropDown=new dijit.Calendar._MonthDropDown({id:this.id+
"_mdd",onChange:dojo.hitch(this,"_onMonthSelect")});this.set("currentFocus",a,!1);var d=this,a=function(a,b,c){d._connects.push(dijit.typematic.addMouseListener(d[a],d,function(a){a>=0&&d._adjustDisplay(b,c)},0.8,500))};a("incrementMonth","month",1);a("decrementMonth","month",-1);a("nextYearLabelNode","year",1);a("previousYearLabelNode","year",-1)},_adjustDisplay:function(a,b){this._setCurrentFocusAttr(this.dateFuncObj.add(this.currentFocus,a,b))},_setCurrentFocusAttr:function(a,b){var c=this.currentFocus,
c=c?dojo.query("[dijitDateValue="+c.valueOf()+"]",this.domNode)[0]:null,a=new this.dateClassObj(a);a.setHours(1,0,0,0);this._set("currentFocus",a);this._populateGrid();var d=dojo.query("[dijitDateValue="+a.valueOf()+"]",this.domNode)[0];d.setAttribute("tabIndex",this.tabIndex);(this._focused||b)&&d.focus();c&&c!=d&&(dojo.isWebKit?c.setAttribute("tabIndex","-1"):c.removeAttribute("tabIndex"))},focus:function(){this._setCurrentFocusAttr(this.currentFocus,!0)},_onMonthSelect:function(a){this.currentFocus=
this.dateFuncObj.add(this.currentFocus,"month",a-this.currentFocus.getMonth());this._populateGrid()},_onDayClick:function(a){dojo.stopEvent(a);for(a=a.target;a&&!a.dijitDateValue;a=a.parentNode);a&&!dojo.hasClass(a,"dijitCalendarDisabledDate")&&this.set("value",a.dijitDateValue)},_onDayMouseOver:function(a){if((a=dojo.hasClass(a.target,"dijitCalendarDateLabel")?a.target.parentNode:a.target)&&(a.dijitDateValue||a==this.previousYearLabelNode||a==this.nextYearLabelNode))dojo.addClass(a,"dijitCalendarHoveredDate"),
this._currentNode=a},_onDayMouseOut:function(a){if(this._currentNode&&!(a.relatedTarget&&a.relatedTarget.parentNode==this._currentNode))a="dijitCalendarHoveredDate",dojo.hasClass(this._currentNode,"dijitCalendarActiveDate")&&(a+=" dijitCalendarActiveDate"),dojo.removeClass(this._currentNode,a),this._currentNode=null},_onDayMouseDown:function(a){if((a=a.target.parentNode)&&a.dijitDateValue)dojo.addClass(a,"dijitCalendarActiveDate"),this._currentNode=a},_onDayMouseUp:function(a){(a=a.target.parentNode)&&
a.dijitDateValue&&dojo.removeClass(a,"dijitCalendarActiveDate")},handleKey:function(a){var b=dojo.keys,c=-1,d,g=this.currentFocus;switch(a.keyCode){case b.RIGHT_ARROW:c=1;case b.LEFT_ARROW:d="day";this.isLeftToRight()||(c*=-1);break;case b.DOWN_ARROW:c=1;case b.UP_ARROW:d="week";break;case b.PAGE_DOWN:c=1;case b.PAGE_UP:d=a.ctrlKey||a.altKey?"year":"month";break;case b.END:g=this.dateFuncObj.add(g,"month",1),d="day";case b.HOME:g=new this.dateClassObj(g);g.setDate(1);break;case b.ENTER:case b.SPACE:this.set("value",
this.currentFocus);break;default:return!0}d&&(g=this.dateFuncObj.add(g,d,c));this._setCurrentFocusAttr(g);return!1},_onKeyPress:function(a){this.handleKey(a)||dojo.stopEvent(a)},onValueSelected:function(){},onChange:function(){},_isSelectedDate:function(a){return this._isValidDate(this.value)&&!this.dateFuncObj.compare(a,this.value,"date")},isDisabledDate:function(){},getClassForDate:function(){}}),dojo.declare("dijit.Calendar._MonthDropDown",[dijit._Widget,dijit._Templated],{months:[],templateString:"<div class='dijitCalendarMonthMenu dijitMenu' dojoAttachEvent='onclick:_onClick,onmouseover:_onMenuHover,onmouseout:_onMenuHover'></div>",
_setMonthsAttr:function(a){this.domNode.innerHTML=dojo.map(a,function(a,c){return a?"<div class='dijitCalendarMonthLabel' month='"+c+"'>"+a+"</div>":""}).join("")},_onClick:function(a){this.onChange(dojo.attr(a.target,"month"))},onChange:function(){},_onMenuHover:function(a){dojo.toggleClass(a.target,"dijitCalendarMonthLabelHover",a.type=="mouseover")}}));