/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dijit.Dialog"])dojo._hasResource["dijit.Dialog"]=!0,dojo.provide("dijit.Dialog"),dojo.require("dojo.dnd.move"),dojo.require("dojo.dnd.TimedMoveable"),dojo.require("dojo.fx"),dojo.require("dojo.window"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit._CssStateMixin"),dojo.require("dijit.form._FormMixin"),dojo.require("dijit._DialogMixin"),dojo.require("dijit.DialogUnderlay"),dojo.require("dijit.layout.ContentPane"),dojo.requireLocalization("dijit",
"common",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.require("dijit.TooltipDialog"),dojo.declare("dijit._DialogBase",[dijit._Templated,dijit.form._FormMixin,dijit._DialogMixin,dijit._CssStateMixin],{templateString:dojo.cache("dijit","templates/Dialog.html",'<div class="dijitDialog" role="dialog" aria-labelledby="${id}_title">\n\t<div dojoAttachPoint="titleBar" class="dijitDialogTitleBar">\n\t<span dojoAttachPoint="titleNode" class="dijitDialogTitle" id="${id}_title"></span>\n\t<span dojoAttachPoint="closeButtonNode" class="dijitDialogCloseIcon" dojoAttachEvent="ondijitclick: onCancel" title="${buttonCancel}" role="button" tabIndex="-1">\n\t\t<span dojoAttachPoint="closeText" class="closeText" title="${buttonCancel}">x</span>\n\t</span>\n\t</div>\n\t\t<div dojoAttachPoint="containerNode" class="dijitDialogPaneContent"></div>\n</div>\n'),
baseClass:"dijitDialog",cssStateNodes:{closeButtonNode:"dijitDialogCloseIcon"},attributeMap:dojo.delegate(dijit._Widget.prototype.attributeMap,{title:[{node:"titleNode",type:"innerHTML"},{node:"titleBar",type:"attribute"}],"aria-describedby":""}),open:!1,duration:dijit.defaultDuration,refocus:!0,autofocus:!0,_firstFocusItem:null,_lastFocusItem:null,doLayout:!1,draggable:!0,"aria-describedby":"",postMixInProperties:function(){var a=dojo.i18n.getLocalization("dijit","common");dojo.mixin(this,a);this.inherited(arguments)},
postCreate:function(){dojo.style(this.domNode,{display:"none",position:"absolute"});dojo.body().appendChild(this.domNode);this.inherited(arguments);this.connect(this,"onExecute","hide");this.connect(this,"onCancel","hide");this._modalconnects=[]},onLoad:function(){this._position();this.autofocus&&dijit._DialogLevelManager.isTop(this)&&(this._getFocusItems(this.domNode),dijit.focus(this._firstFocusItem));this.inherited(arguments)},_endDrag:function(a){if(a&&a.node&&a.node===this.domNode)this._relativePosition=
dojo.position(a.node)},_setup:function(){var a=this.domNode;this.titleBar&&this.draggable?(this._moveable=dojo.isIE==6?new dojo.dnd.TimedMoveable(a,{handle:this.titleBar}):new dojo.dnd.Moveable(a,{handle:this.titleBar,timeout:0}),this._dndListener=dojo.subscribe("/dnd/move/stop",this,"_endDrag")):dojo.addClass(a,"dijitDialogFixed");this.underlayAttrs={dialogId:this.id,"class":dojo.map(this["class"].split(/\s/),function(a){return a+"_underlay"}).join(" ")}},_size:function(){this._checkIfSingleChild();
if(this._singleChild){if(this._singleChildOriginalStyle)this._singleChild.domNode.style.cssText=this._singleChildOriginalStyle;delete this._singleChildOriginalStyle}else dojo.style(this.containerNode,{width:"auto",height:"auto"});var a=dojo._getMarginSize(this.domNode),c=dojo.window.getBox();if(a.w>=c.w||a.h>=c.h){var b=Math.min(a.w,Math.floor(c.w*0.75)),a=Math.min(a.h,Math.floor(c.h*0.75));this._singleChild&&this._singleChild.resize?(this._singleChildOriginalStyle=this._singleChild.domNode.style.cssText,
this._singleChild.resize({w:b,h:a})):dojo.style(this.containerNode,{width:b+"px",height:a+"px",overflow:"auto",position:"relative"})}else this._singleChild&&this._singleChild.resize&&this._singleChild.resize()},_position:function(){if(!dojo.hasClass(dojo.body(),"dojoMove")){var a=this.domNode,c=dojo.window.getBox(),b=this._relativePosition,d=b?null:dojo._getBorderBox(a);dojo.style(a,{left:Math.floor(c.l+(b?b.x:(c.w-d.w)/2))+"px",top:Math.floor(c.t+(b?b.y:(c.h-d.h)/2))+"px"})}},_onKey:function(a){if(a.charOrCode){var c=
dojo.keys,b=a.target;a.charOrCode===c.TAB&&this._getFocusItems(this.domNode);var d=this._firstFocusItem==this._lastFocusItem;if(b==this._firstFocusItem&&a.shiftKey&&a.charOrCode===c.TAB)d||dijit.focus(this._lastFocusItem),dojo.stopEvent(a);else if(b==this._lastFocusItem&&a.charOrCode===c.TAB&&!a.shiftKey)d||dijit.focus(this._firstFocusItem),dojo.stopEvent(a);else{for(;b;){if(b==this.domNode||dojo.hasClass(b,"dijitPopup"))if(a.charOrCode==c.ESCAPE)this.onCancel();else return;b=b.parentNode}if(a.charOrCode!==
c.TAB)dojo.stopEvent(a);else if(!dojo.isOpera)try{this._firstFocusItem.focus()}catch(e){}}}},show:function(){if(!this.open){this._started||this.startup();if(!this._alreadyInitialized)this._setup(),this._alreadyInitialized=!0;this._fadeOutDeferred&&this._fadeOutDeferred.cancel();this._modalconnects.push(dojo.connect(window,"onscroll",this,"layout"));this._modalconnects.push(dojo.connect(window,"onresize",this,function(){var a=dojo.window.getBox();if(!this._oldViewport||a.h!=this._oldViewport.h||a.w!=
this._oldViewport.w)this.layout(),this._oldViewport=a}));this._modalconnects.push(dojo.connect(this.domNode,"onkeypress",this,"_onKey"));dojo.style(this.domNode,{opacity:0,display:""});this._set("open",!0);this._onShow();this._size();this._position();var a;this._fadeInDeferred=new dojo.Deferred(dojo.hitch(this,function(){a.stop();delete this._fadeInDeferred}));a=dojo.fadeIn({node:this.domNode,duration:this.duration,beforeBegin:dojo.hitch(this,function(){dijit._DialogLevelManager.show(this,this.underlayAttrs)}),
onEnd:dojo.hitch(this,function(){this.autofocus&&dijit._DialogLevelManager.isTop(this)&&(this._getFocusItems(this.domNode),dijit.focus(this._firstFocusItem));this._fadeInDeferred.callback(!0);delete this._fadeInDeferred})}).play();return this._fadeInDeferred}},hide:function(){if(this._alreadyInitialized){this._fadeInDeferred&&this._fadeInDeferred.cancel();var a;this._fadeOutDeferred=new dojo.Deferred(dojo.hitch(this,function(){a.stop();delete this._fadeOutDeferred}));a=dojo.fadeOut({node:this.domNode,
duration:this.duration,onEnd:dojo.hitch(this,function(){this.domNode.style.display="none";dijit._DialogLevelManager.hide(this);this.onHide();this._fadeOutDeferred.callback(!0);delete this._fadeOutDeferred})}).play();if(this._scrollConnected)this._scrollConnected=!1;dojo.forEach(this._modalconnects,dojo.disconnect);this._modalconnects=[];this._relativePosition&&delete this._relativePosition;this._set("open",!1);return this._fadeOutDeferred}},layout:function(){this.domNode.style.display!="none"&&(dijit._underlay&&
dijit._underlay.layout(),this._position())},destroy:function(){this._fadeInDeferred&&this._fadeInDeferred.cancel();this._fadeOutDeferred&&this._fadeOutDeferred.cancel();this._moveable&&this._moveable.destroy();this._dndListener&&dojo.unsubscribe(this._dndListener);dojo.forEach(this._modalconnects,dojo.disconnect);dijit._DialogLevelManager.hide(this);this.inherited(arguments)}}),dojo.declare("dijit.Dialog",[dijit.layout.ContentPane,dijit._DialogBase],{}),dijit._DialogLevelManager={show:function(a,
c){var b=dijit._dialogStack;b[b.length-1].focus=dijit.getFocus(a);var d=dijit._underlay;!d||d._destroyed?d=dijit._underlay=new dijit.DialogUnderlay(c):d.set(a.underlayAttrs);var e=b[b.length-1].dialog?b[b.length-1].zIndex+2:950;b.length==1&&d.show();dojo.style(dijit._underlay.domNode,"zIndex",e-1);dojo.style(a.domNode,"zIndex",e);b.push({dialog:a,underlayAttrs:c,zIndex:e})},hide:function(a){var c=dijit._dialogStack;if(c[c.length-1].dialog==a){c.pop();var b=c[c.length-1];c.length==1?dijit._underlay._destroyed||
dijit._underlay.hide():(dojo.style(dijit._underlay.domNode,"zIndex",b.zIndex-1),dijit._underlay.set(b.underlayAttrs));if(a.refocus){c=b.focus;if(!c||b.dialog&&!dojo.isDescendant(c.node,b.dialog.domNode))b.dialog._getFocusItems(b.dialog.domNode),c=b.dialog._firstFocusItem;try{dijit.focus(c)}catch(d){}}}else b=dojo.indexOf(dojo.map(c,function(a){return a.dialog}),a),b!=-1&&c.splice(b,1)},isTop:function(a){var c=dijit._dialogStack;return c[c.length-1].dialog==a}},dijit._dialogStack=[{dialog:null,focus:null,
underlayAttrs:null}];