/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.InlineEditBox"]||(dojo._hasResource["dijit.InlineEditBox"]=!0,dojo.provide("dijit.InlineEditBox"),dojo.require("dojo.i18n"),dojo.require("dijit._Widget"),dojo.require("dijit._Container"),dojo.require("dijit.form.Button"),dojo.require("dijit.form.TextBox"),dojo.requireLocalization("dijit","common",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dijit.InlineEditBox",dijit._Widget,{editing:!1,autoSave:!0,
buttonSave:"",buttonCancel:"",renderAsHtml:!1,editor:"dijit.form.TextBox",editorWrapper:"dijit._InlineEditor",editorParams:{},disabled:!1,onChange:function(){},onCancel:function(){},width:"100%",value:"",noValueIndicator:dojo.isIE<=6?"<span style='font-family: wingdings; text-decoration: underline;'>&nbsp;&nbsp;&nbsp;&nbsp;&#x270d;&nbsp;&nbsp;&nbsp;&nbsp;</span>":"<span style='text-decoration: underline;'>&nbsp;&nbsp;&nbsp;&nbsp;&#x270d;&nbsp;&nbsp;&nbsp;&nbsp;</span>",constructor:function(){this.editorParams=
{}},postMixInProperties:function(){this.inherited(arguments);this.displayNode=this.srcNodeRef;var a={ondijitclick:"_onClick",onmouseover:"_onMouseOver",onmouseout:"_onMouseOut",onfocus:"_onMouseOver",onblur:"_onMouseOut"},b;for(b in a)this.connect(this.displayNode,b,a[b]);dijit.setWaiRole(this.displayNode,"button");this.displayNode.getAttribute("tabIndex")||this.displayNode.setAttribute("tabIndex",0);if(!this.value&&!("value"in this.params))this.value=dojo.trim(this.renderAsHtml?this.displayNode.innerHTML:
this.displayNode.innerText||this.displayNode.textContent||"");if(!this.value)this.displayNode.innerHTML=this.noValueIndicator;dojo.addClass(this.displayNode,"dijitInlineEditBoxDisplayMode")},setDisabled:function(a){dojo.deprecated("dijit.InlineEditBox.setDisabled() is deprecated.  Use set('disabled', bool) instead.","","2.0");this.set("disabled",a)},_setDisabledAttr:function(a){dijit.setWaiState(this.domNode,"disabled",a);a?this.displayNode.removeAttribute("tabIndex"):this.displayNode.setAttribute("tabIndex",
0);dojo.toggleClass(this.displayNode,"dijitInlineEditBoxDisplayModeDisabled",a);this._set("disabled",a)},_onMouseOver:function(){this.disabled||dojo.addClass(this.displayNode,"dijitInlineEditBoxDisplayModeHover")},_onMouseOut:function(){dojo.removeClass(this.displayNode,"dijitInlineEditBoxDisplayModeHover")},_onClick:function(a){this.disabled||(a&&dojo.stopEvent(a),this._onMouseOut(),setTimeout(dojo.hitch(this,"edit"),0))},edit:function(){if(!this.disabled&&!this.editing){this.editing=!0;this._savedPosition=
dojo.style(this.displayNode,"position")||"static";this._savedOpacity=dojo.style(this.displayNode,"opacity")||"1";this._savedTabIndex=dojo.attr(this.displayNode,"tabIndex")||"0";if(this.wrapperWidget){var a=this.wrapperWidget.editWidget;a.set("displayedValue"in a?"displayedValue":"value",this.value)}else a=dojo.create("span",null,this.domNode,"before"),this.wrapperWidget=new (typeof this.editorWrapper=="string"?dojo.getObject(this.editorWrapper):this.editorWrapper)({value:this.value,buttonSave:this.buttonSave,
buttonCancel:this.buttonCancel,dir:this.dir,lang:this.lang,tabIndex:this._savedTabIndex,editor:this.editor,inlineEditBox:this,sourceStyle:dojo.getComputedStyle(this.displayNode),save:dojo.hitch(this,"save"),cancel:dojo.hitch(this,"cancel")},a),this._started||this.startup();var b=this.wrapperWidget;dojo.isIE&&dijit.focus(dijit.getFocus());dojo.style(this.displayNode,{position:"absolute",opacity:"0",display:"none"});dojo.style(b.domNode,{position:this._savedPosition,visibility:"visible",opacity:"1"});
dojo.attr(this.displayNode,"tabIndex","-1");setTimeout(dojo.hitch(this,function(){b.focus();b._resetValue=b.getValue()}),0)}},_onBlur:function(){this.inherited(arguments)},destroy:function(){this.wrapperWidget&&!this.wrapperWidget._destroyed&&(this.wrapperWidget.destroy(),delete this.wrapperWidget);this.inherited(arguments)},_showText:function(a){dojo.style(this.wrapperWidget.domNode,{position:"absolute",visibility:"hidden",opacity:"0"});dojo.style(this.displayNode,{position:this._savedPosition,opacity:this._savedOpacity,
display:""});dojo.attr(this.displayNode,"tabIndex",this._savedTabIndex);a&&dijit.focus(this.displayNode)},save:function(a){if(!this.disabled&&this.editing)this.editing=!1,this.set("value",this.wrapperWidget.getValue()),this._showText(a)},setValue:function(a){dojo.deprecated("dijit.InlineEditBox.setValue() is deprecated.  Use set('value', ...) instead.","","2.0");return this.set("value",a)},_setValueAttr:function(a){a=dojo.trim(a);this.displayNode.innerHTML=(this.renderAsHtml?a:a.replace(/&/gm,"&amp;").replace(/</gm,
"&lt;").replace(/>/gm,"&gt;").replace(/"/gm,"&quot;").replace(/\n/g,"<br>"))||this.noValueIndicator;this._set("value",a);this._started&&setTimeout(dojo.hitch(this,"onChange",a),0)},getValue:function(){dojo.deprecated("dijit.InlineEditBox.getValue() is deprecated.  Use get('value') instead.","","2.0");return this.get("value")},cancel:function(a){if(!this.disabled&&this.editing)this.editing=!1,setTimeout(dojo.hitch(this,"onCancel"),0),this._showText(a)}}),dojo.declare("dijit._InlineEditor",[dijit._Widget,
dijit._Templated],{templateString:dojo.cache("dijit","templates/InlineEditBox.html",'<span data-dojo-attach-point="editNode" role="presentation" style="position: absolute; visibility:hidden" class="dijitReset dijitInline"\n\tdata-dojo-attach-event="onkeypress: _onKeyPress"\n\t><span data-dojo-attach-point="editorPlaceholder"></span\n\t><span data-dojo-attach-point="buttonContainer"\n\t\t><button data-dojo-type="dijit.form.Button" data-dojo-props="label: \'${buttonSave}\', \'class\': \'saveButton\'"\n\t\t\tdata-dojo-attach-point="saveButton" data-dojo-attach-event="onClick:save"></button\n\t\t><button data-dojo-type="dijit.form.Button"  data-dojo-props="label: \'${buttonCancel}\', \'class\': \'cancelButton\'"\n\t\t\tdata-dojo-attach-point="cancelButton" data-dojo-attach-event="onClick:cancel"></button\n\t></span\n></span>\n'),
widgetsInTemplate:!0,postMixInProperties:function(){this.inherited(arguments);this.messages=dojo.i18n.getLocalization("dijit","common",this.lang);dojo.forEach(["buttonSave","buttonCancel"],function(a){this[a]||(this[a]=this.messages[a])},this)},buildRendering:function(){this.inherited(arguments);var a=typeof this.editor=="string"?dojo.getObject(this.editor):this.editor,b=this.sourceStyle,d="line-height:"+b.lineHeight+";",e=dojo.getComputedStyle(this.domNode);dojo.forEach(["Weight","Family","Size",
"Style"],function(a){e["font"+a]!=b["font"+a]&&(d+="font-"+a+":"+b["font"+a]+";")},this);dojo.forEach(["marginTop","marginBottom","marginLeft","marginRight"],function(a){this.domNode.style[a]=b[a]},this);var c=this.inlineEditBox.width;c=="100%"?(d+="width:100%;",this.domNode.style.display="block"):d+="width:"+(c+(Number(c)==c?"px":""))+";";c=dojo.delegate(this.inlineEditBox.editorParams,{style:d,dir:this.dir,lang:this.lang});c["displayedValue"in a.prototype?"displayedValue":"value"]=this.value;this.editWidget=
new a(c,this.editorPlaceholder);this.inlineEditBox.autoSave&&dojo.destroy(this.buttonContainer)},postCreate:function(){this.inherited(arguments);var a=this.editWidget;this.inlineEditBox.autoSave?(this.connect(a,"onChange","_onChange"),this.connect(a,"onKeyPress","_onKeyPress")):"intermediateChanges"in a&&(a.set("intermediateChanges",!0),this.connect(a,"onChange","_onIntermediateChange"),this.saveButton.set("disabled",!0))},_onIntermediateChange:function(){this.saveButton.set("disabled",this.getValue()==
this._resetValue||!this.enableSave())},destroy:function(){this.editWidget.destroy(!0);this.inherited(arguments)},getValue:function(){var a=this.editWidget;return String(a.get("displayedValue"in a?"displayedValue":"value"))},_onKeyPress:function(a){this.inlineEditBox.autoSave&&this.inlineEditBox.editing&&!a.altKey&&!a.ctrlKey&&(a.charOrCode==dojo.keys.ESCAPE?(dojo.stopEvent(a),this.cancel(!0)):a.charOrCode==dojo.keys.ENTER&&a.target.tagName=="INPUT"&&(dojo.stopEvent(a),this._onChange()))},_onBlur:function(){this.inherited(arguments);
this.inlineEditBox.autoSave&&this.inlineEditBox.editing&&(this.getValue()==this._resetValue?this.cancel(!1):this.enableSave()&&this.save(!1))},_onChange:function(){this.inlineEditBox.autoSave&&this.inlineEditBox.editing&&this.enableSave()&&(dojo.style(this.inlineEditBox.displayNode,{display:""}),dijit.focus(this.inlineEditBox.displayNode))},enableSave:function(){return this.editWidget.isValid?this.editWidget.isValid():!0},focus:function(){this.editWidget.focus();setTimeout(dojo.hitch(this,function(){this.editWidget.focusNode&&
this.editWidget.focusNode.tagName=="INPUT"&&dijit.selectInputText(this.editWidget.focusNode)}),0)}}));