/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.TitlePane"]||(dojo._hasResource["dijit.TitlePane"]=!0,dojo.provide("dijit.TitlePane"),dojo.require("dojo.fx"),dojo.require("dijit._Templated"),dojo.require("dijit.layout.ContentPane"),dojo.require("dijit._CssStateMixin"),dojo.declare("dijit.TitlePane",[dijit.layout.ContentPane,dijit._Templated,dijit._CssStateMixin],{title:"",open:!0,toggleable:!0,tabIndex:"0",duration:dijit.defaultDuration,baseClass:"dijitTitlePane",templateString:dojo.cache("dijit","templates/TitlePane.html",
'<div>\n\t<div dojoAttachEvent="onclick:_onTitleClick, onkeypress:_onTitleKey"\n\t\t\tclass="dijitTitlePaneTitle" dojoAttachPoint="titleBarNode">\n\t\t<div class="dijitTitlePaneTitleFocus" dojoAttachPoint="focusNode">\n\t\t\t<img src="${_blankGif}" alt="" dojoAttachPoint="arrowNode" class="dijitArrowNode" role="presentation"\n\t\t\t/><span dojoAttachPoint="arrowNodeInner" class="dijitArrowNodeInner"></span\n\t\t\t><span dojoAttachPoint="titleNode" class="dijitTitlePaneTextNode"></span>\n\t\t</div>\n\t</div>\n\t<div class="dijitTitlePaneContentOuter" dojoAttachPoint="hideNode" role="presentation">\n\t\t<div class="dijitReset" dojoAttachPoint="wipeNode" role="presentation">\n\t\t\t<div class="dijitTitlePaneContentInner" dojoAttachPoint="containerNode" role="region" id="${id}_pane">\n\t\t\t\t<\!-- nested divs because wipeIn()/wipeOut() doesn\'t work right on node w/padding etc.  Put padding on inner div. --\>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n'),
attributeMap:dojo.delegate(dijit.layout.ContentPane.prototype.attributeMap,{title:{node:"titleNode",type:"innerHTML"},tooltip:{node:"focusNode",type:"attribute",attribute:"title"},id:""}),buildRendering:function(){this.inherited(arguments);dojo.setSelectable(this.titleNode,!1)},postCreate:function(){this.inherited(arguments);this.toggleable&&this._trackMouseState(this.titleBarNode,"dijitTitlePaneTitle");var a=this.hideNode;this._wipeIn=dojo.fx.wipeIn({node:this.wipeNode,duration:this.duration,beforeBegin:function(){a.style.display=
""}});this._wipeOut=dojo.fx.wipeOut({node:this.wipeNode,duration:this.duration,onEnd:function(){a.style.display="none"}})},_setOpenAttr:function(a,b){dojo.forEach([this._wipeIn,this._wipeOut],function(a){a&&a.status()=="playing"&&a.stop()});b?this[a?"_wipeIn":"_wipeOut"].play():this.hideNode.style.display=this.wipeNode.style.display=a?"":"none";if(this._started)if(a)this._onShow();else this.onHide();this.arrowNodeInner.innerHTML=a?"-":"+";dijit.setWaiState(this.containerNode,"hidden",a?"false":"true");
dijit.setWaiState(this.focusNode,"pressed",a?"true":"false");this._set("open",a);this._setCss()},_setToggleableAttr:function(a){dijit.setWaiRole(this.focusNode,a?"button":"heading");a?(dijit.setWaiState(this.focusNode,"controls",this.id+"_pane"),dojo.attr(this.focusNode,"tabIndex",this.tabIndex)):dojo.removeAttr(this.focusNode,"tabIndex");this._set("toggleable",a);this._setCss()},_setContentAttr:function(a){!this.open||!this._wipeOut||this._wipeOut.status()=="playing"?this.inherited(arguments):(this._wipeIn&&
this._wipeIn.status()=="playing"&&this._wipeIn.stop(),dojo.marginBox(this.wipeNode,{h:dojo.marginBox(this.wipeNode).h}),this.inherited(arguments),this._wipeIn?this._wipeIn.play():this.hideNode.style.display="")},toggle:function(){this._setOpenAttr(!this.open,!0)},_setCss:function(){var a=this.titleBarNode||this.focusNode,b=this._titleBarClass;this._titleBarClass="dijit"+(this.toggleable?"":"Fixed")+(this.open?"Open":"Closed");dojo.replaceClass(a,this._titleBarClass,b||"");this.arrowNodeInner.innerHTML=
this.open?"-":"+"},_onTitleKey:function(a){a.charOrCode==dojo.keys.ENTER||a.charOrCode==" "?(this.toggleable&&this.toggle(),dojo.stopEvent(a)):a.charOrCode==dojo.keys.DOWN_ARROW&&this.open&&(this.containerNode.focus(),a.preventDefault())},_onTitleClick:function(){this.toggleable&&this.toggle()},setTitle:function(a){dojo.deprecated("dijit.TitlePane.setTitle() is deprecated.  Use set('title', ...) instead.","","2.0");this.set("title",a)}}));