/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.TooltipDialog"]||(dojo._hasResource["dijit.TooltipDialog"]=!0,dojo.provide("dijit.TooltipDialog"),dojo.require("dijit.layout.ContentPane"),dojo.require("dijit._Templated"),dojo.require("dijit.form._FormMixin"),dojo.require("dijit._DialogMixin"),dojo.declare("dijit.TooltipDialog",[dijit.layout.ContentPane,dijit._Templated,dijit.form._FormMixin,dijit._DialogMixin],{title:"",doLayout:!1,autofocus:!0,baseClass:"dijitTooltipDialog",_firstFocusItem:null,_lastFocusItem:null,templateString:dojo.cache("dijit",
"templates/TooltipDialog.html",'<div role="presentation" tabIndex="-1">\n\t<div class="dijitTooltipContainer" role="presentation">\n\t\t<div class ="dijitTooltipContents dijitTooltipFocusNode" dojoAttachPoint="containerNode" role="dialog"></div>\n\t</div>\n\t<div class="dijitTooltipConnector" role="presentation"></div>\n</div>\n'),_setTitleAttr:function(a){this.containerNode.title=a;this._set("title",a)},postCreate:function(){this.inherited(arguments);this.connect(this.containerNode,"onkeypress",
"_onKey")},orient:function(a,c,b){a="dijitTooltipAB"+(b.charAt(1)=="L"?"Left":"Right")+" dijitTooltip"+(b.charAt(0)=="T"?"Below":"Above");dojo.replaceClass(this.domNode,a,this._currentOrientClass||"");this._currentOrientClass=a},focus:function(){this._getFocusItems(this.containerNode);dijit.focus(this._firstFocusItem)},onOpen:function(a){this.orient(this.domNode,a.aroundCorner,a.corner);this._onShow()},onClose:function(){this.onHide()},_onKey:function(a){var c=a.target,b=dojo.keys;a.charOrCode===
b.TAB&&this._getFocusItems(this.containerNode);var d=this._firstFocusItem==this._lastFocusItem;a.charOrCode==b.ESCAPE?(setTimeout(dojo.hitch(this,"onCancel"),0),dojo.stopEvent(a)):c==this._firstFocusItem&&a.shiftKey&&a.charOrCode===b.TAB?(d||dijit.focus(this._lastFocusItem),dojo.stopEvent(a)):c==this._lastFocusItem&&a.charOrCode===b.TAB&&!a.shiftKey?(d||dijit.focus(this._firstFocusItem),dojo.stopEvent(a)):a.charOrCode===b.TAB&&a.stopPropagation()}}));