/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dijit.Tooltip"])dojo._hasResource["dijit.Tooltip"]=!0,dojo.provide("dijit.Tooltip"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.declare("dijit._MasterTooltip",[dijit._Widget,dijit._Templated],{duration:dijit.defaultDuration,templateString:dojo.cache("dijit","templates/Tooltip.html",'<div class="dijitTooltip dijitTooltipLeft" id="dojoTooltip"\n\t><div class="dijitTooltipContainer dijitTooltipContents" dojoAttachPoint="containerNode" role=\'alert\'></div\n\t><div class="dijitTooltipConnector" dojoAttachPoint="connectorNode"></div\n></div>\n'),
postCreate:function(){dojo.body().appendChild(this.domNode);this.bgIframe=new dijit.BackgroundIframe(this.domNode);this.fadeIn=dojo.fadeIn({node:this.domNode,duration:this.duration,onEnd:dojo.hitch(this,"_onShow")});this.fadeOut=dojo.fadeOut({node:this.domNode,duration:this.duration,onEnd:dojo.hitch(this,"_onHide")})},show:function(a,b,c,d){if(!(this.aroundNode&&this.aroundNode===b))this.domNode.width="auto",this.fadeOut.status()=="playing"?this._onDeck=arguments:(this.containerNode.innerHTML=a,dijit.placeOnScreenAroundElement(this.domNode,
b,dijit.getPopupAroundAlignment(c&&c.length?c:dijit.Tooltip.defaultPosition,!d),dojo.hitch(this,"orient")),dojo.style(this.domNode,"opacity",0),this.fadeIn.play(),this.isShowingNow=!0,this.aroundNode=b)},orient:function(a,b,c,d,h){this.connectorNode.style.top="";var i=d.w-this.connectorNode.offsetWidth;a.className="dijitTooltip "+{"BL-TL":"dijitTooltipBelow dijitTooltipABLeft","TL-BL":"dijitTooltipAbove dijitTooltipABLeft","BR-TR":"dijitTooltipBelow dijitTooltipABRight","TR-BR":"dijitTooltipAbove dijitTooltipABRight",
"BR-BL":"dijitTooltipRight","BL-BR":"dijitTooltipLeft"}[b+"-"+c];this.domNode.style.width="auto";var f=dojo.contentBox(this.domNode),g=Math.min(Math.max(i,1),f.w),e=g<f.w;this.domNode.style.width=g+"px";if(e&&(this.containerNode.style.overflow="auto",e=this.containerNode.scrollWidth,this.containerNode.style.overflow="visible",e>g))e=e+dojo.style(this.domNode,"paddingLeft")+dojo.style(this.domNode,"paddingRight"),this.domNode.style.width=e+"px";c.charAt(0)=="B"&&b.charAt(0)=="B"?(a=dojo.marginBox(a),
b=this.connectorNode.offsetHeight,a.h>d.h?(this.connectorNode.style.top=d.h-h.h/2-b/2+"px",this.connectorNode.style.bottom=""):(this.connectorNode.style.bottom=Math.min(Math.max(h.h/2-b/2,0),a.h-b)+"px",this.connectorNode.style.top="")):(this.connectorNode.style.top="",this.connectorNode.style.bottom="");return Math.max(0,f.w-i)},_onShow:function(){if(dojo.isIE)this.domNode.style.filter=""},hide:function(a){if(this._onDeck&&this._onDeck[1]==a)this._onDeck=null;else if(this.aroundNode===a)this.fadeIn.stop(),
this.isShowingNow=!1,this.aroundNode=null,this.fadeOut.play()},_onHide:function(){this.domNode.style.cssText="";this.containerNode.innerHTML="";if(this._onDeck)this.show.apply(this,this._onDeck),this._onDeck=null}}),dijit.showTooltip=function(a,b,c,d){if(!dijit._masterTT)dijit._masterTT=new dijit._MasterTooltip;return dijit._masterTT.show(a,b,c,d)},dijit.hideTooltip=function(a){if(!dijit._masterTT)dijit._masterTT=new dijit._MasterTooltip;return dijit._masterTT.hide(a)},dojo.declare("dijit.Tooltip",
dijit._Widget,{label:"",showDelay:400,connectId:[],position:[],_setConnectIdAttr:function(a){dojo.forEach(this._connections||[],function(a){dojo.forEach(a,dojo.hitch(this,"disconnect"))},this);var b=dojo.isArrayLike(a)?a:a?[a]:[];this._connections=dojo.map(b,function(a){return(a=dojo.byId(a))?[this.connect(a,"onmouseenter","_onTargetMouseEnter"),this.connect(a,"onmouseleave","_onTargetMouseLeave"),this.connect(a,"onfocus","_onTargetFocus"),this.connect(a,"onblur","_onTargetBlur")]:[]},this);this._set("connectId",
a);this._connectIds=b},addTarget:function(a){a=a.id||a;dojo.indexOf(this._connectIds,a)==-1&&this.set("connectId",this._connectIds.concat(a))},removeTarget:function(a){a=dojo.indexOf(this._connectIds,a.id||a);a>=0&&(this._connectIds.splice(a,1),this.set("connectId",this._connectIds))},buildRendering:function(){this.inherited(arguments);dojo.addClass(this.domNode,"dijitTooltipData")},startup:function(){this.inherited(arguments);var a=this.connectId;dojo.forEach(dojo.isArrayLike(a)?a:[a],this.addTarget,
this)},_onTargetMouseEnter:function(a){this._onHover(a)},_onTargetMouseLeave:function(a){this._onUnHover(a)},_onTargetFocus:function(a){this._focus=!0;this._onHover(a)},_onTargetBlur:function(a){this._focus=!1;this._onUnHover(a)},_onHover:function(a){if(!this._showTimer){var b=a.target;this._showTimer=setTimeout(dojo.hitch(this,function(){this.open(b)}),this.showDelay)}},_onUnHover:function(){this._focus||(this._showTimer&&(clearTimeout(this._showTimer),delete this._showTimer),this.close())},open:function(a){this._showTimer&&
(clearTimeout(this._showTimer),delete this._showTimer);dijit.showTooltip(this.label||this.domNode.innerHTML,a,this.position,!this.isLeftToRight());this._connectNode=a;this.onShow(a,this.position)},close:function(){this._connectNode&&(dijit.hideTooltip(this._connectNode),delete this._connectNode,this.onHide());this._showTimer&&(clearTimeout(this._showTimer),delete this._showTimer)},onShow:function(){},onHide:function(){},uninitialize:function(){this.close();this.inherited(arguments)}}),dijit.Tooltip.defaultPosition=
["after","before"];