/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid._Builder"]||(dojo._hasResource["dojox.grid._Builder"]=!0,dojo.provide("dojox.grid._Builder"),dojo.require("dojox.grid.util"),dojo.require("dojo.dnd.Moveable"),function(){var h=dojox.grid,m=function(a){for(;a&&a.tagName!="TABLE";a=a.parentNode);return a},l=function(a,b){for(var c=a;c&&b(c);c=c.parentNode);return c},n=function(a){var b=a.toUpperCase();return function(a){return a.tagName!=b}},o=dojox.grid.util.rowIndexTag,k=dojox.grid.util.gridViewTag;h._Builder=dojo.extend(function(a){if(a)this.view=
a,this.grid=a.grid},{view:null,_table:'<table class="dojoxGridRowTable" border="0" cellspacing="0" cellpadding="0" role="presentation"',getTableArray:function(){var a=[this._table];this.view.viewWidth&&a.push([' style="width:',this.view.viewWidth,';"'].join(""));a.push(">");return a},generateCellMarkup:function(a,b,c,f){var e=[],d;if(f){d=a.index!=a.grid.getSortIndex()?"":a.grid.sortInfo>0?'aria-sort="ascending"':'aria-sort="descending"';if(!a.id)a.id=this.grid.id+"Hdr"+a.index;d=['<th tabIndex="-1" aria-readonly="true" role="columnheader"',
d,'id="',a.id,'"']}else d=['<td tabIndex="-1" role="gridcell"',this.grid.editable&&!a.editable?'aria-readonly="true"':""];a.colSpan&&d.push(' colspan="',a.colSpan,'"');a.rowSpan&&d.push(' rowspan="',a.rowSpan,'"');d.push(' class="dojoxGridCell ');a.classes&&d.push(a.classes," ");c&&d.push(c," ");e.push(d.join(""));e.push("");d=['" idx="',a.index,'" style="'];b&&b[b.length-1]!=";"&&(b+=";");d.push(a.styles,b||"",a.hidden?"display:none;":"");a.unitWidth&&d.push("width:",a.unitWidth,";");e.push(d.join(""));
e.push("");d=['"'];a.attrs&&d.push(" ",a.attrs);d.push(">");e.push(d.join(""));e.push("");e.push(f?"</th>":"</td>");return e},isCellNode:function(a){return Boolean(a&&a!=dojo.doc&&dojo.attr(a,"idx"))},getCellNodeIndex:function(a){return a?Number(dojo.attr(a,"idx")):-1},getCellNode:function(a,b){for(var c=0,f;(f=a.firstChild&&((a.firstChild.rows||0)[c]||a.firstChild.childNodes[c]))&&f.cells;c++)for(var e=0,d;d=f.cells[e];e++)if(this.getCellNodeIndex(d)==b)return d;return null},findCellTarget:function(a,
b){for(var c=a;c&&(!this.isCellNode(c)||c.offsetParent&&k in c.offsetParent.parentNode&&c.offsetParent.parentNode[k]!=this.view.id)&&c!=b;)c=c.parentNode;return c!=b?c:null},baseDecorateEvent:function(a){a.dispatch="do"+a.type;a.grid=this.grid;a.sourceView=this.view;a.cellNode=this.findCellTarget(a.target,a.rowNode);a.cellIndex=this.getCellNodeIndex(a.cellNode);a.cell=a.cellIndex>=0?this.grid.getCell(a.cellIndex):null},findTarget:function(a,b){for(var c=a;c&&c!=this.domNode&&(!(b in c)||k in c&&c[k]!=
this.view.id);)c=c.parentNode;return c!=this.domNode?c:null},findRowTarget:function(a){return this.findTarget(a,o)},isIntraNodeEvent:function(a){try{return a.cellNode&&a.relatedTarget&&dojo.isDescendant(a.relatedTarget,a.cellNode)}catch(b){return!1}},isIntraRowEvent:function(a){try{var b=a.relatedTarget&&this.findRowTarget(a.relatedTarget);return!b&&a.rowIndex==-1||b&&a.rowIndex==b.gridRowIndex}catch(c){return!1}},dispatchEvent:function(a){return a.dispatch in this?this[a.dispatch](a):!1},domouseover:function(a){if(a.cellNode&&
a.cellNode!=this.lastOverCellNode)this.lastOverCellNode=a.cellNode,this.grid.onMouseOver(a);this.grid.onMouseOverRow(a)},domouseout:function(a){if(a.cellNode&&a.cellNode==this.lastOverCellNode&&!this.isIntraNodeEvent(a,this.lastOverCellNode)&&(this.lastOverCellNode=null,this.grid.onMouseOut(a),!this.isIntraRowEvent(a)))this.grid.onMouseOutRow(a)},domousedown:function(a){if(a.cellNode)this.grid.onMouseDown(a);this.grid.onMouseDownRow(a)}});h._ContentBuilder=dojo.extend(function(a){h._Builder.call(this,
a)},h._Builder.prototype,{update:function(){this.prepareHtml()},prepareHtml:function(){for(var a=this.grid.get,b=this.view.structure.cells,c=0,f;f=b[c];c++)for(var e=0,d;d=f[e];e++)if(d.get=d.get||d.value==void 0&&a,d.markup=this.generateCellMarkup(d,d.cellStyles,d.cellClasses,!1),!this.grid.editable&&d.editable)this.grid.editable=!0},generateHtml:function(a,b){var c=this.getTableArray(),f=this.view.structure.cells,e=this.grid.getItem(b);dojox.grid.util.fire(this.view,"onBeforeRow",[b,f]);for(var d=
0,i;i=f[d];d++)if(!i.hidden&&!i.header){c.push(!i.invisible?"<tr>":'<tr class="dojoxGridInvisible">');for(var g=0,j,h,k,l;j=i[g];g++)h=j.markup,k=j.customClasses=[],l=j.customStyles=[],h[5]=j.format(b,e),h[1]=k.join(" "),h[3]=l.join(";"),c.push.apply(c,h);c.push("</tr>")}c.push("</table>");return c.join("")},decorateEvent:function(a){a.rowNode=this.findRowTarget(a.target);if(!a.rowNode)return!1;a.rowIndex=a.rowNode[o];this.baseDecorateEvent(a);a.cell=this.grid.getCell(a.cellIndex);return!0}});h._HeaderBuilder=
dojo.extend(function(a){this.moveable=null;h._Builder.call(this,a)},h._Builder.prototype,{_skipBogusClicks:!1,overResizeWidth:4,minColWidth:1,update:function(){this.tableMap?this.tableMap.mapRows(this.view.structure.cells):this.tableMap=new h._TableMap(this.view.structure.cells)},generateHtml:function(a,b){var c=this.getTableArray(),f=this.view.structure.cells;dojox.grid.util.fire(this.view,"onBeforeRow",[-1,f]);for(var e=0,d;d=f[e];e++)if(!d.hidden){c.push(!d.invisible?"<tr>":'<tr class="dojoxGridInvisible">');
for(var i=0,g,j;g=d[i];i++){g.customClasses=[];g.customStyles=[];if(this.view.simpleStructure){if(g.draggable)g.headerClasses?g.headerClasses.indexOf("dojoDndItem")==-1&&(g.headerClasses+=" dojoDndItem"):g.headerClasses="dojoDndItem";g.attrs?g.attrs.indexOf("dndType='gridColumn_")==-1&&(g.attrs+=" dndType='gridColumn_"+this.grid.id+"'"):g.attrs="dndType='gridColumn_"+this.grid.id+"'"}j=this.generateCellMarkup(g,g.headerStyles,g.headerClasses,!0);j[5]=b!=void 0?b:a(g);j[3]=g.customStyles.join(";");
j[1]=g.customClasses.join(" ");c.push(j.join(""))}c.push("</tr>")}c.push("</table>");return c.join("")},getCellX:function(a){var b,c=a.layerX;if(dojo.isMoz||dojo.isIE>=9)b=l(a.target,n("th")),c-=b&&b.offsetLeft||0,a.sourceView.getScrollbarWidth(),dojo._isBodyLtr()||(table=l(b,n("table")),c-=table&&table.offsetLeft||0);b=l(a.target,function(){if(!b||b==a.cellNode)return!1;c+=b.offsetLeft<0?0:b.offsetLeft;return!0});return c},decorateEvent:function(a){this.baseDecorateEvent(a);a.rowIndex=-1;a.cellX=
this.getCellX(a);return!0},prepareResize:function(a,b){do{var c=a.cellNode.cellIndex>=0?a.cellNode.cellIndex:dojo.indexOf(a.cellNode.parentNode.cells,a.cellNode);a.cellNode=c?a.cellNode.parentNode.cells[c+b]:null;a.cellIndex=a.cellNode?this.getCellNodeIndex(a.cellNode):-1}while(a.cellNode&&a.cellNode.style.display=="none");return Boolean(a.cellNode)},canResize:function(a){if(!a.cellNode||a.cellNode.colSpan>1)return!1;a=this.grid.getCell(a.cellIndex);return!a.noresize&&a.canResize()},overLeftResizeArea:function(a){if(dojo.hasClass(dojo.body(),
"dojoDndMove"))return!1;if(dojo.isIE){var b=a.target;if(dojo.hasClass(b,"dojoxGridArrowButtonNode")||dojo.hasClass(b,"dojoxGridArrowButtonChar"))return!1}return dojo._isBodyLtr()?a.cellIndex>0&&a.cellX>0&&a.cellX<this.overResizeWidth&&this.prepareResize(a,-1):a.cellNode&&a.cellX>0&&a.cellX<this.overResizeWidth},overRightResizeArea:function(a){if(dojo.hasClass(dojo.body(),"dojoDndMove"))return!1;if(dojo.isIE){var b=a.target;if(dojo.hasClass(b,"dojoxGridArrowButtonNode")||dojo.hasClass(b,"dojoxGridArrowButtonChar"))return!1}return dojo._isBodyLtr()?
a.cellNode&&a.cellX>=a.cellNode.offsetWidth-this.overResizeWidth:a.cellIndex>0&&a.cellX>=a.cellNode.offsetWidth-this.overResizeWidth&&this.prepareResize(a,-1)},domousemove:function(a){if(!this.moveable){var b=this.overRightResizeArea(a)?"dojoxGridColResize":this.overLeftResizeArea(a)?"dojoxGridColResize":"";b&&!this.canResize(a)&&(b="dojoxGridColNoResize");dojo.toggleClass(a.sourceView.headerNode,"dojoxGridColNoResize",b=="dojoxGridColNoResize");dojo.toggleClass(a.sourceView.headerNode,"dojoxGridColResize",
b=="dojoxGridColResize");if(dojo.isIE)a.sourceView.headerNode.scrollLeft=a.sourceView.headerNode.scrollLeft;b&&dojo.stopEvent(a)}},domousedown:function(a){this.moveable||((this.overRightResizeArea(a)||this.overLeftResizeArea(a))&&this.canResize(a)?this.beginColumnResize(a):(this.grid.onMouseDown(a),this.grid.onMouseOverRow(a)))},doclick:function(a){return this._skipBogusClicks?(dojo.stopEvent(a),!0):!1},colResizeSetup:function(a,b){var c=dojo.contentBox(a.sourceView.headerNode);if(b){this.lineDiv=
document.createElement("div");var f=(dojo.position||dojo._abs)(a.sourceView.headerNode,!0),e=dojo.contentBox(a.sourceView.domNode),d=a.pageX;!dojo._isBodyLtr()&&dojo.isIE<8&&(d-=dojox.html.metrics.getScrollbar().w);dojo.style(this.lineDiv,{top:f.y+"px",left:d+"px",height:e.h+c.h+"px"});dojo.addClass(this.lineDiv,"dojoxGridResizeColLine");this.lineDiv._origLeft=d;dojo.body().appendChild(this.lineDiv)}for(var f=[],e=this.tableMap.findOverlappingNodes(a.cellNode),d=0,i;i=e[d];d++)f.push({node:i,index:this.getCellNodeIndex(i),
width:i.offsetWidth});e=a.sourceView;i=dojo._isBodyLtr()?1:-1;for(var g=a.grid.views.views,d=[],j=e.idx+i,h;h=g[j];j+=i)d.push({node:h.headerNode,left:window.parseInt(h.headerNode.style.left)});i=e.headerContentNode.firstChild;return{scrollLeft:a.sourceView.headerNode.scrollLeft,view:e,node:a.cellNode,index:a.cellIndex,w:dojo.contentBox(a.cellNode).w,vw:c.w,table:i,tw:dojo.contentBox(i).w,spanners:f,followers:d}},beginColumnResize:function(a){this.moverDiv=document.createElement("div");dojo.style(this.moverDiv,
{position:"absolute",left:0});dojo.body().appendChild(this.moverDiv);dojo.addClass(this.grid.domNode,"dojoxGridColumnResizing");var b=this.moveable=new dojo.dnd.Moveable(this.moverDiv),c=this.colResizeSetup(a,!0);b.onMove=dojo.hitch(this,"doResizeColumn",c);dojo.connect(b,"onMoveStop",dojo.hitch(this,function(){this.endResizeColumn(c);c.node.releaseCapture&&c.node.releaseCapture();this.moveable.destroy();delete this.moveable;this.moveable=null;dojo.removeClass(this.grid.domNode,"dojoxGridColumnResizing")}));
a.cellNode.setCapture&&a.cellNode.setCapture();b.onMouseDown(a)},doResizeColumn:function(a,b,c){var f=c.l,f={deltaX:f,w:a.w+(dojo._isBodyLtr()?f:-f),vw:a.vw+f,tw:a.tw+f};this.dragRecord={inDrag:a,mover:b,leftTop:c};f.w>=this.minColWidth&&(b?dojo.style(this.lineDiv,"left",this.lineDiv._origLeft+f.deltaX+"px"):this.doResizeNow(a,f))},endResizeColumn:function(a){if(this.dragRecord){var b=this.dragRecord.leftTop,b=dojo._isBodyLtr()?b.l:-b.l;b+=Math.max(a.w+b,this.minColWidth)-(a.w+b);dojo.isWebKit&&a.spanners.length&&
(b+=dojo._getPadBorderExtents(a.spanners[0].node).w);this.doResizeNow(a,{deltaX:b,w:a.w+b,vw:a.vw+b,tw:a.tw+b});delete this.dragRecord}dojo.destroy(this.lineDiv);dojo.destroy(this.moverDiv);dojo.destroy(this.moverDiv);delete this.moverDiv;this._skipBogusClicks=!0;a.view.update();this._skipBogusClicks=!1;this.grid.onResizeColumn(a.index)},doResizeNow:function(a,b){a.view.convertColPctToFixed();if(a.view.flexCells&&!a.view.testFlexCells()){var c=m(a.node);if(c)c.style.width=""}for(var f,e,c=0;f=a.spanners[c];c++)if(e=
f.width+b.deltaX,e>0)f.node.style.width=e+"px",a.view.setColWidth(f.index,e);if(dojo._isBodyLtr()||!dojo.isIE)for(c=0;f=a.followers[c];c++)e=f.left+b.deltaX,f.node.style.left=e+"px";a.node.style.width=b.w+"px";a.view.setColWidth(a.index,b.w);a.view.headerNode.style.width=b.vw+"px";a.view.setColumnsWidth(b.tw);if(!dojo._isBodyLtr())a.view.headerNode.scrollLeft=a.scrollLeft+b.deltaX}});h._TableMap=dojo.extend(function(a){this.mapRows(a)},{map:null,mapRows:function(a){if(a.length){this.map=[];var b;
for(b=0;a[b];b++)this.map[b]=[];for(var c=0;b=a[c];c++)for(var f=0,e=0,d,i;d=b[f];f++){for(;this.map[c][e];)e++;this.map[c][e]={c:f,r:c};i=d.rowSpan||1;d=d.colSpan||1;for(var g=0;g<i;g++)for(var h=0;h<d;h++)this.map[c+g][e+h]=this.map[c][e];e+=d}}},dumpMap:function(){for(var a=0,b,c="";b=this.map[a];a++,c="")for(var f=0,e;e=b[f];f++)c+=e.r+","+e.c+"   "},getMapCoords:function(a,b){for(var c=0,f;f=this.map[c];c++)for(var e=0,d;d=f[e];e++)if(d.c==b&&d.r==a)return{j:c,i:e};return{j:-1,i:-1}},getNode:function(a,
b,c){return(a=a&&a.rows[b])&&a.cells[c]},_findOverlappingNodes:function(a,b,c){var d;for(var f=[],b=this.getMapCoords(b,c),c=0,e;e=this.map[c];c++)c!=b.j&&(d=(e=e[b.i])?this.getNode(a,e.r,e.c):null,e=d)&&f.push(e);return f},findOverlappingNodes:function(a){return this._findOverlappingNodes(m(a),a.parentNode.rowIndex>=0?a.parentNode.rowIndex:dojo.indexOf(a.parentNode.parentNode.childNodes,a.parentNode),a.cellIndex>=0?a.cellIndex:dojo.indexOf(a.parentNode.cells,a))}})}());