/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid._Events"]||(dojo._hasResource["dojox.grid._Events"]=!0,dojo.provide("dojox.grid._Events"),dojo.declare("dojox.grid._Events",null,{cellOverClass:"dojoxGridCellOver",onKeyEvent:function(a){this.dispatchKeyEvent(a)},onContentEvent:function(a){this.dispatchContentEvent(a)},onHeaderEvent:function(a){this.dispatchHeaderEvent(a)},onStyleRow:function(a){a.customClasses+=(a.odd?" dojoxGridRowOdd":"")+(a.selected?" dojoxGridRowSelected":"")+(a.over?" dojoxGridRowOver":"");this.focus.styleRow(a);
this.edit.styleRow(a)},onKeyDown:function(a){if(!a.altKey&&!a.metaKey){var b=dojo.keys,c;switch(a.keyCode){case b.ESCAPE:this.edit.cancel();break;case b.ENTER:if(!this.edit.isEditing()){c=this.focus.getHeaderIndex();if(c>=0){this.setSortIndex(c);break}else this.selection.clickSelect(this.focus.rowIndex,dojo.isCopyKey(a),a.shiftKey);dojo.stopEvent(a)}a.shiftKey||(b=this.edit.isEditing(),this.edit.apply(),b||this.edit.setEditCell(this.focus.cell,this.focus.rowIndex));this.edit.isEditing()||((this.focus.focusView||
this.views.views[0]).content.decorateEvent(a),this.onRowClick(a),dojo.stopEvent(a));break;case b.SPACE:if(!this.edit.isEditing()){c=this.focus.getHeaderIndex();if(c>=0){this.setSortIndex(c);break}else this.selection.clickSelect(this.focus.rowIndex,dojo.isCopyKey(a),a.shiftKey);dojo.stopEvent(a)}break;case b.TAB:this.focus[a.shiftKey?"previousKey":"nextKey"](a);break;case b.LEFT_ARROW:case b.RIGHT_ARROW:if(!this.edit.isEditing()){var d=a.keyCode;dojo.stopEvent(a);c=this.focus.getHeaderIndex();c>=0&&
a.shiftKey&&a.ctrlKey?this.focus.colSizeAdjust(a,c,(d==b.LEFT_ARROW?-1:1)*5):(a=d==b.LEFT_ARROW?1:-1,dojo._isBodyLtr()&&(a*=-1),this.focus.move(0,a))}break;case b.UP_ARROW:!this.edit.isEditing()&&this.focus.rowIndex!==0&&(dojo.stopEvent(a),this.focus.move(-1,0));break;case b.DOWN_ARROW:!this.edit.isEditing()&&this.focus.rowIndex+1!=this.rowCount&&(dojo.stopEvent(a),this.focus.move(1,0));break;case b.PAGE_UP:!this.edit.isEditing()&&this.focus.rowIndex!==0&&(dojo.stopEvent(a),this.focus.rowIndex!=this.scroller.firstVisibleRow+
1?this.focus.move(this.scroller.firstVisibleRow-this.focus.rowIndex,0):(this.setScrollTop(this.scroller.findScrollTop(this.focus.rowIndex-1)),this.focus.move(this.scroller.firstVisibleRow-this.scroller.lastVisibleRow+1,0)));break;case b.PAGE_DOWN:!this.edit.isEditing()&&this.focus.rowIndex+1!=this.rowCount&&(dojo.stopEvent(a),this.focus.rowIndex!=this.scroller.lastVisibleRow-1?this.focus.move(this.scroller.lastVisibleRow-this.focus.rowIndex-1,0):(this.setScrollTop(this.scroller.findScrollTop(this.focus.rowIndex+
1)),this.focus.move(this.scroller.lastVisibleRow-this.scroller.firstVisibleRow-1,0)))}}},onMouseOver:function(a){a.rowIndex==-1?this.onHeaderCellMouseOver(a):this.onCellMouseOver(a)},onMouseOut:function(a){a.rowIndex==-1?this.onHeaderCellMouseOut(a):this.onCellMouseOut(a)},onMouseDown:function(a){a.rowIndex==-1?this.onHeaderCellMouseDown(a):this.onCellMouseDown(a)},onMouseOverRow:function(a){this.rows.isOver(a.rowIndex)||(this.rows.setOverRow(a.rowIndex),a.rowIndex==-1?this.onHeaderMouseOver(a):this.onRowMouseOver(a))},
onMouseOutRow:function(a){if(this.rows.isOver(-1))this.onHeaderMouseOut(a);else this.rows.isOver(-2)||(this.rows.setOverRow(-2),this.onRowMouseOut(a))},onMouseDownRow:function(a){if(a.rowIndex!=-1)this.onRowMouseDown(a)},onCellMouseOver:function(a){a.cellNode&&dojo.addClass(a.cellNode,this.cellOverClass)},onCellMouseOut:function(a){a.cellNode&&dojo.removeClass(a.cellNode,this.cellOverClass)},onCellMouseDown:function(){},onCellClick:function(a){this._click[0]=this._click[1];this._click[1]=a;this.edit.isEditCell(a.rowIndex,
a.cellIndex)||this.focus.setFocusCell(a.cell,a.rowIndex);this.onRowClick(a)},onCellDblClick:function(a){this._click.length>1&&dojo.isIE?this.edit.setEditCell(this._click[1].cell,this._click[1].rowIndex):this._click.length>1&&this._click[0].rowIndex!=this._click[1].rowIndex?this.edit.setEditCell(this._click[0].cell,this._click[0].rowIndex):this.edit.setEditCell(a.cell,a.rowIndex);this.onRowDblClick(a)},onCellContextMenu:function(a){this.onRowContextMenu(a)},onCellFocus:function(a,b){this.edit.cellFocus(a,
b)},onRowClick:function(a){this.edit.rowClick(a);this.selection.clickSelectEvent(a)},onRowDblClick:function(){},onRowMouseOver:function(){},onRowMouseOut:function(){},onRowMouseDown:function(){},onRowContextMenu:function(a){dojo.stopEvent(a)},onHeaderMouseOver:function(){},onHeaderMouseOut:function(){},onHeaderCellMouseOver:function(a){a.cellNode&&dojo.addClass(a.cellNode,this.cellOverClass)},onHeaderCellMouseOut:function(a){a.cellNode&&dojo.removeClass(a.cellNode,this.cellOverClass)},onHeaderCellMouseDown:function(){},
onHeaderClick:function(){},onHeaderCellClick:function(a){this.setSortIndex(a.cell.index);this.onHeaderClick(a)},onHeaderDblClick:function(){},onHeaderCellDblClick:function(a){this.onHeaderDblClick(a)},onHeaderCellContextMenu:function(a){this.onHeaderContextMenu(a)},onHeaderContextMenu:function(a){this.headerMenu||dojo.stopEvent(a)},onStartEdit:function(){},onApplyCellEdit:function(){},onCancelEdit:function(){},onApplyEdit:function(){},onCanSelect:function(){return!0},onCanDeselect:function(){return!0},
onSelected:function(a){this.updateRowStyles(a)},onDeselected:function(a){this.updateRowStyles(a)},onSelectionChanged:function(){}}));