/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid._FocusManager"]||(dojo._hasResource["dojox.grid._FocusManager"]=!0,dojo.provide("dojox.grid._FocusManager"),dojo.require("dojox.grid.util"),dojo.declare("dojox.grid._FocusManager",null,{constructor:function(a){this.grid=a;this.cell=null;this.rowIndex=-1;this._connects=[];this._headerConnects=[];this.headerMenu=this.grid.headerMenu;this._connects.push(dojo.connect(this.grid.domNode,"onfocus",this,"doFocus"));this._connects.push(dojo.connect(this.grid.domNode,"onblur",
this,"doBlur"));this._connects.push(dojo.connect(this.grid.domNode,"oncontextmenu",this,"doContextMenu"));this._connects.push(dojo.connect(this.grid.lastFocusNode,"onfocus",this,"doLastNodeFocus"));this._connects.push(dojo.connect(this.grid.lastFocusNode,"onblur",this,"doLastNodeBlur"));this._connects.push(dojo.connect(this.grid,"_onFetchComplete",this,"_delayedCellFocus"));this._connects.push(dojo.connect(this.grid,"postrender",this,"_delayedHeaderFocus"))},destroy:function(){dojo.forEach(this._connects,
dojo.disconnect);dojo.forEach(this._headerConnects,dojo.disconnect);delete this.grid;delete this.cell},_colHeadNode:null,_colHeadFocusIdx:null,_contextMenuBindNode:null,tabbingOut:!1,focusClass:"dojoxGridCellFocus",focusView:null,initFocusView:function(){this.focusView=this.grid.views.getFirstScrollingView()||this.focusView||this.grid.views.views[0];this._initColumnHeaders()},isFocusCell:function(a,b){return this.cell==a&&this.rowIndex==b},isLastFocusCell:function(){return this.cell?this.rowIndex==
this.grid.rowCount-1&&this.cell.index==this.grid.layout.cellCount-1:!1},isFirstFocusCell:function(){return this.cell?this.rowIndex===0&&this.cell.index===0:!1},isNoFocusCell:function(){return this.rowIndex<0||!this.cell},isNavHeader:function(){return!!this._colHeadNode},getHeaderIndex:function(){return this._colHeadNode?dojo.indexOf(this._findHeaderCells(),this._colHeadNode):-1},_focusifyCellNode:function(a){var b=this.cell&&this.cell.getNode(this.rowIndex);if(b&&(dojo.toggleClass(b,this.focusClass,
a),a)){a=this.scrollIntoView();try{if(!this.grid.edit.isEditing()&&(dojox.grid.util.fire(b,"focus"),a))this.cell.view.scrollboxNode.scrollLeft=a}catch(c){}}},_delayedCellFocus:function(){if(!this.isNavHeader()&&this.grid._focused){var a=this.cell&&this.cell.getNode(this.rowIndex);if(a)try{this.grid.edit.isEditing()||(dojo.toggleClass(a,this.focusClass,!0),this.blurHeader(),dojox.grid.util.fire(a,"focus"))}catch(b){}}},_delayedHeaderFocus:function(){this.isNavHeader()&&(this.focusHeader(),this.grid.domNode.focus())},
_initColumnHeaders:function(){dojo.forEach(this._headerConnects,dojo.disconnect);this._headerConnects=[];for(var a=this._findHeaderCells(),b=0;b<a.length;b++)this._headerConnects.push(dojo.connect(a[b],"onfocus",this,"doColHeaderFocus")),this._headerConnects.push(dojo.connect(a[b],"onblur",this,"doColHeaderBlur"))},_findHeaderCells:function(){for(var a=dojo.query("th",this.grid.viewsHeaderNode),b=[],c=0;c<a.length;c++){var d=a[c],f=dojo.hasAttr(d,"tabIndex"),e=dojo.attr(d,"tabIndex");f&&e<0&&b.push(d)}return b},
_setActiveColHeader:function(a,b,c){dojo.attr(this.grid.domNode,"aria-activedescendant",a.id);c!=null&&c>=0&&c!=b&&dojo.toggleClass(this._findHeaderCells()[c],this.focusClass,!1);dojo.toggleClass(a,this.focusClass,!0);this._colHeadNode=a;this._colHeadFocusIdx=b;this._scrollHeader(this._colHeadFocusIdx)},scrollIntoView:function(){var a=this.cell?this._scrollInfo(this.cell):null;if(!a||!a.s)return null;var b=this.grid.scroller.findScrollTop(this.rowIndex);if(a.n&&a.sr)if(a.n.offsetLeft+a.n.offsetWidth>
a.sr.l+a.sr.w)a.s.scrollLeft=a.n.offsetLeft+a.n.offsetWidth-a.sr.w;else if(a.n.offsetLeft<a.sr.l)a.s.scrollLeft=a.n.offsetLeft;a.r&&a.sr&&(b+a.r.offsetHeight>a.sr.t+a.sr.h?this.grid.setScrollTop(b+a.r.offsetHeight-a.sr.h):b<a.sr.t&&this.grid.setScrollTop(b));return a.s.scrollLeft},_scrollInfo:function(a,b){if(a){var c=a.view.scrollboxNode,d={w:c.clientWidth,l:c.scrollLeft,t:c.scrollTop,h:c.clientHeight},f=a.view.getRowNode(this.rowIndex);return{c:a,s:c,sr:d,n:b?b:a.getNode(this.rowIndex),r:f}}return null},
_scrollHeader:function(a){var b=null;if(this._colHeadNode)var c=this.grid.getCell(a),b=this._scrollInfo(c,c.getNode(0));if(b&&b.s&&b.sr&&b.n)if(b.n.offsetLeft+b.n.offsetWidth>b.sr.l+b.sr.w)b.s.scrollLeft=b.n.offsetLeft+b.n.offsetWidth-b.sr.w;else if(b.n.offsetLeft<b.sr.l)b.s.scrollLeft=b.n.offsetLeft;else if(dojo.isIE<=7&&c&&c.view.headerNode)c.view.headerNode.scrollLeft=b.s.scrollLeft},_isHeaderHidden:function(){var a=this.focusView;if(!a)for(var b=0,c;c=this.grid.views.views[b];b++)if(c.headerNode){a=
c;break}return a&&dojo.getComputedStyle(a.headerNode).display=="none"},colSizeAdjust:function(a,b,c){var d=this._findHeaderCells(),f=this.focusView;if(!f)for(var e=0,g;g=this.grid.views.views[e];e++)if(g.header.tableMap.map){f=g;break}e=d[b];if(f&&!(b==d.length-1&&b===0))f.content.baseDecorateEvent(a),a.cellNode=e,a.cellIndex=f.content.getCellNodeIndex(a.cellNode),a.cell=a.cellIndex>=0?this.grid.getCell(a.cellIndex):null,f.header.canResize(a)&&(b={l:c},a=f.header.colResizeSetup(a,!1),f.header.doResizeColumn(a,
null,b),f.update())},styleRow:function(){},setFocusIndex:function(a,b){this.setFocusCell(this.grid.getCell(b),a)},setFocusCell:function(a,b){if(a&&!this.isFocusCell(a,b))this.tabbingOut=!1,this._colHeadNode&&this.blurHeader(),this._colHeadNode=this._colHeadFocusIdx=null,this.focusGridView(),this._focusifyCellNode(!1),this.cell=a,this.rowIndex=b,this._focusifyCellNode(!0);if(dojo.isOpera)setTimeout(dojo.hitch(this.grid,"onCellFocus",this.cell,this.rowIndex),1);else this.grid.onCellFocus(this.cell,
this.rowIndex)},next:function(){if(this.cell){var a=this.rowIndex,b=this.cell.index+1,c=this.grid.layout.cellCount-1,d=this.grid.rowCount-1;b>c&&(b=0,a++);a>d&&(b=c,a=d);if(this.grid.edit.isEditing()&&(c=this.grid.getCell(b),!this.isLastFocusCell()&&(!c.editable||this.grid.canEdit&&!this.grid.canEdit(c,a)))){this.cell=c;this.rowIndex=a;this.next();return}this.setFocusIndex(a,b)}},previous:function(){if(this.cell){var a=this.rowIndex||0,b=(this.cell.index||0)-1;b<0&&(b=this.grid.layout.cellCount-1,
a--);a<0&&(b=a=0);if(this.grid.edit.isEditing()){var c=this.grid.getCell(b);if(!this.isFirstFocusCell()&&!c.editable){this.cell=c;this.rowIndex=a;this.previous();return}}this.setFocusIndex(a,b)}},move:function(a,b){var c=b<0?-1:1;if(this.isNavHeader()){var d=this._findHeaderCells(),f=currentIdx=dojo.indexOf(d,this._colHeadNode);for(currentIdx+=b;currentIdx>=0&&currentIdx<d.length&&d[currentIdx].style.display=="none";)currentIdx+=c;currentIdx>=0&&currentIdx<d.length&&this._setActiveColHeader(d[currentIdx],
currentIdx,f)}else if(this.cell){var e=this.grid.scroller,d=this.rowIndex,f=this.grid.rowCount-1,g=Math.min(f,Math.max(0,d+a));a&&(a>0?g>e.getLastPageRow(e.page)&&this.grid.setScrollTop(this.grid.scrollTop+e.findScrollTop(g)-e.findScrollTop(d)):a<0&&g<=e.getPageRow(e.page)&&this.grid.setScrollTop(this.grid.scrollTop-e.findScrollTop(d)-e.findScrollTop(g)));for(var e=this.grid.layout.cellCount-1,j=this.cell.index,h=Math.min(e,Math.max(0,j+b)),i=this.grid.getCell(h);h>=0&&h<e&&i&&i.hidden===!0;)h+=c,
i=this.grid.getCell(h);if(!i||i.hidden===!0)h=j;c=i.getNode(g);!c&&a?g+a>=0&&g+a<=f&&this.move(a>0?++a:--a,b):(!c||dojo.style(c,"display")==="none")&&b?h+a>=0&&h+a<=e&&this.move(a,b>0?++b:--b):(this.setFocusIndex(g,h),a&&this.grid.updateRow(d))}},previousKey:function(a){if(this.grid.edit.isEditing())dojo.stopEvent(a),this.previous();else if(!this.isNavHeader()&&!this._isHeaderHidden())this.grid.domNode.focus(),dojo.stopEvent(a);else{this.tabOut(this.grid.domNode);if(this._colHeadFocusIdx!=null)dojo.toggleClass(this._findHeaderCells()[this._colHeadFocusIdx],
this.focusClass,!1),this._colHeadFocusIdx=null;this._focusifyCellNode(!1)}},nextKey:function(a){a.target===this.grid.domNode&&this._colHeadFocusIdx==null?(this.focusHeader(),dojo.stopEvent(a)):this.isNavHeader()?(this.blurHeader(),this.findAndFocusGridCell()||this.tabOut(this.grid.lastFocusNode),this._colHeadNode=this._colHeadFocusIdx=null):this.grid.edit.isEditing()?(dojo.stopEvent(a),this.next()):this.tabOut(this.grid.lastFocusNode)},tabOut:function(a){this.tabbingOut=!0;a.focus()},focusGridView:function(){dojox.grid.util.fire(this.focusView,
"focus")},focusGrid:function(){this.focusGridView();this._focusifyCellNode(!0)},findAndFocusGridCell:function(){var a=!0,b=this.grid.rowCount===0;this.isNoFocusCell()&&!b?(b=0,this.grid.getCell(b).hidden&&(b=this.isNavHeader()?this._colHeadFocusIdx:0),this.setFocusIndex(0,b)):this.cell&&!b?(this.focusView&&!this.focusView.rowNodes[this.rowIndex]&&this.grid.scrollToRow(this.rowIndex),this.focusGrid()):a=!1;this._colHeadNode=this._colHeadFocusIdx=null;return a},focusHeader:function(){var a=this._findHeaderCells(),
b=this._colHeadFocusIdx;if(this._isHeaderHidden())this.findAndFocusGridCell();else if(!this._colHeadFocusIdx)this._colHeadFocusIdx=this.isNoFocusCell()?0:this.cell.index;for(this._colHeadNode=a[this._colHeadFocusIdx];this._colHeadNode&&this._colHeadFocusIdx>=0&&this._colHeadFocusIdx<a.length&&this._colHeadNode.style.display=="none";)this._colHeadFocusIdx++,this._colHeadNode=a[this._colHeadFocusIdx];if(this._colHeadNode&&this._colHeadNode.style.display!="none"){if(this.headerMenu&&this._contextMenuBindNode!=
this.grid.domNode)this.headerMenu.unBindDomNode(this.grid.viewsHeaderNode),this.headerMenu.bindDomNode(this.grid.domNode),this._contextMenuBindNode=this.grid.domNode;this._setActiveColHeader(this._colHeadNode,this._colHeadFocusIdx,b);this._scrollHeader(this._colHeadFocusIdx);this._focusifyCellNode(!1)}else this.findAndFocusGridCell()},blurHeader:function(){dojo.removeClass(this._colHeadNode,this.focusClass);dojo.removeAttr(this.grid.domNode,"aria-activedescendant");if(this.headerMenu&&this._contextMenuBindNode==
this.grid.domNode){var a=this.grid.viewsHeaderNode;this.headerMenu.unBindDomNode(this.grid.domNode);this.headerMenu.bindDomNode(a);this._contextMenuBindNode=a}},doFocus:function(a){if(!(a&&a.target!=a.currentTarget))this.tabbingOut||this.focusHeader(),this.tabbingOut=!1;dojo.stopEvent(a)},doBlur:function(a){dojo.stopEvent(a)},doContextMenu:function(a){this.headerMenu||dojo.stopEvent(a)},doLastNodeFocus:function(a){this.tabbingOut?this._focusifyCellNode(!1):this.grid.rowCount>0?(this.isNoFocusCell()&&
this.setFocusIndex(0,0),this._focusifyCellNode(!0)):this.focusHeader();this.tabbingOut=!1;dojo.stopEvent(a)},doLastNodeBlur:function(a){dojo.stopEvent(a)},doColHeaderFocus:function(a){this._setActiveColHeader(a.target,dojo.attr(a.target,"idx"),this._colHeadFocusIdx);this._scrollHeader(this.getHeaderIndex());dojo.stopEvent(a)},doColHeaderBlur:function(a){dojo.toggleClass(a.target,this.focusClass,!1)}}));