/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid._Layout"]||(dojo._hasResource["dojox.grid._Layout"]=!0,dojo.provide("dojox.grid._Layout"),dojo.require("dojox.grid.cells"),dojo.require("dojox.grid._RowSelector"),dojo.declare("dojox.grid._Layout",null,{constructor:function(a){this.grid=a},cells:[],structure:null,defaultWidth:"6em",moveColumn:function(a,c,b,d,g){for(var e=this.structure[a].cells[0],i=this.structure[c].cells[0],f=null,j=f=0,a=0,h;h=e[a];a++)if(h.index==b){f=a;break}f=e.splice(f,1)[0];f.view=this.grid.views.views[c];
a=0;for(h=null;h=i[a];a++)if(h.index==d){j=a;break}g||(j+=1);i.splice(j,0,f);if(b=this.grid.getCell(this.grid.getSortIndex()))b._currentlySorted=this.grid.getSortAsc();this.cells=[];for(a=b=0;c=this.structure[a];a++)for(d=0;g=c.cells[d];d++)for(e=0;h=g[e];e++){h.index=b;this.cells.push(h);if("_currentlySorted"in h)i=b+1,i*=h._currentlySorted?1:-1,this.grid.sortInfo=i,delete h._currentlySorted;b++}dojo.forEach(this.cells,function(a){var b=a.markup[2].split(" ");parseInt(b[1].substring(5))!=a.index&&
(b[1]='idx="'+a.index+'"',a.markup[2]=b.join(" "))});this.grid.setupHeaderMenu()},setColumnVisibility:function(a,c){var b=this.cells[a];if(b.hidden==c){b.hidden=!c;var d=b.view,g=d.viewWidth;if(g&&g!="auto")d._togglingColumn=dojo.marginBox(b.getHeaderNode()).w||0;d.update();return!0}else return!1},addCellDef:function(a,c,b){var d=this,g=function(a){var b=0;a.colSpan>1?b=0:(b=a.width||d._defaultCellProps.width||d.defaultWidth,isNaN(b)||(b+="em"));return b},a={grid:this.grid,subrow:a,layoutIndex:c,
index:this.cells.length};if(b&&b instanceof dojox.grid.cells._Base)return c=dojo.clone(b),a.unitWidth=g(c._props),c=dojo.mixin(c,this._defaultCellProps,b._props,a);c=b.type||b.cellType||this._defaultCellProps.type||this._defaultCellProps.cellType||dojox.grid.cells.Cell;a.unitWidth=g(b);return new c(dojo.mixin({},this._defaultCellProps,b,a))},addRowDef:function(a,c){for(var b=[],d=0,g=0,e=!0,i=0,f;f=c[i];i++)if(f=this.addCellDef(a,i,f),b.push(f),this.cells.push(f),e&&f.relWidth)d+=f.relWidth;else if(f.width)f=
f.width,typeof f=="string"&&f.slice(-1)=="%"?g+=window.parseInt(f,10):f=="auto"&&(e=!1);d&&e&&dojo.forEach(b,function(a){if(a.relWidth)a.width=a.unitWidth=a.relWidth/d*(100-g)+"%"});return b},addRowsDef:function(a){var c=[];if(dojo.isArray(a))if(dojo.isArray(a[0]))for(var b=0,d;a&&(d=a[b]);b++)c.push(this.addRowDef(b,d));else c.push(this.addRowDef(0,a));return c},addViewDef:function(a){this._defaultCellProps=a.defaultCell||{};a.width&&a.width=="auto"&&delete a.width;return dojo.mixin({},a,{cells:this.addRowsDef(a.rows||
a.cells)})},setStructure:function(a){this.fieldIndex=0;this.cells=[];var c=this.structure=[];if(this.grid.rowSelector){var b={type:dojox._scopeName+".grid._RowSelector"};if(dojo.isString(this.grid.rowSelector)){var d=this.grid.rowSelector;d=="false"?b=null:d!="true"&&(b.width=d)}else this.grid.rowSelector||(b=null);b&&c.push(this.addViewDef(b))}b=function(a){return a!==null&&dojo.isObject(a)&&("cells"in a||"rows"in a||"type"in a&&!("name"in a||"field"in a||"get"in a))};if(dojo.isArray(a)){for(var d=
!1,g=0,e;e=a[g];g++)if(b(e)){d=!0;break}if(d)for(g=0;e=a[g];g++)dojo.isArray(e)&&(dojo.isArray(e[0])||"name"in e[0]||"field"in e[0]||"get"in e[0])?c.push(this.addViewDef({cells:e})):b(e)&&c.push(this.addViewDef(e));else c.push(this.addViewDef({cells:a}))}else b(a)&&c.push(this.addViewDef(a));this.cellCount=this.cells.length;this.grid.setupHeaderMenu()}}));