/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid._Selector"]||(dojo._hasResource["dojox.grid._Selector"]=!0,dojo.provide("dojox.grid._Selector"),dojo.require("dojox.grid.Selection"),dojo.require("dojox.grid._View"),dojo.require("dojox.grid._Builder"),function(){dojox.grid._InputSelectorHeaderBuilder=dojo.extend(function(a){dojox.grid._HeaderBuilder.call(this,a)},dojox.grid._HeaderBuilder.prototype,{generateHtml:function(){var a=this.view.contentWidth||0,b=this.view.grid.selection.getSelectedCount();return'<table style="width:'+
a+'px;" border="0" cellspacing="0" cellpadding="0" role="presentation"><tr><th style="text-align: center;"><div class="dojoxGridCheckSelector dijitReset dijitInline dijitCheckBox'+(b&&b==this.view.grid.rowCount?" dijitCheckBoxChecked dijitChecked":"")+'"></div></th></tr></table>'},doclick:function(){var a=this.view.grid.selection.getSelectedCount();this.view._selectionChanging=!0;a==this.view.grid.rowCount?this.view.grid.selection.deselectAll():this.view.grid.selection.selectRange(0,this.view.grid.rowCount-
1);this.view._selectionChanging=!1;this.view.onSelectionChanged();return!0}});dojox.grid._SelectorContentBuilder=dojo.extend(function(a){dojox.grid._ContentBuilder.call(this,a)},dojox.grid._ContentBuilder.prototype,{generateHtml:function(a,b){return'<table class="dojoxGridRowbarTable" style="width:'+(this.view.contentWidth||0)+'px;" border="0" cellspacing="0" cellpadding="0" role="presentation"><tr><td  style="text-align: center;" class="dojoxGridRowbarInner">'+this.getCellContent(b)+"</td></tr></table>"},
getCellContent:function(){return"&nbsp;"},findTarget:function(){return dojox.grid._ContentBuilder.prototype.findTarget.apply(this,arguments)},domouseover:function(a){this.view.grid.onMouseOverRow(a)},domouseout:function(a){if(!this.isIntraRowEvent(a))this.view.grid.onMouseOutRow(a)},doclick:function(a){var a=a.rowIndex,b=this.view.grid.selection.mode;this.view.grid.selection.isSelected(a)?this.view.grid.selection.deselect(a):b=="single"?this.view.grid.selection.select(a):b!="none"&&this.view.grid.selection.addToSelection(a);
return!0}});dojox.grid._InputSelectorContentBuilder=dojo.extend(function(a){dojox.grid._SelectorContentBuilder.call(this,a)},dojox.grid._SelectorContentBuilder.prototype,{getCellContent:function(a){var b=this.view,c=b.inputType=="checkbox"?"CheckBox":"Radio",a=b.grid.selection.isSelected(a)?" dijit"+c+"Checked dijitChecked":"";return'<div class="dojoxGridCheckSelector dijitReset dijitInline dijit'+c+a+'"></div>'}});dojo.declare("dojox.grid._Selector",dojox.grid._View,{inputType:"",selectionMode:"",
defaultWidth:"2em",noscroll:!0,padBorderWidth:2,_contentBuilderClass:dojox.grid._SelectorContentBuilder,postCreate:function(){this.inherited(arguments);if(this.selectionMode)this.grid.selection.mode=this.selectionMode;this.connect(this.grid.selection,"onSelected","onSelected");this.connect(this.grid.selection,"onDeselected","onDeselected")},buildRendering:function(){this.inherited(arguments);this.scrollboxNode.style.overflow="hidden"},getWidth:function(){return this.viewWidth||this.defaultWidth},
resize:function(){this.adaptHeight()},setStructure:function(a){this.inherited(arguments);if(a.defaultWidth)this.defaultWidth=a.defaultWidth},adaptWidth:function(){if(!("contentWidth"in this)&&this.contentNode)this.contentWidth=this.contentNode.offsetWidth-this.padBorderWidth},doStyleRowNode:function(a,b){var c=["dojoxGridRowbar dojoxGridNonNormalizedCell"];this.grid.rows.isOver(a)&&c.push("dojoxGridRowbarOver");this.grid.selection.isSelected(a)&&c.push("dojoxGridRowbarSelected");b.className=c.join(" ")},
onSelected:function(a){this.grid.updateRow(a)},onDeselected:function(a){this.grid.updateRow(a)}});if(!dojox.grid._View.prototype._headerBuilderClass&&!dojox.grid._View.prototype._contentBuilderClass)dojox.grid._Selector.prototype.postCreate=function(){this.connect(this.scrollboxNode,"onscroll","doscroll");dojox.grid.util.funnelEvents(this.contentNode,this,"doContentEvent",["mouseover","mouseout","click","dblclick","contextmenu","mousedown"]);dojox.grid.util.funnelEvents(this.headerNode,this,"doHeaderEvent",
["dblclick","mouseover","mouseout","mousemove","mousedown","click","contextmenu"]);this.content=this._contentBuilderClass?new this._contentBuilderClass(this):new dojox.grid._ContentBuilder(this);this.header=this._headerBuilderClass?new this._headerBuilderClass(this):new dojox.grid._HeaderBuilder(this);if(!dojo._isBodyLtr())this.headerNodeContainer.style.width="";this.connect(this.grid.selection,"onSelected","onSelected");this.connect(this.grid.selection,"onDeselected","onDeselected")};dojo.declare("dojox.grid._RadioSelector",
dojox.grid._Selector,{inputType:"radio",selectionMode:"single",_contentBuilderClass:dojox.grid._InputSelectorContentBuilder,buildRendering:function(){this.inherited(arguments);this.headerNode.style.visibility="hidden"},renderHeader:function(){}});dojo.declare("dojox.grid._CheckBoxSelector",dojox.grid._Selector,{inputType:"checkbox",_headerBuilderClass:dojox.grid._InputSelectorHeaderBuilder,_contentBuilderClass:dojox.grid._InputSelectorContentBuilder,postCreate:function(){this.inherited(arguments);
this.connect(this.grid,"onSelectionChanged","onSelectionChanged");this.connect(this.grid,"updateRowCount","_updateVisibility")},renderHeader:function(){this.inherited(arguments);this._updateVisibility(this.grid.rowCount)},_updateVisibility:function(a){this.headerNode.style.visibility=a?"":"hidden"},onSelectionChanged:function(){if(!this._selectionChanging){var a=dojo.query(".dojoxGridCheckSelector",this.headerNode)[0],b=this.grid,c=b.rowCount&&b.rowCount==b.selection.getSelectedCount();b.allItemsSelected=
c||!1;dojo.toggleClass(a,"dijitChecked",b.allItemsSelected);dojo.toggleClass(a,"dijitCheckBoxChecked",b.allItemsSelected)}}})}());