/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid._TreeView"]||(dojo._hasResource["dojox.grid._TreeView"]=!0,dojo.provide("dojox.grid._TreeView"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dojox.grid._View"),dojo.declare("dojox.grid._Expando",[dijit._Widget,dijit._Templated],{open:!1,toggleClass:"",itemId:"",cellIdx:-1,view:null,rowNode:null,rowIdx:-1,expandoCell:null,level:0,templateString:'<div class="dojoxGridExpando"\n\t><div class="dojoxGridExpandoNode" dojoAttachEvent="onclick:onToggle"\n\t\t><div class="dojoxGridExpandoNodeInner" dojoAttachPoint="expandoInner"></div\n\t></div\n></div>\n',
_toggleRows:function(a,b){if(a&&this.rowNode)if(dojo.query("table.dojoxGridRowTableNeedsRowUpdate").length)this._initialized&&this.view.grid.updateRow(this.rowIdx);else{var c=this;if(this.view.grid.treeModel){var d=this._tableRow?dojo.attr(this._tableRow,"dojoxTreeGridPath"):"";d&&dojo.query('tr[dojoxTreeGridPath^="'+d+'/"]',this.rowNode).forEach(function(c){var e=dojo.query(".dojoxGridExpando",c)[0];e&&e.parentNode&&e.parentNode.parentNode&&!dojo.hasClass(e.parentNode.parentNode,"dojoxGridNoChildren")&&
(e=dijit.byNode(e))&&e._toggleRows(a,e.open&&b);c.style.display=b?"":"none"})}else dojo.query("tr."+a,this.rowNode).forEach(function(a){if(dojo.hasClass(a,"dojoxGridExpandoRow")){var e=dojo.query(".dojoxGridExpando",a)[0];if(e){var d=dijit.byNode(e),n=d?d.toggleClass:e.getAttribute("toggleClass"),e=d?d.open:c.expandoCell.getOpenState(e.getAttribute("itemId"));c._toggleRows(n,e&&b)}}a.style.display=b?"":"none"})}},setOpen:function(a){a&&dojo.hasClass(this.domNode,"dojoxGridExpandoLoading")&&(a=!1);
var b=this.view.grid,c=b.store,d=b.treeModel,f=this;if(b._by_idx[this.rowIdx])if(d&&!this._loadedChildren)if(a){var e=b.getItem(dojo.attr(this._tableRow,"dojoxTreeGridPath"));e?(this.expandoInner.innerHTML="o",dojo.addClass(this.domNode,"dojoxGridExpandoLoading"),d.getChildren(e,function(){f._loadedChildren=!0;f._setOpen(a)})):this._setOpen(a)}else this._setOpen(a);else!d&&c?a?(d=b._by_idx[this.rowIdx])&&!c.isItemLoaded(d.item)?(this.expandoInner.innerHTML="o",dojo.addClass(this.domNode,"dojoxGridExpandoLoading"),
c.loadItem({item:d.item,onItem:dojo.hitch(this,function(e){var d=c.getIdentity(e);b._by_idty[d]=b._by_idx[this.rowIdx]={idty:d,item:e};this._setOpen(a)})})):this._setOpen(a):this._setOpen(a):this._setOpen(a)},_setOpen:function(a){if(a&&this._tableRow&&dojo.hasClass(this._tableRow,"dojoxGridNoChildren"))this._setOpen(!1);else{this.expandoInner.innerHTML=a?"-":"+";dojo.removeClass(this.domNode,"dojoxGridExpandoLoading");dojo.toggleClass(this.domNode,"dojoxGridExpandoOpened",a);if(this._tableRow){dojo.toggleClass(this._tableRow,
"dojoxGridRowCollapsed",!a);var b=dojo.attr(this._tableRow,"dojoxTreeGridBaseClasses"),c="",c=a?dojo.trim((" "+b+" ").replace(" dojoxGridRowCollapsed "," ")):(" "+b+" ").indexOf(" dojoxGridRowCollapsed ")<0?b+(b?" ":"")+"dojoxGridRowCollapsed":b;dojo.attr(this._tableRow,"dojoxTreeGridBaseClasses",c)}b=this.open!==a;this.open=a;this.expandoCell&&this.itemId&&(this.expandoCell.openStates[this.itemId]=a);var c=this.view,d=c.grid;this.toggleClass&&b&&(!this._tableRow||!this._tableRow.style.display)&&
this._toggleRows(this.toggleClass,a);c&&this._initialized&&this.rowIdx>=0&&(d.rowHeightChanged(this.rowIdx),d.postresize(),c.hasVScrollbar(!0));this._initialized=!0}},onToggle:function(a){this.setOpen(!this.open);dojo.stopEvent(a)},setRowNode:function(a,b,c){if(this.cellIdx<0||!this.itemId)return!1;this._initialized=!1;this.view=c;this.rowNode=b;this.rowIdx=a;this.expandoCell=c.structure.cells[0][this.cellIdx];if((a=this.domNode)&&a.parentNode&&a.parentNode.parentNode)this._tableRow=a.parentNode.parentNode;
this.open=this.expandoCell.getOpenState(this.itemId);c.grid.treeModel&&(dojo.style(this.domNode,"marginLeft",this.level*18+"px"),this.domNode.parentNode&&dojo.style(this.domNode.parentNode,"backgroundPosition",this.level*18+3+"px"));this.setOpen(this.open);return!0}}),dojo.declare("dojox.grid._TreeContentBuilder",dojox.grid._ContentBuilder,{generateHtml:function(a,b){var c=this.getTableArray(),d=this.view,f=d.structure.cells[0],e=this.grid.getItem(b),i=this.grid,n=this.grid.store;dojox.grid.util.fire(this.view,
"onBeforeRow",[b,[f]]);var g=function(a,e,b,j,h,o){if(o){var s=c.length,j=j||[],v=j.join("|"),t=j[j.length-1],k=t+(b?" dojoxGridSummaryRow":"");i.treeModel&&e&&!i.treeModel.mayHaveChildren(e)&&(k+=" dojoxGridNoChildren");c.push('<tr style="" class="'+k+'" dojoxTreeGridPath="'+h.join("/")+'" dojoxTreeGridBaseClasses="'+k+'">');for(var w=a+1,k=null,p=0,l;l=f[p];p++){var u=l.markup,x=l.customClasses=[],y=l.customStyles=[];u[5]=l.formatAtLevel(h,e,a,b,t,x);u[1]=x.join(" ");u[3]=y.join(";");c.push.apply(c,
u);if(!k&&l.level===w&&l.parentCell)k=l.parentCell}c.push("</tr>");e&&n&&n.isItem(e)&&(p=n.getIdentity(e),typeof i._by_idty_paths[p]=="undefined"&&(i._by_idty_paths[p]=h.join("/")));var q,m=h.concat([]);i.treeModel&&e?i.treeModel.mayHaveChildren(e)&&(b=d.structure.cells[0][i.expandoCell||0],q=b.getOpenState(e)&&o,b=new dojox.grid.TreePath(h.join("/"),i),b=b.children(!0)||[],dojo.forEach(b,function(a,c){var b=v.split("|");b.push(b[b.length-1]+"-"+c);m.push(c);g(w,a,!1,b,m,q);m.pop()})):e&&k&&!b?(b=
d.structure.cells[0][k.level],q=b.getOpenState(e)&&o,n.hasAttribute(e,k.field)?(o=v.split("|"),o.pop(),b=new dojox.grid.TreePath(h.join("/"),i),b=b.children(!0)||[],b.length?(c[s]='<tr class="'+o.join(" ")+' dojoxGridExpandoRow" dojoxTreeGridPath="'+h.join("/")+'">',dojo.forEach(b,function(a,c){var b=v.split("|");b.push(b[b.length-1]+"-"+c);m.push(c);g(w,a,!1,b,m,q);m.pop()}),m.push(b.length),g(a,e,!0,j,m,q)):c[s]='<tr class="'+t+' dojoxGridNoChildren" dojoxTreeGridPath="'+h.join("/")+'">'):n.isItemLoaded(e)?
c[s]='<tr class="'+t+' dojoxGridNoChildren" dojoxTreeGridPath="'+h.join("/")+'">':c[0]=c[0].replace("dojoxGridRowTable","dojoxGridRowTable dojoxGridRowTableNeedsRowUpdate")):e&&!b&&j.length>1&&(c[s]='<tr class="'+j[j.length-2]+'" dojoxTreeGridPath="'+h.join("/")+'">')}else c[0].indexOf("dojoxGridRowTableNeedsRowUpdate")==-1&&(c[0]=c[0].replace("dojoxGridRowTable","dojoxGridRowTable dojoxGridRowTableNeedsRowUpdate"))};g(0,e,!1,["dojoxGridRowToggle-"+b],[b],!0);c.push("</table>");return c.join("")},
findTarget:function(a){for(;a&&a!=this.domNode;){if(a.tagName&&a.tagName.toLowerCase()=="tr")break;a=a.parentNode}return a!=this.domNode?a:null},getCellNode:function(a,b){var c=dojo.query("td[idx='"+b+"']",a)[0];if(c&&c.parentNode&&!dojo.hasClass(c.parentNode,"dojoxGridSummaryRow"))return c},decorateEvent:function(a){a.rowNode=this.findRowTarget(a.target);if(!a.rowNode)return!1;a.rowIndex=dojo.attr(a.rowNode,"dojoxTreeGridPath");this.baseDecorateEvent(a);a.cell=this.grid.getCell(a.cellIndex);return!0}}),
dojo.declare("dojox.grid._TreeView",[dojox.grid._View],{_contentBuilderClass:dojox.grid._TreeContentBuilder,_onDndDrop:function(a,b,c){this.grid&&this.grid.aggregator&&this.grid.aggregator.clearSubtotalCache();this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this.connect(this.grid,"_cleanupExpandoCache","_cleanupExpandoCache")},_cleanupExpandoCache:function(a,b){if(a!=-1)if(dojo.forEach(this.grid.layout.cells,function(a){typeof a.openStates!="undefined"&&b in a.openStates&&
delete a.openStates[b]}),typeof a=="string"&&a.indexOf("/")>-1){for(var c=new dojox.grid.TreePath(a,this.grid),d=c.parent();d;)c=d,d=c.parent();if(c=c.item())if(d=this.grid.store.getIdentity(c),typeof this._expandos[d]!="undefined"){for(var f in this._expandos[d])(c=this._expandos[d][f])&&c.destroy(),delete this._expandos[d][f];delete this._expandos[d]}}else{for(f in this._expandos)if(typeof this._expandos[f]!="undefined")for(d in this._expandos[f])(c=this._expandos[f][d])&&c.destroy();this._expandos=
{}}},postMixInProperties:function(){this.inherited(arguments);this._expandos={}},onBeforeRow:function(a,b){var c=this.grid;if(c._by_idx&&c._by_idx[a]&&c._by_idx[a].idty)c=c._by_idx[a].idty,this._expandos[c]=this._expandos[c]||{};this.inherited(arguments)},onAfterRow:function(a,b,c){dojo.forEach(dojo.query("span.dojoxGridExpando",c),function(b){if(b&&b.parentNode){var d=b.getAttribute("toggleClass"),f,g,r=this.grid;if(r._by_idx&&r._by_idx[a]&&r._by_idx[a].idty)f=r._by_idx[a].idty,g=this._expandos[f][d];
if(g){if(dojo.place(g.domNode,b,"replace"),g.itemId=b.getAttribute("itemId"),g.cellIdx=parseInt(b.getAttribute("cellIdx"),10),isNaN(g.cellIdx))g.cellIdx=-1}else g=dojo.parser.parse(b.parentNode)[0],f&&(this._expandos[f][d]=g);g.setRowNode(a,c,this)||g.domNode.parentNode.removeChild(g.domNode)}},this);var d=!1,f=this;dojo.query("tr[dojoxTreeGridPath]",c).forEach(function(a){dojo.toggleClass(a,"dojoxGridSubRowAlt",d);dojo.attr(a,"dojoxTreeGridBaseClasses",a.className);d=!d;f.grid.rows.styleRowNode(dojo.attr(a,
"dojoxTreeGridPath"),a)});this.inherited(arguments)},updateRowStyles:function(a){var b=dojo.query("tr[dojoxTreeGridPath='"+a+"']",this.domNode);b.length&&this.styleRowNode(a,b[0])},getCellNode:function(a,b){var c=dojo.query("tr[dojoxTreeGridPath='"+a+"']",this.domNode)[0];if(c)return this.content.getCellNode(c,b)}}));