/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid._ViewManager"]||(dojo._hasResource["dojox.grid._ViewManager"]=!0,dojo.provide("dojox.grid._ViewManager"),dojo.declare("dojox.grid._ViewManager",null,{constructor:function(a){this.grid=a},defaultWidth:200,views:[],resize:function(){this.onEach("resize")},render:function(){this.onEach("render")},addView:function(a){a.idx=this.views.length;this.views.push(a)},destroyViews:function(){for(var a=0,b;b=this.views[a];a++)b.destroy();this.views=[]},getContentNodes:function(){for(var a=
[],b=0,d;d=this.views[b];b++)a.push(d.contentNode);return a},forEach:function(a){for(var b=0,d;d=this.views[b];b++)a(d,b)},onEach:function(a,b){for(var b=b||[],d=0,c;c=this.views[d];d++)a in c&&c[a].apply(c,b)},normalizeHeaderNodeHeight:function(){for(var a=[],b=0,d;d=this.views[b];b++)d.headerContentNode.firstChild&&a.push(d.headerContentNode);this.normalizeRowNodeHeights(a)},normalizeRowNodeHeights:function(a){var b=0,d=[];if(this.grid.rowHeight)b=this.grid.rowHeight;else{if(a.length<=1)return;
for(var c=0,e;e=a[c];c++)if(!dojo.hasClass(e,"dojoxGridNonNormalizedCell"))d[c]=e.firstChild.offsetHeight,b=Math.max(b,d[c]);b=b>=0?b:0;dojo.isMoz&&b&&b++}for(c=0;e=a[c];c++)if(d[c]!=b)e.firstChild.style.height=b+"px"},resetHeaderNodeHeight:function(){for(var a=0,b;b=this.views[a];a++)if(b=b.headerContentNode.firstChild)b.style.height=""},renormalizeRow:function(a){for(var b=[],d=0,c,e;(c=this.views[d])&&(e=c.getRowNode(a));d++)e.firstChild.style.height="",b.push(e);this.normalizeRowNodeHeights(b)},
getViewWidth:function(a){return this.views[a].getWidth()||this.defaultWidth},measureHeader:function(){this.resetHeaderNodeHeight();this.forEach(function(a){a.headerContentNode.style.height=""});var a=0;this.forEach(function(b){a=Math.max(b.headerNode.offsetHeight,a)});return a},measureContent:function(){var a=0;this.forEach(function(b){a=Math.max(b.domNode.offsetHeight,a)});return a},findClient:function(){var a=this.grid.elasticView||-1;if(a<0)for(var b=1,d;d=this.views[b];b++)if(d.viewWidth){for(b=
1;d=this.views[b];b++)if(!d.viewWidth){a=b;break}break}a<0&&(a=Math.floor(this.views.length/2));return a},arrange:function(a,b){var d,c,e,f=this.views.length,g=b<=0?f:this.findClient(),i=function(a,b){var c=a.domNode.style,d=a.headerNode.style;dojo._isBodyLtr()?(c.left=b+"px",d.left=b+"px"):(c.right=b+"px",dojo.isMoz?(d.right=b+a.getScrollbarWidth()+"px",d.width=parseInt(d.width,10)-a.getScrollbarWidth()+"px"):d.right=b+"px");c.top="0px";d.top=0};for(d=0;(c=this.views[d])&&d<g;d++)e=this.getViewWidth(d),
c.setSize(e,0),i(c,a),e=c.headerContentNode&&c.headerContentNode.firstChild?c.getColumnsWidth()+c.getScrollbarWidth():c.domNode.offsetWidth,a+=e;d++;for(var j=b,h=f-1;(c=this.views[h])&&d<=h;h--)e=this.getViewWidth(h),c.setSize(e,0),e=c.domNode.offsetWidth,j-=e,i(c,j);g<f&&(c=this.views[g],e=Math.max(1,j-a),c.setSize(e+"px",0),i(c,a));return a},renderRow:function(a,b,d){for(var c=[],e=0,f,g;(f=this.views[e])&&(g=b[e]);e++)f=f.renderRow(a),g.appendChild(f),c.push(f);d||this.normalizeRowNodeHeights(c)},
rowRemoved:function(a){this.onEach("rowRemoved",[a])},updateRow:function(a,b){for(var d=0,c;c=this.views[d];d++)c.updateRow(a);b||this.renormalizeRow(a)},updateRowStyles:function(a){this.onEach("updateRowStyles",[a])},setScrollTop:function(a){for(var b=a,d=0,c;c=this.views[d];d++)if(b=c.setScrollTop(a),dojo.isIE&&c.headerNode&&c.scrollboxNode)c.headerNode.scrollLeft=c.scrollboxNode.scrollLeft;return b},getFirstScrollingView:function(){for(var a=0,b;b=this.views[a];a++)if(b.hasHScrollbar()||b.hasVScrollbar())return b;
return null}}));