/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.grid.LazyTreeGrid"])dojo._hasResource["dojox.grid.LazyTreeGrid"]=!0,dojo.provide("dojox.grid.LazyTreeGrid"),dojo.require("dojox.grid._View"),dojo.require("dojox.grid.TreeGrid"),dojo.require("dojox.grid.cells.tree"),dojo.require("dojox.grid.LazyTreeGridStoreModel"),dojo.declare("dojox.grid._LazyExpando",[dijit._Widget,dijit._Templated],{itemId:"",cellIdx:-1,view:null,rowIdx:-1,expandoCell:null,level:0,open:!1,templateString:'<div class="dojoxGridExpando"\n\t><div class="dojoxGridExpandoNode" dojoAttachEvent="onclick:onToggle"\n\t\t><div class="dojoxGridExpandoNodeInner" dojoAttachPoint="expandoInner"></div\n\t></div\n></div>\n',
onToggle:function(a){this.setOpen(!this.view.grid.cache.getExpandoStatusByRowIndex(this.rowIdx));try{dojo.stopEvent(a)}catch(b){}},setOpen:function(a){var b=this.view.grid,c=b.cache.getItemByRowIndex(this.rowIdx);if(b.treeModel.mayHaveChildren(c)){if(c&&!b._loading)b.stateChangeNode=this.domNode,b.cache.updateCache(this.rowIdx,{expandoStatus:a}),b.expandoFetch(this.rowIdx,a),this.open=a;this._updateOpenState(c)}else b.stateChangeNode=null},_updateOpenState:function(a){var b=this.view.grid;if(a&&b.treeModel.mayHaveChildren(a))a=
b.cache.getExpandoStatusByRowIndex(this.rowIdx),this.expandoInner.innerHTML=a?"-":"+",dojo.toggleClass(this.domNode,"dojoxGridExpandoOpened",a),dijit.setWaiState(this.domNode.parentNode,"expanded",a)},setRowNode:function(a,b,c){if(this.cellIdx<0||!this.itemId)return!1;this._initialized=!1;this.view=c;this.rowIdx=a;this.expandoCell=c.structure.cells[0][this.cellIdx];if((a=this.domNode)&&a.parentNode&&a.parentNode.parentNode)this._tableRow=a.parentNode.parentNode;dojo.style(this.domNode,"marginLeft",
this.level*1.125+"em");this._updateOpenState(c.grid.cache.getItemByRowIndex(this.rowIdx));return!0}}),dojo.declare("dojox.grid._TreeGridContentBuilder",dojox.grid._ContentBuilder,{generateHtml:function(a,b){var c=this.getTableArray(),d=this.grid,f=this.view.structure.cells,e=d.getItem(b),g=0,h=d.cache.getTreePathByRowIndex(b),m=[],n=[];dojox.grid.util.fire(this.view,"onBeforeRow",[b,f]);e!==null&&h!==null&&(m=h.split("/"),g=m.length-1,n[0]="dojoxGridRowToggle-"+m.join("-"),d.treeModel.mayHaveChildren(e)||
n.push("dojoxGridNoChildren"));for(var d=0,o;o=f[d];d++)if(!o.hidden&&!o.header){h='<tr style="" class="'+n.join(" ")+'" dojoxTreeGridPath="'+m.join("/")+'" dojoxTreeGridBaseClasses="'+n.join(" ")+'">';c.push(h);var h=0,i=this._getColSpans(g),r=0,s=[];i&&dojo.forEach(i,function(a){for(var b=0;o[b];b++)b>=a.start&&b<=a.end&&(r+=this._getCellWidth(o,b));s.push(r);r=0},this);for(var p=0,j,k,l,q;j=o[p];p++)k=j.markup,l=j.customClasses=[],q=j.customStyles=[],i&&i[h]&&p>=i[h].start&&p<=i[h].end?p==(i[h].primary?
i[h].primary:i[h].start)?(k[5]=j.formatAtLevel(m,e,g,!1,n[0],l,b),k[1]=l.join(" "),l=dojo.marginBox(j.getHeaderNode()).w-dojo.contentBox(j.getHeaderNode()).w,q=j.customStyles=["width:"+(s[h]-l)+"px"],k[3]=q.join(";"),c.push.apply(c,k)):p==i[h].end&&h++:(k[5]=j.formatAtLevel(m,e,g,!1,n[0],l,b),k[1]=l.join(" "),k[3]=q.join(";"),c.push.apply(c,k));c.push("</tr>")}c.push("</table>");return c.join("")},_getColSpans:function(a){var b=this.grid.colSpans;return b&&b[a]?b[a]:null},_getCellWidth:function(a,
b){var c=a[b].getHeaderNode();if(b==a.length-1||dojo.every(a.slice(b+1),function(a){return a.hidden})){var d=dojo.position(a[b].view.headerContentNode.firstChild);return d.x+d.w-dojo.position(c).x}else return d=a[b+1].getHeaderNode(),dojo.position(d).x-dojo.position(c).x}}),dojo.declare("dojox.grid._TreeGridView",[dojox.grid._View],{_contentBuilderClass:dojox.grid._TreeGridContentBuilder,postCreate:function(){this.inherited(arguments);this._expandos={};this.connect(this.grid,"_cleanupExpandoCache",
"_cleanupExpandoCache")},_cleanupExpandoCache:function(a,b){if(a!=-1){dojo.forEach(this.grid.layout.cells,function(a){a.openStates&&b in a.openStates&&delete a.openStates[b]});for(var c in this._expandos)this._expandos[c]&&this._expandos[c].destroy();this._expandos={}}},onAfterRow:function(a,b,c){dojo.query("span.dojoxGridExpando",c).forEach(function(b){if(b&&b.parentNode){var f,e,g=this.grid._by_idx;if(g&&g[a]&&g[a].idty)f=g[a].idty,e=this._expandos[f];if(e){if(dojo.place(e.domNode,b,"replace"),
e.itemId=b.getAttribute("itemId"),e.cellIdx=parseInt(b.getAttribute("cellIdx"),10),isNaN(e.cellIdx))e.cellIdx=-1}else e=dojo.parser.parse(b.parentNode)[0],f&&(this._expandos[f]=e);e.setRowNode(a,c,this)||e.domNode.parentNode.removeChild(e.domNode)}},this);this.inherited(arguments)}}),dojox.grid.cells.LazyTreeCell=dojo.mixin(dojo.clone(dojox.grid.cells.TreeCell),{formatAtLevel:function(a,b,c,d,f,e,g){if(!b)return this.formatIndexes(g,a,b,c);dojo.isArray(a)||(a=[a]);d=d="";if(this.isCollapsable){var d=
this.grid.store,h="";b&&d.isItem(b)&&(h=d.getIdentity(b));e.push("dojoxGridExpandoCell");d="<span "+dojo._scopeName+'Type="dojox.grid._LazyExpando" level="'+c+'" class="dojoxGridExpando"" toggleClass="'+f+'" itemId="'+h+'" cellIdx="'+this.index+'"></span>'}d+=this.formatIndexes(g,a,b,c);this.grid.focus.cell&&this.index==this.grid.focus.cell.index&&a.join("/")==this.grid.focus.rowIndex&&e.push(this.grid.focus.focusClass);return d},formatIndexes:function(a,b,c,d){var f=this.grid.edit.info,c=this.get?
this.get(b[0],c,b):this.value||this.defaultValue;return this.editable&&(this.alwaysEditing||f.rowIndex==b[0]&&f.cell==this)?this.formatEditing(c,a,b):this._defaultFormat(c,[c,a,d,this])}}),dojo.declare("dojox.grid._LazyTreeLayout",dojox.grid._Layout,{setStructure:function(a){var b=a;this.grid&&!dojo.every(b,function(a){return"cells"in a})&&(b=arguments[0]=[{cells:[b]}]);if(b.length==1&&b[0].cells.length==1)b[0].type="dojox.grid._TreeGridView",this._isCollapsable=!0,b[0].cells[0][this.grid.expandoCell].isCollapsable=
!0;this.inherited(arguments)},addCellDef:function(a,b,c){var d=this.inherited(arguments);return dojo.mixin(d,dojox.grid.cells.LazyTreeCell)}}),dojo.declare("dojox.grid.TreeGridItemCache",null,{unInit:!0,items:null,constructor:function(a){this.rowsPerPage=a.rowsPerPage;this._buildCache(a.rowsPerPage)},_buildCache:function(a){this.items=[];for(var b=0;b<a;b++)this.cacheItem(b,{item:null,treePath:b+"",expandoStatus:!1})},cacheItem:function(a,b){this.items[a]=dojo.mixin({item:null,treePath:"",expandoStatus:!1},
b)},insertItem:function(a,b){this.items.splice(a,0,dojo.mixin({item:null,treePath:"",expandoStatus:!1},b))},initCache:function(a){if(this.unInit)this._buildCache(a),this.unInit=!1},getItemByRowIndex:function(a){return this.items[a]?this.items[a].item:null},getItemByTreePath:function(a){for(var b=0,c=this.items.length;b<c;b++)if(this.items[b].treePath===a)return this.items[b].item;return null},getTreePathByRowIndex:function(a){return this.items[a]?this.items[a].treePath:null},getExpandoStatusByRowIndex:function(a){return this.items[a]?
this.items[a].expandoStatus:null},getInfoByItem:function(a){for(var b=0,c=this.items.length;b<c;b++)if(this.items[b].item==a)return dojo.mixin({rowIdx:b},this.items[b]);return null},updateCache:function(a,b){this.items[a]&&dojo.mixin(this.items[a],b)},deleteItem:function(a){this.items[a]&&this.items.splice(a,1)},cleanChildren:function(a){for(var a=this.getTreePathByRowIndex(a),b=this.items.length-1;b>=0;b--)this.items[b].treePath.indexOf(a)===0&&this.items[b].treePath!==a&&this.items.splice(b,1)},
emptyCache:function(){this.unInit=!0;this._buildCache(this.rowsPerPage)},cleanupCache:function(){this.items=null}}),dojo.declare("dojox.grid.LazyTreeGrid",dojox.grid.TreeGrid,{treeModel:null,_layoutClass:dojox.grid._LazyTreeLayout,colSpans:null,postCreate:function(){this.inherited(arguments);this.cache=new dojox.grid.TreeGridItemCache(this);if(!this.treeModel||!(this.treeModel instanceof dijit.tree.ForestStoreModel))throw Error("dojox.grid.LazyTreeGrid: must use a treeModel and treeModel must be an instance of dijit.tree.ForestStoreModel");
dojo.addClass(this.domNode,"dojoxGridTreeModel");dojo.setSelectable(this.domNode,this.selectable)},createManagers:function(){this.rows=new dojox.grid._RowManager(this);this.focus=new dojox.grid._FocusManager(this);this.edit=new dojox.grid._EditManager(this)},createSelection:function(){this.selection=new dojox.grid.DataSelection(this)},setModel:function(a){a&&(this._setModel(a),this._refresh(!0))},setStore:function(a,b,c){if(a)this._setQuery(b,c),this.treeModel.query=b,this.treeModel.store=a,this.treeModel.root.children=
[],this.setModel(this.treeModel)},_setQuery:function(a,b){this.inherited(arguments);this.treeModel.query=a},destroy:function(){this._cleanup();this.inherited(arguments)},_cleanup:function(){this.cache.emptyCache();this._cleanupExpandoCache()},setSortIndex:function(a,b){this.canSort(a+1)&&this._cleanup();this.inherited(arguments)},_refresh:function(a){this._cleanup();this.inherited(arguments)},render:function(){this.inherited(arguments);this.setScrollTop(this.scrollTop)},_onNew:function(a,b){var c=
!1,d;b&&this.store.isItem(b.item)&&dojo.some(this.treeModel.childrenAttrs,function(a){return a===b.attribute})&&(c=!0,d=this.cache.getInfoByItem(b.item));c?d&&d.expandoStatus&&d.rowIdx>=0?(this.expandoFetch(d.rowIdx,!1),this.expandoFetch(d.rowIdx,!0)):d&&d.rowIdx&&this.updateRow(d.rowIdx):(this.inherited(arguments),c=this.cache.items,c=parseInt(c[c.length-1].treePath.split("/")[0],10)+1+"",this.cache.insertItem(this.get("rowCount"),{item:a,treePath:c,expandoStatus:!1}))},_onDelete:function(){this._pages=
[];this._eop=this._bop=-1;this._refresh()},_cleanupExpandoCache:function(){},_fetch:function(a){a=a||0;this.reqQueue=[];for(var b=0,c=[],d=Math.min(this.rowsPerPage,this.cache.items.length-a),b=a;b<d;b++)if(this.cache.getItemByRowIndex(b))c.push(this.cache.getItemByRowIndex(b));else break;if(c.length===d)this._onFetchComplete(c,{startRowIdx:a,count:d});else{this.reqQueueIndex=0;for(var f=c="",e=a,g=this.cache.getTreePathByRowIndex(a),d=0,b=a+1;b<a+this.rowsPerPage;b++){if(!this.cache.getTreePathByRowIndex(b))break;
c=this.cache.getTreePathByRowIndex(b-1).split("/").length-1;f=this.cache.getTreePathByRowIndex(b).split("/").length-1;c!==f?(this.reqQueue.push({startTreePath:g,startRowIdx:e,count:d+1}),d=0,e=b,g=this.cache.getTreePathByRowIndex(b)):d++}this.reqQueue.push({startTreePath:g,startRowIdx:e,count:d+1});a=this.reqQueue.length;for(b=0;b<a;b++)this._fetchItems(b,dojo.hitch(this,"_onFetchBegin"),dojo.hitch(this,"_onFetchComplete"),dojo.hitch(this,"_onFetchError"))}},_fetchItems:function(a,b,c,d){if(!this._loading)this._loading=
!0,this.showMessage(this.loadingMessage);var f=this.reqQueue[a].startTreePath.split("/").length-1;this._pending_requests[this.reqQueue[a].startRowIdx]=!0;if(f===0)this.store.fetch({start:parseInt(this.reqQueue[a].startTreePath,10),startRowIdx:this.reqQueue[a].startRowIdx,count:this.reqQueue[a].count,query:this.query,sort:this.getSortProps(),queryOptions:this.queryOptions,onBegin:b,onComplete:c,onError:d});else{b=this.reqQueue[a].startTreePath;f=b.substring(0,b.lastIndexOf("/"));b=b.substring(b.lastIndexOf("/")+
1);f=this.cache.getItemByTreePath(f);if(!f)throw Error("Lazy loading TreeGrid on fetch error:");var e=this.store.getIdentity(f);this.queryObj={start:parseInt(b,10),startRowIdx:this.reqQueue[a].startRowIdx,count:this.reqQueue[a].count,parentId:e,sort:this.getSortProps()};this.treeModel.getChildren(f,c,d,this.queryObj)}},_onFetchBegin:function(a,b){this.cache.initCache(a);a=this.cache.items.length;this.inherited(arguments)},filter:function(a,b){this.cache.emptyCache();this.inherited(arguments)},_onFetchComplete:function(a,
b){var c="",d,f,e;b?(d=b.startRowIdx,f=b.count,e=0):(d=this.queryObj.startRowIdx,f=this.queryObj.count,e=this.queryObj.start);for(var g=0;g<f;g++)(c=this.cache.getTreePathByRowIndex(d+g))&&(this.cache.getItemByRowIndex(d+g)||this.cache.cacheItem(d+g,{item:a[e+g],treePath:c,expandoStatus:!1}));this._pending_requests[d]=!1;if(this.scroller){c=Math.min(f,a.length);for(g=0;g<c;g++)this._addItem(a[e+g],d+g,!0);this.updateRows(d,c);this._lastScrollTop&&this.setScrollTop(this._lastScrollTop);if(this._loading)this._loading=
!1,this.cache.items.length?this.showMessage():this.showMessage(this.noDataMessage)}},expandoFetch:function(a,b){if(!this._loading){this._loading=!0;this.toggleLoadingClass(!0);var c=this.cache.getItemByRowIndex(a);this.expandoRowIndex=a;this._pages=[];if(b){var d={start:0,count:this.keepRows,parentId:this.store.getIdentity(c),sort:this.getSortProps()};this.treeModel.getChildren(c,dojo.hitch(this,"_onExpandoComplete"),dojo.hitch(this,"_onFetchError"),d)}else{this.cache.cleanChildren(a);c=a+1;for(d=
this._by_idx.length;c<d;c++)delete this._by_idx[c];this.updateRowCount(this.cache.items.length);this.cache.getTreePathByRowIndex(a+1)?this._fetch(a+1):this._fetch(a);this.toggleLoadingClass(!1)}}},_onExpandoComplete:function(a,b,c){var b=this.cache.getTreePathByRowIndex(this.expandoRowIndex),c=c&&!isNaN(parseInt(c,10))?parseInt(c,10):a.length,d,f=0,e=this._by_idx.length;for(d=this.expandoRowIndex+1;f<c;d++,f++)this.cache.insertItem(d,{item:null,treePath:b+"/"+f,expandoStatus:!1});this.updateRowCount(this.cache.items.length);
for(d=this.expandoRowIndex+1;d<e;d++)delete this._by_idx[d];this.cache.updateCache(this.expandoRowIndex,{childrenNum:c});for(d=0;d<c;d++)this.cache.updateCache(this.expandoRowIndex+1+d,{item:a[d]});for(d=0;d<Math.min(c,this.keepRows);d++)this._addItem(a[d],this.expandoRowIndex+1+d,!1),this.updateRow(this.expandoRowIndex+1+d);this.toggleLoadingClass(!1);this.stateChangeNode=null;if(this._loading)this._loading=!1;c<this.keepRows&&this.cache.getTreePathByRowIndex(this.expandoRowIndex+1+c)&&this._fetch(this.expandoRowIndex+
1+c)},toggleLoadingClass:function(a){this.stateChangeNode&&dojo.toggleClass(this.stateChangeNode,"dojoxGridExpandoLoading",a)},styleRowNode:function(a,b){b&&this.rows.styleRowNode(a,b)},onStyleRow:function(a){if(this.layout._isCollapsable){var b=dojo.attr(a.node,"dojoxTreeGridBaseClasses");if(b)a.customClasses=b;b=a;b.customClasses+=(b.odd?" dojoxGridRowOdd":"")+(b.selected?" dojoxGridRowSelected":"")+(b.over?" dojoxGridRowOver":"");this.focus.styleRow(b);this.edit.styleRow(b)}else this.inherited(arguments)},
dokeydown:function(a){if(!a.altKey&&!a.metaKey){var b=dojo.keys,c=a.target,c=c&&c.firstChild?dijit.byId(c.firstChild.id):null;if(a.keyCode===b.ENTER&&c instanceof dojox.grid._LazyExpando)c.onToggle();this.onKeyDown(a)}}}),dojox.grid.LazyTreeGrid.markupFactory=function(a,b,c,d){return dojox.grid.TreeGrid.markupFactory(a,b,c,d)};