/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.TreeSelection"]||(dojo._hasResource["dojox.grid.TreeSelection"]=!0,dojo.provide("dojox.grid.TreeSelection"),dojo.require("dojox.grid.DataSelection"),dojo.declare("dojox.grid.TreeSelection",dojox.grid.DataSelection,{setMode:function(a){this.selected={};this.sorted_sel=[];this.sorted_ltos={};this.sorted_stol={};dojox.grid.DataSelection.prototype.setMode.call(this,a)},addToSelection:function(a){if(this.mode!="none"){var b=null,b=typeof a=="number"||typeof a=="string"?a:
this.grid.getItemIndex(a);if(this.selected[b])this.selectedIndex=b;else if(this.onCanSelect(b)!==!1)this.selectedIndex=b,a=dojo.query("tr[dojoxTreeGridPath='"+b+"']",this.grid.domNode),a.length&&dojo.attr(a[0],"aria-selected","true"),this._beginUpdate(),this.selected[b]=!0,this._insertSortedSelection(b),this.onSelected(b),this._endUpdate()}},deselect:function(a){if(this.mode!="none"){var b=null,b=typeof a=="number"||typeof a=="string"?a:this.grid.getItemIndex(a);if(this.selectedIndex==b)this.selectedIndex=
-1;this.selected[b]&&this.onCanDeselect(b)!==!1&&(a=dojo.query("tr[dojoxTreeGridPath='"+b+"']",this.grid.domNode),a.length&&dojo.attr(a[0],"aria-selected","false"),this._beginUpdate(),delete this.selected[b],this._removeSortedSelection(b),this.onDeselected(b),this._endUpdate())}},getSelected:function(){var a=[],b;for(b in this.selected)this.selected[b]&&a.push(this.grid.getItem(b));return a},getSelectedCount:function(){var a=0,b;for(b in this.selected)this.selected[b]&&a++;return a},_bsearch:function(a){for(var b=
this.sorted_sel,d=b.length-1,e=0,c;e<=d;){var f=this._comparePaths(b[c=e+d>>1],a);if(f<0)e=c+1;else if(f>0)d=c-1;else return c}return f<0?c-f:c},_comparePaths:function(a,b){for(var d=0,e=a.length<b.length?a.length:b.length;d<e;d++){if(a[d]<b[d])return-1;if(a[d]>b[d])return 1}return a.length<b.length?-1:a.length>b.length?1:0},_insertSortedSelection:function(a){var a=String(a),b=this.sorted_sel,d=this.sorted_ltos,e=this.sorted_stol,c=a.split("/"),c=dojo.map(c,function(a){return parseInt(a,10)});d[c]=
a;e[a]=c;b.length===0?b.push(c):b.length==1?this._comparePaths(b[0],c)==1?b.unshift(c):b.push(c):this.sorted_sel.splice(this._bsearch(c),0,c)},_removeSortedSelection:function(a){var a=String(a),b=this.sorted_sel,d=this.sorted_ltos,e=this.sorted_stol;if(b.length!==0){var c=e[a];if(c){var f=this._bsearch(c);f>-1&&(delete d[c],delete e[a],b.splice(f,1))}}},getFirstSelected:function(){if(!this.sorted_sel.length||this.mode=="none")return-1;var a=this.sorted_sel[0];if(!a)return-1;a=this.sorted_ltos[a];
return!a?-1:a},getNextSelected:function(a){if(!this.sorted_sel.length||this.mode=="none")return-1;a=this.sorted_stol[String(a)];if(!a)return-1;a=this.sorted_sel[this._bsearch(a)+1];return!a?-1:this.sorted_ltos[a]},_range:function(a,b,d){!dojo.isString(a)&&a<0&&(a=b);var e=this.grid,a=new dojox.grid.TreePath(String(a),e),b=new dojox.grid.TreePath(String(b),e);a.compare(b)>0&&(e=a,a=b,b=e);b=b._str;for(d(a._str);a=a.next();){if(a._str==b)break;d(a._str)}d(b)}}));