/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo.back"]||(dojo._hasResource["dojo.back"]=!0,dojo.provide("dojo.back"),dojo.getObject("back",!0,dojo),function(){function f(){var a=c.pop();if(a){var b=c[c.length-1];!b&&c.length==0&&(b=j);b&&(b.kwArgs.back?b.kwArgs.back():b.kwArgs.backButton?b.kwArgs.backButton():b.kwArgs.handle&&b.kwArgs.handle("back"));e.push(a)}}function m(){var a=e.pop();a&&(a.kwArgs.forward?a.kwArgs.forward():a.kwArgs.forwardButton?a.kwArgs.forwardButton():a.kwArgs.handle&&a.kwArgs.handle("forward"),c.push(a))}
function k(a,b,c){return{url:a,kwArgs:b,urlHash:c}}function n(a){a=a.split("?");return a.length<2?null:a[1]}function s(){var a=(dojo.config.dojoIframeHistoryUrl||dojo.moduleUrl("dojo","resources/iframe_history.html"))+"?"+(new Date).getTime();o=!0;if(i)dojo.isWebKit?i.location=a:window.frames[i.name].location=a;return a}function w(){if(!p){var a=c.length,b=l();(b===t||window.location.href==u)&&a==1?f():e.length>0&&e[e.length-1].urlHash===b?m():a>=2&&c[a-2]&&c[a-2].urlHash===b&&f()}}var d=dojo.back,
l=d.getHash=function(){var a=window.location.hash;a.charAt(0)=="#"&&(a=a.substring(1));return dojo.isMozilla?a:decodeURIComponent(a)},q=d.setHash=function(a){a||(a="");window.location.hash=encodeURIComponent(a)},u=typeof window!=="undefined"?window.location.href:"",t=typeof window!=="undefined"?l():"",j=null,v=null,r=null,i=null,e=[],c=[],o=!1,p=!1;d.goBack=f;d.goForward=m;d.init=function(){if(!dojo.byId("dj_history")){var a=dojo.config.dojoIframeHistoryUrl||dojo.moduleUrl("dojo","resources/iframe_history.html");
dojo._postLoad?console.error("dojo.back.init() must be called before the DOM has loaded. If using xdomain loading or djConfig.debugAtAllCosts, include dojo.back in a build layer."):document.write('<iframe style="border:0;width:1px;height:1px;position:absolute;visibility:hidden;bottom:0;right:0;" name="dj_history" id="dj_history" src="'+a+'"></iframe>')}};d.setInitialState=function(a){j=k(u,a,t)};d.addToHistory=function(a){e=[];var b=null,h=null;if(!i)dojo.config.useXDomain&&!dojo.config.dojoIframeHistoryUrl&&
console.warn("dojo.back: When using cross-domain Dojo builds, please save iframe_history.html to your domain and set djConfig.dojoIframeHistoryUrl to the path on your domain to iframe_history.html"),i=window.frames.dj_history;r||(r=dojo.create("a",{style:{display:"none"}},dojo.body()));if(a.changeUrl){b=""+(a.changeUrl!==!0?a.changeUrl:(new Date).getTime());if(c.length==0&&j.urlHash==b){j=k(h,a,b);return}else if(c.length>0&&c[c.length-1].urlHash==b){c[c.length-1]=k(h,a,b);return}p=!0;setTimeout(function(){q(b);
p=!1},1);r.href=b;if(dojo.isIE){var h=s(),d=a.back||a.backButton||a.handle,g=function(a){l()!=""&&setTimeout(function(){q(b)},1);d.apply(this,[a])};if(a.back)a.back=g;else if(a.backButton)a.backButton=g;else if(a.handle)a.handle=g;var f=a.forward||a.forwardButton||a.handle,g=function(a){l()!=""&&q(b);f&&f.apply(this,[a])};if(a.forward)a.forward=g;else if(a.forwardButton)a.forwardButton=g;else if(a.handle)a.handle=g}else dojo.isIE||v||(v=setInterval(w,200))}else h=s();c.push(k(h,a,b))};d._iframeLoaded=
function(a,b){var d=n(b.href);d==null?c.length==1&&f():o?o=!1:c.length>=2&&d==n(c[c.length-2].url)?f():e.length>0&&d==n(e[e.length-1].url)&&m()}}());