/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo.fx"]||(dojo._hasResource["dojo.fx"]=!0,dojo.provide("dojo.fx"),dojo.require("dojo.fx.Toggler"),function(){var a=dojo,i={_fire:function(b,a){this[b]&&this[b].apply(this,a||[]);return this}},g=function(b){this._index=-1;this._animations=b||[];this._current=this._onAnimateCtx=this._onEndCtx=null;this.duration=0;a.forEach(this._animations,function(a){this.duration+=a.duration;a.delay&&(this.duration+=a.delay)},this)};a.extend(g,{_onAnimate:function(){this._fire("onAnimate",arguments)},
_onEnd:function(){a.disconnect(this._onAnimateCtx);a.disconnect(this._onEndCtx);this._onAnimateCtx=this._onEndCtx=null;this._index+1==this._animations.length?this._fire("onEnd"):(this._current=this._animations[++this._index],this._onAnimateCtx=a.connect(this._current,"onAnimate",this,"_onAnimate"),this._onEndCtx=a.connect(this._current,"onEnd",this,"_onEnd"),this._current.play(0,!0))},play:function(b,c){if(!this._current)this._current=this._animations[this._index=0];if(!c&&this._current.status()==
"playing")return this;var d=a.connect(this._current,"beforeBegin",this,function(){this._fire("beforeBegin")}),e=a.connect(this._current,"onBegin",this,function(a){this._fire("onBegin",arguments)}),j=a.connect(this._current,"onPlay",this,function(b){this._fire("onPlay",arguments);a.disconnect(d);a.disconnect(e);a.disconnect(j)});this._onAnimateCtx&&a.disconnect(this._onAnimateCtx);this._onAnimateCtx=a.connect(this._current,"onAnimate",this,"_onAnimate");this._onEndCtx&&a.disconnect(this._onEndCtx);
this._onEndCtx=a.connect(this._current,"onEnd",this,"_onEnd");this._current.play.apply(this._current,arguments);return this},pause:function(){if(this._current){var b=a.connect(this._current,"onPause",this,function(c){this._fire("onPause",arguments);a.disconnect(b)});this._current.pause()}return this},gotoPercent:function(b,c){this.pause();var d=this.duration*b;this._current=null;a.some(this._animations,function(a){if(a.duration<=d)return this._current=a,!0;d-=a.duration;return!1});this._current&&
this._current.gotoPercent(d/this._current.duration,c);return this},stop:function(b){if(this._current){if(b){for(;this._index+1<this._animations.length;++this._index)this._animations[this._index].stop(!0);this._current=this._animations[this._index]}var c=a.connect(this._current,"onStop",this,function(b){this._fire("onStop",arguments);a.disconnect(c)});this._current.stop()}return this},status:function(){return this._current?this._current.status():"stopped"},destroy:function(){this._onAnimateCtx&&a.disconnect(this._onAnimateCtx);
this._onEndCtx&&a.disconnect(this._onEndCtx)}});a.extend(g,i);dojo.fx.chain=function(a){return new g(a)};var h=function(b){this._animations=b||[];this._connects=[];this.duration=this._finished=0;a.forEach(b,function(b){var c=b.duration;b.delay&&(c+=b.delay);if(this.duration<c)this.duration=c;this._connects.push(a.connect(b,"onEnd",this,"_onEnd"))},this);this._pseudoAnimation=new a.Animation({curve:[0,1],duration:this.duration});var c=this;a.forEach(["beforeBegin","onBegin","onPlay","onAnimate","onPause",
"onStop","onEnd"],function(b){c._connects.push(a.connect(c._pseudoAnimation,b,function(){c._fire(b,arguments)}))})};a.extend(h,{_doAction:function(b,c){a.forEach(this._animations,function(a){a[b].apply(a,c)});return this},_onEnd:function(){++this._finished>this._animations.length&&this._fire("onEnd")},_call:function(a,c){var d=this._pseudoAnimation;d[a].apply(d,c)},play:function(a,c){this._finished=0;this._doAction("play",arguments);this._call("play",arguments);return this},pause:function(){this._doAction("pause",
arguments);this._call("pause",arguments);return this},gotoPercent:function(b,c){var d=this.duration*b;a.forEach(this._animations,function(a){a.gotoPercent(a.duration<d?1:d/a.duration,c)});this._call("gotoPercent",arguments);return this},stop:function(a){this._doAction("stop",arguments);this._call("stop",arguments);return this},status:function(){return this._pseudoAnimation.status()},destroy:function(){a.forEach(this._connects,dojo.disconnect)}});a.extend(h,i);dojo.fx.combine=function(a){return new h(a)};
dojo.fx.wipeIn=function(b){var c=b.node=a.byId(b.node),d=c.style,e,b=a.animateProperty(a.mixin({properties:{height:{start:function(){e=d.overflow;d.overflow="hidden";if(d.visibility=="hidden"||d.display=="none")return d.height="1px",d.display="",d.visibility="",1;else{var b=a.style(c,"height");return Math.max(b,1)}},end:function(){return c.scrollHeight}}}},b));a.connect(b,"onEnd",function(){d.height="auto";d.overflow=e});return b};dojo.fx.wipeOut=function(b){var c=(b.node=a.byId(b.node)).style,d,
b=a.animateProperty(a.mixin({properties:{height:{end:1}}},b));a.connect(b,"beforeBegin",function(){d=c.overflow;c.overflow="hidden";c.display=""});a.connect(b,"onEnd",function(){c.overflow=d;c.height="auto";c.display="none"});return b};dojo.fx.slideTo=function(b){var c=null,d=null,e=function(b){return function(){var e=a.getComputedStyle(b),f=e.position;c=f=="absolute"?b.offsetTop:parseInt(e.top)||0;d=f=="absolute"?b.offsetLeft:parseInt(e.left)||0;if(f!="absolute"&&f!="relative")e=a.position(b,!0),
c=e.y,d=e.x,b.style.position="absolute",b.style.top=c+"px",b.style.left=d+"px"}}(b.node=a.byId(b.node));e();b=a.animateProperty(a.mixin({properties:{top:b.top||0,left:b.left||0}},b));a.connect(b,"beforeBegin",b,e);return b}}());