/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojo.number"])dojo._hasResource["dojo.number"]=!0,dojo.provide("dojo.number"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojo.cldr","number",null,"ROOT,ar,ca,cs,da,de,el,en,en-au,en-gb,es,fi,fr,fr-ch,he,hu,it,ja,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-hant,zh-hk"),dojo.require("dojo.string"),dojo.require("dojo.regexp"),dojo.getObject("number",!0,dojo),dojo.number.format=function(c,a){var a=dojo.mixin({},a||{}),b=dojo.i18n.normalizeLocale(a.locale),b=dojo.i18n.getLocalization("dojo.cldr",
"number",b);a.customs=b;b=a.pattern||b[(a.type||"decimal")+"Format"];return isNaN(c)||Math.abs(c)==Infinity?null:dojo.number._applyPattern(c,b,a)},dojo.number._numberPatternRE=/[#0,]*[#0](?:\.0*#*)?/,dojo.number._applyPattern=function(c,a,b){var b=b||{},e=b.customs.group,d=b.customs.decimal,a=a.split(";"),f=a[0],a=a[c<0?1:0]||"-"+f;if(a.indexOf("%")!=-1)c*=100;else if(a.indexOf("\u2030")!=-1)c*=1E3;else if(a.indexOf("\u00a4")!=-1)e=b.customs.currencyGroup||e,d=b.customs.currencyDecimal||d,a=a.replace(/\u00a4{1,3}/,
function(c){return b[["symbol","currency","displayName"][c.length-1]]||b.currency||""});else if(a.indexOf("E")!=-1)throw Error("exponential notation not supported");var g=dojo.number._numberPatternRE,f=f.match(g);if(!f)throw Error("unable to find a number expression in pattern: "+a);if(b.fractional===!1)b.places=0;return a.replace(g,dojo.number._formatAbsolute(c,f[0],{decimal:d,group:e,places:b.places,round:b.round}))},dojo.number.round=function(c,a,b){b=10/(b||10);return(b*+c).toFixed(a)/b},(0.9).toFixed()==
0&&function(){var c=dojo.number.round;dojo.number.round=function(a,b,e){var d=Math.pow(10,-b||0),f=Math.abs(a);if(!a||f>=d||f*Math.pow(10,b+1)<5)d=0;return c(a,b,e)+(a>0?d:-d)}}(),dojo.number._formatAbsolute=function(c,a,b){b=b||{};if(b.places===!0)b.places=0;if(b.places===Infinity)b.places=6;var a=a.split("."),e=typeof b.places=="string"&&b.places.indexOf(","),d=b.places;if(e)d=b.places.substring(e+1);else if(!(d>=0))d=(a[1]||[]).length;b.round<0||(c=dojo.number.round(c,d,b.round));var c=String(Math.abs(c)).split("."),
f=c[1]||"";if(a[1]||b.places){if(e)b.places=b.places.substring(0,e);e=b.places!==void 0?b.places:a[1]&&a[1].lastIndexOf("0")+1;e>f.length&&(c[1]=dojo.string.pad(f,e,"0",!0));d<f.length&&(c[1]=f.substr(0,d))}else c[1]&&c.pop();d=a[0].replace(",","");e=d.indexOf("0");e!=-1&&(e=d.length-e,e>c[0].length&&(c[0]=dojo.string.pad(c[0],e)),d.indexOf("#")==-1&&(c[0]=c[0].substr(c[0].length-e)));var d=a[0].lastIndexOf(","),g,i;d!=-1&&(g=a[0].length-d-1,a=a[0].substr(0,d),d=a.lastIndexOf(","),d!=-1&&(i=a.length-
d-1));a=[];for(d=c[0];d;)e=d.length-g,a.push(e>0?d.substr(e):d),d=e>0?d.slice(0,e):"",i&&(g=i,delete i);c[0]=a.reverse().join(b.group||",");return c.join(b.decimal||".")},dojo.number.regexp=function(c){return dojo.number._parseInfo(c).regexp},dojo.number._parseInfo=function(c){var c=c||{},a=dojo.i18n.normalizeLocale(c.locale),a=dojo.i18n.getLocalization("dojo.cldr","number",a),b=c.pattern||a[(c.type||"decimal")+"Format"],e=a.group,d=a.decimal,f=1;if(b.indexOf("%")!=-1)f/=100;else if(b.indexOf("\u2030")!=
-1)f/=1E3;else{var g=b.indexOf("\u00a4")!=-1;g&&(e=a.currencyGroup||e,d=a.currencyDecimal||d)}a=b.split(";");a.length==1&&a.push("-"+a[0]);a=dojo.regexp.buildGroupRE(a,function(a){a="(?:"+dojo.regexp.escapeString(a,".")+")";return a.replace(dojo.number._numberPatternRE,function(a){var b={signed:!1,separator:c.strict?e:[e,""],fractional:c.fractional,decimal:d,exponent:!1},a=a.split("."),h=c.places;a.length==1&&f!=1&&(a[1]="###");if(a.length==1||h===0)b.fractional=!1;else{h===void 0&&(h=c.pattern?a[1].lastIndexOf("0")+
1:Infinity);if(h&&c.fractional==void 0)b.fractional=!0;!c.places&&h<a[1].length&&(h+=","+a[1].length);b.places=h}a=a[0].split(",");if(a.length>1&&(b.groupSize=a.pop().length,a.length>1))b.groupSize2=a.pop().length;return"("+dojo.number._realNumberRegexp(b)+")"})},!0);g&&(a=a.replace(/([\s\xa0]*)(\u00a4{1,3})([\s\xa0]*)/g,function(a,b,e,d){a=dojo.regexp.escapeString(c[["symbol","currency","displayName"][e.length-1]]||c.currency||"");b=b?"[\\s\\xa0]":"";d=d?"[\\s\\xa0]":"";return!c.strict?(b&&(b+="*"),
d&&(d+="*"),"(?:"+b+a+d+")?"):b+a+d}));return{regexp:a.replace(/[\xa0 ]/g,"[\\s\\xa0]"),group:e,decimal:d,factor:f}},dojo.number.parse=function(c,a){var b=dojo.number._parseInfo(a),e=RegExp("^"+b.regexp+"$").exec(c);if(!e)return NaN;var d=e[1];if(!e[1]){if(!e[2])return NaN;d=e[2];b.factor*=-1}d=d.replace(RegExp("["+b.group+"\\s\\xa0]","g"),"").replace(b.decimal,".");return d*b.factor},dojo.number._realNumberRegexp=function(c){c=c||{};if(!("places"in c))c.places=Infinity;if(typeof c.decimal!="string")c.decimal=
".";if(!("fractional"in c)||/^0/.test(c.places))c.fractional=[!0,!1];if(!("exponent"in c))c.exponent=[!0,!1];if(!("eSigned"in c))c.eSigned=[!0,!1];var a=dojo.number._integerRegexp(c),b=dojo.regexp.buildGroupRE(c.fractional,function(a){var b="";a&&c.places!==0&&(b="\\"+c.decimal,c.places==Infinity?b="(?:"+b+"\\d+)?":b+="\\d{"+c.places+"}");return b},!0),e=dojo.regexp.buildGroupRE(c.exponent,function(a){return a?"([eE]"+dojo.number._integerRegexp({signed:c.eSigned})+")":""});a+=b;b&&(a="(?:(?:"+a+")|(?:"+
b+"))");return a+e},dojo.number._integerRegexp=function(c){c=c||{};if(!("signed"in c))c.signed=[!0,!1];if("separator"in c){if(!("groupSize"in c))c.groupSize=3}else c.separator="";var a=dojo.regexp.buildGroupRE(c.signed,function(a){return a?"[-+]":""},!0),b=dojo.regexp.buildGroupRE(c.separator,function(a){if(!a)return"(?:\\d+)";a=dojo.regexp.escapeString(a);a==" "?a="\\s":a=="\u00a0"&&(a="\\s\\xa0");var b=c.groupSize,f=c.groupSize2;return f?(a="(?:0|[1-9]\\d{0,"+(f-1)+"}(?:["+a+"]\\d{"+f+"})*["+a+
"]\\d{"+b+"})",b-f>0?"(?:"+a+"|(?:0|[1-9]\\d{0,"+(b-1)+"}))":a):"(?:0|[1-9]\\d{0,"+(b-1)+"}(?:["+a+"]\\d{"+b+"})*)"},!0);return a+b};