/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.highlight._base"]||(dojo._hasResource["dojox.highlight._base"]=!0,dojo.provide("dojox.highlight._base"),function(){function f(a){return a.replace(/&/gm,"&amp;").replace(/</gm,"&lt;").replace(/>/gm,"&gt;")}function n(a){return dojo.every(a.childNodes,function(a){return a.nodeType==3||String(a.nodeName).toLowerCase()=="br"})}function i(a){var b=[];dojo.forEach(a.childNodes,function(a){if(a.nodeType==3)b.push(a.nodeValue);else if(String(a.nodeName).toLowerCase()=="br")b.push("\n");
else throw"Complex markup";});return b.join("")}function j(a){if(!a.keywordGroups)for(var b in a.keywords){a.keywordGroups=a.keywords[b]instanceof Object?a.keywords:{keyword:a.keywords};break}}function k(a,b,c){if(String(a.tagName).toLowerCase()=="code"&&String(a.parentNode.tagName).toLowerCase()=="pre"){var d=document.createElement("div"),e=a.parentNode.parentNode;d.innerHTML='<pre><code class="'+b+'">'+c+"</code></pre>";e.replaceChild(d.firstChild,a.parentNode)}else a.className=b,a.innerHTML=c}
function l(a,b){var c=new h(a,b);return{result:c.result,langName:a,partialResult:c.partialResult}}function m(a){var b="",c="",d;for(d in g.languages)if(g.languages[d].defaultMode){var e=new h(d,a),f=e.keywordCount+e.relevance;if(!b||f>0)b=e.result,c=e.langName}return{result:b,langName:c}}function o(a){var b=m(i(a));b.result&&k(a,b.langName,b.result)}var g=dojox.highlight;g.constants={IDENT_RE:"[a-zA-Z][a-zA-Z0-9_]*",UNDERSCORE_IDENT_RE:"[a-zA-Z_][a-zA-Z0-9_]*",NUMBER_RE:"\\b\\d+(\\.\\d+)?",C_NUMBER_RE:"\\b(0x[A-Za-z0-9]+|\\d+(\\.\\d+)?)",
APOS_STRING_MODE:{className:"string",begin:"'",end:"'",illegal:"\\n",contains:["escape"],relevance:0},QUOTE_STRING_MODE:{className:"string",begin:'"',end:'"',illegal:"\\n",contains:["escape"],relevance:0},BACKSLASH_ESCAPE:{className:"escape",begin:"\\\\.",end:"^",relevance:0},C_LINE_COMMENT_MODE:{className:"comment",begin:"//",end:"$",relevance:0},C_BLOCK_COMMENT_MODE:{className:"comment",begin:"/\\*",end:"\\*/"},HASH_COMMENT_MODE:{className:"comment",begin:"#",end:"$"},C_NUMBER_MODE:{className:"number",
begin:"\\b(0x[A-Za-z0-9]+|\\d+(\\.\\d+)?)",end:"^",relevance:0}};var h=function(a,b){this.langName=a;this.lang=g.languages[a];this.modes=[this.lang.defaultMode];this.keywordCount=this.relevance=0;this.result=[];if(!this.lang.defaultMode.illegalRe){this.buildRes();var c=this.lang;c.defaultMode&&c.modes&&(j(c.defaultMode),dojo.forEach(c.modes,j))}try{this.highlight(b),this.result=this.result.join("")}catch(d){if(d=="Illegal")this.keywordCount=this.relevance=0,this.partialResult=this.result.join(""),
this.result=f(b);else throw d;}};dojo.extend(h,{buildRes:function(){dojo.forEach(this.lang.modes,function(a){if(a.begin)a.beginRe=this.langRe("^"+a.begin);if(a.end)a.endRe=this.langRe("^"+a.end);if(a.illegal)a.illegalRe=this.langRe("^(?:"+a.illegal+")")},this);this.lang.defaultMode.illegalRe=this.langRe("^(?:"+this.lang.defaultMode.illegal+")")},subMode:function(a){var b=this.modes[this.modes.length-1].contains;if(b)for(var c=this.lang.modes,d=0;d<b.length;++d)for(var e=b[d],f=0;f<c.length;++f){var g=
c[f];if(g.className==e&&g.beginRe.test(a))return g}return null},endOfMode:function(a){for(var b=this.modes.length-1;b>=0;--b){var c=this.modes[b];if(c.end&&c.endRe.test(a))return this.modes.length-b;if(!c.endsWithParent)break}return 0},isIllegal:function(a){var b=this.modes[this.modes.length-1].illegalRe;return b&&b.test(a)},langRe:function(a,b){return RegExp(a,"m"+(this.lang.case_insensitive?"i":"")+(b?"g":""))},buildTerminators:function(){var a=this.modes[this.modes.length-1],b={};a.contains&&dojo.forEach(this.lang.modes,
function(c){dojo.indexOf(a.contains,c.className)>=0&&(b[c.begin]=1)});for(var c=this.modes.length-1;c>=0;--c){var d=this.modes[c];d.end&&(b[d.end]=1);if(!d.endsWithParent)break}a.illegal&&(b[a.illegal]=1);d=[];for(c in b)d.push(c);a.terminatorsRe=this.langRe("("+d.join("|")+")")},eatModeChunk:function(a,b){var c=this.modes[this.modes.length-1];c.terminatorsRe||this.buildTerminators();a=a.substr(b);c=c.terminatorsRe.exec(a);return!c?{buffer:a,lexeme:"",end:!0}:{buffer:c.index?a.substr(0,c.index):"",
lexeme:c[0],end:!1}},keywordMatch:function(a,b){var c=b[0];this.lang.case_insensitive&&(c=c.toLowerCase());for(var d in a.keywordGroups)if(c in a.keywordGroups[d])return d;return""},buildLexemes:function(a){var b={};dojo.forEach(a.lexems,function(a){b[a]=1});var c=[],d;for(d in b)c.push(d);a.lexemsRe=this.langRe("("+c.join("|")+")",!0)},processKeywords:function(a){var b=this.modes[this.modes.length-1];if(!b.keywords||!b.lexems)return f(a);b.lexemsRe||this.buildLexemes(b);b.lexemsRe.lastIndex=0;for(var c=
[],d=0,e=b.lexemsRe.exec(a);e;)c.push(f(a.substr(d,e.index-d))),(d=this.keywordMatch(b,e))?(++this.keywordCount,c.push('<span class="'+d+'">'+f(e[0])+"</span>")):c.push(f(e[0])),d=b.lexemsRe.lastIndex,e=b.lexemsRe.exec(a);c.push(f(a.substr(d,a.length-d)));return c.join("")},processModeInfo:function(a,b,c){var d=this.modes[this.modes.length-1];if(c)this.result.push(this.processKeywords(d.buffer+a));else{if(this.isIllegal(b))throw"Illegal";if(c=this.subMode(b))d.buffer+=a,this.result.push(this.processKeywords(d.buffer)),
c.excludeBegin?(this.result.push(b+'<span class="'+c.className+'">'),c.buffer=""):(this.result.push('<span class="'+c.className+'">'),c.buffer=b),this.modes.push(c),this.relevance+=typeof c.relevance=="number"?c.relevance:1;else if(c=this.endOfMode(b)){d.buffer+=a;for(d.excludeEnd?this.result.push(this.processKeywords(d.buffer)+"</span>"+b):this.result.push(this.processKeywords(d.buffer+b)+"</span>");c>1;)this.result.push("</span>"),--c,this.modes.pop();this.modes.pop();this.modes[this.modes.length-
1].buffer=""}}},highlight:function(a){var b=0;this.lang.defaultMode.buffer="";do{var c=this.eatModeChunk(a,b);this.processModeInfo(c.buffer,c.lexeme,c.end);b+=c.buffer.length+c.lexeme.length}while(!c.end);if(this.modes.length>1)throw"Illegal";}});dojox.highlight.processString=function(a,b){return b?l(b,a):m(a)};dojox.highlight.init=function(a){a=dojo.byId(a);if(!dojo.hasClass(a,"no-highlight")&&n(a)){var b=a.className.split(/\s+/);dojo.some(b,function(c){if(c.charAt(0)!="_"&&g.languages[c]){var b=
a,c=l(c,i(b));k(b,b.className,c.result);return!0}return!1})||o(a)}};g.Code=function(a,b){g.init(b)}}());