/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.mdnd.adapter.DndFromDojo"])dojo._hasResource["dojox.mdnd.adapter.DndFromDojo"]=!0,dojo.provide("dojox.mdnd.adapter.DndFromDojo"),dojo.require("dojox.mdnd.AreaManager"),dojo.require("dojo.dnd.Manager"),dojo.declare("dojox.mdnd.adapter.DndFromDojo",null,{dropIndicatorSize:{w:0,h:50},dropIndicatorSize:{w:0,h:50},_areaManager:null,_dojoManager:null,_currentArea:null,_oldArea:null,_moveHandler:null,_subscribeHandler:null,constructor:function(){this._areaManager=dojox.mdnd.areaManager();
this._dojoManager=dojo.dnd.manager();this._moveHandler=this._currentArea=null;this.subscribeDnd()},subscribeDnd:function(){this._subscribeHandler=[dojo.subscribe("/dnd/start",this,"onDragStart"),dojo.subscribe("/dnd/drop/before",this,"onDrop"),dojo.subscribe("/dnd/cancel",this,"onDropCancel"),dojo.subscribe("/dnd/source/over",this,"onDndSource")]},unsubscribeDnd:function(){dojo.forEach(this._subscribeHandler,dojo.unsubscribe)},_getHoverArea:function(a){var b=a.x,a=a.y;this._oldArea=this._currentArea;
this._currentArea=null;for(var c=this._areaManager._areaList,e=0;e<c.length;e++){var d=c[e],f=d.coords.x,h=f+d.node.offsetWidth,g=d.coords.y,i=g+d.node.offsetHeight;if(f<=b&&b<=h&&g<=a&&a<=i){this._areaManager._oldIndexArea=this._areaManager._currentIndexArea;this._areaManager._currentIndexArea=e;this._currentArea=d.node;break}}if(this._currentArea!=this._oldArea)if(this._currentArea==null)this.onDragExit();else{if(this._oldArea!=null)this.onDragExit();this.onDragEnter()}},onDragStart:function(a,
b,c){this._dragNode=b[0];this._copy=c;this._source=a;this._outSourceHandler=dojo.connect(this._dojoManager,"outSource",this,function(){if(this._moveHandler==null)this._moveHandler=dojo.connect(dojo.doc,"mousemove",this,"onMouseMove")})},onMouseMove:function(a){a={x:a.pageX,y:a.pageY};this._getHoverArea(a);if(this._currentArea&&this._areaManager._accept){if(this._areaManager._dropIndicator.node.style.visibility=="hidden")this._areaManager._dropIndicator.node.style.visibility="",dojo.addClass(this._dojoManager.avatar.node,
"dojoDndAvatarCanDrop");this._areaManager.placeDropIndicator(a,this.dropIndicatorSize)}},onDragEnter:function(){var a=this._dragNode.getAttribute("dndType");this._areaManager._isAccepted(a?a.split(/\s*,\s*/):["text"],this._areaManager._areaList[this._areaManager._currentIndexArea].accept);this._dojoManager.avatar&&(this._areaManager._accept?dojo.addClass(this._dojoManager.avatar.node,"dojoDndAvatarCanDrop"):dojo.removeClass(this._dojoManager.avatar.node,"dojoDndAvatarCanDrop"))},onDragExit:function(){this._areaManager._accept=
!1;this._dojoManager.avatar&&dojo.removeClass(this._dojoManager.avatar.node,"dojoDndAvatarCanDrop");this._currentArea==null?(this._areaManager._dropMode.refreshItems(this._areaManager._areaList[this._areaManager._oldIndexArea],this._areaManager._oldDropIndex,this.dropIndicatorSize,!1),this._areaManager._resetAfterDrop()):this._areaManager._dropIndicator.remove()},isAccepted:function(a,b){var c=a.getAttribute("dndType")?a.getAttribute("dndType"):"text";return c&&c in b?!0:!1},onDndSource:function(a){if(this._currentArea!=
null)if(a){var b=!1;if(b=this._dojoManager.target==a?!0:this.isAccepted(this._dragNode,a.accept)){if(dojo.disconnect(this._moveHandler),this._currentArea=this._moveHandler=null,(a=this._areaManager._dropIndicator.node)&&a.parentNode!==null&&a.parentNode.nodeType==1)a.style.visibility="hidden"}else this._resetAvatar()}else{if(!this._moveHandler)this._moveHandler=dojo.connect(dojo.doc,"mousemove",this,"onMouseMove");this._resetAvatar()}},_resetAvatar:function(){this._dojoManager.avatar&&(this._areaManager._accept?
dojo.addClass(this._dojoManager.avatar.node,"dojoDndAvatarCanDrop"):dojo.removeClass(this._dojoManager.avatar.node,"dojoDndAvatarCanDrop"))},onDropCancel:function(){if(this._currentArea==null)this._areaManager._resetAfterDrop(),dojo.disconnect(this._moveHandler),dojo.disconnect(this._outSourceHandler),this._currentArea=this._moveHandler=this._outSourceHandler=null;else if(this._areaManager._accept)this.onDrop(this._source,[this._dragNode],this._copy,this._currentArea);else this._currentArea=null,
dojo.disconnect(this._outSourceHandler),dojo.disconnect(this._moveHandler),this._moveHandler=this._outSourceHandler=null},onDrop:function(a,b,c){dojo.disconnect(this._moveHandler);dojo.disconnect(this._outSourceHandler);this._moveHandler=this._outSourceHandler=null;if(this._currentArea)dojo.publish("/dnd/drop/after",[a,b,c,this._currentArea,this._areaManager._currentDropIndex]),this._currentArea=null;if(this._areaManager._dropIndicator.node.style.visibility=="hidden")this._areaManager._dropIndicator.node.style.visibility=
"";this._areaManager._resetAfterDrop()}}),dojox.mdnd.adapter._dndFromDojo=null,function(){dojox.mdnd.adapter._dndFromDojo=new dojox.mdnd.adapter.DndFromDojo}();