/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.gauge._Gauge"]||(dojo._hasResource["dojox.widget.gauge._Gauge"]=!0,dojo.provide("dojox.widget.gauge._Gauge"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit._Container"),dojo.require("dijit._Contained"),dojo.require("dijit.Tooltip"),dojo.require("dojo.fx.easing"),dojo.require("dojox.gfx"),dojo.experimental("dojox.widget.gauge._Gauge"),dojo.declare("dojox.widget.gauge._Gauge",[dijit._Widget,dijit._Templated,dijit._Container],{width:0,
height:0,background:null,min:0,max:0,image:null,useRangeStyles:0,useTooltip:!0,majorTicks:null,minorTicks:null,_defaultIndicator:null,defaultColors:[[0,84,170,1],[68,119,187,1],[102,153,204,1],[153,187,238,1],[153,204,255,1],[204,238,255,1],[221,238,255,1]],min:null,max:null,surface:null,hideValues:!1,gaugeContent:void 0,templateString:dojo.cache("dojox.widget.gauge","_Gauge.html",'<div>\n\t<div class="dojoxGaugeContent" dojoAttachPoint="gaugeContent"></div>\n\t<div dojoAttachPoint="containerNode"></div>\n\t<div dojoAttachPoint="mouseNode"></div>\n</div>\n'),
_backgroundDefault:{color:"#E0E0E0"},_rangeData:null,_indicatorData:null,_drag:null,_img:null,_overOverlay:!1,_lastHover:"",startup:function(){if(this.image===null)this.image={};this.connect(this.gaugeContent,"onmousemove",this.handleMouseMove);this.connect(this.gaugeContent,"onmouseover",this.handleMouseOver);this.connect(this.gaugeContent,"onmouseout",this.handleMouseOut);this.connect(this.gaugeContent,"onmouseup",this.handleMouseUp);if(!dojo.isArray(this.ranges))this.ranges=[];if(!dojo.isArray(this.indicators))this.indicators=
[];var a=[],b=[],c;if(this.hasChildren()){var d=this.getChildren();for(c=0;c<d.length;c++)if(/dojox\.widget\..*Indicator/.test(d[c].declaredClass))b.push(d[c]);else switch(d[c].declaredClass){case "dojox.widget.gauge.Range":a.push(d[c])}this.ranges=this.ranges.concat(a);this.indicators=this.indicators.concat(b)}if(!this.background)this.background=this._backgroundDefault;this.background=this.background.color||this.background;this.surface||this.createSurface();this.addRanges(this.ranges);this.minorTicks&&
this.minorTicks.interval&&this.setMinorTicks(this.minorTicks);this.majorTicks&&this.majorTicks.interval&&this.setMajorTicks(this.majorTicks);for(c=0;c<this.indicators.length;c++)this.addIndicator(this.indicators[c])},_setTicks:function(a,b,c){var d;if(a&&dojo.isArray(a._ticks))for(d=0;d<a._ticks.length;d++)this.removeIndicator(a._ticks[d]);a={length:b.length,offset:b.offset,noChange:!0};if(b.color)a.color=b.color;if(b.font)a.font=b.font;b._ticks=[];for(d=this.min;d<=this.max;d+=b.interval){a.value=
d;if(c)a.label=""+d;b._ticks.push(this.addIndicator(a))}return b},setMinorTicks:function(a){this.minorTicks=this._setTicks(this.minorTicks,a,!1)},setMajorTicks:function(a){this.majorTicks=this._setTicks(this.majorTicks,a,!0)},postCreate:function(){this.hideValues&&dojo.style(this.containerNode,"display","none");dojo.style(this.mouseNode,"width","0");dojo.style(this.mouseNode,"height","0");dojo.style(this.mouseNode,"position","absolute");dojo.style(this.mouseNode,"z-index","100");this.useTooltip&&
(dijit.showTooltip("test",this.mouseNode,!this.isLeftToRight()),dijit.hideTooltip(this.mouseNode))},createSurface:function(){this.gaugeContent.style.width=this.width+"px";this.gaugeContent.style.height=this.height+"px";this.surface=dojox.gfx.createSurface(this.gaugeContent,this.width,this.height);this._background=this.surface.createRect({x:0,y:0,width:this.width,height:this.height});this._background.setFill(this.background);if(this.image.url&&(this._img=this.surface.createImage({width:this.image.width||
this.width,height:this.image.height||this.height,src:this.image.url}),this.image.overlay&&this._img.getEventSource().setAttribute("overlay",!0),this.image.x||this.image.y))this._img.setTransform({dx:this.image.x||0,dy:this.image.y||0})},setBackground:function(a){if(!a)a=this._backgroundDefault;this.background=a.color||a;this._background.setFill(this.background)},addRange:function(a){this.addRanges([a])},addRanges:function(a){if(!this._rangeData)this._rangeData=[];for(var b,c=0;c<a.length;c++){b=a[c];
if(this.min===null||b.low<this.min)this.min=b.low;if(this.max===null||b.high>this.max)this.max=b.high;if(!b.color){var d=this._rangeData.length%this.defaultColors.length;dojox.gfx.svg&&this.useRangeStyles>0?(d=this._rangeData.length%this.useRangeStyles+1,b.color={style:"dojoxGaugeRange"+d}):(d=this._rangeData.length%this.defaultColors.length,b.color=this.defaultColors[d])}this._rangeData[this._rangeData.length]=b}this.draw()},addIndicator:function(a){a._gauge=this;a.declaredClass||(a=new this._defaultIndicator(a));
a.hideValue||this.containerNode.appendChild(a.domNode);if(!this._indicatorData)this._indicatorData=[];this._indicatorData[this._indicatorData.length]=a;a.draw();return a},removeIndicator:function(a){for(var b=0;b<this._indicatorData.length;b++)if(this._indicatorData[b]===a){this._indicatorData.splice(b,1);a.remove();break}},moveIndicatorToFront:function(a){if(a.shapes)for(var b=0;b<a.shapes.length;b++)a.shapes[b].moveToFront()},drawText:function(a,b,c,d,g,e,f){a=this.surface.createText({x:b,y:c,text:a,
align:d});a.setFill(e);a.setFont(f);return a},removeText:function(a){this.surface.rawNode.removeChild(a)},updateTooltip:function(a){if(this._lastHover!=a)a!==""?(dijit.hideTooltip(this.mouseNode),dijit.showTooltip(a,this.mouseNode,!this.isLeftToRight())):dijit.hideTooltip(this.mouseNode),this._lastHover=a},handleMouseOver:function(a){var b=a.target.getAttribute("hover");if(a.target.getAttribute("overlay")){this._overOverlay=!0;var c=this.getRangeUnderMouse(a);if(c&&c.hover)b=c.hover}this.useTooltip&&
!this._drag&&(b?this.updateTooltip(b,a):this.updateTooltip("",a))},handleMouseOut:function(a){if(a.target.getAttribute("overlay"))this._overOverlay=!1;this.useTooltip&&this.mouseNode&&dijit.hideTooltip(this.mouseNode)},handleMouseDown:function(a){for(var b=0;b<this._indicatorData.length;b++)for(var c=this._indicatorData[b].shapes,d=0;d<c.length;d++)if(c[d].getEventSource()==a.target)this._drag=this._indicatorData[b],d=c.length,b=this._indicatorData.length;dojo.stopEvent(a)},handleMouseUp:function(a){this._drag=
null;dojo.stopEvent(a)},handleMouseMove:function(a){a&&(dojo.style(this.mouseNode,"left",a.pageX+1+"px"),dojo.style(this.mouseNode,"top",a.pageY+1+"px"));if(this._drag)this._dragIndicator(this,a);else if(this.useTooltip&&this._overOverlay){var b=this.getRangeUnderMouse(a);b&&b.hover?this.updateTooltip(b.hover,a):this.updateTooltip("",a)}}}),dojo.declare("dojox.widget.gauge.Range",[dijit._Widget,dijit._Contained],{low:0,high:0,hover:"",color:null,size:0,startup:function(){this.color=this.color.color||
this.color}}),dojo.declare("dojox.widget.gauge._Indicator",[dijit._Widget,dijit._Contained,dijit._Templated],{value:0,type:"",color:"black",label:"",font:{family:"sans-serif",size:"12px"},length:0,width:0,offset:0,hover:"",front:!1,easing:dojo._defaultEasing,duration:1E3,hideValue:!1,noChange:!1,_gauge:null,title:"",templateString:dojo.cache("dojox.widget.gauge","_Indicator.html",'<div class="dojoxGaugeIndicatorDiv">\n\t<label class="dojoxGaugeIndicatorLabel" for="${title}">${title}:</label>\n\t<input class="dojoxGaugeIndicatorInput" name="${title}" size="5" value="${value}" dojoAttachPoint="valueNode" dojoAttachEvent="onchange:_update"></input>\n</div>\n'),
startup:function(){if(this.onDragMove)this.onDragMove=dojo.hitch(this.onDragMove)},postCreate:function(){this.title===""&&dojo.style(this.domNode,"display","none");if(dojo.isString(this.easing))this.easing=dojo.getObject(this.easing)},_update:function(){var a=this.valueNode.value;a===""?this.value=null:(this.value=Number(a),this.hover=this.title+": "+a);if(this._gauge)this.draw(),this.valueNode.value=this.value,(this.title=="Target"||this.front)&&this._gauge.moveIndicator&&this._gauge.moveIndicatorToFront(this)},
update:function(a){if(!this.noChange)this.valueNode.value=a,this._update()},onDragMove:function(){this.value=Math.floor(this.value);this.valueNode.value=this.value;this.hover=this.title+": "+this.value},draw:function(){},remove:function(){for(var a=0;a<this.shapes.length;a++)this._gauge.surface.remove(this.shapes[a]);this.text&&this._gauge.surface.remove(this.text)}}));