/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.drawing.stencil._Base"])dojo._hasResource["dojox.drawing.stencil._Base"]=!0,dojo.provide("dojox.drawing.stencil._Base"),dojo.require("dojo.fx.easing"),dojox.drawing.stencil._Base=dojox.drawing.util.oo.declare(function(a){dojo.mixin(this,a);this.style=a.style||dojox.drawing.defaults.copy();if(a.stencil)this.stencil=a.stencil,this.util=a.stencil.util,this.mouse=a.stencil.mouse,this.container=a.stencil.container,this.style=a.stencil.style;this.shortType=this.util.abbr(this.type);
this.isText=/Text/.test(this.type);this.isLine=/Line|Vector|Axes|Arrow/.test(this.type);this.renderHit=this.style.renderHitLayer;if(!this.renderHit&&this.style.renderHitLines&&this.isLine)this.renderHit=!0;if(!this.renderHit&&this.style.useSelectedStyle){this.useSelectedStyle=!0;this.selCopy=dojo.clone(this.style.selected);for(var b in this.style.norm)this.style.selected[b]===void 0&&(this.style.selected[b]=this.style.norm[b]);this.textSelected=dojo.clone(this.style.text);this.textSelected.color=
this.style.selected.fill}this.angleSnap=this.style.angleSnap||1;this.marginZero=a.marginZero||this.style.anchors.marginZero;this.id=a.id||this.util.uid(this.type);this._cons=[];!this.annotation&&!this.subShape&&this.util.attr(this.container,"id",this.id);this.connect(this,"onBeforeRender","preventNegativePos");this._offX=this.mouse.origin.x;this._offY=this.mouse.origin.y;if(this.isText)this.align=a.align||this.align,this.valign=a.valign||this.valign,a.data&&a.data.makeFit?(b=this.makeFit(a.data.text,
a.data.width),this.textSize=this.style.text.size=b.size,this._lineHeight=b.box.h):(this.textSize=parseInt(this.style.text.size,10),this._lineHeight=this.textSize*1.4),this.deleteEmptyCreate=a.deleteEmptyCreate!==void 0?a.deleteEmptyCreate:this.style.text.deleteEmptyCreate,this.deleteEmptyModify=a.deleteEmptyModify!==void 0?a.deleteEmptyModify:this.style.text.deleteEmptyModify;this.attr(a.data);if(!this.noBaseRender){if(a.points){if(a.data&&a.data.closePath===!1)this.closePath=!1;this.setPoints(a.points);
this.connect(this,"render",this,"onRender",!0);this.baseRender&&this.enabled&&this.render();a.label&&this.setLabel(a.label);a.shadow&&this.addShadow(a.shadow)}else if(a.data)a.data.width=a.data.width?a.data.width:this.style.text.minWidth,a.data.height=a.data.height?a.data.height:this._lineHeight,this.setData(a.data),this.connect(this,"render",this,"onRender",!0),this.baseRender&&this.enabled&&this.render(a.data.text),this.baseRender&&a.label&&this.setLabel(a.label),this.baseRender&&a.shadow&&this.addShadow(a.shadow);
else if(this.draws)this.points=[],this.data={},this.connectMouse(),this._postRenderCon=dojo.connect(this,"render",this,"_onPostRender");if(this.showAngle)this.angleLabel=new dojox.drawing.annotations.Angle({stencil:this});this.enabled||(this.disable(),this.moveToBack(),this.render(a.data.text))}},{type:"dojox.drawing.stencil",minimumSize:10,enabled:!0,drawingType:"stencil",setData:function(a){this.data=a;this.points=this.dataToPoints()},setPoints:function(a){this.points=a;if(this.pointsToData)this.data=
this.pointsToData()},onDelete:function(){console.info("onDelete",this.id)},onBeforeRender:function(){},onModify:function(){},onChangeData:function(){},onChangeText:function(){},onRender:function(){this._postRenderCon=dojo.connect(this,"render",this,"_onPostRender");this.created=!0;this.disconnectMouse();this.shape?this.shape.superClass=this:this.container.superClass=this;this._setNodeAtts(this)},onChangeStyle:function(){this._isBeingModified=!0;this.enabled?(this.style.current=this.style.norm,this.style.currentHit=
this.style.hitNorm,this.style.currentText=this.style.text):(this.style.current=this.style.disabled,this.style.currentText=this.style.textDisabled,this.style.currentHit=this.style.hitNorm);if(this.selected){if(this.useSelectedStyle)this.style.current=this.style.selected,this.style.currentText=this.textSelected;this.style.currentHit=this.style.hitSelected}else if(this.highlighted)this.style.currentHit=this.style.hitHighlighted;this.render()},animate:function(a){console.warn("ANIMATE..........................");
var b=a.d||a.duration||1E3,e=a.ms||20,f=a.ease||dojo.fx.easing.linear,h=(new Date).getTime(),c=0,d=!0,g,i;dojo.isArray(a.start)?(g=a.start,i=a.end):dojo.isObject(a.start)?(g=a.start,i=a.end,d=!1):console.warn("No data provided to animate");var l=setInterval(dojo.hitch(this,function(){var a=(new Date).getTime()-h,e=f(1-a/b);if(a>b||c++>100)clearInterval(l);else if(d){var n=[];dojo.forEach(g,function(a,b){n.push({x:(i[b].x-g[b].x)*e+g[b].x,y:(i[b].y-g[b].y)*e+g[b].y})});this.setPoints(n);this.render()}else{var a=
{},k;for(k in g)a[k]=(i[k]-g[k])*e+g[k];this.attr(a)}}),e)},attr:function(a,b){var e=this.enabled?this.style.norm:this.style.disabled,f=this.enabled?this.style.text:this.style.textDisabled,h=this.textSelected||{},c,d,g,i=dojo.toJson(e),l=dojo.toJson(f),j={x:!0,y:!0,r:!0,height:!0,width:!0,radius:!0,angle:!0},m=!1;typeof a!="object"?(c={},c[a]=b):c=dojo.clone(a);if(c.width)g=c.width,delete c.width;for(d in c){d in e&&(e[d]=c[d]);d in f&&(f[d]=c[d]);d in h&&(h[d]=c[d]);if(d in j)if(j[d]=c[d],m=!0,d==
"radius"&&c.angle===void 0)c.angle=j.angle=this.getAngle();else if(d=="angle"&&c.radius===void 0)c.radius=j.radius=this.getRadius();d=="text"&&this.setText(c.text);d=="label"&&this.setLabel(c.label)}if(c.borderWidth!==void 0)e.width=c.borderWidth;if(this.useSelectedStyle){for(d in this.style.norm)this.selCopy[d]===void 0&&(this.style.selected[d]=this.style.norm[d]);this.textSelected.color=this.style.selected.color}if(this.created){if(c.x!==void 0||c.y!==void 0){h=this.getBounds(!0);j={dx:0,dy:0};
for(d in c)if(d=="x"||d=="y"||d=="r")j["d"+d]=c[d]-h[d];this.transformPoints(j)}d=this.points;if(c.angle!==void 0)this.dataToPoints({x:this.data.x1,y:this.data.y1,angle:c.angle,radius:c.radius});else if(g!==void 0)d[1].x=d[2].x=d[0].x+g,this.pointsToData(d);if(c.height!==void 0&&c.angle===void 0)console.log("Doing P2D-2"),d[2].y=d[3].y=d[0].y+c.height,this.pointsToData(d);if(c.r!==void 0)this.data.r=Math.max(0,c.r);if(m||l!=dojo.toJson(f)||i!=dojo.toJson(e))this.onChangeStyle(this);c.width=g;if(c.cosphi!=
void 0)!this.data?this.data={cosphi:c.cosphi}:this.data.cosphi=c.cosphi,this.style.zAxis=c.cosphi!=0?!0:!1}},exporter:function(){var a=this.type.substring(this.type.lastIndexOf(".")+1).charAt(0).toLowerCase()+this.type.substring(this.type.lastIndexOf(".")+2),b=dojo.clone(this.style.norm);b.borderWidth=b.width;delete b.width;a=="path"?b.points=this.points:b=dojo.mixin(b,this.data);b.type=a;if(this.isText)b.text=this.getText(),b=dojo.mixin(b,this.style.text),delete b.minWidth,delete b.deleteEmptyCreate,
delete b.deleteEmptyModify;if(a=this.getLabel())b.label=a;return b},disable:function(){this.renderHit=this.enabled=!1;this.onChangeStyle(this)},enable:function(){this.renderHit=this.enabled=!0;this.onChangeStyle(this)},select:function(){this.selected=!0;this.onChangeStyle(this)},deselect:function(a){a?setTimeout(dojo.hitch(this,function(){this.selected=!1;this.onChangeStyle(this)}),200):(this.selected=!1,this.onChangeStyle(this))},_toggleSelected:function(){this.selected&&(this.deselect(),setTimeout(dojo.hitch(this,
"select"),0))},highlight:function(){this.highlighted=!0;this.onChangeStyle(this)},unhighlight:function(){this.highlighted=!1;this.onChangeStyle(this)},moveToFront:function(){this.container&&this.container.moveToFront()},moveToBack:function(){this.container&&this.container.moveToBack()},onTransformBegin:function(){this._isBeingModified=!0},onTransformEnd:function(){this._isBeingModified=!1;this.onModify(this)},onTransform:function(){if(!this._isBeingModified)this.onTransformBegin();this.setPoints(this.points);
this.render()},transformPoints:function(a){if(a.dx||a.dy){var b=dojo.clone(this.points),e=!1;dojo.forEach(this.points,function(b){b.x+=a.dx;b.y+=a.dy;if(b.x<this.marginZero||b.y<this.marginZero)e=!0});e?(this.points=b,console.error("Attempt to set object '"+this.id+"' to less than zero.")):(this.onTransform(),this.onTransformEnd())}},applyTransform:function(a){this.transformPoints(a)},setTransform:function(a){this.attr({x:a.dx,y:a.dy})},getTransform:function(){return this.selected?this.container.getParent().getTransform():
{dx:0,dy:0}},addShadow:function(a){a=a===!0?{}:a;a.stencil=this;this.shadow=new dojox.drawing.annotations.BoxShadow(a)},removeShadow:function(){this.shadow.destroy()},setLabel:function(a){this._label?a!=void 0&&this._label.setLabel(a):this._label=new dojox.drawing.annotations.Label({text:a,util:this.util,mouse:this.mouse,stencil:this,annotation:!0,container:this.container,labelPosition:this.labelPosition})},getLabel:function(){return this._label?this._label.getText():null},getAngle:function(){var a=
this.pointsToData(),a=this.util.angle({start:{x:a.x1,y:a.y1},x:a.x2,y:a.y2},this.angleSnap);a<0&&(a=360+a);return a},getRadius:function(){var a=this.getBounds(!0);return this.util.length({start:{x:a.x1,y:a.y1},x:a.x2,y:a.y2})},getBounds:function(a){var b=this.points,e,f;return b.length==2?(a?(a=b[0].x,e=b[0].y,f=b[1].x,b=b[1].y):(a=b[0].x<b[1].x?b[0].x:b[1].x,e=b[0].y<b[1].y?b[0].y:b[1].y,f=b[0].x<b[1].x?b[1].x:b[0].x,b=b[0].y<b[1].y?b[1].y:b[0].y),{x1:a,y1:e,x2:f,y2:b,x:a,y:e,w:f-a,h:b-e}):{x1:b[0].x,
y1:b[0].y,x2:b[2].x,y2:b[2].y,x:b[0].x,y:b[0].y,w:b[2].x-b[0].x,h:b[2].y-b[0].y}},preventNegativePos:function(){if(!this._isBeingModified&&this.points&&this.points.length){if(this.type=="dojox.drawing.tools.custom.Axes"){var a=this.marginZero,b=this.marginZero;dojo.forEach(this.points,function(b){a=Math.min(b.y,a)});dojo.forEach(this.points,function(a){b=Math.min(a.x,b)});a<this.marginZero&&dojo.forEach(this.points,function(b){b.y+=this.marginZero-a},this);b<this.marginZero&&dojo.forEach(this.points,
function(a){a.x+=this.marginZero-b},this)}else dojo.forEach(this.points,function(a){a.x=a.x<0?this.marginZero:a.x;a.y=a.y<0?this.marginZero:a.y});this.setPoints(this.points)}},_onPostRender:function(){if(this._isBeingModified)this.onModify(this),this._isBeingModified=!1;if(!this.editMode&&!this.selected&&this._prevData&&dojo.toJson(this._prevData)!=dojo.toJson(this.data))this.onChangeData(this),this._prevData=dojo.clone(this.data);else if(!this._prevData&&(!this.isText||this.getText()))this._prevData=
dojo.clone(this.data)},_setNodeAtts:function(a){this.util.attr(a,"drawingType",this.enabled&&(!this.annotation||this.drawingType=="label")?this.drawingType:"")},destroy:function(){if(!this.destroyed){if(this.data||this.points&&this.points.length)this.onDelete(this);this.disconnectMouse();this.disconnect(this._cons);dojo.disconnect(this._postRenderCon);this.remove(this.shape,this.hit);this.destroyed=!0}},remove:function(){var a=arguments;if(!a.length){if(!this.shape)return;a=[this.shape]}for(var b=
0;b<a.length;b++)a[b]&&a[b].removeShape()},connectMult:function(){arguments.length>1?this._cons.push(this.connect.apply(this,arguments)):dojo.isArray(arguments[0][0])?dojo.forEach(arguments[0],function(a){this._cons.push(this.connect.apply(this,a))},this):this._cons.push(this.connect.apply(this,arguments[0]))},connect:function(a,b,e,f,h){var c;if(typeof a!="object")e?(f=e,e=b,b=a,a=this):(f=b,b=a,a=e=this);else if(f){if(h)return c=dojo.connect(a,b,function(a){dojo.hitch(e,f)(a);dojo.disconnect(c)}),
this._cons.push(c),c}else f=e,e=this;c=dojo.connect(a,b,e,f);this._cons.push(c);return c},disconnect:function(a){a&&(dojo.isArray(a)||(a=[a]),dojo.forEach(a,dojo.disconnect,dojo))},connectMouse:function(){this._mouseHandle=this.mouse.register(this)},disconnectMouse:function(){this.mouse.unregister(this._mouseHandle)},render:function(){},dataToPoints:function(){},pointsToData:function(){},onDown:function(){this._downOnCanvas=!0;dojo.disconnect(this._postRenderCon);this._postRenderCon=null},onMove:function(){},
onDrag:function(){},onUp:function(){}});