/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.storage.AirEncryptedLocalStorageProvider"]||(dojo._hasResource["dojox.storage.AirEncryptedLocalStorageProvider"]=!0,dojo.provide("dojox.storage.AirEncryptedLocalStorageProvider"),dojo.require("dojox.storage.manager"),dojo.require("dojox.storage.Provider"),dojo.isAIR&&function(){if(!e)var e={};e.ByteArray=window.runtime.flash.utils.ByteArray;e.EncryptedLocalStore=window.runtime.flash.data.EncryptedLocalStore;dojo.declare("dojox.storage.AirEncryptedLocalStorageProvider",[dojox.storage.Provider],
{initialize:function(){dojox.storage.manager.loaded()},isAvailable:function(){return!0},_getItem:function(a){return(a=e.EncryptedLocalStore.getItem("__dojo_"+a))?a.readUTFBytes(a.length):""},_setItem:function(a,b){var c=new e.ByteArray;c.writeUTFBytes(b);e.EncryptedLocalStore.setItem("__dojo_"+a,c)},_removeItem:function(a){e.EncryptedLocalStore.removeItem("__dojo_"+a)},put:function(a,b,c,d){if(this.isValidKey(a)==!1)throw Error("Invalid key given: "+a);d=d||this.DEFAULT_NAMESPACE;if(this.isValidKey(d)==
!1)throw Error("Invalid namespace given: "+d);try{var e=this._getItem("namespaces")||"|";e.indexOf("|"+d+"|")==-1&&this._setItem("namespaces",e+d+"|");var f=this._getItem(d+"_keys")||"|";f.indexOf("|"+a+"|")==-1&&this._setItem(d+"_keys",f+a+"|");this._setItem("_"+d+"_"+a,b)}catch(g){console.debug("dojox.storage.AirEncryptedLocalStorageProvider.put:",g);c(this.FAILED,a,g.toString(),d);return}c&&c(this.SUCCESS,a,null,d)},get:function(a,b){if(this.isValidKey(a)==!1)throw Error("Invalid key given: "+
a);b=b||this.DEFAULT_NAMESPACE;return this._getItem("_"+b+"_"+a)},getNamespaces:function(){for(var a=[this.DEFAULT_NAMESPACE],b=(this._getItem("namespaces")||"|").split("|"),c=0;c<b.length;c++)b[c].length&&b[c]!=this.DEFAULT_NAMESPACE&&a.push(b[c]);return a},getKeys:function(a){a=a||this.DEFAULT_NAMESPACE;if(this.isValidKey(a)==!1)throw Error("Invalid namespace given: "+a);for(var b=[],a=(this._getItem(a+"_keys")||"|").split("|"),c=0;c<a.length;c++)a[c].length&&b.push(a[c]);return b},clear:function(a){if(this.isValidKey(a)==
!1)throw Error("Invalid namespace given: "+a);var b=this._getItem("namespaces")||"|";b.indexOf("|"+a+"|")!=-1&&this._setItem("namespaces",b.replace("|"+a+"|","|"));for(var b=(this._getItem(a+"_keys")||"|").split("|"),c=0;c<b.length;c++)b[c].length&&this._removeItem(a+"_"+b[c]);this._removeItem(a+"_keys")},remove:function(a,b){var b=b||this.DEFAULT_NAMESPACE,c=this._getItem(b+"_keys")||"|";c.indexOf("|"+a+"|")!=-1&&this._setItem(b+"_keys",c.replace("|"+a+"|","|"));this._removeItem("_"+b+"_"+a)},putMultiple:function(a,
b,c,d){if(this.isValidKeyArray(a)===!1||!b instanceof Array||a.length!=b.length)throw Error("Invalid arguments: keys = ["+a+"], values = ["+b+"]");if(d==null||typeof d=="undefined")d=this.DEFAULT_NAMESPACE;if(this.isValidKey(d)==!1)throw Error("Invalid namespace given: "+d);this._statusHandler=c;try{for(var e=0;e<a.length;e++)this.put(a[e],b[e],null,d)}catch(f){console.debug("dojox.storage.AirEncryptedLocalStorageProvider.putMultiple:",f);c&&c(this.FAILED,a,f.toString(),d);return}c&&c(this.SUCCESS,
a,null)},getMultiple:function(a,b){if(this.isValidKeyArray(a)===!1)throw Error("Invalid key array given: "+a);if(b==null||typeof b=="undefined")b=this.DEFAULT_NAMESPACE;if(this.isValidKey(b)==!1)throw Error("Invalid namespace given: "+b);for(var c=[],d=0;d<a.length;d++)c[d]=this.get(a[d],b);return c},removeMultiple:function(a,b){for(var b=b||this.DEFAULT_NAMESPACE,c=0;c<a.length;c++)this.remove(a[c],b)},isPermanent:function(){return!0},getMaximumSize:function(){return this.SIZE_NO_LIMIT},hasSettingsUI:function(){return!1},
showSettingsUI:function(){throw Error(this.declaredClass+" does not support a storage settings user-interface");},hideSettingsUI:function(){throw Error(this.declaredClass+" does not support a storage settings user-interface");}});dojox.storage.manager.register("dojox.storage.AirEncryptedLocalStorageProvider",new dojox.storage.AirEncryptedLocalStorageProvider);dojox.storage.manager.initialize()}());