/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.storage.AirFileStorageProvider"]||(dojo._hasResource["dojox.storage.AirFileStorageProvider"]=!0,dojo.provide("dojox.storage.AirFileStorageProvider"),dojo.require("dojox.storage.manager"),dojo.require("dojox.storage.Provider"),dojo.isAIR&&function(){if(!e)var e={};e.File=window.runtime.flash.filesystem.File;e.FileStream=window.runtime.flash.filesystem.FileStream;e.FileMode=window.runtime.flash.filesystem.FileMode;dojo.declare("dojox.storage.AirFileStorageProvider",[dojox.storage.Provider],
{initialized:!1,_storagePath:"__DOJO_STORAGE/",initialize:function(){this.initialized=!1;try{var a=e.File.applicationStorageDirectory.resolvePath(this._storagePath);a.exists||a.createDirectory();this.initialized=!0}catch(b){console.debug("dojox.storage.AirFileStorageProvider.initialize:",b)}dojox.storage.manager.loaded()},isAvailable:function(){return!0},put:function(a,b,c,d){if(this.isValidKey(a)==!1)throw Error("Invalid key given: "+a);d=d||this.DEFAULT_NAMESPACE;if(this.isValidKey(d)==!1)throw Error("Invalid namespace given: "+
d);try{this.remove(a,d);var f=e.File.applicationStorageDirectory.resolvePath(this._storagePath+d);f.exists||f.createDirectory();var g=f.resolvePath(a),h=new e.FileStream;h.open(g,e.FileMode.WRITE);h.writeObject(b);h.close()}catch(i){console.debug("dojox.storage.AirFileStorageProvider.put:",i);c(this.FAILED,a,i.toString(),d);return}c&&c(this.SUCCESS,a,null,d)},get:function(a,b){if(this.isValidKey(a)==!1)throw Error("Invalid key given: "+a);var b=b||this.DEFAULT_NAMESPACE,c=null,d=e.File.applicationStorageDirectory.resolvePath(this._storagePath+
b+"/"+a);if(d.exists&&!d.isDirectory){var f=new e.FileStream;f.open(d,e.FileMode.READ);c=f.readObject();f.close()}return c},getNamespaces:function(){var a=[this.DEFAULT_NAMESPACE],b=e.File.applicationStorageDirectory.resolvePath(this._storagePath).getDirectoryListing(),c;for(c=0;c<b.length;c++)b[c].isDirectory&&b[c].name!=this.DEFAULT_NAMESPACE&&a.push(b[c].name);return a},getKeys:function(a){a=a||this.DEFAULT_NAMESPACE;if(this.isValidKey(a)==!1)throw Error("Invalid namespace given: "+a);var b=[],
a=e.File.applicationStorageDirectory.resolvePath(this._storagePath+a);if(a.exists&&a.isDirectory){var a=a.getDirectoryListing(),c;for(c=0;c<a.length;c++)b.push(a[c].name)}return b},clear:function(a){if(this.isValidKey(a)==!1)throw Error("Invalid namespace given: "+a);a=e.File.applicationStorageDirectory.resolvePath(this._storagePath+a);a.exists&&a.isDirectory&&a.deleteDirectory(!0)},remove:function(a,b){var b=b||this.DEFAULT_NAMESPACE,c=e.File.applicationStorageDirectory.resolvePath(this._storagePath+
b+"/"+a);c.exists&&!c.isDirectory&&c.deleteFile()},putMultiple:function(a,b,c,d){if(this.isValidKeyArray(a)===!1||!b instanceof Array||a.length!=b.length)throw Error("Invalid arguments: keys = ["+a+"], values = ["+b+"]");if(d==null||typeof d=="undefined")d=this.DEFAULT_NAMESPACE;if(this.isValidKey(d)==!1)throw Error("Invalid namespace given: "+d);this._statusHandler=c;try{for(var e=0;e<a.length;e++)this.put(a[e],b[e],null,d)}catch(g){console.debug("dojox.storage.AirFileStorageProvider.putMultiple:",
g);c&&c(this.FAILED,a,g.toString(),d);return}c&&c(this.SUCCESS,a,null,d)},getMultiple:function(a,b){if(this.isValidKeyArray(a)===!1)throw Error("Invalid key array given: "+a);if(b==null||typeof b=="undefined")b=this.DEFAULT_NAMESPACE;if(this.isValidKey(b)==!1)throw Error("Invalid namespace given: "+b);for(var c=[],d=0;d<a.length;d++)c[d]=this.get(a[d],b);return c},removeMultiple:function(a,b){for(var b=b||this.DEFAULT_NAMESPACE,c=0;c<a.length;c++)this.remove(a[c],b)},isPermanent:function(){return!0},
getMaximumSize:function(){return this.SIZE_NO_LIMIT},hasSettingsUI:function(){return!1},showSettingsUI:function(){throw Error(this.declaredClass+" does not support a storage settings user-interface");},hideSettingsUI:function(){throw Error(this.declaredClass+" does not support a storage settings user-interface");}});dojox.storage.manager.register("dojox.storage.AirFileStorageProvider",new dojox.storage.AirFileStorageProvider);dojox.storage.manager.initialize()}());