/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.storage.CookieStorageProvider"]||(dojo._hasResource["dojox.storage.CookieStorageProvider"]=!0,dojo.provide("dojox.storage.CookieStorageProvider"),dojo.require("dojox.storage.Provider"),dojo.require("dojox.storage.manager"),dojo.require("dojo.cookie"),dojo.declare("dojox.storage.CookieStorageProvider",[dojox.storage.Provider],{store:null,cookieName:"dojoxStorageCookie",storageLife:730,initialize:function(){this.store=dojo.fromJson(dojo.cookie(this.cookieName))||{};this.initialized=
!0;dojox.storage.manager.loaded()},isAvailable:function(){return dojo.cookie.isSupported()},put:function(a,b,c,d){this._assertIsValidKey(a);d=d||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(d);fullKey=this.getFullKey(a,d);this.store[fullKey]=dojo.toJson(b);this._save();(b=dojo.toJson(this.store)===dojo.cookie(this.cookieName))||this.remove(a,d);c&&c(b?this.SUCCESS:this.FAILED,a,null,d)},get:function(a,b){this._assertIsValidKey(a);b=b||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(b);
a=this.getFullKey(a,b);return this.store[a]?dojo.fromJson(this.store[a]):null},getKeys:function(a){a=a||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(a);var a="__"+a+"_",b=[],c;for(c in this.store)this._beginsWith(c,a)&&(c=c.substring(a.length),b.push(c));return b},clear:function(a){a=a||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(a);var a="__"+a+"_",b;for(b in this.store)this._beginsWith(b,a)&&delete this.store[b];this._save()},remove:function(a,b){b=b||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(b);
this._assertIsValidKey(a);a=this.getFullKey(a,b);delete this.store[a];this._save()},getNamespaces:function(){var a=[this.DEFAULT_NAMESPACE],b={};b[this.DEFAULT_NAMESPACE]=!0;var c=/^__([^_]*)_/,d;for(d in this.store)if(c.test(d)==!0){var e=d.match(c)[1];typeof b[e]=="undefined"&&(b[e]=!0,a.push(e))}return a},isPermanent:function(){return!0},getMaximumSize:function(){return 4},hasSettingsUI:function(){return!1},isValidKey:function(a){return a===null||a===void 0?!1:/^[0-9A-Za-z_-]*$/.test(a)},isValidNamespace:function(a){return a===
null||a===void 0?!1:/^[0-9A-Za-z-]*$/.test(a)},getFullKey:function(a,b){return"__"+b+"_"+a},_save:function(){dojo.cookie(this.cookieName,dojo.toJson(this.store),{expires:this.storageLife})},_beginsWith:function(a,b){return b.length>a.length?!1:a.substring(0,b.length)===b},_assertIsValidNamespace:function(a){if(this.isValidNamespace(a)===!1)throw Error("Invalid namespace given: "+a);},_assertIsValidKey:function(a){if(this.isValidKey(a)===!1)throw Error("Invalid key given: "+a);}}),dojox.storage.manager.register("dojox.storage.CookieStorageProvider",
new dojox.storage.CookieStorageProvider));