/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.storage.FlashStorageProvider"]||(dojo._hasResource["dojox.storage.FlashStorageProvider"]=!0,dojo.provide("dojox.storage.FlashStorageProvider"),dojo.require("dojox.flash"),dojo.require("dojox.storage.manager"),dojo.require("dojox.storage.Provider"),dojo.declare("dojox.storage.FlashStorageProvider",dojox.storage.Provider,{initialized:!1,_available:null,_statusHandler:null,_flashReady:!1,_pageReady:!1,initialize:function(){if(dojo.config.disableFlashStorage!=!0){dojox.flash.addLoadedListener(dojo.hitch(this,
function(){(this._flashReady=!0)&&this._pageReady&&this._loaded()}));var a=dojo.moduleUrl("dojox","storage/Storage.swf").toString();dojox.flash.setSwf(a,!1);dojo.connect(dojo,"loaded",this,function(){this._pageReady=!0;this._flashReady&&this._pageReady&&this._loaded()})}},setFlushDelay:function(a){if(a===null||typeof a==="undefined"||isNaN(a))throw Error("Invalid argunment: "+a);dojox.flash.comm.setFlushDelay(String(a))},getFlushDelay:function(){return Number(dojox.flash.comm.getFlushDelay())},flush:function(a){if(a==
null||typeof a=="undefined")a=dojox.storage.DEFAULT_NAMESPACE;dojox.flash.comm.flush(a)},isAvailable:function(){return this._available=!dojo.config.disableFlashStorage},put:function(a,b,c,d){if(!this.isValidKey(a))throw Error("Invalid key given: "+a);if(!d)d=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(d))throw Error("Invalid namespace given: "+d);this._statusHandler=c;b=dojo.isString(b)?"string:"+b:dojo.toJson(b);dojox.flash.comm.put(a,b,d)},putMultiple:function(a,b,c,d){if(!this.isValidKeyArray(a)||
!b instanceof Array||a.length!=b.length)throw Error("Invalid arguments: keys = ["+a+"], values = ["+b+"]");if(!d)d=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(d))throw Error("Invalid namespace given: "+d);this._statusHandler=c;for(var a=a.join(","),c=[],e=0;e<b.length;e++)b[e]=dojo.isString(b[e])?"string:"+b[e]:dojo.toJson(b[e]),c[e]=b[e].length;b=b.join("");c=c.join(",");dojox.flash.comm.putMultiple(a,b,c,d)},get:function(a,b){if(!this.isValidKey(a))throw Error("Invalid key given: "+a);if(!b)b=
dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+b);var c=dojox.flash.comm.get(a,b);return c==""?null:this._destringify(c)},getMultiple:function(a,b){if(!this.isValidKeyArray(a))throw new ("Invalid key array given: "+a);if(!b)b=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+b);for(var c=a.join(","),c=dojox.flash.comm.getMultiple(c,b),c=eval("("+c+")"),d=0;d<c.length;d++)c[d]=c[d]==""?null:this._destringify(c[d]);
return c},_destringify:function(a){return a=dojo.isString(a)&&/^string:/.test(a)?a.substring(7):dojo.fromJson(a)},getKeys:function(a){if(!a)a=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(a))throw Error("Invalid namespace given: "+a);a=dojox.flash.comm.getKeys(a);if(a==null||a=="null")a="";a=a.split(",");a.sort();return a},getNamespaces:function(){var a=dojox.flash.comm.getNamespaces();if(a==null||a=="null")a=dojox.storage.DEFAULT_NAMESPACE;a=a.split(",");a.sort();return a},clear:function(a){if(!a)a=
dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(a))throw Error("Invalid namespace given: "+a);dojox.flash.comm.clear(a)},remove:function(a,b){if(!b)b=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+b);dojox.flash.comm.remove(a,b)},removeMultiple:function(a,b){this.isValidKeyArray(a)||dojo.raise("Invalid key array given: "+a);if(!b)b=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+b);var c=a.join(",");
dojox.flash.comm.removeMultiple(c,b)},isPermanent:function(){return!0},getMaximumSize:function(){return dojox.storage.SIZE_NO_LIMIT},hasSettingsUI:function(){return!0},showSettingsUI:function(){dojox.flash.comm.showSettings();dojox.flash.obj.setVisible(!0);dojox.flash.obj.center()},hideSettingsUI:function(){dojox.flash.obj.setVisible(!1);dojo.isFunction(dojox.storage.onHideSettingsUI)&&dojox.storage.onHideSettingsUI.call(null)},getResourceList:function(){return[]},_loaded:function(){this._allNamespaces=
this.getNamespaces();this.initialized=!0;dojox.storage.manager.loaded()},_onStatus:function(a,b,c){var d=dojox.storage,e=dojox.flash.obj;a==d.PENDING?(e.center(),e.setVisible(!0)):e.setVisible(!1);d._statusHandler&&d._statusHandler.call(null,a,b,null,c)}}),dojox.storage.manager.register("dojox.storage.FlashStorageProvider",new dojox.storage.FlashStorageProvider));