/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.storage.GearsStorageProvider"]||(dojo._hasResource["dojox.storage.GearsStorageProvider"]=!0,dojo.provide("dojox.storage.GearsStorageProvider"),dojo.require("dojo.gears"),dojo.require("dojox.storage.Provider"),dojo.require("dojox.storage.manager"),dojo.require("dojox.sql"),dojo.gears.available&&function(){dojo.declare("dojox.storage.GearsStorageProvider",dojox.storage.Provider,{constructor:function(){},TABLE_NAME:"__DOJO_STORAGE",initialized:!1,_available:null,_storageReady:!1,
initialize:function(){if(dojo.config.disableGearsStorage!=!0)this.TABLE_NAME="__DOJO_STORAGE",this.initialized=!0,dojox.storage.manager.loaded()},isAvailable:function(){return this._available=dojo.gears.available},put:function(a,b,c,d){this._initStorage();if(!this.isValidKey(a))throw Error("Invalid key given: "+a);d=d||this.DEFAULT_NAMESPACE;if(!this.isValidKey(d))throw Error("Invalid namespace given: "+a);b=dojo.isString(b)?"string:"+b:dojo.toJson(b);try{dojox.sql("DELETE FROM "+this.TABLE_NAME+
" WHERE namespace = ? AND key = ?",d,a),dojox.sql("INSERT INTO "+this.TABLE_NAME+" VALUES (?, ?, ?)",d,a,b)}catch(f){console.debug("dojox.storage.GearsStorageProvider.put:",f);c(this.FAILED,a,f.toString(),d);return}c&&c(dojox.storage.SUCCESS,a,null,d)},get:function(a,b){this._initStorage();if(!this.isValidKey(a))throw Error("Invalid key given: "+a);b=b||this.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+a);var c=dojox.sql("SELECT * FROM "+this.TABLE_NAME+" WHERE namespace = ? AND  key = ?",
b,a);if(c.length)c=c[0].value;else return null;return c=dojo.isString(c)&&/^string:/.test(c)?c.substring(7):dojo.fromJson(c)},getNamespaces:function(){this._initStorage();for(var a=[dojox.storage.DEFAULT_NAMESPACE],b=dojox.sql("SELECT namespace FROM "+this.TABLE_NAME+" DESC GROUP BY namespace"),c=0;c<b.length;c++)b[c].namespace!=dojox.storage.DEFAULT_NAMESPACE&&a.push(b[c].namespace);return a},getKeys:function(a){this._initStorage();a=a||this.DEFAULT_NAMESPACE;if(!this.isValidKey(a))throw Error("Invalid namespace given: "+
a);for(var a=dojox.sql("SELECT key FROM "+this.TABLE_NAME+" WHERE namespace = ?",a),b=[],c=0;c<a.length;c++)b.push(a[c].key);return b},clear:function(a){this._initStorage();a=a||this.DEFAULT_NAMESPACE;if(!this.isValidKey(a))throw Error("Invalid namespace given: "+a);dojox.sql("DELETE FROM "+this.TABLE_NAME+" WHERE namespace = ?",a)},remove:function(a,b){this._initStorage();if(!this.isValidKey(a))throw Error("Invalid key given: "+a);b=b||this.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+
a);dojox.sql("DELETE FROM "+this.TABLE_NAME+" WHERE namespace = ? AND key = ?",b,a)},putMultiple:function(a,b,c,d){this._initStorage();if(!this.isValidKeyArray(a)||!b instanceof Array||a.length!=b.length)throw Error("Invalid arguments: keys = ["+a+"], values = ["+b+"]");if(d==null||typeof d=="undefined")d=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(d))throw Error("Invalid namespace given: "+d);this._statusHandler=c;try{dojox.sql.open();dojox.sql.db.execute("BEGIN TRANSACTION");for(var f="REPLACE INTO "+
this.TABLE_NAME+" VALUES (?, ?, ?)",e=0;e<a.length;e++){var g=b[e],g=dojo.isString(g)?"string:"+g:dojo.toJson(g);dojox.sql.db.execute(f,[d,a[e],g])}dojox.sql.db.execute("COMMIT TRANSACTION");dojox.sql.close()}catch(h){console.debug("dojox.storage.GearsStorageProvider.putMultiple:",h);c&&c(this.FAILED,a,h.toString(),d);return}c&&c(dojox.storage.SUCCESS,a,null,d)},getMultiple:function(a,b){this._initStorage();if(!this.isValidKeyArray(a))throw new ("Invalid key array given: "+a);if(b==null||typeof b==
"undefined")b=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+b);for(var c="SELECT * FROM "+this.TABLE_NAME+" WHERE namespace = ? AND  key = ?",d=[],f=0;f<a.length;f++){var e=dojox.sql(c,b,a[f]);e.length?(e=e[0].value,d[f]=dojo.isString(e)&&/^string:/.test(e)?e.substring(7):dojo.fromJson(e)):d[f]=null}return d},removeMultiple:function(a,b){this._initStorage();if(!this.isValidKeyArray(a))throw Error("Invalid arguments: keys = ["+a+"]");if(b==null||typeof b==
"undefined")b=dojox.storage.DEFAULT_NAMESPACE;if(!this.isValidKey(b))throw Error("Invalid namespace given: "+b);dojox.sql.open();dojox.sql.db.execute("BEGIN TRANSACTION");for(var c="DELETE FROM "+this.TABLE_NAME+" WHERE namespace = ? AND key = ?",d=0;d<a.length;d++)dojox.sql.db.execute(c,[b,a[d]]);dojox.sql.db.execute("COMMIT TRANSACTION");dojox.sql.close()},isPermanent:function(){return!0},getMaximumSize:function(){return this.SIZE_NO_LIMIT},hasSettingsUI:function(){return!1},showSettingsUI:function(){throw Error(this.declaredClass+
" does not support a storage settings user-interface");},hideSettingsUI:function(){throw Error(this.declaredClass+" does not support a storage settings user-interface");},_initStorage:function(){if(!this._storageReady){if(!google.gears.factory.hasPermission&&!google.gears.factory.getPermission(null,null,"This site would like to use Google Gears to enable enhanced functionality."))throw Error("You must give permission to use Gears in order to store data");try{dojox.sql("CREATE TABLE IF NOT EXISTS "+
this.TABLE_NAME+"(  namespace TEXT,  key TEXT,  value TEXT )"),dojox.sql("CREATE UNIQUE INDEX IF NOT EXISTS namespace_key_index ON "+this.TABLE_NAME+" (namespace, key)")}catch(a){throw console.debug("dojox.storage.GearsStorageProvider._createTables:",a),Error("Unable to create storage tables for Gears in Dojo Storage");}this._storageReady=!0}}});dojox.storage.manager.register("dojox.storage.GearsStorageProvider",new dojox.storage.GearsStorageProvider)}());