/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.storage.LocalStorageProvider"]||(dojo._hasResource["dojox.storage.LocalStorageProvider"]=!0,dojo.provide("dojox.storage.LocalStorageProvider"),dojo.require("dojox.storage.Provider"),dojo.require("dojox.storage.manager"),dojo.declare("dojox.storage.LocalStorageProvider",[dojox.storage.Provider],{store:null,initialize:function(){this.store=localStorage;this.initialized=!0;dojox.storage.manager.loaded()},isAvailable:function(){return typeof localStorage!="undefined"},put:function(a,
b,c,d){this._assertIsValidKey(a);d=d||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(d);var e=this.getFullKey(a,d),b=dojo.toJson(b);try{this.store.setItem(e,b),c&&c(this.SUCCESS,a,null,d)}catch(f){c&&c(this.FAILED,a,f.toString(),d)}},get:function(a,b){this._assertIsValidKey(a);b=b||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(b);a=this.getFullKey(a,b);return dojo.fromJson(this.store.getItem(a))},getKeys:function(a){a=a||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(a);for(var a=
"__"+a+"_",b=[],c=0;c<this.store.length;c++){var d=this.store.key(c);this._beginsWith(d,a)&&(d=d.substring(a.length),b.push(d))}return b},clear:function(a){a=a||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(a);for(var a="__"+a+"_",b=[],c=0;c<this.store.length;c++)this._beginsWith(this.store.key(c),a)&&b.push(this.store.key(c));dojo.forEach(b,dojo.hitch(this.store,"removeItem"))},remove:function(a,b){b=b||this.DEFAULT_NAMESPACE;this._assertIsValidNamespace(b);this.store.removeItem(this.getFullKey(a,
b))},getNamespaces:function(){var a=[this.DEFAULT_NAMESPACE],b={};b[this.DEFAULT_NAMESPACE]=!0;for(var c=/^__([^_]*)_/,d=0;d<this.store.length;d++){var e=this.store.key(d);c.test(e)==!0&&(e=e.match(c)[1],typeof b[e]=="undefined"&&(b[e]=!0,a.push(e)))}return a},isPermanent:function(){return!0},getMaximumSize:function(){return dojox.storage.SIZE_NO_LIMIT},hasSettingsUI:function(){return!1},isValidKey:function(a){return a===null||a===void 0?!1:/^[0-9A-Za-z_-]*$/.test(a)},isValidNamespace:function(a){return a===
null||a===void 0?!1:/^[0-9A-Za-z-]*$/.test(a)},getFullKey:function(a,b){return"__"+b+"_"+a},_beginsWith:function(a,b){return b.length>a.length?!1:a.substring(0,b.length)===b},_assertIsValidNamespace:function(a){if(this.isValidNamespace(a)===!1)throw Error("Invalid namespace given: "+a);},_assertIsValidKey:function(a){if(this.isValidKey(a)===!1)throw Error("Invalid key given: "+a);}}),dojox.storage.manager.register("dojox.storage.LocalStorageProvider",new dojox.storage.LocalStorageProvider));