/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.Calendar"]||(dojo._hasResource["dojox.widget.Calendar"]=!0,dojo.provide("dojox.widget.Calendar"),dojo.experimental("dojox.widget.Calendar"),dojo.require("dijit.Calendar"),dojo.require("dijit._Container"),dojo.declare("dojox.widget._CalendarBase",[dijit._Widget,dijit._Templated,dijit._Container],{templateString:dojo.cache("dojox.widget","Calendar/Calendar.html",'<div class="dojoxCalendar">\n    <div tabindex="0" class="dojoxCalendarContainer" style="visibility: visible;" dojoAttachPoint="container">\n\t\t<div style="display:none">\n\t\t\t<div dojoAttachPoint="previousYearLabelNode"></div>\n\t\t\t<div dojoAttachPoint="nextYearLabelNode"></div>\n\t\t\t<div dojoAttachPoint="monthLabelSpacer"></div>\n\t\t</div>\n        <div class="dojoxCalendarHeader">\n            <div>\n                <div class="dojoxCalendarDecrease" dojoAttachPoint="decrementMonth"></div>\n            </div>\n            <div class="">\n                <div class="dojoxCalendarIncrease" dojoAttachPoint="incrementMonth"></div>\n            </div>\n            <div class="dojoxCalendarTitle" dojoAttachPoint="header" dojoAttachEvent="onclick: onHeaderClick">\n            </div>\n        </div>\n        <div class="dojoxCalendarBody" dojoAttachPoint="containerNode"></div>\n        <div class="">\n            <div class="dojoxCalendarFooter" dojoAttachPoint="footer">                        \n            </div>\n        </div>\n    </div>\n</div>\n'),
_views:null,useFx:!0,widgetsInTemplate:!0,value:new Date,constraints:null,footerFormat:"medium",constructor:function(){this._views=[];this.value=new Date},postMixInProperties:function(){var a=this.constraints;if(a){var b=dojo.date.stamp.fromISOString;if(typeof a.min=="string")a.min=b(a.min);if(typeof a.max=="string")a.max=b(a.max)}this.value=this.parseInitialValue(this.value)},parseInitialValue:function(a){if(!a||a===-1)return new Date;else!a.getFullYear&&!isNaN(a)&&(typeof this.value=="string"&&
(a=parseInt(a)),a=this._makeDate(a));return a},_makeDate:function(a){return a},postCreate:function(){this.displayMonth=new Date(this.get("value"));if(this._isInvalidDate(this.displayMonth))this.displayMonth=new Date;var a={parent:this,_getValueAttr:dojo.hitch(this,function(){return new Date(this._internalValue||this.value)}),_getDisplayMonthAttr:dojo.hitch(this,function(){return new Date(this.displayMonth)}),_getConstraintsAttr:dojo.hitch(this,function(){return this.constraints}),getLang:dojo.hitch(this,
function(){return this.lang}),isDisabledDate:dojo.hitch(this,this.isDisabledDate),getClassForDate:dojo.hitch(this,this.getClassForDate),addFx:this.useFx?dojo.hitch(this,this.addFx):function(){}};dojo.forEach(this._views,function(b){b=new b(a,dojo.create("div"));this.addChild(b);var c=b.getHeader();c&&(this.header.appendChild(c),dojo.style(c,"display","none"));dojo.style(b.domNode,"visibility","hidden");dojo.connect(b,"onValueSelected",this,"_onDateSelected");b.set("value",this.get("value"))},this);
this._views.length<2&&dojo.style(this.header,"cursor","auto");this.inherited(arguments);this._children=this.getChildren();this._currentChild=0;this.footer.innerHTML="Today: "+dojo.date.locale.format(new Date,{formatLength:this.footerFormat,selector:"date",locale:this.lang});dojo.connect(this.footer,"onclick",this,"goToToday");var b=this._children[0];dojo.style(b.domNode,"top","0px");dojo.style(b.domNode,"visibility","visible");b.getHeader()&&dojo.style(b.getHeader(),"display","");dojo[b.useHeader?
"removeClass":"addClass"](this.container,"no-header");b.onDisplay();var c=this,b=function(a,b,i){dijit.typematic.addMouseListener(c[a],c,function(a){a>=0&&c._adjustDisplay(b,i)},0.8,500)};b("incrementMonth","month",1);b("decrementMonth","month",-1);this._updateTitleStyle()},addFx:function(){},_isInvalidDate:function(a){return!a||isNaN(a)||typeof a!="object"||a.toString()==this._invalidDate},_setValueAttr:function(a){a||(a=new Date);a.getFullYear||(a=dojo.date.stamp.fromISOString(a+""));if(this._isInvalidDate(a))return!1;
if(!this.value||dojo.date.compare(a,this.value)){a=new Date(a);this.displayMonth=new Date(a);this._internalValue=a;if(!this.isDisabledDate(a,this.lang)&&this._currentChild==0)this.value=a,this.onChange(a);this._children&&this._children.length>0&&this._children[this._currentChild].set("value",this.value);return!0}return!1},isDisabledDate:function(a){var b=this.constraints,c=dojo.date.compare;return b&&(b.min&&c(b.min,a,"date")>0||b.max&&c(b.max,a,"date")<0)},onValueSelected:function(){},_onDateSelected:function(a,
b){this.displayMonth=a;this.set("value",a);this._transitionVert(-1)||(!b&&b!==0&&(b=this.get("value")),this.onValueSelected(b))},onChange:function(){},onHeaderClick:function(){this._transitionVert(1)},goToToday:function(){this.set("value",new Date);this.onValueSelected(this.get("value"))},_transitionVert:function(a){var b=this._children[this._currentChild],c=this._children[this._currentChild+a];if(!c)return!1;dojo.style(c.domNode,"visibility","visible");var d=dojo.style(this.containerNode,"height");
c.set("value",this.displayMonth);b.header&&dojo.style(b.header,"display","none");c.header&&dojo.style(c.header,"display","");dojo.style(c.domNode,"top",d*-1+"px");dojo.style(c.domNode,"visibility","visible");this._currentChild+=a;a*=d;dojo.style(c.domNode,"top",a*-1+"px");a=dojo.animateProperty({node:b.domNode,properties:{top:a},onEnd:function(){dojo.style(b.domNode,"visibility","hidden")}});d=dojo.animateProperty({node:c.domNode,properties:{top:0},onEnd:function(){c.onDisplay()}});dojo[c.useHeader?
"removeClass":"addClass"](this.container,"no-header");a.play();d.play();b.onBeforeUnDisplay();c.onBeforeDisplay();this._updateTitleStyle();return!0},_updateTitleStyle:function(){dojo[this._currentChild<this._children.length-1?"addClass":"removeClass"](this.header,"navToPanel")},_slideTable:function(a,b,c){var a=a.domNode,d=a.cloneNode(!0),f=dojo.style(a,"width");a.parentNode.appendChild(d);dojo.style(a,"left",f*b+"px");c();b=dojo.animateProperty({node:d,properties:{left:f*b*-1},duration:500,onEnd:function(){d.parentNode.removeChild(d)}});
c=dojo.animateProperty({node:a,properties:{left:0},duration:500});b.play();c.play()},_addView:function(a){this._views.push(a)},getClassForDate:function(){},_adjustDisplay:function(a,b){var c=this._children[this._currentChild],d=this.displayMonth=c.adjustDate(this.displayMonth,b);this._slideTable(c,b,function(){c.set("value",d)})}}),dojo.declare("dojox.widget._CalendarView",dijit._Widget,{headerClass:"",useHeader:!0,cloneClass:function(a,b,c){var d=dojo.query(a,this.domNode)[0];if(c){c=dojo.query(a,
this.domNode)[0];for(a=0;a<b;a++)d.parentNode.insertBefore(d.cloneNode(!0),c)}else for(a=0;a<b;a++)d.parentNode.appendChild(d.cloneNode(!0))},_setText:function(a,b){a.innerHTML!=b&&(dojo.empty(a),a.appendChild(dojo.doc.createTextNode(b)))},getHeader:function(){return this.header||(this.header=this.header=dojo.create("span",{"class":this.headerClass}))},onValueSelected:function(){},adjustDate:function(a,b){return dojo.date.add(a,this.datePart,b)},onDisplay:function(){},onBeforeDisplay:function(){},
onBeforeUnDisplay:function(){}}),dojo.declare("dojox.widget._CalendarDay",null,{parent:null,constructor:function(){this._addView(dojox.widget._CalendarDayView)}}),dojo.declare("dojox.widget._CalendarDayView",[dojox.widget._CalendarView,dijit._Templated],{templateString:dojo.cache("dojox.widget","Calendar/CalendarDay.html",'<div class="dijitCalendarDayLabels" style="left: 0px;" dojoAttachPoint="dayContainer">\n\t<div dojoAttachPoint="header">\n\t\t<div dojoAttachPoint="monthAndYearHeader">\n\t\t\t<span dojoAttachPoint="monthLabelNode" class="dojoxCalendarMonthLabelNode"></span>\n\t\t\t<span dojoAttachPoint="headerComma" class="dojoxCalendarComma">,</span>\n\t\t\t<span dojoAttachPoint="yearLabelNode" class="dojoxCalendarDayYearLabel"></span>\n\t\t</div>\n\t</div>\n\t<table cellspacing="0" cellpadding="0" border="0" style="margin: auto;">\n\t\t<thead>\n\t\t\t<tr>\n\t\t\t\t<td class="dijitCalendarDayLabelTemplate"><div class="dijitCalendarDayLabel"></div></td>\n\t\t\t</tr>\n\t\t</thead>\n\t\t<tbody dojoAttachEvent="onclick: _onDayClick">\n\t\t\t<tr class="dijitCalendarWeekTemplate">\n\t\t\t\t<td class="dojoxCalendarNextMonth dijitCalendarDateTemplate">\n\t\t\t\t\t<div class="dijitCalendarDateLabel"></div>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n</div>\n'),
datePart:"month",dayWidth:"narrow",postCreate:function(){this.cloneClass(".dijitCalendarDayLabelTemplate",6);this.cloneClass(".dijitCalendarDateTemplate",6);this.cloneClass(".dijitCalendarWeekTemplate",5);var a=dojo.date.locale.getNames("days",this.dayWidth,"standAlone",this.getLang()),b=dojo.cldr.supplemental.getFirstDayOfWeek(this.getLang());dojo.query(".dijitCalendarDayLabel",this.domNode).forEach(function(c,d){this._setText(c,a[(d+b)%7])},this)},onDisplay:function(){if(!this._addedFx)this._addedFx=
!0,this.addFx(".dijitCalendarDateTemplate div",this.domNode)},_onDayClick:function(a){if(typeof a.target._date!="undefined"){var b=new Date(this.get("displayMonth")),c=a.target.parentNode;(c=dojo.hasClass(c,"dijitCalendarPreviousMonth")?-1:dojo.hasClass(c,"dijitCalendarNextMonth")?1:0)&&(b=dojo.date.add(b,"month",c));b.setDate(a.target._date);this.isDisabledDate(b)?dojo.stopEvent(a):this.parent._onDateSelected(b)}},_setValueAttr:function(){this._populateDays()},_populateDays:function(){var a=new Date(this.get("displayMonth"));
a.setDate(1);var b=a.getDay(),c=dojo.date.getDaysInMonth(a),d=dojo.date.getDaysInMonth(dojo.date.add(a,"month",-1)),f=new Date,i=this.get("value"),m=dojo.cldr.supplemental.getFirstDayOfWeek(this.getLang());m>b&&(m-=7);var l=dojo.date.compare,h=this._lastDate,h=h==null||h.getMonth()!=a.getMonth()||h.getFullYear()!=a.getFullYear();this._lastDate=a;h?(dojo.query(".dijitCalendarDateTemplate",this.domNode).forEach(function(n,j){j+=m;var g=new Date(a),k,e="dijitCalendar",h=0;j<b?(k=d-b+j+1,h=-1,e+="Previous"):
j>=b+c?(k=j-b-c+1,h=1,e+="Next"):(k=j-b+1,e+="Current");h&&(g=dojo.date.add(g,"month",h));g.setDate(k);l(g,f,"date")||(e="dijitCalendarCurrentDate "+e);!l(g,i,"date")&&!l(g,i,"month")&&!l(g,i,"year")&&(e="dijitCalendarSelectedDate "+e);this.isDisabledDate(g,this.getLang())&&(e=" dijitCalendarDisabledDate "+e);(k=this.getClassForDate(g,this.getLang()))&&(e=k+" "+e);n.className=e+"Month dijitCalendarDateTemplate";n.dijitDateValue=g.valueOf();e=dojo.query(".dijitCalendarDateLabel",n)[0];this._setText(e,
g.getDate());e._date=e.parentNode._date=g.getDate()},this),this._setText(this.monthLabelNode,dojo.date.locale.getNames("months","wide","standAlone",this.getLang())[a.getMonth()]),this._setText(this.yearLabelNode,a.getFullYear())):dojo.query(".dijitCalendarDateTemplate",this.domNode).removeClass("dijitCalendarSelectedDate").filter(function(a){return a.className.indexOf("dijitCalendarCurrent")>-1&&a._date==i.getDate()}).addClass("dijitCalendarSelectedDate")}}),dojo.declare("dojox.widget._CalendarMonthYear",
null,{constructor:function(){this._addView(dojox.widget._CalendarMonthYearView)}}),dojo.declare("dojox.widget._CalendarMonthYearView",[dojox.widget._CalendarView,dijit._Templated],{templateString:dojo.cache("dojox.widget","Calendar/CalendarMonthYear.html",'<div class="dojoxCal-MY-labels" style="left: 0px;"\t\n\tdojoAttachPoint="myContainer" dojoAttachEvent="onclick: onClick">\n\t\t<table cellspacing="0" cellpadding="0" border="0" style="margin: auto;">\n\t\t\t\t<tbody>\n\t\t\t\t\t\t<tr class="dojoxCal-MY-G-Template">\n\t\t\t\t\t\t\t\t<td class="dojoxCal-MY-M-Template">\n\t\t\t\t\t\t\t\t\t\t<div class="dojoxCalendarMonthLabel"></div>\n\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t<td class="dojoxCal-MY-M-Template">\n\t\t\t\t\t\t\t\t\t\t<div class="dojoxCalendarMonthLabel"></div>\n\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t<td class="dojoxCal-MY-Y-Template">\n\t\t\t\t\t\t\t\t\t\t<div class="dojoxCalendarYearLabel"></div>\n\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t<td class="dojoxCal-MY-Y-Template">\n\t\t\t\t\t\t\t\t\t\t<div class="dojoxCalendarYearLabel"></div>\n\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t </tr>\n\t\t\t\t\t\t <tr class="dojoxCal-MY-btns">\n\t\t\t\t\t\t \t <td class="dojoxCal-MY-btns" colspan="4">\n\t\t\t\t\t\t \t\t <span class="dijitReset dijitInline dijitButtonNode ok-btn" dojoAttachEvent="onclick: onOk" dojoAttachPoint="okBtn">\n\t\t\t\t\t\t \t \t \t <button\tclass="dijitReset dijitStretch dijitButtonContents">OK</button>\n\t\t\t\t\t\t\t\t </span>\n\t\t\t\t\t\t\t\t <span class="dijitReset dijitInline dijitButtonNode cancel-btn" dojoAttachEvent="onclick: onCancel" dojoAttachPoint="cancelBtn">\n\t\t\t\t\t\t \t \t\t <button\tclass="dijitReset dijitStretch dijitButtonContents">Cancel</button>\n\t\t\t\t\t\t\t\t </span>\n\t\t\t\t\t\t \t </td>\n\t\t\t\t\t\t </tr>\n\t\t\t\t</tbody>\n\t\t</table>\n</div>\n'),
datePart:"year",displayedYears:10,useHeader:!1,postCreate:function(){this.cloneClass(".dojoxCal-MY-G-Template",5,".dojoxCal-MY-btns");this.monthContainer=this.yearContainer=this.myContainer;dojo.query(".dojoxCalendarYearLabel",this.myContainer).forEach(function(a,b){var c="dojoxCalendarIncrease";switch(b){case 0:c="dojoxCalendarDecrease";case 1:dojo.removeClass(a,"dojoxCalendarYearLabel"),dojo.addClass(a,c)}});this._decBtn=dojo.query(".dojoxCalendarDecrease",this.myContainer)[0];this._incBtn=dojo.query(".dojoxCalendarIncrease",
this.myContainer)[0];dojo.query(".dojoxCal-MY-M-Template",this.domNode).filter(function(a){return a.cellIndex==1}).addClass("dojoxCal-MY-M-last");dojo.connect(this,"onBeforeDisplay",dojo.hitch(this,function(){this._cachedDate=new Date(this.get("value").getTime());this._populateYears(this._cachedDate.getFullYear());this._populateMonths();this._updateSelectedMonth();this._updateSelectedYear()}));dojo.connect(this,"_populateYears",dojo.hitch(this,function(){this._updateSelectedYear()}));dojo.connect(this,
"_populateMonths",dojo.hitch(this,function(){this._updateSelectedMonth()}));this._cachedDate=this.get("value");this._populateYears();this._populateMonths();this.addFx(".dojoxCalendarMonthLabel,.dojoxCalendarYearLabel ",this.myContainer)},_setValueAttr:function(a){a&&a.getFullYear()&&this._populateYears(a.getFullYear())},getHeader:function(){return null},_getMonthNames:function(a){return this._monthNames=this._monthNames||dojo.date.locale.getNames("months",a,"standAlone",this.getLang())},_populateMonths:function(){var a=
this._getMonthNames("abbr");dojo.query(".dojoxCalendarMonthLabel",this.monthContainer).forEach(dojo.hitch(this,function(b,c){this._setText(b,a[c])}));var b=this.get("constraints");if(b){(new Date).setFullYear(this._year);var c=-1,d=12;if(b.min){var f=b.min.getFullYear();f>this._year?c=12:f==this._year&&(c=b.min.getMonth())}b.max&&(f=b.max.getFullYear(),f<this._year?d=-1:f==this._year&&(d=b.max.getMonth()));dojo.query(".dojoxCalendarMonthLabel",this.monthContainer).forEach(dojo.hitch(this,function(a,
b){dojo[b<c||b>d?"addClass":"removeClass"](a,"dijitCalendarDisabledDate")}))}this.getHeader()&&this._setText(this.getHeader(),this.get("value").getFullYear())},_populateYears:function(a){var b=this.get("constraints"),c=a||this.get("value").getFullYear(),d=c-Math.floor(this.displayedYears/2),a=b&&b.min?b.min.getFullYear():d-1E4,d=Math.max(a,d);this._displayedYear=c;var c=dojo.query(".dojoxCalendarYearLabel",this.yearContainer),f=b&&b.max?b.max.getFullYear()-d:c.length;c.forEach(dojo.hitch(this,function(a,
b){b<=f?(this._setText(a,d+b),dojo.removeClass(a,"dijitCalendarDisabledDate")):dojo.addClass(a,"dijitCalendarDisabledDate")}));if(this._incBtn)dojo[f<c.length?"addClass":"removeClass"](this._incBtn,"dijitCalendarDisabledDate");if(this._decBtn)dojo[a>=d?"addClass":"removeClass"](this._decBtn,"dijitCalendarDisabledDate");this.getHeader()&&this._setText(this.getHeader(),d+" - "+(d+11))},_updateSelectedYear:function(){this._year=String((this._cachedDate||this.get("value")).getFullYear());this._updateSelectedNode(".dojoxCalendarYearLabel",
dojo.hitch(this,function(a){return this._year!==null&&a.innerHTML==this._year}))},_updateSelectedMonth:function(){var a=(this._cachedDate||this.get("value")).getMonth();this._month=a;this._updateSelectedNode(".dojoxCalendarMonthLabel",function(b,c){return c==a})},_updateSelectedNode:function(a,b){dojo.query(a,this.domNode).forEach(function(a,c,i){dojo[b(a,c,i)?"addClass":"removeClass"](a.parentNode,"dijitCalendarSelectedDate")});var c=dojo.query(".dojoxCal-MY-M-Template div",this.myContainer).filter(function(a){return dojo.hasClass(a.parentNode,
"dijitCalendarSelectedDate")})[0];c&&(c=dojo.hasClass(c,"dijitCalendarDisabledDate"),dojo[c?"addClass":"removeClass"](this.okBtn,"dijitDisabled"))},onClick:function(a){function b(b){return dojo.hasClass(a.target,b)}if(b("dijitCalendarDisabledDate"))return dojo.stopEvent(a),!1;if(b("dojoxCalendarMonthLabel"))this._month=a.target.parentNode.cellIndex+a.target.parentNode.parentNode.rowIndex*2,this._cachedDate.setMonth(this._month),this._updateSelectedMonth();else if(b("dojoxCalendarYearLabel"))this._year=
Number(a.target.innerHTML),this._cachedDate.setYear(this._year),this._populateMonths(),this._updateSelectedYear();else return b("dojoxCalendarDecrease")?this._populateYears(this._displayedYear-10):b("dojoxCalendarIncrease")&&this._populateYears(this._displayedYear+10),!0;dojo.stopEvent(a);return!1},onOk:function(a){dojo.stopEvent(a);if(dojo.hasClass(this.okBtn,"dijitDisabled"))return!1;this.onValueSelected(this._cachedDate);return!1},onCancel:function(a){dojo.stopEvent(a);this.onValueSelected(this.get("value"));
return!1}}),dojo.declare("dojox.widget.Calendar2Pane",[dojox.widget._CalendarBase,dojox.widget._CalendarDay,dojox.widget._CalendarMonthYear],{}),dojo.declare("dojox.widget.Calendar",[dojox.widget._CalendarBase,dojox.widget._CalendarDay,dojox.widget._CalendarMonthYear],{}),dojo.declare("dojox.widget.DailyCalendar",[dojox.widget._CalendarBase,dojox.widget._CalendarDay],{_makeDate:function(a){var b=new Date;b.setDate(a);return b}}),dojo.declare("dojox.widget.MonthAndYearlyCalendar",[dojox.widget._CalendarBase,
dojox.widget._CalendarMonthYear],{}));