/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.DataPresentation"]||(dojo._hasResource["dojox.widget.DataPresentation"]=!0,dojo.provide("dojox.widget.DataPresentation"),dojo.experimental("dojox.widget.DataPresentation"),dojo.require("dojox.grid.DataGrid"),dojo.require("dojox.charting.Chart2D"),dojo.require("dojox.charting.widget.Legend"),dojo.require("dojox.charting.action2d.Tooltip"),dojo.require("dojox.charting.action2d.Highlight"),dojo.require("dojo.colors"),dojo.require("dojo.data.ItemFileWriteStore"),function(){var x=
function(b,c,a,d){var f=[{value:0,text:""}],l=b.length;if(a!=="ClusteredBars"&&a!=="StackedBars"&&(a=d.offsetWidth,d=(""+b[0]).length*b.length*7,c==1))for(var h=1;h<500;++h){if(d/h<a)break;++c}for(a=0;a<l;a++)f.push({value:a+1,text:!c||a%c?"":b[a]});f.push({value:l+1,text:""});return f},y=function(b,c){var a={vertical:!1,labels:c,min:0,max:c.length-1,majorTickStep:1,minorTickStep:1};if(b==="ClusteredBars"||b==="StackedBars")a.vertical=!0;if(b==="Lines"||b==="Areas"||b==="StackedAreas")a.min++,a.max--;
return a},w=function(b,c,a,d){var f={vertical:!0,fixLower:"major",fixUpper:"major",natural:!0};if(c==="secondary")f.leftBottom=!1;if(b==="ClusteredBars"||b==="StackedBars")f.vertical=!1;if(a==d)f.min=a-1,f.max=d+1;return f},z=function(b,c,a){c={type:b,hAxis:"independent",vAxis:"dependent-"+c,gap:4,lines:!1,areas:!1,markers:!1};if(b==="ClusteredBars"||b==="StackedBars")c.hAxis=c.vAxis,c.vAxis="independent";if(b==="Lines"||b==="Hybrid-Lines"||b==="Areas"||b==="StackedAreas")c.lines=!0;if(b==="Areas"||
b==="StackedAreas")c.areas=!0;if(b==="Lines")c.markers=!0;if(b==="Hybrid-Lines")c.shadows={dx:2,dy:2,dw:2},c.type="Lines";if(b==="Hybrid-ClusteredColumns")c.type="ClusteredColumns";if(a)c.animate=a;return c},A=function(b,c,a,d,f,l,h,q,j){if(!c)b.innerHTML="",c=new dojox.charting.Chart2D(b);if(h)h._clone=function(){var a=new dojox.charting.Theme({chart:this.chart,plotarea:this.plotarea,axis:this.axis,series:this.series,marker:this.marker,antiAlias:this.antiAlias,assignColors:this.assignColors,assignMarkers:this.assigneMarkers,
colors:dojo.delegate(this.colors)});a.markers=this.markers;a._buildMarkerArray();return a},c.setTheme(h);var r=j.series_data[0].slice(0);d&&r.reverse();var b=x(r,l,a,b),l={},p=h=null,s={},n;for(n in c.runs)s[n]=!0;for(var e=j.series_name.length,g=0;g<e;g++)if(j.series_chart[g]&&j.series_data[g].length>0){var k=a,i=j.series_axis[g];k=="Hybrid"&&(k=j.series_charttype[g]=="line"?"Hybrid-Lines":"Hybrid-ClusteredColumns");l[i]||(l[i]={});if(!l[i][k]){var m=i+"-"+k;c.addPlot(m,z(k,i,f));var o={};if(typeof q==
"string")o.text=function(a){return dojo.replace(q,[a.element,a.run.name,r[a.index],k==="ClusteredBars"||k==="StackedBars"?a.x:a.y])};else if(typeof q=="function")o.text=q;new dojox.charting.action2d.Tooltip(c,m,o);k!=="Lines"&&k!=="Hybrid-Lines"&&new dojox.charting.action2d.Highlight(c,m);l[i][k]=!0}for(var m=[],o=j.series_data[g].length,t=0;t<o;t++){var u=j.series_data[g][t];m.push(u);if(h===null||u>h)h=u;if(p===null||u<p)p=u}d&&m.reverse();i={plot:i+"-"+k};if(j.series_linestyle[g])i.stroke={style:j.series_linestyle[g]};
c.addSeries(j.series_name[g],m,i);delete s[j.series_name[g]]}for(n in s)c.removeSeries(n);c.addAxis("independent",y(a,b));c.addAxis("dependent-primary",w(a,"primary",p,h));c.addAxis("dependent-secondary",w(a,"secondary",p,h));return c},v=function(b,c){var a=b;if(c)for(var d=c.split(/[.\[\]]+/),f=0,l=d.length;f<l;f++)a&&(a=a[d[f]]);return a};dojo.declare("dojox.widget.DataPresentation",null,{type:"chart",chartType:"clusteredBars",reverse:!1,animate:null,labelMod:1,legendHorizontal:!0,constructor:function(b,
c){dojo.mixin(this,c);this.domNode=dojo.byId(b);this[this.type+"Node"]=this.domNode;if(typeof this.theme=="string")this.theme=dojo.getObject(this.theme);this.chartNode=dojo.byId(this.chartNode);this.legendNode=dojo.byId(this.legendNode);this.gridNode=dojo.byId(this.gridNode);this.titleNode=dojo.byId(this.titleNode);this.footerNode=dojo.byId(this.footerNode);if(this.legendVertical)this.legendHorizontal=!this.legendVertical;this.url?this.setURL(null,null,this.refreshInterval):this.data?this.setData(null,
this.refreshInterval):this.setStore()},setURL:function(b,c,a){a&&this.cancelRefresh();this.url=b||this.url;this.urlContent=c||this.urlContent;this.refreshInterval=a||this.refreshInterval;var d=this;dojo.xhrGet({url:this.url,content:this.urlContent,handleAs:"json-comment-optional",load:function(a){d.setData(a)},error:function(a,b){d.urlError&&typeof d.urlError=="function"&&d.urlError(a,b)}});if(a&&this.refreshInterval>0)this.refreshIntervalPending=setInterval(function(){d.setURL()},this.refreshInterval)},
setData:function(b,c){c&&this.cancelRefresh();this.data=b||this.data;this.refreshInterval=c||this.refreshInterval;for(var a=typeof this.series=="function"?this.series(this.data):this.series,d=[],f=[],l=[],h=[],q=[],j=[],r=[],p=[],s=[],n=0,e=0;e<a.length;e++){d[e]=v(this.data,a[e].datapoints);if(d[e]&&d[e].length>n)n=d[e].length;f[e]=[];l[e]=a[e].name||(a[e].namefield?v(this.data,a[e].namefield):null)||"series "+e;h[e]=a[e].chart!==!1;q[e]=a[e].charttype||"bar";j[e]=a[e].linestyle;r[e]=a[e].axis||
"primary";p[e]=a[e].grid!==!1;s[e]=a[e].gridformatter}var g,k,i,m,o=[];for(g=0;g<n;g++){k={index:g};for(e=0;e<a.length;e++)d[e]&&d[e].length>g&&(i=v(d[e][g],a[e].field),h[e]&&(m=parseFloat(i),isNaN(m)||(i=m)),k["data."+e]=i,f[e].push(i));o.push(k)}n<=0&&o.push({index:0});a=new dojo.data.ItemFileWriteStore({data:{identifier:"index",items:o}});if(this.data.title)a.title=this.data.title;if(this.data.footer)a.footer=this.data.footer;a.series_data=f;a.series_name=l;a.series_chart=h;a.series_charttype=
q;a.series_linestyle=j;a.series_axis=r;a.series_grid=p;a.series_gridformatter=s;this.setPreparedStore(a);if(c&&this.refreshInterval>0){var t=this;this.refreshIntervalPending=setInterval(function(){t.setData()},this.refreshInterval)}},refresh:function(){this.url?this.setURL(this.url,this.urlContent,this.refreshInterval):this.data&&this.setData(this.data,this.refreshInterval)},cancelRefresh:function(){if(this.refreshIntervalPending)clearInterval(this.refreshIntervalPending),this.refreshIntervalPending=
void 0},setStore:function(b,c,a){this.setPreparedStore(b,c,a)},setPreparedStore:function(b,c,a){this.preparedstore=b||this.store;this.query=c||this.query;this.queryOptions=a||this.queryOptions;if(this.preparedstore){if(this.chartNode)this.chartWidget=A(this.chartNode,this.chartWidget,this.chartType,this.reverse,this.animate,this.labelMod,this.theme,this.tooltip,this.preparedstore,this.query,this,a),this.renderChartWidget();if(this.legendNode){var b=this.legendNode,c=this.chartWidget,a=this.legendHorizontal,
d=this.legendWidget;d?d.refresh():d=new dojox.charting.widget.Legend({chart:c,horizontal:a},b);this.legendWidget=d}if(this.gridNode){b=this.preparedstore;a=this.query;d=this.queryOptions;c=this.gridWidget||new dojox.grid.DataGrid({},this.gridNode);c.startup();c.setStore(b,a,d);a=[];for(d=0;d<b.series_name.length;d++)b.series_grid[d]&&b.series_data[d].length>0&&a.push({field:"data."+d,name:b.series_name[d],width:"auto",formatter:b.series_gridformatter[d]});c.setStructure(a);this.gridWidget=c;this.renderGridWidget()}if(this.titleNode&&
(b=this.preparedstore,b.title))this.titleNode.innerHTML=b.title;if(this.footerNode&&(b=this.preparedstore,b.footer))this.footerNode.innerHTML=b.footer}},renderChartWidget:function(){this.chartWidget&&this.chartWidget.render()},renderGridWidget:function(){this.gridWidget&&this.gridWidget.render()},getChartWidget:function(){return this.chartWidget},getGridWidget:function(){return this.gridWidget},destroy:function(){this.cancelRefresh();this.chartWidget&&(this.chartWidget.destroy(),delete this.chartWidget);
this.legendWidget&&delete this.legendWidget;this.gridWidget&&delete this.gridWidget;if(this.chartNode)this.chartNode.innerHTML="";if(this.legendNode)this.legendNode.innerHTML="";if(this.gridNode)this.gridNode.innerHTML="";if(this.titleNode)this.titleNode.innerHTML="";if(this.footerNode)this.footerNode.innerHTML=""}})}());