/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.DocTester"]||(dojo._hasResource["dojox.widget.DocTester"]=!0,dojo.provide("dojox.widget.DocTester"),dojo.require("dojo.string"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dojox.form.BusyButton"),dojo.require("dojox.testing.DocTest"),dojo.declare("dojox.widget.DocTester",[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.widget","DocTester/DocTester.html",'<div dojoAttachPoint="domNode" class="dojoxDocTester">\n\t<div dojoAttachPoint="containerNode"></div>\n\t<button dojoType="dojox.form.BusyButton" busyLabel="Testing..." dojoAttachPoint="runButtonNode">Run tests</button>\n\t<button dojoType="dijit.form.Button" dojoAttachPoint="resetButtonNode" style="display:none;">Reset</button>\n\t<span>\n\t\t<span dojoAttachPoint="numTestsNode">0</span> tests,\n\t\t<span dojoAttachPoint="numTestsOkNode">0</span> passed,\n\t\t<span dojoAttachPoint="numTestsNokNode">0</span> failed\n\t</span>\n</div>\n'),
widgetsInTemplate:!0,_fillContent:function(b){var a=b.innerHTML;this.doctests=new dojox.testing.DocTest;this.tests=this.doctests.getTestsFromString(this._unescapeHtml(a));for(var b=dojo.map(this.tests,"return item.line-1"),a=a.split("\n"),c='<pre class="testCase testNum0 odd">',d=0;d<a.length;d++){var e=dojo.indexOf(b,d);if(e>0&&e!=-1){var f=e%2?"even":"odd";c+='<div class="actualResult">FAILED, actual result was: <span class="result"></span></div>';c+='</pre><pre class="testCase testNum'+e+" "+f+
'">'}c+=a[d].replace(/^\s+/,"")+"\n"}c+='<div class="actualResult">FAILED, actual result was: <span class="result"></span></div></pre>';this.containerNode.innerHTML=c},postCreate:function(){this.inherited("postCreate",arguments);dojo.connect(this.runButtonNode,"onClick",dojo.hitch(this,"runTests"));dojo.connect(this.resetButtonNode,"onClick",dojo.hitch(this,"reset"));this.numTestsNode.innerHTML=this.tests.length},runTests:function(){for(var b={ok:0,nok:0},a=0;a<this.tests.length;a++){var c=this.doctests.runTest(this.tests[a].commands,
this.tests[a].expectedResult);dojo.query(".testNum"+a,this.domNode).addClass(c.success?"resultOk":"resultNok");if(c.success)b.ok++,this.numTestsOkNode.innerHTML=b.ok;else{b.nok++;this.numTestsNokNode.innerHTML=b.nok;var d=dojo.query(".testNum"+a+" .actualResult",this.domNode)[0];dojo.style(d,"display","inline");dojo.query(".result",d)[0].innerHTML=dojo.toJson(c.actualResult)}}this.runButtonNode.cancel();dojo.style(this.runButtonNode.domNode,"display","none");dojo.style(this.resetButtonNode.domNode,
"display","")},reset:function(){dojo.style(this.runButtonNode.domNode,"display","");dojo.style(this.resetButtonNode.domNode,"display","none");this.numTestsOkNode.innerHTML="0";this.numTestsNokNode.innerHTML="0";dojo.query(".actualResult",this.domNode).style("display","none");dojo.query(".testCase",this.domNode).removeClass("resultOk").removeClass("resultNok")},_unescapeHtml:function(b){return b=String(b).replace(/&amp;/gm,"&").replace(/&lt;/gm,"<").replace(/&gt;/gm,">").replace(/&quot;/gm,'"')}}));