/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.FeedPortlet"]||(dojo._hasResource["dojox.widget.FeedPortlet"]=!0,dojo.provide("dojox.widget.FeedPortlet"),dojo.require("dojox.widget.Portlet"),dojo.require("dijit.Tooltip"),dojo.require("dijit.form.TextBox"),dojo.require("dijit.form.Button"),dojo.require("dojox.data.GoogleFeedStore"),dojo.declare("dojox.widget.FeedPortlet",dojox.widget.Portlet,{local:!1,maxResults:5,url:"",openNew:!0,showFeedTitle:!0,postCreate:function(){this.inherited(arguments);if(this.local&&!dojox.data.AtomReadStore)throw Error(this.declaredClass+
": To use local feeds, you must include dojox.data.AtomReadStore on the page.");},onFeedError:function(){this.containerNode.innerHTML="Error accessing the feed."},addChild:function(a){this.inherited(arguments);var b=a.attr("feedPortletUrl");b&&this.set("url",b)},_getTitle:function(a){a=this.store.getValue(a,"title");return this.local?a.text:a},_getLink:function(a){a=this.store.getValue(a,"link");return this.local?a.href:a},_getContent:function(a){a=this.store.getValue(a,"summary");if(!a)return null;
if(this.local)a=a.text;a=a.split("<script").join("<\!--").split("<\/script>").join("--\>");return a=a.split("<iframe").join("<\!--").split("</iframe>").join("--\>")},_setUrlAttr:function(a){this.url=a;this._started&&this.load()},startup:function(){if(!this.started&&!this._started){this.inherited(arguments);if(!this.url||this.url=="")throw Error(this.id+": A URL must be specified for the feed portlet");this.url&&this.url!=""&&this.load()}},load:function(){this._resultList&&dojo.destroy(this._resultList);
var a,b;this.local?(a=new dojox.data.AtomReadStore({url:this.url}),b={}):(a=new dojox.data.GoogleFeedStore,b={url:this.url});b={query:b,count:this.maxResults,onComplete:dojo.hitch(this,function(b){if(this.showFeedTitle&&a.getFeedValue){var c=this.store.getFeedValue("title");c&&this.set("title",c.text?c.text:c)}this.generateResults(b)}),onError:dojo.hitch(this,"onFeedError")};this.store=a;a.fetch(b)},generateResults:function(a){var b,e=this._resultList=dojo.create("ul",{"class":"dojoxFeedPortletList"},
this.containerNode);dojo.forEach(a,dojo.hitch(this,function(a){var d=dojo.create("li",{innerHTML:'<a href="'+this._getLink(a)+'"'+(this.openNew?' target="_blank"':"")+">"+this._getTitle(a)+"</a>"},e);dojo.connect(d,"onmouseover",dojo.hitch(this,function(g){b&&clearTimeout(b);b=setTimeout(dojo.hitch(this,function(){b=null;var f=this._getContent(a);f&&(f='<div class="dojoxFeedPortletPreview">'+f+"</div>",dojo.query("li",e).forEach(function(a){a!=g.target&&dijit.hideTooltip(a)}),dijit.showTooltip(f,
d.firstChild,!this.isLeftToRight()))}),500)}));dojo.connect(d,"onmouseout",function(){b&&(clearTimeout(b),b=null);dijit.hideTooltip(d.firstChild)})}));this.resize()}}),dojo.declare("dojox.widget.ExpandableFeedPortlet",dojox.widget.FeedPortlet,{onlyOpenOne:!1,generateResults:function(a){var b=this._resultList=dojo.create("ul",{"class":"dojoxFeedPortletExpandableList"},this.containerNode);dojo.forEach(a,dojo.hitch(this,dojo.hitch(this,function(a){var c=dojo.create("li",{"class":"dojoxPortletItemCollapsed"},
b),d=dojo.create("div",{style:"width: 100%;"},c);dojo.create("div",{"class":"dojoxPortletItemSummary",innerHTML:this._getContent(a)},c);dojo.create("span",{"class":"dojoxPortletToggleIcon",innerHTML:"<img src='"+dojo.config.baseUrl+"/resources/blank.gif'>"},d);a=dojo.create("a",{href:this._getLink(a),innerHTML:this._getTitle(a)},d);this.openNew&&dojo.attr(a,"target","_blank")})));dojo.connect(b,"onclick",dojo.hitch(this,function(a){if(dojo.hasClass(a.target,"dojoxPortletToggleIcon")||dojo.hasClass(a.target.parentNode,
"dojoxPortletToggleIcon")){dojo.stopEvent(a);for(var c=a.target.parentNode;c.tagName!="LI";)c=c.parentNode;this.onlyOpenOne&&dojo.query("li",b).filter(function(a){return a!=c}).removeClass("dojoxPortletItemOpen").addClass("dojoxPortletItemCollapsed");a=dojo.hasClass(c,"dojoxPortletItemOpen");dojo.toggleClass(c,"dojoxPortletItemOpen",!a);dojo.toggleClass(c,"dojoxPortletItemCollapsed",a)}}))}}),dojo.declare("dojox.widget.PortletFeedSettings",dojox.widget.PortletSettings,{"class":"dojoxPortletFeedSettings",
urls:null,selectedIndex:0,buildRendering:function(){var a;if(this.urls&&this.urls.length>0)console.log(this.id+" -> creating select with urls ",this.urls),a=dojo.create("select"),this.srcNodeRef&&(dojo.place(a,this.srcNodeRef,"before"),dojo.destroy(this.srcNodeRef)),this.srcNodeRef=a,dojo.forEach(this.urls,function(b){dojo.create("option",{value:b.url||b,innerHTML:b.label||b},a)});if(this.srcNodeRef.tagName=="SELECT"){this.text=this.srcNodeRef;var b=dojo.create("div",{},this.srcNodeRef,"before");
b.appendChild(this.text);this.srcNodeRef=b;dojo.query("option",this.text).filter("return !item.value;").forEach("item.value = item.innerHTML");this.text.value||(this.content&&this.text.options.length==0&&this.text.appendChild(this.content),dojo.attr(a||this.text,"value",this.text.options[this.selectedIndex].value))}this.inherited(arguments)},_setContentAttr:function(){},postCreate:function(){console.log(this.id+" -> postCreate");if(!this.text){var a=this.text=new dijit.form.TextBox({});dojo.create("span",
{innerHTML:"Choose Url: "},this.domNode);this.addChild(a)}this.addChild(new dijit.form.Button({label:"Load",onClick:dojo.hitch(this,function(){this.portlet.attr("url",this.text.tagName=="SELECT"?this.text.value:this.text.attr("value"));this.text.tagName=="SELECT"&&dojo.some(this.text.options,dojo.hitch(this,function(a,e){return a.selected?(this.set("selectedIndex",e),!0):!1}));this.toggle()})}));this.addChild(new dijit.form.Button({label:"Cancel",onClick:dojo.hitch(this,"toggle")}));this.inherited(arguments)},
startup:function(){if(!this._started){console.log(this.id+" -> startup");this.inherited(arguments);if(!this.portlet)throw Error(this.declaredClass+": A PortletFeedSettings widget cannot exist without a Portlet.");this.text.tagName=="SELECT"&&dojo.forEach(this.text.options,dojo.hitch(this,function(a,e){dojo.attr(a,"selected",e==this.selectedIndex)}));var a=this.portlet.attr("url");a?this.text.tagName=="SELECT"?!this.urls&&dojo.query("option[value='"+a+"']",this.text).length<1&&dojo.place(dojo.create("option",
{value:a,innerHTML:a,selected:"true"}),this.text,"first"):this.text.attr("value",a):this.portlet.attr("url",this.get("feedPortletUrl"))}},_getFeedPortletUrlAttr:function(){return this.text.value}}));