/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.FilePicker"]||(dojo._hasResource["dojox.widget.FilePicker"]=!0,dojo.provide("dojox.widget.FilePicker"),dojo.require("dojox.widget.RollingList"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojox.widget","FilePicker",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dojox.widget._FileInfoPane",[dojox.widget._RollingListPane],{templateString:"",templateString:dojo.cache("dojox.widget","FilePicker/_FileInfoPane.html",
'<div class="dojoxFileInfoPane">\n\t<table>\n\t\t<tbody>\n\t\t\t<tr>\n\t\t\t\t<td class="dojoxFileInfoLabel dojoxFileInfoNameLabel">${_messages.name}</td>\n\t\t\t\t<td class="dojoxFileInfoName" dojoAttachPoint="nameNode"></td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td class="dojoxFileInfoLabel dojoxFileInfoPathLabel">${_messages.path}</td>\n\t\t\t\t<td class="dojoxFileInfoPath" dojoAttachPoint="pathNode"></td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td class="dojoxFileInfoLabel dojoxFileInfoSizeLabel">${_messages.size}</td>\n\t\t\t\t<td class="dojoxFileInfoSize" dojoAttachPoint="sizeNode"></td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n\t<div dojoAttachPoint="containerNode" style="display:none;"></div>\n</div>\n'),
postMixInProperties:function(){this._messages=dojo.i18n.getLocalization("dojox.widget","FilePicker",this.lang);this.inherited(arguments)},onItems:function(){var a=this.store,b=this.items[0];b?(this.nameNode.innerHTML=a.getLabel(b),this.pathNode.innerHTML=a.getIdentity(b),this.sizeNode.innerHTML=a.getValue(b,"size"),this.parentWidget.scrollIntoView(this),this.inherited(arguments)):this._onError("Load",Error("No item defined"))}}),dojo.declare("dojox.widget.FilePicker",dojox.widget.RollingList,{className:"dojoxFilePicker",
pathSeparator:"",topDir:"",parentAttr:"parentDir",pathAttr:"path",preloadItems:50,selectDirectories:!0,selectFiles:!0,_itemsMatch:function(a,b){if(!a&&!b)return!0;else if(a&&b)if(a==b)return!0;else if(this._isIdentity){var c=[this.store.getIdentity(a),this.store.getIdentity(b)];dojo.forEach(c,function(a,b){a.lastIndexOf(this.pathSeparator)==a.length-1&&(c[b]=a.substring(0,a.length-1))},this);return c[0]==c[1]}return!1},startup:function(){if(!this._started){this.inherited(arguments);var a,b=this.getChildren()[0],
c=dojo.hitch(this,function(){a&&this.disconnect(a);delete a;var c=b.items[0];if(c){var d=this.store,e=d.getValue(c,this.parentAttr),c=d.getValue(c,this.pathAttr);this.pathSeparator=this.pathSeparator||d.pathSeparator;if(!this.pathSeparator)this.pathSeparator=c.substring(e.length,e.length+1);if(!this.topDir)this.topDir=e,this.topDir.lastIndexOf(this.pathSeparator)!=this.topDir.length-1&&(this.topDir+=this.pathSeparator)}});if(!this.pathSeparator||!this.topDir)b.items?c():a=this.connect(b,"onItems",
c)}},getChildItems:function(a){var b=this.inherited(arguments);!b&&this.store.getValue(a,"directory")&&(b=[]);return b},getMenuItemForItem:function(a){var b={iconClass:"dojoxDirectoryItemIcon"};if(!this.store.getValue(a,"directory")){b.iconClass="dojoxFileItemIcon";var a=this.store.getLabel(a),c=a.lastIndexOf(".");c>=0&&(b.iconClass+=" dojoxFileItemIcon_"+a.substring(c+1));if(!this.selectFiles)b.disabled=!0}return new dijit.MenuItem(b)},getPaneForItem:function(a){var b=null;!a||this.store.isItem(a)&&
this.store.getValue(a,"directory")?b=new dojox.widget._RollingListGroupPane({}):this.store.isItem(a)&&!this.store.getValue(a,"directory")&&(b=new dojox.widget._FileInfoPane({}));return b},_setPathValueAttr:function(a,b,c){a?(a.lastIndexOf(this.pathSeparator)==a.length-1&&(a=a.substring(0,a.length-1)),this.store.fetchItemByIdentity({identity:a,onItem:function(a){if(b)this._lastExecutedValue=a;this.set("value",a);c&&c()},scope:this})):this.set("value",null)},_getPathValueAttr:function(a){if(!a)a=this.value;
return a&&this.store.isItem(a)?this.store.getValue(a,this.pathAttr):""},_setValue:function(a){delete this._setInProgress;var b=this.store;if(a&&b.isItem(a)){if((b=this.store.getValue(a,"directory"))&&!this.selectDirectories||!b&&!this.selectFiles)return}else a=null;if(!this._itemsMatch(this.value,a))this.value=a,this._onChange(a)}}));