/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.FisheyeList"]||(dojo._hasResource["dojox.widget.FisheyeList"]=!0,dojo.provide("dojox.widget.FisheyeList"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit._Container"),dojo.require("dijit._Contained"),dojo.declare("dojox.widget.FisheyeList",[dijit._Widget,dijit._Templated,dijit._Container],{constructor:function(){this.pos={x:-1,y:-1};this.timerScale=1},EDGE:{CENTER:0,LEFT:1,RIGHT:2,TOP:3,BOTTOM:4},templateString:'<div class="dojoxFisheyeListBar" dojoAttachPoint="containerNode"></div>',
snarfChildDomOutput:!0,itemWidth:40,itemHeight:40,itemMaxWidth:150,itemMaxHeight:150,imgNode:null,orientation:"horizontal",isFixed:!1,conservativeTrigger:!1,effectUnits:2,itemPadding:10,attachEdge:"center",labelEdge:"bottom",postCreate:function(){var a=this.EDGE;dojo.setSelectable(this.domNode,!1);var c=this.isHorizontal=this.orientation=="horizontal";this.selectedNode=-1;this.isOver=!1;this.hitY2=this.hitX2=this.hitY1=this.hitX1=-1;this.anchorEdge=this._toEdge(this.attachEdge,a.CENTER);this.labelEdge=
this._toEdge(this.labelEdge,a.TOP);if(this.labelEdge==a.CENTER)this.labelEdge=a.TOP;if(c){if(this.anchorEdge==a.LEFT)this.anchorEdge=a.CENTER;if(this.anchorEdge==a.RIGHT)this.anchorEdge=a.CENTER;if(this.labelEdge==a.LEFT)this.labelEdge=a.TOP;if(this.labelEdge==a.RIGHT)this.labelEdge=a.TOP}else{if(this.anchorEdge==a.TOP)this.anchorEdge=a.CENTER;if(this.anchorEdge==a.BOTTOM)this.anchorEdge=a.CENTER;if(this.labelEdge==a.TOP)this.labelEdge=a.LEFT;if(this.labelEdge==a.BOTTOM)this.labelEdge=a.LEFT}c=this.effectUnits;
this.proximityLeft=this.itemWidth*(c-0.5);this.proximityRight=this.itemWidth*(c-0.5);this.proximityTop=this.itemHeight*(c-0.5);this.proximityBottom=this.itemHeight*(c-0.5);if(this.anchorEdge==a.LEFT)this.proximityLeft=0;if(this.anchorEdge==a.RIGHT)this.proximityRight=0;if(this.anchorEdge==a.TOP)this.proximityTop=0;if(this.anchorEdge==a.BOTTOM)this.proximityBottom=0;this.anchorEdge==a.CENTER&&(this.proximityLeft/=2,this.proximityRight/=2,this.proximityTop/=2,this.proximityBottom/=2)},startup:function(){this.children=
this.getChildren();this._initializePositioning();if(!this.conservativeTrigger)this._onMouseMoveHandle=dojo.connect(document.documentElement,"onmousemove",this,"_onMouseMove");if(this.isFixed)this._onScrollHandle=dojo.connect(document,"onscroll",this,"_onScroll");this._onMouseOutHandle=dojo.connect(document.documentElement,"onmouseout",this,"_onBodyOut");this._addChildHandle=dojo.connect(this,"addChild",this,"_initializePositioning");this._onResizeHandle=dojo.connect(window,"onresize",this,"_initializePositioning")},
_initializePositioning:function(){this.itemCount=this.children.length;this.barWidth=(this.isHorizontal?this.itemCount:1)*this.itemWidth;this.barHeight=(this.isHorizontal?1:this.itemCount)*this.itemHeight;this.totalWidth=this.proximityLeft+this.proximityRight+this.barWidth;this.totalHeight=this.proximityTop+this.proximityBottom+this.barHeight;for(var a=0;a<this.children.length;a++){this.children[a].posX=this.itemWidth*(this.isHorizontal?a:0);this.children[a].posY=this.itemHeight*(this.isHorizontal?
0:a);this.children[a].cenX=this.children[a].posX+this.itemWidth/2;this.children[a].cenY=this.children[a].posY+this.itemHeight/2;var c=this.isHorizontal?this.itemWidth:this.itemHeight,d=this.effectUnits*c,b=this.isHorizontal?this.children[a].cenX:this.children[a].cenY,e=this.isHorizontal?this.proximityLeft:this.proximityTop,f=this.isHorizontal?this.proximityRight:this.proximityBottom,g=this.isHorizontal?this.barWidth:this.barHeight,h=d;h>b+e&&(h=b+e);d>g-b+f&&(d=g-b+f);this.children[a].effectRangeLeft=
h/c;this.children[a].effectRangeRght=d/c}this.domNode.style.width=this.barWidth+"px";this.domNode.style.height=this.barHeight+"px";for(a=0;a<this.children.length;a++)c=this.children[a],b=c.domNode,b.style.left=c.posX+"px",b.style.top=c.posY+"px",b.style.width=this.itemWidth+"px",b.style.height=this.itemHeight+"px",c.imgNode.style.left=this.itemPadding+"%",c.imgNode.style.top=this.itemPadding+"%",c.imgNode.style.width=100-2*this.itemPadding+"%",c.imgNode.style.height=100-2*this.itemPadding+"%";this._calcHitGrid()},
_overElement:function(a,c){var a=dojo.byId(a),d={x:c.pageX,y:c.pageY},b=dojo._getBorderBox(a),e=dojo.coords(a,!0),f=e.y,g=f+b.h,e=e.x,b=e+b.w;return d.x>=e&&d.x<=b&&d.y>=f&&d.y<=g},_onBodyOut:function(a){this._overElement(dojo.body(),a)||this._setDormant(a)},_setDormant:function(){if(this.isOver)this.isOver=!1,this.conservativeTrigger&&dojo.disconnect(this._onMouseMoveHandle),this._onGridMouseMove(-1,-1)},_setActive:function(a){if(!this.isOver&&(this.isOver=!0,this.conservativeTrigger))this._onMouseMoveHandle=
dojo.connect(document.documentElement,"onmousemove",this,"_onMouseMove"),this.timerScale=0,this._onMouseMove(a),this._expandSlowly()},_onMouseMove:function(a){a.pageX>=this.hitX1&&a.pageX<=this.hitX2&&a.pageY>=this.hitY1&&a.pageY<=this.hitY2?(this.isOver||this._setActive(a),this._onGridMouseMove(a.pageX-this.hitX1,a.pageY-this.hitY1)):this.isOver&&this._setDormant(a)},_onScroll:function(){this._calcHitGrid()},onResized:function(){this._calcHitGrid()},_onGridMouseMove:function(a,c){this.pos={x:a,y:c};
this._paint()},_paint:function(){var a=this.pos.x,c=this.pos.y;if(!(this.itemCount<=0)){var d=((this.isHorizontal?a:c)-(this.isHorizontal?this.proximityLeft:this.proximityTop))/(this.isHorizontal?this.itemWidth:this.itemHeight)-0.5,b=0;this.anchorEdge==this.EDGE.BOTTOM&&(b=(c-this.proximityTop)/this.itemHeight,b=b>0.5?1:c/(this.proximityTop+this.itemHeight/2));this.anchorEdge==this.EDGE.TOP&&(b=(c-this.proximityTop)/this.itemHeight,b=b<0.5?1:(this.totalHeight-c)/(this.proximityBottom+this.itemHeight/
2));this.anchorEdge==this.EDGE.RIGHT&&(b=(a-this.proximityLeft)/this.itemWidth,b=b>0.5?1:a/(this.proximityLeft+this.itemWidth/2));this.anchorEdge==this.EDGE.LEFT&&(b=(a-this.proximityLeft)/this.itemWidth,b=b<0.5?1:(this.totalWidth-a)/(this.proximityRight+this.itemWidth/2));this.anchorEdge==this.EDGE.CENTER&&(b=this.isHorizontal?c/this.totalHeight:a/this.totalWidth,b>0.5&&(b=1-b),b*=2);for(a=0;a<this.itemCount;a++)c=this._weighAt(d,a),c<0&&(c=0),this._setItemSize(a,c*b);b=Math.round(d);a=0;d<0?b=0:
d>this.itemCount-1?b=this.itemCount-1:a=(d-b)*((this.isHorizontal?this.itemWidth:this.itemHeight)-this.children[b].sizeMain);this._positionElementsFrom(b,a)}},_weighAt:function(a,c){var d=Math.abs(a-c),b=a-c>0?this.children[c].effectRangeRght:this.children[c].effectRangeLeft;return d>b?0:1-d/b},_setItemSize:function(a,c){if(this.children[a].scale!=c){this.children[a].scale=c;c*=this.timerScale;var d=Math.round(this.itemWidth+(this.itemMaxWidth-this.itemWidth)*c),b=Math.round(this.itemHeight+(this.itemMaxHeight-
this.itemHeight)*c);if(this.isHorizontal){this.children[a].sizeW=d;this.children[a].sizeH=b;this.children[a].sizeMain=d;this.children[a].sizeOff=b;var e=0,e=this.anchorEdge==this.EDGE.TOP?this.children[a].cenY-this.itemHeight/2:this.anchorEdge==this.EDGE.BOTTOM?this.children[a].cenY-(b-this.itemHeight/2):this.children[a].cenY-b/2;this.children[a].usualX=Math.round(this.children[a].cenX-d/2);this.children[a].domNode.style.top=e+"px";this.children[a].domNode.style.left=this.children[a].usualX+"px"}else this.children[a].sizeW=
d,this.children[a].sizeH=b,this.children[a].sizeOff=d,this.children[a].sizeMain=b,e=0,e=this.anchorEdge==this.EDGE.LEFT?this.children[a].cenX-this.itemWidth/2:this.anchorEdge==this.EDGE.RIGHT?this.children[a].cenX-(d-this.itemWidth/2):this.children[a].cenX-d/2,this.children[a].domNode.style.left=e+"px",this.children[a].usualY=Math.round(this.children[a].cenY-b/2),this.children[a].domNode.style.top=this.children[a].usualY+"px";this.children[a].domNode.style.width=d+"px";this.children[a].domNode.style.height=
b+"px";this.children[a].svgNode&&this.children[a].svgNode.setSize(d,b)}},_positionElementsFrom:function(a,c){var d=0,b,e;this.isHorizontal?(b="usualX",e="left"):(b="usualY",e="top");d=Math.round(this.children[a][b]+c);this.children[a].domNode.style[e]!=d+"px"&&(this.children[a].domNode.style[e]=d+"px",this._positionLabel(this.children[a]));var f=d;for(b=a-1;b>=0;b--)f-=this.children[b].sizeMain,this.children[a].domNode.style[e]!=f+"px"&&(this.children[b].domNode.style[e]=f+"px",this._positionLabel(this.children[b]));
for(b=a+1;b<this.itemCount;b++)d+=this.children[b-1].sizeMain,this.children[a].domNode.style[e]!=d+"px"&&(this.children[b].domNode.style[e]=d+"px",this._positionLabel(this.children[b]))},_positionLabel:function(a){var c=0,d=0,b=dojo.marginBox(a.lblNode);this.labelEdge==this.EDGE.TOP&&(c=Math.round(a.sizeW/2-b.w/2),d=-b.h);if(this.labelEdge==this.EDGE.BOTTOM)c=Math.round(a.sizeW/2-b.w/2),d=a.sizeH;this.labelEdge==this.EDGE.LEFT&&(c=-b.w,d=Math.round(a.sizeH/2-b.h/2));if(this.labelEdge==this.EDGE.RIGHT)c=
a.sizeW,d=Math.round(a.sizeH/2-b.h/2);a.lblNode.style.left=c+"px";a.lblNode.style.top=d+"px"},_calcHitGrid:function(){var a=dojo.coords(this.domNode,!0);this.hitX1=a.x-this.proximityLeft;this.hitY1=a.y-this.proximityTop;this.hitX2=this.hitX1+this.totalWidth;this.hitY2=this.hitY1+this.totalHeight},_toEdge:function(a,c){return this.EDGE[a.toUpperCase()]||c},_expandSlowly:function(){this.isOver&&(this.timerScale+=0.2,this._paint(),this.timerScale<1&&setTimeout(dojo.hitch(this,"_expandSlowly"),10))},
destroyRecursive:function(){dojo.disconnect(this._onMouseOutHandle);dojo.disconnect(this._onMouseMoveHandle);dojo.disconnect(this._addChildHandle);this.isFixed&&dojo.disconnect(this._onScrollHandle);dojo.disconnect(this._onResizeHandle);this.inherited("destroyRecursive",arguments)}}),dojo.declare("dojox.widget.FisheyeListItem",[dijit._Widget,dijit._Templated,dijit._Contained],{iconSrc:"",label:"",id:"",templateString:'<div class="dojoxFisheyeListItem">  <img class="dojoxFisheyeListItemImage" dojoAttachPoint="imgNode" dojoAttachEvent="onmouseover:onMouseOver,onmouseout:onMouseOut,onclick:onClick">  <div class="dojoxFisheyeListItemLabel" dojoAttachPoint="lblNode"></div></div>',
_isNode:function(a){if(typeof Element=="function")try{return a instanceof Element}catch(c){}else return a&&!isNaN(a.nodeType);return!1},_hasParent:function(a){return Boolean(a&&a.parentNode&&this._isNode(a.parentNode))},postCreate:function(){var a;if(this.iconSrc.toLowerCase().substring(this.iconSrc.length-4)==".png"&&dojo.isIE<7){if(this._hasParent(this.imgNode)&&this.id!="")a=this.imgNode.parentNode,a.setAttribute("id",this.id);this.imgNode.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
this.iconSrc+"', sizingMethod='scale')";this.imgNode.src=this._blankGif.toString()}else{if(this._hasParent(this.imgNode)&&this.id!="")a=this.imgNode.parentNode,a.setAttribute("id",this.id);this.imgNode.src=this.iconSrc}this.lblNode&&this.lblNode.appendChild(document.createTextNode(this.label));dojo.setSelectable(this.domNode,!1);this.startup()},startup:function(){this.parent=this.getParent()},onMouseOver:function(a){this.parent.isOver||this.parent._setActive(a);this.label!=""&&(dojo.addClass(this.lblNode,
"dojoxFishSelected"),this.parent._positionLabel(this))},onMouseOut:function(){dojo.removeClass(this.lblNode,"dojoxFishSelected")},onClick:function(){}}));