/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.Pager"]||(dojo._hasResource["dojox.widget.Pager"]=!0,dojo.provide("dojox.widget.Pager"),dojo.experimental("dojox.widget.Pager"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dojo.fx"),dojo.declare("dojox.widget.Pager",[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.widget","Pager/Pager.html",'<div dojoAttachPoint="pagerContainer" tabIndex="0" dojoAttachEvent="onkeypress: _handleKey, onfocus: _a11yStyle, onblur:_a11yStyle" class="${orientation}PagerContainer">\n    <div class="pagerContainer">\n\t\t<div dojoAttachPoint="pagerContainerStatus" class="${orientation}PagerStatus"></div>\n\t\t<div dojoAttachPoint="pagerContainerView" class="${orientation}PagerView">\n\t\t    <div dojoAttachPoint="pagerItemContainer"><ul dojoAttachPoint="pagerItems" class="pagerItems"></ul></div>\n\t\t</div>\n\t\t<div dojoAttachPoint="pagerContainerPager" class="${orientation}PagerPager">\n\t\t\t<div tabIndex="0" dojoAttachPoint="pagerNext" class="pagerIconContainer" dojoAttachEvent="onclick: _pagerNext"><img dojoAttachPoint="pagerIconNext" src="${iconNext}" alt="Next" /></div>\n\t\t\t<div tabIndex="0" dojoAttachPoint="pagerPrevious" class="pagerIconContainer" dojoAttachEvent="onclick: _pagerPrevious"><img dojoAttachPoint="pagerIconPrevious" src="${iconPrevious}" alt="Previous" /></div>\n\t\t</div>\n    </div>\n\t<div dojoAttachPoint="containerNode" style="display:none"></div>\n</div>\n'),
iconPage:dojo.moduleUrl("dojox.widget","Pager/images/pageInactive.png"),iconPageActive:dojo.moduleUrl("dojox.widget","Pager/images/pageActive.png"),store:null,orientation:"horizontal",statusPos:"leading",pagerPos:"center",duration:500,itemSpace:2,resizeChildren:!0,itemClass:"dojox.widget._PagerItem",itemsPage:3,postMixInProperties:function(){var b=this.orientation=="horizontal";dojo.mixin(this,{_totalPages:0,_currentPage:1,dirClass:"pager"+(b?"Horizontal":"Vertical"),iconNext:dojo.moduleUrl("dojox.widget",
"Pager/images/"+(b?"h":"v")+"Next.png"),iconPrevious:dojo.moduleUrl("dojox.widget","Pager/images/"+(b?"h":"v")+"Previous.png")})},postCreate:function(){this.inherited(arguments);this.store.fetch({onComplete:dojo.hitch(this,"_init")})},_a11yStyle:function(b){dojo[b.type=="focus"?"addClass":"removeClass"](b.target,"pagerFocus")},_handleKey:function(b){var c=dojo.keys;switch(b.charCode==c.SPACE?c.SPACE:b.keyCode){case c.UP_ARROW:case c.RIGHT_ARROW:case 110:case 78:b.preventDefault();this._pagerNext();
break;case c.DOWN_ARROW:case c.LEFT_ARROW:case 112:case 80:b.preventDefault();this._pagerPrevious();break;case c.ENTER:switch(b.target){case this.pagerNext:this._pagerNext();break;case this.pagerPrevious:this._pagerPrevious()}}},_init:function(b){this.items=b;this._renderPages();this._renderStatus();this._renderPager()},_renderPages:function(){var b=this.pagerContainerView,c=this.orientation=="horizontal",a=dojo.style;if(c){var d=dojo.marginBox(this.pagerContainerPager).h,f=dojo.marginBox(this.pagerContainerStatus).h;
if(this.pagerPos!="center")var e=d+f;else{var e=f,g=this.pagerIconNext.width,g=a(b,"width")-2*g;a(b,{width:g+"px",marginLeft:this.pagerIconNext.width+"px",marginRight:this.pagerIconNext.width+"px"})}e=a(this.pagerContainer,"height")-e;a(this.pagerContainerView,"height",e+"px");var h=Math.floor(a(b,"width")/this.itemsPage);this.statusPos=="trailing"?(this.pagerPos!="center"&&a(b,"marginTop",d+"px"),a(b,"marginBottom",f+"px")):(a(b,"marginTop",f+"px"),this.pagerPos!="center"&&a(b,"marginTop",d+"px"))}else d=
dojo.marginBox(this.pagerContainerPager).w,f=dojo.marginBox(this.pagerContainerStatus).w,a(this.pagerContainer,"width"),this.pagerPos!="center"?e=d+f:(e=f,g=this.pagerIconNext.height,g=a(b,"height")-2*g,a(b,{height:g+"px",marginTop:this.pagerIconNext.height+"px",marginBottom:this.pagerIconNext.height+"px"})),e=a(this.pagerContainer,"width")-e,a(b,"width",e+"px"),h=Math.floor(a(b,"height")/this.itemsPage),this.statusPos=="trailing"?(this.pagerPos!="center"&&a(b,"marginLeft",d+"px"),a(b,"marginRight",
f+"px")):(a(b,"marginLeft",f+"px"),this.pagerPos!="center"&&a(b,"marginRight",d+"px"));var i=dojo.getObject(this.itemClass),k="padding"+(c?"Left":"Top"),l="padding"+(c?"Right":"Bottom");dojo.forEach(this.items,function(d,f){var e=dojo.create("div",{innerHTML:d.content}),e=new i({id:this.id+"-item-"+(f+1)},e);this.pagerItems.appendChild(e.domNode);var g={};g[c?"width":"height"]=h-this.itemSpace+"px";var j=c?"height":"width";g[j]=a(b,j)+"px";a(e.containerNode,g);this.resizeChildren&&e.resizeChildren();
e.parseChildren();a(e.domNode,"position","absolute");f<this.itemsPage?(g=f*h,j=c?"left":"top",a(e.domNode,c?"top":"left","0px"),a(e.domNode,j,g+"px")):(a(e.domNode,"top","-1000px"),a(e.domNode,"left","-1000px"));a(e.domNode,l,this.itemSpace/2+"px");a(e.domNode,k,this.itemSpace/2+"px")},this)},_renderPager:function(){var b=this.pagerContainerPager;this.orientation=="horizontal"?(this.statusPos!="center"&&(this.statusPos=="trailing"?dojo.style(b,"top","0px"):dojo.style(b,"bottom","0px")),dojo.style(this.pagerNext,
"right","0px"),dojo.style(this.pagerPrevious,"left","0px")):(this.statusPos=="trailing"?dojo.style(b,"left","0px"):dojo.style(b,"right","0px"),dojo.style(this.pagerNext,"bottom","0px"),dojo.style(this.pagerPrevious,"top","0px"))},_renderStatus:function(){this._totalPages=Math.ceil(this.items.length/this.itemsPage);this.iconsLoaded=this.iconHeight=this.iconWidth=0;this._iconConnects=[];for(var b=1;b<=this._totalPages;b++){var c=new Image,a=b;dojo.connect(c,"onclick",dojo.hitch(this,function(b){this._pagerSkip(b)},
a));this._iconConnects[a]=dojo.connect(c,"onload",dojo.hitch(this,function(b){this.iconWidth+=c.width;this.iconHeight+=c.height;this.iconsLoaded++;if(this._totalPages==this.iconsLoaded)if(this.orientation=="horizontal"){if(this.statusPos=="trailing"){if(this.pagerPos=="center"){var a=dojo.style(this.pagerContainer,"height"),e=dojo.style(this.pagerContainerStatus,"height");dojo.style(this.pagerContainerPager,"top",a/2-e/2+"px")}dojo.style(this.pagerContainerStatus,"bottom","0px")}else this.pagerPos==
"center"&&(a=dojo.style(this.pagerContainer,"height"),e=dojo.style(this.pagerContainerStatus,"height"),dojo.style(this.pagerContainerPager,"bottom",a/2-e/2+"px")),dojo.style(this.pagerContainerStatus,"top","0px");a=dojo.style(this.pagerContainer,"width")/2-this.iconWidth/2;dojo.style(this.pagerContainerStatus,"paddingLeft",a+"px")}else this.statusPos=="trailing"?(this.pagerPos=="center"&&(a=dojo.style(this.pagerContainer,"width"),e=dojo.style(this.pagerContainerStatus,"width"),dojo.style(this.pagerContainerPager,
"left",a/2-e/2+"px")),dojo.style(this.pagerContainerStatus,"right","0px")):(this.pagerPos=="center"&&(a=dojo.style(this.pagerContainer,"width"),e=dojo.style(this.pagerContainerStatus,"width"),dojo.style(this.pagerContainerPager,"right",a/2-e/2+"px")),dojo.style(this.pagerContainerStatus,"left","0px")),a=dojo.style(this.pagerContainer,"height")/2-this.iconHeight/2,dojo.style(this.pagerContainerStatus,"paddingTop",a+"px");dojo.disconnect(this._iconConnects[b])},a));c.src=b==this._currentPage?this.iconPageActive:
this.iconPage;a=b;dojo.addClass(c,this.orientation+"PagerIcon");dojo.attr(c,"id",this.id+"-status-"+b);this.pagerContainerStatus.appendChild(c);this.orientation=="vertical"&&dojo.style(c,"display","block")}},_pagerSkip:function(b){if(this._currentPage!=b){var c;b<this._currentPage?(c=this._currentPage-b,b=this._totalPages+b-this._currentPage):(c=this._totalPages+this._currentPage-b,b-=this._currentPage);var a=b>c;this._toScroll=a?c:b;var d=a?"_pagerPrevious":"_pagerNext",f=this.connect(this,"onScrollEnd",
function(){this._toScroll--;if(this._toScroll<1)this.disconnect(f);else this[d]()});this[d]()}},_pagerNext:function(){if(!this._anim){for(var b=[],c=this._currentPage*this.itemsPage;c>(this._currentPage-1)*this.itemsPage;c--)if(dojo.byId(this.id+"-item-"+c)){var a=dojo.byId(this.id+"-item-"+c),d=dojo.marginBox(a);this.orientation=="horizontal"?(d=d.l-this.itemsPage*d.w,b.push(dojo.fx.slideTo({node:a,left:d,duration:this.duration}))):(d=d.t-this.itemsPage*d.h,b.push(dojo.fx.slideTo({node:a,top:d,duration:this.duration})))}var f=
this._currentPage;this._currentPage==this._totalPages?this._currentPage=1:this._currentPage++;for(var e=this.itemsPage,c=this._currentPage*this.itemsPage;c>(this._currentPage-1)*this.itemsPage;c--){if(dojo.byId(this.id+"-item-"+c))if(a=dojo.byId(this.id+"-item-"+c),d=dojo.marginBox(a),this.orientation=="horizontal"){var g=dojo.style(this.pagerContainerView,"width")+(e-1)*d.w-1;dojo.style(a,"left",g+"px");dojo.style(a,"top","0px");d=g-this.itemsPage*d.w;b.push(dojo.fx.slideTo({node:a,left:d,duration:this.duration}))}else g=
dojo.style(this.pagerContainerView,"height")+(e-1)*d.h-1,dojo.style(a,"top",g+"px"),dojo.style(a,"left","0px"),d=g-this.itemsPage*d.h,b.push(dojo.fx.slideTo({node:a,top:d,duration:this.duration}));e--}this._anim=dojo.fx.combine(b);var h=this.connect(this._anim,"onEnd",function(){delete this._anim;this.onScrollEnd();this.disconnect(h)});this._anim.play();dojo.byId(this.id+"-status-"+f).src=this.iconPage;dojo.byId(this.id+"-status-"+this._currentPage).src=this.iconPageActive}},_pagerPrevious:function(){if(!this._anim){for(var b=
[],c=this._currentPage*this.itemsPage;c>(this._currentPage-1)*this.itemsPage;c--)if(dojo.byId(this.id+"-item-"+c)){var a=dojo.byId(this.id+"-item-"+c),d=dojo.marginBox(a);if(this.orientation=="horizontal"){var f=dojo.style(a,"left")+this.itemsPage*d.w;b.push(dojo.fx.slideTo({node:a,left:f,duration:this.duration}))}else f=dojo.style(a,"top")+this.itemsPage*d.h,b.push(dojo.fx.slideTo({node:a,top:f,duration:this.duration}))}var e=this._currentPage;this._currentPage==1?this._currentPage=this._totalPages:
this._currentPage--;for(var g=this.itemsPage,h=1,c=this._currentPage*this.itemsPage;c>(this._currentPage-1)*this.itemsPage;c--){if(dojo.byId(this.id+"-item-"+c))if(a=dojo.byId(this.id+"-item-"+c),d=dojo.marginBox(a),this.orientation=="horizontal"){var i=-(h*d.w)+1;dojo.style(a,"left",i+"px");dojo.style(a,"top","0px");f=(g-1)*d.w;b.push(dojo.fx.slideTo({node:a,left:f,duration:this.duration}));f=i+this.itemsPage*d.w;b.push(dojo.fx.slideTo({node:a,left:f,duration:this.duration}))}else i=-(h*d.h+1),dojo.style(a,
"top",i+"px"),dojo.style(a,"left","0px"),f=(g-1)*d.h,b.push(dojo.fx.slideTo({node:a,top:f,duration:this.duration}));g--;h++}this._anim=dojo.fx.combine(b);var k=dojo.connect(this._anim,"onEnd",dojo.hitch(this,function(){delete this._anim;this.onScrollEnd();dojo.disconnect(k)}));this._anim.play();dojo.byId(this.id+"-status-"+e).src=this.iconPage;dojo.byId(this.id+"-status-"+this._currentPage).src=this.iconPageActive}},onScrollEnd:function(){}}),dojo.declare("dojox.widget._PagerItem",[dijit._Widget,
dijit._Templated],{templateString:'<li class="pagerItem" dojoAttachPoint="containerNode"></li>',resizeChildren:function(){var b=dojo.marginBox(this.containerNode);dojo.style(this.containerNode.firstChild,{width:b.w+"px",height:b.h+"px"})},parseChildren:function(){dojo.parser.parse(this.containerNode)}}));