/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.widget.Rotator"]||(dojo._hasResource["dojox.widget.Rotator"]=!0,dojo.provide("dojox.widget.Rotator"),dojo.require("dojo.parser"),function(b){b.declare("dojox.widget.Rotator",null,{transition:"dojox.widget.rotator.swap",transitionParams:"duration:500",panes:null,constructor:function(d,a){b.mixin(this,d);var c=this,e=c.transition,h=c._transitions={},k=c._idMap={},g=c.transitionParams=eval("({ "+c.transitionParams+" })"),a=c._domNode=dojo.byId(a);c._domNodeContentBox=b.contentBox(a);
var f={left:0,top:0},i=function(b,a){console.warn(c.declaredClass,' - Unable to find transition "',b,'", defaulting to "',a,'".')};c.id=a.id||(new Date).getTime();b.style(a,"position")=="static"&&b.style(a,"position","relative");h[e]=b.getObject(e);if(!h[e])i(e,"dojox.widget.rotator.swap"),h[c.transition="dojox.widget.rotator.swap"]=b.getObject("dojox.widget.rotator.swap");if(!g.duration)g.duration=500;b.forEach(c.panes,function(c){b.create("div",c,a)});var j=c.panes=[];b.query(">",a).forEach(function(a,
d){var e={node:a,idx:d,params:b.mixin({},g,eval("({ "+(b.attr(a,"transitionParams")||"")+" })"))},l=e.trans=b.attr(a,"transition")||c.transition;b.forEach(["id","title","duration","waitForEvent"],function(c){e[c]=b.attr(a,c)});e.id&&(k[e.id]=d);if(!h[l]&&!(h[l]=b.getObject(l)))i(l,e.trans=c.transition);f.position="absolute";f.display="none";if(c.idx==null||b.attr(a,"selected"))c.idx!=null&&b.style(j[c.idx].node,"display","none"),c.idx=d,f.display="";b.style(a,f);b.query("> script[type^='dojo/method']",
a).orphan().forEach(function(a){var c=b.attr(a,"event");c&&(e[c]=b.parser._functionFromScript(a))});j.push(e)});c._controlSub=b.subscribe(c.id+"/rotator/control",c,"control")},destroy:function(){b.forEach([this._controlSub,this.wfe],b.unsubscribe);b.destroy(this._domNode)},next:function(){return this.go(this.idx+1)},prev:function(){return this.go(this.idx-1)},go:function(d){var a=this,c=a.idx,e=a.panes,h=e.length,k=a._idMap[d];a._resetWaitForEvent();d=k!=null?k:d||0;d=d<h?d<0?h-1:d:0;if(d==c||a.anim)return null;
var g=e[c],f=e[d];b.style(g.node,"zIndex",2);b.style(f.node,"zIndex",1);var i={current:g,next:f,rotator:a};if(c=a.anim=a._transitions[f.trans](b.mixin({rotatorBox:a._domNodeContentBox},i,f.params))){var j=new b.Deferred,m=f.waitForEvent,n=b.connect(c,"onEnd",function(){b.style(g.node,{display:"none",left:0,opacity:1,top:0,zIndex:0});b.disconnect(n);a.anim=null;a.idx=d;if(g.onAfterOut)g.onAfterOut(i);if(f.onAfterIn)f.onAfterIn(i);a.onUpdate("onAfterTransition");m||(a._resetWaitForEvent(),j.callback())});
a.wfe=m?b.subscribe(m,function(){a._resetWaitForEvent();j.callback(!0)}):null;a.onUpdate("onBeforeTransition");if(g.onBeforeOut)g.onBeforeOut(i);if(f.onBeforeIn)f.onBeforeIn(i);c.play();return j}},onUpdate:function(d,a){b.publish(this.id+"/rotator/update",[d,this,a||{}])},_resetWaitForEvent:function(){if(this.wfe)b.unsubscribe(this.wfe),this.wfe=null},control:function(d){var a=b._toArray(arguments),c=this;a.shift();c._resetWaitForEvent();c[d]?((a=c[d].apply(c,a))&&a.addCallback(function(){c.onUpdate(d)}),
c.onManualChange(d)):console.warn(c.declaredClass,' - Unsupported action "',d,'".')},resize:function(d,a){var c=this._domNodeContentBox={w:d,h:a};b.contentBox(this._domNode,c);b.forEach(this.panes,function(a){b.contentBox(a.node,c)})},onManualChange:function(){}});b.setObject("dojox.widget.rotator.swap",function(d){return new b._Animation({play:function(){b.style(d.current.node,"display","none");b.style(d.next.node,"display","");this._fire("onEnd")}})})}(dojo));