/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojo.dnd.Manager"])dojo._hasResource["dojo.dnd.Manager"]=!0,dojo.provide("dojo.dnd.Manager"),dojo.require("dojo.dnd.common"),dojo.require("dojo.dnd.autoscroll"),dojo.require("dojo.dnd.Avatar"),dojo.declare("dojo.dnd.Manager",null,{constructor:function(){this.source=this.avatar=null;this.nodes=[];this.copy=!0;this.target=null;this.canDropFlag=!1;this.events=[]},OFFSET_X:16,OFFSET_Y:16,overSource:function(a){if(this.avatar)this.target=a&&a.targetState!="Disabled"?a:null,this.canDropFlag=
Boolean(this.target),this.avatar.update();dojo.publish("/dnd/source/over",[a])},outSource:function(a){if(this.avatar){if(this.target==a)this.target=null,this.canDropFlag=!1,this.avatar.update(),dojo.publish("/dnd/source/over",[null])}else dojo.publish("/dnd/source/over",[null])},startDrag:function(a,b,c){this.source=a;this.nodes=b;this.copy=Boolean(c);this.avatar=this.makeAvatar();dojo.body().appendChild(this.avatar.node);dojo.publish("/dnd/start",[a,b,this.copy]);this.events=[dojo.connect(dojo.doc,
"onmousemove",this,"onMouseMove"),dojo.connect(dojo.doc,"onmouseup",this,"onMouseUp"),dojo.connect(dojo.doc,"onkeydown",this,"onKeyDown"),dojo.connect(dojo.doc,"onkeyup",this,"onKeyUp"),dojo.connect(dojo.doc,"ondragstart",dojo.stopEvent),dojo.connect(dojo.body(),"onselectstart",dojo.stopEvent)];dojo.addClass(dojo.body(),"dojoDnd"+(c?"Copy":"Move"))},canDrop:function(a){a=Boolean(this.target&&a);if(this.canDropFlag!=a)this.canDropFlag=a,this.avatar.update()},stopDrag:function(){dojo.removeClass(dojo.body(),
["dojoDndCopy","dojoDndMove"]);dojo.forEach(this.events,dojo.disconnect);this.events=[];this.avatar.destroy();this.source=this.target=this.avatar=null;this.nodes=[]},makeAvatar:function(){return new dojo.dnd.Avatar(this)},updateAvatar:function(){this.avatar.update()},onMouseMove:function(a){var b=this.avatar;if(b)dojo.dnd.autoScrollNodes(a),b=b.node.style,b.left=a.pageX+this.OFFSET_X+"px",b.top=a.pageY+this.OFFSET_Y+"px",a=Boolean(this.source.copyState(dojo.isCopyKey(a))),this.copy!=a&&this._setCopyStatus(a)},
onMouseUp:function(a){this.avatar&&(this.target&&this.canDropFlag?(a=[this.source,this.nodes,Boolean(this.source.copyState(dojo.isCopyKey(a))),this.target,a],dojo.publish("/dnd/drop/before",a),dojo.publish("/dnd/drop",a)):dojo.publish("/dnd/cancel"),this.stopDrag())},onKeyDown:function(a){if(this.avatar)switch(a.keyCode){case dojo.keys.CTRL:a=Boolean(this.source.copyState(!0));this.copy!=a&&this._setCopyStatus(a);break;case dojo.keys.ESCAPE:dojo.publish("/dnd/cancel"),this.stopDrag()}},onKeyUp:function(a){this.avatar&&
a.keyCode==dojo.keys.CTRL&&(a=Boolean(this.source.copyState(!1)),this.copy!=a&&this._setCopyStatus(a))},_setCopyStatus:function(a){this.copy=a;this.source._markDndStatus(this.copy);this.updateAvatar();dojo.replaceClass(dojo.body(),"dojoDnd"+(this.copy?"Copy":"Move"),"dojoDnd"+(this.copy?"Move":"Copy"))}}),dojo.dnd._manager=null,dojo.dnd.manager=function(){if(!dojo.dnd._manager)dojo.dnd._manager=new dojo.dnd.Manager;return dojo.dnd._manager};