/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo.dnd.Source"]||(dojo._hasResource["dojo.dnd.Source"]=!0,dojo.provide("dojo.dnd.Source"),dojo.require("dojo.dnd.Selector"),dojo.require("dojo.dnd.Manager"),dojo.declare("dojo.dnd.Source",dojo.dnd.Selector,{isSource:!0,horizontal:!1,copyOnly:!1,selfCopy:!1,selfAccept:!0,skipForm:!1,withHandles:!1,autoSync:!1,delay:0,accept:["text"],generateText:!0,constructor:function(a,b){dojo.mixin(this,dojo.mixin({},b));var c=this.accept;if(c.length){this.accept={};for(var d=0;d<c.length;++d)this.accept[c[d]]=
1}this.mouseDown=this.isDragging=!1;this.targetBox=this.targetAnchor=null;this.before=!0;this._lastY=this._lastX=0;this.sourceState="";this.isSource&&dojo.addClass(this.node,"dojoDndSource");this.targetState="";this.accept&&dojo.addClass(this.node,"dojoDndTarget");this.horizontal&&dojo.addClass(this.node,"dojoDndHorizontal");this.topics=[dojo.subscribe("/dnd/source/over",this,"onDndSourceOver"),dojo.subscribe("/dnd/start",this,"onDndStart"),dojo.subscribe("/dnd/drop",this,"onDndDrop"),dojo.subscribe("/dnd/cancel",
this,"onDndCancel")]},checkAcceptance:function(a,b){if(this==a)return!this.copyOnly||this.selfAccept;for(var c=0;c<b.length;++c){for(var d=a.getItem(b[c].id).type,f=!1,e=0;e<d.length;++e)if(d[e]in this.accept){f=!0;break}if(!f)return!1}return!0},copyState:function(a,b){if(a)return!0;arguments.length<2&&(b=this==dojo.dnd.manager().target);if(b){if(this.copyOnly)return this.selfCopy}else return this.copyOnly;return!1},destroy:function(){dojo.dnd.Source.superclass.destroy.call(this);dojo.forEach(this.topics,
dojo.unsubscribe);this.targetAnchor=null},markupFactory:function(a,b){a._skipStartup=!0;return new dojo.dnd.Source(b,a)},onMouseMove:function(a){if(!(this.isDragging&&this.targetState=="Disabled")){dojo.dnd.Source.superclass.onMouseMove.call(this,a);var b=dojo.dnd.manager();if(!this.isDragging&&this.mouseDown&&this.isSource&&(Math.abs(a.pageX-this._lastX)>this.delay||Math.abs(a.pageY-this._lastY)>this.delay)){var c=this.getSelectedNodes();c.length&&b.startDrag(this,c,this.copyState(dojo.isCopyKey(a),
!0))}if(this.isDragging){c=!1;if(this.current){if(!this.targetBox||this.targetAnchor!=this.current)this.targetBox=dojo.position(this.current,!0);c=this.horizontal?a.pageX-this.targetBox.x<this.targetBox.w/2:a.pageY-this.targetBox.y<this.targetBox.h/2}if(this.current!=this.targetAnchor||c!=this.before)this._markTargetAnchor(c),b.canDrop(!this.current||b.source!=this||!(this.current.id in this.selection))}}},onMouseDown:function(a){if(!this.mouseDown&&this._legalMouseDown(a)&&(!this.skipForm||!dojo.dnd.isFormElement(a)))this.mouseDown=
!0,this._lastX=a.pageX,this._lastY=a.pageY,dojo.dnd.Source.superclass.onMouseDown.call(this,a)},onMouseUp:function(a){if(this.mouseDown)this.mouseDown=!1,dojo.dnd.Source.superclass.onMouseUp.call(this,a)},onDndSourceOver:function(a){this!=a?(this.mouseDown=!1,this.targetAnchor&&this._unmarkTargetAnchor()):this.isDragging&&(a=dojo.dnd.manager(),a.canDrop(this.targetState!="Disabled"&&(!this.current||a.source!=this||!(this.current.id in this.selection))))},onDndStart:function(a,b,c){this.autoSync&&
this.sync();this.isSource&&this._changeState("Source",this==a?c?"Copied":"Moved":"");this._changeState("Target",this.accept&&this.checkAcceptance(a,b)?"":"Disabled");this==a&&dojo.dnd.manager().overSource(this);this.isDragging=!0},onDndDrop:function(a,b,c,d){if(this==d)this.onDrop(a,b,c);this.onDndCancel()},onDndCancel:function(){if(this.targetAnchor)this._unmarkTargetAnchor(),this.targetAnchor=null;this.before=!0;this.mouseDown=this.isDragging=!1;this._changeState("Source","");this._changeState("Target",
"")},onDrop:function(a,b,c){if(this!=a)this.onDropExternal(a,b,c);else this.onDropInternal(b,c)},onDropExternal:function(a,b,c){var d=this._normalizedCreator;this._normalizedCreator=this.creator?function(b,c){return d.call(this,a.getItem(b.id).data,c)}:c?function(b){var c=a.getItem(b.id),b=b.cloneNode(!0);b.id=dojo.dnd.getUniqueId();return{node:b,data:c.data,type:c.type}}:function(b){var c=a.getItem(b.id);a.delItem(b.id);return{node:b,data:c.data,type:c.type}};this.selectNone();!c&&!this.creator&&
a.selectNone();this.insertNodes(!0,b,this.before,this.current);!c&&this.creator&&a.deleteSelectedNodes();this._normalizedCreator=d},onDropInternal:function(a,b){var c=this._normalizedCreator;if(!(this.current&&this.current.id in this.selection)){if(b)this._normalizedCreator=this.creator?function(a,b){return c.call(this,this.getItem(a.id).data,b)}:function(a){var b=this.getItem(a.id),a=a.cloneNode(!0);a.id=dojo.dnd.getUniqueId();return{node:a,data:b.data,type:b.type}};else{if(!this.current)return;
this._normalizedCreator=function(a){var b=this.getItem(a.id);return{node:a,data:b.data,type:b.type}}}this._removeSelection();this.insertNodes(!0,a,this.before,this.current);this._normalizedCreator=c}},onDraggingOver:function(){},onDraggingOut:function(){},onOverEvent:function(){dojo.dnd.Source.superclass.onOverEvent.call(this);dojo.dnd.manager().overSource(this);if(this.isDragging&&this.targetState!="Disabled")this.onDraggingOver()},onOutEvent:function(){dojo.dnd.Source.superclass.onOutEvent.call(this);
dojo.dnd.manager().outSource(this);if(this.isDragging&&this.targetState!="Disabled")this.onDraggingOut()},_markTargetAnchor:function(a){if(!(this.current==this.targetAnchor&&this.before==a))this.targetAnchor&&this._removeItemClass(this.targetAnchor,this.before?"Before":"After"),this.targetAnchor=this.current,this.targetBox=null,this.before=a,this.targetAnchor&&this._addItemClass(this.targetAnchor,this.before?"Before":"After")},_unmarkTargetAnchor:function(){if(this.targetAnchor)this._removeItemClass(this.targetAnchor,
this.before?"Before":"After"),this.targetBox=this.targetAnchor=null,this.before=!0},_markDndStatus:function(a){this._changeState("Source",a?"Copied":"Moved")},_legalMouseDown:function(a){if(!dojo.mouseButtons.isLeft(a))return!1;if(!this.withHandles)return!0;for(a=a.target;a&&a!==this.node;a=a.parentNode){if(dojo.hasClass(a,"dojoDndHandle"))return!0;if(dojo.hasClass(a,"dojoDndItem")||dojo.hasClass(a,"dojoDndIgnore"))break}return!1}}),dojo.declare("dojo.dnd.Target",dojo.dnd.Source,{constructor:function(){this.isSource=
!1;dojo.removeClass(this.node,"dojoDndSource")},markupFactory:function(a,b){a._skipStartup=!0;return new dojo.dnd.Target(b,a)}}),dojo.declare("dojo.dnd.AutoSource",dojo.dnd.Source,{constructor:function(){this.autoSync=!0},markupFactory:function(a,b){a._skipStartup=!0;return new dojo.dnd.AutoSource(b,a)}}));