/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.collections.BinaryTree"])dojo._hasResource["dojox.collections.BinaryTree"]=!0,dojo.provide("dojox.collections.BinaryTree"),dojo.require("dojox.collections._base"),dojox.collections.BinaryTree=function(k){function l(a,b,c){this.value=a||null;this.right=b||null;this.left=c||null;this.clone=function(){var a=new l;a.value=this.value.value?this.value.clone():this.value;if(this.left!=null)a.left=this.left.clone();if(this.right!=null)a.right=this.right.clone();return a};this.compare=
function(a){return this.value>a.value?1:this.value<a.value?-1:0};this.compareData=function(a){return this.value>a?1:this.value<a?-1:0}}function f(a,b){a&&(f(a.left,b),b.push(a.value),f(a.right,b))}function g(a,b){var c="";a&&(c=a.value.toString()+b,c+=g(a.left,b),c+=g(a.right,b));return c}function h(a,b){var c="";a&&(c=h(a.left,b),c+=a.value.toString()+b,c+=h(a.right,b));return c}function i(a,b){var c="";a&&(c=i(a.left,b),c+=i(a.right,b),c+=a.value.toString()+b);return c}function j(a,b){if(!a)return null;
var c=a.compareData(b);return c==0?a:c>0?j(a.left,b):j(a.right,b)}this.add=function(a){for(var a=new l(a),b,c=e,d=null;c;){b=c.compare(a);if(b==0)return;d=c;c=b>0?c.left:c.right}this.count++;d?(b=d.compare(a),b>0?d.left=a:d.right=a):e=a};this.clear=function(){e=null;this.count=0};this.clone=function(){for(var a=new dojox.collections.BinaryTree,b=this.getIterator();!b.atEnd();)a.add(b.get());return a};this.contains=function(a){return this.search(a)!=null};this.deleteData=function(a){for(var b=e,c=
null,d=b.compareData(a);d!=0&&b!=null;){if(d>0)c=b,b=b.left;else if(d<0)c=b,b=b.right;d=b.compareData(a)}if(b)if(this.count--,b.right)if(b.right.left){a=b.right.left;for(d=b.right;a.left!=null;)d=a,a=a.left;d.left=a.right;a.left=b.left;a.right=b.right;if(c)if(d=c.compare(b),d>0)c.left=a;else{if(d<0)c.right=a}else e=a}else if(c)if(d=c.compare(b),d>0)c.left=b.right;else{if(d<0)c.right=b.right}else e=b.right;else if(c)if(d=c.compare(b),d>0)c.left=b.left;else{if(d<0)c.right=b.left}else e=b.left};this.getIterator=
function(){var a=[];f(e,a);return new dojox.collections.Iterator(a)};this.search=function(a){return j(e,a)};this.toString=function(a,b){if(!a)a=dojox.collections.BinaryTree.TraversalMethods.Inorder;b||(b=",");var c="";switch(a){case dojox.collections.BinaryTree.TraversalMethods.Preorder:c=g(e,b);break;case dojox.collections.BinaryTree.TraversalMethods.Inorder:c=h(e,b);break;case dojox.collections.BinaryTree.TraversalMethods.Postorder:c=i(e,b)}return c.length==0?"":c.substring(0,c.length-b.length)};
this.count=0;var e=this.root=null;k&&this.add(k)},dojox.collections.BinaryTree.TraversalMethods={Preorder:1,Inorder:2,Postorder:3};