/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.date.hebrew"])dojo._hasResource["dojox.date.hebrew"]=!0,dojo.provide("dojox.date.hebrew"),dojo.require("dojox.date.hebrew.Date"),dojo.require("dojo.date"),dojox.date.hebrew.getDaysInMonth=function(b){return b.getDaysInHebrewMonth(b.getMonth(),b.getFullYear())},dojox.date.hebrew.compare=function(b,d,c){b instanceof dojox.date.hebrew.Date&&(b=b.toGregorian());d instanceof dojox.date.hebrew.Date&&(d=d.toGregorian());return dojo.date.compare.apply(null,arguments)},dojox.date.hebrew.add=
function(b,d,c){var e=new dojox.date.hebrew.Date(b);switch(d){case "day":e.setDate(b.getDate()+c);break;case "weekday":var a=b.getDay(),f=0;c<0&&a==6&&(a=5,f=-1);if(a+c<5&&a+c>=0)e.setDate(b.getDate()+c+f);else{var d=c>0?5:-1,g=c>0?2:-2;if(c>0&&(a==5||a==6))f=4-a,a=4;var c=a+c-d,h=parseInt(c/5);e.setDate(b.getDate()-a+g+h*7+f+c%5+d)}break;case "year":e.setFullYear(b.getFullYear()+c);break;case "week":c*=7;e.setDate(b.getDate()+c);break;case "month":a=b.getMonth();d=a+c;b.isLeapYear(b.getFullYear())||
(a<5&&d>=5?d++:a>5&&d<=5&&d--);e.setMonth(d);break;case "hour":e.setHours(b.getHours()+c);break;case "minute":e.setMinutes(b.getMinutes()+c);break;case "second":e.setSeconds(b.getSeconds()+c);break;case "millisecond":e.setMilliseconds(b.getMilliseconds()+c)}return e},dojox.date.hebrew.difference=function(b,d,c){var d=d||new dojox.date.hebrew.Date,c=c||"day",e=b.getFullYear()-d.getFullYear(),a=1;switch(c){case "weekday":a=Math.round(dojox.date.hebrew.difference(b,d,"day"));c=parseInt(dojox.date.hebrew.difference(b,
d,"week"));if(a%7==0)a=c*5;else{var e=0,f=d.getDay(),g=b.getDay(),c=parseInt(a/7),b=a%7,d=new dojox.date.hebrew.Date(d);d.setDate(d.getDate()+c*7);d=d.getDay();if(a>0)switch(!0){case f==5:e=-1;break;case f==6:e=0;break;case g==5:e=-1;break;case g==6:e=-2;break;case d+b>5:e=-2}else if(a<0)switch(!0){case f==5:e=0;break;case f==6:e=1;break;case g==5:e=2;break;case g==6:e=1;break;case d+b<0:e=2}a+=e;a-=c*2}break;case "year":a=e;break;case "month":f=b.toGregorian()>d.toGregorian()?b:d;c=b.toGregorian()>
d.toGregorian()?d:b;g=f.getMonth();a=c.getMonth();if(e==0)a=!b.isLeapYear(b.getFullYear())&&f.getMonth()>5&&c.getMonth()<=5?f.getMonth()-c.getMonth()-1:f.getMonth()-c.getMonth();else{a=!c.isLeapYear(c.getFullYear())&&a<6?13-a-1:13-a;a+=!f.isLeapYear(f.getFullYear())&&g>5?g-1:g;e=c.getFullYear()+1;for(f=f.getFullYear();e<f;e++)a+=c.isLeapYear(e)?13:12}b.toGregorian()<d.toGregorian()&&(a=-a);break;case "week":a=parseInt(dojox.date.hebrew.difference(b,d,"day")/7);break;case "day":a/=24;case "hour":a/=
60;case "minute":a/=60;case "second":a/=1E3;case "millisecond":a*=b.toGregorian().getTime()-d.toGregorian().getTime()}return Math.round(a)};