/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.wire.ml.Service"]||(dojo._hasResource["dojox.wire.ml.Service"]=!0,dojo.provide("dojox.wire.ml.Service"),dojo.provide("dojox.wire.ml.RestHandler"),dojo.provide("dojox.wire.ml.XmlHandler"),dojo.provide("dojox.wire.ml.JsonHandler"),dojo.require("dijit._Widget"),dojo.require("dojox.xml.parser"),dojo.require("dojox.wire._base"),dojo.require("dojox.wire.ml.util"),dojo.declare("dojox.wire.ml.Service",dijit._Widget,{url:"",serviceUrl:"",serviceType:"",handlerClass:"",preventCache:!0,
postCreate:function(){this.handler=this._createHandler()},_handlerClasses:{TEXT:"dojox.wire.ml.RestHandler",XML:"dojox.wire.ml.XmlHandler",JSON:"dojox.wire.ml.JsonHandler","JSON-RPC":"dojo.rpc.JsonService"},_createHandler:function(){if(this.url){var b=this;dojo.xhrGet({url:this.url,handleAs:"json",sync:!0}).addCallback(function(a){b.smd=a});if(this.smd&&!this.serviceUrl)this.serviceUrl=this.smd.serviceUrl||this.smd.serviceURL}var a=void 0;if(this.handlerClass)a=dojox.wire._getClass(this.handlerClass);
else if(this.serviceType){if((a=this._handlerClasses[this.serviceType])&&dojo.isString(a))a=dojox.wire._getClass(a),this._handlerClasses[this.serviceType]=a}else if(this.smd&&this.smd.serviceType&&(a=this._handlerClasses[this.smd.serviceType])&&dojo.isString(a))a=dojox.wire._getClass(a),this._handlerClasses[this.smd.serviceType]=a;return!a?null:new a},callMethod:function(b,a){var c=new dojo.Deferred;this.handler.bind(b,a,c,this.serviceUrl);return c}}),dojo.declare("dojox.wire.ml.RestHandler",null,
{contentType:"text/plain",handleAs:"text",bind:function(b,a,c,d){var b=b.toUpperCase(),f=this,d={url:this._getUrl(b,a,d),contentType:this.contentType,handleAs:this.handleAs,headers:this.headers,preventCache:this.preventCache},e=null;b=="POST"?(d.postData=this._getContent(b,a),e=dojo.rawXhrPost(d)):b=="PUT"?(d.putData=this._getContent(b,a),e=dojo.rawXhrPut(d)):e=b=="DELETE"?dojo.xhrDelete(d):dojo.xhrGet(d);e.addCallbacks(function(a){c.callback(f._getResult(a))},function(a){c.errback(a)})},_getUrl:function(b,
a,c){var d;b=="GET"||b=="DELETE"?a.length>0&&(d=a[0]):a.length>1&&(d=a[1]);if(d){var b="",f;for(f in d)if(a=d[f]){var a=encodeURIComponent(a),e="{"+f+"}",g=c.indexOf(e);g>=0?c=c.substring(0,g)+a+c.substring(g+e.length):(b&&(b+="&"),b+=f+"="+a)}b&&(c+="?"+b)}return c},_getContent:function(b,a){return b=="POST"||b=="PUT"?a?a[0]:null:null},_getResult:function(b){return b}}),dojo.declare("dojox.wire.ml.XmlHandler",dojox.wire.ml.RestHandler,{contentType:"text/xml",handleAs:"xml",_getContent:function(b,
a){var c=null;if(b=="POST"||b=="PUT"){var d=a[0];if(d)if(dojo.isString(d))c=d;else{c=d;if(c instanceof dojox.wire.ml.XmlElement)c=c.element;else if(c.nodeType===9)c=c.documentElement;c='<?xml version="1.0"?>'+dojox.xml.parser.innerXML(c)}}return c},_getResult:function(b){b&&(b=new dojox.wire.ml.XmlElement(b));return b}}),dojo.declare("dojox.wire.ml.JsonHandler",dojox.wire.ml.RestHandler,{contentType:"text/json",handleAs:"json",headers:{Accept:"*/json"},_getContent:function(b,a){var c=null;if(b=="POST"||
b=="PUT"){var d=a?a[0]:void 0;d&&(c=dojo.isString(d)?d:dojo.toJson(d))}return c}}));