/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.wire.ml.Transfer"]||(dojo._hasResource["dojox.wire.ml.Transfer"]=!0,dojo.provide("dojox.wire.ml.Transfer"),dojo.provide("dojox.wire.ml.ChildWire"),dojo.provide("dojox.wire.ml.ColumnWire"),dojo.provide("dojox.wire.ml.NodeWire"),dojo.provide("dojox.wire.ml.SegmentWire"),dojo.require("dijit._Widget"),dojo.require("dijit._Container"),dojo.require("dojox.wire._base"),dojo.require("dojox.wire.ml.Action"),dojo.declare("dojox.wire.ml.Transfer",dojox.wire.ml.Action,{source:"",sourceStore:"",
sourceAttribute:"",sourcePath:"",type:"",converter:"",delimiter:"",target:"",targetStore:"",targetAttribute:"",targetPath:"",_run:function(){var b=this._getWire("source"),a=this._getWire("target");dojox.wire.transfer(b,a,arguments)},_getWire:function(b){var a=void 0,a=b=="source"?{object:this.source,dataStore:this.sourceStore,attribute:this.sourceAttribute,path:this.sourcePath,type:this.type,converter:this.converter}:{object:this.target,dataStore:this.targetStore,attribute:this.targetAttribute,path:this.targetPath};
if(a.object)if(a.object.length>=9&&a.object.substring(0,9)=="arguments")a.property=a.object.substring(9),a.object=null;else{var d=a.object.indexOf(".");d<0?a.object=dojox.wire.ml._getValue(a.object):(a.property=a.object.substring(d+1),a.object=dojox.wire.ml._getValue(a.object.substring(0,d)))}if(a.dataStore)a.dataStore=dojox.wire.ml._getValue(a.dataStore);var c=void 0,f=this.getChildren();for(d in f){var e=f[d];e instanceof dojox.wire.ml.ChildWire&&e.which==b&&(c||(c={}),e._addWire(this,c))}if(c)c.object=
dojox.wire.create(a),c.dataStore=a.dataStore,a=c;return a}}),dojo.declare("dojox.wire.ml.ChildWire",dijit._Widget,{which:"source",object:"",property:"",type:"",converter:"",attribute:"",path:"",name:"",_addWire:function(b,a){if(this.name){if(!a.children)a.children={};a.children[this.name]=this._getWire(b)}else{if(!a.children)a.children=[];a.children.push(this._getWire(b))}},_getWire:function(){return{object:this.object?dojox.wire.ml._getValue(this.object):void 0,property:this.property,type:this.type,
converter:this.converter,attribute:this.attribute,path:this.path}}}),dojo.declare("dojox.wire.ml.ColumnWire",dojox.wire.ml.ChildWire,{column:"",_addWire:function(b,a){if(this.column){if(!a.columns)a.columns={};a.columns[this.column]=this._getWire(b)}else{if(!a.columns)a.columns=[];a.columns.push(this._getWire(b))}}}),dojo.declare("dojox.wire.ml.NodeWire",[dojox.wire.ml.ChildWire,dijit._Container],{titleProperty:"",titleAttribute:"",titlePath:"",_addWire:function(b,a){if(!a.nodes)a.nodes=[];a.nodes.push(this._getWires(b))},
_getWires:function(b){var a={node:this._getWire(b),title:{type:"string",property:this.titleProperty,attribute:this.titleAttribute,path:this.titlePath}},d=[],c=this.getChildren(),f;for(f in c){var e=c[f];e instanceof dojox.wire.ml.NodeWire&&d.push(e._getWires(b))}if(d.length>0)a.children=d;return a}}),dojo.declare("dojox.wire.ml.SegmentWire",dojox.wire.ml.ChildWire,{_addWire:function(b,a){if(!a.segments)a.segments=[];a.segments.push(this._getWire(b));if(b.delimiter&&!a.delimiter)a.delimiter=b.delimiter}}));