/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.wire.ml.util"])dojo._hasResource["dojox.wire.ml.util"]=!0,dojo.provide("dojox.wire.ml.util"),dojo.require("dojox.xml.parser"),dojo.require("dojox.wire.Wire"),dojox.wire.ml._getValue=function(a,b){if(a){var c=void 0;if(b&&a.length>=9&&a.substring(0,9)=="arguments")return c=a.substring(9),(new dojox.wire.Wire({property:c})).getValue(b);var d=a.indexOf(".");d>=0&&(c=a.substring(d+1),a=a.substring(0,d));if(d=dijit.byId(a)||dojo.byId(a)||dojo.getObject(a))return c?(new dojox.wire.Wire({object:d,
property:c})).getValue():d}},dojox.wire.ml._setValue=function(a,b){if(a){var c=a.indexOf(".");if(!(c<0)){var d=this._getValue(a.substring(0,c));d&&(c=a.substring(c+1),(new dojox.wire.Wire({object:d,property:c})).setValue(b))}}},dojo.declare("dojox.wire.ml.XmlElement",null,{constructor:function(a){dojo.isString(a)&&(a=this._getDocument().createElement(a));this.element=a},getPropertyValue:function(a){var b=void 0;if(!this.element)return b;if(!a)return b;if(a.charAt(0)=="@")b=this.element.getAttribute(a.substring(1));
else if(a=="text()"){if(a=this.element.firstChild)b=a.nodeValue}else{for(var c=[],d=0;d<this.element.childNodes.length;d++){var e=this.element.childNodes[d];e.nodeType===1&&e.nodeName==a&&c.push(new dojox.wire.ml.XmlElement(e))}c.length>0&&(b=c.length===1?c[0]:c)}return b},setPropertyValue:function(a,b){var c;if(this.element&&a)if(a.charAt(0)=="@"){var d=a.substring(1);b?this.element.setAttribute(d,b):this.element.removeAttribute(d)}else if(a=="text()"){for(;this.element.firstChild;)this.element.removeChild(this.element.firstChild);
b&&(c=this._getDocument().createTextNode(b),this.element.appendChild(c))}else{var d=null,e;for(c=this.element.childNodes.length-1;c>=0;c--)if(e=this.element.childNodes[c],e.nodeType===1&&e.nodeName==a){if(!d)d=e.nextSibling;this.element.removeChild(e)}if(b)if(dojo.isArray(b))for(c in b)e=b[c],e.element&&this.element.insertBefore(e.element,d);else b instanceof dojox.wire.ml.XmlElement?b.element&&this.element.insertBefore(b.element,d):(e=this._getDocument().createElement(a),c=this._getDocument().createTextNode(b),
e.appendChild(c),this.element.insertBefore(e,d))}},toString:function(){var a="";if(this.element){var b=this.element.firstChild;if(b)a=b.nodeValue}return a},toObject:function(){if(!this.element)return null;var a="",b={},c=0,d;for(d=0;d<this.element.childNodes.length;d++){var e=this.element.childNodes[d];if(e.nodeType===1){c++;var f=(new dojox.wire.ml.XmlElement(e)).toObject(),e=e.nodeName,g=b[e];g?dojo.isArray(g)?g.push(f):b[e]=[g,f]:b[e]=f}else if(e.nodeType===3||e.nodeType===4)a+=e.nodeValue}f=0;
if(this.element.nodeType===1){f=this.element.attributes.length;for(d=0;d<f;d++)e=this.element.attributes[d],b["@"+e.nodeName]=e.nodeValue}if(c===0){if(f===0)return a;b["text()"]=a}return b},_getDocument:function(){return this.element?this.element.nodeType==9?this.element:this.element.ownerDocument:dojox.xml.parser.parse()}});