/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojo.io.iframe"])dojo._hasResource["dojo.io.iframe"]=!0,dojo.provide("dojo.io.iframe"),dojo.getObject("io",!0,dojo),dojo.io.iframe={create:function(a,d,b){if(window[a])return window[a];if(window.frames[a])return window.frames[a];var c=null;b||(dojo.config.useXDomain&&!dojo.config.dojoBlankHtmlUrl&&console.warn("dojo.io.iframe.create: When using cross-domain Dojo builds, please save dojo/resources/blank.html to your domain and set djConfig.dojoBlankHtmlUrl to the path on your domain to blank.html"),
b=dojo.config.dojoBlankHtmlUrl||dojo.moduleUrl("dojo","resources/blank.html"));c=dojo.place('<iframe id="'+a+'" name="'+a+'" src="'+b+'" onload="'+d+'" style="position: absolute; left: 1px; top: 1px; height: 1px; width: 1px; visibility: hidden">',dojo.body());return window[a]=c},setSrc:function(a,d,b){try{if(b){var c;(c=dojo.isIE||dojo.isWebKit?a.contentWindow.document:a.contentWindow)?c.location.replace(d):a.location=d}else dojo.isWebKit?a.location=d:frames[a.name].location=d}catch(f){console.log("dojo.io.iframe.setSrc: ",
f)}},doc:function(a){return a.contentDocument||a.name&&a.document&&dojo.doc.getElementsByTagName("iframe")[a.name].contentWindow&&dojo.doc.getElementsByTagName("iframe")[a.name].contentWindow.document||a.name&&dojo.doc.frames[a.name]&&dojo.doc.frames[a.name].document||null},send:function(a){if(!this._frame)this._frame=this.create(this._iframeName,dojo._scopeName+".io.iframe._iframeOnload();");a=dojo._ioSetArgs(a,function(a){a.canceled=!0;a.ioArgs._callNext()},function(a){var b=null;try{var c=a.ioArgs,
f=dojo.io.iframe,h=f.doc(f._frame),e=c.handleAs,b=h;if(e!="html")if(e=="xml"){if(dojo.isIE<9||dojo.isIE&&dojo.isQuirks){dojo.query("a",f._frame.contentWindow.document.documentElement).orphan();var g=f._frame.contentWindow.document.documentElement.innerText,g=g.replace(/>\s+</g,"><"),g=dojo.trim(g),b=dojo._contentHandlers.xml({responseText:g})}}else b=h.getElementsByTagName("textarea")[0].value,e=="json"?b=dojo.fromJson(b):e=="javascript"&&(b=dojo.eval(b))}catch(i){b=i}finally{c._callNext()}return b},
function(a,b){b.ioArgs._hasError=!0;b.ioArgs._callNext();return a});a.ioArgs._callNext=function(){if(!this._calledNext)this._calledNext=!0,dojo.io.iframe._currentDfd=null,dojo.io.iframe._fireNextRequest()};this._dfdQueue.push(a);this._fireNextRequest();dojo._ioWatch(a,function(a){return!a.ioArgs._hasError},function(a){return!!a.ioArgs._finished},function(a){a.ioArgs._finished?a.callback(a):a.errback(Error("Invalid dojo.io.iframe request state"))});return a},_currentDfd:null,_dfdQueue:[],_iframeName:dojo._scopeName+
"IoIframe",_fireNextRequest:function(){try{if(!(this._currentDfd||this._dfdQueue.length==0)){do var a=this._currentDfd=this._dfdQueue.shift();while(a&&a.canceled&&this._dfdQueue.length);if(!a||a.canceled)this._currentDfd=null;else{var d=a.ioArgs,b=d.args;d._contentToClean=[];var c=dojo.byId(b.form),f=b.content||{};if(c){if(f){var h=function(a,b){dojo.create("input",{type:"hidden",name:a,value:b},c);d._contentToClean.push(a)},e;for(e in f){var g=f[e];if(dojo.isArray(g)&&g.length>1){var i;for(i=0;i<
g.length;i++)h(e,g[i])}else c[e]?c[e].value=g:h(e,g)}}var j=c.getAttributeNode("action"),k=c.getAttributeNode("method"),l=c.getAttributeNode("target");if(b.url)d._originalAction=j?j.value:null,j?j.value=b.url:c.setAttribute("action",b.url);if(!k||!k.value)k?k.value=b.method?b.method:"post":c.setAttribute("method",b.method?b.method:"post");d._originalTarget=l?l.value:null;l?l.value=this._iframeName:c.setAttribute("target",this._iframeName);c.target=this._iframeName;dojo._ioNotifyStart(a);c.submit()}else h=
b.url+(b.url.indexOf("?")>-1?"&":"?")+d.query,dojo._ioNotifyStart(a),this.setSrc(this._frame,h,!0)}}}catch(m){a.errback(m)}},_iframeOnload:function(){var a=this._currentDfd;if(a){var a=a.ioArgs,d=dojo.byId(a.args.form);if(d){for(var b=a._contentToClean,c=0;c<b.length;c++)for(var f=b[c],h=0;h<d.childNodes.length;h++){var e=d.childNodes[h];if(e.name==f){dojo.destroy(e);break}}a._originalAction&&d.setAttribute("action",a._originalAction);if(a._originalTarget)d.setAttribute("target",a._originalTarget),
d.target=a._originalTarget}a._finished=!0}else this._fireNextRequest()}};