/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form._DateTimeTextBox"]||(dojo._hasResource["dijit.form._DateTimeTextBox"]=!0,dojo.provide("dijit.form._DateTimeTextBox"),dojo.require("dojo.date"),dojo.require("dojo.date.locale"),dojo.require("dojo.date.stamp"),dojo.require("dijit.form.ValidationTextBox"),dojo.require("dijit._HasDropDown"),dojo.declare("dijit.form._DateTimeTextBox",[dijit.form.RangeBoundTextBox,dijit._HasDropDown],{templateString:dojo.cache("dijit.form","templates/DropDownBox.html",'<div class="dijit dijitReset dijitInlineTable dijitLeft"\n\tid="widget_${id}"\n\trole="combobox"\n\t><div class=\'dijitReset dijitRight dijitButtonNode dijitArrowButton dijitDownArrowButton dijitArrowButtonContainer\'\n\t\tdojoAttachPoint="_buttonNode, _popupStateNode" role="presentation"\n\t\t><input class="dijitReset dijitInputField dijitArrowButtonInner" value="&#9660; " type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t\t\t${_buttonInputDisabled}\n\t/></div\n\t><div class=\'dijitReset dijitValidationContainer\'\n\t\t><input class="dijitReset dijitInputField dijitValidationIcon dijitValidationInner" value="&#935; " type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t/></div\n\t><div class="dijitReset dijitInputField dijitInputContainer"\n\t\t><input class=\'dijitReset dijitInputInner\' ${!nameAttrSetting} type="text" autocomplete="off"\n\t\t\tdojoAttachPoint="textbox,focusNode" role="textbox" aria-haspopup="true"\n\t/></div\n></div>\n'),
hasDownArrow:!0,openOnClick:!0,regExpGen:dojo.date.locale.regexp,datePackage:"dojo.date",compare:function(a,b){var c=this._isInvalidDate(a),d=this._isInvalidDate(b);return c?d?0:-1:d?1:dojo.date.compare(a,b,this._selector)},forceWidth:!0,format:function(a,b){return!a?"":this.dateLocaleModule.format(a,b)},parse:function(a,b){return this.dateLocaleModule.parse(a,b)||(this._isEmpty(a)?null:void 0)},serialize:function(a,b){a.toGregorian&&(a=a.toGregorian());return dojo.date.stamp.toISOString(a,b)},dropDownDefaultValue:new Date,
value:new Date(""),_blankValue:null,popupClass:"",_selector:"",constructor:function(a){this.dateClassObj=dojo.getObject(a.datePackage?a.datePackage+".Date":"Date",!1);this.value=new this.dateClassObj("");this.datePackage=a.datePackage||this.datePackage;this.dateLocaleModule=dojo.getObject(this.datePackage+".locale",!1);this.regExpGen=this.dateLocaleModule.regexp;this._invalidDate=dijit.form._DateTimeTextBox.prototype.value.toString()},buildRendering:function(){this.inherited(arguments);if(!this.hasDownArrow)this._buttonNode.style.display=
"none";if(this.openOnClick||!this.hasDownArrow)this._buttonNode=this.domNode,this.baseClass+=" dijitComboBoxOpenOnClick"},_setConstraintsAttr:function(a){a.selector=this._selector;a.fullYear=!0;var b=dojo.date.stamp.fromISOString;if(typeof a.min=="string")a.min=b(a.min);if(typeof a.max=="string")a.max=b(a.max);this.inherited(arguments)},_isInvalidDate:function(a){return!a||isNaN(a)||typeof a!="object"||a.toString()==this._invalidDate},_setValueAttr:function(a,b,c){a!==void 0&&(typeof a=="string"&&
(a=dojo.date.stamp.fromISOString(a)),this._isInvalidDate(a)&&(a=null),a instanceof Date&&!(this.dateClassObj instanceof Date)&&(a=new this.dateClassObj(a)));this.inherited(arguments);this.dropDown&&this.dropDown.set("value",a,!1)},_set:function(a,b){a=="value"&&this.value instanceof Date&&this.compare(b,this.value)==0||this.inherited(arguments)},_setDropDownDefaultValueAttr:function(a){this._isInvalidDate(a)&&(a=new this.dateClassObj);this.dropDownDefaultValue=a},openDropDown:function(a){this.dropDown&&
this.dropDown.destroy();var b=dojo.getObject(this.popupClass,!1),c=this,d=this.get("value");this.dropDown=new b({onChange:function(a){dijit.form._DateTimeTextBox.superclass._setValueAttr.call(c,a,!0)},id:this.id+"_popup",dir:c.dir,lang:c.lang,value:d,currentFocus:!this._isInvalidDate(d)?d:this.dropDownDefaultValue,constraints:c.constraints,filterString:c.filterString,datePackage:c.datePackage,isDisabledDate:function(a){return!c.rangeCheck(a,c.constraints)}});this.inherited(arguments)},_getDisplayedValueAttr:function(){return this.textbox.value},
_setDisplayedValueAttr:function(a,b){this._setValueAttr(this.parse(a,this.constraints),b,a)}}));