/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form._FormWidget"]||(dojo._hasResource["dijit.form._FormWidget"]=!0,dojo.provide("dijit.form._FormWidget"),dojo.require("dojo.window"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit._CssStateMixin"),dojo.declare("dijit.form._FormWidget",[dijit._Widget,dijit._Templated,dijit._CssStateMixin],{name:"",alt:"",value:"",type:"text",tabIndex:"0",disabled:!1,intermediateChanges:!1,scrollOnFocus:!0,attributeMap:dojo.delegate(dijit._Widget.prototype.attributeMap,
{value:"focusNode",id:"focusNode",tabIndex:"focusNode",alt:"focusNode",title:"focusNode"}),postMixInProperties:function(){this.nameAttrSetting=this.name?'name="'+this.name.replace(/'/g,"&quot;")+'"':"";this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onmousedown","_onMouseDown")},_setDisabledAttr:function(a){this._set("disabled",a);dojo.attr(this.focusNode,"disabled",a);this.valueNode&&dojo.attr(this.valueNode,"disabled",a);dijit.setWaiState(this.focusNode,
"disabled",a);a?(this._set("hovering",!1),this._set("active",!1),a="tabIndex"in this.attributeMap?this.attributeMap.tabIndex:"focusNode",dojo.forEach(dojo.isArray(a)?a:[a],function(a){a=this[a];dojo.isWebKit||dijit.hasDefaultTabStop(a)?a.setAttribute("tabIndex","-1"):a.removeAttribute("tabIndex")},this)):this.tabIndex!=""&&this.focusNode.setAttribute("tabIndex",this.tabIndex)},setDisabled:function(a){dojo.deprecated("setDisabled("+a+") is deprecated. Use set('disabled',"+a+") instead.","","2.0");
this.set("disabled",a)},_onFocus:function(a){this.scrollOnFocus&&dojo.window.scrollIntoView(this.domNode);this.inherited(arguments)},isFocusable:function(){return!this.disabled&&this.focusNode&&dojo.style(this.domNode,"display")!="none"},focus:function(){this.disabled||dijit.focus(this.focusNode)},compare:function(a,b){return typeof a=="number"&&typeof b=="number"?isNaN(a)&&isNaN(b)?0:a-b:a>b?1:a<b?-1:0},onChange:function(){},_onChangeActive:!1,_handleOnChange:function(a,b){if(this._lastValueReported==
void 0&&(b===null||!this._onChangeActive))this._resetValue=this._lastValueReported=a;this._pendingOnChange=this._pendingOnChange||typeof a!=typeof this._lastValueReported||this.compare(a,this._lastValueReported)!=0;if((this.intermediateChanges||b||b===void 0)&&this._pendingOnChange)if(this._lastValueReported=a,this._pendingOnChange=!1,this._onChangeActive)this._onChangeHandle&&clearTimeout(this._onChangeHandle),this._onChangeHandle=setTimeout(dojo.hitch(this,function(){this._onChangeHandle=null;this.onChange(a)}),
0)},create:function(){this.inherited(arguments);this._onChangeActive=!0},destroy:function(){this._onChangeHandle&&(clearTimeout(this._onChangeHandle),this.onChange(this._lastValueReported));this.inherited(arguments)},setValue:function(a){dojo.deprecated("dijit.form._FormWidget:setValue("+a+") is deprecated.  Use set('value',"+a+") instead.","","2.0");this.set("value",a)},getValue:function(){dojo.deprecated(this.declaredClass+"::getValue() is deprecated. Use get('value') instead.","","2.0");return this.get("value")},
_onMouseDown:function(a){if(!a.ctrlKey&&dojo.mouseButtons.isLeft(a)&&this.isFocusable())var b=this.connect(dojo.body(),"onmouseup",function(){this.isFocusable()&&this.focus();this.disconnect(b)})}}),dojo.declare("dijit.form._FormValueWidget",dijit.form._FormWidget,{readOnly:!1,attributeMap:dojo.delegate(dijit.form._FormWidget.prototype.attributeMap,{value:"",readOnly:"focusNode"}),_setReadOnlyAttr:function(a){dojo.attr(this.focusNode,"readOnly",a);dijit.setWaiState(this.focusNode,"readonly",a);this._set("readOnly",
a)},postCreate:function(){this.inherited(arguments);if(dojo.isIE<9||dojo.isIE&&dojo.isQuirks)this.connect(this.focusNode||this.domNode,"onkeydown",this._onKeyDown);if(this._resetValue===void 0)this._lastValueReported=this._resetValue=this.value},_setValueAttr:function(a,b){this._handleOnChange(a,b)},_handleOnChange:function(a,b){this._set("value",a);this.inherited(arguments)},undo:function(){this._setValueAttr(this._lastValueReported,!1)},reset:function(){this._hasBeenBlurred=!1;this._setValueAttr(this._resetValue,
!0)},_onKeyDown:function(a){if(a.keyCode==dojo.keys.ESCAPE&&!a.ctrlKey&&!a.altKey&&!a.metaKey){var b;if(dojo.isIE)a.preventDefault(),b=document.createEventObject(),b.keyCode=dojo.keys.ESCAPE,b.shiftKey=a.shiftKey,a.srcElement.fireEvent("onkeypress",b)}},_layoutHackIE7:function(){if(dojo.isIE==7)for(var a=this.domNode,b=a.parentNode,c=a.firstChild||a,e=c.style.filter,d=this;b&&b.clientHeight==0;)(function(){var a=d.connect(b,"onscroll",function(){d.disconnect(a);c.style.filter=(new Date).getMilliseconds();
setTimeout(function(){c.style.filter=e},0)})})(),b=b.parentNode}}));