/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form._FormMixin"]||(dojo._hasResource["dijit.form._FormMixin"]=!0,dojo.provide("dijit.form._FormMixin"),dojo.require("dojo.window"),dojo.declare("dijit.form._FormMixin",null,{state:"",reset:function(){dojo.forEach(this.getDescendants(),function(b){b.reset&&b.reset()})},validate:function(){var b=!1;return dojo.every(dojo.map(this.getDescendants(),function(a){a._hasBeenBlurred=!0;var c=a.disabled||!a.validate||a.validate();!c&&!b&&(dojo.window.scrollIntoView(a.containerNode||
a.domNode),a.focus(),b=!0);return c}),function(a){return a})},setValues:function(b){dojo.deprecated(this.declaredClass+"::setValues() is deprecated. Use set('value', val) instead.","","2.0");return this.set("value",b)},_setValueAttr:function(b){var a={};dojo.forEach(this.getDescendants(),function(b){b.name&&(a[b.name]||(a[b.name]=[])).push(b)});for(var c in a)if(a.hasOwnProperty(c)){var d=a[c],e=dojo.getObject(c,!1,b);e!==void 0&&(dojo.isArray(e)||(e=[e]),typeof d[0].checked=="boolean"?dojo.forEach(d,
function(a){a.set("value",dojo.indexOf(e,a.value)!=-1)}):d[0].multiple?d[0].set("value",e):dojo.forEach(d,function(a,b){a.set("value",e[b])}))}},getValues:function(){dojo.deprecated(this.declaredClass+"::getValues() is deprecated. Use get('value') instead.","","2.0");return this.get("value")},_getValueAttr:function(){var b={};dojo.forEach(this.getDescendants(),function(a){var c=a.name;if(c&&!a.disabled){var d=a.get("value");typeof a.checked=="boolean"?/Radio/.test(a.declaredClass)?d!==!1?dojo.setObject(c,
d,b):(d=dojo.getObject(c,!1,b),d===void 0&&dojo.setObject(c,null,b)):(a=dojo.getObject(c,!1,b),a||(a=[],dojo.setObject(c,a,b)),d!==!1&&a.push(d)):(a=dojo.getObject(c,!1,b),typeof a!="undefined"?dojo.isArray(a)?a.push(d):dojo.setObject(c,[a,d],b):dojo.setObject(c,d,b))}});return b},isValid:function(){return this.state==""},onValidStateChange:function(){},_getState:function(){var b=dojo.map(this._descendants,function(a){return a.get("state")||""});return dojo.indexOf(b,"Error")>=0?"Error":dojo.indexOf(b,
"Incomplete")>=0?"Incomplete":""},disconnectChildren:function(){dojo.forEach(this._childConnections||[],dojo.hitch(this,"disconnect"));dojo.forEach(this._childWatches||[],function(b){b.unwatch()})},connectChildren:function(b){var a=this;this.disconnectChildren();this._descendants=this.getDescendants();b=b?function(b,c){a[b]=c}:dojo.hitch(this,"_set");b("value",this.get("value"));b("state",this._getState());var c=this._childConnections=[],d=this._childWatches=[];dojo.forEach(dojo.filter(this._descendants,
function(a){return a.validate}),function(b){dojo.forEach(["state","disabled"],function(c){d.push(b.watch(c,function(){a.set("state",a._getState())}))})});var e=function(){a._onChangeDelayTimer&&clearTimeout(a._onChangeDelayTimer);a._onChangeDelayTimer=setTimeout(function(){delete a._onChangeDelayTimer;a._set("value",a.get("value"))},10)};dojo.forEach(dojo.filter(this._descendants,function(a){return a.onChange}),function(b){c.push(a.connect(b,"onChange",e));d.push(b.watch("disabled",e))})},startup:function(){this.inherited(arguments);
this.connectChildren(!0);this.watch("state",function(b,a,c){this.onValidStateChange(c=="")})},destroy:function(){this.disconnectChildren();this.inherited(arguments)}}));