/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form._Spinner"]||(dojo._hasResource["dijit.form._Spinner"]=!0,dojo.provide("dijit.form._Spinner"),dojo.require("dijit.form.ValidationTextBox"),dojo.declare("dijit.form._Spinner",dijit.form.RangeBoundTextBox,{defaultTimeout:500,minimumTimeout:10,timeoutChangeRate:0.9,smallDelta:1,largeDelta:10,templateString:dojo.cache("dijit.form","templates/Spinner.html",'<div class="dijit dijitReset dijitInlineTable dijitLeft"\n\tid="widget_${id}" role="presentation"\n\t><div class="dijitReset dijitButtonNode dijitSpinnerButtonContainer"\n\t\t><input class="dijitReset dijitInputField dijitSpinnerButtonInner" type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t\t/><div class="dijitReset dijitLeft dijitButtonNode dijitArrowButton dijitUpArrowButton"\n\t\t\tdojoAttachPoint="upArrowNode"\n\t\t\t><div class="dijitArrowButtonInner"\n\t\t\t\t><input class="dijitReset dijitInputField" value="&#9650;" type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t\t\t\t\t${_buttonInputDisabled}\n\t\t\t/></div\n\t\t></div\n\t\t><div class="dijitReset dijitLeft dijitButtonNode dijitArrowButton dijitDownArrowButton"\n\t\t\tdojoAttachPoint="downArrowNode"\n\t\t\t><div class="dijitArrowButtonInner"\n\t\t\t\t><input class="dijitReset dijitInputField" value="&#9660;" type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t\t\t\t\t${_buttonInputDisabled}\n\t\t\t/></div\n\t\t></div\n\t></div\n\t><div class=\'dijitReset dijitValidationContainer\'\n\t\t><input class="dijitReset dijitInputField dijitValidationIcon dijitValidationInner" value="&#935;" type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t/></div\n\t><div class="dijitReset dijitInputField dijitInputContainer"\n\t\t><input class=\'dijitReset dijitInputInner\' dojoAttachPoint="textbox,focusNode" type="${type}" dojoAttachEvent="onkeypress:_onKeyPress"\n\t\t\trole="spinbutton" autocomplete="off" ${!nameAttrSetting}\n\t/></div\n></div>\n'),
baseClass:"dijitTextBox dijitSpinner",cssStateNodes:{upArrowNode:"dijitUpArrowButton",downArrowNode:"dijitDownArrowButton"},adjust:function(b){return b},_arrowPressed:function(b,a,c){!this.disabled&&!this.readOnly&&(this._setValueAttr(this.adjust(this.get("value"),a*c),!1),dijit.selectInputText(this.textbox,this.textbox.value.length))},_arrowReleased:function(){this._wheelTimer=null},_typematicCallback:function(b,a,c){var d=this.smallDelta;if(a==this.textbox)a=dojo.keys,c=c.charOrCode,d=c==a.PAGE_UP||
c==a.PAGE_DOWN?this.largeDelta:this.smallDelta,a=c==a.UP_ARROW||c==a.PAGE_UP?this.upArrowNode:this.downArrowNode;b==-1?this._arrowReleased(a):this._arrowPressed(a,a==this.upArrowNode?1:-1,d)},_wheelTimer:null,_mouseWheeled:function(b){dojo.stopEvent(b);b=b.detail?b.detail*-1:b.wheelDelta/120;if(b!==0){var a=this[b>0?"upArrowNode":"downArrowNode"];this._arrowPressed(a,b,this.smallDelta);this._wheelTimer||clearTimeout(this._wheelTimer);this._wheelTimer=setTimeout(dojo.hitch(this,"_arrowReleased",a),
50)}},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,!dojo.isMozilla?"onmousewheel":"DOMMouseScroll","_mouseWheeled");this._connects.push(dijit.typematic.addListener(this.upArrowNode,this.textbox,{charOrCode:dojo.keys.UP_ARROW,ctrlKey:!1,altKey:!1,shiftKey:!1,metaKey:!1},this,"_typematicCallback",this.timeoutChangeRate,this.defaultTimeout,this.minimumTimeout));this._connects.push(dijit.typematic.addListener(this.downArrowNode,this.textbox,{charOrCode:dojo.keys.DOWN_ARROW,
ctrlKey:!1,altKey:!1,shiftKey:!1,metaKey:!1},this,"_typematicCallback",this.timeoutChangeRate,this.defaultTimeout,this.minimumTimeout));this._connects.push(dijit.typematic.addListener(this.upArrowNode,this.textbox,{charOrCode:dojo.keys.PAGE_UP,ctrlKey:!1,altKey:!1,shiftKey:!1,metaKey:!1},this,"_typematicCallback",this.timeoutChangeRate,this.defaultTimeout,this.minimumTimeout));this._connects.push(dijit.typematic.addListener(this.downArrowNode,this.textbox,{charOrCode:dojo.keys.PAGE_DOWN,ctrlKey:!1,
altKey:!1,shiftKey:!1,metaKey:!1},this,"_typematicCallback",this.timeoutChangeRate,this.defaultTimeout,this.minimumTimeout))}}));