/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form.ComboBox"]||(dojo._hasResource["dijit.form.ComboBox"]=!0,dojo.provide("dijit.form.ComboBox"),dojo.require("dojo.window"),dojo.require("dojo.regexp"),dojo.require("dojo.data.util.simpleFetch"),dojo.require("dojo.data.util.filter"),dojo.require("dijit._CssStateMixin"),dojo.require("dijit.form._FormWidget"),dojo.require("dijit.form.ValidationTextBox"),dojo.require("dijit._HasDropDown"),dojo.requireLocalization("dijit.form","ComboBox",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),
dojo.declare("dijit.form.ComboBoxMixin",dijit._HasDropDown,{item:null,pageSize:Infinity,store:null,fetchProperties:{},query:{},autoComplete:!0,highlightMatch:"first",searchDelay:100,searchAttr:"name",labelAttr:"",labelType:"text",queryExpr:"${0}*",ignoreCase:!0,hasDownArrow:!0,templateString:dojo.cache("dijit.form","templates/DropDownBox.html",'<div class="dijit dijitReset dijitInlineTable dijitLeft"\n\tid="widget_${id}"\n\trole="combobox"\n\t><div class=\'dijitReset dijitRight dijitButtonNode dijitArrowButton dijitDownArrowButton dijitArrowButtonContainer\'\n\t\tdojoAttachPoint="_buttonNode, _popupStateNode" role="presentation"\n\t\t><input class="dijitReset dijitInputField dijitArrowButtonInner" value="&#9660; " type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t\t\t${_buttonInputDisabled}\n\t/></div\n\t><div class=\'dijitReset dijitValidationContainer\'\n\t\t><input class="dijitReset dijitInputField dijitValidationIcon dijitValidationInner" value="&#935; " type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t/></div\n\t><div class="dijitReset dijitInputField dijitInputContainer"\n\t\t><input class=\'dijitReset dijitInputInner\' ${!nameAttrSetting} type="text" autocomplete="off"\n\t\t\tdojoAttachPoint="textbox,focusNode" role="textbox" aria-haspopup="true"\n\t/></div\n></div>\n'),
baseClass:"dijitTextBox dijitComboBox",dropDownClass:"dijit.form._ComboBoxMenu",cssStateNodes:{_buttonNode:"dijitDownArrowButton"},maxHeight:-1,_stopClickEvents:!1,_getCaretPos:function(a){var b=0;if(typeof a.selectionStart=="number")b=a.selectionStart;else if(dojo.isIE){var c=dojo.doc.selection.createRange().duplicate(),a=a.createTextRange();c.move("character",0);a.move("character",0);try{a.setEndPoint("EndToEnd",c),b=String(a.text).replace(/\r/g,"").length}catch(d){}}return b},_setCaretPos:function(a,
b){b=parseInt(b);dijit.selectInputText(a,b,b)},_setDisabledAttr:function(a){this.inherited(arguments);dijit.setWaiState(this.domNode,"disabled",a)},_abortQuery:function(){if(this.searchTimer)clearTimeout(this.searchTimer),this.searchTimer=null;if(this._fetchHandle)this._fetchHandle.abort&&this._fetchHandle.abort(),this._fetchHandle=null},_onInput:function(a){if(!this.searchTimer&&(a.type=="paste"||a.type=="input")&&this._lastInput!=this.textbox.value)this.searchTimer=setTimeout(dojo.hitch(this,function(){this._onKey({charOrCode:229})}),
100);this.inherited(arguments)},_onKey:function(a){var b=a.charOrCode;if(!a.altKey&&!((a.ctrlKey||a.metaKey)&&b!="x"&&b!="v"||b==dojo.keys.SHIFT)){var c=!1,d=this.dropDown,e=dojo.keys,f=null;this._prev_key_backspace=!1;this._abortQuery();this.inherited(arguments);this._opened&&(f=d.getHighlightedOption());switch(b){case e.PAGE_DOWN:case e.DOWN_ARROW:case e.PAGE_UP:case e.UP_ARROW:this._opened&&this._announceOption(f);dojo.stopEvent(a);break;case e.ENTER:if(f)if(f==d.nextButton){this._nextSearch(1);
dojo.stopEvent(a);break}else{if(f==d.previousButton){this._nextSearch(-1);dojo.stopEvent(a);break}}else this._setBlurValue(),this._setCaretPos(this.focusNode,this.focusNode.value.length);(this._opened||this._fetchHandle)&&a.preventDefault();case e.TAB:b=this.get("displayedValue");if(d&&(b==d._messages.previousMessage||b==d._messages.nextMessage))break;f&&this._selectOption();if(this._opened)this._lastQuery=null,this.closeDropDown();break;case " ":f?(dojo.stopEvent(a),this._selectOption(),this.closeDropDown()):
c=!0;break;case e.DELETE:case e.BACKSPACE:c=this._prev_key_backspace=!0;break;default:c=typeof b=="string"||b==229}if(c)this.item=void 0,this.searchTimer=setTimeout(dojo.hitch(this,"_startSearchFromInput"),1)}},_autoCompleteText:function(a){var b=this.focusNode;dijit.selectInputText(b,b.value.length);var c=this.ignoreCase?"toLowerCase":"substr";if(a[c](0).indexOf(this.focusNode.value[c](0))==0){if(c=this._getCaretPos(b),c+1>b.value.length)b.value=a,dijit.selectInputText(b,c)}else b.value=a,dijit.selectInputText(b)},
_openResultList:function(a,b){this._fetchHandle=null;if(!this.disabled&&!(this.readOnly||b.query[this.searchAttr]!=this._lastQuery)){var c=this.dropDown._highlighted_option&&dojo.hasClass(this.dropDown._highlighted_option,"dijitMenuItemSelected");this.dropDown.clearResultList();if(!a.length&&!this._maxOptions)this.closeDropDown();else{b._maxOptions=this._maxOptions;var d=this.dropDown.createOptions(a,b,dojo.hitch(this,"_getMenuLabelFromItem"));this._showResultList();b.direction?(1==b.direction?this.dropDown.highlightFirstOption():
-1==b.direction&&this.dropDown.highlightLastOption(),c&&this._announceOption(this.dropDown.getHighlightedOption())):this.autoComplete&&!this._prev_key_backspace&&!/^[*]+$/.test(b.query[this.searchAttr])&&this._announceOption(d[1])}}},_showResultList:function(){this.closeDropDown(!0);this.displayMessage("");this.openDropDown();dijit.setWaiState(this.domNode,"expanded","true")},loadDropDown:function(){this._startSearchAll()},isLoaded:function(){return!1},closeDropDown:function(){this._abortQuery();
this._opened&&(this.inherited(arguments),dijit.setWaiState(this.domNode,"expanded","false"),dijit.removeWaiState(this.focusNode,"activedescendant"))},_setBlurValue:function(){var a=this.get("displayedValue"),b=this.dropDown;b&&(a==b._messages.previousMessage||a==b._messages.nextMessage)?this._setValueAttr(this._lastValueReported,!0):typeof this.item=="undefined"?(this.item=null,this.set("displayedValue",a)):(this.value!=this._lastValueReported&&dijit.form._FormValueWidget.prototype._setValueAttr.call(this,
this.value,!0),this._refreshState())},_onBlur:function(){this.closeDropDown();this.inherited(arguments)},_setItemAttr:function(a,b,c){c||(c=this.store.getValue(a,this.searchAttr));var d=this._getValueField()!=this.searchAttr?this.store.getIdentity(a):c;this._set("item",a);dijit.form.ComboBox.superclass._setValueAttr.call(this,d,b,c)},_announceOption:function(a){if(a){var b;a==this.dropDown.nextButton||a==this.dropDown.previousButton?(b=a.innerHTML,this.item=void 0,this.value=""):(b=this.store.getValue(a.item,
this.searchAttr).toString(),this.set("item",a.item,!1,b));this.focusNode.value=this.focusNode.value.substring(0,this._lastInput.length);dijit.setWaiState(this.focusNode,"activedescendant",dojo.attr(a,"id"));this._autoCompleteText(b)}},_selectOption:function(a){a&&this._announceOption(a.target);this.closeDropDown();this._setCaretPos(this.focusNode,this.focusNode.value.length);dijit.form._FormValueWidget.prototype._setValueAttr.call(this,this.value,!0)},_startSearchAll:function(){this._startSearch("")},
_startSearchFromInput:function(){this._startSearch(this.focusNode.value.replace(/([\\\*\?])/g,"\\$1"))},_getQueryString:function(a){return dojo.string.substitute(this.queryExpr,[a])},_startSearch:function(a){if(!this.dropDown){var b=this.id+"_popup";this.dropDown=new (dojo.getObject(this.dropDownClass,!1))({onChange:dojo.hitch(this,this._selectOption),id:b,dir:this.dir});dijit.removeWaiState(this.focusNode,"activedescendant");dijit.setWaiState(this.textbox,"owns",b)}b=dojo.clone(this.query);this._lastInput=
a;this._lastQuery=b[this.searchAttr]=this._getQueryString(a);this.searchTimer=setTimeout(dojo.hitch(this,function(a,b){this.searchTimer=null;var e={queryOptions:{ignoreCase:this.ignoreCase,deep:!0},query:a,onBegin:dojo.hitch(this,"_setMaxOptions"),onComplete:dojo.hitch(this,"_openResultList"),onError:function(a){b._fetchHandle=null;console.error("dijit.form.ComboBox: "+a);b.closeDropDown()},start:0,count:this.pageSize};dojo.mixin(e,b.fetchProperties);this._fetchHandle=b.store.fetch(e);this._nextSearch=
this.dropDown.onPage=dojo.hitch(this,function(a,b){a.start+=a.count*b;a.direction=b;this._fetchHandle=this.store.fetch(a);this.focus()},this._fetchHandle)},b,this),this.searchDelay)},_setMaxOptions:function(a){this._maxOptions=a},_getValueField:function(){return this.searchAttr},constructor:function(){this.query={};this.fetchProperties={}},postMixInProperties:function(){if(!this.store&&(this.store=new dijit.form._ComboBoxDataStore(this.srcNodeRef),!("value"in this.params))){var a=this.item=this.store.fetchSelectedItem();
if(a){var b=this._getValueField();this.value=this.store.getValue(a,b)}}this.inherited(arguments)},postCreate:function(){var a=dojo.query('label[for="'+this.id+'"]');if(a.length)a[0].id=this.id+"_label",dijit.setWaiState(this.domNode,"labelledby",a[0].id);this.inherited(arguments)},_setHasDownArrowAttr:function(a){this.hasDownArrow=a;this._buttonNode.style.display=a?"":"none"},_getMenuLabelFromItem:function(a){var a=this.labelFunc(a,this.store),b=this.labelType;this.highlightMatch!="none"&&this.labelType==
"text"&&this._lastInput&&(a=this.doHighlight(a,this._escapeHtml(this._lastInput)),b="html");return{html:b=="html",label:a}},doHighlight:function(a,b){var c=(this.ignoreCase?"i":"")+(this.highlightMatch=="all"?"g":""),d=this.queryExpr.indexOf("${0}"),b=dojo.regexp.escapeString(b);return this._escapeHtml(a).replace(RegExp((d==0?"^":"")+"("+b+")"+(d==this.queryExpr.length-4?"$":""),c),'<span class="dijitComboBoxHighlightMatch">$1</span>')},_escapeHtml:function(a){return a=String(a).replace(/&/gm,"&amp;").replace(/</gm,
"&lt;").replace(/>/gm,"&gt;").replace(/"/gm,"&quot;")},reset:function(){this.item=null;this.inherited(arguments)},labelFunc:function(a,b){return b.getValue(a,this.labelAttr||this.searchAttr).toString()}}),dojo.declare("dijit.form._ComboBoxMenu",[dijit._Widget,dijit._Templated,dijit._CssStateMixin],{templateString:"<ul class='dijitReset dijitMenu' dojoAttachEvent='onmousedown:_onMouseDown,onmouseup:_onMouseUp,onmouseover:_onMouseOver,onmouseout:_onMouseOut' style='overflow: \"auto\"; overflow-x: \"hidden\";'><li class='dijitMenuItem dijitMenuPreviousButton' dojoAttachPoint='previousButton' role='option'></li><li class='dijitMenuItem dijitMenuNextButton' dojoAttachPoint='nextButton' role='option'></li></ul>",
_messages:null,baseClass:"dijitComboBoxMenu",postMixInProperties:function(){this.inherited(arguments);this._messages=dojo.i18n.getLocalization("dijit.form","ComboBox",this.lang)},buildRendering:function(){this.inherited(arguments);this.previousButton.innerHTML=this._messages.previousMessage;this.nextButton.innerHTML=this._messages.nextMessage},_setValueAttr:function(a){this.value=a;this.onChange(a)},onChange:function(){},onPage:function(){},onClose:function(){this._blurOptionNode()},_createOption:function(a,
b){var c=dojo.create("li",{"class":"dijitReset dijitMenuItem"+(this.isLeftToRight()?"":" dijitMenuItemRtl"),role:"option"}),d=b(a);d.html?c.innerHTML=d.label:c.appendChild(dojo.doc.createTextNode(d.label));if(c.innerHTML=="")c.innerHTML="&nbsp;";c.item=a;return c},createOptions:function(a,b,c){this.previousButton.style.display=b.start==0?"none":"";dojo.attr(this.previousButton,"id",this.id+"_prev");dojo.forEach(a,function(a,b){var d=this._createOption(a,c);dojo.attr(d,"id",this.id+b);this.domNode.insertBefore(d,
this.nextButton)},this);var d=!1;b._maxOptions&&b._maxOptions!=-1?b.start+b.count<b._maxOptions?d=!0:b.start+b.count>b._maxOptions&&b.count==a.length&&(d=!0):b.count==a.length&&(d=!0);this.nextButton.style.display=d?"":"none";dojo.attr(this.nextButton,"id",this.id+"_next");return this.domNode.childNodes},clearResultList:function(){for(;this.domNode.childNodes.length>2;)this.domNode.removeChild(this.domNode.childNodes[this.domNode.childNodes.length-2]);this._blurOptionNode()},_onMouseDown:function(a){dojo.stopEvent(a)},
_onMouseUp:function(a){if(a.target!==this.domNode&&this._highlighted_option)if(a.target==this.previousButton)this._blurOptionNode(),this.onPage(-1);else if(a.target==this.nextButton)this._blurOptionNode(),this.onPage(1);else{for(a=a.target;!a.item;)a=a.parentNode;this._setValueAttr({target:a},!0)}},_onMouseOver:function(a){if(a.target!==this.domNode){a=a.target;if(!(a==this.previousButton||a==this.nextButton))for(;!a.item;)a=a.parentNode;this._focusOptionNode(a)}},_onMouseOut:function(a){a.target!==
this.domNode&&this._blurOptionNode()},_focusOptionNode:function(a){if(this._highlighted_option!=a)this._blurOptionNode(),this._highlighted_option=a,dojo.addClass(this._highlighted_option,"dijitMenuItemSelected")},_blurOptionNode:function(){if(this._highlighted_option)dojo.removeClass(this._highlighted_option,"dijitMenuItemSelected"),this._highlighted_option=null},_highlightNextOption:function(){if(this.getHighlightedOption()){var a=this._highlighted_option.nextSibling;a&&a.style.display!="none"?this._focusOptionNode(a):
this.highlightFirstOption()}else a=this.domNode.firstChild,this._focusOptionNode(a.style.display=="none"?a.nextSibling:a);dojo.window.scrollIntoView(this._highlighted_option)},highlightFirstOption:function(){var a=this.domNode.firstChild,b=a.nextSibling;this._focusOptionNode(b.style.display=="none"?a:b);dojo.window.scrollIntoView(this._highlighted_option)},highlightLastOption:function(){this._focusOptionNode(this.domNode.lastChild.previousSibling);dojo.window.scrollIntoView(this._highlighted_option)},
_highlightPrevOption:function(){if(this.getHighlightedOption()){var a=this._highlighted_option.previousSibling;a&&a.style.display!="none"?this._focusOptionNode(a):this.highlightLastOption()}else a=this.domNode.lastChild,this._focusOptionNode(a.style.display=="none"?a.previousSibling:a);dojo.window.scrollIntoView(this._highlighted_option)},_page:function(a){var b=0,c=this.domNode.scrollTop,d=dojo.style(this.domNode,"height");for(this.getHighlightedOption()||this._highlightNextOption();b<d;){if(a){if(!this.getHighlightedOption().previousSibling||
this._highlighted_option.previousSibling.style.display=="none")break;this._highlightPrevOption()}else{if(!this.getHighlightedOption().nextSibling||this._highlighted_option.nextSibling.style.display=="none")break;this._highlightNextOption()}var e=this.domNode.scrollTop;b+=(e-c)*(a?-1:1);c=e}},pageUp:function(){this._page(!0)},pageDown:function(){this._page(!1)},getHighlightedOption:function(){var a=this._highlighted_option;return a&&a.parentNode?a:null},handleKey:function(a){switch(a.charOrCode){case dojo.keys.DOWN_ARROW:return this._highlightNextOption(),
!1;case dojo.keys.PAGE_DOWN:return this.pageDown(),!1;case dojo.keys.UP_ARROW:return this._highlightPrevOption(),!1;case dojo.keys.PAGE_UP:return this.pageUp(),!1;default:return!0}}}),dojo.declare("dijit.form.ComboBox",[dijit.form.ValidationTextBox,dijit.form.ComboBoxMixin],{_setValueAttr:function(a,b,c){this._set("item",null);a||(a="");dijit.form.ValidationTextBox.prototype._setValueAttr.call(this,a,b,c)}}),dojo.declare("dijit.form._ComboBoxDataStore",null,{constructor:function(a){this.root=a;if(a.tagName!=
"SELECT"&&a.firstChild)a=dojo.query("select",a),a.length>0?a=a[0]:(this.root.innerHTML="<SELECT>"+this.root.innerHTML+"</SELECT>",a=this.root.firstChild),this.root=a;dojo.query("> option",a).forEach(function(a){a.innerHTML=dojo.trim(a.innerHTML)})},getValue:function(a,b){return b=="value"?a.value:a.innerText||a.textContent||""},isItemLoaded:function(){return!0},getFeatures:function(){return{"dojo.data.api.Read":!0,"dojo.data.api.Identity":!0}},_fetchItems:function(a,b){if(!a.query)a.query={};if(!a.query.name)a.query.name=
"";if(!a.queryOptions)a.queryOptions={};var c=dojo.data.util.filter.patternToRegExp(a.query.name,a.queryOptions.ignoreCase),d=dojo.query("> option",this.root).filter(function(a){return(a.innerText||a.textContent||"").match(c)});a.sort&&d.sort(dojo.data.util.sorter.createSortFunction(a.sort,this));b(d,a)},close:function(){},getLabel:function(a){return a.innerHTML},getIdentity:function(a){return dojo.attr(a,"value")},fetchItemByIdentity:function(a){var b=dojo.query("> option[value='"+a.identity+"']",
this.root)[0];a.onItem(b)},fetchSelectedItem:function(){var a=this.root,b=a.selectedIndex;return typeof b=="number"?dojo.query("> option:nth-child("+(b!=-1?b+1:1)+")",a)[0]:null}}),dojo.extend(dijit.form._ComboBoxDataStore,dojo.data.util.simpleFetch));