/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form.NumberTextBox"]||(dojo._hasResource["dijit.form.NumberTextBox"]=!0,dojo.provide("dijit.form.NumberTextBox"),dojo.require("dijit.form.ValidationTextBox"),dojo.require("dojo.number"),dojo.declare("dijit.form.NumberTextBoxMixin",null,{regExpGen:dojo.number.regexp,value:NaN,editOptions:{pattern:"#.######"},_formatter:dojo.number.format,_setConstraintsAttr:function(a){var b=typeof a.places=="number"?a.places:0;b&&b++;if(typeof a.max!="number")a.max=9*Math.pow(10,15-b);if(typeof a.min!=
"number")a.min=-9*Math.pow(10,15-b);this.inherited(arguments,[a]);this.focusNode&&this.focusNode.value&&!isNaN(this.value)&&this.set("value",this.value)},_onFocus:function(){if(!this.disabled){var a=this.get("value");if(typeof a=="number"&&!isNaN(a)&&(a=this.format(a,this.constraints),a!==void 0))this.textbox.value=a;this.inherited(arguments)}},format:function(a,b){var c=String(a);if(typeof a!="number")return c;if(isNaN(a))return"";if(!("rangeCheck"in this&&this.rangeCheck(a,b))&&b.exponent!==!1&&
/\de[-+]?\d/i.test(c))return c;this.editOptions&&this._focused&&(b=dojo.mixin({},b,this.editOptions));return this._formatter(a,b)},_parser:dojo.number.parse,parse:function(a,b){var c=this._parser(a,dojo.mixin({},b,this.editOptions&&this._focused?this.editOptions:{}));this.editOptions&&this._focused&&isNaN(c)&&(c=this._parser(a,b));return c},_getDisplayedValueAttr:function(){var a=this.inherited(arguments);return isNaN(a)?this.textbox.value:a},filter:function(a){return a===null||a===""||a===void 0?
NaN:this.inherited(arguments)},serialize:function(a,b){return typeof a!="number"||isNaN(a)?"":this.inherited(arguments)},_setBlurValue:function(){this._setValueAttr(dojo.hitch(dojo.mixin({},this,{_focused:!0}),"get")("value"),!0)},_setValueAttr:function(a,b,c){if(a!==void 0&&c===void 0)if(c=String(a),typeof a=="number")if(isNaN(a))c="";else{if("rangeCheck"in this&&this.rangeCheck(a,this.constraints)||this.constraints.exponent===!1||!/\de[-+]?\d/i.test(c))c=void 0}else a?a=void 0:(c="",a=NaN);this.inherited(arguments,
[a,b,c])},_getValueAttr:function(){var a=this.inherited(arguments);if(isNaN(a)&&this.textbox.value!==""){if(this.constraints.exponent!==!1&&/\de[-+]?\d/i.test(this.textbox.value)&&RegExp("^"+dojo.number._realNumberRegexp(dojo.mixin({},this.constraints))+"$").test(this.textbox.value))return a=Number(this.textbox.value),isNaN(a)?void 0:a}else return a},isValid:function(a){if(!this._focused||this._isEmpty(this.textbox.value))return this.inherited(arguments);else{var b=this.get("value");return!isNaN(b)&&
this.rangeCheck(b,this.constraints)?this.constraints.exponent!==!1&&/\de[-+]?\d/i.test(this.textbox.value)?!0:this.inherited(arguments):!1}}}),dojo.declare("dijit.form.NumberTextBox",[dijit.form.RangeBoundTextBox,dijit.form.NumberTextBoxMixin],{baseClass:"dijitTextBox dijitNumberTextBox"}));