/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form.Select"]||(dojo._hasResource["dijit.form.Select"]=!0,dojo.provide("dijit.form.Select"),dojo.require("dijit.form._FormSelectWidget"),dojo.require("dijit._HasDropDown"),dojo.require("dijit.Menu"),dojo.require("dijit.Tooltip"),dojo.requireLocalization("dijit.form","validate",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dijit.form._SelectMenu",dijit.Menu,{buildRendering:function(){this.inherited(arguments);
var a=this.menuTableNode=this.domNode,b=this.domNode=dojo.create("div",{style:{overflowX:"hidden",overflowY:"scroll"}});a.parentNode&&a.parentNode.replaceChild(b,a);dojo.removeClass(a,"dijitMenuTable");b.className=a.className+" dijitSelectMenu";a.className="dijitReset dijitMenuTable";dijit.setWaiRole(a,"listbox");dijit.setWaiRole(b,"presentation");b.appendChild(a)},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onmousemove",dojo.stopEvent)},resize:function(a){if(a&&(dojo.marginBox(this.domNode,
a),"w"in a))this.menuTableNode.style.width="100%"}}),dojo.declare("dijit.form.Select",[dijit.form._FormSelectWidget,dijit._HasDropDown],{baseClass:"dijitSelect",templateString:dojo.cache("dijit.form","templates/Select.html",'<table class="dijit dijitReset dijitInline dijitLeft"\n\tdojoAttachPoint="_buttonNode,tableNode,focusNode" cellspacing=\'0\' cellpadding=\'0\'\n\trole="combobox" aria-haspopup="true"\n\t><tbody role="presentation"><tr role="presentation"\n\t\t><td class="dijitReset dijitStretch dijitButtonContents dijitButtonNode" role="presentation"\n\t\t\t><span class="dijitReset dijitInline dijitButtonText"  dojoAttachPoint="containerNode,_popupStateNode"></span\n\t\t\t><input type="hidden" ${!nameAttrSetting} dojoAttachPoint="valueNode" value="${value}" aria-hidden="true"\n\t\t/></td><td class="dijitReset dijitRight dijitButtonNode dijitArrowButton dijitDownArrowButton"\n\t\t\t\tdojoAttachPoint="titleNode" role="presentation"\n\t\t\t><div class="dijitReset dijitArrowButtonInner" role="presentation"></div\n\t\t\t><div class="dijitReset dijitArrowButtonChar" role="presentation">&#9660;</div\n\t\t></td\n\t></tr></tbody\n></table>\n'),
attributeMap:dojo.mixin(dojo.clone(dijit.form._FormSelectWidget.prototype.attributeMap),{style:"tableNode"}),required:!1,state:"",message:"",tooltipPosition:[],emptyLabel:"&nbsp;",_isLoaded:!1,_childrenLoaded:!1,_fillContent:function(){this.inherited(arguments);if(this.options.length&&!this.value&&this.srcNodeRef){var a=this.srcNodeRef.selectedIndex||0;this.value=this.options[a>=0?a:0].value}this.dropDown=new dijit.form._SelectMenu({id:this.id+"_menu"});dojo.addClass(this.dropDown.domNode,this.baseClass+
"Menu")},_getMenuItemForOption:function(a){if(!a.value&&!a.label)return new dijit.MenuSeparator;else{var b=dojo.hitch(this,"_setValueAttr",a),a=new dijit.MenuItem({option:a,label:a.label||this.emptyLabel,onClick:b,disabled:a.disabled||!1});dijit.setWaiRole(a.focusNode,"listitem");return a}},_addOptionItem:function(a){this.dropDown&&this.dropDown.addChild(this._getMenuItemForOption(a))},_getChildren:function(){return!this.dropDown?[]:this.dropDown.getChildren()},_loadChildren:function(a){a===!0?(this.dropDown&&
delete this.dropDown.focusedChild,this.options.length?this.inherited(arguments):(dojo.forEach(this._getChildren(),function(a){a.destroyRecursive()}),this.dropDown.addChild(new dijit.MenuItem({label:"&nbsp;"})))):this._updateSelection();this._isLoaded=!1;this._childrenLoaded=!0;this._loadingStore||this._setValueAttr(this.value)},_setValueAttr:function(a){this.inherited(arguments);dojo.attr(this.valueNode,"value",this.get("value"))},_setDisplay:function(a){a=a||this.emptyLabel;this.containerNode.innerHTML=
'<span class="dijitReset dijitInline '+this.baseClass+'Label">'+a+"</span>";dijit.setWaiState(this.focusNode,"valuetext",a)},validate:function(a){a=this.isValid(a);this._set("state",a?"":"Error");dijit.setWaiState(this.focusNode,"invalid",a?"false":"true");var b=a?"":this._missingMsg;this.message!==b&&(this._set("message",b),dijit.hideTooltip(this.domNode),b&&dijit.showTooltip(b,this.domNode,this.tooltipPosition,!this.isLeftToRight()));return a},isValid:function(){return!this.required||this.value===
0||!/^\s*$/.test(this.value||"")},reset:function(){this.inherited(arguments);dijit.hideTooltip(this.domNode);this._set("state","");this._set("message","")},postMixInProperties:function(){this.inherited(arguments);this._missingMsg=dojo.i18n.getLocalization("dijit.form","validate",this.lang).missingMessage},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onmousemove",dojo.stopEvent)},_setStyleAttr:function(a){this.inherited(arguments);dojo.toggleClass(this.domNode,this.baseClass+
"FixedWidth",!!this.tableNode.style.width)},isLoaded:function(){return this._isLoaded},loadDropDown:function(a){this._loadChildren(!0);this._isLoaded=!0;a()},closeDropDown:function(){this.inherited(arguments);if(this.dropDown&&this.dropDown.menuTableNode)this.dropDown.menuTableNode.style.width=""},uninitialize:function(a){this.dropDown&&!this.dropDown._destroyed&&(this.dropDown.destroyRecursive(a),delete this.dropDown);this.inherited(arguments)}}));