/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.form.ValidationTextBox"]||(dojo._hasResource["dijit.form.ValidationTextBox"]=!0,dojo.provide("dijit.form.ValidationTextBox"),dojo.require("dojo.i18n"),dojo.require("dijit.form.TextBox"),dojo.require("dijit.Tooltip"),dojo.requireLocalization("dijit.form","validate",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dijit.form.ValidationTextBox",dijit.form.TextBox,{templateString:dojo.cache("dijit.form","templates/ValidationTextBox.html",
'<div class="dijit dijitReset dijitInlineTable dijitLeft"\n\tid="widget_${id}" role="presentation"\n\t><div class=\'dijitReset dijitValidationContainer\'\n\t\t><input class="dijitReset dijitInputField dijitValidationIcon dijitValidationInner" value="&#935; " type="text" tabIndex="-1" readonly="readonly" role="presentation"\n\t/></div\n\t><div class="dijitReset dijitInputField dijitInputContainer"\n\t\t><input class="dijitReset dijitInputInner" dojoAttachPoint=\'textbox,focusNode\' autocomplete="off"\n\t\t\t${!nameAttrSetting} type=\'${type}\'\n\t/></div\n></div>\n'),
baseClass:"dijitTextBox dijitValidationTextBox",required:!1,promptMessage:"",invalidMessage:"$_unset_$",missingMessage:"$_unset_$",message:"",constraints:{},regExp:".*",regExpGen:function(){return this.regExp},state:"",tooltipPosition:[],_setValueAttr:function(){this.inherited(arguments);this.validate(this._focused)},validator:function(a,b){return RegExp("^(?:"+this.regExpGen(b)+")"+(this.required?"":"?")+"$").test(a)&&(!this.required||!this._isEmpty(a))&&(this._isEmpty(a)||this.parse(a,b)!==void 0)},
_isValidSubset:function(){return this.textbox.value.search(this._partialre)==0},isValid:function(){return this.validator(this.textbox.value,this.constraints)},_isEmpty:function(a){return(this.trim?/^\s*$/:/^$/).test(a)},getErrorMessage:function(){return this.required&&this._isEmpty(this.textbox.value)?this.missingMessage:this.invalidMessage},getPromptMessage:function(){return this.promptMessage},_maskValidSubsetError:!0,validate:function(a){var b="",c=this.disabled||this.isValid(a);if(c)this._maskValidSubsetError=
!0;var d=this._isEmpty(this.textbox.value),e=!c&&a&&this._isValidSubset();this._set("state",c?"":((!this._hasBeenBlurred||a)&&d||e)&&this._maskValidSubsetError?"Incomplete":"Error");dijit.setWaiState(this.focusNode,"invalid",c?"false":"true");this.state=="Error"?(this._maskValidSubsetError=a&&e,b=this.getErrorMessage(a)):this.state=="Incomplete"?(b=this.getPromptMessage(a),this._maskValidSubsetError=!this._hasBeenBlurred||a):d&&(b=this.getPromptMessage(a));this.set("message",b);return c},displayMessage:function(a){dijit.hideTooltip(this.domNode);
a&&this._focused&&dijit.showTooltip(a,this.domNode,this.tooltipPosition,!this.isLeftToRight())},_refreshState:function(){this.validate(this._focused);this.inherited(arguments)},constructor:function(){this.constraints={}},_setConstraintsAttr:function(a){if(!a.locale&&this.lang)a.locale=this.lang;this._set("constraints",a);this._computePartialRE()},_computePartialRE:function(){var a=this.regExpGen(this.constraints);this.regExp=a;var b="";a!=".*"&&this.regExp.replace(/\\.|\[\]|\[.*?[^\\]{1}\]|\{.*?\}|\(\?[=:!]|./g,
function(a){switch(a.charAt(0)){case "{":case "+":case "?":case "*":case "^":case "$":case "|":case "(":b+=a;break;case ")":b+="|$)";break;default:b+="(?:"+a+"|$)"}});try{"".search(b)}catch(c){b=this.regExp,console.warn("RegExp error in "+this.declaredClass+": "+this.regExp)}this._partialre="^(?:"+b+")$"},postMixInProperties:function(){this.inherited(arguments);this.messages=dojo.i18n.getLocalization("dijit.form","validate",this.lang);if(this.invalidMessage=="$_unset_$")this.invalidMessage=this.messages.invalidMessage;
if(!this.invalidMessage)this.invalidMessage=this.promptMessage;if(this.missingMessage=="$_unset_$")this.missingMessage=this.messages.missingMessage;if(!this.missingMessage)this.missingMessage=this.invalidMessage;this._setConstraintsAttr(this.constraints)},_setDisabledAttr:function(a){this.inherited(arguments);this._refreshState()},_setRequiredAttr:function(a){this._set("required",a);dijit.setWaiState(this.focusNode,"required",a);this._refreshState()},_setMessageAttr:function(a){this._set("message",
a);this.displayMessage(a)},reset:function(){this._maskValidSubsetError=!0;this.inherited(arguments)},_onBlur:function(){this.displayMessage("");this.inherited(arguments)}}),dojo.declare("dijit.form.MappedTextBox",dijit.form.ValidationTextBox,{postMixInProperties:function(){this.inherited(arguments);this.nameAttrSetting=""},serialize:function(a){return a.toString?a.toString():""},toString:function(){var a=this.filter(this.get("value"));return a!=null?typeof a=="string"?a:this.serialize(a,this.constraints):
""},validate:function(){this.valueNode.value=this.toString();return this.inherited(arguments)},buildRendering:function(){this.inherited(arguments);this.valueNode=dojo.place("<input type='hidden'"+(this.name?" name='"+this.name.replace(/'/g,"&quot;")+"'":"")+"/>",this.textbox,"after")},reset:function(){this.valueNode.value="";this.inherited(arguments)}}),dojo.declare("dijit.form.RangeBoundTextBox",dijit.form.MappedTextBox,{rangeMessage:"",rangeCheck:function(a,b){return("min"in b?this.compare(a,b.min)>=
0:!0)&&("max"in b?this.compare(a,b.max)<=0:!0)},isInRange:function(){return this.rangeCheck(this.get("value"),this.constraints)},_isDefinitelyOutOfRange:function(){var a=this.get("value"),b=!1,c=!1;if("min"in this.constraints)b=this.constraints.min,b=this.compare(a,typeof b=="number"&&b>=0&&a!=0?0:b),b=typeof b=="number"&&b<0;if("max"in this.constraints)c=this.constraints.max,c=this.compare(a,typeof c!="number"||c>0?c:0),c=typeof c=="number"&&c>0;return b||c},_isValidSubset:function(){return this.inherited(arguments)&&
!this._isDefinitelyOutOfRange()},isValid:function(a){return this.inherited(arguments)&&(this._isEmpty(this.textbox.value)&&!this.required||this.isInRange(a))},getErrorMessage:function(a){var b=this.get("value");return b!==null&&b!==""&&b!==void 0&&(typeof b!="number"||!isNaN(b))&&!this.isInRange(a)?this.rangeMessage:this.inherited(arguments)},postMixInProperties:function(){this.inherited(arguments);if(!this.rangeMessage)this.messages=dojo.i18n.getLocalization("dijit.form","validate",this.lang),this.rangeMessage=
this.messages.rangeMessage},_setConstraintsAttr:function(a){this.inherited(arguments);this.focusNode&&(this.constraints.min!==void 0?dijit.setWaiState(this.focusNode,"valuemin",this.constraints.min):dijit.removeWaiState(this.focusNode,"valuemin"),this.constraints.max!==void 0?dijit.setWaiState(this.focusNode,"valuemax",this.constraints.max):dijit.removeWaiState(this.focusNode,"valuemax"))},_setValueAttr:function(a,b){dijit.setWaiState(this.focusNode,"valuenow",a);this.inherited(arguments)}}));