/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.cells._base"]||(dojo._hasResource["dojox.grid.cells._base"]=!0,dojo.provide("dojox.grid.cells._base"),dojo.require("dojox.grid.util"),dojo.require("dijit._Widget"),dojo.declare("dojox.grid._DeferredTextWidget",dijit._Widget,{deferred:null,_destroyOnRemove:!0,postCreate:function(){this.deferred&&this.deferred.addBoth(dojo.hitch(this,function(f){if(this.domNode)this.domNode.innerHTML=f}))}}),function(){var f=function(){setTimeout(dojo.hitch.apply(dojo,arguments),0)},e=
dojox.grid.cells;dojo.declare("dojox.grid.cells._Base",null,{styles:"",classes:"",editable:!1,alwaysEditing:!1,formatter:null,defaultValue:"...",value:null,hidden:!1,noresize:!1,draggable:!0,_valueProp:"value",_formatPending:!1,constructor:function(a){this._props=a||{};dojo.mixin(this,a);if(this.draggable===void 0)this.draggable=!0},_defaultFormat:function(a,b){var g;var c=this.grid.formatterScope||this,d=this.formatter;if(d&&c&&typeof d=="string")g=this.formatter=c[d],d=g;c=a!=this.defaultValue&&
d?d.apply(c,b):a;if(typeof c=="undefined")return this.defaultValue;c&&c.addBoth&&(c=new dojox.grid._DeferredTextWidget({deferred:c},dojo.create("span",{innerHTML:this.defaultValue})));return c&&c.declaredClass&&c.startup?"<div class='dojoxGridStubNode' linkWidget='"+c.id+"' cellIdx='"+this.index+"'>"+this.defaultValue+"</div>":c},format:function(a,b){var c=this.grid.edit.info,d=this.get?this.get(a,b):this.value||this.defaultValue,d=d&&d.replace&&this.grid.escapeHTMLInData?d.replace(/&/g,"&amp;").replace(/</g,
"&lt;"):d;return this.editable&&(this.alwaysEditing||c.rowIndex==a&&c.cell==this)?this.formatEditing(d,a):this._defaultFormat(d,[d,a,this])},formatEditing:function(){},getNode:function(a){return this.view.getCellNode(a,this.index)},getHeaderNode:function(){return this.view.getHeaderCellNode(this.index)},getEditNode:function(a){return(this.getNode(a)||0).firstChild||0},canResize:function(){var a=this.unitWidth;return a&&a!=="auto"},isFlex:function(){var a=this.unitWidth;return a&&dojo.isString(a)&&
(a=="auto"||a.slice(-1)=="%")},applyEdit:function(a,b){this.grid.edit.applyCellEdit(a,this,b)},cancelEdit:function(a){this.grid.doCancelEdit(a)},_onEditBlur:function(a){this.grid.edit.isEditCell(a,this.index)&&this.grid.edit.apply()},registerOnBlur:function(a,b){this.commitOnBlur&&dojo.connect(a,"onblur",function(){setTimeout(dojo.hitch(this,"_onEditBlur",b),250)})},needFormatNode:function(a,b){this._formatPending=!0;f(this,"_formatNode",a,b)},cancelFormatNode:function(){this._formatPending=!1},_formatNode:function(a,
b){if(this._formatPending)this._formatPending=!1,dojo.setSelectable(this.grid.domNode,!0),this.formatNode(this.getEditNode(b),a,b)},formatNode:function(a,b,c){dojo.isIE?f(this,"focus",c,a):this.focus(c,a)},dispatchEvent:function(a,b){if(a in this)return this[a](b)},getValue:function(a){return this.getEditNode(a)[this._valueProp]},setValue:function(a,b){var c=this.getEditNode(a);c&&(c[this._valueProp]=b)},focus:function(a,b){var c=b||this.getEditNode(a);try{dojox.grid.util.fire(c,"focus"),dojox.grid.util.fire(c,
"select")}catch(d){}},save:function(a){this.value=this.value||this.getValue(a)},restore:function(a){this.setValue(a,this.value)},_finish:function(){dojo.setSelectable(this.grid.domNode,!1);this.cancelFormatNode()},apply:function(a){this.applyEdit(this.getValue(a),a);this._finish(a)},cancel:function(a){this.cancelEdit(a);this._finish(a)}});e._Base.markupFactory=function(a,b){var c=dojo,d=c.trim(c.attr(a,"formatter")||"");if(d)b.formatter=dojo.getObject(d)||d;if(d=c.trim(c.attr(a,"get")||""))b.get=
dojo.getObject(d);d=function(b,d,e){var g=c.trim(c.attr(a,b)||"");g&&(d[e||b]=g.toLowerCase()!="false")};d("sortDesc",b);d("editable",b);d("alwaysEditing",b);d("noresize",b);d("draggable",b);if(d=c.trim(c.attr(a,"loadingText")||c.attr(a,"defaultValue")||""))b.defaultValue=d;d=function(b,d,e){var g=c.trim(c.attr(a,b)||"")||void 0;g&&(d[e||b]=g)};d("styles",b);d("headerStyles",b);d("cellStyles",b);d("classes",b);d("headerClasses",b);d("cellClasses",b)};dojo.declare("dojox.grid.cells.Cell",e._Base,{constructor:function(){this.keyFilter=
this.keyFilter},keyFilter:null,formatEditing:function(a,b){this.needFormatNode(a,b);return'<input class="dojoxGridInput" type="text" value="'+a+'">'},formatNode:function(a,b,c){this.inherited(arguments);this.registerOnBlur(a,c)},doKey:function(a){this.keyFilter&&String.fromCharCode(a.charCode).search(this.keyFilter)==-1&&dojo.stopEvent(a)},_finish:function(a){this.inherited(arguments);var b=this.getEditNode(a);try{dojox.grid.util.fire(b,"blur")}catch(c){}}});e.Cell.markupFactory=function(a,b){e._Base.markupFactory(a,
b);var c=dojo;if(c=c.trim(c.attr(a,"keyFilter")||""))b.keyFilter=RegExp(c)};dojo.declare("dojox.grid.cells.RowIndex",e.Cell,{name:"Row",postscript:function(){this.editable=!1},get:function(a){return a+1}});e.RowIndex.markupFactory=function(a,b){e.Cell.markupFactory(a,b)};dojo.declare("dojox.grid.cells.Select",e.Cell,{options:null,values:null,returnIndex:-1,constructor:function(){this.values=this.values||this.options},formatEditing:function(a,b){this.needFormatNode(a,b);for(var c=['<select class="dojoxGridSelect">'],
d=0,e,f;(e=this.options[d])!==void 0&&(f=this.values[d])!==void 0;d++)c.push("<option",a==f?" selected":"",' value="'+f+'"',">",e,"</option>");c.push("</select>");return c.join("")},getValue:function(a){var b=this.getEditNode(a);if(b)return a=b.selectedIndex,b=b.options[a],this.returnIndex>-1?a:b.value||b.innerHTML}});e.Select.markupFactory=function(a,b){e.Cell.markupFactory(a,b);var c=dojo,d=c.trim(c.attr(a,"options")||"");if(d){var f=d.split(",");if(f[0]!=d)b.options=f}if(c=c.trim(c.attr(a,"values")||
""))if(d=c.split(","),d[0]!=c)b.values=d};dojo.declare("dojox.grid.cells.AlwaysEdit",e.Cell,{alwaysEditing:!0,_formatNode:function(a,b){this.formatNode(this.getEditNode(b),a,b)},applyStaticValue:function(a){var b=this.grid.edit;b.applyCellEdit(this.getValue(a),this,a);b.start(this,a,!0)}});e.AlwaysEdit.markupFactory=function(a,b){e.Cell.markupFactory(a,b)};dojo.declare("dojox.grid.cells.Bool",e.AlwaysEdit,{_valueProp:"checked",formatEditing:function(a){return'<input class="dojoxGridInput" type="checkbox"'+
(a?' checked="checked"':"")+' style="width: auto" />'},doclick:function(a){a.target.tagName=="INPUT"&&this.applyStaticValue(a.rowIndex)}});e.Bool.markupFactory=function(a,b){e.AlwaysEdit.markupFactory(a,b)}}());