/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.cells.dijit"]||(dojo._hasResource["dojox.grid.cells.dijit"]=!0,dojo.provide("dojox.grid.cells.dijit"),dojo.require("dojox.grid.cells"),dojo.require("dijit.form.DateTextBox"),dojo.require("dijit.form.TimeTextBox"),dojo.require("dijit.form.ComboBox"),dojo.require("dojo.data.ItemFileReadStore"),dojo.require("dijit.form.CheckBox"),dojo.require("dijit.form.TextBox"),dojo.require("dijit.form.NumberSpinner"),dojo.require("dijit.form.NumberTextBox"),dojo.require("dijit.form.CurrencyTextBox"),
dojo.require("dijit.form.HorizontalSlider"),dojo.require("dijit.Editor"),function(){var d=dojox.grid.cells;dojo.declare("dojox.grid.cells._Widget",d._Base,{widgetClass:dijit.form.TextBox,constructor:function(){this.widget=null;if(typeof this.widgetClass=="string")dojo.deprecated("Passing a string to widgetClass is deprecated","pass the widget class object instead","2.0"),this.widgetClass=dojo.getObject(this.widgetClass)},formatEditing:function(a,b){this.needFormatNode(a,b);return"<div></div>"},getValue:function(){return this.widget.get("value")},
setValue:function(a,b){if(this.widget&&this.widget.set)if(this.widget.onLoadDeferred){var c=this;this.widget.onLoadDeferred.addCallback(function(){c.widget.set("value",b===null?"":b)})}else this.widget.set("value",b);else this.inherited(arguments)},getWidgetProps:function(a){return dojo.mixin({dir:this.dir,lang:this.lang},this.widgetProps||{},{constraints:dojo.mixin({},this.constraint)||{},value:a})},createWidget:function(a,b){return new this.widgetClass(this.getWidgetProps(b),a)},attachWidget:function(a,
b,c){a.appendChild(this.widget.domNode);this.setValue(c,b)},formatNode:function(a,b,c){if(!this.widgetClass)return b;this.widget?this.attachWidget.apply(this,arguments):this.widget=this.createWidget.apply(this,arguments);this.sizeWidget.apply(this,arguments);this.grid.views.renormalizeRow(c);this.grid.scroller.rowHeightChanged(c,!0);this.focus()},sizeWidget:function(a,b,c){a=this.getNode(c);a=dojo.contentBox(a);dojo.marginBox(this.widget.domNode,{w:a.w})},focus:function(){this.widget&&setTimeout(dojo.hitch(this.widget,
function(){dojox.grid.util.fire(this,"focus")}),0)},_finish:function(a){this.inherited(arguments);dojox.grid.util.removeNode(this.widget.domNode);dojo.isIE&&dojo.setSelectable(this.widget.domNode,!0)}});d._Widget.markupFactory=function(a,b){d._Base.markupFactory(a,b);var c=dojo,e=c.trim(c.attr(a,"widgetProps")||""),f=c.trim(c.attr(a,"constraint")||""),g=c.trim(c.attr(a,"widgetClass")||"");if(e)b.widgetProps=c.fromJson(e);if(f)b.constraint=c.fromJson(f);if(g)b.widgetClass=c.getObject(g)};dojo.declare("dojox.grid.cells.ComboBox",
d._Widget,{widgetClass:dijit.form.ComboBox,getWidgetProps:function(a){var b=[];dojo.forEach(this.options,function(a){b.push({name:a,value:a})});var c=new dojo.data.ItemFileReadStore({data:{identifier:"name",items:b}});return dojo.mixin({},this.widgetProps||{},{value:a,store:c})},getValue:function(){var a=this.widget;a.set("displayedValue",a.get("displayedValue"));return a.get("value")}});d.ComboBox.markupFactory=function(a,b){d._Widget.markupFactory(a,b);var c=dojo;if(c=c.trim(c.attr(a,"options")||
"")){var e=c.split(",");if(e[0]!=c)b.options=e}};dojo.declare("dojox.grid.cells.DateTextBox",d._Widget,{widgetClass:dijit.form.DateTextBox,setValue:function(a,b){this.widget?this.widget.set("value",new Date(b)):this.inherited(arguments)},getWidgetProps:function(a){return dojo.mixin(this.inherited(arguments),{value:new Date(a)})}});d.DateTextBox.markupFactory=function(a,b){d._Widget.markupFactory(a,b)};dojo.declare("dojox.grid.cells.CheckBox",d._Widget,{widgetClass:dijit.form.CheckBox,getValue:function(){return this.widget.checked},
setValue:function(a,b){this.widget&&this.widget.attributeMap.checked?this.widget.set("checked",b):this.inherited(arguments)},sizeWidget:function(){}});d.CheckBox.markupFactory=function(a,b){d._Widget.markupFactory(a,b)};dojo.declare("dojox.grid.cells.Editor",d._Widget,{widgetClass:dijit.Editor,getWidgetProps:function(){return dojo.mixin({},this.widgetProps||{},{height:this.widgetHeight||"100px"})},createWidget:function(a,b){var c=new this.widgetClass(this.getWidgetProps(b),a);dojo.connect(c,"onLoad",
dojo.hitch(this,"populateEditor"));return c},formatNode:function(a,b,c){this.content=b;this.inherited(arguments);if(dojo.isMoz){var d=this.widget;d.open();this.widgetToolbar&&dojo.place(d.toolbar.domNode,d.editingArea,"before")}},populateEditor:function(){this.widget.set("value",this.content);this.widget.placeCursorAtEnd()}});d.Editor.markupFactory=function(a,b){d._Widget.markupFactory(a,b);var c=dojo.trim(dojo.attr(a,"widgetHeight")||"");if(c)c!="auto"&&c.substr(-2)!="em"&&(c=parseInt(c,10)+"px"),
b.widgetHeight=c}}());