/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.plot2d.Bars"]||(dojo._hasResource["dojox.charting.plot2d.Bars"]=!0,dojo.provide("dojox.charting.plot2d.Bars"),dojo.require("dojox.charting.plot2d.common"),dojo.require("dojox.charting.plot2d.Base"),dojo.require("dojox.gfx.fx"),dojo.require("dojox.lang.utils"),dojo.require("dojox.lang.functional"),dojo.require("dojox.lang.functional.reversed"),function(){var p=dojox.lang.functional,i=dojox.lang.utils,q=dojox.charting.plot2d.common,v=p.lambda("item.purgeGroup()");dojo.declare("dojox.charting.plot2d.Bars",
dojox.charting.plot2d.Base,{defaultParams:{hAxis:"x",vAxis:"y",gap:0,animate:null},optionalParams:{minBarSize:1,maxBarSize:1,stroke:{},outline:{},shadow:{},fill:{},font:"",fontColor:""},constructor:function(a,b){this.opt=dojo.clone(this.defaultParams);i.updateWithObject(this.opt,b);i.updateWithPattern(this.opt,b,this.optionalParams);this.series=[];this.hAxis=this.opt.hAxis;this.vAxis=this.opt.vAxis;this.animate=this.opt.animate},getSeriesStats:function(){var a=q.collectSimpleStats(this.series),b;
a.hmin-=0.5;a.hmax+=0.5;b=a.hmin;a.hmin=a.vmin;a.vmin=b;b=a.hmax;a.hmax=a.vmax;a.vmax=b;return a},render:function(a,b){if(this.zoom&&!this.isDataDirty())return this.performZoom(a,b);this.dirty=this.isDirty();this.resetEvents();if(this.dirty){dojo.forEach(this.series,v);this._eventSeries={};this.cleanGroup();var f=this.group;p.forEachRev(this.series,function(a){a.cleanGroup(f)})}var k=this.chart.theme,g,i,r=this._hScaler.scaler.getTransformerFromModel(this._hScaler),w=this._vScaler.scaler.getTransformerFromModel(this._vScaler),
s=Math.max(0,this._hScaler.bounds.lower),l=r(s),x=this.events();g=q.calculateBarSize(this._vScaler.bounds.scale,this.opt);i=g.gap;g=g.size;for(var m=this.series.length-1;m>=0;--m){var d=this.series[m];if(!this.dirty&&!d.dirty)k.skip(),this._reconnectEvents(d.name);else{d.cleanGroup();for(var t=k.next("bar",[this.opt,d]),f=d.group,u=Array(d.data.length),e=0;e<d.data.length;++e){var c=d.data[e];if(c!==null){var h=typeof c=="number"?c:c.y,j=r(h),n=Math.abs(j-l),c=typeof c!="number"?k.addMixin(t,"bar",
c,!0):k.post(t,"bar");if(n>=1&&g>=1){var j={x:b.l+(h<s?j:l),y:a.height-b.b-w(e+1.5)+i,width:n,height:g},o=this._plotFill(c.series.fill,a,b),o=this._shapeFill(o,j),c=f.createRect(j).setFill(o).setStroke(c.series.stroke);d.dyn.fill=c.getFill();d.dyn.stroke=c.getStroke();x&&(h={element:"bar",index:e,run:d,shape:c,x:h,y:e+1.5},this._connectEvents(h),u[e]=h);this.animate&&this._animateBar(c,b.l+l,-n)}}}this._eventSeries[d.name]=u;d.dirty=!1}}this.dirty=!1;return this},_animateBar:function(a,b,f){dojox.gfx.fx.animateTransform(dojo.delegate({shape:a,
duration:1200,transform:[{name:"translate",start:[b-b/f,0],end:[0,0]},{name:"scale",start:[1/f,1],end:[1,1]},{name:"original"}]},this.animate)).play()}})}());