/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.plot2d.Bubble"]||(dojo._hasResource["dojox.charting.plot2d.Bubble"]=!0,dojo.provide("dojox.charting.plot2d.Bubble"),dojo.require("dojox.charting.plot2d.Base"),dojo.require("dojox.lang.functional"),function(){var o=dojox.lang.functional,m=dojox.lang.utils,q=dojox.charting.plot2d.common,r=o.lambda("item.purgeGroup()");dojo.declare("dojox.charting.plot2d.Bubble",dojox.charting.plot2d.Base,{defaultParams:{hAxis:"x",vAxis:"y",animate:null},optionalParams:{stroke:{},outline:{},
shadow:{},fill:{},font:"",fontColor:""},constructor:function(f,d){this.opt=dojo.clone(this.defaultParams);m.updateWithObject(this.opt,d);m.updateWithPattern(this.opt,d,this.optionalParams);this.series=[];this.hAxis=this.opt.hAxis;this.vAxis=this.opt.vAxis;this.animate=this.opt.animate},render:function(f,d){if(this.zoom&&!this.isDataDirty())return this.performZoom(f,d);this.resetEvents();if(this.dirty=this.isDirty()){dojo.forEach(this.series,r);this._eventSeries={};this.cleanGroup();var g=this.group;
o.forEachRev(this.series,function(a){a.cleanGroup(g)})}for(var h=this.chart.theme,m=this._hScaler.scaler.getTransformerFromModel(this._hScaler),s=this._vScaler.scaler.getTransformerFromModel(this._vScaler),t=this.events(),n=this.series.length-1;n>=0;--n){var c=this.series[n];if(!this.dirty&&!c.dirty)h.skip(),this._reconnectEvents(c.name);else if(c.cleanGroup(),c.data.length)if(typeof c.data[0]=="number")console.warn("dojox.charting.plot2d.Bubble: the data in the following series cannot be rendered as a bubble chart; ",
c);else{var i=h.next("circle",[this.opt,c]),g=c.group,j=dojo.map(c.data,function(a){return a?{x:m(a.x)+d.l,y:f.height-d.b-s(a.y),radius:this._vScaler.bounds.scale*(a.size/2)}:null},this),e=null,k=null,l=null;if(i.series.shadow&&(l=dojo.map(j,function(a){if(a!==null){var b=h.addMixin(i,"circle",a,!0).series.shadow,b=g.createCircle({cx:a.x+b.dx,cy:a.y+b.dy,r:a.radius}).setStroke(b).setFill(b.color);this.animate&&this._animateBubble(b,f.height-d.b,a.radius);return b}return null},this),l.length))c.dyn.shadow=
l[l.length-1].getStroke();if(i.series.outline&&(k=dojo.map(j,function(a){if(a!==null){var b=h.addMixin(i,"circle",a,!0),b=q.makeStroke(b.series.outline);b.width=2*b.width+i.series.stroke.width;b=g.createCircle({cx:a.x,cy:a.y,r:a.radius}).setStroke(b);this.animate&&this._animateBubble(b,f.height-d.b,a.radius);return b}return null},this),k.length))c.dyn.outline=k[k.length-1].getStroke();e=dojo.map(j,function(a){if(a!==null){var b=h.addMixin(i,"circle",a,!0),c={x:a.x-a.radius,y:a.y-a.radius,width:2*
a.radius,height:2*a.radius},e=this._plotFill(b.series.fill,f,d),e=this._shapeFill(e,c),b=g.createCircle({cx:a.x,cy:a.y,r:a.radius}).setFill(e).setStroke(b.series.stroke);this.animate&&this._animateBubble(b,f.height-d.b,a.radius);return b}return null},this);if(e.length)c.dyn.fill=e[e.length-1].getFill(),c.dyn.stroke=e[e.length-1].getStroke();if(t){var p=Array(e.length);dojo.forEach(e,function(a,b){if(a!==null){var d={element:"circle",index:b,run:c,shape:a,outline:k&&k[b]||null,shadow:l&&l[b]||null,
x:c.data[b].x,y:c.data[b].y,r:c.data[b].size/2,cx:j[b].x,cy:j[b].y,cr:j[b].radius};this._connectEvents(d);p[b]=d}},this);this._eventSeries[c.name]=p}else delete this._eventSeries[c.name];c.dirty=!1}else c.dirty=!1,h.skip()}this.dirty=!1;return this},_animateBubble:function(f,d,g){dojox.gfx.fx.animateTransform(dojo.delegate({shape:f,duration:1200,transform:[{name:"translate",start:[0,d],end:[0,0]},{name:"scale",start:[0,1/g],end:[1,1]},{name:"original"}]},this.animate)).play()}})}());