/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.plot2d.Candlesticks"]||(dojo._hasResource["dojox.charting.plot2d.Candlesticks"]=!0,dojo.provide("dojox.charting.plot2d.Candlesticks"),dojo.require("dojox.charting.plot2d.common"),dojo.require("dojox.charting.plot2d.Base"),dojo.require("dojox.lang.utils"),dojo.require("dojox.lang.functional"),dojo.require("dojox.lang.functional.reversed"),function(){var u=dojox.lang.functional,q=dojox.lang.utils,v=dojox.charting.plot2d.common,z=u.lambda("item.purgeGroup()");dojo.declare("dojox.charting.plot2d.Candlesticks",
dojox.charting.plot2d.Base,{defaultParams:{hAxis:"x",vAxis:"y",gap:2,animate:null},optionalParams:{minBarSize:1,maxBarSize:1,stroke:{},outline:{},shadow:{},fill:{},font:"",fontColor:""},constructor:function(d,b){this.opt=dojo.clone(this.defaultParams);q.updateWithObject(this.opt,b);q.updateWithPattern(this.opt,b,this.optionalParams);this.series=[];this.hAxis=this.opt.hAxis;this.vAxis=this.opt.vAxis;this.animate=this.opt.animate},collectStats:function(d){for(var b=dojo.delegate(v.defaultStats),g=0;g<
d.length;g++){var c=d[g];if(c.data.length){var a=b.vmin,r=b.vmax;(!("ymin"in c)||!("ymax"in c))&&dojo.forEach(c.data,function(a,d){if(a!==null){var c=a.x||d+1;b.hmin=Math.min(b.hmin,c);b.hmax=Math.max(b.hmax,c);b.vmin=Math.min(b.vmin,a.open,a.close,a.high,a.low);b.vmax=Math.max(b.vmax,a.open,a.close,a.high,a.low)}});if("ymin"in c)b.vmin=Math.min(a,c.ymin);if("ymax"in c)b.vmax=Math.max(r,c.ymax)}}return b},getSeriesStats:function(){var d=this.collectStats(this.series);d.hmin-=0.5;d.hmax+=0.5;return d},
render:function(d,b){if(this.zoom&&!this.isDataDirty())return this.performZoom(d,b);this.resetEvents();if(this.dirty=this.isDirty()){dojo.forEach(this.series,z);this._eventSeries={};this.cleanGroup();var g=this.group;u.forEachRev(this.series,function(a){a.cleanGroup(g)})}var c=this.chart.theme,a,r,q=this._hScaler.scaler.getTransformerFromModel(this._hScaler),m=this._vScaler.scaler.getTransformerFromModel(this._vScaler);m(Math.max(0,this._vScaler.bounds.lower));var A=this.events();a=v.calculateBarSize(this._hScaler.bounds.scale,
this.opt);r=a.gap;a=a.size;for(var t=this.series.length-1;t>=0;--t){var f=this.series[t];if(!this.dirty&&!f.dirty)c.skip(),this._reconnectEvents(f.name);else{f.cleanGroup();for(var B=c.next("candlestick",[this.opt,f]),g=f.group,w=Array(f.data.length),n=0;n<f.data.length;++n){var e=f.data[n];if(e!==null){var j=c.addMixin(B,"candlestick",e,!0),x=q(e.x||n+0.5)+b.l+r,k=d.height-b.b,h=m(e.open),i=m(e.close),p=m(e.high),o=m(e.low);if("mid"in e)var y=m(e.mid);if(o>p)var l=p,p=o,o=l;if(a>=1){var l=h>i,C=
{x1:a/2,x2:a/2,y1:k-p,y2:k-o},D={x:0,y:k-Math.max(h,i),width:a,height:Math.max(l?h-i:i-h,1)};shape=g.createGroup();shape.setTransform({dx:x,dy:0});var s=shape.createGroup();s.createLine(C).setStroke(j.series.stroke);s.createRect(D).setStroke(j.series.stroke).setFill(l?j.series.fill:"white");"mid"in e&&s.createLine({x1:j.series.stroke.width||1,x2:a-(j.series.stroke.width||1),y1:k-y,y2:k-y}).setStroke(l?"white":j.series.stroke);f.dyn.fill=j.series.fill;f.dyn.stroke=j.series.stroke;A&&(e={element:"candlestick",
index:n,run:f,shape:s,x:x,y:k-Math.max(h,i),cx:a/2,cy:k-Math.max(h,i)+Math.max(l?h-i:i-h,1)/2,width:a,height:Math.max(l?h-i:i-h,1),data:e},this._connectEvents(e),w[n]=e)}this.animate&&this._animateCandlesticks(shape,k-o,p-o)}}this._eventSeries[f.name]=w;f.dirty=!1}}this.dirty=!1;return this},_animateCandlesticks:function(d,b,g){dojox.gfx.fx.animateTransform(dojo.delegate({shape:d,duration:1200,transform:[{name:"translate",start:[0,b-b/g],end:[0,0]},{name:"scale",start:[1,1/g],end:[1,1]},{name:"original"}]},
this.animate)).play()}})}());