/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.plot2d.Pie"]||(dojo._hasResource["dojox.charting.plot2d.Pie"]=!0,dojo.provide("dojox.charting.plot2d.Pie"),dojo.require("dojox.charting.Element"),dojo.require("dojox.charting.axis2d.common"),dojo.require("dojox.charting.plot2d.common"),dojo.require("dojox.charting.plot2d._PlotEvents"),dojo.require("dojox.lang.functional"),dojo.require("dojox.lang.utils"),dojo.require("dojox.gfx"),function(){var i=dojox.lang.functional,A=dojox.lang.utils,t=dojox.charting.plot2d.common,
B=dojox.charting.axis2d.common,C=dojox.gfx,G=C.matrix;dojo.declare("dojox.charting.plot2d.Pie",[dojox.charting.Element,dojox.charting.plot2d._PlotEvents],{defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:20,labelStyle:"default",htmlLabels:!0,radGrad:"native",fanSize:5,startAngle:0},optionalParams:{radius:0,stroke:{},outline:{},shadow:{},fill:{},font:"",fontColor:"",labelWiring:{}},constructor:function(f,b){this.opt=dojo.clone(this.defaultParams);A.updateWithObject(this.opt,b);A.updateWithPattern(this.opt,
b,this.optionalParams);this.run=null;this.dyn=[]},clear:function(){this.dirty=!0;this.dyn=[];this.run=null;return this},setAxis:function(){return this},addSeries:function(f){this.run=f;return this},getSeriesStats:function(){return dojo.delegate(t.defaultStats)},initializeScalers:function(){return this},getRequiredColors:function(){return this.run?this.run.data.length:0},render:function(f,b){if(!this.dirty)return this;this.resetEvents();this.dirty=!1;this._eventSeries={};this.cleanGroup();var v=this.group,
d=this.chart.theme;if(!this.run||!this.run.data.length)return this;var g=(f.width-b.l-b.r)/2,c=(f.height-b.t-b.b)/2,h=Math.min(g,c),m="font"in this.opt?this.opt.font:d.axis.font,o=m?C.normalizedLength(C.splitFontString(m).size):0,y=G._degToRad(this.opt.startAngle),k=y,n,q,r,z,w=this.run.data,A=this.events();if(typeof w[0]=="number"){n=i.map(w,"x ? Math.max(x, 0) : 0");if(i.every(n,"<= 0"))return this;q=i.map(n,"/this",i.foldl(n,"+",0));this.opt.labels&&(r=dojo.map(q,function(a){return a>0?this._getLabel(a*
100)+"%":""},this))}else{n=i.map(w,"x ? Math.max(x.y, 0) : 0");if(i.every(n,"<= 0"))return this;q=i.map(n,"/this",i.foldl(n,"+",0));this.opt.labels&&(r=dojo.map(q,function(a,b){if(a<=0)return"";var l=w[b];return"text"in l?l.text:this._getLabel(a*100)+"%"},this))}var E=i.map(w,function(a){return a===null||typeof a=="number"?d.next("slice",[this.opt,this.run],!0):d.next("slice",[this.opt,this.run,a],!0)},this);this.opt.labels&&(n=i.foldl1(i.map(r,function(a,b){return dojox.gfx._base._getTextBox(a,{font:E[b].series.font}).w},
this),"Math.max(a, b)")/2,this.opt.labelOffset<0&&(h=Math.min(g-2*n,c-o)+this.opt.labelOffset),z=h-this.opt.labelOffset);if("radius"in this.opt)h=this.opt.radius,z=h-this.opt.labelOffset;var a={cx:b.l+g,cy:b.t+c,r:h};this.dyn=[];var F=Array(q.length);dojo.some(q,function(d,u){if(d<=0)return!1;var l=w[u],s=E[u],e;if(d>=1){e=this._plotFill(s.series.fill,f,b);e=this._shapeFill(e,{x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r});e=this._pseudoRadialFill(e,{x:a.cx,y:a.cy},a.r);var c=v.createCircle(a).setFill(e).setStroke(s.series.stroke);
this.dyn.push({fill:e,stroke:s.series.stroke});A&&(l={element:"slice",index:u,run:this.run,shape:c,x:u,y:typeof l=="number"?l:l.y,cx:a.cx,cy:a.cy,cr:h},this._connectEvents(l),F[u]=l);return!0}var g=k+d*2*Math.PI;u+1==q.length&&(g=y+2*Math.PI);var c=g-k,i=a.cx+h*Math.cos(k),m=a.cy+h*Math.sin(k),n=a.cx+h*Math.cos(g),o=a.cy+h*Math.sin(g);e=G._degToRad(this.opt.fanSize);if(s.series.fill&&s.series.fill.type==="radial"&&this.opt.radGrad==="fan"&&c>e){var r=v.createGroup(),t=Math.ceil(c/e),x=c/t;e=this._shapeFill(s.series.fill,
{x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r});for(var p=0;p<t;++p){var z=p==0?i:a.cx+h*Math.cos(k+(p-0.2)*x),B=p==0?m:a.cy+h*Math.sin(k+(p-0.2)*x),C=p==t-1?n:a.cx+h*Math.cos(k+(p+1+0.2)*x),D=p==t-1?o:a.cy+h*Math.sin(k+(p+1+0.2)*x);r.createPath({}).moveTo(a.cx,a.cy).lineTo(z,B).arcTo(h,h,0,x>Math.PI,!0,C,D).lineTo(a.cx,a.cy).closePath().setFill(this._pseudoRadialFill(e,{x:a.cx,y:a.cy},h,k+(p+0.5)*x,k+(p+0.5)*x))}r.createPath({}).moveTo(a.cx,a.cy).lineTo(i,m).arcTo(h,h,0,c>Math.PI,!0,n,o).lineTo(a.cx,
a.cy).closePath().setStroke(s.series.stroke);c=r}else c=v.createPath({}).moveTo(a.cx,a.cy).lineTo(i,m).arcTo(h,h,0,c>Math.PI,!0,n,o).lineTo(a.cx,a.cy).closePath().setStroke(s.series.stroke),(e=s.series.fill)&&e.type==="radial"?(e=this._shapeFill(e,{x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r}),this.opt.radGrad==="linear"&&(e=this._pseudoRadialFill(e,{x:a.cx,y:a.cy},h,k,g))):e&&e.type==="linear"&&(e=this._plotFill(e,f,b),e=this._shapeFill(e,c.getBoundingBox())),c.setFill(e);this.dyn.push({fill:e,
stroke:s.series.stroke});A&&(l={element:"slice",index:u,run:this.run,shape:c,x:u,y:typeof l=="number"?l:l.y,cx:a.cx,cy:a.cy,cr:h},this._connectEvents(l),F[u]=l);k=g;return!1},this);if(this.opt.labels)if(this.opt.labelStyle=="default")k=y,dojo.some(q,function(b,c){if(b<=0)return!1;var l=E[c];if(b>=1)return l=B.createText[this.opt.htmlLabels&&dojox.gfx.renderer!="vml"?"html":"gfx"](this.chart,v,a.cx,a.cy+o/2,"middle",r[c],l.series.font,l.series.fontColor),this.opt.htmlLabels&&this.htmlElements.push(l),
!0;var d=k+b*2*Math.PI;c+1==q.length&&(d=y+2*Math.PI);var e=(k+d)/2,l=B.createText[this.opt.htmlLabels&&dojox.gfx.renderer!="vml"?"html":"gfx"](this.chart,v,a.cx+z*Math.cos(e),a.cy+z*Math.sin(e)+o/2,"middle",r[c],l.series.font,l.series.fontColor);this.opt.htmlLabels&&this.htmlElements.push(l);k=d;return!1},this);else if(this.opt.labelStyle=="columns"){var k=y,D=[];dojo.forEach(q,function(a,b){var c=k+a*2*Math.PI;b+1==q.length&&(c=y+2*Math.PI);var d=(k+c)/2;D.push({angle:d,left:Math.cos(d)<0,theme:E[b],
index:b,omit:c-k<0.0010});k=c});g=dojox.gfx._base._getTextBox("a",{font:m}).h;this._getProperLabelRadius(D,g,a.r*1.1);dojo.forEach(D,function(b,c){if(!b.omit){var d=a.cx-a.r*2,f=a.cx+a.r*2,e=dojox.gfx._base._getTextBox(r[c],{font:m}).w,h=a.cx+b.labelR*Math.cos(b.angle),g=a.cy+b.labelR*Math.sin(b.angle),f=b.left?d+e:f-e,d=b.left?d:f,k=v.createPath().moveTo(a.cx+a.r*Math.cos(b.angle),a.cy+a.r*Math.sin(b.angle));Math.abs(b.labelR*Math.cos(b.angle))<a.r*2-e&&k.lineTo(h,g);k.lineTo(f,g).setStroke(b.theme.series.labelWiring);
e=B.createText[this.opt.htmlLabels&&dojox.gfx.renderer!="vml"?"html":"gfx"](this.chart,v,d,g,"left",r[c],b.theme.series.font,b.theme.series.fontColor);this.opt.htmlLabels&&this.htmlElements.push(e)}},this)}var t=0;this._eventSeries[this.run.name]=i.map(w,function(a){return a<=0?null:F[t++]});return this},_getProperLabelRadius:function(f,b,i){var d={},g={},c=1,h=1;if(f.length==1)f[0].labelR=i;else{for(var m=0;m<f.length;m++){var o=Math.abs(Math.sin(f[m].angle));f[m].left?c>o&&(c=o,d=f[m]):h>o&&(h=
o,g=f[m])}d.labelR=g.labelR=i;this._caculateLabelR(d,f,b);this._caculateLabelR(g,f,b)}},_caculateLabelR:function(f,b,i){for(var d=f.index,g=b.length,c=f.labelR;!(b[d%g].left^b[(d+1)%g].left);){if(!b[(d+1)%g].omit)c=(Math.sin(b[d%g].angle)*c+(b[d%g].left?-i:i))/Math.sin(b[(d+1)%g].angle),c=c<f.labelR?f.labelR:c,b[(d+1)%g].labelR=c;d++}d=f.index;for(j=d==0?g-1:d-1;!(b[d].left^b[j].left);){if(!b[j].omit)c=(Math.sin(b[d].angle)*c+(b[d].left?i:-i))/Math.sin(b[j].angle),c=c<f.labelR?f.labelR:c,b[j].labelR=
c;d--;j--;d=d<0?d+b.length:d;j=j<0?j+b.length:j}},_getLabel:function(f){return t.getLabel(f,this.opt.fixed,this.opt.precision)}})}());