/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.plot2d.Spider"]||(dojo._hasResource["dojox.charting.plot2d.Spider"]=!0,dojo.provide("dojox.charting.plot2d.Spider"),dojo.experimental("dojox.charting.plot2d.Spider"),dojo.require("dojox.charting.Element"),dojo.require("dojox.charting.plot2d._PlotEvents"),dojo.require("dojox.charting.axis2d.common"),dojo.require("dojox.charting.plot2d.common"),dojo.require("dojox.charting.scaler.primitive"),dojo.require("dojox.lang.functional"),dojo.require("dojox.lang.utils"),dojo.require("dojox.gfx"),
dojo.require("dojo.fx"),dojo.require("dojo.fx.easing"),dojo.require("dojox.gfx.fx"),function(){var K=dojox.lang.functional,E=dojox.lang.utils,H=dojox.charting.plot2d.common,L=dojox.charting.axis2d.common,F=dojox.gfx,M=F.matrix;dojo.declare("dojox.charting.plot2d.Spider",[dojox.charting.Element,dojox.charting.plot2d._PlotEvents],{defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:-10,labelStyle:"default",htmlLabels:!0,startAngle:-90,divisions:3,axisColor:"",axisWidth:0,spiderColor:"",
spiderWidth:0,seriesWidth:0,seriesFillAlpha:0.2,spiderOrigin:0.16,markerSize:3,spiderType:"polygon",animationType:dojo.fx.easing.backOut,axisTickFont:"",axisTickFontColor:"",axisFont:"",axisFontColor:""},optionalParams:{radius:0,font:"",fontColor:""},constructor:function(c,b){this.opt=dojo.clone(this.defaultParams);E.updateWithObject(this.opt,b);E.updateWithPattern(this.opt,b,this.optionalParams);this.series=[];this.dyn=[];this.datas={};this.labelKey=[];this.oldSeriePoints={};this.animations={}},
clear:function(){this.dirty=!0;this.dyn=[];this.series=[];this.datas={};this.labelKey=[];this.oldSeriePoints={};this.animations={};return this},setAxis:function(){return this},addSeries:function(c){this.series.push(c);for(var b in c.data){var e=c.data[b],d=this.datas[b];d?(d.vlist.push(e),d.min=Math.min(d.min,e),d.max=Math.max(d.max,e)):this.datas[b]={min:e,max:e,vlist:[e]}}if(this.labelKey.length<=0)for(b in c.data)this.labelKey.push(b);return this},getSeriesStats:function(){return dojox.charting.plot2d.common.collectSimpleStats(this.series)},
calculateAxes:function(c){this.initializeScalers(c,this.getSeriesStats());return this},getRequiredColors:function(){return this.series.length},initializeScalers:function(c,b){this._hAxis?(this._hAxis.initialized()||this._hAxis.calculate(b.hmin,b.hmax,c.width),this._hScaler=this._hAxis.getScaler()):this._hScaler=dojox.charting.scaler.primitive.buildScaler(b.hmin,b.hmax,c.width);this._vAxis?(this._vAxis.initialized()||this._vAxis.calculate(b.vmin,b.vmax,c.height),this._vScaler=this._vAxis.getScaler()):
this._vScaler=dojox.charting.scaler.primitive.buildScaler(b.vmin,b.vmax,c.height);return this},render:function(c,b){if(!this.dirty)return this;this.dirty=!1;this.cleanGroup();var e=this.group,d=this.chart.theme;this.resetEvents();if(!this.series||!this.series.length)return this;var a=this.opt,g=d.axis,f=(c.width-b.l-b.r)/2,j=(c.height-b.t-b.b)/2,k=Math.min(f,j),o=a.font||g.majorTick&&g.majorTick.font||g.tick&&g.tick.font||"normal normal normal 7pt Tahoma",i=a.axisFont||g.tick&&g.tick.titleFont||"normal normal normal 11pt Tahoma",
r=a.axisTickFontColor||g.majorTick&&g.majorTick.fontColor||g.tick&&g.tick.fontColor||"silver",A=a.axisFontColor||g.tick&&g.tick.titleFontColor||"black",t=a.axisColor||g.tick&&g.tick.axisColor||"silver",l=a.spiderColor||g.tick&&g.tick.spiderColor||"silver",N=a.axisWidth||g.stroke&&g.stroke.width||2,u=a.spiderWidth||g.stroke&&g.stroke.width||2,g=a.seriesWidth||g.stroke&&g.stroke.width||2,n=F.normalizedLength(F.splitFontString(i).size),z=M._degToRad(a.startAngle),I,p,G,q,x,v,s=a.spiderOrigin,y=a.divisions>=
3?a.divisions:3,E=a.markerSize,H=a.spiderType,O=a.animationType,h=a.labelOffset<-10?a.labelOffset:-10;a.labels&&(k=dojo.map(this.series,function(a){return a.name},this),k=K.foldl1(K.map(k,function(a){return dojox.gfx._base._getTextBox(a,{font:d.series.font}).w},this),"Math.max(a, b)")/2,k=Math.min(f-2*k,j-n)+h,I=k-h);if("radius"in a)k=a.radius,I=k-h;k/=1.2;f={cx:b.l+f,cy:b.t+j,r:k};for(j=this.series.length-1;j>=0;j--){var m=this.series[j];if(!this.dirty&&!m.dirty)d.skip();else if(m.cleanGroup(),h=
m.data,h!==null&&(n=this._getObjectLength(h),!p||p.length<=0))if(p=[],G=[],v=[],this._buildPoints(p,n,f,k,z,!0),this._buildPoints(G,n,f,k*s,z,!0),this._buildPoints(v,n,f,I,z),y>2){q=[];x=[];for(h=0;h<y-2;h++)q[h]=[],this._buildPoints(q[h],n,f,k*(s+(1-s)*(h+1)/(y-1)),z,!0),x[h]=k*(s+(1-s)*(h+1)/(y-1))}}j=e.createGroup();t={color:t,width:N};n={color:l,width:u};for(h=p.length-1;h>=0;--h)l=p[h],u={x:l.x+(l.x-f.cx)*0.2,y:l.y+(l.y-f.cy)*0.2},l={x:l.x+(l.x-f.cx)*0.2/2,y:l.y+(l.y-f.cy)*0.2/2},j.createLine({x1:f.cx,
y1:f.cy,x2:u.x,y2:u.y}).setStroke(t),this._drawArrow(j,u,l,t);j=e.createGroup();for(h=v.length-1;h>=0;--h)l=v[h],u=dojox.gfx._base._getTextBox(this.labelKey[h],{font:i}).w||0,t=this.opt.htmlLabels&&dojox.gfx.renderer!="vml"?"html":"gfx",elem=L.createText[t](this.chart,j,!dojo._isBodyLtr()&&t=="html"?l.x+u-c.width:l.x,l.y,"middle",this.labelKey[h],i,A),this.opt.htmlLabels&&this.htmlElements.push(elem);i=e.createGroup();if(H=="polygon"){if(i.createPolyline(p).setStroke(n),i.createPolyline(G).setStroke(n),
q.length>0)for(h=q.length-1;h>=0;--h)i.createPolyline(q[h]).setStroke(n)}else if(this._getObjectLength(this.datas),i.createCircle({cx:f.cx,cy:f.cy,r:k}).setStroke(n),i.createCircle({cx:f.cx,cy:f.cy,r:k*s}).setStroke(n),x.length>0)for(h=x.length-1;h>=0;--h)i.createCircle({cx:f.cx,cy:f.cy,r:x[h]}).setStroke(n);x=e.createGroup();n=this._getObjectLength(this.datas);p=0;for(var B in this.datas){i=this.datas[B];q=i.min;i=i.max;i-=q;A=z+2*Math.PI*p/n;for(j=0;j<y;j++)v=q+i*j/(y-1),l=this._getCoordinate(f,
k*(s+(1-s)*j/(y-1)),A),v=this._getLabel(v),u=dojox.gfx._base._getTextBox(v,{font:o}).w||0,t=this.opt.htmlLabels&&dojox.gfx.renderer!="vml"?"html":"gfx",this.opt.htmlLabels&&this.htmlElements.push(L.createText[t](this.chart,x,!dojo._isBodyLtr()&&t=="html"?l.x+u-c.width:l.x,l.y,"start",v,o,r));p++}this.chart.seriesShapes={};for(j=this.series.length-1;j>=0;j--)if(m=this.series[j],h=m.data,h!==null){var w=[];p=0;var C=[];for(B in h)i=this.datas[B],q=i.min,i=i.max,i-=q,o=h[B],A=z+2*Math.PI*p/n,l=this._getCoordinate(f,
k*(s+(1-s)*(o-q)/i),A),w.push(l),C.push({sname:m.name,key:B,data:o}),p++;w[w.length]=w[0];C[C.length]=C[0];var o=this._getBoundary(w),r=d.next("spider",[a,m]),J=m.group,D=F.normalizeColor(r.series.fill),r={color:r.series.fill,width:g};D.a=a.seriesFillAlpha;m.dyn={fill:D,stroke:r};r=this._createSeriesEntry(J,this.oldSeriePoints[m.name]||G,w,D,r,k,s,E,O);this.chart.seriesShapes[m.name]=r;this.oldSeriePoints[m.name]=w;this._connectEvents({element:"spider_poly",index:j,id:"spider_poly_"+m.name,run:m,
plot:this,shape:r.poly,parent:J,brect:o,cx:f.cx,cy:f.cy,cr:k,f:D,s:e});this._connectEvents({element:"spider_plot",index:j,id:"spider_plot_"+m.name,run:m,plot:this,shape:m.group});dojo.forEach(r.circles,function(a,b){a.getShape();this._connectEvents({element:"spider_circle",index:b,id:"spider_circle_"+m.name+b,run:m,plot:this,shape:a,parent:J,tdata:C[b],cx:w[b].x,cy:w[b].y,f:D,s:e})},this)}return this},_createSeriesEntry:function(c,b,e,d,a,g,f,j,k){for(var o=c.createPolyline(b).setFill(d).setStroke(a),
i=[],g=0;g<b.length;g++)f=b[g],f=c.createCircle({cx:f.x,cy:f.y,r:j}).setFill(d).setStroke(a),i.push(f);d=dojo.map(e,function(a,c){var d=new dojo._Animation({duration:1E3,easing:k,curve:[b[c].y,a.y]}),e=i[c];dojo.connect(d,"onAnimate",function(a){var b=o.getShape();b.points[c].y=a;o.setShape(b);b=e.getShape();b.cy=a;e.setShape(b)});return d});e=dojo.map(e,function(a,c){var d=new dojo._Animation({duration:1E3,easing:k,curve:[b[c].x,a.x]}),e=i[c];dojo.connect(d,"onAnimate",function(a){var b=o.getShape();
b.points[c].x=a;o.setShape(b);b=e.getShape();b.cx=a;e.setShape(b)});return d});dojo.fx.combine(d.concat(e)).play();return{group:c,poly:o,circles:i}},plotEvent:function(c){var b=c.id?c.id:"default";b in this.animations?(b=this.animations[b],b.anim&&b.anim.stop(!0)):b=this.animations[b]={};if(c.element=="spider_poly"){if(!b.color){var e=c.shape.getFill();if(!e||!(e instanceof dojo.Color))return;var d=b,a;a=(new dojox.color.Color(e)).toHsl();a.s==0?a.l=a.l<50?100:0:(a.s=100,a.l=a.l<50?75:a.l>75?50:a.l-
50>75-a.l?50:75);a=dojox.color.fromHsl(a);a.a=0.7;d.color={start:e,end:a}}e=b.color.start;d=b.color.end;c.type=="onmouseout"&&(a=e,e=d,d=a);b.anim=dojox.gfx.fx.animateFill({shape:c.shape,duration:800,easing:dojo.fx.easing.backOut,color:{start:e,end:d}});b.anim.play()}else c.element=="spider_circle"?(c.type=="onmouseover"?(e=1.5,d={type:"rect"},d.x=c.cx,d.y=c.cy,d.width=d.height=1,a=dojo.coords(this.chart.node,!0),d.x+=a.x,d.y+=a.y,d.x=Math.round(d.x),d.y=Math.round(d.y),d.width=Math.ceil(d.width),
d.height=Math.ceil(d.height),this.aroundRect=d,d=["after","before"],dijit&&dijit.Tooltip&&dijit.showTooltip(c.tdata.sname+"<br/>"+c.tdata.key+"<br/>"+c.tdata.data,this.aroundRect,d)):(dojox.gfx.matrix.scaleAt(1.5,c.cx,c.cy),e=1/1.5,dijit&&dijit.Tooltip&&this.aroundRect&&dijit.hideTooltip(this.aroundRect)),a=c.shape.getShape(),d=M.scaleAt(1.5,a.cx,a.cy),b.anim=dojox.gfx.fx.animateTransform({shape:c.shape,duration:200,easing:dojo.fx.easing.backOut,transform:[{name:"scaleAt",start:[1,a.cx,a.cy],end:[e,
a.cx,a.cy]},d]}),b.anim.play()):c.element=="spider_plot"&&c.type=="onmouseover"&&!dojo.isIE&&c.shape.moveToFront()},_getBoundary:function(c){for(var b=c[0].x,e=c[0].x,d=c[0].y,a=c[0].y,g=0;g<c.length;g++)var f=c[g],b=Math.max(f.x,b),d=Math.max(f.y,d),e=Math.min(f.x,e),a=Math.min(f.y,a);return{x:e,y:a,width:b-e,height:d-a}},_drawArrow:function(c,b,e,d){var a=Math.sqrt(Math.pow(e.x-b.x,2)+Math.pow(e.y-b.y,2)),g=(e.y-b.y)/a,f=(e.x-b.x)/a;c.createPolyline([b,{x:e.x+a/3*-g,y:e.y+a/3*f},{x:e.x+a/3*g,y:e.y+
a/3*-f}]).setFill(d.color).setStroke(d)},_buildPoints:function(c,b,e,d,a,g){for(var f=0;f<b;f++)c.push(this._getCoordinate(e,d,a+2*Math.PI*f/b));g&&c.push(this._getCoordinate(e,d,a+2*Math.PI))},_getCoordinate:function(c,b,e){return{x:c.cx+b*Math.cos(e),y:c.cy+b*Math.sin(e)}},_getObjectLength:function(c){var b=0;if(dojo.isObject(c))for(var e in c)b++;return b},_getLabel:function(c){return H.getLabel(c,this.opt.fixed,this.opt.precision)}})}());