/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.plot2d.StackedBars"]||(dojo._hasResource["dojox.charting.plot2d.StackedBars"]=!0,dojo.provide("dojox.charting.plot2d.StackedBars"),dojo.require("dojox.charting.plot2d.common"),dojo.require("dojox.charting.plot2d.Bars"),dojo.require("dojox.lang.functional"),dojo.require("dojox.lang.functional.reversed"),dojo.require("dojox.lang.functional.sequence"),function(){var j=dojox.lang.functional,o=dojox.charting.plot2d.common,t=j.lambda("item.purgeGroup()");dojo.declare("dojox.charting.plot2d.StackedBars",
dojox.charting.plot2d.Bars,{getSeriesStats:function(){var c=o.collectStackedStats(this.series),f;this._maxRunLength=c.hmax;c.hmin-=0.5;c.hmax+=0.5;f=c.hmin;c.hmin=c.vmin;c.vmin=f;f=c.hmax;c.hmax=c.vmax;c.vmax=f;return c},render:function(c,f){if(this._maxRunLength<=0)return this;for(var h=j.repeat(this._maxRunLength,"-> 0",0),g=0;g<this.series.length;++g)for(var d=this.series[g],b=0;b<d.data.length;++b){var a=d.data[b];if(a!==null){var e=typeof a=="number"?a:a.y;isNaN(e)&&(e=0);h[b]+=e}}if(this.zoom&&
!this.isDataDirty())return this.performZoom(c,f);this.resetEvents();if(this.dirty=this.isDirty()){dojo.forEach(this.series,t);this._eventSeries={};this.cleanGroup();var k=this.group;j.forEachRev(this.series,function(a){a.cleanGroup(k)})}var i=this.chart.theme,p,l,u=this._hScaler.scaler.getTransformerFromModel(this._hScaler),v=this._vScaler.scaler.getTransformerFromModel(this._vScaler),w=this.events(),g=o.calculateBarSize(this._vScaler.bounds.scale,this.opt);p=g.gap;l=g.size;for(g=this.series.length-
1;g>=0;--g)if(d=this.series[g],!this.dirty&&!d.dirty)i.skip(),this._reconnectEvents(d.name);else{d.cleanGroup();for(var q=i.next("bar",[this.opt,d]),k=d.group,r=Array(h.length),b=0;b<h.length;++b)if(a=d.data[b],a!==null){var e=h[b],m=u(e),a=typeof a!="number"?i.addMixin(q,"bar",a,!0):i.post(q,"bar");if(m>=1&&l>=1){var s={x:f.l,y:c.height-f.b-v(b+1.5)+p,width:m,height:l},n=this._plotFill(a.series.fill,c,f),n=this._shapeFill(n,s),a=k.createRect(s).setFill(n).setStroke(a.series.stroke);d.dyn.fill=a.getFill();
d.dyn.stroke=a.getStroke();w&&(e={element:"bar",index:b,run:d,shape:a,x:e,y:b+1.5},this._connectEvents(e),r[b]=e);this.animate&&this._animateBar(a,f.l,-m)}}this._eventSeries[d.name]=r;d.dirty=!1;for(b=0;b<d.data.length;++b)a=d.data[b],a!==null&&(e=typeof a=="number"?a:a.y,isNaN(e)&&(e=0),h[b]-=e)}this.dirty=!1;return this}})}());