/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit._base.manager"]||(dojo._hasResource["dijit._base.manager"]=!0,dojo.provide("dijit._base.manager"),dojo.declare("dijit.WidgetSet",null,{constructor:function(){this._hash={};this.length=0},add:function(c){if(this._hash[c.id])throw Error("Tried to register widget with id=="+c.id+" but that id is already registered");this._hash[c.id]=c;this.length++},remove:function(c){this._hash[c]&&(delete this._hash[c],this.length--)},forEach:function(c,b){var b=b||dojo.global,e=0,d;for(d in this._hash)c.call(b,
this._hash[d],e++,this._hash);return this},filter:function(c,b){var b=b||dojo.global,e=new dijit.WidgetSet,d=0,f;for(f in this._hash){var h=this._hash[f];c.call(b,h,d++,this._hash)&&e.add(h)}return e},byId:function(c){return this._hash[c]},byClass:function(c){var b=new dijit.WidgetSet,e,d;for(e in this._hash)d=this._hash[e],d.declaredClass==c&&b.add(d);return b},toArray:function(){var c=[],b;for(b in this._hash)c.push(this._hash[b]);return c},map:function(c,b){return dojo.map(this.toArray(),c,b)},
every:function(c,b){var b=b||dojo.global,e=0,d;for(d in this._hash)if(!c.call(b,this._hash[d],e++,this._hash))return!1;return!0},some:function(c,b){var b=b||dojo.global,e=0,d;for(d in this._hash)if(c.call(b,this._hash[d],e++,this._hash))return!0;return!1}}),function(){dijit.registry=new dijit.WidgetSet;var c=dijit.registry._hash,b=dojo.attr,e=dojo.hasAttr,d=dojo.style;dijit.byId=function(a){return typeof a=="string"?c[a]:a};var f={};dijit.getUniqueId=function(a){var b;do b=a+"_"+(a in f?++f[a]:f[a]=
0);while(c[b]);return dijit._scopeName=="dijit"?b:dijit._scopeName+"_"+b};dijit.findWidgets=function(a){function b(a){for(a=a.firstChild;a;a=a.nextSibling)if(a.nodeType==1){var e=a.getAttribute("widgetId");e?(e=c[e])&&d.push(e):b(a)}}var d=[];b(a);return d};dijit._destroyAll=function(){dijit._curFocus=null;dijit._prevFocus=null;dijit._activeStack=[];dojo.forEach(dijit.findWidgets(dojo.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})};dojo.isIE&&
dojo.addOnWindowUnload(function(){dijit._destroyAll()});dijit.byNode=function(a){return c[a.getAttribute("widgetId")]};dijit.getEnclosingWidget=function(a){for(;a;){var b=a.getAttribute&&a.getAttribute("widgetId");if(b)return c[b];a=a.parentNode}return null};var h=dijit._isElementShown=function(a){var c=d(a);return c.visibility!="hidden"&&c.visibility!="collapsed"&&c.display!="none"&&b(a,"type")!="hidden"};dijit.hasDefaultTabStop=function(a){switch(a.nodeName.toLowerCase()){case "a":return e(a,"href");
case "area":case "button":case "input":case "object":case "select":case "textarea":return!0;case "iframe":var b;try{var c=a.contentDocument;if("designMode"in c&&c.designMode=="on")return!0;b=c.body}catch(d){try{b=a.contentWindow.document.body}catch(f){return!1}}return b.contentEditable=="true"||b.firstChild&&b.firstChild.contentEditable=="true";default:return a.contentEditable=="true"}};var o=dijit.isTabNavigable=function(a){return b(a,"disabled")?!1:e(a,"tabIndex")?b(a,"tabIndex")>=0:dijit.hasDefaultTabStop(a)};
dijit._getTabNavigable=function(a){function c(a){return a&&a.tagName.toLowerCase()=="input"&&a.type&&a.type.toLowerCase()=="radio"&&a.name&&a.name.toLowerCase()}var d,f,j,l,k,m,i={},n=function(a){dojo.query("> *",a).forEach(function(a){if(!(dojo.isIE&&a.scopeName!=="HTML")&&h(a)){if(o(a)){var g=b(a,"tabIndex");if(!e(a,"tabIndex")||g==0)d||(d=a),f=a;else if(g>0){if(!j||g<l)l=g,j=a;if(!k||g>=m)m=g,k=a}g=c(a);dojo.attr(a,"checked")&&g&&(i[g]=a)}a.nodeName.toUpperCase()!="SELECT"&&n(a)}})};h(a)&&n(a);
return{first:i[c(d)]||d,last:i[c(f)]||f,lowest:i[c(j)]||j,highest:i[c(k)]||k}};dijit.getFirstInTabbingOrder=function(a){a=dijit._getTabNavigable(dojo.byId(a));return a.lowest?a.lowest:a.first};dijit.getLastInTabbingOrder=function(a){a=dijit._getTabNavigable(dojo.byId(a));return a.last?a.last:a.highest};dijit.defaultDuration=dojo.config.defaultDuration||200}());