/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dijit._base.popup"])dojo._hasResource["dijit._base.popup"]=!0,dojo.provide("dijit._base.popup"),dojo.require("dijit._base.focus"),dojo.require("dijit._base.place"),dojo.require("dijit._base.window"),dijit.popup={_stack:[],_beginZIndex:1E3,_idGen:1,_createWrapper:function(a){var b=a.declaredClass?a._popupWrapper:a.parentNode&&dojo.hasClass(a.parentNode,"dijitPopup"),c=a.domNode||a;if(!b&&(b=dojo.create("div",{"class":"dijitPopup",style:{display:"none"},role:"presentation"},dojo.body()),
b.appendChild(c),c=c.style,c.display="",c.visibility="",c.position="",c.top="0px",a.declaredClass))a._popupWrapper=b,dojo.connect(a,"destroy",function(){dojo.destroy(b);delete a._popupWrapper});return b},moveOffScreen:function(a){a=this._createWrapper(a);dojo.style(a,{visibility:"hidden",top:"-9999px",display:""})},hide:function(a){a=this._createWrapper(a);dojo.style(a,"display","none")},getTopPopup:function(){for(var a=this._stack,b=a.length-1;b>0&&a[b].parent===a[b-1].widget;b--);return a[b]},open:function(a){for(var b=
this._stack,c=a.popup,d=a.orient||((a.parent?a.parent.isLeftToRight():dojo._isBodyLtr())?{BL:"TL",BR:"TR",TL:"BL",TR:"BR"}:{BR:"TR",BL:"TL",TR:"BR",TL:"BL"}),e=a.around,g=a.around&&a.around.id?a.around.id+"_dropdown":"popup_"+this._idGen++;b.length&&(!a.parent||!dojo.isDescendant(a.parent.domNode,b[b.length-1].widget.domNode));)dijit.popup.close(b[b.length-1].widget);var f=this._createWrapper(c);dojo.attr(f,{id:g,style:{zIndex:this._beginZIndex+b.length},"class":"dijitPopup "+(c.baseClass||c["class"]||
"").split(" ")[0]+"Popup",dijitPopupParent:a.parent?a.parent.id:""});if((dojo.isIE||dojo.isMoz)&&!c.bgIframe)c.bgIframe=new dijit.BackgroundIframe(f);d=e?dijit.placeOnScreenAroundElement(f,e,d,c.orient?dojo.hitch(c,"orient"):null):dijit.placeOnScreen(f,a,d=="R"?["TR","BR","TL","BL"]:["TL","BL","TR","BR"],a.padding);f.style.display="";f.style.visibility="visible";c.domNode.style.visibility="visible";e=[];e.push(dojo.connect(f,"onkeypress",this,function(b){if(b.charOrCode==dojo.keys.ESCAPE&&a.onCancel)dojo.stopEvent(b),
a.onCancel();else if(b.charOrCode===dojo.keys.TAB&&(dojo.stopEvent(b),(b=this.getTopPopup())&&b.onCancel))b.onCancel()}));c.onCancel&&e.push(dojo.connect(c,"onCancel",a.onCancel));e.push(dojo.connect(c,c.onExecute?"onExecute":"onChange",this,function(){var a=this.getTopPopup();if(a&&a.onExecute)a.onExecute()}));b.push({widget:c,parent:a.parent,onExecute:a.onExecute,onCancel:a.onCancel,onClose:a.onClose,handlers:e});if(c.onOpen)c.onOpen(d);return d},close:function(a){for(var b=this._stack;a&&dojo.some(b,
function(b){return b.widget==a})||!a&&b.length;){var c=b.pop(),d=c.widget,e=c.onClose;if(d.onClose)d.onClose();dojo.forEach(c.handlers,dojo.disconnect);d&&d.domNode&&this.hide(d);e&&e()}}},dijit._frames=new function(){var a=[];this.pop=function(){var b;a.length?(b=a.pop(),b.style.display=""):(dojo.isIE<9?(b="<iframe src='"+(dojo.config.dojoBlankHtmlUrl||dojo.moduleUrl("dojo","resources/blank.html")+""||'javascript:""')+"' style='position: absolute; left: 0px; top: 0px;z-index: -1; filter:Alpha(Opacity=\"0\");'>",
b=dojo.doc.createElement(b)):(b=dojo.create("iframe"),b.src='javascript:""',b.className="dijitBackgroundIframe",dojo.style(b,"opacity",0.1)),b.tabIndex=-1,dijit.setWaiRole(b,"presentation"));return b};this.push=function(b){b.style.display="none";a.push(b)}},dijit.BackgroundIframe=function(a){if(!a.id)throw Error("no id");if(dojo.isIE||dojo.isMoz){var b=this.iframe=dijit._frames.pop();a.appendChild(b);dojo.isIE<7||dojo.isQuirks?(this.resize(a),this._conn=dojo.connect(a,"onresize",this,function(){this.resize(a)})):
dojo.style(b,{width:"100%",height:"100%"})}},dojo.extend(dijit.BackgroundIframe,{resize:function(a){this.iframe&&dojo.style(this.iframe,{width:a.offsetWidth+"px",height:a.offsetHeight+"px"})},destroy:function(){if(this._conn)dojo.disconnect(this._conn),this._conn=null;this.iframe&&(dijit._frames.push(this.iframe),delete this.iframe)}});