/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dijit._base.typematic"])dojo._hasResource["dijit._base.typematic"]=!0,dojo.provide("dijit._base.typematic"),dijit.typematic={_fireEventAndReload:function(){this._timer=null;this._callback(++this._count,this._node,this._evt);this._currentTimeout=Math.max(this._currentTimeout<0?this._initialDelay:this._subsequentDelay>1?this._subsequentDelay:Math.round(this._currentTimeout*this._subsequentDelay),this._minDelay);this._timer=setTimeout(dojo.hitch(this,"_fireEventAndReload"),this._currentTimeout)},
trigger:function(b,a,h,f,e,g,d,c){if(e!=this._obj)this.stop(),this._initialDelay=d||500,this._subsequentDelay=g||0.9,this._minDelay=c||10,this._obj=e,this._evt=b,this._node=h,this._count=this._currentTimeout=-1,this._callback=dojo.hitch(a,f),this._fireEventAndReload(),this._evt=dojo.mixin({faux:!0},b)},stop:function(){if(this._timer)clearTimeout(this._timer),this._timer=null;if(this._obj)this._callback(-1,this._node,this._evt),this._obj=null},addKeyListener:function(b,a,h,f,e,g,d){if(a.keyCode)a.charOrCode=
a.keyCode,dojo.deprecated("keyCode attribute parameter for dijit.typematic.addKeyListener is deprecated. Use charOrCode instead.","","2.0");else if(a.charCode)a.charOrCode=String.fromCharCode(a.charCode),dojo.deprecated("charCode attribute parameter for dijit.typematic.addKeyListener is deprecated. Use charOrCode instead.","","2.0");return[dojo.connect(b,"onkeypress",this,function(c){c.charOrCode==a.charOrCode&&(a.ctrlKey===void 0||a.ctrlKey==c.ctrlKey)&&(a.altKey===void 0||a.altKey==c.altKey)&&(a.metaKey===
void 0||a.metaKey==(c.metaKey||!1))&&(a.shiftKey===void 0||a.shiftKey==c.shiftKey)?(dojo.stopEvent(c),dijit.typematic.trigger(c,h,b,f,a,e,g,d)):dijit.typematic._obj==a&&dijit.typematic.stop()}),dojo.connect(b,"onkeyup",this,function(){dijit.typematic._obj==a&&dijit.typematic.stop()})]},addMouseListener:function(b,a,h,f,e,g){var d=dojo.connect;return[d(b,"mousedown",this,function(c){dojo.stopEvent(c);dijit.typematic.trigger(c,a,b,h,b,f,e,g)}),d(b,"mouseup",this,function(a){dojo.stopEvent(a);dijit.typematic.stop()}),
d(b,"mouseout",this,function(a){dojo.stopEvent(a);dijit.typematic.stop()}),d(b,"mousemove",this,function(a){a.preventDefault()}),d(b,"dblclick",this,function(c){dojo.stopEvent(c);dojo.isIE&&(dijit.typematic.trigger(c,a,b,h,b,f,e,g),setTimeout(dojo.hitch(this,dijit.typematic.stop),50))})]},addListener:function(b,a,h,f,e,g,d,c){return this.addKeyListener(a,h,f,e,g,d,c).concat(this.addMouseListener(b,f,e,g,d,c))}};