/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.drawing.tools.custom.Vector"]){dojo._hasResource["dojox.drawing.tools.custom.Vector"]=!0;dojo.provide("dojox.drawing.tools.custom.Vector");dojo.require("dojox.drawing.tools.Arrow");dojo.require("dojox.drawing.util.positioning");dojox.drawing.tools.custom.Vector=dojox.drawing.util.oo.declare(dojox.drawing.tools.Arrow,function(){this.minimumSize=this.style.arrows.length;this.addShadow({size:3,mult:2})},{draws:!0,type:"dojox.drawing.tools.custom.Vector",minimumSize:30,showAngle:!0,
changeAxis:function(a){a=a!==void 0?a:this.style.zAxis?0:1;if(a==0)this.style.zAxis=!1,this.data.cosphi=0;else{this.style.zAxis=!0;var a=this.points,b=this.zPoint();this.setPoints([{x:a[0].x,y:a[0].y},{x:b.x,y:b.y}])}this.render()},_createZeroVector:function(a,b,c){var b=a=="hit"?this.minimumSize:this.minimumSize/6,d=a=="hit"?c.fill:null,b={cx:this.data.x1,cy:this.data.y1,rx:b,ry:b};this.remove(this[a]);this[a]=this.container.createEllipse(b).setStroke(c).setFill(d);this.util.attr(this[a],"drawingType",
"stencil")},_create:function(a,b,c){this.remove(this[a]);this[a]=this.container.createLine(b).setStroke(c);this._setNodeAtts(this[a])},onDrag:function(a){if(!this.created){var b=a.start.x,c=a.start.y,d=a.x,e=a.y;if(this.keys.shift&&!this.style.zAxis)e=this.util.snapAngle(a,0.25),d=e.x,e=e.y;if(this.keys.alt){var f=d>b?(d-b)/2:(b-d)/-2,g=e>c?(e-c)/2:(c-e)/-2;b-=f;d-=f;c-=g;e-=g}if(this.style.zAxis)a=this.zPoint(a),d=a.x,e=a.y;this.setPoints([{x:b,y:c},{x:d,y:e}]);this.render()}},onTransform:function(){if(!this._isBeingModified)this.onTransformBegin();
this.setPoints(this.points);this.render()},anchorConstrain:function(a,b){if(!this.style.zAxis)return null;var c=this.style.zAngle*Math.PI/180,d=a<0?a>-b:a<-b;return{x:d?a:-b/Math.tan(c),y:!d?b:-Math.tan(c)*a}},zPoint:function(a){if(a===void 0){if(!this.points[0])return null;a=this.pointsToData();a={start:{x:a.x1,y:a.y1},x:a.x2,y:a.y2}}var b=this.util.length(a),c=this.util.angle(a);c<0&&(c=360+c);c=c>135&&c<315?this.style.zAngle:this.util.oppAngle(this.style.zAngle);return this.util.pointOnCircle(a.start.x,
a.start.y,b,c)},pointsToData:function(a){var a=a||this.points,b=0,c={start:{x:a[0].x,y:a[0].y},x:a[1].x,y:a[1].y};this.style.zAxis&&this.util.length(c)>this.minimumSize&&(b=this.util.angle(c),b<0&&(b=360+b),b=b>135&&b<315?1:-1);return this.data={x1:a[0].x,y1:a[0].y,x2:a[1].x,y2:a[1].y,cosphi:b}},dataToPoints:function(a){a=a||this.data;if(a.radius||a.angle){var b=0,c=this.util.pointOnCircle(a.x,a.y,a.radius,a.angle);if(this.style.zAxis||a.cosphi&&a.cosphi!=0)this.style.zAxis=!0,b=a.angle>135&&a.angle<
315?1:-1;this.data=a={x1:a.x,y1:a.y,x2:c.x,y2:c.y,cosphi:b}}return this.points=[{x:a.x1,y:a.y1},{x:a.x2,y:a.y2}]},render:function(){this.onBeforeRender(this);this.getRadius()>=this.minimumSize?(this._create("hit",this.data,this.style.currentHit),this._create("shape",this.data,this.style.current)):(this.data.cosphi=0,this._createZeroVector("hit",this.data,this.style.currentHit),this._createZeroVector("shape",this.data,this.style.current))},onUp:function(a){if(!this.created&&this._downOnCanvas){this._downOnCanvas=
!1;if(!this.shape)a.start.x=this.style.zAxis?a.start.x+100:a.start.x,a.y+=100,this.setPoints([{x:a.start.x,y:a.start.y},{x:a.x,y:a.y}]),this.render();if(this.getRadius()<this.minimumSize){var b=this.points;this.setPoints([{x:b[0].x,y:b[0].y},{x:b[0].x,y:b[0].y}])}else b=this.points,a=this.style.zAxis?this.zPoint(a):this.util.snapAngle(a,this.angleSnap/180),this.setPoints([{x:b[0].x,y:b[0].y},{x:a.x,y:a.y}]);this.renderedOnce=!0;this.onRender(this)}}});dojox.drawing.tools.custom.Vector.setup={name:"dojox.drawing.tools.custom.Vector",
tooltip:"Vector Tool",iconClass:"iconVector"};if(dojox.drawing.defaults.zAxisEnabled)dojox.drawing.tools.custom.Vector.setup.secondary={name:"vectorSecondary",label:"z-axis",funct:function(a){a.selected?this.zDeselect(a):this.zSelect(a);var a=this.drawing.stencils.selectedStencils,b;for(b in a)if(a[b].shortType=="vector"&&a[b].style.zAxis!=dojox.drawing.defaults.zAxis){var c=a[b];c.changeAxis();c.style.zAxis&&(c.deselect(),c.select())}},setup:function(){var a=dojox.drawing.defaults.zAxis;this.zSelect=
function(b){if(b.enabled)a=!0,dojox.drawing.defaults.zAxis=!0,b.select(),this.vectorTest(),this.zSelected=b};this.zDeselect=function(b){if(b.enabled)a=!1,dojox.drawing.defaults.zAxis=!1,b.deselect(),this.vectorTest(),this.zSelected=null};this.vectorTest=function(){dojo.forEach(this.buttons,function(b){if(b.toolType=="vector"&&b.selected)this.drawing.currentStencil.style.zAxis=a},this)};dojo.connect(this,"onRenderStencil",this,function(){this.zSelected&&this.zDeselect(this.zSelected)});var b=dojo.connect(this.drawing,
"onSurfaceReady",this,function(){dojo.disconnect(b);dojo.connect(this.drawing.stencils,"onSelect",this,function(a){a.shortType=="vector"&&(a.style.zAxis?dojo.forEach(this.buttons,function(a){a.toolType=="vectorSecondary"&&this.zSelect(a)},this):dojo.forEach(this.buttons,function(a){a.toolType=="vectorSecondary"&&this.zDeselect(a)},this))})})},postSetup:function(a){dojo.connect(a,"enable",function(){dojox.drawing.defaults.zAxisEnabled=!0});dojo.connect(a,"disable",function(){dojox.drawing.defaults.zAxisEnabled=
!1})}};dojox.drawing.register(dojox.drawing.tools.custom.Vector.setup,"tool")};