/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.cometd._base"])dojo._hasResource["dojox.cometd._base"]=!0,dojo.provide("dojox.cometd._base"),dojo.require("dojo.AdapterRegistry"),dojox.cometd={Connection:function(i){dojo.mixin(this,{prefix:i,_status:"unconnected",_handshook:!1,_initialized:!1,_polling:!1,expectedNetworkDelay:1E4,connectTimeout:0,version:"1.0",minimumVersion:"0.9",clientId:null,messageId:0,batch:0,_isXD:!1,handshakeReturn:null,currentTransport:null,url:null,lastMessage:null,_messageQ:[],handleAs:"json",
_advice:{},_backoffInterval:0,_backoffIncrement:1E3,_backoffMax:6E4,_deferredSubscribes:{},_deferredUnsubscribes:{},_subscriptions:[],_extendInList:[],_extendOutList:[]});this.state=function(){return this._status};this.init=function(a,b,d){b=b||{};b.version=this.version;b.minimumVersion=this.minimumVersion;b.channel="/meta/handshake";b.id=""+this.messageId++;this.url=a||dojo.config.cometdRoot;if(!this.url)throw"no cometd root";var c=(""+window.location).match(/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/);
if(c[4]){var c=c[4].split(":"),a=c[0],g=c[1]||"80",c=this.url.match(/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/);if(c[4]){var c=c[4].split(":"),e=c[1]||"80";this._isXD=c[0]!=a||e!=g}}if(!this._isXD)b.supportedConnectionTypes=dojo.map(dojox.cometd.connectionTypes.pairs,"return item[0]");b=this._extendOut(b);a={url:this.url,handleAs:this.handleAs,content:{message:dojo.toJson([b])},load:dojo.hitch(this,function(a){this._backon();this._finishInit(a)}),error:dojo.hitch(this,function(a){this._backoff();
this._finishInit(a)}),timeout:this.expectedNetworkDelay};d&&dojo.mixin(a,d);this._props=b;for(var f in this._subscriptions)for(var h in this._subscriptions[f])this._subscriptions[f][h].topic&&dojo.unsubscribe(this._subscriptions[f][h].topic);this._messageQ=[];this._subscriptions=[];this._initialized=!0;this._status="handshaking";this.batch=0;this.startBatch();this._isXD?(a.callbackParamName="jsonp",b=dojo.io.script.get(a)):b=dojo.xhrPost(a);return b};this.publish=function(a,b,d){a={data:b,channel:a};
d&&dojo.mixin(a,d);this._sendMessage(a)};this.subscribe=function(a,b,d,c){c=c||{};if(b){var g=i+a,e=this._subscriptions[g];if(!e||e.length==0){e=[];c.channel="/meta/subscribe";c.subscription=a;this._sendMessage(c);var f=this._deferredSubscribes;f[a]&&(f[a].cancel(),delete f[a]);f[a]=new dojo.Deferred}for(var h in e)if(e[h].objOrFunc===b&&(!e[h].funcName&&!d||e[h].funcName==d))return null;f=dojo.subscribe(g,b,d);e.push({topic:f,objOrFunc:b,funcName:d});this._subscriptions[g]=e}g=this._deferredSubscribes[a]||
{};g.args=dojo._toArray(arguments);return g};this.unsubscribe=function(a,b,d,c){if(arguments.length==1&&!dojo.isString(a)&&a.args)return this.unsubscribe.apply(this,a.args);var g=i+a,e=this._subscriptions[g];if(!e||e.length==0)return null;var f=0,h;for(h in e){var j=e[h];!b||j.objOrFunc===b&&(!j.funcName&&!d||j.funcName==d)?(dojo.unsubscribe(e[h].topic),delete e[h]):f++}if(f==0)c=c||{},c.channel="/meta/unsubscribe",c.subscription=a,delete this._subscriptions[g],this._sendMessage(c),this._deferredUnsubscribes[a]=
new dojo.Deferred,this._deferredSubscribes[a]&&(this._deferredSubscribes[a].cancel(),delete this._deferredSubscribes[a]);return this._deferredUnsubscribes[a]};this.disconnect=function(){for(var a in this._subscriptions)for(var b in this._subscriptions[a])this._subscriptions[a][b].topic&&dojo.unsubscribe(this._subscriptions[a][b].topic);this._subscriptions=[];this._messageQ=[];if(this._initialized&&this.currentTransport)this._initialized=!1,this.currentTransport.disconnect();this._polling||this._publishMeta("connect",
!1);this._handshook=this._initialized=!1;this._status="disconnected";this._publishMeta("disconnect",!0)};this.subscribed=function(){};this.unsubscribed=function(){};this.tunnelInit=function(){};this.tunnelCollapse=function(){};this._backoff=function(){if(this._advice){if(!this._advice.interval)this._advice.interval=0}else this._advice={reconnect:"retry",interval:0};this._backoffInterval<this._backoffMax&&(this._backoffInterval+=this._backoffIncrement)};this._backon=function(){this._backoffInterval=
0};this._interval=function(){var a=this._backoffInterval+(this._advice?this._advice.interval?this._advice.interval:0:0);a>0&&console.log("Retry in interval+backoff="+this._advice.interval+"+"+this._backoffInterval+"="+a+"ms");return a};this._publishMeta=function(a,b,d){try{var c={cometd:this,action:a,successful:b,state:this.state()};d&&dojo.mixin(c,d);dojo.publish(this.prefix+"/meta",[c])}catch(g){console.log(g)}};this._finishInit=function(a){if(this._status=="handshaking"){var b=this._handshook,
d=!1,c={};if(a instanceof Error)dojo.mixin(c,{reestablish:!1,failure:!0,error:a,advice:this._advice});else{a=a[0];this.handshakeReturn=a=this._extendIn(a);if(a.advice)this._advice=a.advice;d=a.successful?a.successful:!1;if(a.version<this.minimumVersion)console.log&&console.log("cometd protocol version mismatch. We wanted",this.minimumVersion,"but got",a.version),d=!1,this._advice.reconnect="none";dojo.mixin(c,{reestablish:d&&b,response:a})}this._publishMeta("handshake",d,c);if(this._status=="handshaking")d?
(this._status="connecting",this._handshook=!0,b=this.currentTransport=dojox.cometd.connectionTypes.match(a.supportedConnectionTypes,a.version,this._isXD),b._cometd=this,b.version=a.version,this.clientId=a.clientId,this.tunnelInit=b.tunnelInit&&dojo.hitch(b,"tunnelInit"),this.tunnelCollapse=b.tunnelCollapse&&dojo.hitch(b,"tunnelCollapse"),b.startup(a)):(!this._advice||this._advice.reconnect!="none")&&setTimeout(dojo.hitch(this,"init",this.url,this._props),this._interval())}};this._extendIn=function(a){dojo.forEach(dojox.cometd._extendInList,
function(b){a=b(a)||a});return a};this._extendOut=function(a){dojo.forEach(dojox.cometd._extendOutList,function(b){a=b(a)||a});return a};this.deliver=function(a){dojo.forEach(a,this._deliver,this);return a};this._deliver=function(a){a=this._extendIn(a);if(a.channel||a.success===!0){this.lastMessage=a;if(a.advice)this._advice=a.advice;var b=null;if(a.channel&&a.channel.length>5&&a.channel.substr(0,5)=="/meta")switch(a.channel){case "/meta/connect":b={response:a};if(a.successful&&this._status!="connected")this._status=
"connected",this.endBatch();this._initialized&&this._publishMeta("connect",a.successful,b);break;case "/meta/subscribe":b=this._deferredSubscribes[a.subscription];try{if(!a.successful){b&&b.errback(Error(a.error));this.currentTransport.cancelConnect();return}b&&b.callback(!0);this.subscribed(a.subscription,a)}catch(d){log.warn(d)}break;case "/meta/unsubscribe":b=this._deferredUnsubscribes[a.subscription];try{if(!a.successful){b&&b.errback(Error(a.error));this.currentTransport.cancelConnect();return}b&&
b.callback(!0);this.unsubscribed(a.subscription,a)}catch(c){log.warn(c)}break;default:if(a.successful&&!a.successful){this.currentTransport.cancelConnect();return}}this.currentTransport.deliver(a);if(a.data)try{for(var b=[a],g=i+a.channel,e=a.channel.split("/"),a=i,f=1;f<e.length-1;f++)dojo.publish(a+"/**",b),a+="/"+e[f];dojo.publish(a+"/**",b);dojo.publish(a+"/*",b);dojo.publish(g,b)}catch(h){console.log(h)}}};this._sendMessage=function(a){return this.currentTransport&&!this.batch?this.currentTransport.sendMessages([a]):
(this._messageQ.push(a),null)};this.startBatch=function(){this.batch++};this.endBatch=function(){if(--this.batch<=0&&this.currentTransport&&this._status=="connected"){this.batch=0;var a=this._messageQ;this._messageQ=[];a.length>0&&this.currentTransport.sendMessages(a)}};this._onUnload=function(){dojo.addOnUnload(dojox.cometd,"disconnect")};this._connectTimeout=function(){var a=0;this._advice&&this._advice.timeout&&this.expectedNetworkDelay>0&&(a=this._advice.timeout+this.expectedNetworkDelay);return this.connectTimeout>
0&&this.connectTimeout<a?this.connectTimeout:a}},connectionTypes:new dojo.AdapterRegistry(!0)},dojox.cometd.Connection.call(dojox.cometd,"/cometd"),dojo.addOnUnload(dojox.cometd,"_onUnload");