/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.widget.Chart"]||(dojo._hasResource["dojox.charting.widget.Chart"]=!0,dojo.provide("dojox.charting.widget.Chart"),dojo.require("dijit._Widget"),dojo.require("dojox.charting.Chart"),dojo.require("dojox.lang.functional"),function(){var i,l,m,n,o,j=function(b){return b},p=dojox.lang.functional,k=dojox.lang.utils,h=dojox.charting,g=dojo;dojo.declare("dojox.charting.widget.Chart",dijit._Widget,{theme:null,margins:null,stroke:null,fill:null,buildRendering:function(){var b=
this.domNode=this.srcNodeRef,d=g.query("> .axis",b).map(l).filter(j),c=g.query("> .plot",b).map(m).filter(j),a=g.query("> .action",b).map(n).filter(j),e=g.query("> .series",b).map(o).filter(j);b.innerHTML="";var f=this.chart=new h.Chart(b,{margins:this.margins,stroke:this.stroke,fill:this.fill});this.theme&&f.setTheme(this.theme);d.forEach(function(a){f.addAxis(a.name,a.kwArgs)});c.forEach(function(a){f.addPlot(a.name,a.kwArgs)});this.actions=a.map(function(a){return new a.action(f,a.plot,a.kwArgs)});
p.foldl(e,function(a,b){if(b.type=="data")f.addSeries(b.name,b.data,b.kwArgs),a=!0;else{f.addSeries(b.name,[0],b.kwArgs);var c={};k.updateWithPattern(c,b.kwArgs,{query:"",queryOptions:null,start:0,count:1},!0);if(b.kwArgs.sort)c.sort=dojo.clone(b.kwArgs.sort);g.mixin(c,{onComplete:function(a){if("valueFn"in b.kwArgs)var c=b.kwArgs.valueFn,a=g.map(a,function(a){return c(b.data.getValue(a,b.field,0))});else a=g.map(a,function(a){return b.data.getValue(a,b.field,0)});f.addSeries(b.name,a,b.kwArgs).render()}});
b.data.fetch(c)}return a},!1)&&f.render()},destroy:function(){this.chart.destroy();this.inherited(arguments)},resize:function(b){this.chart.resize(b)}});i=function(b,d,c){var a=eval("("+d+".prototype.defaultParams)"),e,f;for(e in a)e in c||(f=b.getAttribute(e),c[e]=k.coerceType(a[e],f==null||typeof f=="undefined"?a[e]:f));d=eval("("+d+".prototype.optionalParams)");for(e in d)e in c||(f=b.getAttribute(e),f!=null&&(c[e]=k.coerceType(d[e],f)))};l=function(b){var d=b.getAttribute("name"),c=b.getAttribute("type");
if(!d)return null;var d={name:d,kwArgs:{}},a=d.kwArgs;if(c){h.axis2d[c]&&(c=dojox._scopeName+".charting.axis2d."+c);var e=eval("("+c+")");if(e)a.type=e}else c=dojox._scopeName+".charting.axis2d.Default";i(b,c,a);if(a.font||a.fontColor){if(!a.tick)a.tick={};if(a.font)a.tick.font=a.font;if(a.fontColor)a.tick.fontColor=a.fontColor}return d};m=function(b){var d=b.getAttribute("name"),c=b.getAttribute("type");if(!d)return null;var d={name:d,kwArgs:{}},a=d.kwArgs;if(c){h.plot2d&&h.plot2d[c]&&(c=dojox._scopeName+
".charting.plot2d."+c);var e=eval("("+c+")");if(e)a.type=e}else c=dojox._scopeName+".charting.plot2d.Default";i(b,c,a);return d};n=function(b){var d=b.getAttribute("plot"),c=b.getAttribute("type");d||(d="default");var d={plot:d,kwArgs:{}},a=d.kwArgs;if(c){h.action2d[c]&&(c=dojox._scopeName+".charting.action2d."+c);var e=eval("("+c+")");if(!e)return null;d.action=e}else return null;i(b,c,a);return d};o=function(b){var b=g.partial(g.attr,b),d=b("name");if(!d)return null;var d={name:d,kwArgs:{}},c=d.kwArgs,
a;a=b("plot");if(a!=null)c.plot=a;a=b("marker");if(a!=null)c.marker=a;a=b("stroke");if(a!=null)c.stroke=eval("("+a+")");a=b("outline");if(a!=null)c.outline=eval("("+a+")");a=b("shadow");if(a!=null)c.shadow=eval("("+a+")");a=b("fill");if(a!=null)c.fill=eval("("+a+")");a=b("font");if(a!=null)c.font=a;a=b("fontColor");if(a!=null)c.fontColor=eval("("+a+")");a=b("legend");if(a!=null)c.legend=a;a=b("data");if(a!=null)return d.type="data",d.data=a?dojo.map(String(a).split(","),Number):[],d;a=b("array");
if(a!=null)return d.type="data",d.data=eval("("+a+")"),d;a=b("store");if(a!=null){d.type="store";d.data=eval("("+a+")");a=b("field");d.field=a!=null?a:"value";if(a=b("query"))c.query=a;if(a=b("queryOptions"))c.queryOptions=eval("("+a+")");if(a=b("start"))c.start=Number(a);if(a=b("count"))c.count=Number(a);if(a=b("sort"))c.sort=eval("("+a+")");if(a=b("valueFn"))c.valueFn=p.lambda(a);return d}return null}}());