/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.widget.Legend"]||(dojo._hasResource["dojox.charting.widget.Legend"]=!0,dojo.provide("dojox.charting.widget.Legend"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dojox.lang.functional.array"),dojo.require("dojox.lang.functional.fold"),dojo.declare("dojox.charting.widget.Legend",[dijit._Widget,dijit._Templated],{chartRef:"",horizontal:!0,swatchSize:18,templateString:"<table dojoAttachPoint='legendNode' class='dojoxLegendNode' role='group' aria-label='chart legend'><tbody dojoAttachPoint='legendBody'></tbody></table>",
legendNode:null,legendBody:null,postCreate:function(){if(this.chart)this.series=this.chart.series;else{if(!this.chartRef)return;this.chart=dijit.byId(this.chartRef);if(!this.chart){var c=dojo.byId(this.chartRef);if(c)this.chart=dijit.byNode(c);else{console.log("Could not find chart instance with id: "+this.chartRef);return}}this.series=this.chart.chart.series}this.refresh()},refresh:function(){var c=dojox.lang.functional;this._surfaces&&dojo.forEach(this._surfaces,function(a){a.destroy()});for(this._surfaces=
[];this.legendBody.lastChild;)dojo.destroy(this.legendBody.lastChild);if(this.horizontal)dojo.addClass(this.legendNode,"dojoxLegendHorizontal"),this._tr=dojo.create("tr",null,this.legendBody),this._inrow=0;var b=this.series;if(b.length!=0)if(b[0].chart.stack[0].declaredClass=="dojox.charting.plot2d.Pie"){var a=b[0].chart.stack[0];typeof a.run.data[0]=="number"?(b=c.map(a.run.data,"Math.max(x, 0)"),c.every(b,"<= 0")||(c=c.map(b,"/this",c.foldl(b,"+",0)),dojo.forEach(c,function(b,c){this._addLabel(a.dyn[c],
a._getLabel(b*100)+"%")},this))):dojo.forEach(a.run.data,function(b,c){this._addLabel(a.dyn[c],b.legend||b.text||b.y)},this)}else dojo.forEach(b,function(a){this._addLabel(a.dyn,a.legend||a.name)},this)},_addLabel:function(c,b){var a=dojo.create("td"),d=dojo.create("div",null,a),e=dojo.create("label",null,a),f=dojo.create("div",{style:{width:this.swatchSize+"px",height:this.swatchSize+"px","float":"left"}},d);dojo.addClass(d,"dojoxLegendIcon dijitInline");dojo.addClass(e,"dojoxLegendText");if(this._tr){if(this._tr.appendChild(a),
++this._inrow===this.horizontal)this._tr=dojo.create("tr",null,this.legendBody),this._inrow=0}else dojo.create("tr",null,this.legendBody).appendChild(a);this._makeIcon(f,c);e.innerHTML=String(b)},_makeIcon:function(c,b){var a={h:this.swatchSize,w:this.swatchSize},d=dojox.gfx.createSurface(c,a.w,a.h);this._surfaces.push(d);if(b.fill)d.createRect({x:2,y:2,width:a.w-4,height:a.h-4}).setFill(b.fill).setStroke(b.stroke);else if(b.stroke||b.marker){var e={x1:0,y1:a.h/2,x2:a.w,y2:a.h/2};b.stroke&&d.createLine(e).setStroke(b.stroke);
b.marker&&(a={x:a.w/2,y:a.h/2},b.stroke?d.createPath({path:"M"+a.x+" "+a.y+" "+b.marker}).setFill(b.stroke.color).setStroke(b.stroke):d.createPath({path:"M"+a.x+" "+a.y+" "+b.marker}).setFill(b.color).setStroke(b.color))}else d.createRect({x:2,y:2,width:a.w-4,height:a.h-4}).setStroke("black"),d.createLine({x1:2,y1:2,x2:a.w-2,y2:a.h-2}).setStroke("black"),d.createLine({x1:2,y1:a.h-2,x2:a.w-2,y2:2}).setStroke("black")}}));