/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.widget.SelectableLegend"]||(dojo._hasResource["dojox.charting.widget.SelectableLegend"]=!0,dojo.provide("dojox.charting.widget.SelectableLegend"),dojo.require("dojox.charting.widget.Legend"),dojo.require("dijit.form.CheckBox"),dojo.require("dojox.charting.action2d.Highlight"),function(){var h=dojox.lang.functional;dojo.declare("dojox.charting.widget.SelectableLegend",[dojox.charting.widget.Legend],{outline:!1,transitionFill:null,transitionStroke:null,postCreate:function(){this.legends=
[];this.legendAnim={};this.inherited(arguments)},refresh:function(){this.legends=[];this.inherited(arguments);this._applyEvents();new dojox.charting.widget._FocusManager(this)},_addLabel:function(a,c){this.inherited(arguments);var b=dojo.query("td",this.legendBody),b=b[b.length-1];this.legends.push(b);var d=new dijit.form.CheckBox({checked:!0});dojo.place(d.domNode,b,"first");c=dojo.query("label",b)[0];dojo.attr(c,"for",d.id)},_applyEvents:function(){dojo.forEach(this.legends,function(a,c){var b,
d=[],e,g;this._isPie()?(b=this.chart.stack[0],d.push(b.group.children[c]),e=b.name,g=this.chart.series[0].name):(b=this.chart.series[c],d=b.group.children,e=b.plot,g=b.name);var i={fills:h.map(d,"x.getFill()"),strokes:h.map(d,"x.getStroke()")};b=dojo.query(".dijitCheckBox",a)[0];dojo.connect(b,"onclick",this,function(b){this._toggle(d,c,a.vanished,i,g,e);a.vanished=!a.vanished;b.stopPropagation()});var k=dojo.query(".dojoxLegendIcon",a)[0],f=this._getFilledShape(this._surfaces[c].children);dojo.forEach(["onmouseenter",
"onmouseleave"],function(b){dojo.connect(k,b,this,function(b){this._highlight(b,f,d,c,a.vanished,i,g,e)})},this)},this)},_toggle:function(a,c,b,d,e,g){dojo.forEach(a,function(a,c){var f=d.fills[c],e=this._getTransitionFill(g),j=d.strokes[c],l=this.transitionStroke;f&&(e&&(typeof f=="string"||f instanceof dojo.Color)?dojox.gfx.fx.animateFill({shape:a,color:{start:b?e:f,end:b?f:e}}).play():a.setFill(b?f:e));j&&!this.outline&&a.setStroke(b?j:l)},this)},_highlight:function(a,c,b,d,e,g,i,k){if(!e){var f=
this._getAnim(k),h=this._isPie(),j=a.type=="mouseenter"?"onmouseover":a.type=="mouseleave"?"onmouseout":"on"+a.type;f.process({shape:c,index:h?"legend"+d:"legend",run:{name:i},type:j});dojo.forEach(b,function(a,b){a.setFill(g.fills[b]);var c={shape:a,index:h?d:b,run:{name:i},type:j};f.duration=100;f.process(c)})}},_getAnim:function(a){this.legendAnim[a]||(this.legendAnim[a]=new dojox.charting.action2d.Highlight(this.chart,a));return this.legendAnim[a]},_getTransitionFill:function(a){return this.chart.stack[this.chart.plots[a]].declaredClass.indexOf("dojox.charting.plot2d.Stacked")!=
-1?this.chart.theme.plotarea.fill:null},_getFilledShape:function(a){for(var c=0;a[c];){if(a[c].getFill())return a[c];c++}},_isPie:function(){return this.chart.stack[0].declaredClass=="dojox.charting.plot2d.Pie"}});dojo.declare("dojox.charting.widget._FocusManager",null,{constructor:function(a){this.legend=a;this.index=0;this.horizontalLength=this._getHrizontalLength();dojo.forEach(a.legends,function(a,b){b>0&&dojo.query("input",a).attr("tabindex",-1)});this.firstLabel=dojo.query("input",a.legends[0])[0];
dojo.connect(this.firstLabel,"focus",this,function(){this.legend.active=!0});dojo.connect(this.legend.legendNode,"keydown",this,"_onKeyEvent")},_getHrizontalLength:function(){var a=this.legend.horizontal;return typeof a=="number"?Math.min(a,this.legend.legends.length):a?this.legend.legends.length:1},_onKeyEvent:function(a){if(this.legend.active)if(a.keyCode==dojo.keys.TAB)this.legend.active=!1;else{var c=this.legend.legends.length;switch(a.keyCode){case dojo.keys.LEFT_ARROW:this.index--;this.index<
0&&(this.index+=c);break;case dojo.keys.RIGHT_ARROW:this.index++;this.index>=c&&(this.index-=c);break;case dojo.keys.UP_ARROW:this.index-this.horizontalLength>=0&&(this.index-=this.horizontalLength);break;case dojo.keys.DOWN_ARROW:this.index+this.horizontalLength<c&&(this.index+=this.horizontalLength);break;default:return}this._moveToFocus();dojo.stopEvent(a)}},_moveToFocus:function(){dojo.query("input",this.legend.legends[this.index])[0].focus()}})}());