/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.mobile.compat"]&&(dojo._hasResource["dojox.mobile.compat"]=!0,dojo.provide("dojox.mobile.compat"),dojo.require("dijit._base.sniff"),dojo.require("dojo._base.fx"),dojo.require("dojo.fx"),dojo.require("dojox.fx.flip"),!dojo.isWebKit)){dojo.extend(dojox.mobile.View,{_doTransition:function(a,b,c,d){this.wakeUp(b);if(!c||c=="none")b.style.display="",a.style.display="none",b.style.left="0px",this.invokeCallback();else if(c=="slide"){var c=a.offsetWidth,e=dojo.fx.slideTo({node:a,
duration:400,left:-c*d,top:a.offsetTop}),f=dojo.fx.slideTo({node:b,duration:400,left:0});b.style.position="absolute";b.style.left=c*d+"px";b.style.display="";d=dojo.fx.combine([e,f]);dojo.connect(d,"onEnd",this,function(){a.style.display="none";b.style.position="relative";this.invokeCallback()});d.play()}else if(c=="flip")d=dojox.fx.flip({node:a,dir:"right",depth:0.5,duration:400}),b.style.position="absolute",b.style.left="0px",dojo.connect(d,"onEnd",this,function(){a.style.display="none";b.style.position=
"relative";b.style.display="";this.invokeCallback()}),d.play();else if(c=="fade")d=dojo.fx.chain([dojo.fadeOut({node:a,duration:600}),dojo.fadeIn({node:b,duration:600})]),b.style.position="absolute",b.style.left="0px",b.style.display="",dojo.style(b,"opacity",0),dojo.connect(d,"onEnd",this,function(){a.style.display="none";b.style.position="relative";dojo.style(a,"opacity",1);this.invokeCallback()}),d.play()},wakeUp:function(a){if(dojo.isIE&&!a._wokeup){a._wokeup=!0;var b=a.style.display;a.style.display=
"";for(var c=a.getElementsByTagName("*"),d=0,e=c.length;d<e;d++){var f=c[d].style.display;c[d].style.display="none";c[d].style.display="";c[d].style.display=f}a.style.display=b}}});dojo.extend(dojox.mobile.Switch,{buildRendering:function(){this.domNode=this.srcNodeRef||dojo.doc.createElement("DIV");this.domNode.className="mblSwitch";this.domNode.innerHTML='<div class="mblSwitchInner"><div class="mblSwitchBg mblSwitchBgLeft"><div class="mblSwitchCorner mblSwitchCorner1T"></div><div class="mblSwitchCorner mblSwitchCorner2T"></div><div class="mblSwitchCorner mblSwitchCorner3T"></div><div class="mblSwitchText mblSwitchTextLeft">'+
this.leftLabel+'</div><div class="mblSwitchCorner mblSwitchCorner1B"></div><div class="mblSwitchCorner mblSwitchCorner2B"></div><div class="mblSwitchCorner mblSwitchCorner3B"></div></div><div class="mblSwitchBg mblSwitchBgRight"><div class="mblSwitchCorner mblSwitchCorner1T"></div><div class="mblSwitchCorner mblSwitchCorner2T"></div><div class="mblSwitchCorner mblSwitchCorner3T"></div><div class="mblSwitchText mblSwitchTextRight">'+this.rightLabel+'</div><div class="mblSwitchCorner mblSwitchCorner1B"></div><div class="mblSwitchCorner mblSwitchCorner2B"></div><div class="mblSwitchCorner mblSwitchCorner3B"></div></div><div class="mblSwitchKnobContainer"><div class="mblSwitchCorner mblSwitchCorner1T"></div><div class="mblSwitchCorner mblSwitchCorner2T"></div><div class="mblSwitchCorner mblSwitchCorner3T"></div><div class="mblSwitchKnob"></div><div class="mblSwitchCorner mblSwitchCorner1B"></div><div class="mblSwitchCorner mblSwitchCorner2B"></div><div class="mblSwitchCorner mblSwitchCorner3B"></div></div></div>';
var a=this.inner=this.domNode.firstChild;this.left=a.childNodes[0];this.right=a.childNodes[1];this.knob=a.childNodes[2];dojo.addClass(this.domNode,this.value=="on"?"mblSwitchOn":"mblSwitchOff");this[this.value=="off"?"left":"right"].style.display="none"},_changeState:function(a){if(!this.inner.parentNode||!this.inner.parentNode.tagName)dojo.addClass(this.domNode,a=="on"?"mblSwitchOn":"mblSwitchOff");else{var b;if(this.inner.offsetLeft==0){if(a=="on")return;b=-53}else{if(a=="off")return;b=0}b=dojo.fx.slideTo({node:this.inner,
duration:500,left:b});var c=this;dojo.connect(b,"onEnd",function(){c[a=="off"?"left":"right"].style.display="none"});b.play()}}});if(dojo.isIE||dojo.isBB){dojo.extend(dojox.mobile.RoundRect,{buildRendering:function(){dojox.mobile.createRoundRect(this);this.domNode.className="mblRoundRect"}});dojox.mobile.RoundRectList._addChild=dojox.mobile.RoundRectList.prototype.addChild;dojo.extend(dojox.mobile.RoundRectList,{buildRendering:function(){dojox.mobile.createRoundRect(this,!0);this.domNode.className=
"mblRoundRectList"},postCreate:function(){this.redrawBorders()},addChild:function(a){dojox.mobile.RoundRectList._addChild.apply(this,arguments);this.redrawBorders();dojox.mobile.applyPngFilter&&dojox.mobile.applyPngFilter(a.domNode)},redrawBorders:function(){for(var a=!1,b=this.containerNode.childNodes.length-1;b>=0;b--){var c=this.containerNode.childNodes[b];if(c.tagName=="LI")c.style.borderBottomStyle=a?"solid":"none",a=!0}}});dojo.extend(dojox.mobile.EdgeToEdgeList,{buildRendering:function(){this.domNode=
this.containerNode=this.srcNodeRef||dojo.doc.createElement("UL");this.domNode.className="mblEdgeToEdgeList"}});if(dojox.mobile.IconContainer)dojox.mobile.IconContainer._addChild=dojox.mobile.IconContainer.prototype.addChild,dojo.extend(dojox.mobile.IconContainer,{addChild:function(a){dojox.mobile.IconContainer._addChild.apply(this,arguments);dojox.mobile.applyPngFilter&&dojox.mobile.applyPngFilter(a.domNode)}});dojo.mixin(dojox.mobile,{createRoundRect:function(a,b){var c;a.domNode=dojo.doc.createElement("DIV");
a.domNode.style.padding="0px";a.domNode.style.backgroundColor="transparent";a.domNode.style.borderStyle="none";a.containerNode=dojo.doc.createElement(b?"UL":"DIV");a.containerNode.className="mblRoundRectContainer";if(a.srcNodeRef){a.srcNodeRef.parentNode.replaceChild(a.domNode,a.srcNodeRef);c=0;for(len=a.srcNodeRef.childNodes.length;c<len;c++)a.containerNode.appendChild(a.srcNodeRef.removeChild(a.srcNodeRef.firstChild));a.srcNodeRef=null}a.domNode.appendChild(a.containerNode);for(c=0;c<=5;c++){var d=
dojo.create("DIV");d.className="mblRoundCorner mblRoundCorner"+c+"T";a.domNode.insertBefore(d,a.containerNode);d=dojo.create("DIV");d.className="mblRoundCorner mblRoundCorner"+c+"B";a.domNode.appendChild(d)}}});dojox.mobile.ScrollableView&&dojo.extend(dojox.mobile.ScrollableView,{postCreate:function(){var a=dojo.create("DIV",{className:"mblDummyForIE",innerHTML:"&nbsp;"},this.containerNode,"first");dojo.style(a,{position:"relative",marginBottom:"-2px",fontSize:"1px"})}})}if(dojo.isIE<=6)dojox.mobile.applyPngFilter=
function(a){for(var a=a||dojo.body(),a=a.getElementsByTagName("IMG"),b=dojo.moduleUrl("dojo","resources/blank.gif"),c=0,d=a.length;c<d;c++){var e=a[c],f=e.offsetWidth,g=e.offsetHeight;if(f===0||g===0){if(dojo.style(e,"display")!="none")continue;e.style.display="";f=e.offsetWidth;g=e.offsetHeight;e.style.display="none";if(f===0||g===0)continue}var h=e.src;if(h.indexOf("resources/blank.gif")==-1)e.src=b,e.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+h+"')",e.style.width=
f+"px",e.style.height=g+"px"}};dojox.mobile.loadCss=function(a){if(!dojo.global._loadedCss){var b={};dojo.forEach(dojox.mobile.getCssPaths(),function(a){b[a]=!0});dojo.global._loadedCss=b}dojo.isArray(a)||(a=[a]);for(var c=0;c<a.length;c++){var d=a[c];if(!dojo.global._loadedCss[d])if(dojo.global._loadedCss[d]=!0,dojo.doc.createStyleSheet)setTimeout(function(a){return function(){dojo.doc.createStyleSheet(a)}}(d),0);else{var e=dojo.doc.createElement("link");e.href=d;e.type="text/css";e.rel="stylesheet";
dojo.doc.getElementsByTagName("head")[0].appendChild(e)}}};dojox.mobile.getCssPaths=function(){var a=[],b,c,d=dojo.doc.styleSheets;for(b=0;b<d.length;b++){var e=d[b].cssRules||d[b].imports;if(e)for(c=0;c<e.length;c++)e[c].href&&a.push(e[c].href)}c=dojo.doc.getElementsByTagName("link");b=0;for(len=c.length;b<len;b++)c[b].href&&a.push(c[b].href);return a};dojox.mobile.loadCompatPattern=/\/themes\/(domButtons|buttons|iphone|android).*\.css$/;dojox.mobile.loadCompatCssFiles=function(){for(var a=dojox.mobile.getCssPaths(),
b=0;b<a.length;b++){var c=a[b];c.match(dojox.mobile.loadCompatPattern)&&c.indexOf("-compat.css")==-1&&(c=c.substring(0,c.length-4)+"-compat.css",dojox.mobile.loadCss(c))}};dojox.mobile.hideAddressBar=function(){};dojo.addOnLoad(function(){dojo.config.mblLoadCompatCssFiles!==!1&&dojox.mobile.loadCompatCssFiles();dojox.mobile.applyPngFilter&&dojox.mobile.applyPngFilter()})};