/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.IconContainer"]||(dojo._hasResource["dojox.mobile.IconContainer"]=!0,dojo.provide("dojox.mobile.IconContainer"),dojo.require("dojox.mobile"),dojo.declare("dojox.mobile.IconContainer",dijit._WidgetBase,{defaultIcon:"",transition:"below",pressedIconOpacity:0.4,iconBase:"",iconPos:"",back:"Home",label:"My Application",single:!1,buildRendering:function(){this.domNode=this.containerNode=this.srcNodeRef||dojo.doc.createElement("UL");this.domNode.className="mblIconContainer";
var a=this._terminator=dojo.create("LI");a.className="mblIconItemTerminator";a.innerHTML="&nbsp;";this.domNode.appendChild(a)},_setupSubNodes:function(a){var b=this.domNode.childNodes.length-1;for(i=0;i<b;i++)if(child=this.domNode.childNodes[i],child.nodeType==1){w=dijit.byNode(child);if(this.single)w.subNode.firstChild.style.display="none";a.appendChild(w.subNode)}},startup:function(){var a;if(this.transition=="below")this._setupSubNodes(this.domNode);else{var b=new dojox.mobile.View({id:this.id+
"_mblApplView"}),d=this;b.onAfterTransitionIn=function(){d._opening._open_1()};b.domNode.style.visibility="hidden";var c=b._heading=new dojox.mobile.Heading({back:this.back,label:this.label,moveTo:this.domNode.parentNode.id,transition:this.transition});b.addChild(c);a=dojo.doc.createElement("UL");a.className="mblIconContainer";a.style.marginTop="0px";this._setupSubNodes(a);b.domNode.appendChild(a);dojo.doc.body.appendChild(b.domNode);c.startup()}},closeAll:function(){for(var a=this.domNode.childNodes.length,
b=0;b<a;b++)if(child=this.domNode.childNodes[b],child.nodeType==1){if(child==this._terminator)break;w=dijit.byNode(child);w.containerNode.parentNode.style.display="none";w.setOpacity(w.iconNode,1)}},addChild:function(a){this.domNode.insertBefore(a.domNode,this._terminator);a.transition=this.transition;this.transition=="below"&&this.domNode.appendChild(a.subNode);a.inheritParams();a.setIcon()}}),dojo.declare("dojox.mobile.IconItem",dojox.mobile.AbstractItem,{lazy:!1,requires:"",timeout:10,templateString:'<li class="mblIconItem"><div class="mblIconArea" dojoAttachPoint="iconDivNode"><div><img src="${icon}" dojoAttachPoint="iconNode"></div>${label}</div></li>',
templateStringSub:'<li class="mblIconItemSub" lazy="${lazy}" style="display:none;" dojoAttachPoint="contentNode"><h2 class="mblIconContentHeading" dojoAttachPoint="closeNode"><div class="mblBlueMinusButton" style="position:absolute;left:4px;top:2px;" dojoAttachPoint="closeIconNode"><div></div></div>${label}</h2><div class="mblContent" dojoAttachPoint="containerNode"></div></li>',createTemplate:function(a){dojo.forEach(["lazy","icon","label"],function(b){for(;a.indexOf("${"+b+"}")!=-1;)a=a.replace("${"+
b+"}",this[b])},this);var b=dojo.doc.createElement("DIV");b.innerHTML=a;var d=b.getElementsByTagName("*"),c,e,f;e=d.length;for(c=0;c<e;c++)(f=d[c].getAttribute("dojoAttachPoint"))&&(this[f]=d[c]);d=b.removeChild(b.firstChild);b=null;return d},buildRendering:function(){this.inheritParams();this.domNode=this.createTemplate(this.templateString);this.subNode=this.createTemplate(this.templateStringSub);this.subNode._parentNode=this.domNode;if(this.srcNodeRef){for(var a=0,b=this.srcNodeRef.childNodes.length;a<
b;a++)this.containerNode.appendChild(this.srcNodeRef.removeChild(this.srcNodeRef.firstChild));this.srcNodeRef.parentNode.replaceChild(this.domNode,this.srcNodeRef);this.srcNodeRef=null}this.setIcon()},setIcon:function(){this.iconNode.src=this.icon;dojox.mobile.setupIcon(this.iconNode,this.iconPos)},postCreate:function(){this.connect(this.iconNode,"onmousedown","onMouseDownIcon");this.connect(this.iconNode,"onclick","iconClicked");this.connect(this.closeIconNode,"onclick","closeIconClicked");this.connect(this.iconNode,
"onerror","onError")},highlight:function(){dojo.addClass(this.iconDivNode,"mblVibrate");if(this.timeout>0){var a=this;setTimeout(function(){a.unhighlight()},this.timeout*1E3)}},unhighlight:function(){dojo.removeClass(this.iconDivNode,"mblVibrate")},setOpacity:function(a,b){a.style.opacity=b;a.style.mozOpacity=b;a.style.khtmlOpacity=b;a.style.webkitOpacity=b},instantiateWidget:function(){for(var a=this.containerNode.getElementsByTagName("*"),b=a.length,d,c=0;c<b;c++)(d=a[c].getAttribute("dojoType"))&&
dojo.require(d);b>0&&(dojox.mobile.parser||dojo.parser).parse(this.containerNode);this.lazy=!1},isOpen:function(){return this.containerNode.style.display!="none"},onMouseDownIcon:function(){this.setOpacity(this.iconNode,this.getParentWidget().pressedIconOpacity)},iconClicked:function(a){a?setTimeout(dojo.hitch(this,function(){this.iconClicked()}),0):this.moveTo||this.href||this.url?(this.transitionTo(this.moveTo,this.href,this.url),setTimeout(dojo.hitch(this,function(){this.setOpacity(this.iconNode,
1)}),1500)):this.open()},closeIconClicked:function(a){a?setTimeout(dojo.hitch(this,function(){this.closeIconClicked()}),0):this.close()},open:function(){var a=this.getParentWidget();this.transition=="below"?(a.single&&(a.closeAll(),this.setOpacity(this.iconNode,this.getParentWidget().pressedIconOpacity)),this._open_1()):(a._opening=this,a.single&&(a.closeAll(),dijit.byId(a.id+"_mblApplView")._heading.setLabel(this.label)),this.transitionTo(a.id+"_mblApplView"))},_open_1:function(){this.contentNode.style.display=
"";this.unhighlight();this.lazy&&(this.requires&&dojo.forEach(this.requires.split(/,/),function(a){dojo.require(a)}),this.instantiateWidget());this.contentNode.scrollIntoView();this.onOpen()},close:function(){if(dojo.isWebKit){for(var a=this.domNode.parentNode.offsetWidth/8,b=this.iconNode.offsetLeft,d=0,c=1;c<=3;c++)if(a*(2*c-1)<b&&b<=a*(2*(c+1)-1)){d=c;break}dojo.addClass(this.containerNode.parentNode,"mblCloseContent mblShrink"+d)}else this.containerNode.parentNode.style.display="none";this.setOpacity(this.iconNode,
1);this.onClose()},onOpen:function(){},onClose:function(){},onError:function(){this.iconNode.src=this.getParentWidget().defaultIcon}}));