/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.mobile.scrollable"])dojo._hasResource["dojox.mobile.scrollable"]=!0,typeof dojo!="undefined"&&dojo.provide?dojo.provide("dojox.mobile.scrollable"):(dojo={doc:document,global:window,isWebKit:navigator.userAgent.indexOf("WebKit")!=-1},dojox={mobile:{}}),dojox.mobile.scrollable=function(){this.fixedFooterHeight=this.fixedHeaderHeight=0;this.isLocalFooter=!1;this.scrollBar=!0;this.scrollDir="v";this.weight=0.6;this.fadeScrollBar=!0;this.disableFlashScrollBar=!1;this.threshold=
0;this.init=function(a){if(a)for(var b in a)a.hasOwnProperty(b)&&(this[b]=(b=="domNode"||b=="containerNode")&&typeof a[b]=="string"?dojo.doc.getElementById(a[b]):a[b]);this._v=this.scrollDir.indexOf("v")!=-1;this._h=this.scrollDir.indexOf("h")!=-1;this._f=this.scrollDir=="f";this._ch=[];this._ch.push(dojo.connect(this.containerNode,dojox.mobile.hasTouch?"touchstart":"onmousedown",this,"onTouchStart"));dojo.isWebKit&&(this._ch.push(dojo.connect(this.domNode,"webkitAnimationEnd",this,"onFlickAnimationEnd")),
this._ch.push(dojo.connect(this.domNode,"webkitAnimationStart",this,"onFlickAnimationStart")));dojo.global.onorientationchange!==void 0?this._ch.push(dojo.connect(dojo.global,"onorientationchange",this,"resizeView")):this._ch.push(dojo.connect(dojo.global,"onresize",this,"resizeView"));this.resizeView();var c=this;setTimeout(function(){c.flashScrollBar()},600)};this.cleanup=function(){for(var a=0;a<this._ch.length;a++)dojo.disconnect(this._ch[a]);this._ch=null};this.resizeView=function(){this._appFooterHeight=
this.fixedFooterHeight&&!this.isLocalFooter?this.fixedFooterHeight:0;this.containerNode.style.paddingTop=this.fixedHeaderHeight+"px";var a=0,b=this,c=setInterval(function(){b.domNode.style.height=(dojo.global.innerHeight||dojo.doc.documentElement.clientHeight)-b._appFooterHeight+"px";b.resetScrollBar();a++>=4&&clearInterval(c)},300)};this.onFlickAnimationStart=function(a){dojo.stopEvent(a)};this.onFlickAnimationEnd=function(a){a&&a.srcElement&&dojo.stopEvent(a);this.stopAnimation();if(this._bounce){var b=
this,c=b._bounce;setTimeout(function(){b.slideTo(c,0.3,"ease-out")},0);b._bounce=void 0}else this.hideScrollBar(),this.removeCover()};this.onTouchStart=function(a){if(!(this._conn&&(new Date).getTime()-this.startTime<500)){if(!this._conn)this._conn=[],this._conn.push(dojo.connect(dojo.doc,dojox.mobile.hasTouch?"touchmove":"onmousemove",this,"onTouchMove")),this._conn.push(dojo.connect(dojo.doc,dojox.mobile.hasTouch?"touchend":"onmouseup",this,"onTouchEnd"));this._aborted=!1;dojo.hasClass(this.containerNode,
"mblScrollableScrollTo2")&&this.abort();this.touchStartX=a.touches?a.touches[0].pageX:a.clientX;this.touchStartY=a.touches?a.touches[0].pageY:a.clientY;this.startTime=(new Date).getTime();this.startPos=this.getPos();this._dim=this.getDim();this._time=[0];this._posX=[this.touchStartX];this._posY=[this.touchStartY];(a.target.nodeType!=1||a.target.tagName!="SELECT"&&a.target.tagName!="INPUT"&&a.target.tagName!="TEXTAREA")&&dojo.stopEvent(a)}};this.onTouchMove=function(a){var b=a.touches?a.touches[0].pageX:
a.clientX,a=a.touches?a.touches[0].pageY:a.clientY,c=b-this.touchStartX,f=a-this.touchStartY,d={x:this.startPos.x+c,y:this.startPos.y+f},e=this._dim;if(this._time.length==1){if(c<this.threshold&&f<this.threshold)return;this.addCover();this.showScrollBar()}c=this.weight;if(this._v)if(d.y>0)d.y=Math.round(d.y*c);else if(d.y<-e.o.h)d.y=e.c.h<e.d.h?Math.round(d.y*c):-e.o.h-Math.round((-e.o.h-d.y)*c);if(this._h||this._f)if(d.x>0)d.x=Math.round(d.x*c);else if(d.x<-e.o.w)d.x=e.c.w<e.d.w?Math.round(d.x*c):
-e.o.w-Math.round((-e.o.w-d.x)*c);this.scrollTo(d);d=this._time.length;if(d>=2){var h,g;this._v&&!this._h?(h=this._posY[d-1]-this._posY[d-2],g=a-this._posY[d-1]):!this._v&&this._h&&(h=this._posX[d-1]-this._posX[d-2],g=b-this._posX[d-1]);if(h*g<0)this._time=[this._time[d-1]],this._posX=[this._posX[d-1]],this._posY=[this._posY[d-1]],d=1}d==10&&(this._time.shift(),this._posX.shift(),this._posY.shift());this._time.push((new Date).getTime()-this.startTime);this._posX.push(b);this._posY.push(a)};this.onTouchEnd=
function(a){if(this._conn){for(var b=0;b<this._conn.length;b++)dojo.disconnect(this._conn[b]);this._conn=null;var b=this._time.length,c=!1;this._aborted||(b<=1?c=!0:b==2&&Math.abs(this._posY[1]-this._posY[0])<4&&(c=!0));if(c){if(this.hideScrollBar(),this.removeCover(),dojox.mobile.hasTouch){var f=a.target;if(f.nodeType!=1)f=f.parentNode;var d=dojo.doc.createEvent("MouseEvents");d.initEvent("click",!0,!0);f.dispatchEvent(d)}}else{a={x:0,y:0};if(b>=2&&(new Date).getTime()-this.startTime-this._time[b-
1]<500){var c=this._posX[b-(b>3?2:1)]-this._posX[b-6>=0?b-6:0],e=this._time[b-(b>3?2:1)]-this._time[b-6>=0?b-6:0];a.y=this.calcSpeed(this._posY[b-(b>3?2:1)]-this._posY[b-6>=0?b-6:0],e);a.x=this.calcSpeed(c,e)}b=this.getPos();c={};e=this._dim;if(this._v)c.y=b.y+a.y;if(this._h||this._f)c.x=b.x+a.x;if(this.scrollDir=="v"&&e.c.h<=e.d.h)this.slideTo({y:0},0.3,"ease-out");else if(this.scrollDir=="h"&&e.c.w<=e.d.w)this.slideTo({x:0},0.3,"ease-out");else if(this._v&&this._h&&e.c.h<=e.d.h&&e.c.w<=e.d.w)this.slideTo({x:0,
y:0},0.3,"ease-out");else{var h="ease-out",g={};if(this._v)if(c.y>0)b.y>0?(f=0.3,c.y=0):(c.y=Math.min(c.y,20),h="linear",g.y=0);else if(-a.y>e.o.h- -b.y)b.y<-e.o.h?(f=0.3,c.y=e.c.h<=e.d.h?0:-e.o.h):(c.y=Math.max(c.y,-e.o.h-20),h="linear",g.y=-e.o.h);if(this._h||this._f)if(c.x>0)b.x>0?(f=0.3,c.x=0):(c.x=Math.min(c.x,20),h="linear",g.x=0);else if(-a.x>e.o.w- -b.x)b.x<-e.o.w?(f=0.3,c.x=e.c.w<=e.d.w?0:-e.o.w):(c.x=Math.max(c.x,-e.o.w-20),h="linear",g.x=-e.o.w);this._bounce=g.x!==void 0||g.y!==void 0?
g:void 0;if(f===void 0){var i;if(this._v&&this._h)i=Math.sqrt(a.x+a.x+a.y*a.y),d=Math.sqrt(Math.pow(c.y-b.y,2)+Math.pow(c.x-b.x,2));else if(this._v)i=a.y,d=c.y-b.y;else if(this._h)i=a.x,d=c.x-b.x;f=i!==0?Math.abs(d/i):0.01}this.slideTo(c,f,h)}}}};this.abort=function(){this.scrollTo(this.getPos());this.stopAnimation();this._aborted=!0};this.stopAnimation=function(){dojo.removeClass(this.containerNode,"mblScrollableScrollTo2");if(this._scrollBarV)this._scrollBarV.className="";if(this._scrollBarH)this._scrollBarH.className=
""};this.calcSpeed=function(a,b){return Math.round(a/b*100)*4};this.scrollTo=function(a,b){var c=this.containerNode.style;if(dojo.isWebKit)c.webkitTransform=this.makeTranslateStr(a);else{if(this._v)c.top=a.y+"px";if(this._h||this._f)c.left=a.x+"px"}b||this.scrollScrollBarTo(this.calcScrollBarPos(a))};this.slideTo=function(a,b,c){this._runSlideAnimation(this.getPos(),a,b,c,this.containerNode,2);this.slideScrollBarTo(a,b,c)};this.makeTranslateStr=function(a){var b=this._v&&typeof a.y=="number"?a.y+
"px":"0px",a=(this._h||this._f)&&typeof a.x=="number"?a.x+"px":"0px";return dojox.mobile.hasTranslate3d?"translate3d("+a+","+b+",0px)":"translate("+a+","+b+")"};this.getPos=function(){if(dojo.isWebKit){var a=dojo.doc.defaultView.getComputedStyle(this.containerNode,"")["-webkit-transform"];return a&&a.indexOf("matrix")===0?(a=a.split(/[,\s\)]+/),{y:a[5]-0,x:a[4]-0}):{x:0,y:0}}else return{y:this.containerNode.offsetTop,x:this.containerNode.offsetLeft}};this.getDim=function(){var a={};a.c={h:this.containerNode.offsetHeight-
this.fixedHeaderHeight,w:this.containerNode.offsetWidth};a.v={h:this.domNode.offsetHeight+this._appFooterHeight,w:this.domNode.offsetWidth};a.d={h:a.v.h-this.fixedHeaderHeight-this.fixedFooterHeight,w:a.v.w};a.o={h:a.c.h-a.v.h+this.fixedHeaderHeight+this.fixedFooterHeight,w:a.c.w-a.v.w};return a};this.showScrollBar=function(){if(this.scrollBar){var a=this._dim;if(!(this.scrollDir=="v"&&a.c.h<=a.d.h)&&!(this.scrollDir=="h"&&a.c.w<=a.d.w)&&(!this._v||!this._h||!(a.c.h<=a.d.h&&a.c.w<=a.d.w))){a=function(a,
c){var f=a["_scrollBarNode"+c];if(!f){var f=dojo.create("div",null,a.domNode),d={position:"absolute",overflow:"hidden"};c=="V"?(d.right="2px",d.width="5px"):(d.bottom=(a.isLocalFooter?a.fixedFooterHeight:0)+2+"px",d.height="5px");dojo.style(f,d);f.className="mblScrollBarWrapper";a["_scrollBarWrapper"+c]=f;f=dojo.create("div",null,f);dojo.style(f,{opacity:0.6,position:"absolute",backgroundColor:"#606060",fontSize:"1px",webkitBorderRadius:"2px",MozBorderRadius:"2px",webkitTransformOrigin:"0 0",zIndex:2147483647});
dojo.style(f,c=="V"?{width:"5px"}:{height:"5px"});a["_scrollBarNode"+c]=f}return f};if(this._v&&!this._scrollBarV)this._scrollBarV=a(this,"V");if(this._h&&!this._scrollBarH)this._scrollBarH=a(this,"H");this.resetScrollBar()}}};this.hideScrollBar=function(){if(this.fadeScrollBar&&dojo.isWebKit&&!dojox.mobile._fadeRule){var a=dojo.create("style",null,dojo.doc.getElementsByTagName("head")[0]);a.textContent=".mblScrollableFadeOutScrollBar{  -webkit-animation-duration: 1s;  -webkit-animation-name: scrollableViewFadeOutScrollBar;}@-webkit-keyframes scrollableViewFadeOutScrollBar{  from { opacity: 0.6; }  50% { opacity: 0.6; }  to { opacity: 0; }}";
dojox.mobile._fadeRule=a.sheet.cssRules[1]}if(this.scrollBar){a=function(a){dojo.style(a,{opacity:0,webkitAnimationDuration:""});a.className="mblScrollableFadeOutScrollBar"};if(this._scrollBarV)a(this._scrollBarV),this._scrollBarV=null;if(this._scrollBarH)a(this._scrollBarH),this._scrollBarH=null}};this.calcScrollBarPos=function(a){var b={},c=this._dim,f=function(a,b,c,f,i){c=Math.round((f-b-8)/(f-i)*c);c<-b+5&&(c=-b+5);c>a-5&&(c=a-5);return c};if(typeof a.y=="number"&&this._scrollBarV)b.y=f(this._scrollBarWrapperV.offsetHeight,
this._scrollBarV.offsetHeight,a.y,c.d.h,c.c.h);if(typeof a.x=="number"&&this._scrollBarH)b.x=f(this._scrollBarWrapperH.offsetWidth,this._scrollBarH.offsetWidth,a.x,c.d.w,c.c.w);return b};this.scrollScrollBarTo=function(a){if(this.scrollBar){if(this._v&&this._scrollBarV&&typeof a.y=="number")dojo.isWebKit?this._scrollBarV.style.webkitTransform=this.makeTranslateStr({y:a.y}):this._scrollBarV.style.top=a.y+"px";if(this._h&&this._scrollBarH&&typeof a.x=="number")dojo.isWebKit?this._scrollBarH.style.webkitTransform=
this.makeTranslateStr({x:a.x}):this._scrollBarH.style.left=a.x+"px"}};this.slideScrollBarTo=function(a,b,c){if(this.scrollBar){var f=this.calcScrollBarPos(this.getPos()),a=this.calcScrollBarPos(a);this._v&&this._scrollBarV&&this._runSlideAnimation({y:f.y},{y:a.y},b,c,this._scrollBarV,0);this._h&&this._scrollBarH&&this._runSlideAnimation({x:f.x},{x:a.x},b,c,this._scrollBarH,1)}};this._runSlideAnimation=function(a,b,c,f,d,e){dojo.isWebKit?(this.setKeyframes(a,b,e),dojo.style(d,{webkitAnimationDuration:c+
"s",webkitAnimationTimingFunction:f}),dojo.addClass(d,"mblScrollableScrollTo"+e),e==2?this.scrollTo(b,!0):this.scrollScrollBarTo(b)):dojo.fx&&dojo.fx.easing?(a=dojo.fx.slideTo({node:d,duration:c*1E3,left:b.x,top:b.y,easing:f=="ease-out"?dojo.fx.easing.quadOut:dojo.fx.easing.linear}).play(),e==2&&dojo.connect(a,"onEnd",this,"onFlickAnimationEnd")):e==2?(this.scrollTo(b),this.onFlickAnimationEnd()):this.scrollScrollBarTo(b)};this.resetScrollBar=function(){var a=function(a,b,d,e,h,g){if(b){var i={};
i[g?"top":"left"]=h+4+"px";i[g?"height":"width"]=d-8+"px";dojo.style(a,i);a=Math.round(d*d/e);a=Math.min(Math.max(a-8,5),d-8);b.style[g?"height":"width"]=a+"px";dojo.style(b,{opacity:0.6})}},b=this.getDim();a(this._scrollBarWrapperV,this._scrollBarV,b.d.h,b.c.h,this.fixedHeaderHeight,!0);a(this._scrollBarWrapperH,this._scrollBarH,b.d.w,b.c.w,0);this.createMask()};this.createMask=function(){if(dojo.isWebKit){var a;if(this._scrollBarWrapperV){var b=this._scrollBarWrapperV.offsetHeight;a=dojo.doc.getCSSCanvasContext("2d",
"scrollBarMaskV",5,b);a.fillStyle="rgba(0,0,0,0.5)";a.fillRect(1,0,3,2);a.fillRect(0,1,5,1);a.fillRect(0,b-2,5,1);a.fillRect(1,b-1,3,2);a.fillStyle="rgb(0,0,0)";a.fillRect(0,2,5,b-4);this._scrollBarWrapperV.style.webkitMaskImage="-webkit-canvas(scrollBarMaskV)"}if(this._scrollBarWrapperH)b=this._scrollBarWrapperH.offsetWidth,a=dojo.doc.getCSSCanvasContext("2d","scrollBarMaskH",b,5),a.fillStyle="rgba(0,0,0,0.5)",a.fillRect(0,1,2,3),a.fillRect(1,0,1,5),a.fillRect(b-2,0,1,5),a.fillRect(b-1,1,2,3),a.fillStyle=
"rgb(0,0,0)",a.fillRect(2,0,b-4,5),this._scrollBarWrapperH.style.webkitMaskImage="-webkit-canvas(scrollBarMaskH)"}};this.flashScrollBar=function(){if(!this.disableFlashScrollBar&&(this._dim=this.getDim(),!(this._dim.d.h<=0))){this.showScrollBar();var a=this;setTimeout(function(){a.hideScrollBar()},300)}};this.addCover=function(){if(!dojox.mobile.hasTouch&&!this.noCover)this._cover?this._cover.style.display="":(this._cover=dojo.create("div",null,dojo.doc.body),dojo.style(this._cover,{backgroundColor:"#ffff00",
opacity:0,position:"absolute",top:"0px",left:"0px",width:"100%",height:"100%",zIndex:2147483647}),this._ch.push(dojo.connect(this._cover,dojox.mobile.hasTouch?"touchstart":"onmousedown",this,"onTouchEnd")));this.setSelectable(this.domNode,!1);var a;dojo.global.getSelection?(a=dojo.global.getSelection(),a.collapse(dojo.doc.body,0)):(a=dojo.doc.selection.createRange(),a.setEndPoint("EndToStart",a),a.select())};this.removeCover=function(){if(!dojox.mobile.hasTouch&&this._cover)this._cover.style.display=
"none";this.setSelectable(this.domNode,!0)};this.setKeyframes=function(a,b,c){if(!dojox.mobile._rule)dojox.mobile._rule=[];if(!dojox.mobile._rule[c]){var f=dojo.create("style",null,dojo.doc.getElementsByTagName("head")[0]);f.textContent=".mblScrollableScrollTo"+c+"{-webkit-animation-name: scrollableViewScroll"+c+";}@-webkit-keyframes scrollableViewScroll"+c+"{}";dojox.mobile._rule[c]=f.sheet.cssRules[1]}if(c=dojox.mobile._rule[c])if(a&&(c.deleteRule("from"),c.insertRule("from { -webkit-transform: "+
this.makeTranslateStr(a)+"; }")),b){if(b.x===void 0)b.x=a.x;if(b.y===void 0)b.y=a.y;c.deleteRule("to");c.insertRule("to { -webkit-transform: "+this.makeTranslateStr(b)+"; }")}};this.setSelectable=function(a,b){a.style.KhtmlUserSelect=b?"auto":"none";a.style.MozUserSelect=b?"":"none";a.onselectstart=b?null:function(){return!1};a.unselectable=b?"":"on"}},function(){if(dojo.isWebKit){var a=dojo.doc.createElement("div");a.style.webkitTransform="translate3d(0px,1px,0px)";dojo.doc.documentElement.appendChild(a);
var b=dojo.doc.defaultView.getComputedStyle(a,"")["-webkit-transform"];dojox.mobile.hasTranslate3d=b&&b.indexOf("matrix")===0;dojo.doc.documentElement.removeChild(a);dojox.mobile.hasTouch=typeof dojo.doc.documentElement.ontouchstart!="undefined"&&navigator.appVersion.indexOf("Mobile")!=-1}}();