/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.TabBar"]||(dojo._hasResource["dojox.mobile.TabBar"]=!0,dojo.provide("dojox.mobile.TabBar"),dojo.require("dojox.mobile"),dojo.declare("dojox.mobile.TabBar",dijit._WidgetBase,{iconBase:"",iconPos:"",barType:"tabBar",inHeading:!1,_fixedButtonWidth:76,_fixedButtonMargin:17,_largeScreenWidth:500,buildRendering:function(){this._clsName=this.barType=="segmentedControl"?"mblTabButton":"mblTabBarButton";this.domNode=this.containerNode=this.srcNodeRef||dojo.doc.createElement("H1");
this.domNode.className=this.barType=="segmentedControl"?"mblTabPanelHeader":"mblTabBar"},postCreate:function(){dojo.global.onorientationchange!==void 0?this.connect(dojo.global,"onorientationchange","onResize"):this.connect(dojo.global,"onresize","onResize")},startup:function(){var a=this;setTimeout(function(){a.onResize()},0)},onResize:function(){var a,b=dojo.marginBox(this.domNode.parentNode).w,e=this._fixedButtonWidth,f=this._fixedButtonMargin,d=this.containerNode.childNodes,c=[];for(a=0;a<d.length;a++){var g=
d[a];g.nodeType==1&&dojo.hasClass(g,this._clsName)&&c.push(g)}if(this.barType=="segmentedControl"){d=b;for(a=b=0;a<c.length;a++)d-=dojo.marginBox(c[a]).w,c[a].style.marginTop="3px",b+=c[a].offsetWidth;d=Math.floor(d/2);a=dijit.getEnclosingWidget(this.domNode.parentNode);a=this.inHeading||a instanceof dojox.mobile.Heading;this.containerNode.style.padding="3px 0px 0px "+(a?0:d)+"px";a&&dojo.style(this.domNode,{background:"none",border:"none",width:b+2+"px"})}else if(d=Math.floor((b-(e+f*2)*c.length)/
2),b<this._largeScreenWidth||d<0){for(a=0;a<c.length;a++)c[a].style.width=Math.round(98/c.length)+"%",c[a].style.margin="0px";this.containerNode.style.padding="0px 0px 0px 1%"}else{for(a=0;a<c.length;a++)c[a].style.width=e+"px",c[a].style.margin="0 "+f+"px";this.containerNode.style.padding="0px 0px 0px "+d+"px"}}}),dojo.declare("dojox.mobile.TabBarButton",dojox.mobile.AbstractItem,{icon1:"",icon2:"",iconPos1:"",iconPos2:"",selected:!1,transition:"none",tag:"LI",selectOne:!0,inheritParams:function(){var a=
this.getParentWidget();if(this.parent=a){if(!this.transition)this.transition=a.transition;if(!this.icon1)this.icon1=a.iconBase;if(!this.iconPos1)this.iconPos1=a.iconPos;if(!this.icon2)this.icon2=a.iconBase||this.icon1;if(!this.iconPos2)this.iconPos2=a.iconPos||this.iconPos1}},buildRendering:function(){this.inheritParams();var a=this.anchorNode=dojo.create("A",{className:"mblTabBarButtonAnchor"});this.connect(a,"onclick","onClick");var b=dojo.create("DIV",{className:"mblTabBarButtonDiv"},a),b=dojo.create("DIV",
{className:"mblTabBarButtonDiv mblTabBarButtonDivInner"},b);this.img1=dojo.create("IMG",{className:"mblTabBarButtonIcon",src:this.icon1},b);this.img1.style.visibility=this.selected?"hidden":"";dojox.mobile.setupIcon(this.img1,this.iconPos1);this.img1.onload=function(){this.style.width=this.width+"px";this.style.height=this.height+"px"};this.img2=dojo.create("IMG",{className:"mblTabBarButtonIcon",src:this.icon2},b);this.img2.style.visibility=this.selected?"":"hidden";dojox.mobile.setupIcon(this.img2,
this.iconPos2);this.img2.onload=function(){this.style.width=this.width+"px";this.style.height=this.height+"px"};var b=this.box=dojo.create("DIV",{className:"mblTabBarButtonTextBox"},a),e=this.srcNodeRef;if(e)for(var f=0,d=e.childNodes.length;f<d;f++)b.appendChild(e.firstChild);this.label&&b.appendChild(dojo.doc.createTextNode(this.label));this.containerNode=this.domNode=this.srcNodeRef||dojo.create(this.tag);dojo.addClass(this.domNode,(this.parent?this.parent._clsName:"mblTabBarButton")+(this.selected?
" mblTabButtonSelected":""));this.domNode.appendChild(a);this.createDomButton(this.domNode,a)},startup:function(){var a=this.getParentWidget();if((this.parent=a)&&a.barType=="segmentedControl")dojo.removeClass(this.domNode,"mblTabBarButton"),dojo.addClass(this.domNode,a._clsName),this.box.className=""},select:function(a){if(a)this.selected=!1,dojo.removeClass(this.domNode,"mblTabButtonSelected");else{this.selected=!0;dojo.addClass(this.domNode,"mblTabButtonSelected");for(var a=0,b=this.domNode.parentNode.childNodes;a<
b.length;a++)if(b[a].nodeType==1){var e=dijit.byNode(b[a]);e&&e!=this&&e.select(!0)}}this.img1.style.visibility=this.selected?"hidden":"";this.img2.style.visibility=this.selected?"":"hidden"},onClick:function(){this.defaultClickAction()}}));