/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.TabContainer"]||(dojo._hasResource["dojox.mobile.TabContainer"]=!0,dojo.provide("dojox.mobile.TabContainer"),dojo.require("dojox.mobile"),dojo.declare("dojox.mobile.TabContainer",dijit._WidgetBase,{iconBase:"",iconPos:"",fixedHeader:!1,constructor:function(){dojo.deprecated("dojox.mobile.TabContainer is deprecated","use dojox.mobile.TabBar instead",2)},buildRendering:function(){var a=this.domNode=this.srcNodeRef;a.className="mblTabContainer";for(var b=this.tabHeaderNode=
dojo.doc.createElement("DIV"),f=this.containerNode=dojo.doc.createElement("DIV"),d=0,g=a.childNodes.length;d<g;d++)f.appendChild(a.removeChild(a.firstChild));b.className="mblTabPanelHeader";b.align="center";this.fixedHeader?(d=dijit.getEnclosingWidget(this.domNode.parentNode),d.domNode.insertBefore(b,d.domNode.firstChild),dojo.style(b,{position:"absolute",width:"100%",top:"0px",zIndex:"1"}),d.fixedHeader=b):a.appendChild(b);f.className="mblTabPanelPane";a.appendChild(f)},startup:function(){this.createTabButtons();
this.inherited(arguments)},createTabButtons:function(){var a=dojo.doc.createElement("DIV");a.align="center";for(var b=dojo.doc.createElement("TABLE"),f=b.insertRow(-1).insertCell(-1),d=this.containerNode.childNodes,g=0;g<d.length;g++){var c=d[g];if(c.nodeType==1){var e=dijit.byNode(c);if(e.selected||!this._selectedPane)this._selectedPane=e;c.style.display="none";c=dojo.doc.createElement("DIV");c.className="mblTabButton";if(e.icon){var h=dojo.create("DIV"),i=dojo.create("IMG");h.className="mblTabButtonImgDiv";
i.src=e.icon;dojox.mobile.setupIcon(i,e.iconPos);h.appendChild(i);c.appendChild(h)}c.appendChild(dojo.doc.createTextNode(e.label));c.pane=e;e.tab=c;this.connect(c,"onclick","onTabClick");f.appendChild(c)}}a.appendChild(b);this.tabHeaderNode.appendChild(a);this.selectTab(this._selectedPane.tab)},selectTab:function(a){this._selectedPane.domNode.style.display="none";dojo.removeClass(this._selectedPane.tab,"mblTabButtonSelected");this._selectedPane=a.pane;this._selectedPane.domNode.style.display="";dojo.addClass(a,
"mblTabButtonSelected");if(dojo.isBB){var b=a.nextSibling;a.parentNode.insertBefore(a.parentNode.removeChild(a),b)}a=dijit.getEnclosingWidget(this.domNode.parentNode);this.fixedHeader&&a&&a.scrollTo&&a.scrollTo({y:0});a.flashScrollBar&&a.flashScrollBar()},onTabClick:function(a){var b=a.currentTarget;dojo.addClass(b,"mblTabButtonHighlighted");setTimeout(function(){dojo.removeClass(b,"mblTabButtonHighlighted")},200);this.selectTab(b)}}),dojo.declare("dojox.mobile.TabPane",dijit._WidgetBase,{label:"",
icon:"",iconPos:"",selected:!1,inheritParams:function(){var a=this.getParentWidget();if(a){if(!this.icon)this.icon=a.iconBase;if(!this.iconPos)this.iconPos=a.iconPos}},buildRendering:function(){this.inheritParams();this.domNode=this.containerNode=this.srcNodeRef||dojo.doc.createElement("DIV");this.domNode.className="mblTabPane"},getParentWidget:function(){var a=this.srcNodeRef||this.domNode;return a&&a.parentNode?dijit.getEnclosingWidget(a.parentNode):null}}));