/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.secure.capability"])dojo._hasResource["dojox.secure.capability"]=!0,dojo.provide("dojox.secure.capability"),dojox.secure.badProps=/^__|^(apply|call|callee|caller|constructor|eval|prototype|this|unwatch|valueOf|watch)$|__$/,dojox.secure.capability={keywords:["break","case","catch","const","continue","debugger","default","delete","do","else","enum","false","finally","for","function","if","in","instanceof","new","null","yield","return","switch","throw","true","try","typeof",
"var","void","while"],validate:function(a,e,f){function n(a){var d={};a.replace(/#\d+/g,function(a){var a=h[a.substring(1)],b;for(b in a){if(b==j)throw b;b=="this"&&a[":method"]&&a["this"]==1&&(b=j);b!=":method"&&(d[b]=2)}});a.replace(/(\W|^)([a-z_\$A-Z][\w_\$]*)/g,function(a,b,k){if(k.charAt(0)=="_")throw Error("Names may not start with _");d[k]=1});return d}function l(a,d,c,b,e,g){function f(a,b,d,c){c.replace(/,?([a-z\$A-Z][_\w\$]*)/g,function(a,b){if(b=="Class")throw Error("Class is reserved");
delete i[b]})}g.replace(/(^|,)0:\s*function#(\d+)/g,function(a,b,d){h[d][":method"]=1});g=g.replace(/(^|[^_\w\$])Class\s*\(\s*([_\w\$]+\s*,\s*)*#(\d+)/g,function(a,b,d,c){delete h[c][j];return(b||"")+(d||"")+"#"+c});i=n(g,d);d&&f(a,c,c,e);g.replace(/(\W|^)(var) ([ \t,_\w\$]+)/g,f);return(c||"")+(b||"")+"#"+(h.push(i)-1)}for(var m=this.keywords,c=0;c<m.length;c++)f[m[c]]=!0;var j="|this| keyword in object literal without a Class call",h=[];if(a.match(/[\u200c-\u200f\u202a-\u202e\u206a-\u206f\uff00-\uffff]/))throw Error("Illegal unicode characters detected");
if(a.match(/\/\*@cc_on/))throw Error("Conditional compilation token is not allowed");a=a.replace(/\\["'\\\/bfnrtu]/g,"@").replace(/\/\/.*|\/\*[\w\W]*?\*\/|\/(\\[\/\\]|[^*\/])(\\.|[^\/\n\\])*\/[gim]*|("[^"]*")|('[^']*')/g,function(a){return a.match(/^\/\/|^\/\*/)?" ":"0"}).replace(/\.\s*([a-z\$_A-Z][\w\$_]*)|([;,{])\s*([a-z\$_A-Z][\w\$_]*\s*):/g,function(a,d,c,b){d=d||b;if(/^__|^(apply|call|callee|caller|constructor|eval|prototype|this|unwatch|valueOf|watch)$|__$/.test(d))throw Error("Illegal property name "+
d);return c&&c+"0:"||"~"});a.replace(/([^\[][\]\}]\s*=)|((\Wreturn|\S)\s*\[\s*\+?)|([^=!][=!]=[^=])/g,function(a){if(!a.match(/((\Wreturn|[=\&\|\:\?\,])\s*\[)|\[\s*\+$/))throw Error("Illegal operator "+a.substring(1));});var a=a.replace(RegExp("("+e.join("|")+")[\\s~]*\\(","g"),function(){return"new("}),i;do e=a.replace(/((function|catch)(\s+[_\w\$]+)?\s*\(([^\)]*)\)\s*)?{([^{}]*)}/g,l);while(e!=a&&(a=e));l(0,0,0,0,0,a);for(c in i)if(!(c in f))throw Error("Illegal reference to "+c);}};