/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.secure.DOM"])dojo._hasResource["dojox.secure.DOM"]=!0,dojo.provide("dojox.secure.DOM"),dojo.require("dojox.lang.observable"),dojox.secure.DOM=function(e){function f(a){if(a){if(a.nodeType){var b=n(a);if(a.nodeType==1&&typeof b.style=="function")b.style=r(a.style),b.ownerDocument=i,b.childNodes={__get__:function(b){return f(a.childNodes[b])},length:0};return b}if(a&&typeof a=="object"){if(a.__observable)return a.__observable;b=a instanceof Array?[]:{};a.__observable=b;
for(var d in a)d!="__observable"&&(b[d]=f(a[d]));b.data__=a;return b}if(typeof a=="function"){var c=function(a){return typeof a=="function"?function(){for(var b=0;b<arguments.length;b++)arguments[b]=f(arguments[b]);return c(a.apply(f(this),arguments))}:dojox.secure.unwrap(a)};return function(){a.safetyCheck&&a.safetyCheck.apply(c(this),arguments);for(var b=0;b<arguments.length;b++)arguments[b]=c(arguments[b]);return f(a.apply(c(this),arguments))}}}return a}function g(a){a+="";if(a.match(/behavior:|content:|javascript:|binding|expression|\@import/))throw Error("Illegal CSS");
var b=e.id||(e.id="safe"+(""+Math.random()).substring(2));return a.replace(/(\}|^)\s*([^\{]*\{)/g,function(a,c,f){return c+" #"+b+" "+f})}function o(a){if(a.match(/:/)&&!a.match(/^(http|ftp|mailto)/))throw Error("Unsafe URL "+a);}function k(a){if(a&&a.nodeType==1){if(a.tagName.match(/script/i)){var b=a.src;b&&b!=""?(a.parentNode.removeChild(a),dojo.xhrGet({url:b,secure:!0}).addCallback(function(a){i.evaluate(a)})):(b=a.innerHTML,a.parentNode.removeChild(a),f.evaluate(b))}if(a.tagName.match(/link/i))throw Error("illegal tag");
if(a.tagName.match(/style/i)){var d=function(b){a.styleSheet?a.styleSheet.cssText=b:(b=j.createTextNode(b),a.childNodes[0]?a.replaceChild(b,a.childNodes[0]):a.appendChild(b))};if((b=a.src)&&b!="")alert("src"+b),a.src=null,dojo.xhrGet({url:b,secure:!0}).addCallback(function(a){d(g(a))});d(g(a.innerHTML))}a.style&&g(a.style.cssText);a.href&&o(a.href);a.src&&o(a.src);for(var c,b=0;c=a.attributes[b++];)if(c.name.substring(0,2)=="on"&&c.value!="null"&&c.value!="")throw Error("event handlers not allowed in the HTML, they must be set with element.addEventListener");
c=a.childNodes;for(var b=0,e=c.length;b<e;b++)k(c[b])}}function l(a){var b=document.createElement("div");if(a.match(/<object/i))throw Error("The object tag is not allowed");b.innerHTML=a;k(b);return b}function m(a,b){return function(d,c){k(c[b]);return d[a](c[0])}}function p(a){return dojox.lang.makeObservable(function(a,d){return a[d]},a,function(a,d,c,e){for(var g=0;g<e.length;g++)e[g]=unwrap(e[g]);return h[c]?f(h[c].call(a,d,e)):f(d[c].apply(d,e))},h)}unwrap=dojox.secure.unwrap;var j=e.ownerDocument,
i={getElementById:function(a){a:if(a=j.getElementById(a)){var b=a;do if(b==e){a=f(a);break a}while(b=b.parentNode);a=null}return a},createElement:function(a){return f(j.createElement(a))},createTextNode:function(a){return f(j.createTextNode(a))},write:function(a){for(a=l(a);a.childNodes.length;)e.appendChild(a.childNodes[0])}};i.open=i.close=function(){};var q={innerHTML:function(a,b){console.log("setting innerHTML");a.innerHTML=l(b).innerHTML},outerHTML:function(){throw Error("Can not set this property");
}},h={appendChild:m("appendChild",0),insertBefore:m("insertBefore",0),replaceChild:m("replaceChild",1),cloneNode:function(a,b){return a.cloneNode(b[0])},addEventListener:function(a,b){dojo.connect(a,"on"+b[0],this,function(a){a=n(a||window.event);b[1].call(this,a)})}};h.childNodes=h.style=h.ownerDocument=function(){};var n=p(function(a,b,d){if(q[b])q[b](a,d);a[b]=d}),s={behavior:1,MozBinding:1},r=p(function(a,b,d){s[b]||(a[b]=g(d))});f.safeHTML=l;f.safeCSS=g;return f},dojox.secure.unwrap=function(e){return e&&
e.data__||e};