/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.secure.sandbox"])dojo._hasResource["dojox.secure.sandbox"]=!0,dojo.provide("dojox.secure.sandbox"),dojo.require("dojox.secure.DOM"),dojo.require("dojox.secure.capability"),dojo.require("dojo.NodeList-fx"),function(){if({}.__proto__){var a=function(a){var b=Array.prototype[a];if(b&&!b.fixed)(Array.prototype[a]=function(){if(this==window)throw new TypeError("Called with wrong this");return b.apply(this,arguments)}).fixed=!0};a("concat");a("reverse");a("sort");a("slice");
a("forEach");a("filter");a("reduce");a("reduceRight");a("every");a("map");a("some")}var c=function(){return dojo.xhrGet.apply(dojo,arguments)};dojox.secure.sandbox=function(a){var b=dojox.secure.DOM(a),a=b(a),g=dojox.secure._safeDojoFunctions(a,b),f=[],d=["isNaN","isFinite","parseInt","parseFloat","escape","unescape","encodeURI","encodeURIComponent","decodeURI","decodeURIComponent","alert","confirm","prompt","Error","EvalError","RangeError","ReferenceError","SyntaxError","TypeError","Date","RegExp",
"Number","Object","Array","String","Math","setTimeout","setInterval","clearTimeout","clearInterval","dojo","get","set","forEach","load","evaluate"],e;for(e in g)d.push(e),f.push("var "+e+"=dojo."+e);eval(f.join(";"));b.load=function(a){if(a.match(/^[\w\s]*:/))throw Error("Access denied to cross-site requests");return c({url:new g._Url(b.rootUrl,a)+"",secure:!0})};b.evaluate=function(a){dojox.secure.capability.validate(a,d,{document:1,element:1});a.match(/^\s*[\[\{]/)?eval("("+a+")"):eval(a)};return{loadJS:function(a){b.rootUrl=
a;return c({url:a,secure:!0}).addCallback(function(a){b.evaluate(a)})},loadHTML:function(d){b.rootUrl=d;return c({url:d,secure:!0}).addCallback(function(d){a.innerHTML=d})},evaluate:function(a){return b.evaluate(a)}}}}(),dojox.secure._safeDojoFunctions=function(a,c){var h=["mixin","require","isString","isArray","isFunction","isObject","isArrayLike","isAlien","hitch","delegate","partial","trim","disconnect","subscribe","unsubscribe","Deferred","toJson","style","attr"],b=dojox.secure.unwrap;dojo.NodeList.prototype.addContent.safetyCheck=
function(a){c.safeHTML(a)};dojo.NodeList.prototype.style.safetyCheck=function(a,b){if(a=="behavior")throw Error("Can not set behavior");c.safeCSS(b)};dojo.NodeList.prototype.attr.safetyCheck=function(a,b){if(b&&(a=="src"||a=="href"||a=="style"))throw Error("Illegal to set "+a);};for(var g={query:function(d,e){return c(dojo.query(d,b(e||a)))},connect:function(a,e){var c=a;arguments[0]=b(a);if(c!=arguments[0]&&e.substring(0,2)!="on")throw Error("Invalid event name for element");return dojo.connect.apply(dojo,
arguments)},body:function(){return a},byId:function(b){return a.ownerDocument.getElementById(b)},fromJson:function(a){dojox.secure.capability.validate(a,[],{});return dojo.fromJson(a)}},f=0;f<h.length;f++)g[h[f]]=dojo[h[f]];return g};