/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced._FocusManager"]||(dojo._hasResource["dojox.grid.enhanced._FocusManager"]=!0,dojo.provide("dojox.grid.enhanced._FocusManager"),dojo.declare("dojox.grid.enhanced._FocusArea",null,{constructor:function(a,c){this._fm=c;this._evtStack=[a.name];var b=function(){return!0};a.onFocus=a.onFocus||b;a.onBlur=a.onBlur||b;a.onMove=a.onMove||b;a.onKeyUp=a.onKeyUp||b;a.onKeyDown=a.onKeyDown||b;dojo.mixin(this,a)},move:function(a,c,b){if(this.name){var d;for(d=this._evtStack.length-
1;d>=0;--d)if(this._fm._areas[this._evtStack[d]].onMove(a,c,b)===!1)return!1}return!0},_onKeyEvent:function(a,c){if(this.name){var b,d=this._evtStack.length;for(b=d-1;b>=0;--b)if(this._fm._areas[this._evtStack[b]][c](a,!1)===!1)return!1;for(b=0;b<d;++b)if(this._fm._areas[this._evtStack[b]][c](a,!0)===!1)return!1}return!0},keydown:function(a){return this._onKeyEvent(a,"onKeyDown")},keyup:function(a){return this._onKeyEvent(a,"onKeyUp")},contentMouseEventPlanner:function(){return 0},headerMouseEventPlanner:function(){return 0}}),
dojo.declare("dojox.grid.enhanced._FocusManager",dojox.grid._FocusManager,{_stopEvent:function(a){try{a&&a.preventDefault&&dojo.stopEvent(a)}catch(c){}},constructor:function(a){this.grid=a;this._areas={};this._areaQueue=[];this._contentMouseEventHandlers=[];this._headerMouseEventHandlers=[];this._currentAreaIdx=-1;this._gridBlured=!0;this._connects.push(dojo.connect(a,"onBlur",this,"_doBlur"));this._connects.push(dojo.connect(a.scroller,"renderPage",this,"_delayedCellFocus"));this.addArea({name:"header",
onFocus:dojo.hitch(this,this.focusHeader),onBlur:dojo.hitch(this,this._blurHeader),onMove:dojo.hitch(this,this._navHeader),getRegions:dojo.hitch(this,this._findHeaderCells),onRegionFocus:dojo.hitch(this,this.doColHeaderFocus),onRegionBlur:dojo.hitch(this,this.doColHeaderBlur),onKeyDown:dojo.hitch(this,this._onHeaderKeyDown)});this.addArea({name:"content",onFocus:dojo.hitch(this,this._focusContent),onBlur:dojo.hitch(this,this._blurContent),onMove:dojo.hitch(this,this._navContent),onKeyDown:dojo.hitch(this,
this._onContentKeyDown)});this.addArea({name:"editableCell",onFocus:dojo.hitch(this,this._focusEditableCell),onBlur:dojo.hitch(this,this._blurEditableCell),onKeyDown:dojo.hitch(this,this._onEditableCellKeyDown),onContentMouseEvent:dojo.hitch(this,this._onEditableCellMouseEvent),contentMouseEventPlanner:function(){return-1}});this.placeArea("header");this.placeArea("content");this.placeArea("editableCell");this.placeArea("editableCell","above","content")},destroy:function(){for(var a in this._areas){var c=
this._areas[a];dojo.forEach(c._connects,dojo.disconnect);c._connects=null;c.uninitialize&&c.uninitialize()}this.inherited(arguments)},addArea:function(a){a.name&&dojo.isString(a.name)&&(this._areas[a.name]&&dojo.forEach(a._connects,dojo.disconnect),this._areas[a.name]=new dojox.grid.enhanced._FocusArea(a,this),a.onHeaderMouseEvent&&this._headerMouseEventHandlers.push(a.name),a.onContentMouseEvent&&this._contentMouseEventHandlers.push(a.name))},getArea:function(a){return this._areas[a]},_bindAreaEvents:function(){var a,
c,b=this._areas;dojo.forEach(this._areaQueue,function(d){a=b[d];if(!a._initialized&&dojo.isFunction(a.initialize))a.initialize(),a._initialized=!0;if(a.getRegions)a._regions=a.getRegions()||[],dojo.forEach(a._connects||[],dojo.disconnect),a._connects=[],dojo.forEach(a._regions,function(b){a.onRegionFocus&&(c=dojo.connect(b,"onfocus",a.onRegionFocus),a._connects.push(c));a.onRegionBlur&&(c=dojo.connect(b,"onblur",a.onRegionBlur),a._connects.push(c))})})},removeArea:function(a){var c=this._areas[a];
if(c){this.ignoreArea(a);var b=dojo.indexOf(this._contentMouseEventHandlers,a);b>=0&&this._contentMouseEventHandlers.splice(b,1);b=dojo.indexOf(this._headerMouseEventHandlers,a);b>=0&&this._headerMouseEventHandlers.splice(b,1);dojo.forEach(c._connects,dojo.disconnect);c.uninitialize&&c.uninitialize();delete this._areas[a]}},currentArea:function(a,c){var b,d=this._currentAreaIdx;if(dojo.isString(a)&&(b=dojo.indexOf(this._areaQueue,a))>=0){if(d!=b){this.tabbingOut=!1;if(c&&d>=0&&d<this._areaQueue.length)this._areas[this._areaQueue[d]].onBlur();
this._currentAreaIdx=b}}else return d<0||d>=this._areaQueue.length?new dojox.grid.enhanced._FocusArea({},this):this._areas[this._areaQueue[this._currentAreaIdx]];return null},placeArea:function(a,c,b){if(this._areas[a]){var d=dojo.indexOf(this._areaQueue,b);switch(c){case "after":d>=0&&++d;case "before":if(d>=0){this._areaQueue.splice(d,0,a);break}default:this._areaQueue.push(a);break;case "above":var e=!0;case "below":(c=this._areas[b])&&(e?c._evtStack.push(a):c._evtStack.splice(0,0,a))}}},ignoreArea:function(a){this._areaQueue=
dojo.filter(this._areaQueue,function(c){return c!=a})},focusArea:function(a,c){var b;b=typeof a=="number"?a<0?this._areaQueue.length+a:a:dojo.indexOf(this._areaQueue,dojo.isString(a)?a:a&&a.name);b<0&&(b=0);b-=this._currentAreaIdx;this._gridBlured=!1;if(b)this.tab(b,c);else this.currentArea().onFocus(c,b)},tab:function(a,c){this.tabbingOut=this._gridBlured=!1;if(a!==0){var b=this._currentAreaIdx,d=a>0?1:-1;if(b<0||b>=this._areaQueue.length)b=this._currentAreaIdx+=a;else{var e=this._areas[this._areaQueue[b]].onBlur(c,
a);if(e===!0)b=this._currentAreaIdx+=a;else if(dojo.isString(e)&&this._areas[e])b=this._currentAreaIdx=dojo.indexOf(this._areaQueue,e)}for(;b>=0&&b<this._areaQueue.length;b+=d)if(this._currentAreaIdx=b,this._areaQueue[b]&&this._areas[this._areaQueue[b]].onFocus(c,a))return;this.tabbingOut=!0;a<0?(this._currentAreaIdx=-1,dijit.focus(this.grid.domNode)):(this._currentAreaIdx=this._areaQueue.length,dijit.focus(this.grid.lastFocusNode))}},_onMouseEvent:function(a,c){for(var b=a.toLowerCase(),d=this["_"+
b+"MouseEventHandlers"],e=dojo.map(d,function(a){return{area:a,idx:this._areas[a][b+"MouseEventPlanner"](c,d)}},this).sort(function(a,b){return b.idx-a.idx}),f=dojo.map(e,function(){return e.area}),g=e.length;--g>=0;)if(this._areas[e[g].area]["on"+a+"MouseEvent"](c,f)===!1)break},contentMouseEvent:function(a){this._onMouseEvent("Content",a)},headerMouseEvent:function(a){this._onMouseEvent("Header",a)},initFocusView:function(){this.focusView=this.grid.views.getFirstScrollingView()||this.focusView||
this.grid.views.views[0];this._bindAreaEvents()},isNavHeader:function(){return this._areaQueue[this._currentAreaIdx]=="header"},previousKey:function(a){this.tab(-1,a)},nextKey:function(a){this.tab(1,a)},setFocusCell:function(a,c){if(a)this.currentArea(this.grid.edit.isEditing()?"editableCell":"content",!0),this._focusifyCellNode(!1),this.cell=a,this.rowIndex=c,this._focusifyCellNode(!0);this.grid.onCellFocus(this.cell,this.rowIndex)},doFocus:function(a){if(a&&a.target==a.currentTarget&&!this.tabbingOut){if(this._gridBlured)this._gridBlured=
!1,this._currentAreaIdx<0||this._currentAreaIdx>=this._areaQueue.length?this.focusArea(0,a):this.focusArea(this._currentAreaIdx,a)}else this.tabbingOut=!1;dojo.stopEvent(a)},_doBlur:function(){this._gridBlured=!0},doLastNodeFocus:function(a){this.tabbingOut?this.tabbingOut=!1:this.focusArea(-1,a)},_delayedHeaderFocus:function(){this.isNavHeader()&&this.focusHeader()},_delayedCellFocus:function(){this.currentArea("header",!0);this.focusArea(this._currentAreaIdx)},_changeMenuBindNode:function(a,c){var b=
this.grid.headerMenu;if(b&&this._contextMenuBindNode==a)b.unBindDomNode(a),b.bindDomNode(c),this._contextMenuBindNode=c},focusHeader:function(a,c){var b=!1;this.inherited(arguments);this._colHeadNode&&dojo.style(this._colHeadNode,"display")!="none"&&(dijit.focus(this._colHeadNode),this._stopEvent(a),b=!0);return b},_blurHeader:function(){this._colHeadNode&&dojo.removeClass(this._colHeadNode,this.focusClass);dojo.removeAttr(this.grid.domNode,"aria-activedescendant");this._changeMenuBindNode(this.grid.domNode,
this.grid.viewsHeaderNode);this._colHeadNode=this._colHeadFocusIdx=null;return!0},_navHeader:function(a,c,b){var d=c<0?-1:1,e=dojo.indexOf(this._findHeaderCells(),this._colHeadNode);e>=0&&b.shiftKey&&b.ctrlKey?this.colSizeAdjust(b,e,d*5):this.move(a,c)},_onHeaderKeyDown:function(a,c){if(c){var b=dojo.keys;switch(a.keyCode){case b.ENTER:case b.SPACE:b=this.getHeaderIndex(),b>=0&&!this.grid.pluginMgr.isFixedCell(a.cell)&&(this.grid.setSortIndex(b,null,a),dojo.stopEvent(a))}}return!0},_setActiveColHeader:function(){this.inherited(arguments);
dijit.focus(this._colHeadNode)},findAndFocusGridCell:function(){this._focusContent()},_focusContent:function(a){var c=!0,b=this.grid.rowCount===0;if(this.isNoFocusCell()&&!b){for(var b=0,d=this.grid.getCell(0);d&&d.hidden;d=this.grid.getCell(++b));this.setFocusIndex(0,d?b:0)}else this.cell&&!b?this.focusView&&!this.focusView.rowNodes[this.rowIndex]?(this.grid.scrollToRow(this.rowIndex),this.focusGrid()):this.setFocusIndex(this.rowIndex,this.cell.index):c=!1;c&&this._stopEvent(a);return c},_blurContent:function(){this._focusifyCellNode(!1);
return!0},_navContent:function(a,c,b){if(!(this.rowIndex===0&&a<0||this.rowIndex===this.grid.rowCount-1&&a>0))this._colHeadNode=null,this.move(a,c,b),b&&dojo.stopEvent(b)},_onContentKeyDown:function(a,c){if(c){var b=dojo.keys,d=this.grid.scroller;switch(a.keyCode){case b.ENTER:case b.SPACE:b=this.grid;if(b.indirectSelection)break;b.selection.clickSelect(this.rowIndex,dojo.isCopyKey(a),a.shiftKey);b.onRowClick(a);dojo.stopEvent(a);break;case b.PAGE_UP:this.rowIndex!==0&&(this.rowIndex!=d.firstVisibleRow+
1?this._navContent(d.firstVisibleRow-this.rowIndex,0):(this.grid.setScrollTop(d.findScrollTop(this.rowIndex-1)),this._navContent(d.firstVisibleRow-d.lastVisibleRow+1,0)),dojo.stopEvent(a));break;case b.PAGE_DOWN:this.rowIndex+1!=this.grid.rowCount&&(dojo.stopEvent(a),this.rowIndex!=d.lastVisibleRow-1?this._navContent(d.lastVisibleRow-this.rowIndex-1,0):(this.grid.setScrollTop(d.findScrollTop(this.rowIndex+1)),this._navContent(d.lastVisibleRow-d.firstVisibleRow-1,0)),dojo.stopEvent(a))}}return!0},
_blurFromEditableCell:!1,_isNavigating:!1,_navElems:null,_focusEditableCell:function(a,c){var b=!1;if(this._isNavigating)b=!0;else if(this.grid.edit.isEditing()&&this.cell){if(this._blurFromEditableCell||!this._blurEditableCell(a,c))this.setFocusIndex(this.rowIndex,this.cell.index),b=!0;this._stopEvent(a)}return b},_applyEditableCell:function(){try{this.grid.edit.apply()}catch(a){console.warn("_FocusManager._applyEditableCell() error:",a)}},_blurEditableCell:function(a,c){this._blurFromEditableCell=
!1;if(this._isNavigating){var b=!0;if(a)var d=this._navElems,b=d.lowest||d.first,d=d.last||d.highest||b,b=(dojo.isIE?a.srcElement:a.target)==(c>0?d:b);return b?(this._isNavigating=!1,"content"):!1}else if(this.grid.edit.isEditing()&&this.cell){if(!c||typeof c!="number")return!1;for(var b=c>0?1:-1,d=this.grid.layout.cellCount,e,f=this.cell.index+b;f>=0&&f<d;f+=b)if(e=this.grid.getCell(f),e.editable)return this.cell=e,this._blurFromEditableCell=!0,!1;if((this.rowIndex>0||b==1)&&(this.rowIndex<this.grid.rowCount||
b==-1)){this.rowIndex+=b;for(f=b>0?0:d-1;f>=0&&f<d;f+=b)if(e=this.grid.getCell(f),e.editable){this.cell=e;break}this._applyEditableCell();return"content"}}return!0},_initNavigatableElems:function(){this._navElems=dijit._getTabNavigable(this.cell.getNode(this.rowIndex))},_onEditableCellKeyDown:function(a,c){var b=dojo.keys,d=this.grid,e=d.edit,f=!1,g=!0;switch(a.keyCode){case b.ENTER:c&&e.isEditing()&&(this._applyEditableCell(),f=!0,dojo.stopEvent(a));case b.SPACE:if(!c&&this._isNavigating){g=!1;break}if(c){if(!this.cell.editable&&
this.cell.navigatable&&(this._initNavigatableElems(),b=this._navElems.lowest||this._navElems.first)){this._isNavigating=!0;dijit.focus(b);dojo.stopEvent(a);this.currentArea("editableCell",!0);break}!f&&!e.isEditing()&&!d.pluginMgr.isFixedCell(this.cell)&&e.setEditCell(this.cell,this.rowIndex);f?this.currentArea("content",!0):this.cell.editable&&d.canEdit()&&this.currentArea("editableCell",!0)}break;case b.PAGE_UP:case b.PAGE_DOWN:!c&&e.isEditing()&&(g=!1);break;case b.ESCAPE:c||(e.cancel(),this.currentArea("content",
!0))}return g},_onEditableCellMouseEvent:function(a){if(a.type=="click"){var c=this.cell||a.cell;if(c&&!c.editable&&c.navigatable){if(this._initNavigatableElems(),this._navElems.lowest||this._navElems.first){var b=dojo.isIE?a.srcElement:a.target;if(b!=c.getNode(a.rowIndex))return this._isNavigating=!0,this.focusArea("editableCell",a),dijit.focus(b),!1}}else if(this.grid.singleClickEdit)return this.currentArea("editableCell"),!1}return!0}}));