<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>PHProjekt</title>
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
    <style type="text/css">
        @import "<?php echo $this->webpath; ?>css/themes/phprojekt/phprojektCssCompiler.php";
    </style>
    <script type="text/javascript">
        var djConfig = {isDebug: false, parseOnLoad: false, preventBackButtonFix: false,
                        bindEncoding: "utf-8", dojoIframeHistoryUrl: '../resources/iframe_history.html',
                        locale: '<?php echo $this->language; ?>', useCommentedJson: true};
    </script>
    <script type="text/javascript" src="<?php echo $this->webpath; ?>dojo/dojo/dojo.js"></script>
    <?php
    if ($this->compressedDojo) {
    ?>
    <script type="text/javascript" src="<?php echo $this->webpath; ?>dojo/dojo/mydojo.js"></script>
    <?php
    }
    ?>
    <script type="text/javascript" src="<?php echo $this->url(array('controller' => 'js', 'action' => 'index')); ?>"></script>
    <script type="text/javascript">
        function init() {
            if (document.layers) {
                availHeight = window.innerHeight + window.pageYOffset;
            } else if (document.all) {
                availHeight = document.documentElement.clientHeight + document.documentElement.scrollTop;
            } else if (document.getElementById) {
                availHeight = window.innerHeight + window.pageYOffset;
            }
            dojo.style(dojo.byId('completeContent'), "height", availHeight + "px");
            dijit.byId('completeContent').resize();

            dojo.style(dojo.byId('completeCenterContent'), "height", (availHeight - 55) + "px");
            dijit.byId('completeCenterContent').resize();
        }
        dojo.addOnLoad(init);
        window.onresize = function(){
            init();
        };
    </script>
</head>
<body class="phprojekt">
    <script type="text/javascript">
        var main = new phpr.Main("<?php echo $this->webpath; ?>","Project",1,'<?php echo $this->language; ?>');
    </script>
</body>
</html>
<!-- template: index.phml -->