<div id="completeContent" dojoType="dijit.layout.ContentPane"
    style="width: 100%; height: 1000px; overflow: hidden;">
    <!-- Top Bar menu -->
    <div dojoType="dijit.layout.ContentPane" id="header" region="top" splitter="false"
    style="height:55px;">
        <img class="left" src="<?php echo $this->webpath; ?>img/logo.png" alt="PHProjekt 6" />
        <div id="mainNavigation" class="right align-right">
        </div>
    </div>
    <!-- Left Content -->
    <div id="navigation-container"
    style="width:15%; height: 100%">
        <div dojoType="dijit.layout.ContentPane">
            <div id="subheader" class="block">
                <div id="navigation-container-titel">
                </div>
            </div>
            <!-- Tree menu -->
            <div id="tree-navigation" dojoType="dijit.layout.ContentPane">
                <div dojoType="dijit.layout.ContentPane" id="treeBox">
                </div>
            </div>
        </div>
    </div>
    <!-- Center Content -->
    <div dojoType="dijit.layout.ContentPane"
    style="position: absolute; top: 55px; left: 16%; width: 100%;">
        <div dojoType="dijit.layout.ContentPane" design="sidebar"
        style="width: 84%; height: 100%;">
            <!-- Second Top Bar -->
            <div dojoType="dijit.layout.ContentPane" region="top" class="block"
            style="height: 7%;" splitter="false">
                <!-- Submodule navigation -->
                <div class="column left span-17 append-1 align-left" id="subModuleNavigation">
                </div>
                <!-- Add / Save Buttons -->
                <div id="buttonRow" class="align-right append-0">
                </div>
                <!-- spaces -->
                <hr class="space"/>
                <hr class="space"/>
                <hr class="space"/>
                <!-- Exception Form -->
                <div id="serverFeedback" class="prepend-24">
                <?php
                if ($this->message) {
                    echo '<div class="error">'.$this->message.'</div>';
                }
                if ($this->errors) {
                    echo '<div class="error">'.$this->errors.'</div>';
                }
                ?>
                </div>
            </div>
            <!-- Main Content -->
            <div dojoType="dijit.layout.ContentPane" region="center" id="centerMainContent">
                <form dojoType="dijit.form.Form" id="loginForm" name="loginForm" method="post" action="<?php echo $this->url(array('controller' => 'login', 'action' => 'login')); ?>">
                    <input dojoType="dijit.form.TextBox" id="hash" type="hidden" name="hash" value=""" />
                    <table width="100%" align="center" class="form">
                    <col class="col1" />
                        <tr>
                            <td class="label"><label for="username">Username:</label></td>
                            <td>
                                <input dojoType="dijit.form.TextBox" id="username" type="text" name="username" value="<?php echo $this->username; ?>" />
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="password">Password:</label></td>
                            <td>
                                <input dojoType="dijit.form.TextBox" id="password" type="password" name="password" value="" />
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td><button dojoType="dijit.form.Button" baseClass="positive" id="loginButton" type="submit" iconClass="tick"
                            onfocus="dojo.byId('loginForm').submit();">
                                    Login
                                </button>
                            </td>

                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
