<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>PHProjekt</title>
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
    <style type="text/css">
        @import "<?php echo $this->webpath; ?>dojo/dojo/resources/dojo.css";
        @import "<?php echo $this->webpath; ?>css/themes/phprojekt/phprojekt.css";
        @import "<?php echo $this->webpath; ?>dojo/dijit/themes/dijit.css";
        @import "<?php echo $this->webpath; ?>dojo/dijit/themes/dijit_rtl.css";
    </style>
    <script type="text/javascript" src="<?php echo $this->webpath; ?>dojo/dojo/dojo.js"
     djConfig="isDebug: false, parseOnLoad: true, useCommentedJson: true"></script>
    <?php
    if ($this->compressedDojo) {
    ?>
    <script type="text/javascript" src="<?php echo $this->webpath; ?>dojo/dojo/mydojo.js"></script>
    <?php
    }
    ?>
    <script type="text/javascript">
        function updateInput() {
            var par     = window.parent.document;
            var input   = par.getElementById("<?php echo $this->field; ?>");
            input.value = "<?php echo $this->value; ?>";
        }
    </script>
</head>
<body class="phprojekt">
    <?php
    if (null !== $this->fileName) {
        echo '<div style="display:inline;"><a href="'. $this->downloadLink .'" target=_blank>'. $this->fileName . '</a></div>&nbsp;';
    }
    ?>
    <form method="post" id="upload" action="<?php echo $this->formPath; ?>" enctype="multipart/form-data" style="display:inline;">
        <div style="display:inline;">
            <input type="hidden" name="field" id="field" value="<?php echo $this->field; ?>" />
            <input type="hidden" name="itemId" id="itemId" value="<?php echo $this->itemId; ?>" />
            <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
            <input type="file" name="uploadedFile"  id="uploadedFile" onChange="dojo.byId('upload').submit();" />
        </div>
    </form>
    <?php
    if ($this->upload) {
        echo '<script type="text/javascript">updateInput();</script>';
    }
    ?>
</body>
</html>