<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>PHProjekt</title>
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
    <style type="text/css">
        @import "<?php echo $this->webpath; ?>css/themes/phprojekt/phprojektCssCompiler.php";

    .deleteButton { background: url("<?php echo $this->webpath; ?>/img/close.png") no-repeat left top;
            width:13px;
            height:13px;
            
            
            }
     .deleteButton:hover { background: url("<?php echo $this->webpath; ?>/img/close_on.png"); 
        cursor: hand;
        }
    </style>
    <script type="text/javascript">
        var djConfig = {isDebug: false, parseOnLoad: true, useCommentedJson: true};
    </script>
    <script type="text/javascript" src="<?php echo $this->webpath; ?>dojo/dojo/dojo.js"></script>
    <?php
    if ($this->compressedDojo) {
    ?>
    <script type="text/javascript" src="<?php echo $this->webpath; ?>dojo/dojo/mydojo.js"></script>
    <?php
    }
    ?>
    <script type="text/javascript">
       <?php
        if ($this->filesChanged) {
            ?>
            var par     = window.parent.document;
            var input   = par.getElementById("<?php echo $this->field; ?>");
            input.value = "<?php echo $this->value; ?>";
            <?php
        }
        ?>

        //onMouseOver and onMouseOut function
        function closeMouse(which, mode) {
            if (mode == 'over') {
                var from = 'close';
                var to   = 'closeOn';
            } else if (mode == 'out' ) {
                var from = 'closeOn';
                var to   = 'close';
            }
            var btnClose = dojo.byId(which.id);
            dojo.removeClass(btnClose.firstChild, from);
            dojo.addClass(btnClose.firstChild, to);
        }
    </script>
</head>
<body class="phprojekt">
    <form method="post" id="upload" action="<?php echo $this->formPath; ?>" enctype="multipart/form-data" style="display:inline;">
        <div style="display:inline;">
            <input type="hidden" name="field" id="field" value="<?php echo $this->field; ?>" />
            <input type="hidden" name="itemId" id="itemId" value="<?php echo $this->itemId; ?>" />
            <input type="hidden" name="value" id="value" value="<?php echo $this->value; ?>" />
            <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
            <input type="file" name="uploadedFile"  id="uploadedFile" onChange="dojo.byId('upload').submit();" />
        </div>
    </form>
    <br>
    <?php
    $iframeSize = 25;
    if (is_array($this->files)) {
        echo '<div id="filesList" style="display:inline;"><table border="0" cellspacing="0" cellpadding="0">';
        $i = 0;
        $iframeSize += count($this->files)*31;

        foreach ($this->files as $file) {
            $i++;
            echo '<tr><td>'
                 . '<a href="'. $file['downloadLink'] .'" target=_blank>' . $file['fileName'] 
                 . '</a></td><td width=5></td><td>'
                 . '<button id="btnClose' . $i . '" dojoType="dijit.form.Button" showLabel="false" '
                 . 'iconClass="close" class="closeButton" onMouseOver="closeMouse(this, \'over\');" '
                 . 'onMouseOut="closeMouse(this, \'out\');" onClick="window.location.href=\''
                 . $file['deleteLink'] . '\';"></button>'
                 . '</td></tr>';
        }
        echo '</table></div>&nbsp;';
    }
    ?>
    <!-- Set the parent Iframe size -->
    <script type="text/javascript">
        window.parent.document.getElementById('filesIframe').height='<?php echo $iframeSize ?>px';
    </script>
</body>
</html>