/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.atom.io.Connection"]||(dojo._hasResource["dojox.atom.io.Connection"]=!0,dojo.provide("dojox.atom.io.Connection"),dojo.require("dojox.atom.io.model"),dojo.declare("dojox.atom.io.Connection",null,{constructor:function(a,b){this.sync=a;this.preventCache=b},preventCache:!1,alertsEnabled:!1,getFeed:function(a,b,e,f){this._getXmlDoc(a,"feed",new dojox.atom.io.model.Feed,dojox.atom.io.model._Constants.ATOM_NS,b,e,f)},getService:function(a,b,e,f){this._getXmlDoc(a,"service",new dojox.atom.io.model.Service(a),
dojox.atom.io.model._Constants.APP_NS,b,e,f)},getEntry:function(a,b,e,f){this._getXmlDoc(a,"entry",new dojox.atom.io.model.Entry,dojox.atom.io.model._Constants.ATOM_NS,b,e,f)},_getXmlDoc:function(a,b,e,f,c,d,h){if(!h)h=dojo.global;var j=this.alertsEnabled,a={url:a,handleAs:"xml",sync:this.sync,preventCache:this.preventCache,load:function(a,g){var d=null,i;if(a){if(typeof a.getElementsByTagNameNS!="undefined")if((i=a.getElementsByTagNameNS(f,b))&&i.length>0)d=i.item(0);else{if(a.lastChild)d=a.lastChild}else if(typeof a.getElementsByTagName!=
"undefined")if((i=a.getElementsByTagName(b))&&i.length>0)for(var k=0;k<i.length;k++){if(i[k].namespaceURI==f){d=i[k];break}}else{if(a.lastChild)d=a.lastChild}else if(a.lastChild)d=a.lastChild;else{c.call(h,null,null,g);return}e.buildFromDom(d);if(c)c.call(h,e,a,g);else if(j)throw Error("The callback value does not exist.");}else c.call(h,null,null,g)}};if(this.user&&this.user!==null)a.user=this.user;if(this.password&&this.password!==null)a.password=this.password;a.error=d?function(a,b){d.call(h,a,
b)}:function(){throw Error("The URL requested cannot be accessed");};dojo.xhrGet(a)},updateEntry:function(a,b,e,f,c,d){if(!d)d=dojo.global;a.updated=new Date;var h=a.getEditHref();if(!h)throw Error("A URL has not been specified for editing this entry.");var j=this,l=this.alertsEnabled,g={url:h,handleAs:"text",contentType:"text/xml",sync:this.sync,preventCache:this.preventCache,load:function(c,e){var g=null;if(f)(g=e.xhr.getResponseHeader("Location"))||(g=h),j.getEntry(g,function(a,e,c){if(b)b.call(d,
a,g,c);else if(l)throw Error("The callback value does not exist.");});else if(b)b.call(d,a,e.xhr.getResponseHeader("Location"),e);else if(l)throw Error("The callback value does not exist.");return c}};if(this.user&&this.user!==null)g.user=this.user;if(this.password&&this.password!==null)g.password=this.password;g.error=e?function(a,b){e.call(d,a,b)}:function(){throw Error("The URL requested cannot be accessed");};c?(g.postData=a.toString(!0),g.headers={"X-Method-Override":"PUT"},dojo.rawXhrPost(g)):
(g.putData=a.toString(!0),dojo.rawXhrPut(g))},addEntry:function(a,b,e,f,c,d){if(!d)d=dojo.global;a.published=new Date;a.updated=new Date;var c=a.feedUrl,h=this.alertsEnabled;!b&&c&&(b=c);if(b){var j=this,c={url:b,handleAs:"text",contentType:"text/xml",sync:this.sync,preventCache:this.preventCache,postData:a.toString(!0),load:function(c,g){var f=g.xhr.getResponseHeader("Location");f||(f=b);if(g.retrieveEntry)j.getEntry(f,function(a,b,c){if(e)e.call(d,a,f,c);else if(h)throw Error("The callback value does not exist.");
});else if(e)e.call(d,a,f,g);else if(h)throw Error("The callback value does not exist.");return c}};if(this.user&&this.user!==null)c.user=this.user;if(this.password&&this.password!==null)c.password=this.password;c.error=f?function(a,b){f.call(d,a,b)}:function(){throw Error("The URL requested cannot be accessed");};dojo.rawXhrPost(c)}else if(h)throw Error("The request cannot be processed because the URL parameter is missing.");},deleteEntry:function(a,b,e,f,c){if(!c)c=dojo.global;var d=null,d=typeof a==
"string"?a:a.getEditHref();if(!d)throw b.call(c,!1,null),Error("The request cannot be processed because the URL parameter is missing.");a={url:d,handleAs:"text",sync:this.sync,preventCache:this.preventCache,load:function(a,d){b.call(c,d);return a}};if(this.user&&this.user!==null)a.user=this.user;if(this.password&&this.password!==null)a.password=this.password;a.error=e?function(a,b){e.call(c,a,b)}:function(){throw Error("The URL requested cannot be accessed");};f?(a.headers={"X-Method-Override":"DELETE"},
dojo.xhrPost(a)):dojo.xhrDelete(a)}}));