/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.xmpp.TransportSession"])dojo._hasResource["dojox.xmpp.TransportSession"]=!0,dojo.provide("dojox.xmpp.TransportSession"),dojo.require("dojox.xmpp.bosh"),dojo.require("dojox.xmpp.util"),dojo.require("dojox.data.dom"),dojox.xmpp.TransportSession=function(a){this.sendTimeout=(this.wait+20)*1E3;if(a&&dojo.isObject(a)&&(dojo.mixin(this,a),this.useScriptSrcTransport))this.transportIframes=[]},dojo.extend(dojox.xmpp.TransportSession,{rid:0,hold:1,polling:1E3,secure:!1,wait:60,
lang:"en",submitContentType:"text/xml; charset=utf=8",serviceUrl:"/httpbind",defaultResource:"dojoIm",domain:"imserver.com",sendTimeout:0,useScriptSrcTransport:!1,keepAliveTimer:null,state:"NotReady",transmitState:"Idle",protocolPacketQueue:[],outboundQueue:[],outboundRequests:{},inboundQueue:[],deferredRequests:{},matchTypeIdAttribute:{},open:function(){this.status="notReady";this.rid=Math.round(Math.random()*1E9);this.protocolPacketQueue=[];this.outboundQueue=[];this.outboundRequests={};this.inboundQueue=
[];this.deferredRequests={};this.matchTypeIdAttribute={};this.keepAliveTimer=setTimeout(dojo.hitch(this,"_keepAlive"),1E4);this.useScriptSrcTransport?dojox.xmpp.bosh.initialize({iframes:this.hold+1,load:dojo.hitch(this,function(){this._sendLogin()})}):this._sendLogin()},_sendLogin:function(){var a=this.rid++;this.addToOutboundQueue(dojox.xmpp.util.createElement("body",{content:this.submitContentType,hold:this.hold,rid:a,to:this.domain,secure:this.secure,wait:this.wait,"xml:lang":this.lang,"xmpp:version":"1.0",
xmlns:dojox.xmpp.xmpp.BODY_NS,"xmlns:xmpp":"urn:xmpp:xbosh"},!0),a)},_sendRestart:function(){var a=this.rid++;this.addToOutboundQueue(dojox.xmpp.util.createElement("body",{rid:a,sid:this.sid,to:this.domain,"xmpp:restart":"true","xml:lang":this.lang,xmlns:dojox.xmpp.xmpp.BODY_NS,"xmlns:xmpp":"urn:xmpp:xbosh"},!0),a)},processScriptSrc:function(a,b){var c=dojox.xml.parser.parse(a,"text/xml");c&&this.processDocument(c,b)},_keepAlive:function(){if(!(this.state=="wait"||this.isTerminated()))this._dispatchPacket(),
this.keepAliveTimer=setTimeout(dojo.hitch(this,"_keepAlive"),1E4)},close:function(a){var b=this.rid++,c={sid:this.sid,rid:b,type:"terminate"},d=null;a?(d=new dojox.string.Builder(dojox.xmpp.util.createElement("body",c,!1)),d.append(a),d.append("</body>")):d=new dojox.string.Builder(dojox.xmpp.util.createElement("body",c,!1));this.addToOutboundQueue(d.toString(),b)},dispatchPacket:function(a,b,c,d){a&&this.protocolPacketQueue.push(a);a=new dojo.Deferred;if(b&&c&&(a.protocolMatchType=b,a.matchId=c,
a.matchProperty=d||"id",a.matchProperty!="id"))this.matchTypeIdAttribute[b]=a.matchProperty;this.deferredRequests[a.protocolMatchType+"-"+a.matchId]=a;if(!this.dispatchTimer)this.dispatchTimer=setTimeout(dojo.hitch(this,"_dispatchPacket"),600);return a},_dispatchPacket:function(){clearTimeout(this.dispatchTimer);delete this.dispatchTimer;if(this.sid)if(this.authId){if(!(this.transmitState!="error"&&this.protocolPacketQueue.length==0&&this.outboundQueue.length>0)&&!(this.state=="wait"||this.isTerminated())){var a=
{sid:this.sid,xmlns:dojox.xmpp.xmpp.BODY_NS},b;if(this.protocolPacketQueue.length>0)a.rid=this.rid++,b=new dojox.string.Builder(dojox.xmpp.util.createElement("body",a,!1)),b.append(this.processProtocolPacketQueue()),b.append("</body>"),delete this.lastPollTime;else{if(this.lastPollTime&&(b=(new Date).getTime(),b-this.lastPollTime<this.polling)){this.dispatchTimer=setTimeout(dojo.hitch(this,"_dispatchPacket"),this.polling-(b-this.lastPollTime)+10);return}a.rid=this.rid++;this.lastPollTime=(new Date).getTime();
b=new dojox.string.Builder(dojox.xmpp.util.createElement("body",a,!0))}this.addToOutboundQueue(b.toString(),a.rid)}}else console.debug("TransportSession::dispatchPacket() No authId, packet dropped [FIXME]");else console.debug("TransportSession::dispatchPacket() No SID, packet dropped.")},redispatchPacket:function(a){this.sendXml(this.outboundRequests[a],a)},addToOutboundQueue:function(a,b){this.outboundQueue.push({msg:a,rid:b});this.outboundRequests[b]=a;this.sendXml(a,b)},removeFromOutboundQueue:function(a){for(var b=
0;b<this.outboundQueue.length;b++)if(a==this.outboundQueue[b].rid){this.outboundQueue.splice(b,1);break}delete this.outboundRequests[a]},processProtocolPacketQueue:function(){for(var a=new dojox.string.Builder,b=0;b<this.protocolPacketQueue.length;b++)a.append(this.protocolPacketQueue[b]);this.protocolPacketQueue=[];return a.toString()},sendXml:function(a,b){if(this.isTerminated())return!1;this.transmitState="transmitting";var c=null,c=this.useScriptSrcTransport?dojox.xmpp.bosh.get({rid:b,url:this.serviceUrl+
"?"+encodeURIComponent(a),error:dojo.hitch(this,function(){this.setState("Terminate","error");return!1}),timeout:this.sendTimeout}):dojo.rawXhrPost({contentType:"text/xml",url:this.serviceUrl,postData:a,handleAs:"xml",error:dojo.hitch(this,function(a,c){return this.processError(c.xhr.responseXML,c.xhr.status,b)}),timeout:this.sendTimeout});c.addCallback(this,function(a){return this.processDocument(a,b)});return c},processDocument:function(a,b){if(this.isTerminated()||!a.firstChild)return!1;this.transmitState=
"idle";var c=a.firstChild;if(this.outboundQueue.length<1)return!1;var d=this.outboundQueue[0].rid;b==d?(this.removeFromOutboundQueue(b),this.processResponse(c,b),this.processInboundQueue()):b-d<this.hold+2&&this.addToInboundQueue(a,b);return a},processInboundQueue:function(){for(;this.inboundQueue.length>0;){var a=this.inboundQueue.shift();this.processDocument(a.doc,a.rid)}},addToInboundQueue:function(a,b){for(var c=0;c<this.inboundQueue.length;c++)b<this.inboundQueue[c].rid||this.inboundQueue.splice(c,
0,{doc:a,rid:b})},processResponse:function(a,b){if(a.getAttribute("type")=="terminate"){var c="";a.firstChild.firstChild.nodeName=="conflict"&&(c="conflict");this.setState("Terminate",c)}else{if(this.state!="Ready"&&this.state!="Terminate"){if(c=a.getAttribute("sid"))this.sid=c;else throw Error("No sid returned during xmpp session startup");this.authId=a.getAttribute("authid");this.authId==""&&this.authRetries--<1&&(console.error("Unable to obtain Authorization ID"),this.terminateSession());this.wait=
a.getAttribute("wait");if(a.getAttribute("polling"))this.polling=parseInt(a.getAttribute("polling"))*1E3;this.inactivity=a.getAttribute("inactivity");this.setState("Ready")}dojo.forEach(a.childNodes,function(a){this.processProtocolResponse(a,b)},this);this.transmitState=="idle"&&this.dispatchPacket()}},processProtocolResponse:function(a){this.onProcessProtocolResponse(a);var b=a.nodeName+"-"+a.getAttribute("id"),c=this.deferredRequests[b];c&&(c.callback(a),delete this.deferredRequests[b])},setState:function(a,
b){if(this.state!=a){if(this["on"+a])this["on"+a](a,this.state,b);this.state=a}},isTerminated:function(){return this.state=="Terminate"},processError:function(a,b,c){if(this.isTerminated())return!1;if(b!=200)return b>=400&&b<500?(this.setState("Terminate",d),!1):(this.removeFromOutboundQueue(c),setTimeout(dojo.hitch(this,function(){this.dispatchPacket()}),200),!0);this.removeFromOutboundQueue(c);if(a&&a.firstChild&&a.firstChild.getAttribute("type")=="terminate"){var a=a.firstChild.firstChild,d="";
a&&a.nodeName=="conflict"&&(d="conflict");this.setState("Terminate",d);return!1}this.transmitState="error";setTimeout(dojo.hitch(this,function(){this.dispatchPacket()}),200);return!0},onTerminate:function(){},onProcessProtocolResponse:function(){},onReady:function(){}});