/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.xmpp.xmppSession"])dojo._hasResource["dojox.xmpp.xmppSession"]=!0,dojo.provide("dojox.xmpp.xmppSession"),dojo.require("dojox.xmpp.TransportSession"),dojo.require("dojox.xmpp.RosterService"),dojo.require("dojox.xmpp.PresenceService"),dojo.require("dojox.xmpp.UserService"),dojo.require("dojox.xmpp.ChatService"),dojo.require("dojox.xmpp.sasl"),dojox.xmpp.xmpp={STREAM_NS:"http://etherx.jabber.org/streams",CLIENT_NS:"jabber:client",STANZA_NS:"urn:ietf:params:xml:ns:xmpp-stanzas",
SASL_NS:"urn:ietf:params:xml:ns:xmpp-sasl",BIND_NS:"urn:ietf:params:xml:ns:xmpp-bind",SESSION_NS:"urn:ietf:params:xml:ns:xmpp-session",BODY_NS:"http://jabber.org/protocol/httpbind",XHTML_BODY_NS:"http://www.w3.org/1999/xhtml",XHTML_IM_NS:"http://jabber.org/protocol/xhtml-im",INACTIVE:"Inactive",CONNECTED:"Connected",ACTIVE:"Active",TERMINATE:"Terminate",LOGIN_FAILURE:"LoginFailure",INVALID_ID:-1,NO_ID:0,error:{BAD_REQUEST:"bad-request",CONFLICT:"conflict",FEATURE_NOT_IMPLEMENTED:"feature-not-implemented",
FORBIDDEN:"forbidden",GONE:"gone",INTERNAL_SERVER_ERROR:"internal-server-error",ITEM_NOT_FOUND:"item-not-found",ID_MALFORMED:"jid-malformed",NOT_ACCEPTABLE:"not-acceptable",NOT_ALLOWED:"not-allowed",NOT_AUTHORIZED:"not-authorized",SERVICE_UNAVAILABLE:"service-unavailable",SUBSCRIPTION_REQUIRED:"subscription-required",UNEXPECTED_REQUEST:"unexpected-request"}},dojox.xmpp.xmppSession=function(a){this.roster=[];this.chatRegister=[];this._iqId=Math.round(Math.random()*1E9);a&&dojo.isObject(a)&&dojo.mixin(this,
a);this.session=new dojox.xmpp.TransportSession(a);dojo.connect(this.session,"onReady",this,"onTransportReady");dojo.connect(this.session,"onTerminate",this,"onTransportTerminate");dojo.connect(this.session,"onProcessProtocolResponse",this,"processProtocolResponse")},dojo.extend(dojox.xmpp.xmppSession,{roster:[],chatRegister:[],_iqId:0,open:function(a,b,c){if(a){if(this.jid=a,a.indexOf("@")==-1)this.jid=this.jid+"@"+this.domain}else throw Error("User id cannot be null");if(b)this.password=b;if(c)this.resource=
c;this.session.open()},close:function(){this.state=dojox.xmpp.xmpp.TERMINATE;this.session.close(dojox.xmpp.util.createElement("presence",{type:"unavailable",xmlns:dojox.xmpp.xmpp.CLIENT_NS},!0))},processProtocolResponse:function(a){var b=a.nodeName,c=b.indexOf(":");c>0&&(b=b.substring(c+1));switch(b){case "iq":case "presence":case "message":case "features":this[b+"Handler"](a);break;default:a.getAttribute("xmlns")==dojox.xmpp.xmpp.SASL_NS&&this.saslHandler(a)}},messageHandler:function(a){switch(a.getAttribute("type")){case "chat":this.chatHandler(a);
break;default:this.simpleMessageHandler(a)}},iqHandler:function(a){a.getAttribute("type")=="set"?this.iqSetHandler(a):a.getAttribute("type")},presenceHandler:function(a){switch(a.getAttribute("type")){case "subscribe":this.presenceSubscriptionRequest(a.getAttribute("from"));break;case "subscribed":case "unsubscribed":break;case "error":this.processXmppError(a);break;default:this.presenceUpdate(a)}},featuresHandler:function(a){var b=[],c=!1,d=!1;if(a.hasChildNodes())for(var e=0;e<a.childNodes.length;e++){var f=
a.childNodes[e];switch(f.nodeName){case "mechanisms":for(var i=0;i<f.childNodes.length;i++)b.push(f.childNodes[i].firstChild.nodeValue);break;case "bind":c=!0;break;case "session":d=!0}}if(this.state==dojox.xmpp.xmpp.CONNECTED)if(this.auth)c&&this.bindResource(d);else for(e=0;e<b.length;e++)try{this.auth=dojox.xmpp.sasl.registry.match(b[e],this);break}catch(h){console.warn("No suitable auth mechanism found for: ",b[e])}},saslHandler:function(a){if(a.nodeName=="success")this.auth.onSuccess();else if(a.nodeName==
"challenge")this.auth.onChallenge(a);else a.hasChildNodes()&&(this.onLoginFailure(a.firstChild.nodeName),this.session.setState("Terminate",a.firstChild.nodeName))},sendRestart:function(){this.session._sendRestart()},chatHandler:function(a){var b,c={from:a.getAttribute("from"),to:a.getAttribute("to")};for(b=0;b<a.childNodes.length;b++){var d=a.childNodes[b];if(d.hasChildNodes())switch(d.nodeName){case "thread":c.chatid=d.firstChild.nodeValue;break;case "body":if(!d.getAttribute("xmlns")||d.getAttribute("xmlns")==
"")c.body=d.firstChild.nodeValue;break;case "subject":c.subject=d.firstChild.nodeValue;case "html":if(d.getAttribute("xmlns")==dojox.xmpp.xmpp.XHTML_IM_NS)c.xhtml=d.getElementsByTagName("body")[0]}}a=-1;if(c.chatid)for(b=0;b<this.chatRegister.length;b++){if((d=this.chatRegister[b])&&d.chatid==c.chatid){a=b;break}}else for(b=0;b<this.chatRegister.length;b++)(d=this.chatRegister[b])&&d.uid==this.getBareJid(c.from)&&(a=b);if(c.body&&c.body!=""||c.xhtml)a>-1?(b=this.chatRegister[a],b.recieveMessage(c)):
(b=new dojox.xmpp.ChatService,b.uid=this.getBareJid(c.from),b.chatid=c.chatid,b.firstMessage=!0,this.useChatState=!1,this.registerChatInstance(b,c))},simpleMessageHandler:function(){},registerChatInstance:function(a,b){a.setSession(this);this.chatRegister.push(a);this.onRegisterChatInstance(a,b);a.recieveMessage(b,!0)},iqSetHandler:function(a){if(a.hasChildNodes()){var b=a.firstChild;switch(b.nodeName){case "query":b.getAttribute("xmlns")=="jabber:iq:roster"&&(this.rosterSetHandler(b),this.sendIqResult(a.getAttribute("id"),
a.getAttribute("from")))}}},sendIqResult:function(a,b){this.dispatchPacket(dojox.xmpp.util.createElement("iq",{id:a,to:b||this.domain,type:"result",from:this.jid+"/"+this.resource},!0))},rosterSetHandler:function(a){for(var b=0;b<a.childNodes.length;b++){var c=a.childNodes[b];if(c.nodeName=="item"){for(var d=!1,e=-1,f=null,i=null,h=0;h<this.roster.length;h++){var g=this.roster[h];if(c.getAttribute("jid")==g.jid){d=!0;if(c.getAttribute("subscription")=="remove"){f={id:g.jid,name:g.name,groups:[]};
for(e=0;e<g.groups.length;e++)f.groups.push(g.groups[e]);this.roster.splice(h,1);e=dojox.xmpp.roster.REMOVED}else{i=dojo.clone(g);if(f=c.getAttribute("name"))this.roster[h].name=f;g.groups=[];if(c.getAttribute("subscription"))g.status=c.getAttribute("subscription");g.substatus=dojox.xmpp.presence.SUBSCRIPTION_SUBSTATUS_NONE;if(c.getAttribute("ask")=="subscribe")g.substatus=dojox.xmpp.presence.SUBSCRIPTION_REQUEST_PENDING;for(e=0;e<c.childNodes.length;e++)h=c.childNodes[e],h.nodeName=="group"&&h.hasChildNodes()&&
g.groups.push(h.firstChild.nodeValue);f=g;e=dojox.xmpp.roster.CHANGED}break}}if(!d&&c.getAttribute("subscription")!="remove")f=g=this.createRosterEntry(c),e=dojox.xmpp.roster.ADDED;switch(e){case dojox.xmpp.roster.ADDED:this.onRosterAdded(f);break;case dojox.xmpp.roster.REMOVED:this.onRosterRemoved(f);break;case dojox.xmpp.roster.CHANGED:this.onRosterChanged(f,i)}}}},presenceUpdate:function(a){if(!(a.getAttribute("to")&&this.getBareJid(a.getAttribute("to"))!=this.jid)){var b=this.getResourceFromJid(a.getAttribute("from")),
b={from:this.getBareJid(a.getAttribute("from")),resource:b,show:dojox.xmpp.presence.STATUS_ONLINE,priority:5,hasAvatar:!1};if(a.getAttribute("type")=="unavailable")b.show=dojox.xmpp.presence.STATUS_OFFLINE;for(var c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];if(d.hasChildNodes())switch(d.nodeName){case "status":case "show":b[d.nodeName]=d.firstChild.nodeValue;break;case "status":b.priority=parseInt(d.firstChild.nodeValue);break;case "x":if(d.firstChild&&d.firstChild.firstChild&&d.firstChild.firstChild.nodeValue!=
"")b.avatarHash=d.firstChild.firstChild.nodeValue,b.hasAvatar=!0}}this.onPresenceUpdate(b)}},retrieveRoster:function(){var a={id:this.getNextIqId(),from:this.jid+"/"+this.resource,type:"get"},b=new dojox.string.Builder(dojox.xmpp.util.createElement("iq",a,!1));b.append(dojox.xmpp.util.createElement("query",{xmlns:"jabber:iq:roster"},!0));b.append("</iq>");this.dispatchPacket(b,"iq",a.id).addCallback(this,"onRetrieveRoster")},getRosterIndex:function(a){a.indexOf("@")==-1&&(a+="@"+this.domain);for(var b=
0;b<this.roster.length;b++)if(a==this.roster[b].jid)return b;return-1},createRosterEntry:function(a){var b={name:a.getAttribute("name"),jid:a.getAttribute("jid"),groups:[],status:dojox.xmpp.presence.SUBSCRIPTION_NONE,substatus:dojox.xmpp.presence.SUBSCRIPTION_SUBSTATUS_NONE};if(!b.name)b.name=b.id;for(var c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];d.nodeName=="group"&&d.hasChildNodes()&&b.groups.push(d.firstChild.nodeValue)}if(a.getAttribute("subscription"))b.status=a.getAttribute("subscription");
if(a.getAttribute("ask")=="subscribe")b.substatus=dojox.xmpp.presence.SUBSCRIPTION_REQUEST_PENDING;return b},bindResource:function(a){var b={id:this.getNextIqId(),type:"set"},c=new dojox.string.Builder(dojox.xmpp.util.createElement("iq",b,!1));c.append(dojox.xmpp.util.createElement("bind",{xmlns:dojox.xmpp.xmpp.BIND_NS},!1));this.resource&&(c.append(dojox.xmpp.util.createElement("resource")),c.append(this.resource),c.append("</resource>"));c.append("</bind></iq>");this.dispatchPacket(c,"iq",b.id).addCallback(this,
function(b){this.onBindResource(b,a);return b})},getNextIqId:function(){return"im_"+this._iqId++},presenceSubscriptionRequest:function(a){this.onSubscriptionRequest(a)},dispatchPacket:function(a,b,c){if(this.state!="Terminate")return this.session.dispatchPacket(a,b,c)},setState:function(a,b){if(this.state!=a){if(this["on"+a])this["on"+a](a,this.state,b);this.state=a}},search:function(a,b,c){var b={id:this.getNextIqId(),"xml:lang":this.lang,type:"set",from:this.jid+"/"+this.resource,to:b},d=new dojox.string.Builder(dojox.xmpp.util.createElement("iq",
b,!1));d.append(dojox.xmpp.util.createElement("query",{xmlns:"jabber:iq:search"},!1));d.append(dojox.xmpp.util.createElement(c,{},!1));d.append(a);d.append("</").append(c).append(">");d.append("</query></iq>");this.dispatchPacket(d.toString,"iq",b.id).addCallback(this,"_onSearchResults")},_onSearchResults:function(a){if(a.getAttribute("type")=="result"&&a.hasChildNodes())this.onSearchResults([])},onLogin:function(){this.retrieveRoster()},onLoginFailure:function(){},onBindResource:function(a,b){if(a.getAttribute("type")==
"result"){if(a.hasChildNodes()&&a.firstChild.nodeName=="bind"){var c=a.firstChild;if(c.hasChildNodes()&&c.firstChild.nodeName=="jid"&&c.firstChild.hasChildNodes())c=c.firstChild.firstChild.nodeValue,this.jid=this.getBareJid(c),this.resource=this.getResourceFromJid(c);if(b){var c={id:this.getNextIqId(),type:"set"},d=new dojox.string.Builder(dojox.xmpp.util.createElement("iq",c,!1));d.append(dojox.xmpp.util.createElement("session",{xmlns:dojox.xmpp.xmpp.SESSION_NS},!0));d.append("</iq>");this.dispatchPacket(d,
"iq",c.id).addCallback(this,"onBindSession");return}}this.onLogin()}else if(a.getAttribute("type")=="error")this.onLoginFailure(this.processXmppError(a))},onBindSession:function(a){if(a.getAttribute("type")=="error")this.onLoginFailure(this.processXmppError(a));else this.onLogin()},onSearchResults:function(){},onRetrieveRoster:function(a){if(a.getAttribute("type")=="result"&&a.hasChildNodes()){var b=a.getElementsByTagName("query")[0];if(b.getAttribute("xmlns")=="jabber:iq:roster")for(var c=0;c<b.childNodes.length;c++)b.childNodes[c].nodeName==
"item"&&(this.roster[c]=this.createRosterEntry(b.childNodes[c]))}else a.getAttribute("type");this.setState(dojox.xmpp.xmpp.ACTIVE);this.onRosterUpdated();return a},onRosterUpdated:function(){},onSubscriptionRequest:function(){},onPresenceUpdate:function(){},onTransportReady:function(){this.setState(dojox.xmpp.xmpp.CONNECTED);this.rosterService=new dojox.xmpp.RosterService(this);this.presenceService=new dojox.xmpp.PresenceService(this);this.userService=new dojox.xmpp.UserService(this)},onTransportTerminate:function(a,
b,c){this.setState(dojox.xmpp.xmpp.TERMINATE,c)},onConnected:function(){},onTerminate:function(){},onActive:function(){},onRegisterChatInstance:function(){},onRosterAdded:function(){},onRosterRemoved:function(){},onRosterChanged:function(){},processXmppError:function(a){for(var b={stanzaType:a.nodeName,id:a.getAttribute("id")},c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];switch(d.nodeName){case "error":b.errorType=d.getAttribute("type");for(var e=0;e<d.childNodes.length;e++){var f=d.childNodes[e];
if(f.nodeName=="text"&&f.getAttribute("xmlns")==dojox.xmpp.xmpp.STANZA_NS&&f.hasChildNodes())b.message=f.firstChild.nodeValue;else if(f.getAttribute("xmlns")==dojox.xmpp.xmpp.STANZA_NS&&!f.hasChildNodes())b.condition=f.nodeName}}}return b},sendStanzaError:function(a,b,c,d,e,f){e={type:"error"};if(b)e.to=b;if(c)e.id=c;b=new dojox.string.Builder(dojox.xmpp.util.createElement(a,e,!1));b.append(dojox.xmpp.util.createElement("error",{type:d},!1));b.append(dojox.xmpp.util.createElement("condition",{xmlns:dojox.xmpp.xmpp.STANZA_NS},
!0));f&&(b.append(dojox.xmpp.util.createElement("text",{xmlns:dojox.xmpp.xmpp.STANZA_NS,"xml:lang":this.lang},!1)),b.append(f).append("</text>"));b.append("</error></").append(a).append(">");this.dispatchPacket(b.toString())},getBareJid:function(a){var b=a.indexOf("/");return b!=-1?a.substring(0,b):a},getResourceFromJid:function(a){var b=a.indexOf("/");return b!=-1?a.substring(b+1,a.length):""}});