/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.html._base"]||(dojo._hasResource["dojox.html._base"]=!0,dojo.provide("dojox.html._base"),dojo.require("dojo.html"),function(){if(dojo.isIE)var j=/(AlphaImageLoader\([^)]*?src=(['"]))(?![a-z]+:|\/)([^\r\n;}]+?)(\2[^)]*\)\s*[;}]?)/g;var k=/(?:(?:@import\s*(['"])(?![a-z]+:|\/)([^\r\n;{]+?)\1)|url\(\s*(['"]?)(?![a-z]+:|\/)([^\r\n;]+?)\3\s*\))([a-z, \s]*[;}]?)/g,l=dojox.html._adjustCssPaths=function(b,a){if(a&&b)return j&&(a=a.replace(j,function(a,i,f,e,d){return i+(new dojo._Url(b,
"./"+e)).toString()+d})),a.replace(k,function(a,i,f,e,d,h){return f?'@import "'+(new dojo._Url(b,"./"+f)).toString()+'"'+h:"url("+(new dojo._Url(b,"./"+d)).toString()+")"+h})},m=/(<[a-z][a-z0-9]*\s[^>]*)(?:(href|src)=(['"]?)([^>]*?)\3|style=(['"]?)([^>]*?)\5)([^>]*>)/gi,n=dojox.html._adjustHtmlPaths=function(b,a){var c=b||"./";return a.replace(m,function(a,b,e,d,h,g,j,k){return b+(e?e+"="+d+(new dojo._Url(c,h)).toString()+d:"style="+g+l(c,j)+g)+k})},o=dojox.html._snarfStyles=function(b,a,c){c.attributes=
[];return a.replace(/(?:<style([^>]*)>([\s\S]*?)<\/style>|<link\s+(?=[^>]*rel=['"]?stylesheet)([^>]*?href=(['"])([^>]*?)\4[^>\/]*)\/?>)/gi,function(a,f,e,d,h,g){a=(f||d||"").replace(/^\s*([\s\S]*?)\s*$/i,"$1");e?e=c.push(b?l(b,e):e):(e=c.push('@import "'+g+'";'),a=a.replace(/\s*(?:rel|href)=(['"])?[^\s]*\1\s*/gi,""));if(a){a=a.split(/\s+/);g={};d=0;for(h=a.length;d<h;d++)f=a[d].split("="),g[f[0]]=f[1].replace(/^\s*['"]?([\s\S]*?)['"]?\s*$/,"$1");c.attributes[e-1]=g}return""})},p=dojox.html._snarfScripts=
function(b,a){function c(b){a.downloadRemote&&(b=b.replace(/&([a-z0-9#]+);/g,function(a,b){switch(b){case "amp":return"&";case "gt":return">";case "lt":return"<";default:return b.charAt(0)=="#"?String.fromCharCode(b.substring(1)):"&"+b+";"}}),dojo.xhrGet({url:b,sync:!0,load:function(b){a.code+=b+";"},error:a.errBack}))}a.code="";b=b.replace(/<[!][-][-](.|\s)*?[-][-]>/g,function(a){return a.replace(/<(\/?)script\b/ig,"&lt;$1Script")});return b.replace(/<script\s*(?![^>]*type=['"]?(?:dojo\/|text\/html\b))(?:[^>]*?(?:src=(['"]?)([^>]*?)\1[^>]*)?)*>([\s\S]*?)<\/script>/gi,
function(b,f,e,d){e?c(e):a.code+=d;return""})},q=dojox.html.evalInGlobal=function(b,a){var a=a||dojo.doc.body,c=a.ownerDocument.createElement("script");c.type="text/javascript";a.appendChild(c);c.text=b};dojo.declare("dojox.html._ContentSetter",[dojo.html._ContentSetter],{adjustPaths:!1,referencePath:".",renderStyles:!1,executeScripts:!1,scriptHasHooks:!1,scriptHookReplacement:null,_renderStyles:function(b){this._styleNodes=[];for(var a,c,i,f=this.node.ownerDocument,e=f.getElementsByTagName("head")[0],
d=0,h=b.length;d<h;d++){i=b[d];c=b.attributes[d];a=f.createElement("style");a.setAttribute("type","text/css");for(var g in c)a.setAttribute(g,c[g]);this._styleNodes.push(a);e.appendChild(a);a.styleSheet?a.styleSheet.cssText=i:a.appendChild(f.createTextNode(i))}},empty:function(){this.inherited("empty",arguments);this._styles=[]},onBegin:function(){this.inherited("onBegin",arguments);var b=this.content,a=this._styles;if(dojo.isString(b)){this.adjustPaths&&this.referencePath&&(b=n(this.referencePath,
b));if(this.renderStyles||this.cleanContent)b=o(this.referencePath,b,a);if(this.executeScripts){var c=this,a={downloadRemote:!0,errBack:function(a){c._onError.call(c,"Exec",'Error downloading remote script in "'+c.id+'"',a)}},b=p(b,a);this._code=a.code}}this.content=b},onEnd:function(){var b=this._code,a=this._styles;if(this._styleNodes&&this._styleNodes.length)for(;this._styleNodes.length;)dojo.destroy(this._styleNodes.pop());this.renderStyles&&a&&a.length&&this._renderStyles(a);if(this.executeScripts&&
b){this.cleanContent&&(b=b.replace(/(<\!--|(?:\/\/)?--\>|<!\[CDATA\[|\]\]>)/g,""));this.scriptHasHooks&&(b=b.replace(/_container_(?!\s*=[^=])/g,this.scriptHookReplacement));try{q(b,this.node)}catch(c){this._onError("Exec","Error eval script in "+this.id+", "+c.message,c)}}this.inherited("onEnd",arguments)},tearDown:function(){this.inherited(arguments);delete this._styles;if(this._styleNodes&&this._styleNodes.length)for(;this._styleNodes.length;)dojo.destroy(this._styleNodes.pop());delete this._styleNodes;
dojo.mixin(this,dojo.getObject(this.declaredClass).prototype)}});dojox.html.set=function(b,a,c){return c?(new dojox.html._ContentSetter(dojo.mixin(c,{content:a,node:b}))).set():dojo.html._setNodeContent(b,a,!0)}}());