/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.html.format"])dojo._hasResource["dojox.html.format"]=!0,dojo.provide("dojox.html.format"),dojo.require("dojox.html.entities"),dojox.html.format.prettyPrint=function(v,i,k,s,w){var e=[],h=0,p=[],j="\t",f="",t=[],q,x=/[=]([^"']+?)(\s|>)/g,y=/style=("[^"]*"|'[^']*'|\S*)/gi,z=/[\w-]+=("[^"]*"|'[^']*'|\S*)/gi;if(i&&i>0&&i<10){j="";for(q=0;q<i;q++)j+=" "}i=dojo.doc.createElement("div");i.innerHTML=v;var A=dojox.html.entities.encode,B=dojox.html.entities.decode,r=i.ownerDocument.createElement("div"),
C=function(a){a=a.cloneNode(!1);r.appendChild(a);a=r.innerHTML;r.innerHTML="";return a},l=function(){var a;for(a=0;a<h;a++)e.push(j)},m=function(){e.push("\n")},n=function(a){var b,d,a=a.split("\n");for(b=0;b<a.length;b++)a[b]=dojo.trim(a[b]);a=a.join(" ");a=dojo.trim(a);if(a!==""){var c=[];if(k&&k>0){var g="";for(b=0;b<h;b++)g+=j;b=g.length;g=k;for(k>b&&(g-=b);a;)if(a.length>k){for(b=g;b>0&&a.charAt(b)!==" ";b--);if(!b)for(b=g;b<a.length&&a.charAt(b)!==" ";b++);var e=a.substring(0,b),e=dojo.trim(e),
a=dojo.trim(a.substring(b==a.length?a.length:b+1,a.length));if(e){d="";for(b=0;b<h;b++)d+=j;e=d+e+"\n"}c.push(e)}else{d="";for(b=0;b<h;b++)d+=j;a=d+a+"\n";c.push(a);a=null}return c.join("")}else{d="";for(b=0;b<h;b++)d+=j;return d+a+"\n"}}else return""},D=function(a){if(a){var b=a;b&&(b=b.replace(/&quot;/gi,'"'),b=b.replace(/&gt;/gi,">"),b=b.replace(/&lt;/gi,"<"),b=b.replace(/&amp;/gi,"&"));for(var d,c,a=0,g=b.split("\n"),e=[],b=0;b<g.length;b++){var f=g[b],o=f.indexOf("\n")>-1;if(f=dojo.trim(f)){o=
a;for(d=0;d<f.length;d++)c=f.charAt(d),c==="{"?a++:c==="}"&&(a--,o=a);c="";for(d=0;d<h+o;d++)c+=j;e.push(c+f+"\n")}else o&&b===0&&e.push("\n")}a=e.join("")}return a},E=function(a){var b=a.nodeName.toLowerCase(),d=dojo.trim(C(a)),a=d.substring(0,d.indexOf(">")+1),a=a.replace(x,'="$1"$2'),a=a.replace(y,function(a){var b=a.substring(0,6),a=a.substring(6,a.length),c=a.charAt(0),a=dojo.trim(a.substring(1,a.length-1)),a=a.split(";"),d=[];dojo.forEach(a,function(a){if(a=dojo.trim(a))a=a.substring(0,a.indexOf(":")).toLowerCase()+
a.substring(a.indexOf(":"),a.length),d.push(a)});var d=d.sort(),a=d.join("; "),e=dojo.trim(a);return!e||e===";"?"":(a+=";",b+c+a+c)}),c=[],a=a.replace(z,function(a){c.push(dojo.trim(a));return""}),c=c.sort(),a="<"+b;c.length&&(a+=" "+c.join(" "));d.indexOf("</")!=-1?(p.push(b),a+=">"):(a+=w?" />":">",p.push(!1));a:switch(b){case "a":case "b":case "strong":case "s":case "strike":case "i":case "u":case "em":case "sup":case "sub":case "span":case "font":case "big":case "cite":case "q":case "small":b=
!0;break a;default:b=!1}t.push(b);f&&!b&&(e.push(n(f)),f="");b?f+=a:(l(),e.push(a),m(),h++)},u=function(a){var b=a.childNodes;if(b){var d;for(d=0;d<b.length;d++){var c=b[d];if(c.nodeType===1){var g=dojo.trim(c.tagName.toLowerCase());if(!(dojo.isIE&&c.parentNode!=a)&&!(g&&g.charAt(0)==="/"))E(c),g==="script"?e.push(D(c.innerHTML)):g==="pre"?(c=c.innerHTML,dojo.isMoz&&(c=c.replace("<br>","\n"),c=c.replace("<pre>",""),c=c.replace("</pre>","")),c.charAt(c.length-1)!=="\n"&&(c+="\n"),e.push(c)):u(c),c=
t.pop(),f&&!c&&(e.push(n(f)),f=""),(g=p.pop())?(g="</"+g+">",c?f+=g:(h--,l(),e.push(g),m())):h--}else c.nodeType===3||c.nodeType===4?f+=A(c.nodeValue,s):c.nodeType===8&&(c=B(c.nodeValue,s),l(),e.push("<\!--"),m(),h++,e.push(n(c)),h--,l(),e.push("--\>"),m())}}};u(i);f&&(e.push(n(f)),f="");return e.join("")};