/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.html.metrics"]||(dojo._hasResource["dojox.html.metrics"]=!0,dojo.provide("dojox.html.metrics"),function(){var b=dojox.html.metrics;b.getFontMeasurements=function(){var a={"1em":0,"1ex":0,"100%":0,"12pt":0,"16px":0,"xx-small":0,"x-small":0,small:0,medium:0,large:0,"x-large":0,"xx-large":0};if(dojo.isIE)dojo.doc.documentElement.style.fontSize="100%";var b=dojo.doc.createElement("div"),d=b.style;d.position="absolute";d.left="-100px";d.top="0";d.width="30px";d.height="1000em";
d.borderWidth="0";d.margin="0";d.padding="0";d.outline="0";d.lineHeight="1";d.overflow="hidden";dojo.body().appendChild(b);for(var f in a)d.fontSize=f,a[f]=Math.round(b.offsetHeight*12/16)*16/12/1E3;dojo.body().removeChild(b);return a};var g=null;b.getCachedFontMeasurements=function(a){if(a||!g)g=b.getFontMeasurements();return g};var h=null,i={};b.getTextBox=function(a,b,d){var f,c;if(h)f=h;else{f=h=dojo.doc.createElement("div");var e=dojo.doc.createElement("div");e.appendChild(f);c=e.style;c.overflow=
"scroll";c.position="absolute";c.left="0px";c.top="-10000px";c.width="1px";c.height="1px";c.visibility="hidden";c.borderWidth="0";c.margin="0";c.padding="0";c.outline="0";dojo.body().appendChild(e)}f.className="";c=f.style;c.borderWidth="0";c.margin="0";c.padding="0";c.outline="0";if(arguments.length>1&&b)for(var g in b)g in i||(c[g]=b[g]);if(arguments.length>2&&d)f.className=d;f.innerHTML=a;c=dojo.position(f);c.w=f.parentNode.scrollWidth;return c};var e={w:16,h:16};b.getScrollbar=function(){return{w:e.w,
h:e.h}};b._fontResizeNode=null;b.initOnFontResize=function(){var a=b._fontResizeNode=dojo.doc.createElement("iframe"),e=a.style;e.position="absolute";e.width="5em";e.height="10em";e.top="-10000px";dojo.isIE?a.onreadystatechange=function(){if(a.contentWindow.document.readyState=="complete")a.onresize=a.contentWindow.parent[dojox._scopeName].html.metrics._fontresize}:a.onload=function(){a.contentWindow.onresize=a.contentWindow.parent[dojox._scopeName].html.metrics._fontresize};a.setAttribute("src",
"javascript:'<html><head><script>if(\"loadFirebugConsole\" in window){window.loadFirebugConsole();}<\/script></head><body></body></html>'");dojo.body().appendChild(a);b.initOnFontResize=function(){}};b.onFontResize=function(){};b._fontresize=function(){b.onFontResize()};dojo.addOnUnload(function(){var a=b._fontResizeNode;if(a){if(dojo.isIE&&a.onresize)a.onresize=null;else if(a.contentWindow&&a.contentWindow.onresize)a.contentWindow.onresize=null;b._fontResizeNode=null}});dojo.addOnLoad(function(){try{var a=
dojo.doc.createElement("div");a.style.cssText="top:0;left:0;width:100px;height:100px;overflow:scroll;position:absolute;visibility:hidden;";dojo.body().appendChild(a);e.w=a.offsetWidth-a.clientWidth;e.h=a.offsetHeight-a.clientHeight;dojo.body().removeChild(a);delete a}catch(g){}"fontSizeWatch"in dojo.config&&dojo.config.fontSizeWatch&&b.initOnFontResize()})}());