/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.html.styles"]||(dojo._hasResource["dojox.html.styles"]=!0,dojo.provide("dojox.html.styles"),function(){var e={},d={},g=[];dojox.html.insertCssRule=function(a,b,c){var c=dojox.html.getDynamicStyleSheet(c),f=a+" {"+b+"}";console.log("insertRule:",f);dojo.isIE?(c.cssText+=f,console.log("ss.cssText:",c.cssText)):c.sheet?c.sheet.insertRule(f,c._indicies.length):c.appendChild(dojo.doc.createTextNode(f));c._indicies.push(a+" "+b);return a};dojox.html.removeCssRule=function(a,b,c){var f,
d=-1,g;for(g in e)if(!(c&&c!=g)){f=e[g];for(var h=0;h<f._indicies.length;h++)if(a+" "+b==f._indicies[h]){d=h;break}if(d>-1)break}if(!f)return console.log("No dynamic style sheet has been created from which to remove a rule."),!1;if(d==-1)return console.log("The css rule was not found and could not be removed."),!1;f._indicies.splice(d,1);dojo.isIE?f.removeRule(d):f.sheet?f.sheet.deleteRule(d):document.styleSheets[0]&&console.log("what browser hath useth thith?");return!0};dojox.html.getStyleSheet=
function(a){if(e[a||"default"])return e[a||"default"];if(!a)return!1;var b=dojox.html.getStyleSheets();if(b[a])return dojox.html.getStyleSheets()[a];for(var c in b)if(b[c].href&&b[c].href.indexOf(a)>-1)return b[c];return!1};dojox.html.getDynamicStyleSheet=function(a){a||(a="default");if(!e[a]){if(dojo.doc.createStyleSheet){if(e[a]=dojo.doc.createStyleSheet(),dojo.isIE<9)e[a].title=a}else e[a]=dojo.doc.createElement("style"),e[a].setAttribute("type","text/css"),dojo.doc.getElementsByTagName("head")[0].appendChild(e[a]),
console.log(a," ss created: ",e[a].sheet);e[a]._indicies=[]}return e[a]};dojox.html.enableStyleSheet=function(a){if(a=dojox.html.getStyleSheet(a))a.sheet?a.sheet.disabled=!1:a.disabled=!1};dojox.html.disableStyleSheet=function(a){if(a=dojox.html.getStyleSheet(a))a.sheet?a.sheet.disabled=!0:a.disabled=!0};dojox.html.activeStyleSheet=function(a){var b=dojox.html.getToggledStyleSheets();if(arguments.length==1)dojo.forEach(b,function(b){b.disabled=b.title==a?!1:!0});else for(var c=0;c<b.length;c++)if(b[c].disabled==
!1)return b[c];return!0};dojox.html.getPreferredStyleSheet=function(){};dojox.html.getToggledStyleSheets=function(){if(!g.length){var a=dojox.html.getStyleSheets(),b;for(b in a)a[b].title&&g.push(a[b])}return g};dojox.html.getStyleSheets=function(){if(d.collected)return d;dojo.forEach(dojo.doc.styleSheets,function(a){var b=a.sheet?a.sheet:a,a=b.title||b.href;dojo.isIE?b.cssText.indexOf("#default#VML")==-1&&(b.href?d[a]=b:b.imports.length?dojo.forEach(b.imports,function(a){d[a.title||a.href]=a}):d[a]=
b):(d[a]=b,d[a].id=b.ownerNode.id,dojo.forEach(b.cssRules,function(a){if(a.href)d[a.href]=a.styleSheet,d[a.href].id=b.ownerNode.id}))});d.collected=!0;return d}}());