/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.AutoUrlLink"]||(dojo._hasResource["dojox.editor.plugins.AutoUrlLink"]=!0,dojo.provide("dojox.editor.plugins.AutoUrlLink"),dojo.require("dojo.string"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.form.Button"),dojo.declare("dojox.editor.plugins.AutoUrlLink",[dijit._editor._Plugin],{_template:"<a _djrealurl='${url}' href='${url}'>${url}</a>",setEditor:function(a){this.editor=a;dojo.isIE||(dojo.some(a._plugins,function(a){return a.isInstanceOf(dijit._editor.plugins.EnterKeyHandling)?
(this.blockNodeForEnter=a.blockNodeForEnter,!0):!1},this),this.connect(a,"onKeyPress","_keyPress"),this.connect(a,"onClick","_recognize"),this.connect(a,"onBlur","_recognize"))},_keyPress:function(a){var d=dojo.keys,c=a.keyCode,b=a.charCode;b==d.SPACE||a.ctrlKey&&(b==118||b==86)?setTimeout(dojo.hitch(this,"_recognize"),0):c==d.ENTER?setTimeout(dojo.hitch(this,function(){this._recognize({enter:!0})}),0):this._saved=this.editor.window.getSelection().anchorNode},_recognize:function(a){var d=this._template,
c=a?a.enter:!1,a=this.editor,b=a.window.getSelection();if(b){var c=c?this._findLastEditingNode(b.anchorNode):this._saved||b.anchorNode,f=this._saved=b.anchorNode,g=b.anchorOffset;if(c.nodeType==3&&!this._inLink(c)){var e=!1,j=this._findUrls(c,f,g),h=a.document.createRange(),i,k=0,l=f==c;for(i=j.shift();i;)h.setStart(c,i.start),h.setEnd(c,i.end),b.removeAllRanges(),b.addRange(h),a.execCommand("insertHTML",dojo.string.substitute(d,{url:h.toString()})),k+=i.end,i=j.shift(),e=!0;if(!(l&&(g-=k)<=0)&&e)try{h.setStart(f,
0),h.setEnd(f,g),b.removeAllRanges(),b.addRange(h),dojo.withGlobal(a.window,"collapse",dijit._editor.selection,[])}catch(m){}}}},_inLink:function(a){for(var d=this.editor.editNode,c=!1,b,a=a.parentNode;a&&a!==d;){b=a.tagName?a.tagName.toLowerCase():"";if(b=="a"){c=!0;break}a=a.parentNode}return c},_findLastEditingNode:function(a){var d=dijit.range.BlockTagNames,c=this.editor.editNode,b;if(!a)return a;if(this.blockNodeForEnter=="BR"&&(!(b=dijit.range.getBlockAncestor(a,null,c).blockNode)||b.tagName.toUpperCase()!=
"LI"))for(;(a=a.previousSibling)&&a.nodeType!=3;);else{for(a=(b||(b=dijit.range.getBlockAncestor(a,null,c).blockNode))&&b.tagName.toUpperCase()=="LI"?b:dijit.range.getBlockAncestor(a,null,c).blockNode;(a=a.previousSibling)&&(!a.tagName||!a.tagName.match(d)););if(a)for(a=a.lastChild;a;)if(a.nodeType==3&&dojo.trim(a.nodeValue)!="")break;else a=a.nodeType==1?a.lastChild:a.previousSibling}return a},_findUrls:function(a,d,c){var b=/(http|https|ftp):\/\/[^\s]+/ig,f=[],g=0,e=a.nodeValue,j;for(a===d&&c<e.length&&
(e=e.substr(0,c));(a=b.exec(e))!=null;)if(a.index==0||(j=e.charAt(a.index-1))==" "||j=="\u00a0")f.push({start:a.index-g,end:a.index+a[0].length-g}),g=a.index+a[0].length;return f}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="autourllink")a.plugin=new dojox.editor.plugins.AutoUrlLink}));