/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.Blockquote"]||(dojo._hasResource["dojox.editor.plugins.Blockquote"]=!0,dojo.provide("dojox.editor.plugins.Blockquote"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.form.Button"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojox.editor.plugins","Blockquote",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dojox.editor.plugins.Blockquote",dijit._editor._Plugin,{iconClassPrefix:"dijitAdditionalEditorIcon",
_initButton:function(){this._nlsResources=dojo.i18n.getLocalization("dojox.editor.plugins","Blockquote");this.button=new dijit.form.ToggleButton({label:this._nlsResources.blockquote,showLabel:!1,iconClass:this.iconClassPrefix+" "+this.iconClassPrefix+"Blockquote",tabIndex:"-1",onClick:dojo.hitch(this,"_toggleQuote")})},setEditor:function(a){this.editor=a;this._initButton();this.connect(this.editor,"onNormalizedDisplayChanged","updateState");a.customUndo=!0},_toggleQuote:function(){try{var a=this.editor;
a.focus();var e=this.button.get("checked"),g=dijit.range.getSelection(a.window),d,i,b,h;g&&g.rangeCount>0&&(d=g.getRangeAt(0));if(d){a.beginEditing();if(e){var c,k;if(d.startContainer===d.endContainer){if(this._isRootInline(d.startContainer)){for(b=d.startContainer;b&&b.parentNode!==a.editNode;)b=b.parentNode;for(;b&&b.previousSibling&&(this._isTextElement(b)||b.nodeType===1&&this._isInlineFormat(this._getTagName(b)));)b=b.previousSibling;if(b&&b.nodeType===1&&!this._isInlineFormat(this._getTagName(b)))b=
b.nextSibling;if(b){c=a.document.createElement("blockquote");dojo.place(c,b,"after");c.appendChild(b);for(h=c.nextSibling;h&&(this._isTextElement(h)||h.nodeType===1&&this._isInlineFormat(this._getTagName(h)));)c.appendChild(h),h=c.nextSibling}}else{for(var j=d.startContainer;(this._isTextElement(j)||this._isInlineFormat(this._getTagName(j))||this._getTagName(j)==="li")&&j!==a.editNode&&j!==a.document.body;)j=j.parentNode;j!==a.editNode&&j!==j.ownerDocument.documentElement&&(c=a.document.createElement("blockquote"),
dojo.place(c,j,"after"),c.appendChild(j))}c&&(dojo.withGlobal(a.window,"selectElementChildren",dijit._editor.selection,[c]),dojo.withGlobal(a.window,"collapse",dijit._editor.selection,[!0]))}else{var f;b=d.startContainer;for(h=d.endContainer;b&&this._isTextElement(b)&&b.parentNode!==a.editNode;)b=b.parentNode;for(f=b;f.nextSibling&&dojo.withGlobal(a.window,"inSelection",dijit._editor.selection,[f]);)f=f.nextSibling;h=f;if(h===a.editNode||h===a.document.body){c=a.document.createElement("blockquote");
dojo.place(c,b,"after");k=this._getTagName(b);if(this._isTextElement(b)||this._isInlineFormat(k))for(a=b;a&&(this._isTextElement(a)||a.nodeType===1&&this._isInlineFormat(this._getTagName(a)));)c.appendChild(a),a=c.nextSibling;else c.appendChild(b);return}h=h.nextSibling;for(f=b;f&&f!==h;){if(f.nodeType===1){if(k=this._getTagName(f),k!=="br"){if(!window.getSelection&&k==="p"&&this._isEmpty(f)){f=f.nextSibling;continue}this._isInlineFormat(k)?c||(c=a.document.createElement("blockquote"),dojo.place(c,
f,"after")):(c&&this._isEmpty(c)&&c.parentNode.removeChild(c),c=a.document.createElement("blockquote"),dojo.place(c,f,"after"));c.appendChild(f);f=c}}else this._isTextElement(f)&&(c||(c=a.document.createElement("blockquote"),dojo.place(c,f,"after")),c.appendChild(f),f=c);f=f.nextSibling}c&&(this._isEmpty(c)?c.parentNode.removeChild(c):(dojo.withGlobal(a.window,"selectElementChildren",dijit._editor.selection,[c]),dojo.withGlobal(a.window,"collapse",dijit._editor.selection,[!0])))}}else if(c=!1,d.startContainer===
d.endContainer){for(i=d.endContainer;i&&i!==a.editNode&&i!==a.document.body;){if((i.tagName?i.tagName.toLowerCase():"")==="blockquote"){c=!0;break}i=i.parentNode}if(c){for(var m;i.firstChild;)m=i.firstChild,dojo.place(m,i,"before");i.parentNode.removeChild(i);m&&(dojo.withGlobal(a.window,"selectElementChildren",dijit._editor.selection,[m]),dojo.withGlobal(a.window,"collapse",dijit._editor.selection,[!0]))}}else{for(b=d.startContainer;b&&this._isTextElement(b)&&b.parentNode!==a.editNode;)b=b.parentNode;
for(d=[];b&&b.nextSibling&&dojo.withGlobal(a.window,"inSelection",dijit._editor.selection,[b]);){if(b.parentNode&&this._getTagName(b.parentNode)==="blockquote")b=b.parentNode;d.push(b);b=b.nextSibling}for(var n=this._findBlockQuotes(d);n.length;){var l=n.pop();if(l.parentNode){for(;l.firstChild;)dojo.place(l.firstChild,l,"before");l.parentNode.removeChild(l)}}}a.endEditing()}a.onNormalizedDisplayChanged()}catch(o){}},updateState:function(){var a=this.editor,e=this.get("disabled");if(a&&a.isLoaded&&
this.button&&(this.button.set("disabled",e),!e)){var g,e=!1,d=dijit.range.getSelection(a.window);if(d&&d.rangeCount>0&&(d=d.getRangeAt(0)))g=d.endContainer;for(;g&&g!==a.editNode&&g!==a.document;){if((g.tagName?g.tagName.toLowerCase():"")==="blockquote"){e=!0;break}g=g.parentNode}this.button.set("checked",e)}},_findBlockQuotes:function(a){var e=[];if(a){var g;for(g=0;g<a.length;g++){var d=a[g];d.nodeType===1&&(this._getTagName(d)==="blockquote"&&e.push(d),d.childNodes&&d.childNodes.length>0&&(e=e.concat(this._findBlockQuotes(d.childNodes))))}}return e},
_getTagName:function(a){var e="";a&&a.nodeType===1&&(e=a.tagName?a.tagName.toLowerCase():"");return e},_isRootInline:function(a){var e=this.editor;if(this._isTextElement(a)&&a.parentNode===e.editNode)return!0;else if(a.nodeType===1&&this._isInlineFormat(a)&&a.parentNode===e.editNode)return!0;else if(this._isTextElement(a)&&this._isInlineFormat(this._getTagName(a.parentNode))){for(a=a.parentNode;a&&a!==e.editNode&&this._isInlineFormat(this._getTagName(a));)a=a.parentNode;if(a===e.editNode)return!0}return!1},
_isTextElement:function(a){return a&&a.nodeType===3||a.nodeType===4?!0:!1},_isEmpty:function(a){if(a.childNodes){var e=!0,g;for(g=0;g<a.childNodes.length;g++){var d=a.childNodes[g];if(d.nodeType===1){if(this._getTagName(d)!=="p"||dojo.trim(d.innerHTML)){e=!1;break}}else if(this._isTextElement(d)){if((d=dojo.trim(d.nodeValue))&&d!=="&nbsp;"&&d!=="\u00a0"){e=!1;break}}else{e=!1;break}}return e}else return!0},_isInlineFormat:function(a){switch(a){case "a":case "b":case "strong":case "s":case "strike":case "i":case "u":case "em":case "sup":case "sub":case "span":case "font":case "big":case "cite":case "q":case "img":case "small":return!0;
default:return!1}}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="blockquote")a.plugin=new dojox.editor.plugins.Blockquote({})}));