/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.Breadcrumb"]||(dojo._hasResource["dojox.editor.plugins.Breadcrumb"]=!0,dojo.provide("dojox.editor.plugins.Breadcrumb"),dojo.require("dojo.string"),dojo.require("dijit.Toolbar"),dojo.require("dijit.Menu"),dojo.require("dijit.MenuItem"),dojo.require("dijit.MenuSeparator"),dojo.require("dijit._editor.range"),dojo.require("dijit._editor.selection"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.form.Button"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojox.editor.plugins",
"Breadcrumb",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.experimental("dojox.editor.plugins.Breadcrumb"),dojo.declare("dojox.editor.plugins._BreadcrumbMenuTitle",[dijit._Widget,dijit._Templated,dijit._Contained],{templateString:'<tr><td dojoAttachPoint="title" colspan="4" class="dijitToolbar" style="font-weight: bold; padding: 3px;"></td></tr>',menuTitle:"",postCreate:function(){dojo.setSelectable(this.domNode,!1);dijit.setWaiState(this.domNode,
"labelledby",this.id+"_text")},_setMenuTitleAttr:function(a){this.title.innerHTML=a},_getMenuTitleAttr:function(){return this.title.innerHTML}}),dojo.declare("dojox.editor.plugins.Breadcrumb",dijit._editor._Plugin,{_menu:null,breadcrumbBar:null,setEditor:function(a){this.editor=a;this._buttons=[];this.breadcrumbBar=new dijit.Toolbar;var c=dojo.i18n.getLocalization("dojox.editor.plugins","Breadcrumb");this._titleTemplate=c.nodeActions;dojo.place(this.breadcrumbBar.domNode,a.footer);this.editor.onLoadDeferred.addCallback(dojo.hitch(this,
function(){this._menu=new dijit.Menu({});dojo.addClass(this.breadcrumbBar.domNode,"dojoxEditorBreadcrumbArrow");var b=new dijit.form.ComboButton({showLabel:!0,label:"body",_selNode:a.editNode,dropDown:this._menu,onClick:dojo.hitch(this,function(){this._menuTarget=a.editNode;this._selectContents()})});this._menuTitle=new dojox.editor.plugins._BreadcrumbMenuTitle({menuTitle:c.nodeActions});this._selCMenu=new dijit.MenuItem({label:c.selectContents,onClick:dojo.hitch(this,this._selectContents)});this._delCMenu=
new dijit.MenuItem({label:c.deleteContents,onClick:dojo.hitch(this,this._deleteContents)});this._selEMenu=new dijit.MenuItem({label:c.selectElement,onClick:dojo.hitch(this,this._selectElement)});this._delEMenu=new dijit.MenuItem({label:c.deleteElement,onClick:dojo.hitch(this,this._deleteElement)});this._moveSMenu=new dijit.MenuItem({label:c.moveStart,onClick:dojo.hitch(this,this._moveCToStart)});this._moveEMenu=new dijit.MenuItem({label:c.moveEnd,onClick:dojo.hitch(this,this._moveCToEnd)});this._menu.addChild(this._menuTitle);
this._menu.addChild(this._selCMenu);this._menu.addChild(this._delCMenu);this._menu.addChild(new dijit.MenuSeparator({}));this._menu.addChild(this._selEMenu);this._menu.addChild(this._delEMenu);this._menu.addChild(new dijit.MenuSeparator({}));this._menu.addChild(this._moveSMenu);this._menu.addChild(this._moveEMenu);b._ddConnect=dojo.connect(b,"openDropDown",dojo.hitch(this,function(){this._menuTarget=b._selNode;this._menuTitle.set("menuTitle",dojo.string.substitute(this._titleTemplate,{nodeName:"&lt;body&gt;"}));
this._selEMenu.set("disabled",!0);this._delEMenu.set("disabled",!0);this._selCMenu.set("disabled",!1);this._delCMenu.set("disabled",!1);this._moveSMenu.set("disabled",!1);this._moveEMenu.set("disabled",!1)}));this.breadcrumbBar.addChild(b);this.connect(this.editor,"onNormalizedDisplayChanged","updateState")}));this.breadcrumbBar.startup();dojo.isIE&&setTimeout(dojo.hitch(this,function(){this.breadcrumbBar.domNode.className=this.breadcrumbBar.domNode.className}),100)},_selectContents:function(){this.editor.focus();
if(this._menuTarget)switch(this._menuTarget.tagName.toLowerCase()){case "br":case "hr":case "img":case "input":case "base":case "meta":case "area":case "basefont":break;default:try{dojo.withGlobal(this.editor.window,"collapse",dijit._editor.selection,[null]),dojo.withGlobal(this.editor.window,"selectElementChildren",dijit._editor.selection,[this._menuTarget]),this.editor.onDisplayChanged()}catch(a){}}},_deleteContents:function(){this._menuTarget&&(this.editor.beginEditing(),this._selectContents(),
dojo.withGlobal(this.editor.window,"remove",dijit._editor.selection,[this._menuTarget]),this.editor.endEditing(),this._updateBreadcrumb(),this.editor.onDisplayChanged())},_selectElement:function(){this.editor.focus();this._menuTarget&&(dojo.withGlobal(this.editor.window,"collapse",dijit._editor.selection,[null]),dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[this._menuTarget]),this.editor.onDisplayChanged())},_deleteElement:function(){this._menuTarget&&(this.editor.beginEditing(),
this._selectElement(),dojo.withGlobal(this.editor.window,"remove",dijit._editor.selection,[this._menuTarget]),this.editor.endEditing(),this._updateBreadcrumb(),this.editor.onDisplayChanged())},_moveCToStart:function(){this.editor.focus();this._menuTarget&&(this._selectContents(),dojo.withGlobal(this.editor.window,"collapse",dijit._editor.selection,[!0]))},_moveCToEnd:function(){this.editor.focus();this._menuTarget&&(this._selectContents(),dojo.withGlobal(this.editor.window,"collapse",dijit._editor.selection,
[!1]))},_updateBreadcrumb:function(){var a=this.editor;if(a.window){var c=dijit.range.getSelection(a.window);if(c&&c.rangeCount>0){var c=c.getRangeAt(0),b=dojo.withGlobal(a.window,"getSelectedElement",dijit._editor.selection)||c.startContainer,c=[];if(b&&b.ownerDocument===a.document){for(;b&&b!==a.editNode&&b!=a.document.body&&b!=a.document;)b.nodeType===1&&c.push({type:b.tagName.toLowerCase(),node:b}),b=b.parentNode;for(c=c.reverse();this._buttons.length;)a=this._buttons.pop(),dojo.disconnect(a._ddConnect),
this.breadcrumbBar.removeChild(a);this._buttons=[];for(var d=this,a=0;a<c.length;a++)b=c[a],b=new dijit.form.ComboButton({showLabel:!0,label:b.type,_selNode:b.node,dropDown:this._menu,onClick:function(){d._menuTarget=this._selNode;d._selectContents()}}),b._ddConnect=dojo.connect(b,"openDropDown",dojo.hitch(b,function(){d._menuTarget=this._selNode;var a=d._menuTarget.tagName.toLowerCase(),b=dojo.string.substitute(d._titleTemplate,{nodeName:"&lt;"+a+"&gt;"});d._menuTitle.set("menuTitle",b);switch(a){case "br":case "hr":case "img":case "input":case "base":case "meta":case "area":case "basefont":d._selCMenu.set("disabled",
!0);d._delCMenu.set("disabled",!0);d._moveSMenu.set("disabled",!0);d._moveEMenu.set("disabled",!0);d._selEMenu.set("disabled",!1);d._delEMenu.set("disabled",!1);break;default:d._selCMenu.set("disabled",!1),d._delCMenu.set("disabled",!1),d._selEMenu.set("disabled",!1),d._delEMenu.set("disabled",!1),d._moveSMenu.set("disabled",!1),d._moveEMenu.set("disabled",!1)}})),this._buttons.push(b),this.breadcrumbBar.addChild(b);if(dojo.isIE)this.breadcrumbBar.domNode.className=this.breadcrumbBar.domNode.className}}}},
updateState:function(){dojo.style(this.editor.iframe,"display")==="none"||this.get("disabled")?dojo.style(this.breadcrumbBar.domNode,"display","none"):(dojo.style(this.breadcrumbBar.domNode,"display")==="none"&&dojo.style(this.breadcrumbBar.domNode,"display","block"),this._updateBreadcrumb(),this.editor.resize({h:dojo.marginBox(this.editor.domNode).h}))},destroy:function(){if(this.breadcrumbBar)this.breadcrumbBar.destroyRecursive(),this.breadcrumbBar=null;this._menu&&(this._menu.destroyRecursive(),
delete this._menu);this._buttons=null;delete this.editor.breadcrumbBar;this.inherited(arguments)}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="breadcrumb")a.plugin=new dojox.editor.plugins.Breadcrumb({})}));