/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.EntityPalette"]||(dojo._hasResource["dojox.editor.plugins.EntityPalette"]=!0,dojo.provide("dojox.editor.plugins.EntityPalette"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit._PaletteMixin"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojox.editor.plugins","latinEntities",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.experimental("dojox.editor.plugins.EntityPalette"),
dojo.declare("dojox.editor.plugins.EntityPalette",[dijit._Widget,dijit._Templated,dijit._PaletteMixin],{templateString:'<div class="dojoxEntityPalette">\n\t<table>\n\t\t<tbody>\n\t\t\t<tr>\n\t\t\t\t<td>\n\t\t\t\t\t<table class="dijitPaletteTable">\n\t\t\t\t\t\t<tbody dojoAttachPoint="gridNode"></tbody>\n\t\t\t\t   </table>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td>\n\t\t\t\t\t<table dojoAttachPoint="previewPane" class="dojoxEntityPalettePreviewTable">\n\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t<th class="dojoxEntityPalettePreviewHeader">Preview</th>\n\t\t\t\t\t\t\t\t<th class="dojoxEntityPalettePreviewHeader" dojoAttachPoint="codeHeader">Code</th>\n\t\t\t\t\t\t\t\t<th class="dojoxEntityPalettePreviewHeader" dojoAttachPoint="entityHeader">Name</th>\n\t\t\t\t\t\t\t\t<th class="dojoxEntityPalettePreviewHeader">Description</th>\n\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t<td class="dojoxEntityPalettePreviewDetailEntity" dojoAttachPoint="previewNode"></td>\n\t\t\t\t\t\t\t\t<td class="dojoxEntityPalettePreviewDetail" dojoAttachPoint="codeNode"></td>\n\t\t\t\t\t\t\t\t<td class="dojoxEntityPalettePreviewDetail" dojoAttachPoint="entityNode"></td>\n\t\t\t\t\t\t\t\t<td class="dojoxEntityPalettePreviewDetail" dojoAttachPoint="descNode"></td>\n\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t</tbody>\n\t\t\t\t\t</table>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n</div>',
baseClass:"dojoxEntityPalette",showPreview:!0,showCode:!1,showEntityName:!1,palette:"latin",dyeClass:"dojox.editor.plugins.LatinEntity",paletteClass:"editorLatinEntityPalette",cellClass:"dojoxEntityPaletteCell",postMixInProperties:function(){var a=dojo.i18n.getLocalization("dojox.editor.plugins","latinEntities"),b=0,d;for(d in a)b++;var b=Math.floor(Math.sqrt(b)),f=0,e=[],c=[];for(d in a)f++,c.push(d),f%b===0&&(e.push(c),c=[]);c.length>0&&e.push(c);this._palette=e},buildRendering:function(){this.inherited(arguments);
this._preparePalette(this._palette,dojo.i18n.getLocalization("dojox.editor.plugins","latinEntities"));var a=dojo.query(".dojoxEntityPaletteCell",this.gridNode);dojo.forEach(a,function(a){this.connect(a,"onmouseenter","_onCellMouseEnter")},this)},_onCellMouseEnter:function(a){this._displayDetails(a.target)},postCreate:function(){this.inherited(arguments);dojo.style(this.codeHeader,"display",this.showCode?"":"none");dojo.style(this.codeNode,"display",this.showCode?"":"none");dojo.style(this.entityHeader,
"display",this.showEntityName?"":"none");dojo.style(this.entityNode,"display",this.showEntityName?"":"none");this.showPreview||dojo.style(this.previewNode,"display","none")},_setCurrent:function(a){this.inherited(arguments);this.showPreview&&this._displayDetails(a)},_displayDetails:function(a){var b=this._getDye(a);b?(a=b.getValue(),b=b._alias,this.previewNode.innerHTML=a,this.codeNode.innerHTML="&amp;#"+parseInt(a.charCodeAt(0),10)+";",this.entityNode.innerHTML="&amp;"+b+";",this.descNode.innerHTML=
dojo.i18n.getLocalization("dojox.editor.plugins","latinEntities")[b].replace("\n","<br>")):(this.previewNode.innerHTML="",this.codeNode.innerHTML="",this.entityNode.innerHTML="",this.descNode.innerHTML="")}}),dojo.declare("dojox.editor.plugins.LatinEntity",null,{constructor:function(a){this._alias=a},getValue:function(){return"&"+this._alias+";"},fillCell:function(a){a.innerHTML=this.getValue()}}));