/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.InsertAnchor"]||(dojo._hasResource["dojox.editor.plugins.InsertAnchor"]=!0,dojo.provide("dojox.editor.plugins.InsertAnchor"),dojo.require("dojo.string"),dojo.require("dijit._Widget"),dojo.require("dijit._editor.range"),dojo.require("dijit._Templated"),dojo.require("dijit.TooltipDialog"),dojo.require("dijit.form.ValidationTextBox"),dojo.require("dijit.form.Select"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.form.Button"),dojo.require("dojox.editor.plugins.ToolbarLineBreak"),
dojo.require("dojo.i18n"),dojo.requireLocalization("dojox.editor.plugins","InsertAnchor",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.requireLocalization("dijit","common",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dojox.editor.plugins.InsertAnchor",dijit._editor._Plugin,{htmlTemplate:'<a name="${anchorInput}" class="dijitEditorPluginInsertAnchorStyle">${textInput}</a>',
iconClassPrefix:"dijitAdditionalEditorIcon",_template:"<table><tr><td><label for='${id}_anchorInput'>${anchor}</label></td><td><input dojoType='dijit.form.ValidationTextBox' required='true' id='${id}_anchorInput' name='anchorInput' intermediateChanges='true'></td></tr><tr><td><label for='${id}_textInput'>${text}</label></td><td><input dojoType='dijit.form.ValidationTextBox' required='true' id='${id}_textInput' name='textInput' intermediateChanges='true'></td></tr><tr><td colspan='2'><button dojoType='dijit.form.Button' type='submit' id='${id}_setButton'>${set}</button><button dojoType='dijit.form.Button' type='button' id='${id}_cancelButton'>${cancel}</button></td></tr></table>",
_initButton:function(){var a=this,b=dojo.i18n.getLocalization("dojox.editor.plugins","InsertAnchor",this.lang),c=this.dropDown=new dijit.TooltipDialog({title:b.title,execute:dojo.hitch(this,"setValue"),onOpen:function(){a._onOpenDialog();dijit.TooltipDialog.prototype.onOpen.apply(this,arguments)},onCancel:function(){setTimeout(dojo.hitch(a,"_onCloseDialog"),0)}});this.button=new dijit.form.DropDownButton({label:b.insertAnchor,showLabel:!1,iconClass:this.iconClassPrefix+" "+this.iconClassPrefix+"InsertAnchor",
tabIndex:"-1",dropDown:this.dropDown});b.id=dijit.getUniqueId(this.editor.id);this._uniqueId=b.id;this.dropDown.set("content",c.title+"<div style='border-bottom: 1px black solid;padding-bottom:2pt;margin-bottom:4pt'></div>"+dojo.string.substitute(this._template,b));c.startup();this._anchorInput=dijit.byId(this._uniqueId+"_anchorInput");this._textInput=dijit.byId(this._uniqueId+"_textInput");this._setButton=dijit.byId(this._uniqueId+"_setButton");this.connect(dijit.byId(this._uniqueId+"_cancelButton"),
"onClick",function(){this.dropDown.onCancel()});this._anchorInput&&this.connect(this._anchorInput,"onChange","_checkInput");this._textInput&&this.connect(this._anchorInput,"onChange","_checkInput");this.editor.contentDomPreFilters.push(dojo.hitch(this,this._preDomFilter));this.editor.contentDomPostFilters.push(dojo.hitch(this,this._postDomFilter));this._setup()},updateState:function(){this.button.set("disabled",this.get("disabled"))},setEditor:function(a){this.editor=a;this._initButton()},_checkInput:function(){var a=
!0;this._anchorInput.isValid()&&(a=!1);this._setButton.set("disabled",a)},_setup:function(){this.editor.onLoadDeferred.addCallback(dojo.hitch(this,function(){this.connect(this.editor.editNode,"ondblclick",this._onDblClick);setTimeout(dojo.hitch(this,function(){this._applyStyles()}),100)}))},getAnchorStyle:function(){var a=dojo.moduleUrl(dojox._scopeName,"editor/plugins/resources").toString();if(!a.match(/^https?:\/\//i)&&!a.match(/^file:\/\//i)){var b;b=a.charAt(0)==="/"?dojo.doc.location.protocol+
"//"+dojo.doc.location.host:this._calcBaseUrl(dojo.global.location.href);b[b.length-1]!=="/"&&a.charAt(0)!=="/"&&(b+="/");a=b+a}return"@media screen {\n\t.dijitEditorPluginInsertAnchorStyle {\n\t\tbackground-image: url({MODURL}/images/anchor.gif);\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: top left;\n\t\tborder-width: 1px;\n\t\tborder-style: dashed;\n\t\tborder-color: #D0D0D0;\n\t\tpadding-left: 20px;\n\t}\n}\n".replace(/\{MODURL\}/gi,a)},_applyStyles:function(){if(!this._styled)try{this._styled=
!0;var a=this.editor.document,b=this.getAnchorStyle();if(dojo.isIE)a.createStyleSheet("").cssText=b;else{var c=a.createElement("style");c.appendChild(a.createTextNode(b));a.getElementsByTagName("head")[0].appendChild(c)}}catch(d){}},_calcBaseUrl:function(a){var b=null;a!==null&&(b=a.indexOf("?"),b!=-1&&(a=a.substring(0,b)),b=a.lastIndexOf("/"),b=b>0&&b<a.length?a.substring(0,b):a);return b},_checkValues:function(a){if(a){if(a.anchorInput)a.anchorInput=a.anchorInput.replace(/"/g,"&quot;");if(!a.textInput)a.textInput=
"&nbsp;"}return a},setValue:function(a){this._onCloseDialog();if(!this.editor.window.getSelection){var b=dijit.range.getSelection(this.editor.window).getRangeAt(0).endContainer;if(b.nodeType===3)b=b.parentNode;b&&b.nodeName&&b.nodeName.toLowerCase()!=="a"&&(b=dojo.withGlobal(this.editor.window,"getSelectedElement",dijit._editor.selection,["a"]));b&&b.nodeName&&b.nodeName.toLowerCase()==="a"&&this.editor.queryCommandEnabled("unlink")&&(dojo.withGlobal(this.editor.window,"selectElementChildren",dijit._editor.selection,
[b]),this.editor.execCommand("unlink"))}a=this._checkValues(a);this.editor.execCommand("inserthtml",dojo.string.substitute(this.htmlTemplate,a))},_onCloseDialog:function(){this.editor.focus()},_getCurrentValues:function(a){var b,c;a&&a.tagName.toLowerCase()==="a"&&dojo.attr(a,"name")?(b=dojo.attr(a,"name"),c=a.textContent||a.innerText,dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[a,!0])):c=dojo.withGlobal(this.editor.window,dijit._editor.selection.getSelectedText);return{anchorInput:b||
"",textInput:c||""}},_onOpenDialog:function(){var a;if(this.editor.window.getSelection)a=dojo.withGlobal(this.editor.window,"getAncestorElement",dijit._editor.selection,["a"]);else{a=dijit.range.getSelection(this.editor.window).getRangeAt(0).endContainer;if(a.nodeType===3)a=a.parentNode;a&&a.nodeName&&a.nodeName.toLowerCase()!=="a"&&(a=dojo.withGlobal(this.editor.window,"getSelectedElement",dijit._editor.selection,["a"]))}this.dropDown.reset();this._setButton.set("disabled",!0);this.dropDown.set("value",
this._getCurrentValues(a))},_onDblClick:function(a){if(a&&a.target&&(a=a.target,(a.tagName?a.tagName.toLowerCase():"")==="a"&&dojo.attr(a,"name")))this.editor.onDisplayChanged(),dojo.withGlobal(this.editor.window,"selectElement",dijit._editor.selection,[a]),setTimeout(dojo.hitch(this,function(){this.button.set("disabled",!1);this.button.openDropDown()}),10)},_preDomFilter:function(){var a=this.editor;dojo.withGlobal(a.window,function(){dojo.query("a",a.editNode).forEach(function(a){dojo.attr(a,"name")&&
!dojo.attr(a,"href")&&(dojo.hasClass(a,"dijitEditorPluginInsertAnchorStyle")||dojo.addClass(a,"dijitEditorPluginInsertAnchorStyle"))})})},_postDomFilter:function(a){dojo.withGlobal(this.editor.window,function(){dojo.query("a",a).forEach(function(a){dojo.attr(a,"name")&&!dojo.attr(a,"href")&&dojo.hasClass(a,"dijitEditorPluginInsertAnchorStyle")&&dojo.removeClass(a,"dijitEditorPluginInsertAnchorStyle")})});return a}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin){var b=
a.args.name;b&&(b=b.toLowerCase());if(b==="insertanchor")a.plugin=new dojox.editor.plugins.InsertAnchor}}));