/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.LocalImage"]||(dojo._hasResource["dojox.editor.plugins.LocalImage"]=!0,dojo.provide("dojox.editor.plugins.LocalImage"),dojo.require("dijit._editor.plugins.LinkDialog"),dojo.require("dojox.form.FileUploader"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojox.editor.plugins","LocalImage",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dojox.editor.plugins.LocalImage",dijit._editor.plugins.ImgLinkDialog,
{uploadable:!1,uploadUrl:"",baseImageUrl:"",fileMask:"*.jpg;*.jpeg;*.gif;*.png;*.bmp",urlRegExp:"",_fileUploader:null,htmlFieldName:"uploadedfile",_isLocalFile:!1,_messages:"",_cssPrefix:"dijitEditorEilDialog",_closable:!0,linkDialogTemplate:"<div style='border-bottom: 1px solid black; padding-bottom: 2pt; margin-bottom: 4pt;'></div><div class='dijitEditorEilDialogDescription'>${prePopuTextUrl}${prePopuTextBrowse}</div><table><tr><td colspan='2'><label for='${id}_urlInput' title='${prePopuTextUrl}${prePopuTextBrowse}'>${url}</label></td></tr><tr><td class='dijitEditorEilDialogField'><input dojoType='dijit.form.ValidationTextBox' class='dijitEditorEilDialogField'regExp='${urlRegExp}' title='${prePopuTextUrl}${prePopuTextBrowse}'  selectOnClick='true' required='true' id='${id}_urlInput' name='urlInput' intermediateChanges='true' invalidMessage='${invalidMessage}' prePopuText='&lt;${prePopuTextUrl}${prePopuTextBrowse}&gt'></td><td><div id='${id}_browse' style='display:${uploadable}'>${browse}</div></td></tr><tr><td colspan='2'><label for='${id}_textInput'>${text}</label></td></tr><tr><td><input dojoType='dijit.form.TextBox' required='false' id='${id}_textInput' name='textInput' intermediateChanges='true' selectOnClick='true' class='dijitEditorEilDialogField'></td><td></td></tr><tr><td></td><td></td></tr><tr><td colspan='2'><button dojoType='dijit.form.Button' id='${id}_setButton'>${set}</button></td></tr></table>",
_initButton:function(){var a=this,b=this._messages=dojo.i18n.getLocalization("dojox.editor.plugins","LocalImage");this.tag="img";var e=this.dropDown=new dijit.TooltipDialog({title:b[this.command+"Title"],onOpen:function(){a._initialFileUploader();a._onOpenDialog();dijit.TooltipDialog.prototype.onOpen.apply(this,arguments);setTimeout(function(){dijit.selectInputText(a._urlInput.textbox);a._urlInput.isLoadComplete=!0},0)},onClose:function(){dojo.disconnect(a.blurHandler);a.blurHandler=null;this.onHide()},
onCancel:function(){setTimeout(dojo.hitch(a,"_onCloseDialog"),0)}}),c=this.getLabel(this.command),g=this.iconClassPrefix+" "+this.iconClassPrefix+this.command.charAt(0).toUpperCase()+this.command.substr(1),c=dojo.mixin({label:c,showLabel:!1,iconClass:g,dropDown:this.dropDown,tabIndex:"-1"},this.params||{});if(!dojo.isIE&&(!dojo.isFF||dojo.isFF<4))c.closeDropDown=function(b){if(a._closable&&this._opened)dijit.popup.close(this.dropDown),b&&this.focus(),this._opened=!1,this.state="";setTimeout(function(){a._closable=
!0},10)};this.button=new dijit.form.DropDownButton(c);var c=this.fileMask.split(";"),d="";dojo.forEach(c,function(a){a=a.replace(/\./,"\\.").replace(/\*/g,".*");d+="|"+a+"|"+a.toUpperCase()});b.urlRegExp=this.urlRegExp=d.substring(1);this.uploadable||(b.prePopuTextBrowse=".");b.id=dijit.getUniqueId(this.editor.id);b.uploadable=this.uploadable?"inline":"none";this._uniqueId=b.id;this._setContent("<div class='"+this._cssPrefix+"Title'>"+e.title+"</div>"+dojo.string.substitute(this.linkDialogTemplate,
b));e.startup();b=this._urlInput=dijit.byId(this._uniqueId+"_urlInput");this._textInput=dijit.byId(this._uniqueId+"_textInput");this._setButton=dijit.byId(this._uniqueId+"_setButton");if(b){var f=dijit.form.ValidationTextBox.prototype,b=dojo.mixin(b,{isLoadComplete:!1,isValid:function(a){return this.isLoadComplete?f.isValid.apply(this,arguments):this.get("value").length>0},reset:function(){this.isLoadComplete=!1;f.reset.apply(this,arguments)}});this.connect(b,"onKeyDown","_cancelFileUpload");this.connect(b,
"onChange","_checkAndFixInput")}this._setButton&&this.connect(this._setButton,"onClick","_checkAndSetValue");this._connectTagEvents()},_initialFileUploader:function(){var a=null,b=this,e=b._uniqueId+"_browse",c=b._urlInput;if(b.uploadable&&!b._fileUploader)a=b._fileUploader=new dojox.form.FileUploader({force:"html",uploadUrl:b.uploadUrl,htmlFieldName:b.htmlFieldName,uploadOnChange:!1,selectMultipleFiles:!1,showProgress:!0},e),a.reset=function(){b._isLocalFile=!1;a._resetHTML()},b.connect(a,"onClick",
function(){c.validate(!1);if(!dojo.isIE&&(!dojo.isFF||dojo.isFF<4))b._closable=!1}),b.connect(a,"onChange",function(a){b._isLocalFile=!0;c.set("value",a[0].name);c.focus()}),b.connect(a,"onComplete",function(a){var d=b.baseImageUrl,d=d&&d.charAt(d.length-1)=="/"?d:d+"/";c.set("value",d+a[0].file);b._isLocalFile=!1;b._setDialogStatus(!0);b.setValue(b.dropDown.get("value"))}),b.connect(a,"onError",function(){console.log("Error occurred when uploading image file!");b._setDialogStatus(!0)})},_checkAndFixInput:function(){this._setButton.set("disabled",
!this._isValid())},_isValid:function(){return this._urlInput.isValid()},_cancelFileUpload:function(){this._fileUploader.reset();this._isLocalFile=!1},_checkAndSetValue:function(){this._fileUploader&&this._isLocalFile?(this._setDialogStatus(!1),this._fileUploader.upload()):this.setValue(this.dropDown.get("value"))},_setDialogStatus:function(a){this._urlInput.set("disabled",!a);this._textInput.set("disabled",!a);this._setButton.set("disabled",!a)},destroy:function(){this.inherited(arguments);if(this._fileUploader)this._fileUploader.destroy(),
this._fileUploader=null}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="localimage")a.plugin=new dojox.editor.plugins.LocalImage({command:"insertImage",uploadable:"uploadable"in a.args?a.args.uploadable:!1,uploadUrl:"uploadable"in a.args&&"uploadUrl"in a.args?a.args.uploadUrl:"",htmlFieldName:"uploadable"in a.args&&"htmlFieldName"in a.args?a.args.htmlFieldName:"uploadedfile",baseImageUrl:"uploadable"in a.args&&"baseImageUrl"in a.args?
a.args.baseImageUrl:"",fileMask:"fileMask"in a.args?a.args.fileMask:"*.jpg;*.jpeg;*.gif;*.png;*.bmp"})}));