/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.NormalizeIndentOutdent"]||(dojo._hasResource["dojox.editor.plugins.NormalizeIndentOutdent"]=!0,dojo.provide("dojox.editor.plugins.NormalizeIndentOutdent"),dojo.require("dijit._editor.selection"),dojo.require("dijit._editor._Plugin"),dojo.declare("dojox.editor.plugins.NormalizeIndentOutdent",dijit._editor._Plugin,{indentBy:40,indentUnits:"px",setEditor:function(a){this.editor=a;a._indentImpl=dojo.hitch(this,this._indentImpl);a._outdentImpl=dojo.hitch(this,this._outdentImpl);
if(!a._indentoutdent_queryCommandEnabled)a._indentoutdent_queryCommandEnabled=a.queryCommandEnabled;a.queryCommandEnabled=dojo.hitch(this,this._queryCommandEnabled);a.customUndo=!0},_queryCommandEnabled:function(a){var c=a.toLowerCase(),b,e,d,f="marginLeft";this._isLtr()||(f="marginRight");if(c==="indent"){if(c=this.editor,(b=dijit.range.getSelection(c.window))&&b.rangeCount>0){b=b.getRangeAt(0);for(e=b.startContainer;e&&e!==c.document&&e!==c.editNode;){d=this._getTagName(e);if(d==="li"){for(a=e.previousSibling;a&&
a.nodeType!==1;)a=a.previousSibling;return a&&this._getTagName(a)==="li"?!0:!1}else if(this._isIndentableElement(d))return!0;e=e.parentNode}if(this._isRootInline(b.startContainer))return!0}}else if(c==="outdent"){if(c=this.editor,(b=dijit.range.getSelection(c.window))&&b.rangeCount>0){b=b.getRangeAt(0);for(e=b.startContainer;e&&e!==c.document&&e!==c.editNode;){d=this._getTagName(e);if(d==="li")return this.editor._indentoutdent_queryCommandEnabled(a);else if(this._isIndentableElement(d)){if(a=e.style?
e.style[f]:"")if(a=this._convertIndent(a),a/this.indentBy>=1)return!0;return!1}e=e.parentNode}this._isRootInline(b.startContainer)}}else return this.editor._indentoutdent_queryCommandEnabled(a);return!1},_indentImpl:function(){var a=this.editor,c=dijit.range.getSelection(a.window);if(c&&c.rangeCount>0){var c=c.getRangeAt(0),b=c.startContainer,e,d;if(c.startContainer===c.endContainer)if(this._isRootInline(c.startContainer)){for(b=c.startContainer;b&&b.parentNode!==a.editNode;)b=b.parentNode;for(;b&&
b.previousSibling&&(this._isTextElement(b)||b.nodeType===1&&this._isInlineFormat(this._getTagName(b)));)b=b.previousSibling;if(b&&b.nodeType===1&&!this._isInlineFormat(this._getTagName(b)))b=b.nextSibling;if(b){d=a.document.createElement("div");dojo.place(d,b,"after");d.appendChild(b);for(e=d.nextSibling;e&&(this._isTextElement(e)||e.nodeType===1&&this._isInlineFormat(this._getTagName(e)));)d.appendChild(e),e=d.nextSibling;this._indentElement(d);dojo.withGlobal(a.window,"selectElementChildren",dijit._editor.selection,
[d]);dojo.withGlobal(a.window,"collapse",dijit._editor.selection,[!0])}}else for(;b&&b!==a.document&&b!==a.editNode;){c=this._getTagName(b);if(c==="li"){this._indentList(b);break}else if(this._isIndentableElement(c)){this._indentElement(b);break}b=b.parentNode}else{var f,b=c.startContainer;for(e=c.endContainer;b&&this._isTextElement(b)&&b.parentNode!==a.editNode;)b=b.parentNode;for(;e&&this._isTextElement(e)&&e.parentNode!==a.editNode;)e=e.parentNode;if(e===a.editNode||e===a.document.body){for(f=
b;f.nextSibling&&dojo.withGlobal(a.window,"inSelection",dijit._editor.selection,[f]);)f=f.nextSibling;e=f;if(e===a.editNode||e===a.document.body){c=this._getTagName(b);if(c==="li")this._indentList(b);else if(this._isIndentableElement(c))this._indentElement(b);else if(this._isTextElement(b)||this._isInlineFormat(c)){d=a.document.createElement("div");dojo.place(d,b,"after");for(a=b;a&&(this._isTextElement(a)||a.nodeType===1&&this._isInlineFormat(this._getTagName(a)));)d.appendChild(a),a=d.nextSibling;
this._indentElement(d)}return}}e=e.nextSibling;for(f=b;f&&f!==e;){if(f.nodeType===1){c=this._getTagName(f);if(dojo.isIE&&c==="p"&&this._isEmpty(f)){f=f.nextSibling;continue}c==="li"?(d&&(this._isEmpty(d)?d.parentNode.removeChild(d):this._indentElement(d),d=null),this._indentList(f)):!this._isInlineFormat(c)&&this._isIndentableElement(c)?(d&&(this._isEmpty(d)?d.parentNode.removeChild(d):this._indentElement(d),d=null),f=this._indentElement(f)):this._isInlineFormat(c)&&(d||(d=a.document.createElement("div"),
dojo.place(d,f,"after")),d.appendChild(f),f=d)}else this._isTextElement(f)&&(d||(d=a.document.createElement("div"),dojo.place(d,f,"after")),d.appendChild(f),f=d);f=f.nextSibling}d&&(this._isEmpty(d)?d.parentNode.removeChild(d):this._indentElement(d))}}},_indentElement:function(a){var c="marginLeft";this._isLtr()||(c="marginRight");var b=this._getTagName(a);if(b==="ul"||b==="ol")b=this.editor.document.createElement("div"),dojo.place(b,a,"after"),b.appendChild(a),a=b;(b=a.style?a.style[c]:"")?(b=this._convertIndent(b),
b=parseInt(b,10)+this.indentBy+this.indentUnits):b=this.indentBy+this.indentUnits;dojo.style(a,c,b);return a},_outdentElement:function(a){var c="marginLeft";this._isLtr()||(c="marginRight");var b=a.style?a.style[c]:"";b&&(b=this._convertIndent(b),b=b-this.indentBy>0?parseInt(b,10)-this.indentBy+this.indentUnits:"",dojo.style(a,c,b))},_outdentImpl:function(a){var c=this.editor,b=dijit.range.getSelection(c.window);if(b&&b.rangeCount>0){var b=b.getRangeAt(0),e=b.startContainer;if(b.startContainer===
b.endContainer){for(;e&&e!==c.document&&e!==c.editNode;){b=this._getTagName(e);if(b==="li")return this._outdentList(e);else if(this._isIndentableElement(b))return this._outdentElement(e);e=e.parentNode}c.document.execCommand("outdent",!1,a)}else{c=b.startContainer;for(a=b.endContainer;c&&c.nodeType===3;)c=c.parentNode;for(;a&&a.nodeType===3;)a=a.parentNode;for(a=a.nextSibling;c&&c!==a;)c.nodeType===1&&(b=this._getTagName(c),b==="li"?this._outdentList(c):this._isIndentableElement(b)&&this._outdentElement(c)),
c=c.nextSibling}}return null},_indentList:function(a){for(var c=this.editor,b,e,d=a.parentNode,f=a.previousSibling;f&&f.nodeType!==1;)f=f.previousSibling;b=null;d=this._getTagName(d);d==="ol"?b="ol":d==="ul"&&(b="ul");if(b&&f&&f.tagName.toLowerCase()=="li"){if(f.childNodes)for(d=0;d<f.childNodes.length;d++){var g=f.childNodes[d];if(g.nodeType===3){if(dojo.trim(g.nodeValue)&&e)break}else if(g.nodeType===1&&!e)b===g.tagName.toLowerCase()&&(e=g);else break}e?e.appendChild(a):(b=c.document.createElement(b),
dojo.style(b,{paddingTop:"0px",paddingBottom:"0px"}),e=c.document.createElement("li"),dojo.style(e,{listStyleImage:"none",listStyleType:"none"}),f.appendChild(b),b.appendChild(a));dojo.withGlobal(c.window,"selectElementChildren",dijit._editor.selection,[a]);dojo.withGlobal(c.window,"collapse",dijit._editor.selection,[!0])}},_outdentList:function(a){var c=this.editor,b=a.parentNode,e=null,d=b.tagName?b.tagName.toLowerCase():"";d==="ol"?e="ol":d==="ul"&&(e="ul");var d=b.parentNode,f=this._getTagName(d);
if(f==="li"||f==="ol"||f==="ul"){if(f==="ol"||f==="ul"){for(d=b.previousSibling;d&&(d.nodeType!==1||d.nodeType===1&&this._getTagName(d)!=="li");)d=d.previousSibling;if(d)d.appendChild(b);else{for(f=d=a;d.previousSibling;)d=d.previousSibling,d.nodeType===1&&this._getTagName(d)==="li"&&(f=d);f!==a?(dojo.place(f,b,"before"),f.appendChild(b),d=f):(d=c.document.createElement("li"),dojo.place(d,b,"before"),d.appendChild(b));dojo.style(b,{paddingTop:"0px",paddingBottom:"0px"})}}for(f=a.previousSibling;f&&
f.nodeType!==1;)f=f.previousSibling;for(var g=a.nextSibling;g&&g.nodeType!==1;)g=g.nextSibling;if(f){if(g){e=c.document.createElement(e);dojo.style(e,{paddingTop:"0px",paddingBottom:"0px"});for(a.appendChild(e);a.nextSibling;)e.appendChild(a.nextSibling)}dojo.place(a,d,"after")}else dojo.place(a,d,"after"),a.appendChild(b);b&&this._isEmpty(b)&&b.parentNode.removeChild(b);d&&this._isEmpty(d)&&d.parentNode.removeChild(d);dojo.withGlobal(c.window,"selectElementChildren",dijit._editor.selection,[a]);
dojo.withGlobal(c.window,"collapse",dijit._editor.selection,[!0])}else c.document.execCommand("outdent",!1,null)},_isEmpty:function(a){if(a.childNodes){var c=!0,b;for(b=0;b<a.childNodes.length;b++){var e=a.childNodes[b];if(e.nodeType===1){if(this._getTagName(e)!=="p"||dojo.trim(e.innerHTML)){c=!1;break}}else if(this._isTextElement(e)){if((e=dojo.trim(e.nodeValue))&&e!=="&nbsp;"&&e!=="\u00a0"){c=!1;break}}else{c=!1;break}}return c}else return!0},_isIndentableElement:function(a){switch(a){case "p":case "div":case "h1":case "h2":case "h3":case "center":case "table":case "ul":case "ol":return!0;
default:return!1}},_convertIndent:function(a){a+="";var a=a.toLowerCase(),c=a.indexOf("px")>0?"px":a.indexOf("em")>0?"em":"px",a=a.replace(/(px;?|em;?)/gi,"");c==="px"?this.indentUnits==="em"&&(a=Math.ceil(a/12)):this.indentUnits==="px"&&(a*=12);return a},_isLtr:function(){var a=this.editor.document.body;return dojo.withGlobal(this.editor.window,function(){var c=dojo.getComputedStyle(a);return c?c.direction=="ltr":!0})},_isInlineFormat:function(a){switch(a){case "a":case "b":case "strong":case "s":case "strike":case "i":case "u":case "em":case "sup":case "sub":case "span":case "font":case "big":case "cite":case "q":case "img":case "small":return!0;
default:return!1}},_getTagName:function(a){var c="";a&&a.nodeType===1&&(c=a.tagName?a.tagName.toLowerCase():"");return c},_isRootInline:function(a){var c=this.editor;if(this._isTextElement(a)&&a.parentNode===c.editNode)return!0;else if(a.nodeType===1&&this._isInlineFormat(a)&&a.parentNode===c.editNode)return!0;else if(this._isTextElement(a)&&this._isInlineFormat(this._getTagName(a.parentNode))){for(a=a.parentNode;a&&a!==c.editNode&&this._isInlineFormat(this._getTagName(a));)a=a.parentNode;if(a===
c.editNode)return!0}return!1},_isTextElement:function(a){return a&&a.nodeType===3||a.nodeType===4?!0:!1}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="normalizeindentoutdent")a.plugin=new dojox.editor.plugins.NormalizeIndentOutdent({indentBy:"indentBy"in a.args?a.args.indentBy>0?a.args.indentBy:40:40,indentUnits:"indentUnits"in a.args?a.args.indentUnits.toLowerCase()=="em"?"em":"px":"px"})}));