/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.NormalizeStyle"]||(dojo._hasResource["dojox.editor.plugins.NormalizeStyle"]=!0,dojo.provide("dojox.editor.plugins.NormalizeStyle"),dojo.require("dijit._editor.html"),dojo.require("dijit._editor._Plugin"),dojo.declare("dojox.editor.plugins.NormalizeStyle",dijit._editor._Plugin,{mode:"semantic",condenseSpans:!0,setEditor:function(a){this.editor=a;a.customUndo=!0;this.mode==="semantic"?this.editor.contentDomPostFilters.push(dojo.hitch(this,this._convertToSemantic)):
this.mode==="css"&&this.editor.contentDomPostFilters.push(dojo.hitch(this,this._convertToCss));dojo.isIE?(this.editor.contentDomPreFilters.push(dojo.hitch(this,this._convertToSemantic)),this._browserFilter=this._convertToSemantic):dojo.isWebKit?(this.editor.contentDomPreFilters.push(dojo.hitch(this,this._convertToCss)),this._browserFilter=this._convertToCss):(this.editor.contentDomPreFilters.push(dojo.hitch(this,this._convertToSemantic)),this._browserFilter=this._convertToSemantic);if(this.editor._inserthtmlImpl)this.editor._oldInsertHtmlImpl=
this.editor._inserthtmlImpl;this.editor._inserthtmlImpl=dojo.hitch(this,this._inserthtmlImpl)},_convertToSemantic:function(a){if(a){var e=this.editor.window,i=this,k=function(b){if(b.nodeType==1){if(b.id!=="dijitEditorBody"){var d=b.style,a=b.tagName?b.tagName.toLowerCase():"",f;if(d&&a!="table"&&a!="ul"&&a!="ol"){var g=d.fontWeight?d.fontWeight.toLowerCase():"",q=d.fontStyle?d.fontStyle.toLowerCase():"",m=d.textDecoration?d.textDecoration.toLowerCase():"",c=d.fontSize?d.fontSize.toLowerCase():"",
l=d.backgroundColor?d.backgroundColor.toLowerCase():"",d=d.color?d.color.toLowerCase():"",j=function(b,c){if(b){for(;c.firstChild;)b.appendChild(c.firstChild);a=="span"&&!c.style.cssText?(dojo.place(b,c,"before"),c.parentNode.removeChild(c),c=b):c.appendChild(b)}return c};switch(g){case "bold":case "bolder":case "700":case "800":case "900":f=dojo.withGlobal(e,"create",dojo,["b",{}]),b.style.fontWeight=""}b=j(f,b);f=null;if(q=="italic")f=dojo.withGlobal(e,"create",dojo,["i",{}]),b.style.fontStyle=
"";b=j(f,b);f=null;if(m){var n=m.split(" "),o=0;dojo.forEach(n,function(c){switch(c){case "underline":f=dojo.withGlobal(e,"create",dojo,["u",{}]);break;case "line-through":f=dojo.withGlobal(e,"create",dojo,["strike",{}])}o++;if(o==n.length)b.style.textDecoration="";b=j(f,b);f=null})}if(c)c.indexOf("pt")>0?(c=c.substring(0,c.indexOf("pt")),c=parseInt(c),c<5?c="xx-small":c<10?c="x-small":c<15?c="small":c<20?c="medium":c<25?c="large":c<30?c="x-large":c>30&&(c="xx-large")):c.indexOf("px")>0&&(c=c.substring(0,
c.indexOf("px")),c=parseInt(c),c<5?c="xx-small":c<10?c="x-small":c<15?c="small":c<20?c="medium":c<25?c="large":c<30?c="x-large":c>30&&(c="xx-large")),(g={"xx-small":1,"x-small":2,small:3,medium:4,large:5,"x-large":6,"xx-large":7,"-webkit-xxx-large":7}[c])||(g=3),f=dojo.withGlobal(e,"create",dojo,["font",{size:g}]),b.style.fontSize="";b=j(f,b);f=null;if(l&&a!=="font"&&i._isInline(a))l=(new dojo.Color(l)).toHex(),f=dojo.withGlobal(e,"create",dojo,["font",{style:{backgroundColor:l}}]),b.style.backgroundColor=
"";if(d&&a!=="font")d=(new dojo.Color(d)).toHex(),f=dojo.withGlobal(e,"create",dojo,["font",{color:d}]),b.style.color="";b=j(f,b);f=null}}if(b.childNodes){var p=[];dojo.forEach(b.childNodes,function(b){p.push(b)});dojo.forEach(p,k)}}return b};return this._normalizeTags(k(a))}return a},_normalizeTags:function(a){var e=this.editor.window,i=dojo.withGlobal(e,function(){return dojo.query("em,s,strong",a)});i&&i.length&&dojo.forEach(i,function(a){if(a){var b;switch(a.tagName?a.tagName.toLowerCase():""){case "s":b=
"strike";break;case "em":b="i";break;case "strong":b="b"}if(b){for(b=dojo.withGlobal(e,"create",dojo,[b,null,a,"before"]);a.firstChild;)b.appendChild(a.firstChild);a.parentNode.removeChild(a)}}});return a},_convertToCss:function(a){if(a){var e=this.editor.window,i=function(a){if(a.nodeType==1){if(a.id!=="dijitEditorBody"){var b=a.tagName?a.tagName.toLowerCase():"";if(b){var d;switch(b){case "b":case "strong":d=dojo.withGlobal(e,"create",dojo,["span",{style:{fontWeight:"bold"}}]);break;case "i":case "em":d=
dojo.withGlobal(e,"create",dojo,["span",{style:{fontStyle:"italic"}}]);break;case "u":d=dojo.withGlobal(e,"create",dojo,["span",{style:{textDecoration:"underline"}}]);break;case "strike":case "s":d=dojo.withGlobal(e,"create",dojo,["span",{style:{textDecoration:"line-through"}}]);break;case "font":b={};if(dojo.attr(a,"color"))b.color=dojo.attr(a,"color");if(dojo.attr(a,"face"))b.fontFace=dojo.attr(a,"face");if(a.style&&a.style.backgroundColor)b.backgroundColor=a.style.backgroundColor;if(a.style&&a.style.color)b.color=
a.style.color;d={1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large"};if(dojo.attr(a,"size"))b.fontSize=d[dojo.attr(a,"size")];d=dojo.withGlobal(e,"create",dojo,["span",{style:b}])}if(d){for(;a.firstChild;)d.appendChild(a.firstChild);dojo.place(d,a,"before");a.parentNode.removeChild(a);a=d}}}if(a.childNodes){var h=[];dojo.forEach(a.childNodes,function(a){h.push(a)});dojo.forEach(h,i)}}return a},a=i(a);this.condenseSpans&&this._condenseSpans(a)}return a},_condenseSpans:function(a){var e=
function(a){var k=function(a){var b;a&&(b={},a=a.toLowerCase().split(";"),dojo.forEach(a,function(a){if(a){var d=a.split(":"),a=d[0]?dojo.trim(d[0]):"",d=d[1]?dojo.trim(d[1]):"";if(a&&d){var e,f="";for(e=0;e<a.length;e++){var g=a.charAt(e);g=="-"?(e++,g=a.charAt(e),f+=g.toUpperCase()):f+=g}b[f]=d}}}));return b};if(a&&a.nodeType==1&&(a.tagName?a.tagName.toLowerCase():"")==="span"&&a.childNodes&&a.childNodes.length===1)for(var b=a.firstChild;b&&b.nodeType==1&&b.tagName&&b.tagName.toLowerCase()=="span";)if(!dojo.attr(b,
"class")&&!dojo.attr(b,"id")&&b.style){var d=k(a.style.cssText),h=k(b.style.cssText);if(d&&h){var f={},g;for(g in d)if(!d[g]||!h[g]||d[g]==h[g])f[g]=d[g],delete h[g];else{d[g]!=h[g]?g=="textDecoration"?(f[g]=d[g]+" "+h[g],delete h[g]):f=null:f=null;break}if(f){for(g in h)f[g]=h[g];for(dojo.style(a,f);b.firstChild;)a.appendChild(b.firstChild);d=b.nextSibling;b.parentNode.removeChild(b);b=d}else b=b.nextSibling}else b=b.nextSibling}else b=b.nextSibling;a.childNodes&&a.childNodes.length&&dojo.forEach(a.childNodes,
e)};e(a)},_isInline:function(a){switch(a){case "a":case "b":case "strong":case "s":case "strike":case "i":case "u":case "em":case "sup":case "sub":case "span":case "font":case "big":case "cite":case "q":case "img":case "small":return!0;default:return!1}},_inserthtmlImpl:function(a){if(a){var e=this.editor.document.createElement("div");e.innerHTML=a;e=this._browserFilter(e);a=dijit._editor.getChildrenHtml(e);e.innerHTML="";return this.editor._oldInsertHtmlImpl?this.editor._oldInsertHtmlImpl(a):this.editor.execCommand("inserthtml",
a)}return!1}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="normalizestyle")a.plugin=new dojox.editor.plugins.NormalizeStyle({mode:"mode"in a.args?a.args.mode:"semantic",condenseSpans:"condenseSpans"in a.args?a.args.condenseSpans:!0})}));