/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.ResizeTableColumn"]||(dojo._hasResource["dojox.editor.plugins.ResizeTableColumn"]=!0,dojo.provide("dojox.editor.plugins.ResizeTableColumn"),dojo.require("dojox.editor.plugins.TablePlugins"),dojo.declare("dojox.editor.plugins.ResizeTableColumn",dojox.editor.plugins.TablePlugins,{constructor:function(){this.isLtr=this.dir?this.dir=="ltr":dojo._isBodyLtr();this.ruleDiv=dojo.create("div",{style:"top: -10000px; z-index: 10001"},dojo.body(),"last")},setEditor:function(g){function l(a,
d){var b=dojo.withGlobal(g.window,"query",dojo,["> td",a.parentNode]);switch(d){case "first":return b[0]==a;case "last":return b[b.length-1]==a;default:return!1}}function r(a){for(a=a.nextSibling;a;){if(a.tagName&&a.tagName.toLowerCase()=="td")break;a=a.nextSibling}return a}function n(a){for(;(a=a.parentNode)&&a.tagName.toLowerCase()!="table";);return a}function s(a){for(var d=dojo.withGlobal(g.window,"query",dojo,["td",n(a)]),b=d.length,c=0;c<b;c++)if(dojo.coords(d[c]).x==dojo.coords(a).x)return d[c];
return null}function o(a,d){function b(a,b){if(!b)return 0;if(b=="medium")return 1;if(b.slice&&b.slice(-2)=="px")return parseFloat(b);with(a){var c=style.left,d=runtimeStyle.left;runtimeStyle.left=currentStyle.left;try{style.left=b,b=style.pixelLeft}catch(e){b=0}style.left=c;runtimeStyle.left=d}return b}if(dojo.isIE){var c=a.currentStyle,e=b(a,c.borderLeftWidth),f=b(a,c.borderRightWidth),g=b(a,c.paddingLeft),c=b(a,c.paddingRight);a.style.width=d-e-f-g-c}else dojo.marginBox(a,{w:d})}var i=this.ruleDiv;
this.editor=g;this.editor.customUndo=!0;this.onEditorLoaded();g.onLoadDeferred.addCallback(dojo.hitch(this,function(){this.connect(this.editor.editNode,"onmousemove",function(a){var d=dojo.coords(g.iframe,!0),b=d.x,c=a.clientX;if(this.isDragging){var e=this.activeCell,a=dojo.coords(e),d=a.x,a=a.w,f=r(e),j,h,k=dojo.coords(n(e).parentNode),e=k.x,k=k.w;if(f)j=dojo.coords(f),h=j.x,j=j.w;(this.isLtr&&(i.headerColumn&&f&&e<c&&c<d+a||!f&&d<c&&c<e+k||f&&d<c&&c<h+j)||!this.isLtr&&(i.headerColumn&&f&&e>c&&
c>d||!f&&d+a>c&&c>e||f&&d+a>c&&c>h))&&dojo.style(i,{left:b+c+"px"})}else if(h=a.target,h.tagName&&h.tagName.toLowerCase()=="td"){j=dojo.coords(h);a=j.x;f=j.w;b=b+j.x-2;if(this.isLtr){if(i.headerColumn=!0,!l(h,"first")||c>a+f/2)b+=f,i.headerColumn=!1}else if(i.headerColumn=!1,l(h,"first")&&c>a+f/2)b+=f,i.headerColumn=!0;dojo.style(i,{position:"absolute",cursor:"col-resize",display:"block",width:"4px",backgroundColor:"transparent",top:d.y+j.y+"px",left:b+"px",height:j.h+"px"});this.activeCell=h}else dojo.style(i,
{display:"none",top:"-10000px"})});this.connect(i,"onmousedown",function(a){var d=dojo.coords(g.iframe,!0),b=dojo.coords(n(this.activeCell));this.isDragging=!0;dojo.style(g.editNode,{cursor:"col-resize"});dojo.style(i,{width:"1px",left:a.clientX+"px",top:d.y+b.y+"px",height:b.h+"px",backgroundColor:"#777"})});this.connect(i,"onmouseup",function(a){var d=this.activeCell,b=dojo.coords(d),c=b.w,e=b.x,b=r(d),f,j,h=dojo.coords(g.iframe).x,k=n(d),u=dojo.coords(k),m=k.getAttribute("cellspacing"),a=a.clientX,
t=s(d),p,q;if(!m||(m=parseInt(m,10))<0)m=2;if(b)f=dojo.coords(b),j=f.x,f=f.w,p=s(b);this.isLtr?i.headerColumn?e=h+e+c-a:(e=a-h-e,b&&(q=h+j+f-a-m)):i.headerColumn?e=a-h-e:(e=h+e+c-a,b&&(q=a-h-j-m));this.isDragging=!1;o(t,e);b&&(i.headerColumn||o(p,q));(i.headerColumn&&l(d,"first")||l(d,"last"))&&dojo.marginBox(k,{w:u.w+e-c});o(t,dojo.coords(d).w);b&&o(p,dojo.coords(b).w);dojo.style(g.editNode,{cursor:"auto"});dojo.style(i,{display:"none",top:"-10000px"});this.activeCell=null})}))}}),dojo.subscribe(dijit._scopeName+
".Editor.getPlugin",null,function(g){if(!g.plugin&&g.args&&g.args.command){var l=g.args.command.charAt(0).toLowerCase()+g.args.command.substring(1,g.args.command.length);if(l=="resizeTableColumn")g.plugin=new dojox.editor.plugins.ResizeTableColumn({commandName:l})}}));