/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.editor.plugins.ShowBlockNodes"]||(dojo._hasResource["dojox.editor.plugins.ShowBlockNodes"]=!0,dojo.provide("dojox.editor.plugins.ShowBlockNodes"),dojo.require("dijit._editor._Plugin"),dojo.require("dijit.form.Button"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojox.editor.plugins","ShowBlockNodes",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dojox.editor.plugins.ShowBlockNodes",dijit._editor._Plugin,
{useDefaultCommand:!1,iconClassPrefix:"dijitAdditionalEditorIcon",_styled:!1,_initButton:function(){var a=dojo.i18n.getLocalization("dojox.editor.plugins","ShowBlockNodes");this.button=new dijit.form.ToggleButton({label:a.showBlockNodes,showLabel:!1,iconClass:this.iconClassPrefix+" "+this.iconClassPrefix+"ShowBlockNodes",tabIndex:"-1",onChange:dojo.hitch(this,"_showBlocks")});this.editor.addKeyHandler(dojo.keys.F9,!0,!0,dojo.hitch(this,this.toggle))},updateState:function(){this.button.set("disabled",
this.get("disabled"))},setEditor:function(a){this.editor=a;this._initButton()},toggle:function(){this.button.set("checked",!this.button.get("checked"))},_showBlocks:function(a){var b=this.editor.document;if(!this._styled)try{this._styled=!0;var d="";dojo.forEach(["div","p","ul","ol","table","h1","h2","h3","h4","h5","h6","pre","dir","center","blockquote","form","fieldset","address","object","pre","hr","ins","noscript","li","map","button","dd","dt"],function(a){d+="@media screen {\n\t.editorShowBlocks {TAG} {\n\t\tbackground-image: url({MODURL}/images/blockelems/{TAG}.gif);\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: top left;\n\t\tborder-width: 1px;\n\t\tborder-style: dashed;\n\t\tborder-color: #D0D0D0;\n\t\tpadding-top: 15px;\n\t\tpadding-left: 15px;\n\t}\n}\n".replace(/\{TAG\}/gi,
a)});var c=dojo.moduleUrl(dojox._scopeName,"editor/plugins/resources").toString();if(!c.match(/^https?:\/\//i)&&!c.match(/^file:\/\//i)){var e;e=c.charAt(0)==="/"?dojo.doc.location.protocol+"//"+dojo.doc.location.host:this._calcBaseUrl(dojo.global.location.href);e[e.length-1]!=="/"&&c.charAt(0)!=="/"&&(e+="/");c=e+c}d=d.replace(/\{MODURL\}/gi,c);if(dojo.isIE)b.createStyleSheet("").cssText=d;else{var f=b.createElement("style");f.appendChild(b.createTextNode(d));b.getElementsByTagName("head")[0].appendChild(f)}}catch(g){console.warn(g)}a?
dojo.addClass(this.editor.editNode,"editorShowBlocks"):dojo.removeClass(this.editor.editNode,"editorShowBlocks")},_calcBaseUrl:function(a){var b=null;a!==null&&(b=a.indexOf("?"),b!=-1&&(a=a.substring(0,b)),b=a.lastIndexOf("/"),b=b>0&&b<a.length?a.substring(0,b):a);return b}}),dojo.subscribe(dijit._scopeName+".Editor.getPlugin",null,function(a){if(!a.plugin&&a.args.name.toLowerCase()==="showblocknodes")a.plugin=new dojox.editor.plugins.ShowBlockNodes}));