/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


define(["require","dojo/_base/_loader/bootstrap"],function(h,c){var i=["_moduleHasPrefix","_loadPath","_loadUri","_loadUriAndCheck","loaded","_callLoaded","_getModuleSymbols","_loadModule","require","provide","platformRequire","requireIf","requireAfterIf","registerModulePath"],j,k;for(j=0;j<i.length;)k=i[j++],c[k]=function(a){return function(){console.warn("dojo."+a+" not available when using an AMD loader.")}}(k);var l=function(a){var b=[],c;for(c=0;c<a.length;)b.push(a[c++]);return b},m=function(a,
b){return b?typeof b=="string"?function(){a[b]()}:function(){b.call(a)}:a};c.ready=c.addOnLoad=function(a,b){h.ready(b?m(a,b):a)};c.addOnLoad(function(){c.postLoad=c.config.afterOnLoad=!0});if(i=c.config.addOnLoad)c.addOnLoad[i instanceof Array?"apply":"call"](c,i);var g=c._loaders=[],n=function(){var a=g.slice(0);for(Array.prototype.splice.apply(g,[0,g.length]);a.length;)a.shift().call()};g.unshift=function(){Array.prototype.unshift.apply(g,l(arguments));h.ready(n)};g.splice=function(){Array.prototype.splice.apply(g,
l(arguments));h.ready(n)};var o=c._unloaders=[];c.unloaded=function(){for(;o.length;)o.pop().call()};c._onto=function(a,b,c){a.push(c?m(b,c):b)};c._modulesLoaded=function(){};c.loadInit=function(a){a()};c.getL10nName=function(a,b,e){e=e?e.toLowerCase():c.locale;a="i18n!"+a.replace(/\./g,"/");return/root/i.test(e)?a+"/nls/"+b:a+"/nls/"+e+"/"+b};c.requireLocalization=function(a,b,e){h.vendor!="altoviso.com"&&(e=!e||e.toLowerCase()===c.locale?"root":e);return h(c.getL10nName(a,b,e))};c.i18n={getLocalization:c.requireLocalization,
normalizeLocale:function(a){a=a?a.toLowerCase():c.locale;a=="root"&&(a="ROOT");return a}};var p=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,q=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/;c._Url=function(){for(var a=arguments,b=[a[0]],e=1;e<a.length;e++)if(a[e]){var d=new c._Url(a[e]+""),b=new c._Url(b[0]+"");if(d.path==""&&!d.scheme&&!d.authority&&!d.query){if(d.fragment!=null)b.fragment=d.fragment;d=b}else if(!d.scheme&&(d.scheme=b.scheme,!d.authority&&(d.authority=
b.authority,d.path.charAt(0)!="/"))){for(var b=(b.path.substring(0,b.path.lastIndexOf("/")+1)+d.path).split("/"),f=0;f<b.length;f++)b[f]=="."?f==b.length-1?b[f]="":(b.splice(f,1),f--):f>0&&!(f==1&&b[0]=="")&&b[f]==".."&&b[f-1]!=".."&&(f==b.length-1?(b.splice(f,1),b[f-1]=""):(b.splice(f-1,2),f-=2));d.path=b.join("/")}b=[];d.scheme&&b.push(d.scheme,":");d.authority&&b.push("//",d.authority);b.push(d.path);d.query&&b.push("?",d.query);d.fragment&&b.push("#",d.fragment)}this.uri=b.join("");a=this.uri.match(p);
this.scheme=a[2]||(a[1]?"":null);this.authority=a[4]||(a[3]?"":null);this.path=a[5];this.query=a[7]||(a[6]?"":null);this.fragment=a[9]||(a[8]?"":null);if(this.authority!=null)a=this.authority.match(q),this.user=a[3]||null,this.password=a[4]||null,this.host=a[6]||a[7],this.port=a[9]||null};c._Url.prototype.toString=function(){return this.uri};c.moduleUrl=function(a,b){if(!a)return null;var a=a.replace(/\./g,"/")+(b?"/"+b:""),e="",d=a.match(/(.+)(\.[^\/]*)$/);d&&(a=d[1],e=d[2]);return new c._Url(h.nameToUrl(a,
e))};return c});