/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.form.FileUploader"]||(dojo._hasResource["dojox.form.FileUploader"]=!0,dojo.provide("dojox.form.FileUploader"),dojo.require("dojox.embed.Flash"),dojo.require("dojo.io.iframe"),dojo.require("dojox.html.styles"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dojox.embed.flashVars"),dojo.require("dijit._Contained"),console.warn("DEPRECATED: dojox.form.FileUploader is no longer supported and will be removed in 2.0. Suggested that you use dojox.form.Uploader instead."),
dojo.declare("dojox.form.FileUploader",[dijit._Widget,dijit._Templated,dijit._Contained],{swfPath:dojo.config.uploaderPath||dojo.moduleUrl("dojox.form","resources/fileuploader.swf"),templateString:'<div><div dojoAttachPoint="progNode"><div dojoAttachPoint="progTextNode"></div></div><div dojoAttachPoint="insideNode" class="uploaderInsideNode"></div></div>',uploadUrl:"",isDebug:!1,devMode:!1,baseClass:"dojoxUploaderNorm",hoverClass:"dojoxUploaderHover",activeClass:"dojoxUploaderActive",disabledClass:"dojoxUploaderDisabled",
force:"",uploaderType:"",flashObject:null,flashMovie:null,insideNode:null,deferredUploading:1,fileListId:"",uploadOnChange:!1,selectMultipleFiles:!0,htmlFieldName:"uploadedfile",flashFieldName:"flashUploadFiles",fileMask:null,minFlashVersion:9,tabIndex:-1,showProgress:!1,progressMessage:"Loading",progressBackgroundUrl:dojo.moduleUrl("dijit","themes/tundra/images/buttonActive.png"),progressBackgroundColor:"#ededed",progressWidgetId:"",skipServerCheck:!1,serverTimeout:5E3,log:function(){this.isDebug&&
console.log(Array.prototype.slice.call(arguments).join(" "))},constructor:function(){this._subs=[]},postMixInProperties:function(){this.fileList=[];this._cons=[];this.fileMask=this.fileMask||[];this.fileInputs=[];this.fileCount=0;this._disabled=this.flashReady=!1;this.force=this.force.toLowerCase();this.uploaderType=(dojox.embed.Flash.available>=this.minFlashVersion||this.force=="flash")&&this.force!="html"?"flash":"html";this.deferredUploading=this.deferredUploading===!0?1:this.deferredUploading;
this._refNode=this.srcNodeRef;this.getButtonStyle()},startup:function(){},postCreate:function(){this.inherited(arguments);this.setButtonStyle();var a;this.uploaderType=="flash"?a="createFlashUploader":(this.uploaderType="html",a="createHtmlUploader");this[a]();this.fileListId&&this.connect(dojo.byId(this.fileListId),"click",function(a){a=a.target.parentNode.parentNode.parentNode;a.id&&a.id.indexOf("file_")>-1&&this.removeFile(a.id.split("file_")[1])});dojo.addOnUnload(this,this.destroy)},getHiddenWidget:function(){for(var a=
this.domNode.parentNode;a;){var b=a.getAttribute&&a.getAttribute("widgetId");if(b&&dijit.byId(b).onShow)return dijit.byId(b);a=a.parentNode}return null},getHiddenNode:function(a){if(!a)return null;for(var b=null,a=a.parentNode;a&&a.tagName.toLowerCase()!="body";){if(dojo.style(a,"display")=="none"){b=a;break}a=a.parentNode}return b},getButtonStyle:function(){var a=this.srcNodeRef;(this._hiddenNode=this.getHiddenNode(a))&&dojo.style(this._hiddenNode,"display","block");if(!a&&this.button&&this.button.domNode){var b=
!0,a=this.button.domNode.className+" dijitButtonNode",c=this.getText(dojo.query(".dijitButtonText",this.button.domNode)[0]);this.srcNodeRef=a=dojo.place('<button id="'+this.button.id+'" class="'+a+'">'+c+"</button>",this.button.domNode,"after");this.button.destroy();this.baseClass="dijitButton";this.hoverClass="dijitButtonHover";this.pressClass="dijitButtonActive";this.disabledClass="dijitButtonDisabled"}else if(!this.srcNodeRef&&this.button)a=this.button;dojo.attr(a,"class")&&(this.baseClass+=" "+
dojo.attr(a,"class"));dojo.attr(a,"class",this.baseClass);this.norm=this.getStyle(a);this.width=this.norm.w;this.height=this.norm.h;if(this.uploaderType=="flash")this.over=this.getTempNodeStyle(a,this.baseClass+" "+this.hoverClass,b),this.down=this.getTempNodeStyle(a,this.baseClass+" "+this.activeClass,b),this.dsbl=this.getTempNodeStyle(a,this.baseClass+" "+this.disabledClass,b),this.fhtml={cn:this.getText(a),nr:this.norm,ov:this.over,dn:this.down,ds:this.dsbl};else if(this.fhtml={cn:this.getText(a),
nr:this.norm},this.norm.va=="middle")this.norm.lh=this.norm.h;this.devMode&&(this.log("classes - base:",this.baseClass," hover:",this.hoverClass,"active:",this.activeClass),this.log("fhtml:",this.fhtml),this.log("norm:",this.norm),this.log("over:",this.over),this.log("down:",this.down))},setButtonStyle:function(){dojo.style(this.domNode,{width:this.fhtml.nr.w+"px",height:this.fhtml.nr.h+"px",padding:"0px",lineHeight:"normal",position:"relative"});this.uploaderType=="html"&&this.norm.va=="middle"&&
dojo.style(this.domNode,"lineHeight",this.norm.lh+"px");this.showProgress?(this.progTextNode.innerHTML=this.progressMessage,dojo.style(this.progTextNode,{width:this.fhtml.nr.w+"px",height:this.fhtml.nr.h+0+"px",padding:"0px",margin:"0px",left:"0px",lineHeight:this.fhtml.nr.h+0+"px",position:"absolute"}),dojo.style(this.progNode,{width:this.fhtml.nr.w+"px",height:this.fhtml.nr.h+0+"px",padding:"0px",margin:"0px",left:"0px",position:"absolute",display:"none",backgroundImage:"url("+this.progressBackgroundUrl+
")",backgroundPosition:"bottom",backgroundRepeat:"repeat-x",backgroundColor:this.progressBackgroundColor})):dojo.destroy(this.progNode);dojo.style(this.insideNode,{position:"absolute",top:"0px",left:"0px",display:""});dojo.addClass(this.domNode,this.srcNodeRef.className);this.fhtml.nr.d.indexOf("inline")>-1&&dojo.addClass(this.domNode,"dijitInline");try{this.insideNode.innerHTML=this.fhtml.cn}catch(a){if(this.uploaderType=="flash"){this.insideNode=this.insideNode.parentNode.removeChild(this.insideNode);
dojo.body().appendChild(this.insideNode);this.insideNode.innerHTML=this.fhtml.cn;var b=dojo.connect(this,"onReady",this,function(){dojo.disconnect(b);this.insideNode=this.insideNode.parentNode.removeChild(this.insideNode);this.domNode.appendChild(this.insideNode)})}else this.insideNode.appendChild(document.createTextNode(this.fhtml.cn))}this._hiddenNode&&dojo.style(this._hiddenNode,"display","none")},onChange:function(){},onProgress:function(){},onComplete:function(){},onCancel:function(){},onError:function(){},
onReady:function(){},onLoad:function(){},submit:function(a){this.upload(a?dojo.formToObject(a):null);return!1},upload:function(a){if(!this.fileList.length)return!1;if(!this.uploadUrl)return console.warn("uploadUrl not provided. Aborting."),!1;this.showProgress||this.set("disabled",!0);if(this.progressWidgetId){var b=dijit.byId(this.progressWidgetId).domNode;if(dojo.style(b,"display")=="none")this.restoreProgDisplay="none",dojo.style(b,"display","block");if(dojo.style(b,"visibility")=="hidden")this.restoreProgDisplay=
"hidden",dojo.style(b,"visibility","visible")}if(a&&!a.target)this.postData=a;this.log("upload type:",this.uploaderType," - postData:",this.postData);for(a=0;a<this.fileList.length;a++)b=this.fileList[a],b.bytesLoaded=0,b.bytesTotal=b.size||1E5,b.percent=0;this.uploaderType=="flash"?this.uploadFlash():this.uploadHTML();return!1},removeFile:function(a,b){var c;for(c=0;c<this.fileList.length;c++)if(this.fileList[c].name==a){b||this.fileList.splice(c,1);break}this.uploaderType=="flash"?this.flashMovie.removeFile(a):
b||(dojo.destroy(this.fileInputs[c]),this.fileInputs.splice(c,1),this._renumberInputs());this.fileListId&&dojo.destroy("file_"+a)},destroy:function(){this.uploaderType=="flash"&&!this.flashMovie?this._cons.push(dojo.connect(this,"onLoad",this,"destroy")):(dojo.forEach(this._subs,dojo.unsubscribe,dojo),dojo.forEach(this._cons,dojo.disconnect,dojo),this.scrollConnect&&dojo.disconnect(this.scrollConnect),this.uploaderType=="flash"?(this.flashObject.destroy(),delete this.flashObject):(dojo.destroy(this._fileInput),
dojo.destroy(this._formNode)),this.inherited(arguments))},_displayProgress:function(a){a===!0?(this.uploaderType=="flash"?dojo.style(this.insideNode,"top","-2500px"):dojo.style(this.insideNode,"display","none"),dojo.style(this.progNode,"display","")):a===!1?(dojo.style(this.insideNode,{display:"",left:"0px"}),dojo.style(this.progNode,"display","none")):dojo.style(this.progNode,"width",a*this.fhtml.nr.w+"px")},_animateProgress:function(){this._displayProgress(!0);var a=!1,b=dojo.connect(this,"_complete",
function(){dojo.disconnect(b);a=!0}),c=0,d=setInterval(dojo.hitch(this,function(){c+=5;c>this.fhtml.nr.w&&(c=0,a=!0);this._displayProgress(c/this.fhtml.nr.w);a&&(clearInterval(d),setTimeout(dojo.hitch(this,function(){this._displayProgress(!1)}),500))}),50)},_error:function(a){typeof a=="string"&&(a=Error(a));this.onError(a)},_addToFileList:function(){if(this.fileListId){var a="";dojo.forEach(this.fileList,function(b){a+='<table id="file_'+b.name+'" class="fileToUpload"><tr><td class="fileToUploadClose"></td><td class="fileToUploadName">'+
b.name+'</td><td class="fileToUploadSize">'+(b.size?Math.ceil(b.size*0.0010)+"kb":"")+"</td></tr></table>"},this);dojo.byId(this.fileListId).innerHTML=a}},_change:function(a){dojo.isIE&&dojo.forEach(a,function(a){a.name=a.name.split("\\")[a.name.split("\\").length-1]});this.selectMultipleFiles?this.fileList=this.fileList.concat(a):(this.fileList[0]&&this.removeFile(this.fileList[0].name,!0),this.fileList=a);this._addToFileList();this.onChange(a);this.uploadOnChange?(this.uploaderType=="html"&&this._buildFileInput(),
this.upload()):this.uploaderType=="html"&&this.selectMultipleFiles&&(this._buildFileInput(),this._connectInput())},_complete:function(a){a=dojo.isArray(a)?a:[a];dojo.forEach(a,function(a){a.ERROR&&this._error(a.ERROR)},this);dojo.forEach(this.fileList,function(a){a.bytesLoaded=1;a.bytesTotal=1;a.percent=100;this._progress(a)},this);dojo.forEach(this.fileList,function(a){this.removeFile(a.name,!0)},this);this.onComplete(a);this.fileList=[];this._resetHTML();this.set("disabled",!1);this.restoreProgDisplay&&
setTimeout(dojo.hitch(this,function(){dojo.style(dijit.byId(this.progressWidgetId).domNode,this.restoreProgDisplay=="none"?"display":"visibility",this.restoreProgDisplay)}),500)},_progress:function(a){for(var b=0,c=0,d=0;d<this.fileList.length;d++){var e=this.fileList[d];if(e.name==a.name)e.bytesLoaded=a.bytesLoaded,e.bytesTotal=a.bytesTotal,e.percent=Math.ceil(e.bytesLoaded/e.bytesTotal*100),this.log(e.name,"percent:",e.percent);c+=Math.ceil(0.0010*e.bytesLoaded);b+=Math.ceil(0.0010*e.bytesTotal)}a=
Math.ceil(c/b*100);this.progressWidgetId&&dijit.byId(this.progressWidgetId).update({progress:a+"%"});this.showProgress&&this._displayProgress(a*0.01);this.onProgress(this.fileList)},_getDisabledAttr:function(){return this._disabled},_setDisabledAttr:function(a){if(this._disabled!=a){if(this.uploaderType=="flash"){if(!this.flashReady){var b=dojo.connect(this,"onLoad",this,function(){dojo.disconnect(b);this._setDisabledAttr(a)});return}this._disabled=a;this.flashMovie.doDisable(a)}else this._disabled=
a,dojo.style(this._fileInput,"display",this._disabled?"none":"");dojo.toggleClass(this.domNode,this.disabledClass,a)}},_onFlashBlur:function(){this.flashMovie.blur();if(!this.nextFocusObject&&this.tabIndex)for(var a=dojo.query("[tabIndex]"),b=0;b<a.length;b++)if(a[b].tabIndex>=Number(this.tabIndex)+1){this.nextFocusObject=a[b];break}this.nextFocusObject.focus()},_disconnect:function(){dojo.forEach(this._cons,dojo.disconnect,dojo)},uploadHTML:function(){this.selectMultipleFiles&&dojo.destroy(this._fileInput);
this._setHtmlPostData();this.showProgress&&this._animateProgress();dojo.io.iframe.send({url:this.uploadUrl.toString(),form:this._formNode,handleAs:"json",error:dojo.hitch(this,function(a){this._error("HTML Upload Error:"+a.message)}),load:dojo.hitch(this,function(a){this._complete(a)})})},createHtmlUploader:function(){this._buildForm();this._setFormStyle();this._buildFileInput();this._connectInput();this._styleContent();dojo.style(this.insideNode,"visibility","visible");this.onReady()},_connectInput:function(){this._disconnect();
this._cons.push(dojo.connect(this._fileInput,"mouseover",this,function(a){dojo.addClass(this.domNode,this.hoverClass);this.onMouseOver(a)}));this._cons.push(dojo.connect(this._fileInput,"mouseout",this,function(a){setTimeout(dojo.hitch(this,function(){dojo.removeClass(this.domNode,this.activeClass);dojo.removeClass(this.domNode,this.hoverClass);this.onMouseOut(a);this._checkHtmlCancel("off")}),0)}));this._cons.push(dojo.connect(this._fileInput,"mousedown",this,function(a){dojo.addClass(this.domNode,
this.activeClass);dojo.removeClass(this.domNode,this.hoverClass);this.onMouseDown(a)}));this._cons.push(dojo.connect(this._fileInput,"mouseup",this,function(a){dojo.removeClass(this.domNode,this.activeClass);this.onMouseUp(a);this.onClick(a);this._checkHtmlCancel("up")}));this._cons.push(dojo.connect(this._fileInput,"change",this,function(){this._checkHtmlCancel("change");this._change([{name:this._fileInput.value,type:"",size:0}])}));this.tabIndex>=0&&dojo.attr(this.domNode,"tabIndex",this.tabIndex)},
_checkHtmlCancel:function(a){if(a=="change")this.dialogIsOpen=!1;if(a=="up")this.dialogIsOpen=!0;if(a=="off"){if(this.dialogIsOpen)this.onCancel();this.dialogIsOpen=!1}},_styleContent:function(){var a=this.fhtml.nr;dojo.style(this.insideNode,{width:a.w+"px",height:a.va=="middle"?a.h+"px":"auto",textAlign:a.ta,paddingTop:a.p[0]+"px",paddingRight:a.p[1]+"px",paddingBottom:a.p[2]+"px",paddingLeft:a.p[3]+"px"});try{dojo.style(this.insideNode,"lineHeight","inherit")}catch(b){}},_resetHTML:function(){if(this.uploaderType==
"html"&&this._formNode)this.fileInputs=[],dojo.query("*",this._formNode).forEach(function(a){dojo.destroy(a)}),this.fileCount=0,this._buildFileInput(),this._connectInput()},_buildForm:function(){if(!this._formNode)dojo.isIE<9||dojo.isIE&&dojo.isQuirks?(this._formNode=document.createElement('<form enctype="multipart/form-data" method="post">'),this._formNode.encoding="multipart/form-data",this._formNode.id=dijit.getUniqueId("FileUploaderForm"),this.domNode.appendChild(this._formNode)):this._formNode=
dojo.create("form",{enctype:"multipart/form-data",method:"post",id:dijit.getUniqueId("FileUploaderForm")},this.domNode)},_buildFileInput:function(){this._fileInput&&(this._disconnect(),this._fileInput.id+=this.fileCount,dojo.style(this._fileInput,"display","none"));this._fileInput=document.createElement("input");this.fileInputs.push(this._fileInput);var a=this.htmlFieldName;this.selectMultipleFiles&&(a+=this.fileCount,this.fileCount++);dojo.attr(this._fileInput,{id:this.id,name:a,type:"file"});dojo.addClass(this._fileInput,
"dijitFileInputReal");this._formNode.appendChild(this._fileInput);a=dojo.marginBox(this._fileInput);dojo.style(this._fileInput,{position:"relative",left:this.fhtml.nr.w-a.w+"px",opacity:0})},_renumberInputs:function(){if(this.selectMultipleFiles){var a;this.fileCount=0;dojo.forEach(this.fileInputs,function(b){a=this.htmlFieldName+this.fileCount;this.fileCount++;dojo.attr(b,"name",a)},this)}},_setFormStyle:function(){dojox.html.insertCssRule("#"+this._formNode.id+" input","font-size:"+Math.max(2,Math.max(Math.ceil(this.fhtml.nr.w/
60),Math.ceil(this.fhtml.nr.h/15)))+"em");dojo.style(this.domNode,{overflow:"hidden",position:"relative"});dojo.style(this.insideNode,"position","absolute")},_setHtmlPostData:function(){if(this.postData)for(var a in this.postData)dojo.create("input",{type:"hidden",name:a,value:this.postData[a]},this._formNode)},uploadFlash:function(){try{if(this.showProgress){this._displayProgress(!0);var a=dojo.connect(this,"_complete",this,function(){dojo.disconnect(a);this._displayProgress(!1)})}var b={},c;for(c in this.postData)b[c]=
this.postData[c];this.flashMovie.doUpload(b)}catch(d){this._error("FileUploader - Sorry, the SWF failed to initialize."+d)}},createFlashUploader:function(){if(this.uploadUrl=this.uploadUrl.toString())if(this.uploadUrl.toLowerCase().indexOf("http")<0&&this.uploadUrl.indexOf("/")!=0){var a=window.location.href.split("/");a.pop();a=a.join("/")+"/";this.uploadUrl=a+this.uploadUrl;this.log("SWF Fixed - Relative loc:",a," abs loc:",this.uploadUrl)}else this.log("SWF URL unmodified:",this.uploadUrl);else console.warn("Warning: no uploadUrl provided.");
a={expressInstall:!0,path:this.swfPath.uri||this.swfPath,width:this.fhtml.nr.w,height:this.fhtml.nr.h,allowScriptAccess:"always",allowNetworking:"all",vars:{uploadDataFieldName:this.flashFieldName,uploadUrl:this.uploadUrl,uploadOnSelect:this.uploadOnChange,deferredUploading:this.deferredUploading||0,selectMultipleFiles:this.selectMultipleFiles,id:this.id,isDebug:this.isDebug,devMode:this.devMode,flashButton:dojox.embed.flashVars.serialize("fh",this.fhtml),fileMask:dojox.embed.flashVars.serialize("fm",
this.fileMask),noReturnCheck:this.skipServerCheck,serverTimeout:this.serverTimeout},params:{scale:"noscale",wmode:"opaque",allowScriptAccess:"always",allowNetworking:"all"}};this.flashObject=new dojox.embed.Flash(a,this.insideNode);this.flashObject.onError=dojo.hitch(function(a){this._error("Flash Error: "+a)});this.flashObject.onReady=dojo.hitch(this,function(){dojo.style(this.insideNode,"visibility","visible");this.log("FileUploader flash object ready");this.onReady(this)});this.flashObject.onLoad=
dojo.hitch(this,function(a){this.flashMovie=a;this.flashReady=!0;this.onLoad(this)});this._connectFlash()},_connectFlash:function(){this._doSub("/filesSelected","_change");this._doSub("/filesUploaded","_complete");this._doSub("/filesProgress","_progress");this._doSub("/filesError","_error");this._doSub("/filesCanceled","onCancel");this._doSub("/stageBlur","_onFlashBlur");this._doSub("/up","onMouseUp");this._doSub("/down","onMouseDown");this._doSub("/over","onMouseOver");this._doSub("/out","onMouseOut");
this.connect(this.domNode,"focus",function(){this.flashMovie.focus();this.flashMovie.doFocus()});this.tabIndex>=0&&dojo.attr(this.domNode,"tabIndex",this.tabIndex)},_doSub:function(a,b){this._subs.push(dojo.subscribe(this.id+a,this,b))},urlencode:function(a){return!a||a=="none"?!1:a.replace(/:/g,"||").replace(/\./g,"^^").replace("url(","").replace(")","").replace(/'/g,"").replace(/"/g,"")},isButton:function(a){a=a.tagName.toLowerCase();return a=="button"||a=="input"},getTextStyle:function(a){var b=
{};b.ff=dojo.style(a,"fontFamily");if(b.ff){b.ff=b.ff.replace(", ",",");b.ff=b.ff.replace(/\"|\'/g,"");b.ff=b.ff=="sans-serif"?"Arial":b.ff;b.fw=dojo.style(a,"fontWeight");b.fi=dojo.style(a,"fontStyle");b.fs=parseInt(dojo.style(a,"fontSize"),10);if(dojo.style(a,"fontSize").indexOf("%")>-1)for(var c=a;c.tagName;){if(dojo.style(c,"fontSize").indexOf("%")==-1){b.fs=parseInt(dojo.style(c,"fontSize"),10);break}if(c.tagName.toLowerCase()=="body")b.fs=0.16*parseInt(dojo.style(c,"fontSize"),10);c=c.parentNode}b.fc=
(new dojo.Color(dojo.style(a,"color"))).toHex();b.fc=parseInt(b.fc.substring(1,Infinity),16)}b.lh=dojo.style(a,"lineHeight");b.ta=dojo.style(a,"textAlign");b.ta=b.ta=="start"||!b.ta?"left":b.ta;b.va=this.isButton(a)?"middle":b.lh==b.h?"middle":dojo.style(a,"verticalAlign");return b},getText:function(a){a=dojo.trim(a.innerHTML);a.indexOf("<")>-1&&(a=escape(a));return a},getStyle:function(a){var b={},c=dojo.contentBox(a),d=dojo._getPadExtents(a);b.p=[d.t,d.w-d.l,d.h-d.t,d.l];b.w=c.w+d.w;b.h=c.h+d.h;
b.d=dojo.style(a,"display");c=new dojo.Color(dojo.style(a,"backgroundColor"));b.bc=c.a==0?"#ffffff":c.toHex();b.bc=parseInt(b.bc.substring(1,Infinity),16);if(c=this.urlencode(dojo.style(a,"backgroundImage")))if(b.bi={url:c,rp:dojo.style(a,"backgroundRepeat"),pos:escape(dojo.style(a,"backgroundPosition"))},!b.bi.pos)c=dojo.style(a,"backgroundPositionX"),d=dojo.style(a,"backgroundPositionY"),b.bi.pos=escape((c=="left"?"0%":c=="right"?"100%":c)+" "+(d=="top"?"0%":d=="bottom"?"100%":d));return dojo.mixin(b,
this.getTextStyle(a))},getTempNodeStyle:function(a,b,c){if(c){var c=dojo.place("<"+a.tagName+"><span>"+a.innerHTML+"</span></"+a.tagName+">",a.parentNode),d=c.firstChild;dojo.addClass(d,a.className);dojo.addClass(c,b);a=this.getStyle(d)}else c=dojo.place("<"+a.tagName+">"+a.innerHTML+"</"+a.tagName+">",a.parentNode),dojo.addClass(c,a.className),dojo.addClass(c,b),c.id=a.id,a=this.getStyle(c);dojo.destroy(c);return a}}));