/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.form.ListInput"]||(dojo._hasResource["dojox.form.ListInput"]=!0,dojo.experimental("dojox.form.ListInput"),dojo.provide("dojox.form.ListInput"),dojo.require("dijit.form._FormWidget"),dojo.require("dijit.form.ValidationTextBox"),dojo.require("dijit.InlineEditBox"),dojo.requireLocalization("dijit","common",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dojox.form.ListInput",[dijit.form._FormValueWidget],
{constructor:function(){this._items=[];if(!dojo.isArray(this.delimiter))this.delimiter=[this.delimiter];this.regExp="^"+this.regExp+("("+this.delimiter.join("|")+")?")+"$"},inputClass:"dojox.form._ListInputInputBox",inputHandler:"onChange",inputProperties:{minWidth:50},submitOnlyValidValue:!0,useOnBlur:!0,readOnlyInput:!1,maxItems:null,showCloseButtonWhenValid:!0,showCloseButtonWhenInvalid:!0,regExp:".*",delimiter:",",constraints:{},baseClass:"dojoxListInput",type:"select",value:"",templateString:'<div dojoAttachPoint="focusNode" class="dijit dijitReset dijitLeft dojoxListInput"><select dojoAttachpoint="_selectNode" multiple="multiple" class="dijitHidden" ${!nameAttrSetting}></select><ul dojoAttachPoint="_listInput"><li dojoAttachEvent="onclick: _onClick" class="dijitInputField dojoxListInputNode dijitHidden" dojoAttachPoint="_inputNode"></li></ul></div>',
useAnim:!0,duration:500,easingIn:null,easingOut:null,readOnlyItem:!1,useArrowForEdit:!0,_items:null,_lastAddedItem:null,_currentItem:null,_input:null,_count:0,postCreate:function(){this.inherited(arguments);this._createInputBox()},_setReadOnlyInputAttr:function(a){if(!this._started)return this._createInputBox();this.readOnlyInput=a;this._createInputBox()},_setReadOnlyItemAttr:function(a){if(this._started)for(var b in this._items)this._items[b].set("readOnlyItem",a)},_createInputBox:function(){dojo.toggleClass(this._inputNode,
"dijitHidden",this.readOnlyInput);if(!this.readOnlyInput&&!this._input){if(this.inputHandler===null)return console.warn("you must add some handler to connect to input field"),!1;if(dojo.isString(this.inputHandler))this.inputHandler=this.inputHandler.split(",");if(dojo.isString(this.inputProperties))this.inputProperties=dojo.fromJson(this.inputProperties);var a=dojo.getObject(this.inputClass,!1);this.inputProperties.regExp=this.regExpGen(this.constraints);this._input=new a(this.inputProperties);this._input.startup();
this._inputNode.appendChild(this._input.domNode);dojo.forEach(this.inputHandler,function(a){this.connect(this._input,dojo.string.trim(a),"_onHandler")},this);this.connect(this._input,"onKeyDown","_inputOnKeyDown");this.connect(this._input,"onBlur","_inputOnBlur")}},compare:function(a,b){a=a.join(",");b=b.join(",");return a>b?1:a<b?-1:0},add:function(a){if(!(this._count>=this.maxItems&&this.maxItems!==null)){this._lastValueReported=this._getValues();dojo.isArray(a)||(a=[a]);for(var b in a){var c=a[b];
if(!(c===""||typeof c!="string")){this._count++;this.regExpGen(this.constraints);this._lastAddedItem=new dojox.form._ListInputInputItem({index:this._items.length,readOnlyItem:this.readOnlyItem,value:c,regExp:this.regExpGen(this.constraints)});this._lastAddedItem.startup();this._testItem(this._lastAddedItem,c);this._lastAddedItem.onClose=dojo.hitch(this,"_onItemClose",this._lastAddedItem);this._lastAddedItem.onChange=dojo.hitch(this,"_onItemChange",this._lastAddedItem);this._lastAddedItem.onEdit=dojo.hitch(this,
"_onItemEdit",this._lastAddedItem);this._lastAddedItem.onKeyDown=dojo.hitch(this,"_onItemKeyDown",this._lastAddedItem);this.useAnim&&dojo.style(this._lastAddedItem.domNode,{opacity:0,display:""});this._placeItem(this._lastAddedItem.domNode);this.useAnim&&dojo.fadeIn({node:this._lastAddedItem.domNode,duration:this.duration,easing:this.easingIn}).play();this._items[this._lastAddedItem.index]=this._lastAddedItem;if(this._onChangeActive&&this.intermediateChanges)this.onChange(c);if(this._count>=this.maxItems&&
this.maxItems!==null)break}}this._updateValues();if(this._lastValueReported.length==0)this._lastValueReported=this.value;this.readOnlyInput||this._input.set("value","");if(this._onChangeActive)this.onChange(this.value);this._setReadOnlyWhenMaxItemsReached()}},_setReadOnlyWhenMaxItemsReached:function(){this.set("readOnlyInput",this._count>=this.maxItems&&this.maxItems!==null)},_setSelectNode:function(){this._selectNode.options.length=0;var a=this.submitOnlyValidValue?this.get("MatchedValue"):this.value;
dojo.isArray(a)&&dojo.forEach(a,function(a){this._selectNode.options[this._selectNode.options.length]=new Option(a,a,!0,!0)},this)},_placeItem:function(a){dojo.place(a,this._inputNode,"before")},_getCursorPos:function(a){if(typeof a.selectionStart!="undefined")return a.selectionStart;try{a.focus()}catch(b){}var c=a.createTextRange();c.moveToBookmark(dojo.doc.selection.createRange().getBookmark());c.moveEnd("character",a.value.length);return a.value.length-c.text.length},_onItemClose:function(a){this.disabled||
(this.useAnim?dojo.fadeOut({node:a.domNode,duration:this.duration,easing:this.easingOut,onEnd:dojo.hitch(this,"_destroyItem",a)}).play():this._destroyItem(a))},_onItemKeyDown:function(a,b){!this.readOnlyItem&&this.useArrowForEdit&&(b.keyCode==dojo.keys.LEFT_ARROW&&this._getCursorPos(b.target)==0?this._editBefore(a):b.keyCode==dojo.keys.RIGHT_ARROW&&this._getCursorPos(b.target)==b.target.value.length&&this._editAfter(a))},_editBefore:function(a){this._currentItem=this._getPreviousItem(a);this._currentItem!==
null&&this._currentItem.edit()},_editAfter:function(a){this._currentItem=this._getNextItem(a);this._currentItem!==null&&this._currentItem.edit();this.readOnlyInput||this._currentItem===null&&this._focusInput()},_onItemChange:function(a,b){b=b||a.get("value");this._testItem(a,b);this._updateValues()},_onItemEdit:function(a){dojo.removeClass(a.domNode,["dijitError",this.baseClass+"Match",this.baseClass+"Mismatch"])},_testItem:function(a,b){var c=RegExp(this.regExpGen(this.constraints)),c=b.match(c);
dojo.removeClass(a.domNode,this.baseClass+(!c?"Match":"Mismatch"));dojo.addClass(a.domNode,this.baseClass+(c?"Match":"Mismatch"));dojo.toggleClass(a.domNode,"dijitError",!c);this.showCloseButtonWhenValid&&c||this.showCloseButtonWhenInvalid&&!c?dojo.addClass(a.domNode,this.baseClass+"Closable"):dojo.removeClass(a.domNode,this.baseClass+"Closable")},_getValueAttr:function(){return this.value},_setValueAttr:function(a){this._destroyAllItems();this.add(this._parseValue(a))},_parseValue:function(a){if(typeof a==
"string"){if(dojo.isString(this.delimiter))this.delimiter=[this.delimiter];var b=RegExp("^.*("+this.delimiter.join("|")+").*");if(a.match(b))return b=RegExp(this.delimiter.join("|")),a.split(b)}return a},regExpGen:function(){return this.regExp},_setDisabledAttr:function(a){if(!this.readOnlyItem)for(var b in this._items)this._items[b].set("disabled",a);this.readOnlyInput||this._input.set("disabled",a);this.inherited(arguments)},_onHandler:function(a){a=this._parseValue(a);dojo.isArray(a)&&this.add(a)},
_onClick:function(){this._focusInput()},_focusInput:function(){!this.readOnlyInput&&this._input.focus&&this._input.focus()},_inputOnKeyDown:function(a){this._currentItem=null;var b=this._input.get("value");a.keyCode==dojo.keys.BACKSPACE&&b==""&&this.get("lastItem")?this._destroyItem(this.get("lastItem")):a.keyCode==dojo.keys.ENTER&&b!=""?this.add(b):a.keyCode==dojo.keys.LEFT_ARROW&&this._getCursorPos(this._input.focusNode)==0&&!this.readOnlyItem&&this.useArrowForEdit&&this._editBefore()},_inputOnBlur:function(){var a=
this._input.get("value");this.useOnBlur&&a!=""&&this.add(a)},_getMatchedValueAttr:function(){return this._getValues(dojo.hitch(this,this._matchValidator))},_getMismatchedValueAttr:function(){return this._getValues(dojo.hitch(this,this._mismatchValidator))},_getValues:function(a){var b=[],a=a||this._nullValidator,c;for(c in this._items){var d=this._items[c];d!==null&&(d=d.get("value"),a(d)&&b.push(d))}return b},_nullValidator:function(){return!0},_matchValidator:function(a){var b=RegExp(this.regExpGen(this.constraints));
return a.match(b)},_mismatchValidator:function(a){var b=RegExp(this.regExpGen(this.constraints));return!a.match(b)},_getLastItemAttr:function(){return this._getSomeItem()},_getSomeItem:function(a,b){var a=a||!1,b=b||"last",c=null,d=-1,e;for(e in this._items)if(this._items[e]!==null){if(b=="before"&&this._items[e]===a)break;c=this._items[e];if(b=="first"||d==0){d=1;break}b=="after"&&this._items[e]===a&&(d=0)}b=="after"&&d==0&&(c=null);return c},_getPreviousItem:function(a){return this._getSomeItem(a,
"before")},_getNextItem:function(a){return this._getSomeItem(a,"after")},_destroyItem:function(a,b){this._items[a.index]=null;a.destroy();this._count--;b!==!1&&(this._updateValues(),this._setReadOnlyWhenMaxItemsReached())},_updateValues:function(){this.value=this._getValues();this._setSelectNode()},_destroyAllItems:function(){for(var a in this._items)this._items[a]!=null&&this._destroyItem(this._items[a],!1);this._items=[];this._count=0;this.value=null;this._setSelectNode();this._setReadOnlyWhenMaxItemsReached()},
destroy:function(){this._destroyAllItems();this._lastAddedItem=null;this._input||this._input.destroy();this.inherited(arguments)}}),dojo.declare("dojox.form._ListInputInputItem",[dijit._Widget,dijit._Templated],{templateString:'<li class="dijit dijitReset dijitLeft dojoxListInputItem" dojoAttachEvent="onclick: onClick" ><span dojoAttachPoint="labelNode"></span></li>',closeButtonNode:null,readOnlyItem:!0,baseClass:"dojoxListInputItem",value:"",regExp:".*",_editBox:null,_handleKeyDown:null,attributeMap:{value:{node:"labelNode",
type:"innerHTML"}},postMixInProperties:function(){var a=dojo.i18n.getLocalization("dijit","common");dojo.mixin(this,a);this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this.closeButtonNode=dojo.create("span",{"class":"dijitButtonNode dijitDialogCloseIcon",title:this.itemClose,onclick:dojo.hitch(this,"onClose"),onmouseenter:dojo.hitch(this,"_onCloseEnter"),onmouseleave:dojo.hitch(this,"_onCloseLeave")},this.domNode);dojo.create("span",{"class":"closeText",title:this.itemClose,
innerHTML:"x"},this.closeButtonNode)},startup:function(){this.inherited(arguments);this._createInlineEditBox()},_setReadOnlyItemAttr:function(a){(this.readOnlyItem=a)?this._editBox&&this._editBox.set("disabled",!0):this._createInlineEditBox()},_createInlineEditBox:function(){if(!this.readOnlyItem&&this._started)this._editBox?this._editBox.set("disabled",!1):(this._editBox=new dijit.InlineEditBox({value:this.value,editor:"dijit.form.ValidationTextBox",editorParams:{regExp:this.regExp}},this.labelNode),
this.connect(this._editBox,"edit","_onEdit"),this.connect(this._editBox,"onChange","_onCloseEdit"),this.connect(this._editBox,"onCancel","_onCloseEdit"))},edit:function(){this.readOnlyItem||this._editBox.edit()},_onCloseEdit:function(a){dojo.removeClass(this.closeButtonNode,this.baseClass+"Edited");dojo.disconnect(this._handleKeyDown);this.onChange(a)},_onEdit:function(){dojo.addClass(this.closeButtonNode,this.baseClass+"Edited");this._handleKeyDown=dojo.connect(this._editBox.editWidget,"_onKeyPress",
this,"onKeyDown");this.onEdit()},_setDisabledAttr:function(a){this.readOnlyItem||this._editBox.set("disabled",a)},_getValueAttr:function(){return!this.readOnlyItem&&this._started?this._editBox.get("value"):this.value},destroy:function(){this._editBox&&this._editBox.destroy();this.inherited(arguments)},_onCloseEnter:function(){dojo.addClass(this.closeButtonNode,"dijitDialogCloseIcon-hover")},_onCloseLeave:function(){dojo.removeClass(this.closeButtonNode,"dijitDialogCloseIcon-hover")},onClose:function(){},
onEdit:function(){},onClick:function(){},onChange:function(){},onKeyDown:function(){}}),dojo.declare("dojox.form._ListInputInputBox",[dijit.form.ValidationTextBox],{minWidth:50,intermediateChanges:!0,regExp:".*",_sizer:null,onChange:function(a){this.inherited(arguments);if(this._sizer===null)this._sizer=dojo.create("div",{style:{position:"absolute",left:"-10000px",top:"-10000px"}},dojo.body());this._sizer.innerHTML=a;var b=dojo.contentBox(this._sizer).w+this.minWidth;dojo.contentBox(this.domNode,
{w:b})},destroy:function(){dojo.destroy(this._sizer);this.inherited(arguments)}}));