/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.form.PasswordValidator"]||(dojo._hasResource["dojox.form.PasswordValidator"]=!0,dojo.provide("dojox.form.PasswordValidator"),dojo.require("dijit.form._FormWidget"),dojo.require("dijit.form.ValidationTextBox"),dojo.requireLocalization("dojox.form","PasswordValidator",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),dojo.declare("dojox.form._ChildTextBox",dijit.form.ValidationTextBox,{containerWidget:null,type:"password",
reset:function(){dijit.form.ValidationTextBox.prototype._setValueAttr.call(this,"",!0);this._hasBeenBlurred=!1},postCreate:function(){this.inherited(arguments);this.name||dojo.removeAttr(this.focusNode,"name");this.connect(this.focusNode,"onkeypress","_onChildKeyPress")},_onChildKeyPress:function(a){a&&a.keyCode==dojo.keys.ENTER&&this._setBlurValue()}}),dojo.declare("dojox.form._OldPWBox",dojox.form._ChildTextBox,{_isPWValid:!1,_setValueAttr:function(a,b){a===""&&(a=dojox.form._OldPWBox.superclass.attr.call(this,
"value"));if(b!==null)this._isPWValid=this.containerWidget.pwCheck(a);this.inherited(arguments);this.containerWidget._childValueAttr(this.containerWidget._inputWidgets[1].get("value"))},isValid:function(a){return this.inherited("isValid",arguments)&&this._isPWValid},_update:function(a){this._hasBeenBlurred&&this.validate(!0);this._onMouse(a)},_getValueAttr:function(){return this.containerWidget._started&&this.containerWidget.isValid()?this.inherited(arguments):""},_setBlurValue:function(){this._setValueAttr(dijit.form.ValidationTextBox.prototype._getValueAttr.call(this),
this.isValid?this.isValid():!0)}}),dojo.declare("dojox.form._NewPWBox",dojox.form._ChildTextBox,{required:!0,onChange:function(){this.containerWidget._inputWidgets[2].validate(!1);this.inherited(arguments)}}),dojo.declare("dojox.form._VerifyPWBox",dojox.form._ChildTextBox,{isValid:function(a){return this.inherited("isValid",arguments)&&this.get("value")==this.containerWidget._inputWidgets[1].get("value")}}),dojo.declare("dojox.form.PasswordValidator",dijit.form._FormValueWidget,{required:!0,_inputWidgets:null,
oldName:"",templateString:dojo.cache("dojox.form","resources/PasswordValidator.html",'<div dojoAttachPoint="containerNode">\n\t<input type="hidden" name="${name}" value="" dojoAttachPoint="focusNode" />\n</div>\n'),_hasBeenBlurred:!1,isValid:function(){return dojo.every(this._inputWidgets,function(a){a&&a._setStateClass&&a._setStateClass();return!a||a.isValid()})},validate:function(){return dojo.every(dojo.map(this._inputWidgets,function(a){return a&&a.validate?(a._hasBeenBlurred=a._hasBeenBlurred||
this._hasBeenBlurred,a.validate()):!0},this),"return item;")},reset:function(){this._hasBeenBlurred=!1;dojo.forEach(this._inputWidgets,function(a){a&&a.reset&&a.reset()},this)},_createSubWidgets:function(){var a=this._inputWidgets,b=dojo.i18n.getLocalization("dojox.form","PasswordValidator",this.lang);dojo.forEach(a,function(f,d){if(f){var c={containerWidget:this},e;if(d===0)c.name=this.oldName,c.invalidMessage=b.badPasswordMessage,e=dojox.form._OldPWBox;else if(d===1)c.required=this.required,e=dojox.form._NewPWBox;
else if(d===2)c.invalidMessage=b.nomatchMessage,e=dojox.form._VerifyPWBox;a[d]=new e(c,f)}},this)},pwCheck:function(){return!1},postCreate:function(){this.inherited(arguments);var a=this._inputWidgets=[];dojo.forEach(["old","new","verify"],function(b){a.push(dojo.query("input[pwType="+b+"]",this.containerNode)[0])},this);if(!a[1]||!a[2])throw Error('Need at least pwType="new" and pwType="verify"');if(this.oldName&&!a[0])throw Error('Need to specify pwType="old" if using oldName');this.containerNode=
this.domNode;this._createSubWidgets();this.connect(this._inputWidgets[1],"_setValueAttr","_childValueAttr");this.connect(this._inputWidgets[2],"_setValueAttr","_childValueAttr")},_childValueAttr:function(a){this.set("value",this.isValid()?a:"")},_setDisabledAttr:function(a){this.inherited(arguments);dojo.forEach(this._inputWidgets,function(b){b&&b.set&&b.set("disabled",a)})},_setRequiredAttribute:function(a){this.required=a;dojo.attr(this.focusNode,"required",a);dijit.setWaiState(this.focusNode,"required",
a);this._refreshState();dojo.forEach(this._inputWidgets,function(b){b&&b.set&&b.set("required",a)})},_setValueAttr:function(a){this.inherited(arguments);dojo.attr(this.focusNode,"value",a)},_getValueAttr:function(){return this.inherited(arguments)||""},focus:function(){var a=!1;dojo.forEach(this._inputWidgets,function(b){b&&!b.isValid()&&!a&&(b.focus(),a=!0)});a||this._inputWidgets[1].focus()}}));