/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.jq"]||(dojo._hasResource["dojox.jq"]=!0,dojo.provide("dojox.jq"),dojo.require("dojo.NodeList-traverse"),dojo.require("dojo.NodeList-manipulate"),dojo.require("dojo.io.script"),function(){function K(a,b){a+="";a=a.replace(/<\s*(\w+)([^\/\>]*)\/\s*>/g,function(a,b,h){return L.indexOf("|"+b+"|")==-1?"<"+b+h+"></"+b+">":a});return dojo._toDom(a,b)}function y(a){var b=a.indexOf("-");b!=-1&&(b==0&&(a=a.substring(1)),a=a.replace(/-(\w)/g,function(a,b){return b.toUpperCase()}));return a}
function z(a,b){if(a==b)return a;var c={},d;for(d in b)if((c[d]===void 0||c[d]!=b[d])&&b[d]!==void 0&&a!=b[d])a[d]=dojo.isObject(a[d])&&dojo.isObject(b[d])?dojo.isArray(b[d])?b[d]:z(a[d],b[d]):b[d];if(dojo.isIE&&b&&(d=b.toString,typeof d=="function"&&d!=a.toString&&d!=c.toString&&d!="\nfunction toString() {\n    [native code]\n}\n"))a.toString=b.toString;return a}function A(a,b,c,d){if(d){var h={};h[c]=d;a.forEach(function(a){dojo[b](a,h)});return a}else return Math.abs(Math.round(dojo[b](a[0])[c]))}
function o(a,b,c,d,h){var e=!1;if(e=a.style.display=="none")a.style.display="block";var g=dojo.getComputedStyle(a),i=Math.abs(Math.round(dojo._getContentBox(a,g)[b])),c=c?Math.abs(Math.round(dojo._getPadExtents(a,g)[b])):0,d=d?Math.abs(Math.round(dojo._getBorderExtents(a,g)[b])):0,b=h?Math.abs(Math.round(dojo._getMarginExtents(a,g)[b])):0;if(e)a.style.display="none";return c+i+d+b}function p(a){var a=a.split("$$")[0],b=a.indexOf(".");b!=-1&&(a=a.substring(0,b));return a}function B(a,b){return b.indexOf("ajax")==
0?dojo.subscribe(s[b],function(c,d){var h=new e.Event(b);"ajaxComplete|ajaxSend|ajaxSuccess".indexOf(b)!=-1?n(a,[h,c.ioArgs.xhr,c.ioArgs.args]):b=="ajaxError"?n(a,[h,c.ioArgs.xhr,c.ioArgs.args,d]):n(a,[h])}):dojo.connect(a,"on"+b,function(b){n(a,arguments)})}function C(a,b){var a=a||[],a=[].concat(a),c=a[0];if(!c||!c.preventDefault)c=b&&b.preventDefault?b:new e.Event(b),a.unshift(c);return a}function n(a,b,c){t=!0;b=b||u;if(a.nodeType==9)a=a.documentElement;var d=a.getAttribute(j);if(d){var h=b[0],
e=h.type,g=p(e),d=l[d][g],i;c&&(i=c.apply(a,b));if(i!==!1)for(var f in d)if(f!="_connectId"&&(!h._isStrict&&f.indexOf(e)==0||h._isStrict&&f==e))h[dojo._scopeName+"callbackId"]=f,a=d[f],h.data=typeof a.data!="undefined"?a.data:null,(i=a.fn.apply(h.target,b))===!1&&!h._isFake&&dojo.stopEvent(h),h.result=i;return i}}function D(a,b,c,d,h){var e=a[b];if(e){var g=c.indexOf(".")!=-1,f=!1;if(d)delete e[d];else if(!g&&!h)f=!0;else if(g)if(c.charAt(0)==".")for(var k in e)k.indexOf(c)==k.length-c.length&&delete e[k];
else delete e[c];else for(k in e)if(k.indexOf("$$")!=-1&&e[k].fn==h){delete e[k];break}c=!0;for(k in e)if(k!="_connectId"){c=!1;break}if(f||c)b.indexOf("ajax")!=-1?dojo.unsubscribe(e._connectId):dojo.disconnect(e._connectId),delete a[b]}}function E(a){dojo.isString(a)&&(a=a=="slow"?700:(a="fast",300));return a}function F(a){for(var b in a)if(b.indexOf("callback")==b.length-8)return b;return null}dojo.config.ioPublish=!0;var L="|img|meta|hr|br|input|",M=dojo.global.$,N=dojo.global.jQuery,e=dojo.global.$=
dojo.global.jQuery=function(a,b){var c=a;if(c)if(dojo.isString(c))if(c.charAt(0)=="<")if(c=K(c),c.nodeType==11)c=c.childNodes;else return e._wrap([c],null,e);else{var d=dojo._NodeListCtor;dojo._NodeListCtor=e;var h=b;h&&h._is$?h=h[0]:dojo.isString(h)&&(h=dojo.query(h)[0]);c=dojo.query.call(this,c,h);dojo._NodeListCtor=d;return c}else if(dojo.isFunction(c))return e.ready(c),e;else if(c==document||c==window)return e._wrap([c],null,e);else if(dojo.isArray(c)){d=[];for(h=0;h<c.length;h++)dojo.indexOf(d,
c[h])==-1&&d.push(c[h]);return e._wrap(c,null,e)}else{if("nodeType"in c)return e._wrap([c],null,e)}else return e._wrap([],null,e);return e._wrap(dojo._toArray(c),null,e)},v=dojo.NodeList.prototype,f=e.fn=e.prototype=dojo.delegate(v);e._wrap=dojo.NodeList._wrap;var O=/^H\d/i,m=dojo.query.pseudos;dojo.mixin(m,{has:function(a,b){return function(a){return e(b,a).length}},visible:function(){return function(a){return dojo.style(a,"visible")!="hidden"&&dojo.style(a,"display")!="none"}},hidden:function(){return function(a){return a.type==
"hidden"||dojo.style(a,"visible")=="hidden"||dojo.style(a,"display")=="none"}},selected:function(){return function(a){return a.selected}},checked:function(){return function(a){return a.nodeName.toUpperCase()=="INPUT"&&a.checked}},disabled:function(){return function(a){return a.getAttribute("disabled")}},enabled:function(){return function(a){return!a.getAttribute("disabled")}},input:function(){return function(a){a=a.nodeName.toUpperCase();return a=="INPUT"||a=="SELECT"||a=="TEXTAREA"||a=="BUTTON"}},
button:function(){return function(a){return a.nodeName.toUpperCase()=="INPUT"&&a.type=="button"||a.nodeName.toUpperCase()=="BUTTON"}},header:function(){return function(a){return a.nodeName.match(O)}}});var G={};dojo.forEach(["text","password","radio","checkbox","submit","image","reset","file"],function(a){G[a]=function(){return function(b){return b.nodeName.toUpperCase()=="INPUT"&&b.type==a}}});dojo.mixin(m,G);e.browser={mozilla:dojo.isMoz,msie:dojo.isIE,opera:dojo.isOpera,safari:dojo.isSafari};e.browser.version=
dojo.isIE||dojo.isMoz||dojo.isOpera||dojo.isSafari||dojo.isWebKit;e.ready=e.fn.ready=function(a){dojo.addOnLoad(dojo.hitch(null,a,e));return this};f._is$=!0;f.size=function(){return this.length};e.prop=function(a,b){return dojo.isFunction(b)?b.call(a):b};e.className={add:dojo.addClass,remove:dojo.removeClass,has:dojo.hasClass};e.makeArray=function(a){return typeof a=="undefined"?[]:a.length&&!dojo.isString(a)&&!("location"in a)?dojo._toArray(a):[a]};e.merge=function(a,b){var c=[a.length,0],c=c.concat(b);
a.splice.apply(a,c);return a};e.each=function(a,b){if(dojo.isArrayLike(a))for(var c=0;c<a.length;c++){if(b.call(a[c],c,a[c])===!1)break}else if(dojo.isObject(a))for(c in a)if(b.call(a[c],c,a[c])===!1)break;return this};f.each=function(a){return e.each.call(this,this,a)};f.eq=function(){var a=e();dojo.forEach(arguments,function(b){this[b]&&a.push(this[b])},this);return a};f.get=function(a){return a||a==0?this[a]:this};f.index=function(a){a._is$&&(a=a[0]);return this.indexOf(a)};var H=[],P=0,w=dojo._scopeName+
"DataId",I=function(a){var b={};a.nodeType==1&&(b=a.getAttribute(w),b||(b=P++,a.setAttribute(w,b)),(b=H[void 0])||(b=H[void 0]={}));return b};e.data=function(a,b,c){var d=null;if(b=="events"){d=l[a.getAttribute(j)];b=!0;if(d)for(var e in d){b=!1;break}return b?null:d}e=I(a);typeof c!="undefined"?e[b]=c:d=e[b];return c?this:d};e.removeData=function(a,b){var c=I(a);delete c[b];if(a.nodeType==1){var d=!0,e;for(e in c){d=!1;break}d&&a.removeAttribute(w)}return this};f.data=function(a,b){var c=null;this.forEach(function(d){c=
e.data(d,a,b)});return b?this:c};f.removeData=function(a){this.forEach(function(b){e.removeData(b,a)});return this};f.extend=function(){var a=[this],a=a.concat(arguments);return e.extend.apply(e,a)};e.extend=function(){for(var a=arguments,b,c=0;c<a.length;c++){var d=a[c];d&&dojo.isObject(d)&&(b?z(b,d):b=d)}return b};e.noConflict=function(a){var b=e;dojo.global.$=M;if(a)dojo.global.jQuery=N;return b};f.attr=function(a,b){if(arguments.length==1&&dojo.isString(arguments[0])){var c=this[0];if(!c)return null;
var d=arguments[0],e=dojo.attr(c,d),f=c[d];return d in c&&!dojo.isObject(f)&&a!="href"?f:e||f}else{if(dojo.isObject(a))for(c in a)this.attr(c,a[c]);else{var g=dojo.isFunction(b);this.forEach(function(c,d){var e=c[a];a in c&&!dojo.isObject(e)&&a!="href"?c[a]=g?b.call(c,d):b:c.nodeType==1&&dojo.attr(c,a,g?b.call(c,d):b)})}return this}};f.removeAttr=function(a){this.forEach(function(b){var c=b[a];a in b&&!dojo.isObject(c)&&a!="href"?delete b[a]:b.nodeType==1&&(a=="class"?b.removeAttribute(a):dojo.removeAttr(b,
a))});return this};f.toggleClass=function(a,b){var c=arguments.length>1;this.forEach(function(d){dojo.toggleClass(d,a,c?b:!dojo.hasClass(d,a))});return this};f.toggle=function(){var a=arguments;if(arguments.length>1&&dojo.isFunction(arguments[0])){var b=0;return this.bind("click",function(){a[b].apply(this,arguments);b+=1;b>a.length-1&&(b=0)})}else{var c=arguments.length==1?arguments[0]:void 0;this.forEach(function(b){var h=(typeof c=="undefined"?dojo.style(b,"display")=="none":c)?"show":"hide",b=
e(b);b[h].apply(b,a)});return this}};f.hasClass=function(a){return this.some(function(b){return dojo.hasClass(b,a)})};f.html=f.innerHTML;dojo.forEach(["filter","slice"],function(a){f[a]=function(){var b;if(dojo.isFunction(arguments[0])){var c=arguments[0];arguments[0]=function(a,b){return c.call(a,a,b)}}if(a=="filter"&&dojo.isString(arguments[0]))b=this._filterQueryResult(this,arguments[0]);else{var d=dojo._NodeListCtor;dojo._NodeListCtor=f;b=e(v[a].apply(this,arguments));dojo._NodeListCtor=d}return b._stash(this)}});
f.map=function(a){return this._buildArrayFromCallback(a)};e.map=function(a,b){return f._buildArrayFromCallback.call(a,b)};e.inArray=function(a,b){return dojo.indexOf(b,a)};f.is=function(a){return a?!!this.filter(a).length:!1};f.not=function(){var a=e.apply(e,arguments);return e(v.filter.call(this,function(b){return a.indexOf(b)==-1}))._stash(this)};f.add=function(){return this.concat.apply(this,arguments)};f.contents=function(){var a=[];this.forEach(function(b){if(b.nodeName.toUpperCase()=="IFRAME")(b=
b.contentDocument||b.name&&b.document&&document.getElementsByTagName("iframe")[b.name].contentWindow&&document.getElementsByTagName("iframe")[b.name].contentWindow.document||b.name&&document.frames[b.name]&&document.frames[b.name].document||null)&&a.push(b);else for(var b=b.childNodes,c=0;c<b.length;c++)a.push(b[c])});return this._wrap(a)._stash(this)};f.find=function(a){var b=[];this.forEach(function(c){c.nodeType==1&&(b=b.concat(dojo._toArray(e(a,c))))});return this._getUniqueAsNodeList(b)._stash(this)};
f.andSelf=function(){return this.add(this._parent)};f.remove=function(a){a=a?this._filterQueryResult(this,a):this;a.removeData();a.forEach(function(a){a.parentNode.removeChild(a)});return this};e.css=function(a,b,c){b=y(b);return c?dojo.style(a,b,c):dojo.style(a,b)};f.css=function(a,b){if(dojo.isString(a))return a=y(a),arguments.length==2?(!dojo.isString(b)&&a!="zIndex"&&(b+="px"),this.forEach(function(c){c.nodeType==1&&dojo.style(c,a,b)}),this):(b=dojo.style(this[0],a),!dojo.isString(b)&&a!="zIndex"&&
(b+="px"),b);else{for(var c in a)this.css(c,a[c]);return this}};f.height=function(a){return A(this,"contentBox","h",a)};f.width=function(a){return A(this,"contentBox","w",a)};f.innerHeight=function(){return o(this[0],"h",!0)};f.innerWidth=function(){return o(this[0],"w",!0)};f.outerHeight=function(a){return o(this[0],"h",!0,!0,a)};f.outerWidth=function(a){return o(this[0],"w",!0,!0,a)};var l=[],J=1,j=dojo._scopeName+"eventid",u;e.Event=function(a){if(this==e)return new e.Event(a);typeof a=="string"?
this.type=a.replace(/!/,""):dojo.mixin(this,a);this.timeStamp=(new Date).getTime();this._isFake=!0;this._isStrict=this.type.indexOf("!")!=-1};m=e.Event.prototype={preventDefault:function(){this.isDefaultPrevented=this._true},stopPropagation:function(){this.isPropagationStopped=this._true},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=this.isPropagationStopped=this._true},_true:function(){return!0},_false:function(){return!1}};dojo.mixin(m,{isPropagationStopped:m._false,isImmediatePropagationStopped:m._false,
isDefaultPrevented:m._false});var t=!1;f.triggerHandler=function(a,b,c){var d=this[0];if(d&&d.nodeType!=3&&d.nodeType!=8)return b=C(b,a),n(d,b,c)};f.trigger=function(a,b,c){var b=C(b,a),d=b[0],a=p(d.type);u=b;currentExtraFunc=c;var h=null,f=!d.target;this.forEach(function(g){if(g.nodeType!=3&&g.nodeType!=8){if(g.nodeType==9)g=g.documentElement;if(d._isFake&&(d.currentTarget=g,f))d.target=g;if(c){var i=b.slice(1);h=c.apply(g,h=i.concat(h))}if(h!==!1){t=!1;if(g[a])try{h=g[a]()}catch(k){}else if(g["on"+
a])try{h=g["on"+a]()}catch(q){}t||(h=n(g,b));g=g.parentNode;h!==!1&&!d.isImmediatePropagationStopped()&&!d.isPropagationStopped()&&g&&g.nodeType==1&&e(g).trigger(a,b,c)}}});currentExtraFunc=u=null;return this};var Q=0;f.bind=function(a,b,c){a=a.split(" ");c||(c=b,b=null);this.forEach(function(d){if(d.nodeType!=3&&d.nodeType!=8){if(d.nodeType==9)d=d.documentElement;var e=d.getAttribute(j);e||(e=J++,d.setAttribute(j,e),l[e]={});for(var f=0;f<a.length;f++){var g=a[f],i=p(g);i==g&&(g=i+"$$"+Q++);var k=
l[e];k[i]||(k[i]={_connectId:B(d,i)});k[i][g]={fn:c,data:b}}}});return this};f.unbind=function(a,b){var c=a?a[dojo._scopeName+"callbackId"]:null,a=(a=a&&a.type?a.type:a)?a.split(" "):a;this.forEach(function(d){if(d.nodeType!=3&&d.nodeType!=8){if(d.nodeType==9)d=d.documentElement;if(d=d.getAttribute(j))if(d=l[d]){var e=a;if(!e){var e=[],f;for(f in d)e.push(f)}for(var g=0;g<e.length;g++){var i=e[g],k=p(i);if(i.charAt(0)==".")for(f in d)D(d,f,i,c,b);else D(d,k,i,c,b)}}}});return this};f.one=function(a,
b){return this.bind(a,function(){e(this).unbind(a,arguments.callee);return b.apply(this,arguments)})};f._cloneNode=function(a){var b=a.cloneNode(!0);if(a.nodeType==1)for(var c=dojo.query("["+j+"]",b),d=0,e;e=c[d];d++)if(dojo.query("["+j+'="'+e.getAttribute(j)+'"]',a)[0]){var f=e.getAttribute(j);if(f=l[f]){var g=g=J++;e.setAttribute(j,g);var g=l[g]={},i=void 0;for(i in f){var k=g[i]={_connectId:B(e,i)},q=f[i],r;for(r in q)k[r]={fn:q[r].fn,data:q[r].data}}}}return b};dojo.getObject("$.event.global",
!0);dojo.forEach(["blur","focus","dblclick","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit","ajaxStart","ajaxSend","ajaxSuccess","ajaxError","ajaxComplete","ajaxStop"],function(a){f[a]=function(b){b?this.bind(a,b):this.trigger(a);return this}});f.hide=function(a,b){a=E(a);this.forEach(function(c){var d=c.style;if(dojo.getComputedStyle(c).display!="none")d.overflow="hidden",d.display="block",a?dojo.anim(c,
{width:0,height:0,opacity:0},a,null,function(){d.width="";d.height="";d.display="none";return b&&b.call(c)}):(dojo.style(c,"display","none"),b&&b.call(c))});return this};f.show=function(a,b){a=E(a);this.forEach(function(c){var d=c.style;if(dojo.getComputedStyle(c).display=="none")if(a){var e=parseFloat(d.width),f=parseFloat(d.height);if(!e||!f)d.display="block",f=dojo.marginBox(c),e=f.w,f=f.h;d.width=0;d.height=0;d.overflow="hidden";dojo.attr(c,"opacity",0);d.display="block";dojo.anim(c,{width:e,
height:f,opacity:1},a,null,b?dojo.hitch(c,b):void 0)}else dojo.style(c,"display","block"),b&&b.call(c)});return this};e.ajaxSettings={};e.ajaxSetup=function(a){dojo.mixin(e.ajaxSettings,a)};var s={ajaxStart:"/dojo/io/start",ajaxSend:"/dojo/io/send",ajaxSuccess:"/dojo/io/load",ajaxError:"/dojo/io/error",ajaxComplete:"/dojo/io/done",ajaxStop:"/dojo/io/stop"},x;for(x in s)x.indexOf("ajax")==0&&function(a){f[a]=function(b){this.forEach(function(c){dojo.subscribe(s[a],function(d,f){var j=new e.Event(a),
g=d&&d.ioArgs,i=g&&g.xhr,g=g&&g.args;return"ajaxComplete|ajaxSend|ajaxSuccess".indexOf(a)!=-1?b.call(c,j,i,g):a=="ajaxError"?b.call(c,j,i,g,f):b.call(c,j)})});return this}}(x);var R=dojo._xhrObj;dojo._xhrObj=function(a){var b=R.apply(dojo,arguments);return a&&a.beforeSend&&a.beforeSend(b)===!1?!1:b};e.ajax=function(a){var b=dojo.delegate(e.ajaxSettings),c;for(c in a)if(c=="data"&&dojo.isObject(a[c])&&dojo.isObject(b.data))for(var d in a[c])b.data[d]=a[c][d];else b[c]=a[c];a=b;b=a.url;if("async"in
a)a.sync=!a.async;if(a.global===!1)a.ioPublish=!1;if(a.data)if(d=a.data,dojo.isString(d))a.content=dojo.queryToObject(d);else{for(c in d)dojo.isFunction(d[c])&&(d[c]=d[c]());a.content=d}c=a.dataType;"dataType"in a?(c=="script"?c="javascript":c=="html"&&(c="text"),a.handleAs=c):(c=a.handleAs="text",a.guessedType=!0);if("cache"in a)a.preventCache=!a.cache;else if(a.dataType=="script"||a.dataType=="jsonp")a.preventCache=!0;if(a.error)a._jqueryError=a.error,delete a.error;a.handle=function(b,c){var d=
"success";if(b instanceof Error)d=b.dojoType=="timeout"?"timeout":"error",a._jqueryError&&a._jqueryError(c.xhr,d,b);else{var e=c.args.guessedType&&c.xhr&&c.xhr.responseXML;e&&(b=e);a.success&&a.success(b,d,c.xhr)}a.complete&&a.complete(b,d,c.xhr);return b};d=c=="jsonp";if(c=="javascript"){var f=b.indexOf(":"),j=b.indexOf("/");if(f>0&&f<j){var g=b.indexOf("/",j+2);if(g==-1)g=b.length;if(location.protocol!=b.substring(0,f+1)||location.hostname!=b.substring(j+2,g))d=!0}}if(d){if(c=="jsonp"){b=a.jsonp;
if(!b){if((c=a.url.split("?")[1])&&(c=dojo.queryToObject(c)))if(b=F(c))a.url=a.url.replace(RegExp("([&\\?])?"+b+"=?")+"=?");b||(b=F(a.content))&&delete a.content[b]}a.jsonp=b||"callback"}return b=dojo.io.script.get(a)}else return b=dojo.xhr(a.type||"GET",a),b.ioArgs.xhr===!1?!1:b.ioArgs.xhr};e.getpost=function(a,b,c,d,f){a={url:b,type:a};if(c)dojo.isFunction(c)&&!d?a.complete=c:a.data=c;if(d)dojo.isString(d)&&!f?f=d:a.complete=d;if(f)a.dataType=f;return e.ajax(a)};e.get=dojo.hitch(e,"getpost","GET");
e.post=dojo.hitch(e,"getpost","POST");e.getJSON=function(a,b,c){return e.getpost("GET",a,b,c,"json")};e.getScript=function(a,b){return e.ajax({url:a,success:b,dataType:"script"})};f.load=function(a,b,c){var d=this[0];if(!d||!d.nodeType||d.nodeType==9)return dojo.addOnLoad(a),this;var d=a.split(/\s+/),a=d[0],f=d[1],j=c||b,d=dojo.hitch(this,function(a,b,c){var d=a.match(/\<\s*body[^>]+>.*<\/body\s*>/i);d&&(a=d);d=dojo._toDom(a);if(f){var l=e(dojo.create("div"));l.append(d);d=l.find(f)}else d=e(d.nodeType==
11?d.childNodes:d);this.html(d);j&&setTimeout(dojo.hitch(this,function(){this.forEach(function(d){j.call(d,a,b,c)})}),10)});c?c=d:b=d;d="GET";b&&dojo.isObject(b)&&(d="POST");e.getpost(d,a,b,c,"html");return this};f.serialize=function(){return""+this.map(function(a){if(a.nodeName.toUpperCase()=="FORM")return dojo.formToQuery(a);else if("file|submit|image|reset|button|".indexOf((a.type||"").toLowerCase())==-1){var b=dojo.fieldToObject(a);if(a.name&&b!=null){var c={};c[a.name]=b;return dojo.objectToQuery(c)}}}).join("&")};
e.param=function(a){return a._is$&&a.serialize?a.serialize():dojo.isArray(a)?dojo.map(a,function(a){return e.param(a)}).join("&"):dojo.objectToQuery(a)};e.isFunction=function(){var a=dojo.isFunction.apply(dojo,arguments);a&&(a=typeof arguments[0]!="object");return a}}());