/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.layout.GridContainer"]||(dojo._hasResource["dojox.layout.GridContainer"]=!0,dojo.provide("dojox.layout.GridContainer"),dojo.require("dojox.layout.GridContainerLite"),dojo.declare("dojox.layout.GridContainer",dojox.layout.GridContainerLite,{hasResizableColumns:!0,liveResizeColumns:!1,minColWidth:20,minChildWidth:150,mode:"right",isRightFixed:!1,isLeftFixed:!1,startup:function(){this.inherited(arguments);if(this.hasResizableColumns){for(var b=0;b<this._grid.length-1;b++)this._createGrip(b);
this.getParent()||dojo.ready(dojo.hitch(this,"_placeGrips"))}},resizeChildAfterDrop:function(b,a,c){this.inherited(arguments)&&this._placeGrips()},onShow:function(){this.inherited(arguments);this._placeGrips()},resize:function(){this.inherited(arguments);this._isShown()&&this.hasResizableColumns&&this._placeGrips()},_createGrip:function(b){var b=this._grid[b],a=dojo.create("div",{"class":"gridContainerGrip"},this.domNode);b.grip=a;b.gripHandler=[this.connect(a,"onmouseover",function(a){for(var b=
!1,e=0;e<this._grid.length-1;e++)if(dojo.hasClass(this._grid[e].grip,"gridContainerGripShow")){b=!0;break}b||(dojo.removeClass(a.target,"gridContainerGrip"),dojo.addClass(a.target,"gridContainerGripShow"))})[0],this.connect(a,"onmouseout",function(a){this._isResized||(dojo.removeClass(a.target,"gridContainerGripShow"),dojo.addClass(a.target,"gridContainerGrip"))})[0],this.connect(a,"onmousedown","_resizeColumnOn")[0],this.connect(a,"ondblclick","_onGripDbClick")[0]]},_placeGrips:function(){var b,
a,c=0,d;dojo.forEach(this._grid,function(e){if(e.grip){d=e.grip;b||(b=d.offsetWidth/2);c+=dojo.marginBox(e.node).w;dojo.style(d,"left",c-b+"px");if(!a)a=dojo.contentBox(this.gridNode).h;a>0&&dojo.style(d,"height",a+"px")}},this)},_onGripDbClick:function(){this._updateColumnsWidth(this._dragManager);this.resize()},_resizeColumnOn:function(b){this._activeGrip=b.target;this._initX=b.pageX;b.preventDefault();dojo.body().style.cursor="ew-resize";this._isResized=!0;var b=[],a,c;for(c=0;c<this._grid.length;c++)b[c]=
dojo.contentBox(this._grid[c].node).w;this._oldTabSize=b;for(c=0;c<this._grid.length;c++){a=this._grid[c];if(this._activeGrip==a.grip)this._currentColumn=a.node,this._currentColumnWidth=b[c],this._nextColumn=this._grid[c+1].node,this._nextColumnWidth=b[c+1];a.node.style.width=b[c]+"px"}a=function(a,b){var c=0,g=0;dojo.forEach(a,function(a){a.nodeType==1&&(a=dojo.getComputedStyle(a),g=(dojo.isIE?b:parseInt(a.minWidth))+parseInt(a.marginLeft)+parseInt(a.marginRight),c<g&&(c=g))});return c};b=a(this._currentColumn.childNodes,
this.minChildWidth);a=a(this._nextColumn.childNodes,this.minChildWidth);c=Math.round(dojo.marginBox(this.gridContainerTable).w*this.minColWidth/100);this._currentMinCol=b;this._nextMinCol=a;if(c>this._currentMinCol)this._currentMinCol=c;if(c>this._nextMinCol)this._nextMinCol=c;this._connectResizeColumnMove=dojo.connect(dojo.doc,"onmousemove",this,"_resizeColumnMove");this._connectOnGripMouseUp=dojo.connect(dojo.doc,"onmouseup",this,"_onGripMouseUp")},_onGripMouseUp:function(){dojo.body().style.cursor=
"default";dojo.disconnect(this._connectResizeColumnMove);dojo.disconnect(this._connectOnGripMouseUp);this._connectOnGripMouseUp=this._connectResizeColumnMove=null;this._activeGrip&&(dojo.removeClass(this._activeGrip,"gridContainerGripShow"),dojo.addClass(this._activeGrip,"gridContainerGrip"));this._isResized=!1},_resizeColumnMove:function(b){b.preventDefault();if(!this._connectResizeColumnOff)dojo.disconnect(this._connectOnGripMouseUp),this._connectOnGripMouseUp=null,this._connectResizeColumnOff=
dojo.connect(dojo.doc,"onmouseup",this,"_resizeColumnOff");var a=b.pageX-this._initX;if(a!=0&&!(this._currentColumnWidth+a<this._currentMinCol||this._nextColumnWidth-a<this._nextMinCol))if(this._currentColumnWidth+=a,this._nextColumnWidth-=a,this._initX=b.pageX,this._activeGrip.style.left=parseInt(this._activeGrip.style.left)+a+"px",this.liveResizeColumns)this._currentColumn.style.width=this._currentColumnWidth+"px",this._nextColumn.style.width=this._nextColumnWidth+"px",this.resize()},_resizeColumnOff:function(){dojo.body().style.cursor=
"default";dojo.disconnect(this._connectResizeColumnMove);dojo.disconnect(this._connectResizeColumnOff);this._connectResizeColumnOff=this._connectResizeColumnMove=null;if(!this.liveResizeColumns)this._currentColumn.style.width=this._currentColumnWidth+"px",this._nextColumn.style.width=this._nextColumnWidth+"px";var b=[],a=[],c=this.gridContainerTable.clientWidth,d,e=!1,f;for(f=0;f<this._grid.length;f++)d=this._grid[f].node,dojo.isIE?(b[f]=dojo.marginBox(d).w,a[f]=dojo.contentBox(d).w):(b[f]=dojo.contentBox(d).w,
a=b);for(f=0;f<a.length;f++)if(a[f]!=this._oldTabSize[f]){e=!0;break}if(e){a=dojo.isIE?100:1E4;for(f=0;f<this._grid.length;f++)this._grid[f].node.style.width=Math.round(100*a*b[f]/c)/a+"%";this.resize()}this._activeGrip&&(dojo.removeClass(this._activeGrip,"gridContainerGripShow"),dojo.addClass(this._activeGrip,"gridContainerGrip"));this._isResized=!1},setColumns:function(b){var a,c;if(b>0){a=this._grid.length;b=a-b;if(b>0){var d=[],e,f,g;if(this.mode=="right"){f=this.isLeftFixed&&a>0?1:0;for(a=c=
this.isRightFixed?a-2:a-1;a>=f;a--){g=0;e=this._grid[a].node;for(c=0;c<e.childNodes.length;c++)if(e.childNodes[c].nodeType==1&&e.childNodes[c].id!=""){g++;break}g==0&&(d[d.length]=a);if(d.length>=b){this._deleteColumn(d);break}}}else{c=this.isLeftFixed&&a>0?1:0;f=this.isRightFixed?a-1:a;for(a=c;a<f;a++){g=0;e=this._grid[a].node;for(c=0;c<e.childNodes.length;c++)if(e.childNodes[c].nodeType==1&&e.childNodes[c].id!=""){g++;break}g==0&&(d[d.length]=a);if(d.length>=b){this._deleteColumn(d);break}}}d.length<
b&&dojo.publish("/dojox/layout/gridContainer/noEmptyColumn",[this])}else b<0&&this._addColumn(Math.abs(b));this.hasResizableColumns&&this._placeGrips()}},_addColumn:function(b){var a=this._grid,c,d,e=this.mode=="right",f=this.acceptTypes.join(","),g=this._dragManager;this.hasResizableColumns&&(!this.isRightFixed&&e||this.isLeftFixed&&!e&&this.nbZones==1)&&this._createGrip(a.length-1);for(var h=0;h<b;h++)c=dojo.create("td",{"class":"gridContainerZone dojoxDndArea",accept:f,id:this.id+"_dz"+this.nbZones}),
d=a.length,e?this.isRightFixed?(d-=1,a.splice(d,0,{node:a[d].node.parentNode.insertBefore(c,a[d].node)})):a.push({node:this.gridNode.appendChild(c)}):this.isLeftFixed?(d=d==1?0:1,this._grid.splice(1,0,{node:this._grid[d].node.parentNode.appendChild(c,this._grid[d].node)}),d=1):(d-=this.nbZones,this._grid.splice(d,0,{node:a[d].node.parentNode.insertBefore(c,a[d].node)})),this.hasResizableColumns&&(!e&&this.nbZones!=1||!e&&this.nbZones==1&&!this.isLeftFixed||e&&h<b-1||e&&h==b-1&&this.isRightFixed)&&
this._createGrip(d),g.registerByNode(a[d].node),this.nbZones++;this._updateColumnsWidth(g)},_deleteColumn:function(b){for(var a,c,d=0,e=b.length,f=this._dragManager,g=0;g<e;g++){c=this.mode=="right"?b[g]:b[g]-d;a=this._grid[c];if(this.hasResizableColumns&&a.grip)dojo.forEach(a.gripHandler,function(a){dojo.disconnect(a)}),dojo.destroy(this.domNode.removeChild(a.grip)),a.grip=null;f.unregister(a.node);dojo.destroy(this.gridNode.removeChild(a.node));this._grid.splice(c,1);this.nbZones--;d++}b=this._grid[this.nbZones-
1];if(b.grip)dojo.forEach(b.gripHandler,dojo.disconnect),dojo.destroy(this.domNode.removeChild(b.grip)),b.grip=null;this._updateColumnsWidth(f)},_updateColumnsWidth:function(b){this.inherited(arguments);b._dropMode.updateAreas(b._areaList)},destroy:function(){dojo.unsubscribe(this._dropHandler);this.inherited(arguments)}}));