/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.layout.RadioGroup"]||(dojo._hasResource["dojox.layout.RadioGroup"]=!0,dojo.provide("dojox.layout.RadioGroup"),dojo.experimental("dojox.layout.RadioGroup"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit._Contained"),dojo.require("dijit.layout.StackContainer"),dojo.require("dojo.fx.easing"),dojo.declare("dojox.layout.RadioGroup",[dijit.layout.StackContainer,dijit._Templated],{duration:750,hasButtons:!1,buttonClass:"dojox.layout._RadioButton",
templateString:'<div class="dojoxRadioGroup"> \t<div dojoAttachPoint="buttonHolder" style="display:none;">\t\t<table class="dojoxRadioButtons"><tbody><tr class="dojoxRadioButtonRow" dojoAttachPoint="buttonNode"></tr></tbody></table>\t</div>\t<div class="dojoxRadioView" dojoAttachPoint="containerNode"></div></div>',startup:function(){this.inherited(arguments);this._children=this.getChildren();this._buttons=this._children.length;this._size=dojo.coords(this.containerNode);this.hasButtons&&dojo.style(this.buttonHolder,
"display","block")},_setupChild:function(a){dojo.style(a.domNode,"position","absolute");if(this.hasButtons){var b=this.buttonNode.appendChild(dojo.create("td")),b=dojo.create("div",null,b),b=new (dojo.getObject(this.buttonClass))({label:a.title,page:a},b);dojo.mixin(a,{_radioButton:b});b.startup()}a.domNode.style.display="none"},removeChild:function(a){this.hasButtons&&a._radioButton&&(a._radioButton.destroy(),delete a._radioButton);this.inherited(arguments)},_transition:function(a,b){this._showChild(a);
b&&this._hideChild(b);this.doLayout&&a.resize&&a.resize(this._containerContentBox||this._contentBox)},_showChild:function(a){var b=this.getChildren();a.isFirstChild=a==b[0];a.isLastChild=a==b[b.length-1];a.selected=!0;a.domNode.style.display="";if(a._onShow)a._onShow();else if(a.onShow)a.onShow()},_hideChild:function(a){a.selected=!1;a.domNode.style.display="none";if(a.onHide)a.onHide()}}),dojo.declare("dojox.layout.RadioGroupFade",dojox.layout.RadioGroup,{_hideChild:function(a){dojo.fadeOut({node:a.domNode,
duration:this.duration,onEnd:dojo.hitch(this,"inherited",arguments,arguments)}).play()},_showChild:function(a){this.inherited(arguments);dojo.style(a.domNode,"opacity",0);dojo.fadeIn({node:a.domNode,duration:this.duration}).play()}}),dojo.declare("dojox.layout.RadioGroupSlide",dojox.layout.RadioGroup,{easing:"dojo.fx.easing.backOut",zTop:99,constructor:function(){if(dojo.isString(this.easing))this.easing=dojo.getObject(this.easing)},_positionChild:function(a){if(this._size){var b=!0,c=!0;switch(a.slideFrom){case "bottom":c=
!c;break;case "right":b=!b;c=!c;break;case "top":break;case "left":b=!b;break;default:b=Math.round(Math.random()),c=Math.round(Math.random())}dojo.style(a.domNode,b?"top":"left",(c?"-":"")+(this._size[b?"h":"w"]+20)+"px")}},_showChild:function(a){var b=this.getChildren();a.isFirstChild=a==b[0];a.isLastChild=a==b[b.length-1];a.selected=!0;dojo.style(a.domNode,{zIndex:this.zTop,display:""});this._anim&&this._anim.status()=="playing"&&this._anim.gotoPercent(100,!0);this._anim=dojo.animateProperty({node:a.domNode,
properties:{left:0,top:0},duration:this.duration,easing:this.easing,onEnd:dojo.hitch(a,function(){if(this.onShow)this.onShow();this._onShow&&this._onShow()}),beforeBegin:dojo.hitch(this,"_positionChild",a)});this._anim.play()},_hideChild:function(a){a.selected=!1;a.domNode.style.zIndex=this.zTop-1;if(a.onHide)a.onHide()}}),dojo.declare("dojox.layout._RadioButton",[dijit._Widget,dijit._Templated,dijit._Contained],{label:"",page:null,templateString:'<div dojoAttachPoint="focusNode" class="dojoxRadioButton"><span dojoAttachPoint="titleNode" class="dojoxRadioButtonLabel">${label}</span></div>',
startup:function(){this.connect(this.domNode,"onmouseenter","_onMouse")},_onMouse:function(){this.getParent().selectChild(this.page);this._clearSelected();dojo.addClass(this.domNode,"dojoxRadioButtonSelected")},_clearSelected:function(){dojo.query(".dojoxRadioButtonSelected",this.domNode.parentNode.parentNode).removeClass("dojoxRadioButtonSelected")}}),dojo.extend(dijit._Widget,{slideFrom:"random"}));