/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.layout.ScrollPane"]||(dojo._hasResource["dojox.layout.ScrollPane"]=!0,dojo.provide("dojox.layout.ScrollPane"),dojo.experimental("dojox.layout.ScrollPane"),dojo.require("dijit.layout.ContentPane"),dojo.require("dijit._Templated"),dojo.declare("dojox.layout.ScrollPane",[dijit.layout.ContentPane,dijit._Templated],{_line:null,_lo:null,_offset:15,orientation:"vertical",autoHide:!0,templateString:dojo.cache("dojox.layout","resources/ScrollPane.html",'<div class="dojoxScrollWindow" dojoAttachEvent="onmouseenter: _enter, onmouseleave: _leave">\n    <div class="dojoxScrollWrapper" style="${style}" dojoAttachPoint="wrapper" dojoAttachEvent="onmousemove: _calc">\n\t<div class="dojoxScrollPane" dojoAttachPoint="containerNode"></div>\n    </div>\n    <div dojoAttachPoint="helper" class="dojoxScrollHelper"><span class="helperInner">|</span></div>\n</div>\n'),
resize:function(a){a&&(a.h&&dojo.style(this.domNode,"height",a.h+"px"),a.w&&dojo.style(this.domNode,"width",a.w+"px"));var a=this._dir,b=this._vertical,c=this.containerNode[b?"scrollHeight":"scrollWidth"];dojo.style(this.wrapper,this._dir,this.domNode.style[this._dir]);this._lo=dojo.coords(this.wrapper,!0);if(this._size=Math.max(0,c-this._lo[b?"h":"w"])){this.helper.style.display="";this._line=new dojo._Line(0-this._offset,this._size+this._offset*2);var b=this._lo[b?"h":"w"],c=Math.min(1,b/c),d=b*
c;this._helpLine=new dojo._Line(0,Math.floor(b-b*c));dojo.style(this.helper,a,Math.floor(d)+"px")}else this.helper.style.display="none",this.wrapper[this._scroll]=0},postCreate:function(){this.inherited(arguments);if(this.autoHide)this._showAnim=dojo._fade({node:this.helper,end:0.5,duration:350}),this._hideAnim=dojo.fadeOut({node:this.helper,duration:750});(this._vertical=this.orientation=="vertical")?(this._dir="height",this._edge="top",this._scroll="scrollTop"):(dojo.addClass(this.containerNode,
"dijitInline"),this._dir="width",this._edge="left",this._scroll="scrollLeft");this._hideAnim&&this._hideAnim.play();dojo.style(this.wrapper,"overflow","hidden")},_set:function(a){this._size&&(this.wrapper[this._scroll]=Math.floor(this._line.getValue(a)),dojo.style(this.helper,this._edge,Math.floor(this._helpLine.getValue(a))+"px"))},_calc:function(a){this._lo||this.resize();this._set(this._vertical?(a.pageY-this._lo.y)/this._lo.h:(a.pageX-this._lo.x)/this._lo.w)},_enter:function(){this._hideAnim&&
(this._hideAnim.status()=="playing"&&this._hideAnim.stop(),this._showAnim.play())},_leave:function(){this._hideAnim&&this._hideAnim.play()}}));