/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.layout.TableContainer"]||(dojo._hasResource["dojox.layout.TableContainer"]=!0,dojo.experimental("dojox.layout.TableContainer"),dojo.provide("dojox.layout.TableContainer"),dojo.require("dijit.layout._LayoutWidget"),dojo.declare("dojox.layout.TableContainer",dijit.layout._LayoutWidget,{cols:1,labelWidth:"100",showLabels:!0,orientation:"horiz",spacing:1,customClass:"",postCreate:function(){this.inherited(arguments);this._children=[];this.connect(this,"set",function(a,c){c&&(a==
"orientation"||a=="customClass"||a=="cols")&&this.layout()})},startup:function(){if(!this._started&&(this.inherited(arguments),!this._initialized)){var a=this.getChildren();if(!(a.length<1))this._initialized=!0,dojo.addClass(this.domNode,"dijitTableLayout"),dojo.forEach(a,function(a){!a.started&&!a._started&&a.startup()}),this.resize(),this.layout()}},resize:function(){dojo.forEach(this.getChildren(),function(a){typeof a.resize=="function"&&a.resize()})},layout:function(){function a(a,c,d){if(k.customClass!=
""){var b=k.customClass+"-"+(c||a.tagName.toLowerCase());dojo.addClass(a,b);arguments.length>2&&dojo.addClass(a,b+"-"+d)}}if(this._initialized){var c=this.getChildren(),l={},k=this;dojo.forEach(this._children,dojo.hitch(this,function(a){l[a.id]=a}));dojo.forEach(c,dojo.hitch(this,function(a){l[a.id]||this._children.push(a)}));var f=dojo.create("table",{width:"100%","class":"tableContainer-table tableContainer-table-"+this.orientation,cellspacing:this.spacing},this.domNode),g=dojo.create("tbody");
f.appendChild(g);a(f,"table",this.orientation);var h=dojo.create("tr",{},g),m=!this.showLabels||this.orientation=="horiz"?h:dojo.create("tr",{},g),i=this.cols*(this.showLabels?2:1),j=0;dojo.forEach(this._children,dojo.hitch(this,function(e,c){var d=e.colspan||1;d>1&&(d=this.showLabels?Math.min(i-1,d*2-1):Math.min(i,d));if(j+d-1+(this.showLabels?1:0)>=i)j=0,h=dojo.create("tr",{},g),m=this.orientation=="horiz"?h:dojo.create("tr",{},g);var b;if(this.showLabels)if(b=dojo.create("td",{"class":"tableContainer-labelCell"},
h),e.spanLabel)dojo.attr(b,this.orientation=="vert"?"rowspan":"colspan",2);else{a(b,"labelCell");var f={"for":e.get("id")},f=dojo.create("label",f,b);if(Number(this.labelWidth)>-1||String(this.labelWidth).indexOf("%")>-1)dojo.style(b,"width",String(this.labelWidth).indexOf("%")<0?this.labelWidth+"px":this.labelWidth);f.innerHTML=e.get("label")||e.get("title")}b=e.spanLabel&&b?b:dojo.create("td",{"class":"tableContainer-valueCell"},m);d>1&&dojo.attr(b,"colspan",d);a(b,"valueCell",c);b.appendChild(e.domNode);
j+=d+(this.showLabels?1:0)}));this.table&&this.table.parentNode.removeChild(this.table);dojo.forEach(c,function(a){typeof a.layout=="function"&&a.layout()});this.table=f;this.resize()}},destroyDescendants:function(a){dojo.forEach(this._children,function(c){c.destroyRecursive(a)})},_setSpacingAttr:function(a){this.spacing=a;if(this.table)this.table.cellspacing=Number(a)}}),dojo.extend(dijit._Widget,{label:"",title:"",spanLabel:!1,colspan:1}));