/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.av.FLAudio"]||(dojo._hasResource["dojox.av.FLAudio"]=!0,dojo.provide("dojox.av.FLAudio"),dojo.experimental("dojox.av.FLAudio"),dojo.require("dojox.embed.Flash"),dojo.require("dojox.timing.doLater"),dojo.declare("dojox.av.FLAudio",null,{id:"",initialVolume:0.7,initialPan:0,isDebug:!1,statusInterval:200,_swfPath:dojo.moduleUrl("dojox.av","resources/audio.swf"),allowScriptAccess:"always",allowNetworking:"all",constructor:function(a){dojo.global.swfIsInHTML=function(){return!0};
dojo.mixin(this,a||{});if(!this.id)this.id="flaudio_"+(new Date).getTime();this.domNode=dojo.doc.createElement("div");dojo.style(this.domNode,{position:"relative",width:"1px",height:"1px",top:"1px",left:"1px"});dojo.body().appendChild(this.domNode);this.init()},init:function(){this._subs=[];this.initialVolume=this._normalizeVolume(this.initialVolume);var a={path:this._swfPath.uri,width:"1px",height:"1px",minimumVersion:9,expressInstall:!0,params:{wmode:"transparent",allowScriptAccess:this.allowScriptAccess,
allowNetworking:this.allowNetworking},vars:{id:this.id,autoPlay:this.autoPlay,initialVolume:this.initialVolume,initialPan:this.initialPan,statusInterval:this.statusInterval,isDebug:this.isDebug}};this._sub("mediaError","onError");this._sub("filesProgress","onLoadStatus");this._sub("filesAllLoaded","onAllLoaded");this._sub("mediaPosition","onPlayStatus");this._sub("mediaEnd","onComplete");this._sub("mediaMeta","onID3");this._flashObject=new dojox.embed.Flash(a,this.domNode);this._flashObject.onError=
function(a){console.warn("Flash Error:",a)};this._flashObject.onLoad=dojo.hitch(this,function(a){this.flashMedia=a;this.isPlaying=this.autoPlay;this.isStopped=!this.autoPlay;this.onLoad(this.flashMedia)})},load:function(a){if(dojox.timing.doLater(this.flashMedia,this))return!1;if(a.url)a.url=this._normalizeUrl(a.url);else throw Error("An url is required for loading media");this.flashMedia.load(a);return a.url},doPlay:function(a){this.flashMedia.doPlay(a)},pause:function(a){this.flashMedia.pause(a)},
stop:function(a){this.flashMedia.doStop(a)},setVolume:function(a){this.flashMedia.setVolume(a)},setPan:function(a){this.flashMedia.setPan(a)},getVolume:function(a){return this.flashMedia.getVolume(a)},getPan:function(a){return this.flashMedia.getPan(a)},getPosition:function(a){return this.flashMedia.getPosition(a)},onError:function(a){console.warn("SWF ERROR:",a)},onLoadStatus:function(){},onAllLoaded:function(){},onPlayStatus:function(){},onComplete:function(){},onLoad:function(){},onID3:function(){},
destroy:function(){this.flashMedia?(dojo.forEach(this._subs,function(a){dojo.unsubscribe(a)}),dojo.forEach(this._cons,function(a){dojo.disconnect(a)}),this._flashObject.destroy()):this._cons.push(dojo.connect(this,"onLoad",this,"destroy"))},_sub:function(a,b){dojo.subscribe(this.id+"/"+a,this,b)},_normalizeVolume:function(a){if(a>1)for(;a>1;)a*=0.1;return a},_normalizeUrl:function(a){if(a&&a.toLowerCase().indexOf("http")<0){var b=window.location.href.split("/");b.pop();b=b.join("/")+"/";a=b+a}return a}}));