//>>built
require({cache:{"url:phpr/template/bookingList.html":'<div>\n    <div data-dojo-attach-point="bookingCreator" data-dojo-type="phpr/BookingList/BookingCreator"></div>\n    <div data-dojo-attach-point="content, containerNode"></div>\n</div>\n'}});
define("phpr/BookingList","dojo/_base/array,dojo/_base/declare,dijit/_WidgetBase,dijit/_TemplatedMixin,dijit/_WidgetsInTemplateMixin,dojo/date/locale,dojo/html,dojo/json,dojo/when,dojo/store/JsonRest,dojo/store/Memory,dojo/store/Observable,dojo/store/Cache,dojo/date,dojo/dom-construct,phpr/BookingList/DayBlock,phpr/JsonRestQueryEngine,dojo/_base/lang,phpr/Timehelper,dojo/text!phpr/template/bookingList.html,phpr/BookingList/BookingCreator,dijit/form/FilteringSelect,dijit/form/Textarea,dijit/form/Button,dijit/form/DateTextBox,dijit/form/Form,phpr/DateTextBox".split(","),function(e,
l,m,n,o,x,y,p,i,q,r,s,t,h,j,u,v,g,f,w){return l([m,n,o],{store:null,date:new Date,templateString:w,observer:null,data:null,day2dayBlock:null,constructor:function(){this._setStoreAttr(new q({target:"index.php/Timecard/Timecard/",queryEngine:v}));this.data=[];this.day2dayBlock={}},startup:function(){this.inherited(arguments);this._update()},_setStoreAttr:function(a){this.store=new s(new t(a,new r));this._update()},_setDateAttr:function(a){var b=!this._started||a.getFullYear()!==this.date.getFullYear()||
a.getMonth()!==this.date.getMonth();this.date=a;this.bookingCreator.set("date",a);b&&this._update()},_updating:!1,_update:function(){if(this._started&&!this._destoyed){var a=this._getQueryString();if(this._updating)this._updating=a;this._updating=a;this.bookingCreator.set("store",this.store);j.place("<span>Loading...</span>",this.content,"only");if(this.observer)this.observer.cancel(),this.observer=null;var b=this.store.query({filter:this._getQueryString()},{sort:[{attribute:"start_datetime",descending:!0}]});
i(b,g.hitch(this,function(b){var d=this._updating;this._updating=null;if(d!==a)return this._update();j.empty(this.content);d=this._partitionBookingsByDay(b);this.data=g.clone(b);this.day2dayBlock={};this._addBookingsPartitionedByDay(d)}));this.observer=b.observe(g.hitch(this,"_storeChanged"),!0)}},_storeChanged:function(a,b,c){var a=g.clone(a),d=f.datetimeToJsDate(a.startDatetime);if(-1<b){var k=f.datetimeToJsDate(this.data[b].startDatetime);this.data.splice(b,1);0!==h.compare(d,k,"date")&&this._reloadDay(k)}-1<
c&&this.data.splice(c,0,a);this._reloadDay(d,d)},_reloadDay:function(a,b){var c=new Date(a.getFullYear(),a.getMonth(),a.getDate()),d=this.store.query({filter:this._getQueryString(c,h.add(c,"day",1))});i(d,g.hitch(this,function(a){var d=this.day2dayBlock[c.getTime()];d&&d.widget&&(d.widget.destroyRecursive(),delete this.day2dayBlock[c.getTime()]);a=this._partitionBookingsByDay(a);b&&e.some(a,function(a){return e.some(a.bookings,function(a){var d=0===h.compare(f.datetimeToJsDate(a.startDatetime),b);
if(d)a.highlight=!0;return d})});this._addBookingsPartitionedByDay(a)}))},_addBookingsPartitionedByDay:function(a){e.forEach(a,this._addDayBlock,this);this._reorderDayWidgets()},_addDayBlock:function(a){var b=this.day2dayBlock[a.day.getTime()];b&&b.widget&&(b.widget.destroyRecursive(),delete this.day2dayBlock[a.day.getTime()]);a.store=this.store;widget=new u(a);widget.placeAt(this.content);this.own(widget);this.day2dayBlock[a.day.getTime()]={widget:widget,placed:!1}},_getQueryString:function(a,b){a||
(a=this.date||new Date,a=new Date(a.getFullYear(),a.getMonth(),1));b=b||h.add(a,"month",1);return p.stringify({startDatetime:{"!ge":f.jsDateToIsoDatetime(a),"!lt":f.jsDateToIsoDatetime(b)}})},_partitionBookingsByDay:function(a){var b={};e.forEach(a,function(a){var c=f.datetimeToJsDate(a.startDatetime),c=new Date(c.getFullYear(),c.getMonth(),c.getDate());b[c]=b[c]||[];b[c].push(a)});var a=[],c;for(c in b)a.push({day:new Date(c),bookings:b[c]});return a},_reorderDayWidgets:function(){var a=[],b;for(b in this.day2dayBlock)a.push({ts:parseInt(b,
10),entry:this.day2dayBlock[b]});a.sort(function(a,b){return b.ts-a.ts});e.forEach(a,function(a,b,f){if(!1===a.entry.placed){var e=a.entry.widget;0===b?e.placeAt(this.content,"first"):b===f.length-1?e.placeAt(this.content,"last"):e.placeAt(f[b-1].entry.widget,"after");a.entry.placed=!0;2>b&&e.set("open",!0)}},this)}})});