//>>built
define("phpr/ProjectChooser","dojo/_base/declare,dojo/_base/lang,dojo/_base/array,dojo/dom-class,dojo/store/Memory,dojo/promise/all,dojo/Deferred,dojo/when,dijit/form/FilteringSelect,phpr/models/Project,phpr/Api,phpr/SearchQueryEngine".split(","),function(k,e,l,m,n,o,i,h,p,j,s,q){return k([p],{renderDeferred:null,autoComplete:!1,labelType:"html",searchAttr:"name",labelAttr:"label",dataLoaded:!1,constructor:function(){this.connect(this,"_openResultList",function(a){0<a.length&&this.dropDown.selectFirstNode()})},
createOptions:function(a){var b=new i,d=[],e=this,c=!0,f=function(a){var b={id:""+a.id,name:""+a.id+" "+a.title,label:'<span class="projectId">'+a.id+"</span> "+a.title};if(c)c=!1,e.postStoreSet=function(){this.set("value",""+a.id)};d.push(b)};l.forEach(a.recent,f);0<a.recent.length&&d.push({label:"<hr />"});for(var r in a.projects)f(a.projects[r]);b.resolve(d);return b},buildRendering:function(){this.inherited(arguments);m.add(this.domNode,"project");this.renderOptions()},renderOptions:function(){var a=
this.renderDeferred=new i;this.getData().then(e.hitch(this,this.createOptions)).then(e.hitch(this,function(b){if(!0!==this._destroyed)this.set("store",new n({queryEngine:q,data:b})),this.dataLoaded=!0,this.postStoreSet(),this.renderDeferred=null,a.resolve()}))},postStoreSet:function(){},_setValueAttr:function(){this.dataLoaded&&this.inherited(arguments)},_setCreateOptionsAttr:function(){var a=this,b=arguments;this.renderDeferred&&!0===this._started?this.renderDeferred.then(function(){a.inherited(b);
a.renderOptions()}):!0===this._started&&(this.inherited(arguments),a.renderOptions())},_setGetDataAttr:function(){var a=this,b=arguments;this.renderDeferred&&!0===this._started?this.renderDeferred.then(function(){a.inherited(b);a.renderOptions()}):!0===this._started&&(this.inherited(arguments),a.renderOptions())},getData:function(){return o({recent:j.getRecentProjects(),projects:j.getProjects()})},_selectOption:function(a){this._hasSearchAttr(a)&&this.inherited(arguments)},_announceOption:function(a){this._hasSearchAttr(a)&&
this.inherited(arguments)},_hasSearchAttr:function(a){if(!a)return!1;if(this.dropDown.items[a.getAttribute("item")].hasOwnProperty(this.searchAttr))return!0},_startSearch:function(a){if(!this.dropDown){var b=this.id+"_popup";this.dropDown=new (e.isString(this.dropDownClass)?e.getObject(this.dropDownClass,!1):this.dropDownClass)({onChange:e.hitch(this,this._selectOption),id:b,baseClass:"projectChooserDropDown",dir:this.dir,textDir:this.textDir});this.focusNode.removeAttribute("aria-activedescendant");
this.textbox.setAttribute("aria-owns",b)}this._lastInput=a;this._abortQuery();var d=this,g=e.clone(this.query),c={start:0,count:this.pageSize,queryOptions:{ignoreCase:this.ignoreCase,deep:!0}},f=function(){var b=d._fetchHandle=d.store.query(g,c);!d.disabled&&!(d.readOnly||a!==d._lastQuery)&&h(b,function(e){d._fetchHandle=null;!d.disabled&&!d.readOnly&&a===d._lastQuery&&h(b.total,function(a){e.total=a;var b=d.pageSize;if(isNaN(b)||b>e.total)b=e.total;e.nextPage=function(a){c.direction=a=!1!==a;c.count=
b;if(a){if(c.start+=e.length,c.start>=e.total)c.count=0}else if(c.start-=b,0>c.start)c.count=Math.max(b+c.start,0),c.start=0;0>=c.count?(e.length=0,d.onSearch(e,g,c)):f()};d.onSearch(e,g,c)})},function(a){d._fetchHandle=null;d._cancelingQuery||console.error(d.declaredClass+" "+a.toString())})};e.mixin(c,this.fetchProperties);this._lastQuery=g[this.searchAttr]=a;this._queryDeferHandle=this.defer(f,this.searchDelay)},_setDisplayedValueAttr:function(a,b){null===a&&(a="");if(!this._created){if(!("displayedValue"in
this.params))return;b=!1}if(this.store){this.closeDropDown();var d=e.clone(this.query),g=this._getDisplayQueryString(a);this._lastQuery=d[this.searchAttr]=g;this._lastDisplayedValue=this.textbox.value=a;this._set("displayedValue",a);var c=this,f={ignoreCase:this.ignoreCase,deep:!0};e.mixin(f,this.fetchProperties);this._fetchHandle=this.store.query(d,f);h(this._fetchHandle,function(a){c._fetchHandle=null;c._callbackSetLabel(a||[],d,f,b)},function(a){c._fetchHandle=null;c._cancelingQuery||console.error("dijit.form.FilteringSelect: "+
a.toString())})}}})});