/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.themes.Claro"]||(dojo._hasResource["dojox.charting.themes.Claro"]=!0,dojo.provide("dojox.charting.themes.Claro"),dojo.require("dojox.gfx.gradutils"),dojo.require("dojox.charting.Theme"),function(){var c=dojox.charting,h=c.themes,f=c.Theme,d=f.generateGradient,e={type:"linear",space:"shape",x1:0,y1:0,x2:0,y2:100};h.Claro=new c.Theme({chart:{fill:{type:"linear",x1:0,x2:0,y1:0,y2:100,colors:[{offset:0,color:"#dbdbdb"},{offset:1,color:"#efefef"}]},stroke:{color:"#b5bcc7"}},
plotarea:{fill:{type:"linear",x1:0,x2:0,y1:0,y2:100,colors:[{offset:0,color:"#dbdbdb"},{offset:1,color:"#efefef"}]}},axis:{stroke:{color:"#888c76",width:1},tick:{color:"#888c76",position:"center",font:"normal normal normal 7pt Verdana, Arial, sans-serif",fontColor:"#888c76"}},series:{stroke:{width:2.5,color:"#fff"},outline:null,font:"normal normal normal 7pt Verdana, Arial, sans-serif",fontColor:"#131313"},marker:{stroke:{width:1.25,color:"#131313"},outline:{width:1.25,color:"#131313"},font:"normal normal normal 8pt Verdana, Arial, sans-serif",
fontColor:"#131313"},seriesThemes:[{fill:d(e,"#2a6ead","#3a99f2")},{fill:d(e,"#613e04","#996106")},{fill:d(e,"#0e3961","#155896")},{fill:d(e,"#55aafa","#3f7fba")},{fill:d(e,"#ad7b2a","#db9b35")}],markerThemes:[{fill:"#2a6ead",stroke:{color:"#fff"}},{fill:"#613e04",stroke:{color:"#fff"}},{fill:"#0e3961",stroke:{color:"#fff"}},{fill:"#55aafa",stroke:{color:"#fff"}},{fill:"#ad7b2a",stroke:{color:"#fff"}}]});h.Claro.next=function(a,d,e){var g=a=="line";if(g||a=="area"){var b=this.seriesThemes[this._current%
this.seriesThemes.length],c=this.markerThemes[this._current%this.markerThemes.length];b.fill.space="plot";if(g)b.stroke={width:4,color:b.fill.colors[0].color};c.outline={width:1.25,color:c.fill};g=f.prototype.next.apply(this,arguments);delete b.outline;delete b.stroke;b.fill.space="shape";return g}else if(a=="candlestick")return b=this.seriesThemes[this._current%this.seriesThemes.length],b.fill.space="plot",b.stroke={width:1,color:b.fill.colors[0].color},g=f.prototype.next.apply(this,arguments);return f.prototype.next.apply(this,
arguments)};h.Claro.post=function(a,c){a=f.prototype.post.apply(this,arguments);if((c=="slice"||c=="circle")&&a.series.fill&&a.series.fill.type=="radial")a.series.fill=dojox.gfx.gradutils.reverse(a.series.fill);return a}}());