/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.charting.themes.Renkoo"]||(dojo._hasResource["dojox.charting.themes.Renkoo"]=!0,dojo.provide("dojox.charting.themes.Renkoo"),dojo.require("dojox.gfx.gradutils"),dojo.require("dojox.charting.Theme"),function(){var e=dojox.charting,g=e.themes,f=e.Theme,b=f.generateGradient,c={type:"linear",space:"shape",x1:0,y1:0,x2:0,y2:150};g.Renkoo=new e.Theme({chart:{fill:"#123666",pageStyle:{backgroundColor:"#123666",backgroundImage:"none",color:"#95afdb"}},plotarea:{fill:"#123666"},axis:{stroke:{color:"#95afdb",
width:1},tick:{color:"#95afdb",position:"center",font:"normal normal normal 7pt Lucida Grande, Helvetica, Arial, sans-serif",fontColor:"#95afdb"}},series:{stroke:{width:2.5,color:"#123666"},outline:null,font:"normal normal normal 8pt Lucida Grande, Helvetica, Arial, sans-serif",fontColor:"#95afdb"},marker:{stroke:{width:2.5,color:"#ccc"},outline:null,font:"normal normal normal 8pt Lucida Grande, Helvetica, Arial, sans-serif",fontColor:"#95afdb"},seriesThemes:[{fill:b(c,"#e7e391","#f8f7de")},{fill:b(c,
"#ffb6b6","#ffe8e8")},{fill:b(c,"#bcda7d","#eef7da")},{fill:b(c,"#d5d5d5","#f4f4f4")},{fill:b(c,"#c1e3fd","#e4f3ff")}],markerThemes:[{fill:"#fcfcf3",stroke:{color:"#e7e391"}},{fill:"#fff1f1",stroke:{color:"#ffb6b6"}},{fill:"#fafdf4",stroke:{color:"#bcda7d"}},{fill:"#fbfbfb",stroke:{color:"#d5d5d5"}},{fill:"#f3faff",stroke:{color:"#c1e3fd"}}]});g.Renkoo.next=function(a,b,c){if("slice,column,bar".indexOf(a)==-1){var d=this.seriesThemes[this._current%this.seriesThemes.length];d.fill.space="plot";d.stroke=
{width:2,color:d.fill.colors[0].color};if(a=="line"||a=="area")d.stroke.width=4;var e=f.prototype.next.apply(this,arguments);delete d.stroke;d.fill.space="shape";return e}return f.prototype.next.apply(this,arguments)};g.Renkoo.post=function(a,b){a=f.prototype.post.apply(this,arguments);if((b=="slice"||b=="circle")&&a.series.fill&&a.series.fill.type=="radial")a.series.fill=dojox.gfx.gradutils.reverse(a.series.fill);return a}}());