/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins._RowMapLayer"]||(dojo._hasResource["dojox.grid.enhanced.plugins._RowMapLayer"]=!0,dojo.provide("dojox.grid.enhanced.plugins._RowMapLayer"),dojo.require("dojox.grid.enhanced.plugins._StoreLayer"),function(){var j=function(b){b.sort(function(a,b){return a-b});for(var c=[[b[0]]],a=1,d=0;a<b.length;++a)b[a]==b[a-1]+1?c[d].push(b[a]):c[++d]=[b[a]];return c},l=function(b,c){return c?dojo.hitch(b||dojo.global,c):function(){}};dojo.declare("dojox.grid.enhanced.plugins._RowMapLayer",
dojox.grid.enhanced.plugins._StoreLayer,{tags:["reorder"],constructor:function(b){this._map={};this._revMap={};this.grid=b;this._oldOnDelete=b._onDelete;var c=this;b._onDelete=function(a){c._onDelete(a);c._oldOnDelete.call(b,a)};this._oldSort=b.sort;b.sort=function(){c.clearMapping();c._oldSort.apply(b,arguments)}},uninitialize:function(){this.grid._onDelete=this._oldOnDelete;this.grid.sort=this._oldSort},setMapping:function(b){this._store.forEachLayer(function(a){if(a.name()==="rowmap")return!1;
else if(a.onRowMappingChange)a.onRowMappingChange(b);return!0},!1);var c,a,d,f={};for(c in b)c=parseInt(c,10),a=b[c],typeof a=="number"&&(c in this._revMap?(d=this._revMap[c],delete this._revMap[c]):d=c,d==a?(delete this._map[d],f[a]="eq"):(this._map[d]=a,f[a]=d));for(a in f)f[a]==="eq"?delete this._revMap[parseInt(a,10)]:this._revMap[parseInt(a,10)]=f[a]},clearMapping:function(){this._map={};this._revMap={}},_onDelete:function(b){var c=this.grid._getItemIndex(b,!0);if(c in this._revMap){var b=[],
a,d=this._revMap[c];delete this._map[d];delete this._revMap[c];for(a in this._revMap)a=parseInt(a,10),this._revMap[a]>d&&--this._revMap[a];for(a in this._revMap)a=parseInt(a,10),a>c&&b.push(a);b.sort(function(a,b){return b-a});for(c=b.length-1;c>=0;--c)a=b[c],this._revMap[a-1]=this._revMap[a],delete this._revMap[a];this._map={};for(a in this._revMap)this._map[this._revMap[a]]=a}},_fetch:function(b){var c=0,a,d=b.start||0;for(a in this._revMap)a=parseInt(a,10),a>=d&&++c;if(c>0){var f=[],e,g={},h=b.count>
0?b.count:-1;if(h>0)for(e=0;e<h;++e)a=d+e,a=a in this._revMap?this._revMap[a]:a,g[a]=e,f.push(a);else for(e=0;;++e)if(a=d+e,a in this._revMap&&(--c,a=this._revMap[a]),g[a]=e,f.push(a),c<=0)break;this._subFetch(b,this._getRowArrays(f),0,[],g,b.onComplete,d,h);return b}else return dojo.hitch(this._store,this._originFetch)(b)},_getRowArrays:function(b){return j(b)},_subFetch:function(b,c,a,d,f,e,g,h){var i=c[a],k=this,j=b.start=i[0];b.count=i[i.length-1]-i[0]+1;b.onComplete=function(i){dojo.forEach(i,
function(a,b){var c=j+b;c in f&&(d[f[c]]=a)});++a==c.length?h>0?(b.start=g,b.count=h,b.onComplete=e,l(b.scope,e)(d,b)):(b.start+=i.length,delete b.count,b.onComplete=function(a){d=d.concat(a);b.start=g;b.onComplete=e;l(b.scope,e)(d,b)},k.originFetch(b)):k._subFetch(b,c,a,d,f,e,g,h)};k.originFetch(b)}})}());