/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins._StoreLayer"]||(dojo._hasResource["dojox.grid.enhanced.plugins._StoreLayer"]=!0,dojo.provide("dojox.grid.enhanced.plugins._StoreLayer"),function(){var f=dojox.grid.enhanced.plugins,g=function(a){for(var b=["reorder","sizeChange","normal","presentation"],c=b.length,d=a.length-1;d>=0;--d){var e=dojo.indexOf(b,a[d]);e>=0&&e<=c&&(c=e)}return c<b.length-1?b.slice(0,c+1):b},h=function(a){var b,c=this._layers;b=c.length;if(a){for(b-=1;b>=0;--b)if(c[b].name()==
a){c[b]._unwrap(c[b+1]);break}c.splice(b,1)}else for(b-=1;b>=0;--b)c[b]._unwrap();c.length||(delete this._layers,delete this.layer,delete this.unwrap,delete this.forEachLayer);return this},i=function(a){var b,c=this._layers;if(typeof a=="undefined")return c.length;if(typeof a=="number")return c[a];for(b=c.length-1;b>=0;--b)if(c[b].name()==a)return c[b];return null},j=function(a,b){var c=this._layers.length,d,e;b?(d=0,e=1):(d=c-1,e=c=-1);for(;d!=c;d+=e)if(a(this._layers[d],d)===!1)return d;return c};
f.wrap=function(a,b,c,d){if(!a._layers)a._layers=[],a.layer=dojo.hitch(a,i),a.unwrap=dojo.hitch(a,h),a.forEachLayer=dojo.hitch(a,j);var e=g(c.tags);dojo.some(a._layers,function(f,g){return dojo.some(f.tags,function(a){return dojo.indexOf(e,a)>=0})?!1:(a._layers.splice(g,0,c),c._wrap(a,b,d,f),!0)})||(a._layers.push(c),c._wrap(a,b,d));return a};dojo.declare("dojox.grid.enhanced.plugins._StoreLayer",null,{tags:["normal"],layerFuncName:"_fetch",constructor:function(){this._originFetch=this._store=null;
this.__enabled=!0},initialize:function(){},uninitialize:function(){},invalidate:function(){},_wrap:function(a,b,c,d){this._store=a;this._funcName=b;var e=dojo.hitch(this,function(){return(this.enabled()?this[c||this.layerFuncName]:this.originFetch).apply(this,arguments)});d?(this._originFetch=d._originFetch,d._originFetch=e):(this._originFetch=a[b]||function(){},a[b]=e);this.initialize(a)},_unwrap:function(a){this.uninitialize(this._store);a?a._originFetch=this._originFetch:this._store[this._funcName]=
this._originFetch;this._store=this._originFetch=null},enabled:function(a){if(typeof a!="undefined")this.__enabled=!!a;return this.__enabled},name:function(){if(!this.__name){var a=this.declaredClass.match(/(?:\.(?:_*)([^\.]+)Layer$)|(?:\.([^\.]+)$)/i);this.__name=a?(a[1]||a[2]).toLowerCase():this.declaredClass}return this.__name},originFetch:function(){return dojo.hitch(this._store,this._originFetch).apply(this,arguments)}});dojo.declare("dojox.grid.enhanced.plugins._ServerSideLayer",f._StoreLayer,
{constructor:function(a){a=a||{};this._url=a.url||"";this._isStateful=!!a.isStateful;this._onUserCommandLoad=a.onCommandLoad||function(){};this.__cmds={cmdlayer:this.name(),enable:!0};this.useCommands(this._isStateful)},enabled:function(a){var b=this.inherited(arguments);this.__cmds.enable=this.__enabled;return b},useCommands:function(a){if(typeof a!="undefined")this.__cmds.cmdlayer=a&&this._isStateful?this.name():null;return!!this.__cmds.cmdlayer},_fetch:function(a){this.__cmds.cmdlayer?dojo.xhrPost({url:this._url||
this._store.url,content:this.__cmds,load:dojo.hitch(this,function(b){this.onCommandLoad(b,a);this.originFetch(a)}),error:dojo.hitch(this,this.onCommandError)}):(this.onCommandLoad("",a),this.originFetch(a));return a},command:function(a,b){var c=this.__cmds;b===null?delete c[a]:typeof b!=="undefined"&&(c[a]=b);return c[a]},onCommandLoad:function(a,b){this._onUserCommandLoad(this.__cmds,b,a)},onCommandError:function(a){console.log(a);throw a;}})}());