/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.CellMerge"]||(dojo._hasResource["dojox.grid.enhanced.plugins.CellMerge"]=!0,dojo.provide("dojox.grid.enhanced.plugins.CellMerge"),dojo.require("dojox.grid.enhanced._Plugin"),dojo.declare("dojox.grid.enhanced.plugins.CellMerge",dojox.grid.enhanced._Plugin,{name:"cellMerge",constructor:function(a,b){this.grid=a;this._records=[];this._merged={};b&&dojo.isObject(b)&&this._setupConfig(b.mergedCells);this._initEvents();this._mixinGrid()},mergeCells:function(a,
b,d,f){(a=this._createRecord({row:a,start:b,end:d,major:f}))&&this._updateRows(a);return a},unmergeCells:function(a){var b;if(a&&(b=dojo.indexOf(this._records,a))>=0)this._records.splice(b,1),this._updateRows(a)},getMergedCells:function(){var a=[],b;for(b in this._merged)a=a.concat(this._merged[b]);return a},getMergedCellsByRow:function(a){return this._merged[a]||[]},_setupConfig:function(a){dojo.forEach(a,this._createRecord,this)},_initEvents:function(){dojo.forEach(this.grid.views.views,function(a){this.connect(a,
"onAfterRow",dojo.hitch(this,"_onAfterRow",a.index))},this)},_mixinGrid:function(){var a=this.grid;a.mergeCells=dojo.hitch(this,"mergeCells");a.unmergeCells=dojo.hitch(this,"unmergeCells");a.getMergedCells=dojo.hitch(this,"getMergedCells");a.getMergedCellsByRow=dojo.hitch(this,"getMergedCellsByRow")},_getWidth:function(a){a=this.grid.layout.cells[a].getHeaderNode();return dojo.position(a).w},_onAfterRow:function(a,b,d){try{if(!(b<0)){var f=[],g,c,j=this._records.length,k=this.grid.layout.cells;for(g=
0;g<j;++g){var e=this._records[g],l=this.grid._by_idx[b];if(e.view==a&&e.row(b,l&&l.item,this.grid.store)){var h={record:e,hiddenCells:[],totalWidth:0,majorNode:k[e.major].getNode(b),majorHeaderNode:k[e.major].getHeaderNode()};for(c=e.start;c<=e.end;++c){var m=this._getWidth(c,b);h.totalWidth+=m;c!=e.major&&h.hiddenCells.push(k[c].getNode(b))}if(d.length!=1||h.totalWidth>0){for(c=f.length-1;c>=0;--c){var i=f[c].record;(i.start>=e.start&&i.start<=e.end||i.end>=e.start&&i.end<=e.end)&&f.splice(c,1)}f.push(h)}}}this._merged[b]=
[];dojo.forEach(f,function(a){dojo.forEach(a.hiddenCells,function(a){dojo.style(a,"display","none")});var d=dojo.marginBox(a.majorHeaderNode).w-dojo.contentBox(a.majorHeaderNode).w,c=a.totalWidth;dojo.isWebKit||(c-=d);dojo.style(a.majorNode,"width",c+"px");dojo.attr(a.majorNode,"colspan",a.hiddenCells.length+1);this._merged[b].push({row:b,start:a.record.start,end:a.record.end,major:a.record.major,handle:a.record})},this)}}catch(n){console.warn("CellMerge._onAfterRow() error: ",b,n)}},_createRecord:function(a){if(this._isValid(a)){a=
{row:a.row,start:a.start,end:a.end,major:a.major};a.view=this.grid.layout.cells[a.start].view.index;a.major=typeof a.major=="number"&&!isNaN(a.major)?a.major:a.start;if(typeof a.row=="number"){var b=a.row;a.row=function(a){return a===b}}else if(typeof a.row=="string"){var d=a.row;a.row=function(a,b,c){try{if(c&&b&&c.getFeatures()["dojo.data.api.Identity"])return c.getIdentity(b)==d}catch(j){console.error(j)}return!1}}if(dojo.isFunction(a.row))return this._records.push(a),a}return null},_isValid:function(a){var b=
this.grid.layout.cells,d=b.length;return dojo.isObject(a)&&"row"in a&&"start"in a&&"end"in a&&a.start>=0&&a.start<d&&a.end>a.start&&a.end<d&&b[a.start].view.index==b[a.end].view.index&&b[a.start].subrow==b[a.end].subrow&&!(typeof a.major=="number"&&(a.major<a.start||a.major>a.end))},_updateRows:function(a){for(var b=null,d=0,f=this.grid.rowCount;d<f;++d){var g=this.grid._by_idx[d];g&&a.row(d,g&&g.item,this.grid.store)&&(this.grid.views.updateRow(d),b===null&&(b=d))}b>=0&&this.grid.scroller.rowHeightChanged(b)}}),
dojox.grid.EnhancedGrid.registerPlugin(dojox.grid.enhanced.plugins.CellMerge));