/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.Cookie"]||(dojo._hasResource["dojox.grid.enhanced.plugins.Cookie"]=!0,dojo.provide("dojox.grid.enhanced.plugins.Cookie"),dojo.require("dojox.grid.enhanced._Plugin"),dojo.require("dojo.cookie"),dojo.require("dojox.grid._RowSelector"),dojo.require("dojox.grid.cells._base"),function(){var g=function(a){var b=[];dojo.isArray(a)||(a=[a]);dojo.forEach(a,function(a){dojo.isArray(a)&&(a={cells:a});a=a.rows||a.cells;dojo.isArray(a)&&(dojo.isArray(a[0])||(a=[a]),
dojo.forEach(a,function(a){dojo.isArray(a)&&dojo.forEach(a,function(a){b.push(a)})}))});return b},h=function(a,b){if(dojo.isArray(a)){var c=b._setStructureAttr;b._setStructureAttr=function(d){if(!b._colWidthLoaded){b._colWidthLoaded=!0;for(var e=g(d),f=e.length-1;f>=0;--f)if(typeof a[f]=="number")e[f].width=a[f]+"px"}c.call(b,d);b._setStructureAttr=c}}},i=function(a){return dojo.map(dojo.filter(a.layout.cells,function(a){return!(a.isRowSelector||a instanceof dojox.grid.cells.RowIndex)}),function(a){return dojo[dojo.isWebKit?
"marginBox":"contentBox"](a.getHeaderNode()).w})},j=function(a,b){if(a&&dojo.every(a,function(a){return dojo.isArray(a)&&dojo.every(a,function(a){return dojo.isArray(a)&&a.length>0})})){var c=b._setStructureAttr,d=function(a){return a!==null&&dojo.isObject(a)&&("cells"in a||"rows"in a||"type"in a&&!("name"in a||"field"in a||"get"in a))};b._setStructureAttr=function(e){if(!b._colOrderLoaded){b._colOrderLoaded=!0;b._setStructureAttr=c;e=dojo.clone(e);dojo.isArray(e)&&!dojo.some(e,d)?e=[{cells:e}]:d(e)&&
(e=[e]);var f=g(e);dojo.forEach(dojo.isArray(e)?e:[e],function(b,c){var d=b;dojo.isArray(b)?b.splice(0,b.length):(delete b.rows,d=b.cells=[]);dojo.forEach(a[c],function(a){dojo.forEach(a,function(a){var b,c;for(b=0;b<f.length;++b)if(c=f[b],dojo.toJson({name:c.name,field:c.field})==dojo.toJson(a))break;b<f.length&&d.push(c)})})})}c.call(b,e)}}},k=function(a){return dojo.map(dojo.filter(a.views.views,function(a){return!(a instanceof dojox.grid._RowSelector)}),function(a){return dojo.map(a.structure.cells,
function(a){return dojo.map(dojo.filter(a,function(a){return!(a.isRowSelector||a instanceof dojox.grid.cells.RowIndex)}),function(a){return{name:a.name,field:a.field}})})})},l=function(a,b){try{dojo.isObject(a)&&b.setSortIndex(a.idx,a.asc)}catch(c){}},m=function(a){return{idx:a.getSortIndex(),asc:a.getSortAsc()}};dojo.isIE||dojo.addOnWindowUnload(function(){dojo.forEach(dijit.findWidgets(dojo.body()),function(a){a instanceof dojox.grid.EnhancedGrid&&!a._destroyed&&a.destroyRecursive()})});dojo.declare("dojox.grid.enhanced.plugins.Cookie",
dojox.grid.enhanced._Plugin,{name:"cookie",_cookieEnabled:!0,constructor:function(a,b){this.grid=a;b=b&&dojo.isObject(b)?b:{};this.cookieProps=b.cookieProps;this._cookieHandlers=[];this._mixinGrid();this.addCookieHandler({name:"columnWidth",onLoad:h,onSave:i});this.addCookieHandler({name:"columnOrder",onLoad:j,onSave:k});this.addCookieHandler({name:"sortOrder",onLoad:l,onSave:m});dojo.forEach(this._cookieHandlers,function(a){if(b[a.name]===!1)a.enable=!1},this)},destroy:function(){this._saveCookie();
this._cookieHandlers=null;this.inherited(arguments)},_mixinGrid:function(){var a=this.grid;a.addCookieHandler=dojo.hitch(this,"addCookieHandler");a.removeCookie=dojo.hitch(this,"removeCookie");a.setCookieEnabled=dojo.hitch(this,"setCookieEnabled");a.getCookieEnabled=dojo.hitch(this,"getCookieEnabled")},_saveCookie:function(){if(this.getCookieEnabled()){for(var a={},b=this._cookieHandlers,c=this.cookieProps,d=window.location+"/"+this.grid.id,c=b.length-1;c>=0;--c)b[c].enabled&&(a[b[c].name]=b[c].onSave(this.grid));
c=dojo.isObject(this.cookieProps)?this.cookieProps:{};dojo.cookie(d,dojo.toJson(a),c)}else this.removeCookie()},onPreInit:function(){var a=this.grid,b=this._cookieHandlers,c=dojo.cookie(window.location+"/"+a.id);if(c)for(var c=dojo.fromJson(c),d=0;d<b.length;++d)if(b[d].name in c&&b[d].enabled)b[d].onLoad(c[b[d].name],a);this._cookie=c||{};this._cookieStartedup=!0},addCookieHandler:function(a){if(a.name){var b=function(){};a.onLoad=a.onLoad||b;a.onSave=a.onSave||b;if(!("enabled"in a))a.enabled=!0;
for(b=this._cookieHandlers.length-1;b>=0;--b)this._cookieHandlers[b].name==a.name&&this._cookieHandlers.splice(b,1);this._cookieHandlers.push(a);if(this._cookieStartedup&&a.name in this._cookie)a.onLoad(this._cookie[a.name],this.grid)}},removeCookie:function(){dojo.cookie(window.location+"/"+this.grid.id,null,{expires:-1})},setCookieEnabled:function(a,b){if(arguments.length==2)for(var c=this._cookieHandlers,d=c.length-1;d>=0;--d){if(c[d].name===a)c[d].enabled=!!b}else(this._cookieEnabled=!!a)||this.removeCookie()},
getCookieEnabled:function(a){if(dojo.isString(a)){for(var b=this._cookieHandlers,c=b.length-1;c>=0;--c)if(b[c].name==a)return b[c].enabled;return!1}return this._cookieEnabled}});dojox.grid.EnhancedGrid.registerPlugin(dojox.grid.enhanced.plugins.Cookie,{preInit:!0})}());