/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.IndirectSelection"]||(dojo._hasResource["dojox.grid.enhanced.plugins.IndirectSelection"]=!0,dojo.provide("dojox.grid.enhanced.plugins.IndirectSelection"),dojo.require("dojo.string"),dojo.require("dojox.grid.cells.dijit"),dojo.require("dojox.grid.enhanced._Plugin"),dojo.declare("dojox.grid.enhanced.plugins.IndirectSelection",dojox.grid.enhanced._Plugin,{name:"indirectSelection",constructor:function(){var a=this.grid.layout;this.connect(a,"setStructure",
dojo.hitch(a,this.addRowSelectCell,this.option))},addRowSelectCell:function(a){if(this.grid.indirectSelection&&this.grid.selectionMode!="none"){var b=!1,c=["get","formatter","field","fields"],e={type:dojox.grid.cells.MultipleRowSelector,name:"",width:"30px",styles:"text-align: center;"};if(a.headerSelector)a.name="";this.grid.rowSelectCell&&this.grid.rowSelectCell.destroy();dojo.forEach(this.structure,function(d){var f=d.cells;if(f&&f.length>0&&!b){d=f[0];if(d[0]&&d[0].isRowSelector)console.debug("addRowSelectCell() - row selector cells already added, return.");
else{var g;g=dojo.mixin(e,a,{type:this.grid.selectionMode=="single"?dojox.grid.cells.SingleRowSelector:dojox.grid.cells.MultipleRowSelector,editable:!1,notselectable:!0,filterable:!1,navigatable:!0,nosort:!0});dojo.forEach(c,function(a){a in g&&delete g[a]});if(f.length>1)g.rowSpan=f.length;dojo.forEach(this.cells,function(a,b){a.index>=0?a.index+=1:console.warn("Error:IndirectSelection.addRowSelectCell()-  cell "+b+" has no index!")});f=this.addCellDef(0,0,g);f.index=0;d.unshift(f);this.cells.unshift(f);
this.grid.rowSelectCell=f}b=!0}},this);this.cellCount=this.cells.length}},destroy:function(){this.grid.rowSelectCell.destroy();delete this.grid.rowSelectCell;this.inherited(arguments)}}),dojo.declare("dojox.grid.cells.RowSelector",dojox.grid.cells._Widget,{inputType:"",map:null,disabledMap:null,isRowSelector:!0,_connects:null,_subscribes:null,checkedText:"&#8730;",unCheckedText:"O",constructor:function(){this.map={};this.disabledMap={};this.disabledCount=0;this._connects=[];this._subscribes=[];this.inA11YMode=
dojo.hasClass(dojo.body(),"dijit_a11y");this.baseClass="dojoxGridRowSelector dijitReset dijitInline dijit"+this.inputType;this.checkedClass=" dijit"+this.inputType+"Checked";this.disabledClass=" dijit"+this.inputType+"Disabled";this.checkedDisabledClass=" dijit"+this.inputType+"CheckedDisabled";this.statusTextClass=" dojoxGridRowSelectorStatusText";this._connects.push(dojo.connect(this.grid,"dokeyup",this,"_dokeyup"));this._connects.push(dojo.connect(this.grid.selection,"onSelected",this,"_onSelected"));
this._connects.push(dojo.connect(this.grid.selection,"onDeselected",this,"_onDeselected"));this._connects.push(dojo.connect(this.grid.scroller,"invalidatePageNode",this,"_pageDestroyed"));this._connects.push(dojo.connect(this.grid,"onCellClick",this,"_onClick"));this._connects.push(dojo.connect(this.grid,"updateRow",this,"_onUpdateRow"))},formatter:function(a,b){var c=this.baseClass,e=this.getValue(b),d=!!this.disabledMap[b];e?(c+=this.checkedClass,d&&(c+=this.checkedDisabledClass)):d&&(c+=this.disabledClass);
return["<div tabindex = -1 ","id = '"+this.grid.id+"_rowSelector_"+b+"' ","name = '"+this.grid.id+"_rowSelector' class = '"+c+"' ","role = 'presentation' aria-pressed = '"+e+"' aria-disabled = '"+d+"' aria-label = '"+dojo.string.substitute(this.grid._nls["indirectSelection"+this.inputType],[b+1])+"'>","<span class = '"+this.statusTextClass+"'>"+(e?this.checkedText:this.unCheckedText)+"</span>","</div>"].join("")},setValue:function(){},getValue:function(a){return this.grid.selection.isSelected(a)},
toggleRow:function(a,b){this._nativeSelect(a,b)},setDisabled:function(a,b){a<0||this._toggleDisabledStyle(a,b)},disabled:function(a){return!!this.disabledMap[a]},_onClick:function(a){a.cell===this&&this._selectRow(a)},_dokeyup:function(a){a.cellIndex==this.index&&a.rowIndex>=0&&a.keyCode==dojo.keys.SPACE&&this._selectRow(a)},focus:function(a){(a=this.map[a])&&a.focus()},_focusEndingCell:function(a,b){this.grid.focus.setFocusCell(this.grid.getCell(b),a)},_nativeSelect:function(a,b){this.grid.selection[b?
"select":"deselect"](a)},_onSelected:function(a){this._toggleCheckedStyle(a,!0)},_onDeselected:function(a){this._toggleCheckedStyle(a,!1)},_onUpdateRow:function(a){delete this.map[a]},_toggleCheckedStyle:function(a,b){var c=this._getSelector(a);c&&(dojo.toggleClass(c,this.checkedClass,b),this.disabledMap[a]&&dojo.toggleClass(c,this.checkedDisabledClass,b),dijit.setWaiState(c,"pressed",b),this.inA11YMode&&dojo.attr(c.firstChild,"innerHTML",b?this.checkedText:this.unCheckedText))},_toggleDisabledStyle:function(a,
b){var c=this._getSelector(a);c&&(dojo.toggleClass(c,this.disabledClass,b),this.getValue(a)&&dojo.toggleClass(c,this.checkedDisabledClass,b),dijit.setWaiState(c,"disabled",b));this.disabledMap[a]=b;a>=0&&(this.disabledCount+=b?1:-1)},_getSelector:function(a){var b=this.map[a];if(!b){var c=this.view.rowNodes[a];c&&(b=dojo.query(".dojoxGridRowSelector",c)[0])&&(this.map[a]=b)}return b},_pageDestroyed:function(a){var b=this.grid.scroller.rowsPerPage;a*=b;for(b=a+b-1;a<=b;a++)this.map[a]&&(dojo.destroy(this.map[a]),
delete this.map[a])},destroy:function(){for(var a in this.map)dojo.destroy(this.map[a]),delete this.map[a];for(a in this.disabledMap)delete this.disabledMap[a];dojo.forEach(this._connects,dojo.disconnect);dojo.forEach(this._subscribes,dojo.unsubscribe);delete this._connects;delete this._subscribes}}),dojo.declare("dojox.grid.cells.SingleRowSelector",dojox.grid.cells.RowSelector,{inputType:"Radio",_selectRow:function(a){a=a.rowIndex;this.disabledMap[a]||(this._focusEndingCell(a,0),this._nativeSelect(a,
!this.grid.selection.selected[a]))}}),dojo.declare("dojox.grid.cells.MultipleRowSelector",dojox.grid.cells.RowSelector,{inputType:"CheckBox",swipeStartRowIndex:-1,swipeMinRowIndex:-1,swipeMaxRowIndex:-1,toSelect:!1,lastClickRowIdx:-1,toggleAllTrigerred:!1,unCheckedText:"&#9633;",constructor:function(){this._connects.push(dojo.connect(dojo.doc,"onmouseup",this,"_domouseup"));this._connects.push(dojo.connect(this.grid,"onRowMouseOver",this,"_onRowMouseOver"));this._connects.push(dojo.connect(this.grid.focus,
"move",this,"_swipeByKey"));this._connects.push(dojo.connect(this.grid,"onCellMouseDown",this,"_onMouseDown"));this.headerSelector&&(this._connects.push(dojo.connect(this.grid.views,"render",this,"_addHeaderSelector")),this._connects.push(dojo.connect(this.grid,"onSelectionChanged",this,"_onSelectionChanged")),this._connects.push(dojo.connect(this.grid,"onKeyDown",this,function(a){a.rowIndex==-1&&a.cellIndex==this.index&&a.keyCode==dojo.keys.SPACE&&this._toggletHeader()})))},toggleAllSelection:function(a){var b=
this.grid,c=b.selection;a?c.selectRange(0,b.rowCount-1):c.deselectAll();this.toggleAllTrigerred=!0},_onMouseDown:function(a){a.cell==this&&(this._startSelection(a.rowIndex),dojo.stopEvent(a))},_onRowMouseOver:function(a){this._updateSelection(a,0)},_domouseup:function(a){dojo.isIE&&this.view.content.decorateEvent(a);a.cellIndex>=0&&this.inSwipeSelection()&&!this.grid.edit.isEditRow(a.rowIndex)&&this._focusEndingCell(a.rowIndex,a.cellIndex);this._finishSelect()},_dokeyup:function(a){this.inherited(arguments);
a.shiftKey||this._finishSelect()},_startSelection:function(a){this.swipeStartRowIndex=this.swipeMinRowIndex=this.swipeMaxRowIndex=a;this.toSelect=!this.getValue(a)},_updateSelection:function(a,b){if(this.inSwipeSelection()){var c=b!==0,e=a.rowIndex,d=e-this.swipeStartRowIndex+b;if(d>0&&this.swipeMaxRowIndex<e+b)this.swipeMaxRowIndex=e+b;if(d<0&&this.swipeMinRowIndex>e+b)this.swipeMinRowIndex=e+b;for(var f=d>0?this.swipeStartRowIndex:e+b,e=d>0?e+b:this.swipeStartRowIndex,d=this.swipeMinRowIndex;d<=
this.swipeMaxRowIndex;d++)this.disabledMap[d]||d<0||(d>=f&&d<=e?this._nativeSelect(d,this.toSelect):c||this._nativeSelect(d,!this.toSelect))}},_swipeByKey:function(a,b,c){if(c&&!(a===0||!c.shiftKey||c.cellIndex!=this.index||this.grid.focus.rowIndex<0)){b=c.rowIndex;if(this.swipeStartRowIndex<0)this.swipeStartRowIndex=b,a>0?(this.swipeMaxRowIndex=b+a,this.swipeMinRowIndex=b):(this.swipeMinRowIndex=b+a,this.swipeMaxRowIndex=b),this.toSelect=this.getValue(b);this._updateSelection(c,a)}},_finishSelect:function(){this.swipeMaxRowIndex=
this.swipeMinRowIndex=this.swipeStartRowIndex=-1;this.toSelect=!1},inSwipeSelection:function(){return this.swipeStartRowIndex>=0},_nativeSelect:function(a,b){this.grid.selection[b?"addToSelection":"deselect"](a)},_selectRow:function(a){var b=a.rowIndex;if(!this.disabledMap[b]){dojo.stopEvent(a);this._focusEndingCell(b,0);var c=b-this.lastClickRowIdx,e=!this.grid.selection.selected[b];if(this.lastClickRowIdx>=0&&!a.ctrlKey&&!a.altKey&&a.shiftKey){a=c>0?b:this.lastClickRowIdx;for(c=c>0?this.lastClickRowIdx:
b;c>=0&&c<=a;c++)this._nativeSelect(c,e)}else this._nativeSelect(b,e);this.lastClickRowIdx=b}},getValue:function(a){if(a==-1){var b=this.grid;return b.rowCount>0&&b.rowCount<=b.selection.getSelectedCount()}return this.inherited(arguments)},_addHeaderSelector:function(){var a=this.view.getHeaderCellNode(this.index);if(a){dojo.empty(a);var b=this.grid,a=a.appendChild(dojo.create("div",{tabindex:-1,id:b.id+"_rowSelector_-1","class":this.baseClass,role:"presentation",innerHTML:"<span class = '"+this.statusTextClass+
"'></span><span style='height: 0; width: 0; overflow: hidden; display: block;'>"+b._nls.selectAll+"</span>"}));this.map[-1]=a;b=this._headerSelectorConnectIdx;b!==void 0&&(dojo.disconnect(this._connects[b]),this._connects.splice(b,1));this._headerSelectorConnectIdx=this._connects.length;this._connects.push(dojo.connect(a,"onclick",this,"_toggletHeader"));this._onSelectionChanged()}},_toggletHeader:function(){if(!this.disabledMap[-1])this.grid._selectingRange=!0,this.toggleAllSelection(!this.getValue(-1)),
this._onSelectionChanged(),this.grid._selectingRange=!1},_onSelectionChanged:function(){var a=this.grid;this.map[-1]&&!a._selectingRange&&this._toggleCheckedStyle(-1,this.getValue(-1))},_toggleDisabledStyle:function(a,b){this.inherited(arguments);if(this.headerSelector){var c=this.grid.rowCount==this.disabledCount;c!=!!this.disabledMap[-1]&&(arguments[0]=-1,arguments[1]=c,this.inherited(arguments))}}}),dojox.grid.EnhancedGrid.registerPlugin(dojox.grid.enhanced.plugins.IndirectSelection,{preInit:!0}));