/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.NestedSorting"]||(dojo._hasResource["dojox.grid.enhanced.plugins.NestedSorting"]=!0,dojo.provide("dojox.grid.enhanced.plugins.NestedSorting"),dojo.require("dojox.grid.enhanced._Plugin"),dojo.declare("dojox.grid.enhanced.plugins.NestedSorting",dojox.grid.enhanced._Plugin,{name:"nestedSorting",_currMainSort:"none",_currRegionIdx:-1,_a11yText:{dojoxGridDescending:"&#9662;",dojoxGridAscending:"&#9652;",dojoxGridAscendingTip:"&#1784;",dojoxGridDescendingTip:"&#1783;",
dojoxGridUnsortedTip:"x"},constructor:function(){this._sortDef=[];this._sortData={};this._headerNodes={};this._excludedColIdx=[];this.nls=this.grid._nls;this.grid.setSortInfo=function(){};this.grid.setSortIndex=dojo.hitch(this,"_setGridSortIndex");this.grid.getSortProps=dojo.hitch(this,"getSortProps");this.grid.sortFields&&this._setGridSortIndex(this.grid.sortFields,null,!0);this.connect(this.grid.views,"render","_initSort");this.initCookieHandler();dojo.subscribe("dojox/grid/rearrange/move/"+this.grid.id,
dojo.hitch(this,"_onColumnDnD"))},onStartUp:function(){this.inherited(arguments);this.connect(this.grid,"onHeaderCellClick","_onHeaderCellClick");this.connect(this.grid,"onHeaderCellMouseOver","_onHeaderCellMouseOver");this.connect(this.grid,"onHeaderCellMouseOut","_onHeaderCellMouseOut")},_onColumnDnD:function(a,b){if(a==="col"){var d={},c=this._sortData,e,f=this._getCurrentRegion();this._blurRegion(f);f=dojo.attr(this._getRegionHeader(f),"idx");for(e in b)c[e]&&(d[b[e]]=c[e],delete c[e]),e===f&&
(f=b[e]);for(e in d)c[e]=d[e];d=this._headerNodes[f];this._currRegionIdx=dojo.indexOf(this._getRegions(),d.firstChild);this._initSort(!1)}},_setGridSortIndex:function(a,b,d){if(dojo.isArray(a)){for(var c,e,b=0;b<a.length;b++){c=a[b];e=this.grid.getCellByField(c.attribute);if(!e){console.warn("Invalid sorting option, column ",c.attribute," not found.");return}if(e.nosort||!this.grid.canSort(e.index,e.field)){console.warn("Invalid sorting option, column ",c.attribute," is unsortable.");return}}this.clearSort();
dojo.forEach(a,function(a,b){e=this.grid.getCellByField(a.attribute);this.setSortData(e.index,"index",b);this.setSortData(e.index,"order",a.descending?"desc":"asc")},this)}else if(isNaN(a))return;else{if(b===void 0)return;this.setSortData(a,"order",b?"asc":"desc")}this._updateSortDef();d||this.grid.sort()},getSortProps:function(){return this._sortDef.length?this._sortDef:null},_initSort:function(a){var b=this.grid,d=b.domNode,c=this._sortDef.length;dojo.toggleClass(d,"dojoxGridSorted",!!c);dojo.toggleClass(d,
"dojoxGridSingleSorted",c===1);dojo.toggleClass(d,"dojoxGridNestSorted",c>1);if(c>0)this._currMainSort=this._sortDef[0].descending?"desc":"asc";var e,f=this._excludedCoIdx=[];this._headerNodes=dojo.query("th",b.viewsHeaderNode).forEach(function(a){e=parseInt(dojo.attr(a,"idx"),10);(dojo.style(a,"display")==="none"||b.layout.cells[e].nosort||b.canSort&&!b.canSort(e,b.layout.cells[e].field))&&f.push(e)});this._headerNodes.forEach(this._initHeaderNode,this);this._initFocus();a&&this._focusHeader()},
_initHeaderNode:function(a){var b=dojo.query(".dojoxGridSortNode",a)[0];b&&dojo.toggleClass(b,"dojoxGridSortNoWrap",!0);if(dojo.indexOf(this._excludedCoIdx,dojo.attr(a,"idx"))>=0)dojo.addClass(a,"dojoxGridNoSort");else{if(dojo.query(".dojoxGridSortBtn",a).length){var b=dojo.query(".dojoxGridSortBtnSingle",a)[0],d=dojo.query(".dojoxGridSortBtnNested",a)[0];b.className="dojoxGridSortBtn dojoxGridSortBtnSingle";d.className="dojoxGridSortBtn dojoxGridSortBtnNested";d.innerHTML="1";dojo.removeClass(a,
"dojoxGridCellShowIndex");dojo.removeClass(a.firstChild,"dojoxGridSortNodeSorted");dojo.removeClass(a.firstChild,"dojoxGridSortNodeAsc");dojo.removeClass(a.firstChild,"dojoxGridSortNodeDesc");dojo.removeClass(a.firstChild,"dojoxGridSortNodeMain");dojo.removeClass(a.firstChild,"dojoxGridSortNodeSub")}else this._connects=dojo.filter(this._connects,function(a){return a._sort?(dojo.disconnect(a),!1):!0}),b=dojo.create("a",{className:"dojoxGridSortBtn dojoxGridSortBtnNested",title:this.nls.nestedSort+
" - "+this.nls.ascending,innerHTML:"1"},a.firstChild,"last"),b.onmousedown=dojo.stopEvent,b=dojo.create("a",{className:"dojoxGridSortBtn dojoxGridSortBtnSingle",title:this.nls.singleSort+" - "+this.nls.ascending},a.firstChild,"last"),b.onmousedown=dojo.stopEvent;this._updateHeaderNodeUI(a)}},_onHeaderCellClick:function(a){this._focusRegion(a.target);dojo.hasClass(a.target,"dojoxGridSortBtn")&&(this._onSortBtnClick(a),dojo.stopEvent(a),this._focusRegion(this._getCurrentRegion()))},_onHeaderCellMouseOver:function(a){if(a.cell&&
!(this._sortDef.length>1)&&!(this._sortData[a.cellIndex]&&this._sortData[a.cellIndex].index===0)){for(var b in this._sortData)if(this._sortData[b]&&this._sortData[b].index===0){dojo.addClass(this._headerNodes[b],"dojoxGridCellShowIndex");break}if(dojo.hasClass(dojo.body(),"dijit_a11y")){b=a.cell.index;var d=a.cellNode,a=dojo.query(".dojoxGridSortBtnSingle",d)[0],d=dojo.query(".dojoxGridSortBtnNested",d)[0];dojo.hasClass(this.grid.domNode,"dojoxGridSingleSorted")||dojo.hasClass(this.grid.domNode,"dojoxGridNestSorted");
var c=dojo.attr(d,"orderIndex");if(c===null||c===void 0)dojo.attr(d,"orderIndex",d.innerHTML),c=d.innerHTML;d.innerHTML=this.isAsc(b)?c+this._a11yText.dojoxGridDescending:this.isDesc(b)?c+this._a11yText.dojoxGridUnsortedTip:c+this._a11yText.dojoxGridAscending;if(this._currMainSort==="none")a.innerHTML=this._a11yText.dojoxGridAscending;else if(this._currMainSort==="asc")a.innerHTML=this._a11yText.dojoxGridDescending;else if(this._currMainSort==="desc")a.innerHTML=this._a11yText.dojoxGridUnsortedTip}}},
_onHeaderCellMouseOut:function(){for(var a in this._sortData)if(this._sortData[a]&&this._sortData[a].index===0){dojo.removeClass(this._headerNodes[a],"dojoxGridCellShowIndex");break}},_onSortBtnClick:function(a){var b=a.cell.index;if(dojo.hasClass(a.target,"dojoxGridSortBtnSingle"))this._prepareSingleSort(b);else if(dojo.hasClass(a.target,"dojoxGridSortBtnNested"))this._prepareNestedSort(b);else return;dojo.stopEvent(a);this._doSort(b)},_doSort:function(a){!this._sortData[a]||!this._sortData[a].order?
this.setSortData(a,"order","asc"):this.isAsc(a)?this.setSortData(a,"order","desc"):this.isDesc(a)&&this.removeSortData(a);this._updateSortDef();this.grid.sort();this._initSort(!0)},setSortData:function(a,b,d){var c=this._sortData[a];c||(c=this._sortData[a]={});c[b]=d},removeSortData:function(a){var b=this._sortData,d=b[a].index,c;delete b[a];for(c in b)b[c].index>d&&b[c].index--},_prepareSingleSort:function(a){var b=this._sortData,d;for(d in b)delete b[d];this.setSortData(a,"index",0);this.setSortData(a,
"order",this._currMainSort==="none"?null:this._currMainSort);if(!this._sortData[a]||!this._sortData[a].order)this._currMainSort="asc";else if(this.isAsc(a))this._currMainSort="desc";else if(this.isDesc(a))this._currMainSort="none"},_prepareNestedSort:function(a){var b=this._sortData[a]?this._sortData[a].index:null;b===0||b||this.setSortData(a,"index",this._sortDef.length)},_updateSortDef:function(){this._sortDef.length=0;var a=this._sortData,b;for(b in a)this._sortDef[a[b].index]={attribute:this.grid.layout.cells[b].field,
descending:a[b].order==="desc"}},_updateHeaderNodeUI:function(a){var b=this._getCellByNode(a),d=b.index,c=this._sortData[d],e=dojo.query(".dojoxGridSortNode",a)[0],f=dojo.query(".dojoxGridSortBtnSingle",a)[0],g=dojo.query(".dojoxGridSortBtnNested",a)[0];dojo.toggleClass(f,"dojoxGridSortBtnAsc",this._currMainSort==="asc");dojo.toggleClass(f,"dojoxGridSortBtnDesc",this._currMainSort==="desc");f.title=this._currMainSort==="asc"?this.nls.singleSort+" - "+this.nls.descending:this._currMainSort==="desc"?
this.nls.singleSort+" - "+this.nls.unsorted:this.nls.singleSort+" - "+this.nls.ascending;var h=this;(function(){var a="Column "+(b.index+1)+" "+b.field,d="none",e="ascending";c&&(d=c.order==="asc"?"ascending":"descending",e=c.order==="asc"?"descending":"none");var i=a+" - is sorted by "+d,j=a+" - is nested sorted by "+d,k=a+" - choose to sort by "+e,l=a+" - choose to nested sort by "+e;dijit.setWaiState(f,"label",i);dijit.setWaiState(g,"label",j);a=[h.connect(f,"onmouseover",function(){dijit.setWaiState(f,
"label",k)}),h.connect(f,"onmouseout",function(){dijit.setWaiState(f,"label",i)}),h.connect(g,"onmouseover",function(){dijit.setWaiState(g,"label",l)}),h.connect(g,"onmouseout",function(){dijit.setWaiState(g,"label",j)})];dojo.forEach(a,function(a){a._sort=!0})})();a=dojo.hasClass(dojo.body(),"dijit_a11y");if(c){if(c.index||c.index===0&&this._sortDef.length>1)g.innerHTML=c.index+1;dojo.addClass(e,"dojoxGridSortNodeSorted");if(this.isAsc(d)){if(dojo.addClass(e,"dojoxGridSortNodeAsc"),g.title=this.nls.nestedSort+
" - "+this.nls.descending,a)e.innerHTML=this._a11yText.dojoxGridAscendingTip}else if(this.isDesc(d)&&(dojo.addClass(e,"dojoxGridSortNodeDesc"),g.title=this.nls.nestedSort+" - "+this.nls.unsorted,a))e.innerHTML=this._a11yText.dojoxGridDescendingTip;dojo.addClass(e,c.index===0?"dojoxGridSortNodeMain":"dojoxGridSortNodeSub")}else g.innerHTML=this._sortDef.length+1},isAsc:function(a){return this._sortData[a].order==="asc"},isDesc:function(a){return this._sortData[a].order==="desc"},_getCellByNode:function(a){var b;
for(b=0;b<this._headerNodes.length;b++)if(this._headerNodes[b]===a)return this.grid.layout.cells[b];return null},clearSort:function(){this._sortData={};this._sortDef.length=0},initCookieHandler:function(){this.grid.addCookieHandler&&this.grid.addCookieHandler({name:"sortOrder",onLoad:dojo.hitch(this,"_loadNestedSortingProps"),onSave:dojo.hitch(this,"_saveNestedSortingProps")})},_loadNestedSortingProps:function(a){this._setGridSortIndex(a)},_saveNestedSortingProps:function(){return this.getSortProps()},
_initFocus:function(){var a=this.focus=this.grid.focus;this._focusRegions=this._getRegions();if(!this._headerArea){var b=this._headerArea=a.getArea("header");b.onFocus=a.focusHeader=dojo.hitch(this,"_focusHeader");b.onBlur=a.blurHeader=a._blurHeader=dojo.hitch(this,"_blurHeader");b.onMove=dojo.hitch(this,"_onMove");b.onKeyDown=dojo.hitch(this,"_onKeyDown");b._regions=[];b.getRegions=null;this.connect(this.grid,"onBlur","_blurHeader")}},_focusHeader:function(a){this._currRegionIdx===-1?this._onMove(0,
1,null):this._focusRegion(this._getCurrentRegion());try{dojo.stopEvent(a)}catch(b){}return!0},_blurHeader:function(){this._blurRegion(this._getCurrentRegion());return!0},_onMove:function(a,b,d){var c=this._focusRegions[(this._currRegionIdx||0)+b];if(c)dojo.style(c,"display")==="none"||dojo.style(c,"visibility")==="hidden"?this._onMove(a,b+(b>0?1:-1),d):(this._focusRegion(c),a=this._getRegionView(c),a.scrollboxNode.scrollLeft=a.headerNode.scrollLeft)},_onKeyDown:function(a,b){if(b)switch(a.keyCode){case dojo.keys.ENTER:case dojo.keys.SPACE:(dojo.hasClass(a.target,
"dojoxGridSortBtnSingle")||dojo.hasClass(a.target,"dojoxGridSortBtnNested"))&&this._onSortBtnClick(a)}},_getRegionView:function(a){for(var b=a;b&&!dojo.hasClass(b,"dojoxGridHeader");)b=b.parentNode;return b?dojo.filter(this.grid.views.views,function(a){return a.headerNode===b})[0]||null:null},_getRegions:function(){var a=[],b=this.grid.layout.cells;this._headerNodes.forEach(function(d,c){dojo.style(d,"display")!=="none"&&(b[c].isRowSelector?a.push(d):dojo.query(".dojoxGridSortNode,.dojoxGridSortBtnNested,.dojoxGridSortBtnSingle",
d).forEach(function(b){dojo.attr(b,"tabindex",0);a.push(b)}))},this);return a},_focusRegion:function(a){if(a){var b=this._getCurrentRegion();b&&a!==b&&this._blurRegion(b);b=this._getRegionHeader(a);dojo.addClass(b,"dojoxGridCellSortFocus");dojo.hasClass(a,"dojoxGridSortNode")?dojo.addClass(a,"dojoxGridSortNodeFocus"):dojo.hasClass(a,"dojoxGridSortBtn")&&dojo.addClass(a,"dojoxGridSortBtnFocus");a.focus();this.focus.currentArea("header");this._currRegionIdx=dojo.indexOf(this._focusRegions,a)}},_blurRegion:function(a){if(a){var b=
this._getRegionHeader(a);dojo.removeClass(b,"dojoxGridCellSortFocus");dojo.hasClass(a,"dojoxGridSortNode")?dojo.removeClass(a,"dojoxGridSortNodeFocus"):dojo.hasClass(a,"dojoxGridSortBtn")&&dojo.removeClass(a,"dojoxGridSortBtnFocus");a.blur()}},_getCurrentRegion:function(){return this._focusRegions[this._currRegionIdx]},_getRegionHeader:function(a){for(;a&&!dojo.hasClass(a,"dojoxGridCell");)a=a.parentNode;return a},destroy:function(){this._headerNodes=this._focusRegions=this._sortDef=this._sortData=
null;this.inherited(arguments)}}),dojox.grid.EnhancedGrid.registerPlugin(dojox.grid.enhanced.plugins.NestedSorting));