/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.grid.enhanced.plugins.Pagination"]||(dojo._hasResource["dojox.grid.enhanced.plugins.Pagination"]=!0,dojo.provide("dojox.grid.enhanced.plugins.Pagination"),dojo.require("dijit.form.NumberTextBox"),dojo.require("dijit.form.Button"),dojo.require("dojox.grid.enhanced._Plugin"),dojo.require("dojox.grid.enhanced.plugins.Dialog"),dojo.require("dojox.grid.enhanced.plugins._StoreLayer"),dojo.requireLocalization("dojox.grid.enhanced","Pagination",null,"ROOT,ar,ca,cs,da,de,el,es,fi,fr,he,hr,hu,it,ja,kk,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-tw"),
dojo.declare("dojox.grid.enhanced.plugins.Pagination",dojox.grid.enhanced._Plugin,{name:"pagination",pageSize:25,defaultRows:25,_currentPage:0,_maxSize:0,init:function(){this.gh=null;this.grid.rowsPerPage=this.pageSize=this.grid.rowsPerPage?this.grid.rowsPerPage:this.pageSize;this.grid.usingPagination=!0;this.nls=dojo.i18n.getLocalization("dojox.grid.enhanced","Pagination");this._wrapStoreLayer();this._createPaginators(this.option);this._regApis()},_createPaginators:function(a){this.paginators=[];
this.paginators=a.position==="both"?[new dojox.grid.enhanced.plugins._Paginator(dojo.mixin(a,{position:"bottom",plugin:this})),new dojox.grid.enhanced.plugins._Paginator(dojo.mixin(a,{position:"top",plugin:this}))]:[new dojox.grid.enhanced.plugins._Paginator(dojo.mixin(a,{plugin:this}))]},_wrapStoreLayer:function(){var a=this.grid,b=dojox.grid.enhanced.plugins;this._store=a.store;this.query=a.query;this.forcePageStoreLayer=new b._ForcedPageStoreLayer(this);b.wrap(a,"_storeLayerFetch",this.forcePageStoreLayer);
this.connect(a,"setQuery",function(a){if(a!==this.query)this.query=a})},_stopEvent:function(a){try{dojo.stopEvent(a)}catch(b){}},_onNew:function(a,b){var c=Math.ceil(this._maxSize/this.pageSize);if((this._currentPage+1===c||c===0)&&this.grid.rowCount<this.pageSize||this.showAll)dojo.hitch(this.grid,this._originalOnNew)(a,b),this.forcePageStoreLayer.endIdx++;this._maxSize++;this.showAll&&this.pageSize++;this.showAll&&this.grid.autoHeight?this.grid._refresh():dojo.forEach(this.paginators,function(a){a.update()})},
_removeSelectedRows:function(){this._multiRemoving=!0;this._originalRemove();this._multiRemoving=!1;this.grid.resize();this.grid._refresh()},_onDelete:function(){this._multiRemoving||(this.grid.resize(),this.showAll&&this.grid._refresh());this.grid.get("rowCount")===0&&this.prevPage()},_regApis:function(){var a=this.grid;a.gotoPage=dojo.hitch(this,this.gotoPage);a.nextPage=dojo.hitch(this,this.nextPage);a.prevPage=dojo.hitch(this,this.prevPage);a.gotoFirstPage=dojo.hitch(this,this.gotoFirstPage);
a.gotoLastPage=dojo.hitch(this,this.gotoLastPage);a.changePageSize=dojo.hitch(this,this.changePageSize);a.showGotoPageButton=dojo.hitch(this,this.showGotoPageButton);a.getTotalRowCount=dojo.hitch(this,this.getTotalRowCount);this.originalScrollToRow=dojo.hitch(a,a.scrollToRow);a.scrollToRow=dojo.hitch(this,this.scrollToRow);this._originalOnNew=dojo.hitch(a,a._onNew);this._originalRemove=dojo.hitch(a,a.removeSelectedRows);a.removeSelectedRows=dojo.hitch(this,this._removeSelectedRows);a._onNew=dojo.hitch(this,
this._onNew);this.connect(a,"_onDelete",dojo.hitch(this,this._onDelete))},destroy:function(){this.inherited(arguments);var a=this.grid;try{dojo.forEach(this.paginators,function(a){a.destroy()}),a.unwrap(this.forcePageStoreLayer.name()),a._onNew=this._originalOnNew,a.removeSelectedRows=this._originalRemove,a.scrollToRow=this.originalScrollToRow,this.nls=this.paginators=null}catch(b){console.warn("Pagination.destroy() error: ",b)}},nextPage:function(){this._maxSize>(this._currentPage+1)*this.pageSize&&
this.gotoPage(this._currentPage+2)},prevPage:function(){this._currentPage>0&&this.gotoPage(this._currentPage)},gotoPage:function(a){var b=Math.ceil(this._maxSize/this.pageSize);a--;if(a<b&&a>=0&&this._currentPage!==a)this._currentPage=a,this.grid.setQuery(this.query),this.grid.resize()},gotoFirstPage:function(){this.gotoPage(1)},gotoLastPage:function(){this.gotoPage(Math.ceil(this._maxSize/this.pageSize))},changePageSize:function(a){typeof a=="string"&&(a=parseInt(a,10));var b=this.pageSize*this._currentPage;
dojo.forEach(this.paginators,function(b){b.currentPageSize=this.grid.rowsPerPage=this.pageSize=a;a>=this._maxSize?(this.grid.rowsPerPage=this.defaultRows,this.grid.usingPagination=!1):this.grid.usingPagination=!0},this);b+Math.min(this.pageSize,this._maxSize)>this._maxSize?this.gotoLastPage():(b=Math.ceil(b/this.pageSize),b!==this._currentPage?this.gotoPage(b+1):this.grid._refresh(!0));this.grid.resize()},showGotoPageButton:function(a){dojo.forEach(this.paginators,function(b){b._showGotoButton(a)})},
scrollToRow:function(a){var b=parseInt(a/this.pageSize,10);b>Math.ceil(this._maxSize/this.pageSize)||(this.gotoPage(b+1),this.grid.setScrollTop(this.grid.scroller.findScrollTop(a%this.pageSize)+1))},getTotalRowCount:function(){return this._maxSize}}),dojo.declare("dojox.grid.enhanced.plugins._ForcedPageStoreLayer",dojox.grid.enhanced.plugins._StoreLayer,{tags:["presentation"],constructor:function(a){this._plugin=a},_fetch:function(a){var b=this,c=b._plugin,d=c.grid,e=a.scope||dojo.global,f=a.onBegin;
a.start=c._currentPage*c.pageSize+a.start;b.startIdx=a.start;b.endIdx=a.start+c.pageSize-1;if(f&&(c.showAll||dojo.every(c.paginators,function(a){return c.showAll=!a.sizeSwitch&&!a.pageStepper&&!a.gotoButton})))a.onBegin=function(a,d){c._maxSize=c.pageSize=a;b.startIdx=0;b.endIdx=a-1;dojo.forEach(c.paginators,function(a){a.update()});d.onBegin=f;d.onBegin.call(e,a,d)};else if(f)a.onBegin=function(a,g){g.start=0;g.count=c.pageSize;c._maxSize=a;b.endIdx=b.endIdx>=a?a-1:b.endIdx;b.startIdx>a&&a!==0&&
(d._pending_requests[g.start]=!1,c.gotoFirstPage());dojo.forEach(c.paginators,function(a){a.update()});g.onBegin=f;g.onBegin.call(e,Math.min(c.pageSize,a-b.startIdx),g)};return dojo.hitch(this._store,this._originFetch)(a)}}),dojo.declare("dojox.grid.enhanced.plugins._Paginator",[dijit._Widget,dijit._Templated],{templateString:'<div dojoAttachPoint="paginatorBar">\n\t<table cellpadding="0" cellspacing="0"  class="dojoxGridPaginator">\n\t\t<tr>\n\t\t\t<td dojoAttachPoint="descriptionTd" class="dojoxGridDescriptionTd">\n\t\t\t\t<div dojoAttachPoint="descriptionDiv" class="dojoxGridDescription" />\n\t\t\t</td>\n\t\t\t<td dojoAttachPoint="sizeSwitchTd"></td>\n\t\t\t<td dojoAttachPoint="pageStepperTd" class="dojoxGridPaginatorFastStep">\n\t\t\t\t<div dojoAttachPoint="pageStepperDiv" class="dojoxGridPaginatorStep"></div>\n\t\t\t</td>\n\t\t</tr>\n\t</table>\n</div>\n',
position:"bottom",_maxItemSize:0,description:!0,pageStepper:!0,maxPageStep:7,sizeSwitch:!0,pageSizes:["10","25","50","100","All"],gotoButton:!1,constructor:function(a){dojo.mixin(this,a);this.grid=this.plugin.grid;this.itemTitle=this.itemTitle?this.itemTitle:this.plugin.nls.itemTitle;this.descTemplate=this.descTemplate?this.descTemplate:this.plugin.nls.descTemplate},postCreate:function(){this.inherited(arguments);this._setWidthValue();var a=this,b=this.grid;this.plugin.connect(b,"_resize",dojo.hitch(this,
"_resetGridHeight"));this._originalResize=dojo.hitch(b,"resize");b.resize=function(c,d){a._changeSize=b._pendingChangeSize=c;a._resultSize=b._pendingResultSize=d;b.sizeChange()};this._placeSelf()},destroy:function(){this.inherited(arguments);this.grid.focus.removeArea("pagination"+this.position.toLowerCase());this._gotoPageDialog&&(this._gotoPageDialog.destroy(),dojo.destroy(this.gotoPageTd),delete this.gotoPageTd,delete this._gotoPageDialog);this.grid.resize=this._originalResize;this.pageSizes=null},
update:function(){this.currentPageSize=this.plugin.pageSize;this._maxItemSize=this.plugin._maxSize;this._updateDescription();this._updatePageStepper();this._updateSizeSwitch();this._updateGotoButton()},_setWidthValue:function(){dojo.forEach(["description","sizeSwitch","pageStepper"],function(a){var b,c=this[a];c===void 0||typeof c=="boolean"||(dojo.isString(c)?b=/px$/.test(c)||/%$/.test(c)||/em$/.test(c)?c:parseInt(c,10)>0?parseInt(c,10)+"px":null:typeof c==="number"&&c>0&&(b=c+"px"),this[a]=b?!0:
!1,this[a+"Width"]=b)},this)},_regFocusMgr:function(a){this.grid.focus.addArea({name:"pagination"+a,onFocus:dojo.hitch(this,this._onFocusPaginator),onBlur:dojo.hitch(this,this._onBlurPaginator),onMove:dojo.hitch(this,this._moveFocus),onKeyDown:dojo.hitch(this,this._onKeyDown)});switch(a){case "top":this.grid.focus.placeArea("pagination"+a,"before","header");break;default:this.grid.focus.placeArea("pagination"+a,"after","content")}},_placeSelf:function(){var a=this.grid;switch(dojo.trim(this.position.toLowerCase())){case "top":this.placeAt(a.viewsHeaderNode,
"before");this._regFocusMgr("top");break;default:this.placeAt(a.viewsNode,"after"),this._regFocusMgr("bottom")}},_resetGridHeight:function(a,b){var c=this.grid,a=a||this._changeSize,b=b||this._resultSize;delete this._changeSize;delete this._resultSize;if(!c._autoHeight){var d=c._getPadBorder().h;if(!this.plugin.gh)this.plugin.gh=dojo.contentBox(c.domNode).h+2*d;b&&(a=b);if(a)this.plugin.gh=dojo.contentBox(c.domNode).h+2*d;var e=this.plugin.gh,f=c._getHeaderHeight(),h=dojo.marginBox(this.domNode).h,
h=this.plugin.paginators[1]?h*2:h;if(typeof c.autoHeight=="number")d=e+h-d,dojo.style(c.domNode,"height",d+"px"),dojo.style(c.viewsNode,"height",d-h-f+"px"),this._styleMsgNode(f,dojo.marginBox(c.viewsNode).w,d-h-f);else{var g=e-h-f-d;dojo.style(c.viewsNode,"height",g+"px");var i=dojo.some(c.views.views,function(a){return a.hasHScrollbar()});dojo.forEach(c.viewsNode.childNodes,function(a){dojo.style(a,"height",g+"px")});dojo.forEach(c.views.views,function(a){a.scrollboxNode&&(!a.hasHScrollbar()&&i?
dojo.style(a.scrollboxNode,"height",g-dojox.html.metrics.getScrollbar().h+"px"):dojo.style(a.scrollboxNode,"height",g+"px"))});this._styleMsgNode(f,dojo.marginBox(c.viewsNode).w,g)}}},_styleMsgNode:function(a,b,c){dojo.style(this.grid.messagesNode,{position:"absolute",top:a+"px",width:b+"px",height:c+"px","z-Index":"100"})},_updateDescription:function(){var a=this.plugin.forcePageStoreLayer;if(this.description&&this.descriptionDiv)this.descriptionDiv.innerHTML=this._maxItemSize>0?dojo.string.substitute(this.descTemplate,
[this.itemTitle,this._maxItemSize,a.startIdx+1,a.endIdx+1]):"0 "+this.itemTitle;this.descriptionWidth&&dojo.style(this.descriptionTd,"width",this.descriptionWidth)},_updateSizeSwitch:function(){if(this.sizeSwitchTd)if(!this.sizeSwitch||this._maxItemSize<=0)dojo.style(this.sizeSwitchTd,"display","none");else if(dojo.style(this.sizeSwitchTd,"display",""),!this.initializedSizeNode||this.pageSizeValue)this.sizeSwitchTd.childNodes.length<1&&this._createSizeSwitchNodes(),this._updateSwitchNodeClass(),this._moveToNextActivableNode(this._getAllPageSizeNodes(),
this.pageSizeValue),this.pageSizeValue=null},_createSizeSwitchNodes:function(){var a=null;if(this.pageSizes&&!(this.pageSizes.length<1))dojo.forEach(this.pageSizes,function(b){var b=dojo.trim(b),c=b.toLowerCase()=="all"?this.plugin.nls.allItemsLabelTemplate:dojo.string.substitute(this.plugin.nls.pageSizeLabelTemplate,[b]);a=dojo.create("span",{innerHTML:b,title:c,value:b,tabindex:0},this.sizeSwitchTd,"last");dijit.setWaiState(a,"label",c);this.plugin.connect(a,"onclick",dojo.hitch(this,"_onSwitchPageSize"));
this.plugin.connect(a,"onmouseover",function(a){dojo.addClass(a.target,"dojoxGridPageTextHover")});this.plugin.connect(a,"onmouseout",function(a){dojo.removeClass(a.target,"dojoxGridPageTextHover")});a=dojo.create("span",{innerHTML:"|"},this.sizeSwitchTd,"last");dojo.addClass(a,"dojoxGridSeparator")},this),dojo.destroy(a),this.initializedSizeNode=!0,this.sizeSwitchWidth&&dojo.style(this.sizeSwitchTd,"width",this.sizeSwitchWidth)},_updateSwitchNodeClass:function(){var a=null,b=!1,c=function(a,c){c?
(dojo.addClass(a,"dojoxGridActivedSwitch"),dojo.attr(a,"tabindex","-1"),b=!0):(dojo.addClass(a,"dojoxGridInactiveSwitch"),dojo.attr(a,"tabindex","0"))};dojo.forEach(this.sizeSwitchTd.childNodes,function(d){if(d.value)if(a=d.value,dojo.removeClass(d),this.pageSizeValue)c(d,a===this.pageSizeValue&&!b);else{if(a.toLowerCase()=="all")a=this._maxItemSize;c(d,this.currentPageSize===parseInt(a,10)&&!b)}},this)},_updatePageStepper:function(){if(this.pageStepperTd)!this.pageStepper||this._maxItemSize<=0?dojo.style(this.pageStepperTd,
"display","none"):(dojo.style(this.pageStepperTd,"display",""),this.pageStepperDiv.childNodes.length<1?(this._createPageStepNodes(),this._createWardBtns()):this._resetPageStepNodes(),this._updatePageStepNodeClass(),this._moveToNextActivableNode(this._getAllPageStepNodes(),this.pageStepValue),this.pageStepValue=null)},_createPageStepNodes:function(){for(var a=this._getStartPage(),b=this._getStepPageSize(),c="",d=null,e=a;e<this.maxPageStep+1;e++)c=dojo.string.substitute(this.plugin.nls.pageStepLabelTemplate,
[e+""]),d=dojo.create("div",{innerHTML:e,value:e,title:c,tabindex:e<a+b?0:-1},this.pageStepperDiv,"last"),dijit.setWaiState(d,"label",c),this.plugin.connect(d,"onclick",dojo.hitch(this,"_onPageStep")),this.plugin.connect(d,"onmouseover",function(a){dojo.addClass(a.target,"dojoxGridPageTextHover")}),this.plugin.connect(d,"onmouseout",function(a){dojo.removeClass(a.target,"dojoxGridPageTextHover")}),dojo.style(d,"display",e<a+b?"block":"none");this.pageStepperWidth&&dojo.style(this.pageStepperTd,"width",
this.pageStepperWidth)},_createWardBtns:function(){var a=this,b={prevPage:"&#60;",firstPage:"&#171;",nextPage:"&#62;",lastPage:"&#187;"},c=function(c,e,f){var h=dojo.create("div",{value:c,title:e,tabindex:1},a.pageStepperDiv,f);a.plugin.connect(h,"onclick",dojo.hitch(a,"_onPageStep"));dijit.setWaiState(h,"label",e);c=dojo.create("span",{value:c,title:e,innerHTML:b[c]},h,f);dojo.addClass(c,"dojoxGridWardButtonInner")};c("prevPage",this.plugin.nls.prevTip,"first");c("firstPage",this.plugin.nls.firstTip,
"first");c("nextPage",this.plugin.nls.nextTip,"last");c("lastPage",this.plugin.nls.lastTip,"last")},_resetPageStepNodes:function(){for(var a=this._getStartPage(),b=this._getStepPageSize(),c=this.pageStepperDiv.childNodes,d=null,e=a,f=2;f<c.length-2;f++,e++)d=c[f],e<a+b?(dojo.attr(d,"innerHTML",e),dojo.attr(d,"value",e),dojo.style(d,"display","block"),dijit.setWaiState(d,"label",dojo.string.substitute(this.plugin.nls.pageStepLabelTemplate,[e+""]))):dojo.style(d,"display","none")},_updatePageStepNodeClass:function(){var a=
null,b=this._getCurrentPageNo(),c=this._getPageCount(),d=function(a,b,c){var d=a.value,i=b?"dojoxGrid"+d+"Btn":"dojoxGridInactived",b=b?"dojoxGrid"+d+"BtnDisable":"dojoxGridActived";c?(dojo.addClass(a,b),dojo.attr(a,"tabindex","-1")):(dojo.addClass(a,i),dojo.attr(a,"tabindex","0"))};dojo.forEach(this.pageStepperDiv.childNodes,function(e){dojo.removeClass(e);isNaN(parseInt(e.value,10))?(dojo.addClass(e,"dojoxGridWardButton"),d(e,!0,b==(e.value=="prevPage"||e.value=="firstPage"?1:c))):(a=parseInt(e.value,
10),d(e,!1,a===b||dojo.style(e,"display")==="none"))},this)},_showGotoButton:function(a){this.gotoButton=a;this._updateGotoButton()},_updateGotoButton:function(){this.gotoButton?(this.gotoPageTd||this._createGotoNode(),dojo.toggleClass(this.gotoPageDiv,"dojoxGridPaginatorGotoDivDisabled",this.plugin.pageSize>=this.plugin._maxSize)):this.gotoPageTd&&(this._gotoPageDialog&&this._gotoPageDialog.destroy(),dojo.destroy(this.gotoPageDiv),dojo.destroy(this.gotoPageTd),delete this.gotoPageDiv,delete this.gotoPageTd)},
_createGotoNode:function(){this.gotoPageTd=dojo.create("td",{},dojo.query("tr",this.domNode)[0],"last");dojo.addClass(this.gotoPageTd,"dojoxGridPaginatorGotoTd");this.gotoPageDiv=dojo.create("div",{tabindex:"0",title:this.plugin.nls.gotoButtonTitle},this.gotoPageTd,"first");dojo.addClass(this.gotoPageDiv,"dojoxGridPaginatorGotoDiv");this.plugin.connect(this.gotoPageDiv,"onclick",dojo.hitch(this,"_openGotopageDialog"));var a=dojo.create("span",{title:this.plugin.nls.gotoButtonTitle,innerHTML:"&#8869;"},
this.gotoPageDiv,"last");dojo.addClass(a,"dojoxGridWardButtonInner")},_openGotopageDialog:function(a){if(!this._gotoPageDialog)this._gotoPageDialog=new dojox.grid.enhanced.plugins.pagination._GotoPageDialog(this.plugin);this._currentFocusNode?this._currentFocusNode=this.gotoPageDiv:this.grid.focus.focusArea("pagination"+this.position,a);if(this.focusArea!="pageStep")this.focusArea="pageStep";this._gotoPageDialog.updatePageCount();this._gotoPageDialog.showDialog()},_onFocusPaginator:function(a,b){return this._currentFocusNode?
b>0?this.focusArea==="pageSize"?this._onFocusPageStepNode(a):!1:b<0?this.focusArea==="pageStep"?this._onFocusPageSizeNode(a):!1:!1:b>0?this._onFocusPageSizeNode(a)?!0:this._onFocusPageStepNode(a):b<0?this._onFocusPageStepNode(a)?!0:this._onFocusPageSizeNode(a):!1},_onFocusPageSizeNode:function(a){var b=this._getPageSizeActivableNodes();return a&&a.type!=="click"?b[0]?(dijit.focus(b[0]),this._currentFocusNode=b[0],this.focusArea="pageSize",this.plugin._stopEvent(a),!0):!1:a&&a.type=="click"&&dojo.indexOf(this._getPageSizeActivableNodes(),
a.target)>-1?(this.focusArea="pageSize",this.plugin._stopEvent(a),!0):!1},_onFocusPageStepNode:function(a){var b=this._getPageStepActivableNodes();if(a&&a.type!=="click")return b[0]?(dijit.focus(b[0]),this._currentFocusNode=b[0],this.focusArea="pageStep",this.plugin._stopEvent(a),!0):this.gotoPageDiv?(dijit.focus(this.gotoPageDiv),this._currentFocusNode=this.gotoPageDiv,this.focusArea="pageStep",this.plugin._stopEvent(a),!0):!1;if(a&&a.type=="click")if(dojo.indexOf(this._getPageStepActivableNodes(),
a.target)>-1)return this.focusArea="pageStep",this.plugin._stopEvent(a),!0;else if(a.target==this.gotoPageDiv)return dijit.focus(this.gotoPageDiv),this._currentFocusNode=this.gotoPageDiv,this.focusArea="pageStep",this.plugin._stopEvent(a),!0;return!1},_onFocusGotoPageNode:function(a){if(!this.gotoButton||!this.gotoPageTd)return!1;if(a&&a.type!=="click"||a.type=="click"&&a.target==this.gotoPageDiv)dijit.focus(this.gotoPageDiv),this._currentFocusNode=this.gotoPageDiv,this.focusArea="gotoButton",this.plugin._stopEvent(a);
return!0},_onBlurPaginator:function(a,b){var c=this._getPageSizeActivableNodes(),d=this._getPageStepActivableNodes();if(b>0&&this.focusArea==="pageSize"&&(d.length>1||this.gotoButton))return!1;else if(b<0&&this.focusArea==="pageStep"&&c.length>1)return!1;this.focusArea=this._currentFocusNode=null;return!0},_onKeyDown:function(a,b){if(!b&&!a.altKey&&!a.metaKey){var c=dojo.keys;if(a.keyCode===c.ENTER||a.keyCode===c.SPACE)dojo.indexOf(this._getPageStepActivableNodes(),this._currentFocusNode)>-1?this._onPageStep(a):
dojo.indexOf(this._getPageSizeActivableNodes(),this._currentFocusNode)>-1?this._onSwitchPageSize(a):this._currentFocusNode===this.gotoPageDiv&&this._openGotopageDialog(a);this.plugin._stopEvent(a)}},_moveFocus:function(a,b,c){var d;this.focusArea=="pageSize"?d=this._getPageSizeActivableNodes():this.focusArea=="pageStep"&&(d=this._getPageStepActivableNodes(),this.gotoPageDiv&&d.push(this.gotoPageDiv));if(!(d.length<1)){a=dojo.indexOf(d,this._currentFocusNode)+b;if(a>=0&&a<d.length)dijit.focus(d[a]),
this._currentFocusNode=d[a];this.plugin._stopEvent(c)}},_getPageSizeActivableNodes:function(){return dojo.query("span[tabindex='0']",this.sizeSwitchTd)},_getPageStepActivableNodes:function(){return dojo.query("div[tabindex='0']",this.pageStepperDiv)},_getAllPageSizeNodes:function(){var a=[];dojo.forEach(this.sizeSwitchTd.childNodes,function(b){b.value&&a.push(b)});return a},_getAllPageStepNodes:function(){for(var a=[],b=0,c=this.pageStepperDiv.childNodes.length;b<c;b++)a.push(this.pageStepperDiv.childNodes[b]);
return a},_moveToNextActivableNode:function(a,b){if(b){a.length<2&&this.grid.focus.tab(1);var c=[],d=null,e=0;dojo.forEach(a,function(a){a.value==b?(c.push(a),d=a):dojo.attr(a,"tabindex")=="0"&&c.push(a)});c.length<2&&this.grid.focus.tab(1);e=dojo.indexOf(c,d);dojo.attr(d,"tabindex")!="0"&&(d=c[e+1]?c[e+1]:c[e-1]);dijit.focus(d);this._currentFocusNode=d}},_onSwitchPageSize:function(a){var b;if(b=this.pageSizeValue=a.target.value,a=b){if(dojo.trim(a.toLowerCase())=="all")a=this._maxItemSize,showAll=
!0;this.plugin.grid.usingPagination=!this.plugin.showAll;a=parseInt(a,10);if(!(isNaN(a)||a<=0)){this._currentFocusNode||this.grid.focus.currentArea("pagination"+this.position);if(this.focusArea!="pageSize")this.focusArea="pageSize";this.plugin.changePageSize(a)}}},_onPageStep:function(a){var b=this.plugin,c=this.pageStepValue=a.target.value;this._currentFocusNode||this.grid.focus.currentArea("pagination"+this.position);if(this.focusArea!="pageStep")this.focusArea="pageStep";if(isNaN(parseInt(c,10)))switch(a.target.value){case "prevPage":b.prevPage();
break;case "nextPage":b.nextPage();break;case "firstPage":b.gotoFirstPage();break;case "lastPage":b.gotoLastPage()}else b.gotoPage(c)},_getCurrentPageNo:function(){return this.plugin._currentPage+1},_getPageCount:function(){return!this._maxItemSize||!this.currentPageSize?0:Math.ceil(this._maxItemSize/this.currentPageSize)},_getStartPage:function(){var a=this._getCurrentPageNo(),b=parseInt(this.maxPageStep/2,10),c=this._getPageCount();return a<b||a-b<1?1:c<=this.maxPageStep?1:c-a<b&&a-this.maxPageStep>=
0?c-this.maxPageStep+1:a-b},_getStepPageSize:function(){var a=this._getStartPage(),b=this._getPageCount();return a+this.maxPageStep>b?b-a+1:this.maxPageStep}}),dojo.declare("dojox.grid.enhanced.plugins.pagination._GotoPageDialog",null,{pageCount:0,constructor:function(a){this.plugin=a;this.pageCount=this.plugin.paginators[0]._getPageCount();this._dialogNode=dojo.create("div",{},dojo.body(),"last");this._gotoPageDialog=new dojox.grid.enhanced.plugins.Dialog({refNode:a.grid.domNode,title:this.plugin.nls.dialogTitle},
this._dialogNode);this._createDialogContent();this._gotoPageDialog.startup()},_createDialogContent:function(){this._specifyNode=dojo.create("div",{innerHTML:this.plugin.nls.dialogIndication},this._gotoPageDialog.containerNode,"last");this._pageInputDiv=dojo.create("div",{},this._gotoPageDialog.containerNode,"last");this._pageTextBox=new dijit.form.NumberTextBox;this._pageTextBox.constraints={fractional:!1,min:1,max:this.pageCount};this.plugin.connect(this._pageTextBox.textbox,"onkeyup",dojo.hitch(this,
"_setConfirmBtnState"));this._pageInputDiv.appendChild(this._pageTextBox.domNode);this._pageLabel=dojo.create("label",{innerHTML:dojo.string.substitute(this.plugin.nls.pageCountIndication,[this.pageCount])},this._pageInputDiv,"last");this._buttonDiv=dojo.create("div",{},this._gotoPageDialog.containerNode,"last");this._confirmBtn=new dijit.form.Button({label:this.plugin.nls.dialogConfirm,onClick:dojo.hitch(this,this._onConfirm)});this._confirmBtn.set("disabled",!0);this._cancelBtn=new dijit.form.Button({label:this.plugin.nls.dialogCancel,
onClick:dojo.hitch(this,this._onCancel)});this._buttonDiv.appendChild(this._confirmBtn.domNode);this._buttonDiv.appendChild(this._cancelBtn.domNode);this._styleContent();this._gotoPageDialog.onCancel=dojo.hitch(this,this._onCancel);this.plugin.connect(this._gotoPageDialog,"_onKey",dojo.hitch(this,"_onKeyDown"))},_styleContent:function(){dojo.addClass(this._specifyNode,"dojoxGridDialogMargin");dojo.addClass(this._pageInputDiv,"dojoxGridDialogMargin");dojo.addClass(this._buttonDiv,"dojoxGridDialogButton");
dojo.style(this._pageTextBox.domNode,"width","50px")},updatePageCount:function(){this.pageCount=this.plugin.paginators[0]._getPageCount();this._pageTextBox.constraints={fractional:!1,min:1,max:this.pageCount};dojo.attr(this._pageLabel,"innerHTML",dojo.string.substitute(this.plugin.nls.pageCountIndication,[this.pageCount]))},showDialog:function(){this._gotoPageDialog.show()},_onConfirm:function(a){this._pageTextBox.isValid()&&this._pageTextBox.getDisplayedValue()!==""&&(this.plugin.gotoPage(this._pageTextBox.parse(this._pageTextBox.getDisplayedValue())),
this._gotoPageDialog.hide(),this._pageTextBox.reset());this.plugin._stopEvent(a)},_onCancel:function(a){this._pageTextBox.reset();this._gotoPageDialog.hide();this.plugin._stopEvent(a)},_onKeyDown:function(a){!a.altKey&&!a.metaKey&&a.keyCode===dojo.keys.ENTER&&this._onConfirm(a)},_setConfirmBtnState:function(){this._pageTextBox.isValid()&&this._pageTextBox.getDisplayedValue()!==""?this._confirmBtn.set("disabled",!1):this._confirmBtn.set("disabled",!0)},destroy:function(){this._pageTextBox.destroy();
this._confirmBtn.destroy();this._cancelBtn.destroy();this._gotoPageDialog.destroy();dojo.destroy(this._specifyNode);dojo.destroy(this._pageInputDiv);dojo.destroy(this._pageLabel);dojo.destroy(this._buttonDiv);dojo.destroy(this._dialogNode)}}),dojox.grid.EnhancedGrid.registerPlugin(dojox.grid.enhanced.plugins.Pagination));