/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.io.windowName"])dojo._hasResource["dojox.io.windowName"]=!0,dojo.provide("dojox.io.windowName"),dojox.io.windowName={send:function(i,a){a.url+=(a.url.match(/\?/)?"&":"?")+"windowname="+(a.authElement?"auth":!0);var h=a.authElement,l=function(a){try{var d=g.ioArgs.frame.contentWindow.document;d.write(" ");d.close()}catch(i){}(h||dojo.body()).removeChild(g.ioArgs.outerFrame);return a},g=dojo._ioSetArgs(a,l,l,l);a.timeout&&setTimeout(function(){g.fired==-1&&g.callback(Error("Timeout"))},
a.timeout);var d=dojox.io.windowName;dojo.body()?d._send(g,i,h,a.onAuthLoad):dojo.addOnLoad(function(){d._send(g,i,h,a.onAuthLoad)});return g},_send:function(i,a,h,l){function g(a){a.style.width="100%";a.style.height="100%";a.style.border="0px"}var d=i.ioArgs,k=dojox.io.windowName._frameNum++,p=(dojo.config.dojoBlankHtmlUrl||dojo.config.dojoCallbackUrl||dojo.moduleUrl("dojo","resources/blank.html"))+"#"+k,m=new dojo._Url(window.location,p),e=dojo.doc,f=h||dojo.body();if(dojo.isMoz&&![].reduce){var b=
e.createElement("iframe");g(b);if(!h)b.style.display="none";f.appendChild(b);f=b.contentWindow;e=f.document;e.write("<html><body margin='0px'><iframe style='width:100%;height:100%;border:0px' name='protectedFrame'></iframe></body></html>");e.close();e=f[0];f.__defineGetter__(0,function(){});f.__defineGetter__("protectedFrame",function(){});e=e.document;e.write("<html><body margin='0px'></body></html>");e.close();f=e.body}var c;if(dojo.isIE){var j=e.createElement("div");j.innerHTML='<iframe name="'+
m+'" onload="dojox.io.windowName['+k+']()">';c=j.firstChild}else c=e.createElement("iframe");d.frame=c;g(c);d.outerFrame=b=b||c;if(!h)b.style.display="none";var n=0;dojox.io.windowName[k]=c.onload=function(){try{if(!dojo.isMoz&&c.contentWindow.location=="about:blank")return}catch(a){}if(!n)n=1,h?l&&l():c.contentWindow.location=p;try{if(n<2){var b=c.contentWindow.name;if(typeof b=="string"&&b!=m)n=2,i.ioArgs.hash=c.contentWindow.location.hash,i.callback(b)}}catch(d){}};c.name=m;if(a.match(/GET/i))dojo._ioAddQueryToUrl(d),
c.src=d.url,f.appendChild(c),c.contentWindow&&c.contentWindow.location.replace(d.url);else if(a.match(/POST/i)){f.appendChild(c);a=dojo.doc.createElement("form");dojo.body().appendChild(a);var k=dojo.queryToObject(d.query),o;for(o in k){b=k[o];b=b instanceof Array?b:[b];for(f=0;f<b.length;f++)j=e.createElement("input"),j.type="hidden",j.name=o,j.value=b[f],a.appendChild(j)}a.method="POST";a.action=d.url;a.target=m;a.submit();a.parentNode.removeChild(a)}else throw Error("Method "+a+" not supported with the windowName transport");
if(c.contentWindow)c.contentWindow.name=m},_frameNum:0};