/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.form.uploader.plugins.Flash"]||(dojo._hasResource["dojox.form.uploader.plugins.Flash"]=!0,dojo.provide("dojox.form.uploader.plugins.Flash"),dojo.require("dojox.form.uploader.plugins.HTML5"),dojo.require("dojox.embed.flashVars"),dojo.require("dojox.embed.Flash"),dojo.declare("dojox.form.uploader.plugins.Flash",[],{swfPath:dojo.config.uploaderPath||dojo.moduleUrl("dojox.form","resources/uploader.swf"),skipServerCheck:!0,serverTimeout:2E3,isDebug:!1,devMode:!1,deferredUploading:0,
force:"",postMixInProperties:function(){if(!this.supports("multiple"))this.uploadType="flash",this._files=[],this._fileMap={},this._createInput=this._createFlashUploader,this.getFileList=this.getFlashFileList,this.reset=this.flashReset,this.upload=this.uploadFlash,this.submit=this.submitFlash,this.fieldname="flashUploadFiles";this.inherited(arguments)},onReady:function(){},onLoad:function(){},onFileChange:function(){},onFileProgress:function(){},getFlashFileList:function(){return this._files},flashReset:function(){this.flashMovie.reset();
this._files=[]},uploadFlash:function(){this.onBegin(this.getFileList());this.flashMovie.doUpload()},submitFlash:function(a){this.onBegin(this.getFileList());this.flashMovie.doUpload(a)},_change:function(a){this._files=this._files.concat(a);dojo.forEach(a,function(a){a.bytesLoaded=0;a.bytesTotal=a.size;this._fileMap[a.name+"_"+a.size]=a},this);this.onChange(this._files);this.onFileChange(a)},_complete:function(a){this._getCustomEvent().type="load";this.onComplete(a)},_progress:function(a){this._fileMap[a.name+
"_"+a.bytesTotal].bytesLoaded=a.bytesLoaded;var b=this._getCustomEvent();this.onFileProgress(a);this.onProgress(b)},_error:function(a){this.onError(a)},_onFlashBlur:function(){},_getCustomEvent:function(){var a={bytesLoaded:0,bytesTotal:0,type:"progress",timeStamp:(new Date).getTime()},b;for(b in this._fileMap)a.bytesTotal+=this._fileMap[b].bytesTotal,a.bytesLoaded+=this._fileMap[b].bytesLoaded;a.decimal=a.bytesLoaded/a.bytesTotal;a.percent=Math.ceil(a.bytesLoaded/a.bytesTotal*100)+"%";return a},
_connectFlash:function(){this._subs=[];this._cons=[];var a=dojo.hitch(this,function(a,c){this._subs.push(dojo.subscribe(this.id+a,this,c))});a("/filesSelected","_change");a("/filesUploaded","_complete");a("/filesProgress","_progress");a("/filesError","_error");a("/filesCanceled","onCancel");a("/stageBlur","_onFlashBlur");a=dojo.hitch(this,function(a,c){this._cons.push(dojo.subscribe(this.id+a,this,function(){this.button._cssMouseEvent({type:c})}))});a("/up","mouseup");a("/down","mousedown");a("/over",
"mouseover");a("/out","mouseout");this.connect(this.domNode,"focus",function(){this.flashMovie.focus();this.flashMovie.doFocus()});this.tabIndex>=0&&dojo.attr(this.domNode,"tabIndex",this.tabIndex)},_createFlashUploader:function(){var a=this.getUrl();if(a){if(a.toLowerCase().indexOf("http")<0&&a.indexOf("/")!=0){var b=window.location.href.split("/");b.pop();b=b.join("/")+"/";a=b+a}}else console.warn("Warning: no uploadUrl provided.");this.inputNode=dojo.create("div",{className:"dojoxFlashNode"},this.domNode,
"first");dojo.style(this.inputNode,{position:"absolute",top:"-2px",width:this.btnSize.w+"px",height:this.btnSize.h+"px",opacity:0});var b=this.btnSize.w,c=this.btnSize.h,a={expressInstall:!0,path:(this.swfPath.uri||this.swfPath)+"?cb_"+(new Date).getTime(),width:b,height:c,allowScriptAccess:"always",allowNetworking:"all",vars:{uploadDataFieldName:this.flashFieldName||this.name+"Flash",uploadUrl:a,uploadOnSelect:this.uploadOnSelect,deferredUploading:this.deferredUploading||0,selectMultipleFiles:this.multiple,
id:this.id,isDebug:this.isDebug,noReturnCheck:this.skipServerCheck,serverTimeout:this.serverTimeout},params:{scale:"noscale",wmode:"transparent",wmode:"opaque",allowScriptAccess:"always",allowNetworking:"all"}};this.flashObject=new dojox.embed.Flash(a,this.inputNode);this.flashObject.onError=dojo.hitch(function(a){console.error("Flash Error: "+a)});this.flashObject.onReady=dojo.hitch(this,function(){this.onReady(this)});this.flashObject.onLoad=dojo.hitch(this,function(a){this.flashMovie=a;this.flashReady=
!0;this.onLoad(this)});this._connectFlash()}}),dojox.form.addUploaderPlugin(dojox.form.uploader.plugins.Flash));