/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.form.uploader.plugins.HTML5"]||(dojo._hasResource["dojox.form.uploader.plugins.HTML5"]=!0,dojo.provide("dojox.form.uploader.plugins.HTML5"),dojo.declare("dojox.form.uploader.plugins.HTML5",[],{errMsg:"Error uploading files. Try checking permissions",uploadType:"html5",postCreate:function(){this.connectForm();this.inherited(arguments);this.uploadOnSelect&&this.connect(this,"onChange","upload")},upload:function(a){this.onBegin(this.getFileList());this.supports("FormData")?this.uploadWithFormData(a):
this.supports("sendAsBinary")&&this.sendAsBinary(a)},submit:function(a){a=a?a.tagName?a:this.getForm():this.getForm();a=dojo.formToObject(a);console.log("form data:",a);this.upload(a)},sendAsBinary:function(a){if(this.getUrl()){var b="---------------------------"+(new Date).getTime(),c=this.createXhr();c.setRequestHeader("Content-Type","multipart/form-data; boundary="+b);if(a=this._buildRequestBody(a,b))c.sendAsBinary(a);else this.onError(this.errMsg)}else console.error("No upload url found.",this)},
uploadWithFormData:function(a){if(this.getUrl()){var b=new FormData;dojo.forEach(this.inputNode.files,function(a){b.append(this.name+"s[]",a)},this);if(a)for(var c in a)b.append(c,a[c]);this.createXhr().send(b)}else console.error("No upload url found.",this)},_xhrProgress:function(a){if(a.lengthComputable){var b={bytesLoaded:a.loaded,bytesTotal:a.total,type:a.type,timeStamp:a.timeStamp};a.type=="load"?(b.percent="100%",b.decimal=1):(b.decimal=a.loaded/a.total,b.percent=Math.ceil(a.loaded/a.total*
100)+"%");this.onProgress(b)}},createXhr:function(){var a=new XMLHttpRequest,b;a.upload.addEventListener("progress",dojo.hitch(this,"_xhrProgress"),!1);a.addEventListener("load",dojo.hitch(this,"_xhrProgress"),!1);a.addEventListener("error",dojo.hitch(this,function(a){this.onError(a);clearInterval(b)}),!1);a.addEventListener("abort",dojo.hitch(this,function(a){this.onAbort(a);clearInterval(b)}),!1);a.onreadystatechange=dojo.hitch(this,function(){a.readyState===4&&(console.info("COMPLETE"),clearInterval(b),
this.onComplete(dojo.eval(a.responseText)))});a.open("POST",this.getUrl());b=setInterval(dojo.hitch(this,function(){}),250);return a},_buildRequestBody:function(a,b){var c="",b="--"+b,d=[];dojo.forEach(this.inputNode.files,function(a,f){var e=this.name+"s[]",g=this.inputNode.files[f].fileName,h;try{h=this.inputNode.files[f].getAsBinary()+"\r\n",c+=b+"\r\n",c+="Content-Disposition: form-data; ",c+='name="'+e+'"; ',c+='filename="'+g+'"\r\n',c+="Content-Type: "+this.getMimeType()+"\r\n\r\n",c+=h}catch(i){d.push({index:f,
name:g})}},this);d.length&&d.length>=this.inputNode.files.length&&(this.onError({message:this.errMsg,filesInError:d}),c=!1);if(!c)return!1;if(a)for(var e in a)c+=b+"\r\n",c+="Content-Disposition: form-data; ",c+='name="'+e+'"\r\n\r\n',c+=a[e]+"\r\n";c+=b+"--\r\n";return c}}),dojox.form.addUploaderPlugin(dojox.form.uploader.plugins.HTML5));