/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.date.buddhist.Date"])dojo._hasResource["dojox.date.buddhist.Date"]=!0,dojo.provide("dojox.date.buddhist.Date"),dojo.experimental("dojox.date.buddhist.Date"),dojo.declare("dojox.date.buddhist.Date",null,{_date:0,_month:0,_year:0,_hours:0,_minutes:0,_seconds:0,_milliseconds:0,_day:0,constructor:function(){var a=arguments.length;if(a)if(a==1)a=arguments[0],typeof a=="number"&&(a=new Date(a)),a instanceof Date?this.fromGregorian(a):a==""?this._date=new Date(""):(this._year=
a._year,this._month=a._month,this._date=a._date,this._hours=a._hours,this._minutes=a._minutes,this._seconds=a._seconds,this._milliseconds=a._milliseconds);else{if(a>=3){this._year+=arguments[0];this._month+=arguments[1];this._date+=arguments[2];if(this._month>11)console.warn("the month is incorrect , set 0"),this._month=0;this._hours+=arguments[3]||0;this._minutes+=arguments[4]||0;this._seconds+=arguments[5]||0;this._milliseconds+=arguments[6]||0}}else this.fromGregorian(new Date)},getDate:function(){return parseInt(this._date)},
getMonth:function(){return parseInt(this._month)},getFullYear:function(){return parseInt(this._year)},getHours:function(){return this._hours},getMinutes:function(){return this._minutes},getSeconds:function(){return this._seconds},getMilliseconds:function(){return this._milliseconds},setDate:function(a){a=parseInt(a);if(!(a>0&&a<=this._getDaysInMonth(this._month,this._year))){var b;if(a>0)for(b=this._getDaysInMonth(this._month,this._year);a>b;a-=b,b=this._getDaysInMonth(this._month,this._year))this._month++,
this._month>=12&&(this._year++,this._month-=12);else for(b=this._getDaysInMonth(this._month-1>=0?this._month-1:11,this._month-1>=0?this._year:this._year-1);a<=0;b=this._getDaysInMonth(this._month-1>=0?this._month-1:11,this._month-1>=0?this._year:this._year-1))this._month--,this._month<0&&(this._year--,this._month+=12),a+=b}this._date=a;return this},setFullYear:function(a){this._year=parseInt(a)},setMonth:function(a){this._year+=Math.floor(a/12);for(this._month=Math.floor(a%12);this._month<0;this._month+=
12);},setHours:function(){var a=arguments.length,b=0;a>=1&&(b=parseInt(arguments[0]));if(a>=2)this._minutes=parseInt(arguments[1]);if(a>=3)this._seconds=parseInt(arguments[2]);if(a==4)this._milliseconds=parseInt(arguments[3]);for(;b>=24;)this._date++,a=this._getDaysInMonth(this._month,this._year),this._date>a&&(this._month++,this._month>=12&&(this._year++,this._month-=12),this._date-=a),b-=24;this._hours=b},setMinutes:function(a){for(;a>=60;){this._hours++;if(this._hours>=24){this._date++;this._hours-=
24;var b=this._getDaysInMonth(this._month,this._year);this._date>b&&(this._month++,this._month>=12&&(this._year++,this._month-=12),this._date-=b)}a-=60}this._minutes=a},setSeconds:function(a){for(;a>=60;){this._minutes++;if(this._minutes>=60&&(this._hours++,this._minutes-=60,this._hours>=24)){this._date++;this._hours-=24;var b=this._getDaysInMonth(this._month,this._year);this._date>b&&(this._month++,this._month>=12&&(this._year++,this._month-=12),this._date-=b)}a-=60}this._seconds=a},setMilliseconds:function(a){for(;a>=
1E3;){this.setSeconds++;if(this.setSeconds>=60&&(this._minutes++,this.setSeconds-=60,this._minutes>=60&&(this._hours++,this._minutes-=60,this._hours>=24))){this._date++;this._hours-=24;var b=this._getDaysInMonth(this._month,this._year);this._date>b&&(this._month++,this._month>=12&&(this._year++,this._month-=12),this._date-=b)}a-=1E3}this._milliseconds=a},toString:function(){return this._date+", "+this._month+", "+this._year+"  "+this._hours+":"+this._minutes+":"+this._seconds},_getDaysInMonth:function(a,
b){return dojo.date.getDaysInMonth(new Date(b-543,a))},fromGregorian:function(a){a=new Date(a);this._date=a.getDate();this._month=a.getMonth();this._year=a.getFullYear()+543;this._hours=a.getHours();this._minutes=a.getMinutes();this._seconds=a.getSeconds();this._milliseconds=a.getMilliseconds();this._day=a.getDay();return this},toGregorian:function(){return new Date(this._year-543,this._month,this._date,this._hours,this._minutes,this._seconds,this._milliseconds)},getDay:function(){return this.toGregorian().getDay()}}),
dojox.date.buddhist.Date.prototype.valueOf=function(){return this.toGregorian().valueOf()};