/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.date.buddhist.locale"])dojo._hasResource["dojox.date.buddhist.locale"]=!0,dojo.provide("dojox.date.buddhist.locale"),dojo.experimental("dojox.date.buddhist.locale"),dojo.require("dojox.date.buddhist.Date"),dojo.require("dojo.regexp"),dojo.require("dojo.string"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojo.cldr","buddhist",null,"ROOT,ar,da,de,el,en,en-gb,es,fi,ro,th,zh-hant"),function(){function i(b,e,c,h,g){return g.replace(/([a-z])\1*/ig,function(d){var a,
f,c=d.charAt(0),d=d.length,l=["abbr","wide","narrow"];switch(c){case "G":a=e.eraAbbr[0];break;case "y":a=String(b.getFullYear());break;case "M":a=b.getMonth();d<3?(a+=1,f=!0):(c=["months-format",l[d-3]].join("-"),a=e[c][a]);break;case "d":a=b.getDate(!0);f=!0;break;case "E":a=b.getDay();d<3?(a+=1,f=!0):(c=["days-format",l[d-3]].join("-"),a=e[c][a]);break;case "a":a=b.getHours()<12?"am":"pm";a=e["dayPeriods-format-wide-"+a];break;case "h":case "H":case "K":case "k":f=b.getHours();switch(c){case "h":a=
f%12||12;break;case "H":a=f;break;case "K":a=f%12;break;case "k":a=f||24}f=!0;break;case "m":a=b.getMinutes();f=!0;break;case "s":a=b.getSeconds();f=!0;break;case "S":a=Math.round(b.getMilliseconds()*Math.pow(10,d-3));f=!0;break;case "z":if(a=dojo.date.getTimezoneName(b.toGregorian()))break;d=4;case "Z":a=b.toGregorian().getTimezoneOffset();a=[a<=0?"+":"-",dojo.string.pad(Math.floor(Math.abs(a)/60),2),dojo.string.pad(Math.abs(a)%60,2)];d==4&&(a.splice(0,0,"GMT"),a.splice(3,0,":"));a=a.join("");break;
default:throw Error("dojox.date.buddhist.locale.formatPattern: invalid pattern char: "+g);}f&&(a=dojo.string.pad(a,d));return a})}function k(b,e,c,h){var g=function(a){return a},e=e||g,c=c||g,h=h||g,d=b.match(/(''|[^'])+/g),a=b.charAt(0)=="'";dojo.forEach(d,function(b,g){b?(d[g]=(a?c:e)(b),a=!a):d[g]=""});return h(d.join(""))}function j(b,e,c,h){h=dojo.regexp.escapeString(h);dojo.i18n.normalizeLocale(c.locale);return h.replace(/([a-z])\1*/ig,function(g){var d;d=g.charAt(0);var a=g.length,f="";c.strict?
a>1&&(f="0{"+(a-1)+"}"):f="0?";switch(d){case "y":d="\\d+";break;case "M":d=a>2?"\\S+":f+"[1-9]|1[0-2]";break;case "d":d="[12]\\d|"+f+"[1-9]|3[01]";break;case "E":d="\\S+";break;case "h":d=f+"[1-9]|1[0-2]";break;case "k":d=f+"\\d|1[01]";break;case "H":d=f+"\\d|1\\d|2[0-3]";break;case "K":d=f+"[1-9]|1\\d|2[0-4]";break;case "m":case "s":d=f+"\\d|[0-5]\\d";break;case "S":d="\\d{"+a+"}";break;case "a":a=c.am||e["dayPeriods-format-wide-am"];f=c.pm||e["dayPeriods-format-wide-pm"];c.strict?d=a+"|"+f:(d=
a+"|"+f,a!=a.toLowerCase()&&(d+="|"+a.toLowerCase()),f!=f.toLowerCase()&&(d+="|"+f.toLowerCase()));break;default:d=".*"}b&&b.push(g);return"("+d+")"}).replace(/[\xa0 ]/g,"[\\s\\xa0]")}dojox.date.buddhist.locale.format=function(b,e){var e=e||{},c=dojo.i18n.normalizeLocale(e.locale),h=e.formatLength||"short",g=dojox.date.buddhist.locale._getBuddhistBundle(c),d=[],c=dojo.hitch(this,i,b,g,c,e.fullYear);if(e.selector=="year")return b.getFullYear();if(e.selector!="time"){var a=e.datePattern||g["dateFormat-"+
h];a&&d.push(k(a,c))}e.selector!="date"&&(h=e.timePattern||g["timeFormat-"+h])&&d.push(k(h,c));return d.join(" ")};dojox.date.buddhist.locale.regexp=function(b){return dojox.date.buddhist.locale._parseInfo(b).regexp};dojox.date.buddhist.locale._parseInfo=function(b){var b=b||{},e=dojo.i18n.normalizeLocale(b.locale),e=dojox.date.buddhist.locale._getBuddhistBundle(e),c=b.formatLength||"short",h=b.datePattern||e["dateFormat-"+c],c=b.timePattern||e["timeFormat-"+c],g=[];return{regexp:k(b.selector=="date"?
h:b.selector=="time"?c:typeof c=="undefined"?h:h+" "+c,dojo.hitch(this,j,g,e,b)),tokens:g,bundle:e}};dojox.date.buddhist.locale.parse=function(b,e){b=b.replace(/[\u200E\u200F\u202A-\u202E]/g,"");e||(e={});var c=dojox.date.buddhist.locale._parseInfo(e),h=c.tokens,g=c.bundle,c=RegExp("^"+c.regexp+"$"),d=c.exec(b);dojo.i18n.normalizeLocale(e.locale);if(!d)return console.debug("dojox.date.buddhist.locale.parse: value  "+b+" doesn't match pattern   "+c),null;var a=[2513,0,1,0,0,0,0],f="",j=["abbr","wide",
"narrow"];dojo.every(d,function(b,d){if(!d)return!0;var c=h[d-1],i=c.length;switch(c.charAt(0)){case "y":a[0]=Number(b);break;case "M":if(i>2){if(c=g["months-format-"+j[i-3]].concat(),e.strict||(b=b.replace(".","").toLowerCase(),c=dojo.map(c,function(a){return a?a.replace(".","").toLowerCase():a})),b=dojo.indexOf(c,b),b==-1)return!1}else b--;a[1]=Number(b);break;case "D":a[1]=0;case "d":a[2]=Number(b);break;case "a":c=e.am||g["dayPeriods-format-wide-am"];i=e.pm||g["dayPeriods-format-wide-pm"];if(!e.strict)var k=
/\./g,b=b.replace(k,"").toLowerCase(),c=c.replace(k,"").toLowerCase(),i=i.replace(k,"").toLowerCase();if(e.strict&&b!=c&&b!=i)return!1;f=b==i?"p":b==c?"a":"";break;case "K":b==24&&(b=0);case "h":case "H":case "k":a[3]=Number(b);break;case "m":a[4]=Number(b);break;case "s":a[5]=Number(b);break;case "S":a[6]=Number(b)}return!0});c=+a[3];f==="p"&&c<12?a[3]=c+12:f==="a"&&c==12&&(a[3]=0);return new dojox.date.buddhist.Date(a[0],a[1],a[2],a[3],a[4],a[5],a[6])}}(),function(){var i=[];dojox.date.buddhist.locale.addCustomFormats=
function(k,j){i.push({pkg:k,name:j})};dojox.date.buddhist.locale._getBuddhistBundle=function(k){var j={};dojo.forEach(i,function(b){b=dojo.i18n.getLocalization(b.pkg,b.name,k);j=dojo.mixin(j,b)},this);return j}}(),dojox.date.buddhist.locale.addCustomFormats("dojo.cldr","buddhist"),dojox.date.buddhist.locale.getNames=function(i,k,j,b){var e,b=dojox.date.buddhist.locale._getBuddhistBundle(b),i=[i,j,k];j=="standAlone"&&(j=i.join("-"),e=b[j],e[0]==1&&(e=void 0));i[1]="format";return(e||b[i.join("-")]).concat()};