/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojo.date.locale"])dojo._hasResource["dojo.date.locale"]=!0,dojo.provide("dojo.date.locale"),dojo.require("dojo.date"),dojo.require("dojo.cldr.supplemental"),dojo.require("dojo.regexp"),dojo.require("dojo.string"),dojo.require("dojo.i18n"),dojo.requireLocalization("dojo.cldr","gregorian",null,"ROOT,ar,ca,cs,da,de,el,en,en-au,en-ca,en-gb,es,fi,fr,fr-ch,he,hu,it,ja,ko,nb,nl,pl,pt,pt-pt,ro,ru,sk,sl,sv,th,tr,zh,zh-hant,zh-hk,zh-tw"),dojo.getObject("date.locale",!0,dojo),function(){function j(a,
d,c,f){return f.replace(/([a-z])\1*/ig,function(k){var b,g,e=k.charAt(0),k=k.length,h=["abbr","wide","narrow"];switch(e){case "G":b=d[k<4?"eraAbbr":"eraNames"][a.getFullYear()<0?0:1];break;case "y":b=a.getFullYear();switch(k){case 1:break;case 2:if(!c.fullYear){b=String(b);b=b.substr(b.length-2);break}default:g=!0}break;case "Q":case "q":b=Math.ceil((a.getMonth()+1)/3);g=!0;break;case "M":b=a.getMonth();k<3?(b+=1,g=!0):(e=["months-format",h[k-3]].join("-"),b=d[e][b]);break;case "w":b=dojo.date.locale._getWeekOfYear(a,
0);g=!0;break;case "d":b=a.getDate();g=!0;break;case "D":b=dojo.date.locale._getDayOfYear(a);g=!0;break;case "E":b=a.getDay();k<3?(b+=1,g=!0):(e=["days-format",h[k-3]].join("-"),b=d[e][b]);break;case "a":b=a.getHours()<12?"am":"pm";b=c[b]||d["dayPeriods-format-wide-"+b];break;case "h":case "H":case "K":case "k":g=a.getHours();switch(e){case "h":b=g%12||12;break;case "H":b=g;break;case "K":b=g%12;break;case "k":b=g||24}g=!0;break;case "m":b=a.getMinutes();g=!0;break;case "s":b=a.getSeconds();g=!0;
break;case "S":b=Math.round(a.getMilliseconds()*Math.pow(10,k-3));g=!0;break;case "v":case "z":if(b=dojo.date.locale._getZone(a,!0,c))break;k=4;case "Z":b=dojo.date.locale._getZone(a,!1,c);b=[b<=0?"+":"-",dojo.string.pad(Math.floor(Math.abs(b)/60),2),dojo.string.pad(Math.abs(b)%60,2)];k==4&&(b.splice(0,0,"GMT"),b.splice(3,0,":"));b=b.join("");break;default:throw Error("dojo.date.locale.format: invalid pattern char: "+f);}g&&(b=dojo.string.pad(b,k));return b})}function i(a,d,c,f){var k=function(b){return b},
d=d||k,c=c||k,f=f||k,b=a.match(/(''|[^'])+/g),g=a.charAt(0)=="'";dojo.forEach(b,function(a,f){a?(b[f]=(g?c:d)(a.replace(/''/g,"'")),g=!g):b[f]=""});return f(b.join(""))}function h(a,d,c,f){f=dojo.regexp.escapeString(f);c.strict||(f=f.replace(" a"," ?a"));return f.replace(/([a-z])\1*/ig,function(f){var b;b=f.charAt(0);var g=f.length,e="",h="";c.strict?(g>1&&(e="0{"+(g-1)+"}"),g>2&&(h="0{"+(g-2)+"}")):(e="0?",h="0{0,2}");switch(b){case "y":b="\\d{2,4}";break;case "M":b=g>2?"\\S+?":"1[0-2]|"+e+"[1-9]";
break;case "D":b="[12][0-9][0-9]|3[0-5][0-9]|36[0-6]|"+h+"[1-9][0-9]|"+e+"[1-9]";break;case "d":b="3[01]|[12]\\d|"+e+"[1-9]";break;case "w":b="[1-4][0-9]|5[0-3]|"+e+"[1-9]";break;case "E":b="\\S+";break;case "h":b="1[0-2]|"+e+"[1-9]";break;case "k":b="1[01]|"+e+"\\d";break;case "H":b="1\\d|2[0-3]|"+e+"\\d";break;case "K":b="1\\d|2[0-4]|"+e+"[1-9]";break;case "m":case "s":b="[0-5]\\d";break;case "S":b="\\d{"+g+"}";break;case "a":g=c.am||d["dayPeriods-format-wide-am"];e=c.pm||d["dayPeriods-format-wide-pm"];
b=g+"|"+e;c.strict||(g!=g.toLowerCase()&&(b+="|"+g.toLowerCase()),e!=e.toLowerCase()&&(b+="|"+e.toLowerCase()),b.indexOf(".")!=-1&&(b+="|"+b.replace(/\./g,"")));b=b.replace(/\./g,"\\.");break;default:b=".*"}a&&a.push(f);return"("+b+")"}).replace(/[\xa0 ]/g,"[\\s\\xa0]")}dojo.date.locale._getZone=function(a,d){return d?dojo.date.getTimezoneName(a):a.getTimezoneOffset()};dojo.date.locale.format=function(a,d){var d=d||{},c=dojo.i18n.normalizeLocale(d.locale),f=d.formatLength||"short",c=dojo.date.locale._getGregorianBundle(c),
h=[],b=dojo.hitch(this,j,a,c,d);if(d.selector=="year")return i(c["dateFormatItem-yyyy"]||"yyyy",b);var g;d.selector!="date"&&(g=d.timePattern||c["timeFormat-"+f])&&h.push(i(g,b));d.selector!="time"&&(g=d.datePattern||c["dateFormat-"+f])&&h.push(i(g,b));return h.length==1?h[0]:c["dateTimeFormat-"+f].replace(/\{(\d+)\}/g,function(b,a){return h[a]})};dojo.date.locale.regexp=function(a){return dojo.date.locale._parseInfo(a).regexp};dojo.date.locale._parseInfo=function(a){var a=a||{},d=dojo.i18n.normalizeLocale(a.locale),
d=dojo.date.locale._getGregorianBundle(d),c=a.formatLength||"short",f=a.datePattern||d["dateFormat-"+c],k=a.timePattern||d["timeFormat-"+c],c=a.selector=="date"?f:a.selector=="time"?k:d["dateTimeFormat-"+c].replace(/\{(\d+)\}/g,function(b,a){return[k,f][a]}),b=[];return{regexp:i(c,dojo.hitch(this,h,b,d,a)),tokens:b,bundle:d}};dojo.date.locale.parse=function(a,d){var c=/[\u200E\u200F\u202A\u202E]/g,f=dojo.date.locale._parseInfo(d),h=f.tokens,b=f.bundle,c=RegExp("^"+f.regexp.replace(c,"")+"$",f.strict?
"":"i").exec(a&&a.replace(c,""));if(!c)return null;var g=["abbr","wide","narrow"],e=[1970,0,1,0,0,0,0],j="",c=dojo.every(c,function(a,f){if(!f)return!0;var c=h[f-1],i=c.length;switch(c.charAt(0)){case "y":if(i!=2&&d.strict)e[0]=a;else if(a<100)a=Number(a),i=""+(new Date).getFullYear(),c=i.substring(0,2)*100,i=Math.min(Number(i.substring(2,4))+20,99),e[0]=a<i?c+a:c-100+a;else{if(d.strict)return!1;e[0]=a}break;case "M":if(i>2){if(c=b["months-format-"+g[i-3]].concat(),d.strict||(a=a.replace(".","").toLowerCase(),
c=dojo.map(c,function(a){return a.replace(".","").toLowerCase()})),a=dojo.indexOf(c,a),a==-1)return!1}else a--;e[1]=a;break;case "E":case "e":c=b["days-format-"+g[i-3]].concat();d.strict||(a=a.toLowerCase(),c=dojo.map(c,function(a){return a.toLowerCase()}));a=dojo.indexOf(c,a);if(a==-1)return!1;break;case "D":e[1]=0;case "d":e[2]=a;break;case "a":c=d.am||b["dayPeriods-format-wide-am"];i=d.pm||b["dayPeriods-format-wide-pm"];if(!d.strict)var l=/\./g,a=a.replace(l,"").toLowerCase(),c=c.replace(l,"").toLowerCase(),
i=i.replace(l,"").toLowerCase();if(d.strict&&a!=c&&a!=i)return!1;j=a==i?"p":a==c?"a":"";break;case "K":a==24&&(a=0);case "h":case "H":case "k":if(a>23)return!1;e[3]=a;break;case "m":e[4]=a;break;case "s":e[5]=a;break;case "S":e[6]=a}return!0}),f=+e[3];j==="p"&&f<12?e[3]=f+12:j==="a"&&f==12&&(e[3]=0);f=new Date(e[0],e[1],e[2],e[3],e[4],e[5],e[6]);d.strict&&f.setFullYear(e[0]);var i=h.join(""),m=i.indexOf("d")!=-1,i=i.indexOf("M")!=-1;if(!c||i&&f.getMonth()>e[1]||m&&f.getDate()>e[2])return null;if(i&&
f.getMonth()<e[1]||m&&f.getDate()<e[2])f=dojo.date.add(f,"hour",1);return f}}(),function(){var j=[];dojo.date.locale.addCustomFormats=function(i,h){j.push({pkg:i,name:h})};dojo.date.locale._getGregorianBundle=function(i){var h={};dojo.forEach(j,function(a){a=dojo.i18n.getLocalization(a.pkg,a.name,i);h=dojo.mixin(h,a)},this);return h}}(),dojo.date.locale.addCustomFormats("dojo.cldr","gregorian"),dojo.date.locale.getNames=function(j,i,h,a){var d,a=dojo.date.locale._getGregorianBundle(a),j=[j,h,i];h==
"standAlone"&&(h=j.join("-"),d=a[h],d[0]==1&&(d=void 0));j[1]="format";return(d||a[j.join("-")]).concat()},dojo.date.locale.isWeekend=function(j,i){var h=dojo.cldr.supplemental.getWeekend(i),a=(j||new Date).getDay();h.end<h.start&&(h.end+=7,a<h.start&&(a+=7));return a>=h.start&&a<=h.end},dojo.date.locale._getDayOfYear=function(j){return dojo.date.difference(new Date(j.getFullYear(),0,1,j.getHours()),j)+1},dojo.date.locale._getWeekOfYear=function(j,i){arguments.length==1&&(i=0);var h=(new Date(j.getFullYear(),
0,1)).getDay(),a=Math.floor((dojo.date.locale._getDayOfYear(j)+(h-i+7)%7-1)/7);h==i&&a++;return a};