<html>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>PHProjekt</title>
    <link rel="favicon" href="<?php echo $this->baseUrl('img/favicon.ico'); ?>" type="image/x-icon" ></link>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('img/favicon.ico'); ?>" type="image/x-icon" ></link>
    <link href="<?php echo $this->baseUrl('min/min/?g=login') ?>" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        var djConfig = {isDebug: false, parseOnLoad: true, bindEncoding: "utf-8",
                        locale: 'en', useCommentedJson: true};
    </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('dojo/release/dojo/dojo/dojo.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('dojo/release/dojo/dojo/login.js'); ?>"></script>
    <script type="text/javascript">
        dojo.require("dijit.layout.BorderContainer");
        dojo.require("dijit.layout.ContentPane");
        dojo.require("dijit.Toolbar");
        dojo.require("dijit.form.Form");
        dojo.require("dijit.form.Button");
        dojo.require("dijit.form.CheckBox");
        dojo.require("dijit.form.TextBox");
        dojo.require("dijit.TooltipDialog");
        dojo.require("dijit.form.FilteringSelect");
    </script>
<body class="claro phprojekt-login">
    <!-- Exception Form -->
    <div class="serverFeedback">
    <?php
    if ($this->message) {
        echo '<div class="error">'.$this->message.'</div>';
    }
    if ($this->errors) {
        echo '<div class="error">'.$this->errors.'</div>';
    }
    ?>
    </div>
<div class="loadingOuter">

    <div class="loadingMiddle">
        <div class="loadingMiddleInner">
        <!-- Main Content -->
        <form dojoType="dijit.form.Form"  name="loginForm" method="post"
        action="<?php echo $this->baseUrl('index.php/login/login'); ?>">
            <input dojoType="dijit.form.TextBox" id="hash" type="hidden" name="hash" value="" />
            <table width="100%" align="center" class="form">
            <col class="col1" />
               <?php if (isset($this->domains)) : ?>
               <tr>
                   <td class="label"><label for="domain">Login domain:</label></td>
                   <td>
                       <select name="domain">
                           <?php foreach($this->domains as $key => $display) : ?>
                           <option value="<?php echo $key; ?>"><?php echo $display; ?></option>
                           <?php endforeach ?>
                       </select>
                   </td>
               </tr>
               <?php endif; ?>
                <tr>
                    <td class="label"><label for="username">Username:</label></td>
                    <td>
                        <input type="text" name="username" autocomplete="on"
                        class="dijit dijitReset dijitLeft dijitTextBox dijitTextBoxFocused dijitFocused"
                        id="username" tabindex="0" value="<?php echo $this->username; ?>"
                        style="outline: none;" />
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="password">Password:</label></td>
                    <td>
                        <input type="password" name="password" autocomplete="on"
                        class="dijit dijitReset dijitLeft dijitTextBox dijitTextBoxFocused dijitFocused"
                        id="password" tabindex="0" value=""
                        style="outline: none;" />
                    </td>
                </tr>
                <tr>
                    <td class="label">&nbsp;</td>
                    <td>
                        <input dojoType="dijit.form.CheckBox" class="keepLogged" name="keepLogged" value="1" />
                        &nbsp;
                        <label for="keepLogged">Keep me logged in</label>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <button dojoType="dijit.form.Button"
                        type="submit" iconClass="tick">
                            Login
                        </button>
                    </td>
                </tr>
            </table>
        </form>
        </div>
    </div>
</div>
</body>
</html>
