<div style="font-family: Arial, Helvetica, sans-serif; font-size: 12px;">
<b><?php echo $this->title ?>:</b>
<br />
<a href="<?php echo $this->serverUrl() . $this->baseUrl($this->url); ?>">
         <?php echo $this->serverUrl() . $this->baseUrl($this->url); ?></a><br />
<br />
<b><?php echo $this->currentData; ?>:</b><br />
<br />

<table>
<?php
// All the fields of the item
foreach ($this->mainFields as $field)
{ ?><tr>
        <td><?php echo $field['label'] ?></td>
        <td width="5"></td>
        <td><i><?php echo $field['value'] ?></i></td>
    </tr>
<?php } ?>
</table>

<br />

<?php
// If it is a modification, then the changes are showed
if (!empty($this->changes))
{ ?>
    <b><?php echo $this->changesDone; ?>:</b><br />
    <br />
    <table>
        <tr>
            <th style="color: #888888;" width="120"><?php echo $this->field; ?></th>
            <th style="color: #888888;" width="120"><?php echo $this->oldValue; ?></th>
        </tr>
    <?php
    foreach ($this->changes as $change) { ?>
        <tr>
            <td><i><?php echo $change['label'] ?></i></td>
            <td><i><?php echo $change['oldValue'] ?></i></td>
        </tr>
    <?php } ?>
</table>
<?php } ?>
<br />
<br />
<?php echo $this->copyright; ?><br />
</div>
