/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(typeof window!="undefined")dojo.isBrowser=!0,dojo._name="browser",function(){var a=dojo;a.baseUrl=a.config.baseUrl;var d=navigator,i=d.userAgent,j=parseFloat(d.appVersion);a.isMozilla=a.isMoz=j;if(a.isMoz)a.isFF=parseFloat(i.split("Firefox/")[1])||void 0;a.isQuirks=document.compatMode=="BackCompat";a.locale=dojo.config.locale||d.language.toLowerCase();a._xhrObj=function(){return new XMLHttpRequest};var k=a._loadUri;a._loadUri=function(e,f){if(["file:","chrome:","resource:"].some(function(a){return String(e).indexOf(a)==
0})){var c=Components.classes["@mozilla.org/moz/jssubscript-loader;1"].getService(Components.interfaces.mozIJSSubScriptLoader).loadSubScript(e,a.global);f&&f(c);return!0}else return k.apply(a,arguments)};a._isDocumentOk=function(a){a=a.status||0;return a>=200&&a<300||a==304||a==1223||!a&&(location.protocol=="file:"||location.protocol=="chrome:")};a._getText=function(e,f){var c=a._xhrObj();dojo._Url&&(e=(new dojo._Url(e)).toString());a.config.cacheBust&&(e+="",e+=(e.indexOf("?")==-1?"?":"&")+String(a.config.cacheBust).replace(/\W+/g,
""));if(["file:","chrome:","resource:"].some(function(a){return String(e).indexOf(a)==0})){var b=Components.classes["@mozilla.org/network/io-service;1"].getService(Components.interfaces.nsIIOService),c=Components.classes["@mozilla.org/scriptableinputstream;1"].getService(Components.interfaces.nsIScriptableInputStream),b=b.newChannel(e,null,null).open();c.init(b);var d=c.read(b.available());c.close();b.close();return d}else{c.open("GET",e,!1);try{if(c.send(null),!a._isDocumentOk(c))throw b=Error("Unable to load "+
e+" status:"+c.status),b.status=c.status,b.responseText=c.responseText,b;}catch(g){if(f)return null;throw g;}return c.responseText}};a._windowUnloaders=[];a.windowUnloaded=function(){for(var e=a._windowUnloaders;e.length;)e.pop()()};a.addOnWindowUnload=function(e,f){a._onto(a._windowUnloaders,e,f)};var g=[],h=null;dojo._defaultContext=[window,document];dojo.pushContext=function(a,f){var c=[dojo.global,dojo.doc];g.push(c);var b;if(!a&&!f)b=dojo._defaultContext;else if(b=[a,f],!f&&dojo.isString(a)){var d=
document.getElementById(a);d.contentDocument&&(b=[d.contentWindow,d.contentDocument])}h=b;dojo.setContext.apply(dojo,b);return c};dojo.popContext=function(){var a=h;if(!g.length)return a;dojo.setContext.apply(dojo,g.pop());return a};dojo._inContext=function(a,d,c){var b=dojo._toArray(arguments),c=b.pop();b.length==1&&(d=null);dojo.pushContext(a,d);b=c();dojo.popContext();return b}}(),dojo._initFired=!1,dojo._loadInit=function(a){dojo._initFired=!0;var d=a&&a.type?a.type.toLowerCase():"load";if(!(arguments.callee.initialized||
d!="domcontentloaded"&&d!="load"))arguments.callee.initialized=!0,dojo._inFlightCount==0&&dojo._modulesLoaded()},dojo.config.afterOnLoad||window.addEventListener("DOMContentLoaded",function(a){dojo._loadInit(a)},!1);(function(){var a=dojo.config.modulePaths;if(a)for(var d in a)dojo.registerModulePath(d,a[d])})();if(dojo.config.isDebug)console.log=function(a){Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService).logStringMessage(a)},console.debug=function(){console.log(dojo._toArray(arguments).join(" "))};