/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo.foo"]||(dojo._hasResource["dojo.foo"]=!0,function(){var b=dojo;b.mixin(b,{_loadedModules:{},_inFlightCount:0,_hasResource:{},_modulePrefixes:{dojo:{name:"dojo",value:"."},doh:{name:"doh",value:"../util/doh"},tests:{name:"tests",value:"tests"}},_moduleHasPrefix:function(a){var c=b._modulePrefixes;return!(!c[a]||!c[a].value)},_getModulePrefix:function(a){var c=b._modulePrefixes;return b._moduleHasPrefix(a)?c[a].value:a},_loadedUrls:[],_postLoad:!1,_loaders:[],_unloaders:[],_loadNotifying:!1});
dojo._loadPath=function(a,c,d){a=(a.charAt(0)=="/"||a.match(/^\w+:/)?"":b.baseUrl)+a;try{return!c?b._loadUri(a,d):b._loadUriAndCheck(a,c,d)}catch(e){return console.error(e),!1}finally{}};dojo._loadUri=function(a,c){if(b._loadedUrls[a])return!0;b._inFlightCount++;var d=b._getText(a,!0);if(d){b._loadedUrls[a]=!0;b._loadedUrls.push(a);d=c?/^define\(/.test(d)?d:"("+d+")":b._scopePrefix+d+b._scopeSuffix;b.isIE||(d+="\r\n//@ sourceURL="+a);var e=b.eval(d);c&&c(e)}--b._inFlightCount==0&&b._postLoad&&b._loaders.length&&
setTimeout(function(){b._inFlightCount==0&&b._callLoaded()},0);return!!d};dojo._loadUriAndCheck=function(a,c,d){var e=!1;try{e=b._loadUri(a,d)}catch(f){console.error("failed loading "+a+" with error: "+f)}return!(!e||!b._loadedModules[c])};dojo.loaded=function(){b._loadNotifying=!0;b._postLoad=!0;var a=b._loaders;b._loaders=[];for(var c=0;c<a.length;c++)a[c]();b._loadNotifying=!1;b._postLoad&&b._inFlightCount==0&&a.length&&b._callLoaded()};dojo.unloaded=function(){for(var a=b._unloaders;a.length;)a.pop()()};
b._onto=function(a,b,d){if(d){if(d){var e=typeof d=="string"?b[d]:d;a.push(function(){e.call(b)})}}else a.push(b)};dojo.ready=dojo.addOnLoad=function(a,c){b._onto(b._loaders,a,c);b._postLoad&&b._inFlightCount==0&&!b._loadNotifying&&b._callLoaded()};var g=b.config.addOnLoad;if(g)b.addOnLoad[g instanceof Array?"apply":"call"](b,g);dojo._modulesLoaded=function(){b._postLoad||(b._inFlightCount>0?console.warn("files still in flight!"):b._callLoaded())};dojo._callLoaded=function(){typeof setTimeout=="object"||
b.config.useXDomain&&b.isOpera?setTimeout(b.isAIR?function(){b.loaded()}:b._scopeName+".loaded();",0):b.loaded()};dojo._getModuleSymbols=function(a){for(var a=a.split("."),c=a.length;c>0;c--){var d=a.slice(0,c).join(".");if(c==1&&!b._moduleHasPrefix(d))a[0]="../"+a[0];else{var e=b._getModulePrefix(d);if(e!=d){a.splice(0,c,e);break}}}return a};dojo._global_omit_module_check=!1;dojo.loadInit=function(a){a()};dojo._loadModule=dojo.require=function(a,c){var c=b._global_omit_module_check||c,d=b._loadedModules[a];
if(d)return d;var e=b._getModuleSymbols(a).join("/")+".js";if(!b._loadPath(e,!c?a:null)&&!c)throw Error("Could not load '"+a+"'; last tried '"+e+"'");if(!c&&!b._isXDomain&&(d=b._loadedModules[a],!d))throw Error("symbol '"+a+"' is not defined after loading '"+e+"'");return d};dojo.provide=function(a){a+="";return b._loadedModules[a]=b.getObject(a,!0)};dojo.platformRequire=function(a){for(var a=(a.common||[]).concat(a[b._name]||a["default"]||[]),c=0;c<a.length;c++){var d=a[c];d.constructor==Array?b._loadModule.apply(b,
d):b._loadModule(d)}};dojo.requireIf=function(a,c){if(a===!0){for(var d=[],e=1;e<arguments.length;e++)d.push(arguments[e]);b.require.apply(b,d)}};dojo.requireAfterIf=b.requireIf;dojo.registerModulePath=function(a,c){b._modulePrefixes[a]={name:a,value:c}};dojo.requireLocalization=function(a,c,d,e){b.require("dojo.i18n");b.i18n._requireLocalization.apply(b.hostenv,arguments)};var h=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,i=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/;
dojo._Url=function(){for(var a=arguments,c=[a[0]],d=1;d<a.length;d++)if(a[d]){var e=new b._Url(a[d]+""),c=new b._Url(c[0]+"");if(e.path==""&&!e.scheme&&!e.authority&&!e.query){if(e.fragment!=null)c.fragment=e.fragment;e=c}else if(!e.scheme&&(e.scheme=c.scheme,!e.authority&&(e.authority=c.authority,e.path.charAt(0)!="/"))){for(var c=(c.path.substring(0,c.path.lastIndexOf("/")+1)+e.path).split("/"),f=0;f<c.length;f++)c[f]=="."?f==c.length-1?c[f]="":(c.splice(f,1),f--):f>0&&!(f==1&&c[0]=="")&&c[f]==
".."&&c[f-1]!=".."&&(f==c.length-1?(c.splice(f,1),c[f-1]=""):(c.splice(f-1,2),f-=2));e.path=c.join("/")}c=[];e.scheme&&c.push(e.scheme,":");e.authority&&c.push("//",e.authority);c.push(e.path);e.query&&c.push("?",e.query);e.fragment&&c.push("#",e.fragment)}this.uri=c.join("");a=this.uri.match(h);this.scheme=a[2]||(a[1]?"":null);this.authority=a[4]||(a[3]?"":null);this.path=a[5];this.query=a[7]||(a[6]?"":null);this.fragment=a[9]||(a[8]?"":null);if(this.authority!=null)a=this.authority.match(i),this.user=
a[3]||null,this.password=a[4]||null,this.host=a[6]||a[7],this.port=a[9]||null};dojo._Url.prototype.toString=function(){return this.uri};dojo.moduleUrl=function(a,c){var d=b._getModuleSymbols(a).join("/");if(!d)return null;d.lastIndexOf("/")!=d.length-1&&(d+="/");var e=d.indexOf(":");if(d.charAt(0)!="/"&&(e==-1||e>d.indexOf("/")))d=b.baseUrl+d;return new b._Url(d,c)}}());