/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojo._base._loader.loader_xd"])dojo._hasResource["dojo._base._loader.loader_xd"]=!0,dojo.provide("dojo._base._loader.loader_xd"),dojo._xdReset=function(){dojo._isXDomain=dojo.config.useXDomain||!1;dojo._xdClearInterval();dojo._xdInFlight={};dojo._xdOrderedReqs=[];dojo._xdDepMap={};dojo._xdContents=[];dojo._xdDefList=[]},dojo._xdClearInterval=function(){if(dojo._xdTimer)clearInterval(dojo._xdTimer),dojo._xdTimer=0},dojo._xdReset(),dojo._xdCreateResource=function(a,c,d){for(var b=
a.replace(/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,""),e=[],g=/dojo.(require|requireIf|provide|requireAfterIf|platformRequire|requireLocalization)\s*\(([\w\W]*?)\)/mg,f;(f=g.exec(b))!=null;)f[1]=="requireLocalization"?eval(f[0]):e.push('"'+f[1]+'", '+f[2]);b=[];b.push(dojo._scopeName+"._xdResourceLoaded(function("+dojo._scopePrefixArgs+"){\n");if(g=dojo._xdExtractLoadInits(a)){a=g[0];for(f=1;f<g.length;f++)b.push(g[f]+";\n")}b.push("return {");if(e.length>0){b.push("depends: [");for(f=0;f<e.length;f++)f>
0&&b.push(",\n"),b.push("["+e[f]+"]");b.push("],")}b.push("\ndefineResource: function("+dojo._scopePrefixArgs+"){");(!dojo.config.debugAtAllCosts||c=="dojo._base._loader.loader_debug")&&b.push(a);b.push("\n}, resourceName: '"+c+"', resourcePath: '"+d+"'};});");return b.join("")},dojo._xdExtractLoadInits=function(a){var c=/dojo.loadInit\s*\(/g;c.lastIndex=0;var d=/[\(\)]/g;d.lastIndex=0;for(var b=[],e;e=c.exec(a);){d.lastIndex=c.lastIndex;for(var g=1,f;f=d.exec(a);)if(f[0]==")"?g-=1:g+=1,g==0)break;
if(g!=0)throw"unmatched paren around character "+d.lastIndex+" in: "+a;e=c.lastIndex-e[0].length;b.push(a.substring(e,d.lastIndex));g=d.lastIndex-e;a=a.substring(0,e)+a.substring(d.lastIndex,a.length);c.lastIndex=d.lastIndex-g;c.lastIndex=d.lastIndex}b.length>0&&b.unshift(a);return b.length?b:null},dojo._xdIsXDomainPath=function(a){var c=a.indexOf(":"),d=a.indexOf("/");if(c>0&&c<d||a.indexOf("//")===0)return!0;else if(a=dojo.baseUrl,c=a.indexOf(":"),d=a.indexOf("/"),a.indexOf("//")===0||c>0&&c<d&&
(!location.host||a.indexOf("http://"+location.host)!=0))return!0;return!1},dojo._loadPath=function(a,c,d){var b=dojo._xdIsXDomainPath(a);dojo._isXDomain|=b;a=(a.charAt(0)=="/"||a.match(/^\w+:/)?"":dojo.baseUrl)+a;try{return!c||dojo._isXDomain?dojo._loadUri(a,d,b,c):dojo._loadUriAndCheck(a,c,d)}catch(e){return console.error(e),!1}},dojo._xdCharSet="utf-8",dojo._loadUri=function(a,c,d,b){if(dojo._loadedUrls[a])return 1;if(dojo._isXDomain&&b&&b!="dojo.i18n"){dojo._xdOrderedReqs.push(b);if(d||a.indexOf("/nls/")==
-1)dojo._xdInFlight[b]=!0,dojo._inFlightCount++;if(!dojo._xdTimer)dojo._xdTimer=dojo.isAIR?setInterval(function(){dojo._xdWatchInFlight()},100):setInterval(dojo._scopeName+"._xdWatchInFlight();",100);dojo._xdStartTime=(new Date).getTime()}if(d){b=a.lastIndexOf(".");b<=0&&(b=a.length-1);c=a.substring(0,b)+".xd";b!=a.length-1&&(c+=a.substring(b,a.length));dojo.isAIR&&(c=c.replace("app:/","/"));b=document.createElement("script");b.type="text/javascript";if(dojo._xdCharSet)b.charset=dojo._xdCharSet;b.src=
c;if(!dojo.headElement&&(dojo._headElement=document.getElementsByTagName("head")[0],!dojo._headElement))dojo._headElement=document.getElementsByTagName("html")[0];dojo._headElement.appendChild(b)}else{d=dojo._getText(a,null,!0);if(d==null)return 0;dojo._isXDomain&&a.indexOf("/nls/")==-1&&b!="dojo.i18n"?(c=dojo._xdCreateResource(d,b,a),dojo.eval(c)):(d=c?"("+d+")":dojo._scopePrefix+d+dojo._scopeSuffix,b=dojo.eval(d+"\r\n//@ sourceURL="+a),c&&c(b))}dojo._loadedUrls[a]=!0;dojo._loadedUrls.push(a);return!0},
dojo._xdResourceLoaded=function(a){var a=a.apply(dojo.global,dojo._scopeArgs),c=a.depends,d=null,b=null,e=[];if(c&&c.length>0){for(var g=null,f=0;f<c.length;f++){g=c[f];if(g[0]=="provide")e.push(g[1]);else{d||(d=[]);b||(b=[]);var h=dojo._xdUnpackDependency(g);h.requires&&(d=d.concat(h.requires));h.requiresAfter&&(b=b.concat(h.requiresAfter))}var h=g[0],i=h.split(".");i.length==2?dojo[i[0]][i[1]].apply(dojo[i[0]],g.slice(1)):dojo[h].apply(dojo,g.slice(1))}if(e.length==1&&e[0]=="dojo._base._loader.loader_debug")a.defineResource(dojo);
else{a=dojo._xdContents.push({content:a.defineResource,resourceName:a.resourceName,resourcePath:a.resourcePath,isDefined:!1})-1;for(f=0;f<e.length;f++)dojo._xdDepMap[e[f]]={requires:d,requiresAfter:b,contentIndex:a}}for(f=0;f<e.length;f++)dojo._xdInFlight[e[f]]=!1}},dojo._xdLoadFlattenedBundle=function(a,c,d,b){var e=dojo.i18n.normalizeLocale(d||"root").replace("-","_"),d=[a,"nls",c].join("."),d=dojo.provide(d);d[e]=b;a=[a,e,c].join(".");if(a=dojo._xdBundleMap[a])for(var g in a)d[g]=b},dojo._xdInitExtraLocales=
function(){var a=dojo.config.extraLocale;if(a)!a instanceof Array&&(a=[a]),dojo._xdReqLoc=dojo.xdRequireLocalization,dojo.xdRequireLocalization=function(c,d,b,e){dojo._xdReqLoc(c,d,b,e);if(!b)for(b=0;b<a.length;b++)dojo._xdReqLoc(c,d,a[b],e)}},dojo._xdBundleMap={},dojo.xdRequireLocalization=function(a,c,d,b){if(dojo._xdInitExtraLocales)dojo._xdInitExtraLocales(),dojo._xdInitExtraLocales=null,dojo.xdRequireLocalization.apply(dojo,arguments);else{for(var e=b.split(","),g=dojo.i18n.normalizeLocale(d),
f="",h=0;h<e.length;h++)g.indexOf(e[h])==0&&e[h].length>f.length&&(f=e[h]);e=f.replace("-","_");h=dojo.getObject([a,"nls",c].join("."));if(!h||!h[e])e=[a,e||"root",c].join("."),(h=dojo._xdBundleMap[e])||(h=dojo._xdBundleMap[e]={}),h[g.replace("-","_")]=!0,dojo.require(a+".nls"+(f?"."+f:"")+"."+c)}},dojo._xdRealRequireLocalization=dojo.requireLocalization,dojo.requireLocalization=function(a,c,d,b){var e=dojo.moduleUrl(a).toString();return dojo._xdIsXDomainPath(e)?dojo.xdRequireLocalization.apply(dojo,
arguments):dojo._xdRealRequireLocalization.apply(dojo,arguments)},dojo._xdUnpackDependency=function(a){var c=null,d=null;switch(a[0]){case "requireIf":case "requireAfterIf":a[1]===!0&&(c=[{name:a[2],content:null}]);break;case "platformRequire":var c=a[1],b=c.common||[];if(c=c[dojo.hostenv.name_]?b.concat(c[dojo.hostenv.name_]||[]):b.concat(c["default"]||[]))for(b=0;b<c.length;b++)c[b]=c[b]instanceof Array?{name:c[b][0],content:null}:{name:c[b],content:null};break;case "require":c=[{name:a[1],content:null}];
break;case "i18n._preloadLocalizations":dojo.i18n._preloadLocalizations.apply(dojo.i18n._preloadLocalizations,a.slice(1))}if(a[0]=="requireAfterIf"||a[0]=="requireIf")d=c,c=null;return{requires:c,requiresAfter:d}},dojo._xdWalkReqs=function(){for(var a=null,c,d=0;d<dojo._xdOrderedReqs.length;d++)c=dojo._xdOrderedReqs[d],dojo._xdDepMap[c]&&(a=[c],a[c]=!0,dojo._xdEvalReqs(a))},dojo._xdEvalReqs=function(a){for(;a.length>0;){var c=a[a.length-1],d=dojo._xdDepMap[c],b,e,g;if(d){if((e=d.requires)&&e.length>
0)for(b=0;b<e.length;b++)if((g=e[b].name)&&!a[g])a.push(g),a[g]=!0,dojo._xdEvalReqs(a);b=dojo._xdContents[d.contentIndex];if(!b.isDefined)e=b.content,e.resourceName=b.resourceName,e.resourcePath=b.resourcePath,dojo._xdDefList.push(e),b.isDefined=!0;dojo._xdDepMap[c]=null;if((e=d.requiresAfter)&&e.length>0)for(b=0;b<e.length;b++)if((g=e[b].name)&&!a[g])a.push(g),a[g]=!0,dojo._xdEvalReqs(a)}a.pop()}},dojo._xdWatchInFlight=function(){var a="",c=dojo._xdStartTime+(dojo.config.xdWaitSeconds||15)*1E3<(new Date).getTime(),
d;for(d in dojo._xdInFlight)if(dojo._xdInFlight[d]===!0)if(c)a+=d+" ";else return;dojo._xdClearInterval();if(c)throw"Could not load cross-domain resources: "+a;dojo._xdWalkReqs();c=dojo._xdDefList.length;for(a=0;a<c;a++)if(d=dojo._xdDefList[a],dojo.config.debugAtAllCosts&&d.resourceName){if(!dojo._xdDebugQueue)dojo._xdDebugQueue=[];dojo._xdDebugQueue.push({resourceName:d.resourceName,resourcePath:d.resourcePath})}else d.apply(dojo.global,dojo._scopeArgs);for(a=0;a<dojo._xdContents.length;a++)c=dojo._xdContents[a],
c.content&&!c.isDefined&&c.content.apply(dojo.global,dojo._scopeArgs);dojo._xdReset();dojo._xdDebugQueue&&dojo._xdDebugQueue.length>0?dojo._xdDebugFileLoaded():dojo._xdNotifyLoaded()},dojo._xdNotifyLoaded=function(){for(var a in dojo._xdInFlight)if(typeof dojo._xdInFlight[a]=="boolean")return;dojo._inFlightCount=0;dojo._initFired&&!dojo._loadNotifying&&dojo._callLoaded()};