/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.dtl.contrib.dijit"]||(dojo._hasResource["dojox.dtl.contrib.dijit"]=!0,dojo.provide("dojox.dtl.contrib.dijit"),dojo.require("dojox.dtl.dom"),dojo.require("dojo.parser"),function(){function i(c){var b=c.cloneNode(!0);dojo.isIE&&dojo.query("script",b).forEach("item.text = this[index].text;",dojo.query("script",c));return b}var f=dojox.dtl,d=f.contrib.dijit;d.AttachNode=dojo.extend(function(c,b){this._keys=c;this._object=b},{render:function(c,b){if(!this._rendered){this._rendered=
!0;for(var a=0,e;e=this._keys[a];a++)c.getThis()[e]=this._object||b.getParent()}return b},unrender:function(c,b){if(this._rendered){this._rendered=!1;for(var a=0,e;e=this._keys[a];a++)c.getThis()[e]===(this._object||b.getParent())&&delete c.getThis()[e]}return b},clone:function(){return new this.constructor(this._keys,this._object)}});d.EventNode=dojo.extend(function(c,b){this._command=c;for(var a,e=c.split(/\s*,\s*/),g=dojo.trim,d=[],f=[];a=e.pop();)if(a){var h=null;a.indexOf(":")!=-1?(h=a.split(":"),
a=g(h[0]),h=g(h.slice(1).join(":"))):a=g(a);h||(h=a);d.push(a);f.push(h)}this._types=d;this._fns=f;this._object=b;this._rendered=[]},{_clear:!1,render:function(c,b){for(var a=0,e;e=this._types[a];a++){!this._clear&&!this._object&&(b.getParent()[e]=null);var d=this._fns[a],i;d.indexOf(" ")!=-1&&(this._rendered[a]&&(dojo.disconnect(this._rendered[a]),this._rendered[a]=!1),i=dojo.map(d.split(" ").slice(1),function(a){return(new f._Filter(a)).resolve(c)}),d=d.split(" ",2)[0]);this._rendered[a]||(this._rendered[a]=
this._object?dojo.connect(this._object,e,c.getThis(),d):b.addEvent(c,e,d,i))}this._clear=!0;return b},unrender:function(c,b){for(;this._rendered.length;)dojo.disconnect(this._rendered.pop());return b},clone:function(){return new this.constructor(this._command,this._object)}});d.DojoTypeNode=dojo.extend(function(c,b){this._node=c;this._parsed=b;var a=c.getAttribute("dojoAttachEvent");if(a)this._events=new d.EventNode(dojo.trim(a));if(a=c.getAttribute("dojoAttachPoint"))this._attach=new d.AttachNode(dojo.trim(a).split(/\s*,\s*/));
b?(c=i(c),a=d.widgetsInTemplate,d.widgetsInTemplate=!1,this._template=new f.DomTemplate(c),d.widgetsInTemplate=a):this._dijit=dojo.parser.instantiate([i(c)])[0]},{render:function(c,b){if(this._parsed){var a=new f.DomBuffer;this._template.render(c,a);var a=i(a.getRootNode()),d=document.createElement("div");d.appendChild(a);var g=d.innerHTML;d.removeChild(a);if(g!=this._rendered)this._rendered=g,this._dijit&&this._dijit.destroyRecursive(),this._dijit=dojo.parser.instantiate([a])[0]}a=this._dijit.domNode;
if(this._events)this._events._object=this._dijit,this._events.render(c,b);if(this._attach)this._attach._object=this._dijit,this._attach.render(c,b);return b.concat(a)},unrender:function(c,b){return b.remove(this._dijit.domNode)},clone:function(){return new this.constructor(this._node,this._parsed)}});dojo.mixin(d,{widgetsInTemplate:!0,dojoAttachPoint:function(c,b){return new d.AttachNode(b.contents.slice(16).split(/\s*,\s*/))},dojoAttachEvent:function(c,b){return new d.EventNode(b.contents.slice(16))},
dojoType:function(c,b){var a=!1;b.contents.slice(-7)==" parsed"&&(a=!0);var e=b.contents.slice(9),e=a?e.slice(0,-7):e.toString();if(d.widgetsInTemplate){var g=c.swallowNode();g.setAttribute("dojoType",e);return new d.DojoTypeNode(g,a)}return new f.AttributeNode("dojoType",e)},on:function(c,b){var a=b.contents.split();return new d.EventNode(a[0]+":"+a.slice(1).join(" "))}});f.register.tags("dojox.dtl.contrib",{dijit:["attr:dojoType","attr:dojoAttachPoint",["attr:attach","dojoAttachPoint"],"attr:dojoAttachEvent",
[/(attr:)?on(click|key(up))/i,"on"]]})}());