/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.dtl.contrib.dom"]||(dojo._hasResource["dojox.dtl.contrib.dom"]=!0,dojo.provide("dojox.dtl.contrib.dom"),dojo.require("dojox.dtl.dom"),function(){var i=dojox.dtl,f=i.contrib.dom,j={render:function(){return this.contents}};f.StyleNode=dojo.extend(function(b){this.contents={};this._current={};this._styles=b;for(var a in b){if(b[a].indexOf("{{")!=-1)var c=new i.Template(b[a]);else c=dojo.delegate(j),c.contents=b[a];this.contents[a]=c}},{render:function(b,a){for(var c in this.contents){var d=
this.contents[c].render(b);this._current[c]!=d&&dojo.style(a.getParent(),c,this._current[c]=d)}return a},unrender:function(b,a){this._current={};return a},clone:function(){return new this.constructor(this._styles)}});f.BufferNode=dojo.extend(function(b,a){this.nodelist=b;this.options=a},{_swap:function(b,a){if(!this.swapped&&this.parent.parentNode){if(b=="node"){if(a.nodeType==3&&!this.options.text||a.nodeType==1&&!this.options.node)return}else if(b=="class"&&b!="class")return;this.onAddNode&&dojo.disconnect(this.onAddNode);
this.onRemoveNode&&dojo.disconnect(this.onRemoveNode);this.onChangeAttribute&&dojo.disconnect(this.onChangeAttribute);this.onChangeData&&dojo.disconnect(this.onChangeData);this.swapped=this.parent.cloneNode(!0);this.parent.parentNode.replaceChild(this.swapped,this.parent)}},render:function(b,a){this.parent=a.getParent();if(this.options.node)this.onAddNode=dojo.connect(a,"onAddNode",dojo.hitch(this,"_swap","node")),this.onRemoveNode=dojo.connect(a,"onRemoveNode",dojo.hitch(this,"_swap","node"));if(this.options.text)this.onChangeData=
dojo.connect(a,"onChangeData",dojo.hitch(this,"_swap","node"));if(this.options["class"])this.onChangeAttribute=dojo.connect(a,"onChangeAttribute",dojo.hitch(this,"_swap","class"));a=this.nodelist.render(b,a);this.swapped?(this.swapped.parentNode.replaceChild(this.parent,this.swapped),dojo.destroy(this.swapped)):(this.onAddNode&&dojo.disconnect(this.onAddNode),this.onRemoveNode&&dojo.disconnect(this.onRemoveNode),this.onChangeAttribute&&dojo.disconnect(this.onChangeAttribute),this.onChangeData&&dojo.disconnect(this.onChangeData));
delete this.parent;delete this.swapped;return a},unrender:function(b,a){return this.nodelist.unrender(b,a)},clone:function(b){return new this.constructor(this.nodelist.clone(b),this.options)}});dojo.mixin(f,{buffer:function(b,a){for(var c=a.contents.split().slice(1),d={},g=!1,e=c.length;e--;)g=!0,d[c[e]]=!0;if(!g)d.node=!0;c=b.parse(["endbuffer"]);b.next_token();return new f.BufferNode(c,d)},html:function(b,a){dojo.deprecated("{% html someVariable %}","Use {{ someVariable|safe }} instead");return b.create_variable_node(a.contents.slice(5)+
"|safe")},style_:function(b,a){for(var c={},a=a.contents.replace(/^style\s+/,""),d=a.split(/\s*;\s*/g),g=0,e;e=d[g];g++){var h=e.split(/\s*:\s*/g);e=h[0];(h=dojo.trim(h[1]))&&(c[e]=h)}return new f.StyleNode(c)}});i.register.tags("dojox.dtl.contrib",{dom:["html","attr:style","buffer"]})}());