/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.app._base"]||(dojo._hasResource["dojox.mobile.app._base"]=!0,dojo.provide("dojox.mobile.app._base"),dojo.experimental("dojox.mobile.app._base"),dojo.require("dijit._base"),dojo.require("dijit._WidgetBase"),dojo.require("dojox.mobile"),dojo.require("dojox.mobile.parser"),dojo.require("dojox.mobile.app._event"),dojo.require("dojox.mobile.app._Widget"),dojo.require("dojox.mobile.app.StageController"),dojo.require("dojox.mobile.app.SceneController"),dojo.require("dojox.mobile.app.SceneAssistant"),
dojo.require("dojox.mobile.app.AlertDialog"),dojo.require("dojox.mobile.app.List"),dojo.require("dojox.mobile.app.ListSelector"),dojo.require("dojox.mobile.app.TextBox"),dojo.require("dojox.mobile.app.ImageView"),dojo.require("dojox.mobile.app.ImageThumbView"),function(){function f(a,d){var b,c;do if(b=a.pop(),b.source)c=b.source;else if(b.module)c=dojo.baseUrl+dojo._getModuleSymbols(b.module).join("/")+".js";else{alert("Error: invalid JavaScript resource "+dojo.toJson(b));return}while(a.length>0&&
i[c]);a.length<1&&i[c]?d():dojo.xhrGet({url:c,sync:!1}).addCallbacks(function(b){dojo.eval(b);i[c]=!0;a.length>0?f(a,d):d()},function(){alert("Failed to load resource "+c)})}var e,g,i={},k,h=[],j=function(){e=new dojox.mobile.app.StageController(k);var a={id:"com.test.app",version:"1.0.0",initialScene:"main"};dojo.global.appInfo&&dojo.mixin(a,dojo.global.appInfo);g=dojox.mobile.app.info=a;if(g.title)dojo.query("head title")[0]||dojo.create("title",{},dojo.query("head")[0]),document.title=g.title;
e.pushScene(g.initialScene)},l=function(){var a=!1;dojo.global.BackButton&&(BackButton.override(),dojo.connect(document,"backKeyDown",function(){dojo.publish("/dojox/mobile/app/goback")}),a=!0);a&&dojo.addClass(dojo.body(),"mblNativeBack")};dojo.mixin(dojox.mobile.app,{init:function(a){k=a||dojo.body();dojox.mobile.app.STAGE_CONTROLLER_ACTIVE=!0;dojo.subscribe("/dojox/mobile/app/goback",function(){e.popScene()});dojo.subscribe("/dojox/mobile/app/alert",function(a){dojox.mobile.app.getActiveSceneController().showAlertDialog(a)});
dojo.subscribe("/dojox/mobile/app/pushScene",function(a,b){e.pushScene(a,b||{})});dojo.xhrGet({url:"view-resources.json",load:function(a){var b=[];if(a){h=a=dojo.fromJson(a);for(var c=0;c<a.length;c++)a[c].scene||b.push(a[c])}b.length>0?f(b,j):j()},error:j});l()},getActiveSceneController:function(){return e.getActiveSceneController()},getStageController:function(){return e},loadResources:function(a,d){f(a,d)},loadResourcesForScene:function(a,d){for(var b=[],c=0;c<h.length;c++)h[c].scene==a&&b.push(h[c]);
b.length>0?f(b,d):d()},resolveTemplate:function(a){return"app/views/"+a+"/"+a+"-scene.html"},resolveAssistant:function(a){return"app/assistants/"+a+"-assistant.js"}})}());