/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.app._FormWidget"]||(dojo._hasResource["dojox.mobile.app._FormWidget"]=!0,dojo.provide("dojox.mobile.app._FormWidget"),dojo.experimental("dojox.mobile.app._FormWidget"),dojo.require("dojo.window"),dojo.require("dijit._WidgetBase"),dojo.declare("dojox.mobile.app._FormWidget",dijit._WidgetBase,{name:"",alt:"",value:"",type:"text",disabled:!1,intermediateChanges:!1,scrollOnFocus:!1,attributeMap:dojo.delegate(dijit._WidgetBase.prototype.attributeMap,{value:"focusNode",id:"focusNode",
alt:"focusNode",title:"focusNode"}),postMixInProperties:function(){this.nameAttrSetting=this.name?'name="'+this.name.replace(/'/g,"&quot;")+'"':"";this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onmousedown","_onMouseDown")},_setDisabledAttr:function(a){this.disabled=a;dojo.attr(this.focusNode,"disabled",a);this.valueNode&&dojo.attr(this.valueNode,"disabled",a)},_onFocus:function(a){this.scrollOnFocus&&dojo.window.scrollIntoView(this.domNode);
this.inherited(arguments)},isFocusable:function(){return!this.disabled&&!this.readOnly&&this.focusNode&&dojo.style(this.domNode,"display")!="none"},focus:function(){this.focusNode.focus()},compare:function(a,b){return typeof a=="number"&&typeof b=="number"?isNaN(a)&&isNaN(b)?0:a-b:a>b?1:a<b?-1:0},onChange:function(){},_onChangeActive:!1,_handleOnChange:function(a,b){this._lastValue=a;if(this._lastValueReported==void 0&&(b===null||!this._onChangeActive))this._resetValue=this._lastValueReported=a;if((this.intermediateChanges||
b||b===void 0)&&(typeof a!=typeof this._lastValueReported||this.compare(a,this._lastValueReported)!=0))if(this._lastValueReported=a,this._onChangeActive)this._onChangeHandle&&clearTimeout(this._onChangeHandle),this._onChangeHandle=setTimeout(dojo.hitch(this,function(){this._onChangeHandle=null;this.onChange(a)}),0)},create:function(){this.inherited(arguments);this._onChangeActive=!0},destroy:function(){this._onChangeHandle&&(clearTimeout(this._onChangeHandle),this.onChange(this._lastValueReported));
this.inherited(arguments)},_onMouseDown:function(){if(this.isFocusable())var a=this.connect(dojo.body(),"onmouseup",function(){this.isFocusable()&&this.focus();this.disconnect(a)})},selectInputText:function(a,b,c){var d=dojo.global,a=dojo.byId(a);isNaN(b)&&(b=0);isNaN(c)&&(c=a.value?a.value.length:0);dijit.focus(a);d.getSelection&&a.setSelectionRange&&a.setSelectionRange(b,c)}}),dojo.declare("dojox.mobile.app._FormValueWidget",dojox.mobile.app._FormWidget,{readOnly:!1,attributeMap:dojo.delegate(dojox.mobile.app._FormWidget.prototype.attributeMap,
{value:"",readOnly:"focusNode"}),_setReadOnlyAttr:function(a){this.readOnly=a;dojo.attr(this.focusNode,"readOnly",a)},postCreate:function(){this.inherited(arguments);if(this._resetValue===void 0)this._resetValue=this.value},_setValueAttr:function(a,b){this.value=a;this._handleOnChange(a,b)},_getValueAttr:function(){return this._lastValue},undo:function(){this._setValueAttr(this._lastValueReported,!1)},reset:function(){this._hasBeenBlurred=!1;this._setValueAttr(this._resetValue,!0)}}));