/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.app.AlertDialog"]||(dojo._hasResource["dojox.mobile.app.AlertDialog"]=!0,dojo.provide("dojox.mobile.app.AlertDialog"),dojo.experimental("dojox.mobile.app.AlertDialog"),dojo.require("dijit._WidgetBase"),dojo.declare("dojox.mobile.app.AlertDialog",dijit._WidgetBase,{title:"",text:"",controller:null,buttons:null,defaultButtonLabel:"OK",onChoose:null,constructor:function(){this.onClick=dojo.hitch(this,this.onClick);this._handleSelect=dojo.hitch(this,this._handleSelect)},
buildRendering:function(){this.domNode=dojo.create("div",{"class":"alertDialog"});var a=dojo.create("div",{"class":"alertDialogBody"},this.domNode);dojo.create("div",{"class":"alertTitle",innerHTML:this.title||""},a);dojo.create("div",{"class":"alertText",innerHTML:this.text||""},a);var b=dojo.create("div",{"class":"alertBtns"},a);if(!this.buttons||this.buttons.length==0)this.buttons=[{label:this.defaultButtonLabel,value:"ok","class":"affirmative"}];var c=this;dojo.forEach(this.buttons,function(a){var e=
new dojox.mobile.Button({btnClass:a["class"]||"",label:a.label});e._dialogValue=a.value;dojo.place(e.domNode,b);c.connect(e,"onClick",c._handleSelect)});a=this.controller.getWindowSize();this.mask=dojo.create("div",{"class":"dialogUnderlayWrapper",innerHTML:'<div class="dialogUnderlay"></div>',style:{width:a.w+"px",height:a.h+"px"}},this.controller.assistant.domNode);this.connect(this.mask,"onclick",function(){c.onChoose&&c.onChoose();c.hide()})},postCreate:function(){this.subscribe("/dojox/mobile/app/goback",
this._handleSelect)},_handleSelect:function(a){var b;console.log("handleSelect");if(a&&a.target)for(b=a.target;!dijit.byNode(b););if(this.onChoose)this.onChoose(b?dijit.byNode(b)._dialogValue:void 0);this.hide()},show:function(){this._doTransition(1)},hide:function(){this._doTransition(-1)},_doTransition:function(a){var b,c=dojo.marginBox(this.domNode.firstChild).h;b=this.controller.getWindowSize().h;console.log("dialog height = "+c," body height = "+b);c=b-c;b=dojo.fx.slideTo({node:this.domNode,
duration:400,top:{start:a<0?c:b,end:a<0?b:c}});c=dojo[a<0?"fadeOut":"fadeIn"]({node:this.mask,duration:400});b=dojo.fx.combine([b,c]);var d=this;dojo.connect(b,"onEnd",this,function(){if(a<0)d.domNode.style.display="none",dojo.destroy(d.domNode),dojo.destroy(d.mask)});b.play()},destroy:function(){this.inherited(arguments);dojo.destroy(this.mask)},onClick:function(){}}));