/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.app.ImageView"]||(dojo._hasResource["dojox.mobile.app.ImageView"]=!0,dojo.provide("dojox.mobile.app.ImageView"),dojo.experimental("dojox.mobile.app.ImageView"),dojo.require("dojox.mobile.app._Widget"),dojo.require("dojo.fx.easing"),dojo.declare("dojox.mobile.app.ImageView",dojox.mobile.app._Widget,{zoom:1,zoomCenterX:0,zoomCenterY:0,maxZoom:5,autoZoomLevel:3,disableAutoZoom:!1,disableSwipe:!1,autoZoomEvent:null,_leftImg:null,_centerImg:null,_rightImg:null,_leftSmallImg:null,
_centerSmallImg:null,_rightSmallImg:null,constructor:function(){this.panY=this.panX=0;this.handleLoad=dojo.hitch(this,this.handleLoad);this._updateAnimatedZoom=dojo.hitch(this,this._updateAnimatedZoom);this._updateAnimatedPan=dojo.hitch(this,this._updateAnimatedPan);this._onAnimPanEnd=dojo.hitch(this,this._onAnimPanEnd)},buildRendering:function(){this.inherited(arguments);this.canvas=dojo.create("canvas",{},this.domNode);dojo.addClass(this.domNode,"mblImageView")},postCreate:function(){this.inherited(arguments);
this.size=dojo.marginBox(this.domNode);dojo.style(this.canvas,{width:this.size.w+"px",height:this.size.h+"px"});this.canvas.height=this.size.h;this.canvas.width=this.size.w;var a=this;this.connect(this.domNode,"onmousedown",function(b){if(!a.isAnimating())a.panX&&a.handleDragEnd(),a.downX=b.targetTouches?b.targetTouches[0].clientX:b.clientX,a.downY=b.targetTouches?b.targetTouches[0].clientY:b.clientY});this.connect(this.domNode,"onmousemove",function(b){if(!a.isAnimating()&&!(!a.downX&&a.downX!==
0||!a.downY&&a.downY!==0))if(!a.disableSwipe&&a.zoom==1||!a.disableAutoZoom&&a.zoom!=1){var c=b.targetTouches?b.targetTouches[0].clientY:b.pageY;a.panX=(b.targetTouches?b.targetTouches[0].clientX:b.pageX)-a.downX;a.panY=c-a.downY;a.zoom==1?Math.abs(a.panX)>10&&a.render():(Math.abs(a.panX)>10||Math.abs(a.panY)>10)&&a.render()}});this.connect(this.domNode,"onmouseout",function(){!a.isAnimating()&&a.panX&&a.handleDragEnd()});this.connect(this.domNode,"onmouseover",function(){a.downX=a.downY=null});this.connect(this.domNode,
"onclick",function(b){if(!a.isAnimating()&&!(a.downX==null||a.downY==null)){var c=b.targetTouches?b.targetTouches[0].clientX:b.pageX,b=b.targetTouches?b.targetTouches[0].clientY:b.pageY;if(Math.abs(a.panX)>14||Math.abs(a.panY)>14)a.downX=a.downY=null,a.handleDragEnd();else if(a.downX=a.downY=null,!a.disableAutoZoom&&a._centerImg&&a._centerImg._loaded)if(a.zoom!=1)a.set("animatedZoom",1);else{var d=dojo._abs(a.domNode);a.zoomTo((c-d.x)/(a.size.w/a._centerImg.width)-a.panX,(b-d.y)/(a.size.h/a._centerImg.height)-
a.panY,a.autoZoomLevel)}}});dojo.connect(this.domNode,"flick",this,"handleFlick")},isAnimating:function(){return this._anim&&this._anim.status()=="playing"},handleDragEnd:function(){this.downX=this.downY=null;console.log("handleDragEnd");if(this.zoom==1){if(this.panX){var a=this._leftImg&&this._leftImg._loaded||this._leftSmallImg&&this._leftSmallImg._loaded,b=this._rightImg&&this._rightImg._loaded||this._rightSmallImg&&this._rightSmallImg._loaded;!(Math.abs(this.panX)<this._centerImg._baseWidth/2)&&
(this.panX>0&&a||this.panX<0&&b)?this.moveTo(this.panX):this._animPanTo(0,dojo.fx.easing.expoOut,700)}}else if(this.panX||this.panY)this.zoomCenterX-=this.panX/this.zoom,this.zoomCenterY-=this.panY/this.zoom,this.panX=this.panY=0},handleFlick:function(a){if(this.zoom==1&&a.duration<500)a.direction=="ltr"?this.moveTo(1):a.direction=="rtl"&&this.moveTo(-1),this.downX=this.downY=null},moveTo:function(a){var a=a>0?1:-1,b;if(a<1)if(this._rightImg&&this._rightImg._loaded)b=this._rightImg;else{if(this._rightSmallImg&&
this._rightSmallImg._loaded)b=this._rightSmallImg}else if(this._leftImg&&this._leftImg._loaded)b=this._leftImg;else if(this._leftSmallImg&&this._leftSmallImg._loaded)b=this._leftSmallImg;this._moveDir=a;var c=this;b&&b._loaded?this._animPanTo(this.size.w*a,null,500,function(){c.panX=0;c.panY=0;a<0?c._switchImage("left","right"):c._switchImage("right","left");c.render();c.onChange(a*-1)}):(console.log("moveTo image not loaded!",b),this._animPanTo(0,dojo.fx.easing.expoOut,700))},_switchImage:function(a,
b){var c="_"+a+"SmallImg",d="_"+a+"Img",f="_"+b+"SmallImg",e="_"+b+"Img";this[d]=this._centerImg;this[c]=this._centerSmallImg;this[d]._type=a;if(this[c])this[c]._type=a;this._centerImg=this[e];this._centerSmallImg=this[f];this._centerImg._type="center";if(this._centerSmallImg)this._centerSmallImg._type="center";this[e]=this[f]=null},_animPanTo:function(a,b,c,d){this._animCallback=d;this._anim=new dojo.Animation({curve:[this.panX,a],onAnimate:this._updateAnimatedPan,duration:c||500,easing:b,onEnd:this._onAnimPanEnd});
this._anim.play();return this._anim},onChange:function(){},_updateAnimatedPan:function(a){this.panX=a;this.render()},_onAnimPanEnd:function(){this.panX=this.panY=0;this._animCallback&&this._animCallback()},zoomTo:function(a,b,c){this.set("zoomCenterX",a);this.set("zoomCenterY",b);this.set("animatedZoom",c)},render:function(){this.canvas.getContext("2d").clearRect(0,0,this.canvas.width,this.canvas.height);this._renderImg(this._centerSmallImg,this._centerImg,this.zoom==1?this.panX<0?1:this.panX>0?-1:
0:0);this.zoom==1&&this.panX!=0&&(this.panX>0?this._renderImg(this._leftSmallImg,this._leftImg,1):this._renderImg(this._rightSmallImg,this._rightImg,-1))},_renderImg:function(a,b,c){if((a=b&&b._loaded?b:a)&&a._loaded){var b=this.canvas.getContext("2d"),d=a._baseWidth*this.zoom,f=a._baseHeight*this.zoom,e=Math.min(this.size.w,d),i=Math.min(this.size.h,f),d=this.dispWidth=a.width*(e/d),f=this.dispHeight=a.height*(i/f),g=Math.max(0,Math.round((a.width-d)/2+(Math.floor(Math.max(d/2,Math.min(a.width-d/
2,this.zoomCenterX-this.panX/this.zoom)))-a._centerX))),l=Math.max(0,Math.round((a.height-f)/2+(Math.floor(Math.max(f/2,Math.min(a.height-f/2,this.zoomCenterY-this.panY/this.zoom)))-a._centerY))),h=Math.round(Math.max(0,this.canvas.width-e)/2),m=Math.round(Math.max(0,this.canvas.height-i)/2),j=e,k=d;this.zoom==1&&c&&this.panX&&(this.panX<0?c>0?(e-=Math.abs(this.panX),h=0):c<0&&(e=Math.max(1,Math.abs(this.panX)-5),h=this.size.w-e):c>0?(e=Math.max(1,Math.abs(this.panX)-5),h=0):c<0&&(e-=Math.abs(this.panX),
h=this.size.w-e),d=Math.max(1,Math.floor(d*(e/j))),c>0&&(g=g+k-d),g=Math.floor(g));try{b.drawImage(a,Math.max(0,g),l,Math.min(k,d),f,h,m,Math.min(j,e),i)}catch(n){console.log("Caught Error",n,"type=",a._type,"oldDestWidth = ",j,"destWidth",e,"destX",h,"oldSourceWidth=",k,"sourceWidth=",d,"sourceX = "+g)}}},_setZoomAttr:function(a){this.zoom=Math.min(this.maxZoom,Math.max(1,a));if(this.zoom==1&&this._centerImg&&this._centerImg._loaded){if(!this.isAnimating())this.zoomCenterX=this._centerImg.width/
2,this.zoomCenterY=this._centerImg.height/2;this.panX=this.panY=0}this.render()},_setZoomCenterXAttr:function(a){if(a!=this.zoomCenterX)this._centerImg&&this._centerImg._loaded&&(a=Math.min(this._centerImg.width,a)),this.zoomCenterX=Math.max(0,Math.round(a))},_setZoomCenterYAttr:function(a){if(a!=this.zoomCenterY)this._centerImg&&this._centerImg._loaded&&(a=Math.min(this._centerImg.height,a)),this.zoomCenterY=Math.max(0,Math.round(a))},_setZoomCenterAttr:function(a){if(a.x!=this.zoomCenterX||a.y!=
this.zoomCenterY)this.set("zoomCenterX",a.x),this.set("zoomCenterY",a.y),this.render()},_setAnimatedZoomAttr:function(a){if(!(this._anim&&this._anim.status()=="playing"))this._anim=new dojo.Animation({curve:[this.zoom,a],onAnimate:this._updateAnimatedZoom,onEnd:this._onAnimEnd}),this._anim.play()},_updateAnimatedZoom:function(a){this._setZoomAttr(a)},_setCenterUrlAttr:function(a){this._setImage("center",a)},_setLeftUrlAttr:function(a){this._setImage("left",a)},_setRightUrlAttr:function(a){this._setImage("right",
a)},_setImage:function(a,b){var c=null,d=null;dojo.isString(b)?d=b:(d=b.large,c=b.small);if(!(this["_"+a+"Img"]&&this["_"+a+"Img"]._src==d)){var f=this["_"+a+"Img"]=new Image;f._type=a;f._loaded=!1;f._src=d;f._conn=dojo.connect(f,"onload",this.handleLoad);if(c){var e=this["_"+a+"SmallImg"]=new Image;e._type=a;e._loaded=!1;e._conn=dojo.connect(e,"onload",this.handleLoad);e._isSmall=!0;e._src=c;e.src=c}f.src=d}},handleLoad:function(a){a=a.target;a._loaded=!0;dojo.disconnect(a._conn);switch(a._type){case "center":this.zoomCenterX=
a.width/2,this.zoomCenterY=a.height/2}var b=a.height,c=a.width;c/this.size.w<b/this.size.h?(a._baseHeight=this.canvas.height,a._baseWidth=c/(b/this.size.h)):(a._baseWidth=this.canvas.width,a._baseHeight=b/(c/this.size.w));a._centerX=c/2;a._centerY=b/2;this.render();this.onLoad(a._type,a._src,a._isSmall)},onLoad:function(){}}));