/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.app.List"]||(dojo._hasResource["dojox.mobile.app.List"]=!0,dojo.provide("dojox.mobile.app.List"),dojo.experimental("dojox.mobile.app.List"),dojo.require("dojo.string"),dojo.require("dijit._WidgetBase"),function(){var f={};dojo.declare("dojox.mobile.app.List",dijit._WidgetBase,{items:null,itemTemplate:"",emptyTemplate:"",dividerTemplate:"",dividerFunction:null,labelDelete:"Delete",labelCancel:"Cancel",controller:null,autoDelete:!0,enableDelete:!0,enableHold:!0,formatters:null,
_templateLoadCount:0,_mouseDownPos:null,baseClass:"list",constructor:function(){this._checkLoadComplete=dojo.hitch(this,this._checkLoadComplete);this._replaceToken=dojo.hitch(this,this._replaceToken);this._postDeleteAnim=dojo.hitch(this,this._postDeleteAnim)},postCreate:function(){var a=this;this.emptyTemplate&&this._templateLoadCount++;this.itemTemplate&&this._templateLoadCount++;this.dividerTemplate&&this._templateLoadCount++;this.connect(this.domNode,"onmousedown",function(b){var c=b;b.targetTouches&&
b.targetTouches.length>0&&(c=b.targetTouches[0]);var e=a._getRowNode(b.target);if(e)a._setDataInfo(e,b),a._selectRow(e),a._mouseDownPos={x:c.pageX,y:c.pageY},a._dragThreshold=null});this.connect(this.domNode,"onmouseup",function(b){b.targetTouches&&b.targetTouches.length>0&&(b=b.targetTouches[0]);var c=a._getRowNode(b.target);if(c){a._setDataInfo(c,b);if(a._selectedRow)a.onSelect(c._data,c._idx,c);this._deselectRow()}});this.enableDelete&&this.connect(this.domNode,"mousemove",function(b){dojo.stopEvent(b);
if(a._selectedRow){var c=a._getRowNode(b.target);a.enableDelete&&c&&!a._deleting&&a.handleDrag(b)}});this.connect(this.domNode,"onclick",function(b){b.touches&&b.touches.length>0&&(b=b.touches[0]);var c=a._getRowNode(b.target,!0);c&&a._setDataInfo(c,b)});this.connect(this.domNode,"mouseout",function(b){b.touches&&b.touches.length>0&&(b=b.touches[0]);b.target==a._selectedRow&&a._deselectRow()});if(!this.itemTemplate)throw Error("An item template must be provided to "+this.declaredClass);this._loadTemplate(this.itemTemplate,
"itemTemplate",this._checkLoadComplete);this.emptyTemplate&&this._loadTemplate(this.emptyTemplate,"emptyTemplate",this._checkLoadComplete);this.dividerTemplate&&this._loadTemplate(this.dividerTemplate,"dividerTemplate",this._checkLoadComplete)},handleDrag:function(a){var b=a;a.targetTouches&&a.targetTouches.length>0&&(b=a.targetTouches[0]);a=b.pageX-this._mouseDownPos.x;b=Math.abs(a);if(b>10&&!this._dragThreshold)this._dragThreshold=dojo.marginBox(this._selectedRow).w*0.6,this.autoDelete||this.createDeleteButtons(this._selectedRow);
this._selectedRow.style.left=(b>10?a:0)+"px";this._dragThreshold&&this._dragThreshold<b&&this.preDelete(a)},handleDragCancel:function(){if(!this._deleting)dojo.removeClass(this._selectedRow,"hold"),this._selectedRow.style.left=0,this._dragThreshold=this._mouseDownPos=null,this._deleteBtns&&dojo.style(this._deleteBtns,"display","none")},preDelete:function(a){this._deleting=!0;dojo.animateProperty({node:this._selectedRow,duration:400,properties:{left:{end:a+(a>0?1:-1)*this._dragThreshold*0.8}},onEnd:dojo.hitch(this,
function(){this.autoDelete&&this.deleteRow(this._selectedRow)})}).play()},deleteRow:function(a){dojo.style(a,{visibility:"hidden",minHeight:"0px"});dojo.removeClass(a,"hold");this._deleteAnimConn=this.connect(a,"webkitAnimationEnd",this._postDeleteAnim);dojo.addClass(a,"collapsed")},_postDeleteAnim:function(){if(this._deleteAnimConn)this.disconnect(this._deleteAnimConn),this._deleteAnimConn=null;var a=this._selectedRow,b=a.nextSibling,c=a.previousSibling;c&&c._isDivider&&(!b||b._isDivider)&&c.parentNode.removeChild(c);
a.parentNode.removeChild(a);for(this.onDelete(a._data,a._idx,this.items);b;)b._idx&&b._idx--,b=b.nextSibling;dojo.destroy(a);dojo.query("> *:not(.buttons)",this.domNode).forEach(this.applyClass);this._deleting=!1;this._deselectRow()},createDeleteButtons:function(a){var b=dojo.marginBox(a);dojo._abs(a,!0);if(!this._deleteBtns)this._deleteBtns=dojo.create("div",{"class":"buttons"},this.domNode),this.buttons=[],this.buttons.push(new dojox.mobile.Button({btnClass:"mblRedButton",label:this.labelDelete})),
this.buttons.push(new dojox.mobile.Button({btnClass:"mblBlueButton",label:this.labelCancel})),dojo.place(this.buttons[0].domNode,this._deleteBtns),dojo.place(this.buttons[1].domNode,this._deleteBtns),dojo.addClass(this.buttons[0].domNode,"deleteBtn"),dojo.addClass(this.buttons[1].domNode,"cancelBtn"),this._handleButtonClick=dojo.hitch(this._handleButtonClick),this.connect(this._deleteBtns,"onclick",this._handleButtonClick);dojo.removeClass(this._deleteBtns,"fade out fast");dojo.style(this._deleteBtns,
{display:"",width:b.w+"px",height:b.h+"px",top:a.offsetTop+"px",left:"0px"})},onDelete:function(a,b,c){c.splice(b,1);c.length<1&&this.render()},cancelDelete:function(){this._deleting=!1;this.handleDragCancel()},_handleButtonClick:function(a){a.touches&&a.touches.length>0&&(a=a.touches[0]);a=a.target;if(dojo.hasClass(a,"deleteBtn"))this.deleteRow(this._selectedRow);else if(dojo.hasClass(a,"cancelBtn"))this.cancelDelete();else return;dojo.addClass(this._deleteBtns,"fade out")},applyClass:function(a,
b,c){dojo.removeClass(a,"first last");b==0&&dojo.addClass(a,"first");b==c.length-1&&dojo.addClass(a,"last")},_setDataInfo:function(a,b){b.item=a._data;b.index=a._idx},onSelect:function(){},_selectRow:function(a){this._deleting&&this._selectedRow&&a!=this._selectedRow&&this.cancelDelete();if(dojo.hasClass(a,"row"))(this.enableHold||this.enableDelete)&&dojo.addClass(a,"hold"),this._selectedRow=a},_deselectRow:function(){if(this._selectedRow&&!this._deleting)this.handleDragCancel(),dojo.removeClass(this._selectedRow,
"hold"),this._selectedRow=null},_getRowNode:function(a,b){for(;a&&!a._data&&a!=this.domNode;){if(!b&&dojo.hasClass(a,"noclick"))return null;a=a.parentNode}return a==this.domNode?null:a},applyTemplate:function(a,b){return dojo._toDom(dojo.string.substitute(a,b,this._replaceToken,this.formatters||this))},render:function(){dojo.query("> *:not(.buttons)",this.domNode).forEach(dojo.destroy);this.items.length<1&&this.emptyTemplate?dojo.place(dojo._toDom(this.emptyTemplate),this.domNode,"first"):this.domNode.appendChild(this._renderRange(0,
this.items.length));dojo.hasClass(this.domNode.parentNode,"mblRoundRect")&&dojo.addClass(this.domNode.parentNode,"mblRoundRectList");var a=dojo.query("> .row",this.domNode);a.length>0&&(dojo.addClass(a[0],"first"),dojo.addClass(a[a.length-1],"last"))},_renderRange:function(a,b){var c=[],e,d,f=document.createDocumentFragment(),a=Math.max(0,a),b=Math.min(b,this.items.length);for(d=a;d<b;d++)e=this.applyTemplate(this.itemTemplate,this.items[d]),dojo.addClass(e,"row"),e._data=this.items[d],e._idx=d,c.push(e);
if(!this.dividerFunction||!this.dividerTemplate)for(d=a;d<b;d++)c[d]._data=this.items[d],c[d]._idx=d,f.appendChild(c[d]);else{var g=null;for(d=a;d<b;d++){c[d]._data=this.items[d];c[d]._idx=d;if((e=this.dividerFunction(this.items[d]))&&e!=g)g=this.applyTemplate(this.dividerTemplate,{label:e,item:this.items[d]}),g._isDivider=!0,f.appendChild(g),g=e;f.appendChild(c[d])}}return f},_replaceToken:function(a,b){b.charAt(0)=="!"&&(a=dojo.getObject(b.substr(1),!1,_this));return typeof a=="undefined"?"":a==
null?"":b.charAt(0)=="!"?a:a.toString().replace(/"/g,"&quot;")},_checkLoadComplete:function(){this._templateLoadCount--;this._templateLoadCount<1&&this.get("items")&&this.render()},_loadTemplate:function(a,b,c){if(a)if(f[a])this.set(b,f[a]),c();else{var e=this;dojo.xhrGet({url:a,sync:!1,handleAs:"text",load:function(d){f[a]=dojo.trim(d);e.set(b,f[a]);c()}})}else c()},_setFormattersAttr:function(a){this.formatters=a},_setItemsAttr:function(a){this.items=a||[];this._templateLoadCount<1&&a&&this.render()},
destroy:function(){if(this.buttons)dojo.forEach(this.buttons,function(a){a.destroy()}),this.buttons=null;this.inherited(arguments)}})}());