/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mobile.app.TextBox"]||(dojo._hasResource["dojox.mobile.app.TextBox"]=!0,dojo.provide("dojox.mobile.app.TextBox"),dojo.experimental("dojox.mobile.app.TextBox"),dojo.require("dojox.mobile.app._Widget"),dojo.require("dojox.mobile.app._FormWidget"),dojo.declare("dojox.mobile.app.TextBox",dojox.mobile.app._FormValueWidget,{trim:!1,uppercase:!1,lowercase:!1,propercase:!1,maxLength:"",selectOnClick:!1,placeHolder:"",baseClass:"mblTextBox",attributeMap:dojo.delegate(dojox.mobile.app._FormValueWidget.prototype.attributeMap,
{maxLength:"focusNode"}),buildRendering:function(){var a=this.srcNodeRef;if(!a||a.tagName!="INPUT")a=dojo.create("input",{});dojo.attr(a,{type:"text",value:dojo.attr(a,"value")||"",placeholder:this.placeHolder||null});this.domNode=this.textbox=this.focusNode=a},_setPlaceHolderAttr:function(a){this.placeHolder=a;this.textbox&&dojo.attr(this.textbox,"placeholder",a)},_getValueAttr:function(){return this.parse(this.get("displayedValue"),this.constraints)},_setValueAttr:function(a,d,b){var c;a!==void 0&&
(c=this.filter(a),typeof b!="string"&&(b=c!==null&&(typeof c!="number"||!isNaN(c))?this.filter(this.format(c,this.constraints)):""));if(b!=null&&b!=void 0&&(typeof b!="number"||!isNaN(b))&&this.textbox.value!=b)this.textbox.value=b;this.inherited(arguments,[c,d])},displayedValue:"",_getDisplayedValueAttr:function(){return this.filter(this.textbox.value)},_setDisplayedValueAttr:function(a){a===null||a===void 0?a="":typeof a!="string"&&(a=String(a));this.textbox.value=a;this._setValueAttr(this.get("value"),
void 0,a)},format:function(a){return a==null||a==void 0?"":a.toString?a.toString():a},parse:function(a){return a},_refreshState:function(){},_onInput:function(a){if(a&&a.type&&/key/i.test(a.type)&&a.keyCode)switch(a.keyCode){case dojo.keys.SHIFT:case dojo.keys.ALT:case dojo.keys.CTRL:case dojo.keys.TAB:return}if(this.intermediateChanges){var d=this;setTimeout(function(){d._handleOnChange(d.get("value"),!1)},0)}this._refreshState()},postCreate:function(){this.textbox.setAttribute("value",this.textbox.value);
this.inherited(arguments);dojo.isMoz||dojo.isOpera?this.connect(this.textbox,"oninput",this._onInput):(this.connect(this.textbox,"onkeydown",this._onInput),this.connect(this.textbox,"onkeyup",this._onInput),this.connect(this.textbox,"onpaste",this._onInput),this.connect(this.textbox,"oncut",this._onInput))},_blankValue:"",filter:function(a){if(a===null)return this._blankValue;if(typeof a!="string")return a;this.trim&&(a=dojo.trim(a));this.uppercase&&(a=a.toUpperCase());this.lowercase&&(a=a.toLowerCase());
this.propercase&&(a=a.replace(/[^\s]+/g,function(a){return a.substring(0,1).toUpperCase()+a.substring(1)}));return a},_setBlurValue:function(){this._setValueAttr(this.get("value"),!0)},_onBlur:function(a){if(!this.disabled&&(this._setBlurValue(),this.inherited(arguments),this._selectOnClickHandle&&this.disconnect(this._selectOnClickHandle),this.selectOnClick&&dojo.isMoz))this.textbox.selectionStart=this.textbox.selectionEnd=void 0},_onFocus:function(a){if(!this.disabled&&!this.readOnly){if(this.selectOnClick&&
a=="mouse")this._selectOnClickHandle=this.connect(this.domNode,"onmouseup",function(){this.disconnect(this._selectOnClickHandle);this.textbox.selectionStart==this.textbox.selectionEnd&&this.selectInputText(this.textbox)});this._refreshState();this.inherited(arguments)}},reset:function(){this.textbox.value="";this.inherited(arguments)}}));