/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.io.proxy.xip"])dojo._hasResource["dojox.io.proxy.xip"]=!0,dojo.provide("dojox.io.proxy.xip"),dojo.require("dojo.io.iframe"),dojo.require("dojox.data.dom"),dojox.io.proxy.xip={xipClientUrl:(dojo.config||djConfig).xipClientUrl||dojo.moduleUrl("dojox.io.proxy","xip_client.html"),urlLimit:4E3,_callbackName:(dojox._scopeName||"dojox")+".io.proxy.xip.fragmentReceived",_state:{},_stateIdCounter:0,_isWebKit:navigator.userAgent.indexOf("WebKit")!=-1,send:function(a){var b=this.xipClientUrl;
if(!b.split(":")[0].match(/javascript/i)&&!a._ifpServerUrl.split(":")[0].match(/javascript/i)){var c=b.indexOf(":"),d=b.indexOf("/");if(c==-1||d<c)c=window.location.href,b=d==0?c.substring(0,c.indexOf("/",9))+b:c.substring(0,c.lastIndexOf("/")+1)+b;this.fullXipClientUrl=b;typeof document.postMessage!="undefined"&&document.addEventListener("message",dojo.hitch(this,this.fragmentReceivedEvent),!1);this.send=this._realSend;return this._realSend(a)}},_realSend:function(a){var b="XhrIframeProxy"+this._stateIdCounter++;
a._stateId=b;var c=a._ifpServerUrl+"#0:init:id="+b+"&client="+encodeURIComponent(this.fullXipClientUrl)+"&callback="+encodeURIComponent(this._callbackName);this._state[b]={facade:a,stateId:b,clientFrame:dojo.io.iframe.create(b,"",c),isSending:!1,serverUrl:a._ifpServerUrl,requestData:null,responseMessage:"",requestParts:[],idCounter:1,partIndex:0,serverWindow:null};return b},receive:function(a,b){for(var c={},d=b.split("&"),f=0;f<d.length;f++)if(d[f]){var e=d[f].split("=");c[decodeURIComponent(e[0])]=
decodeURIComponent(e[1])}d=this._state[a].facade;d._setResponseHeaders(c.responseHeaders);if(c.status==0||c.status)d.status=parseInt(c.status,10);if(c.statusText)d.statusText=c.statusText;if(c.responseText&&(d.responseText=c.responseText,f=d.getResponseHeader("Content-Type")))if(e=f.split(";")[0],e.indexOf("application/xml")==0||e.indexOf("text/xml")==0)d.responseXML=dojox.data.dom.createDocument(c.responseText,f);d.readyState=4;this.destroyState(a)},frameLoaded:function(a){var b=this._state[a].facade,
c=[],d;for(d in b._requestHeaders)c.push(d+": "+b._requestHeaders[d]);d={uri:b._uri};if(c.length>0)d.requestHeaders=c.join("\r\n");if(b._method)d.method=b._method;if(b._bodyData)d.data=b._bodyData;this.sendRequest(a,dojo.objectToQuery(d))},destroyState:function(a){var b=this._state[a];if(b)delete this._state[a],b.clientFrame.parentNode.removeChild(b.clientFrame),b.clientFrame=null},createFacade:function(){return arguments&&arguments[0]&&arguments[0].iframeProxyUrl?new dojox.io.proxy.xip.XhrIframeFacade(arguments[0].iframeProxyUrl):
dojox.io.proxy.xip._xhrObjOld.apply(dojo,arguments)},sendRequest:function(a,b){var c=this._state[a];if(!c.isSending){c.isSending=!0;c.requestData=b||"";c.serverWindow=frames[c.stateId];if(!c.serverWindow)c.serverWindow=document.getElementById(c.stateId).contentWindow;if(typeof document.postMessage=="undefined"&&c.serverWindow.contentWindow)c.serverWindow=c.serverWindow.contentWindow;this.sendRequestStart(a)}},sendRequestStart:function(a){var b=this._state[a];b.requestParts=[];for(var c=b.requestData,
d=b.serverUrl.length,f=this.urlLimit-d,e=0;c.length-e+d>this.urlLimit;){var g=c.substring(e,e+f),h=g.lastIndexOf("%");if(h==g.length-1||h==g.length-2)g=g.substring(0,h);b.requestParts.push(g);e+=g.length}b.requestParts.push(c.substring(e,c.length));b.partIndex=0;this.sendRequestPart(a)},sendRequestPart:function(a){var b=this._state[a];if(b.partIndex<b.requestParts.length){var c=b.requestParts[b.partIndex],d="part";b.partIndex+1==b.requestParts.length?d="end":b.partIndex==0&&(d="start");this.setServerUrl(a,
d,c);b.partIndex++}},setServerUrl:function(a,b,c){b=this.makeServerUrl(a,b,c);a=this._state[a];this._isWebKit?a.serverWindow.location=b:a.serverWindow.location.replace(b)},makeServerUrl:function(a,b,c){a=this._state[a];b=a.serverUrl+"#"+a.idCounter++ +":"+b;c&&(b+=":"+c);return b},fragmentReceivedEvent:function(a){a.uri.split("#")[0]==this.fullXipClientUrl&&this.fragmentReceived(a.data)},fragmentReceived:function(a){var b=a.indexOf("#"),c=a.substring(0,b),a=this.unpackMessage(a.substring(b+1,a.length)),
b=this._state[c];switch(a.command){case "loaded":this.frameLoaded(c);break;case "ok":this.sendRequestPart(c);break;case "start":b.responseMessage=""+a.message;this.setServerUrl(c,"ok");break;case "part":b.responseMessage+=a.message;this.setServerUrl(c,"ok");break;case "end":this.setServerUrl(c,"ok"),b.responseMessage+=a.message,this.receive(c,b.responseMessage)}},unpackMessage:function(a){var a=a.split(":"),b=a[1],a=a[2]||"",c=null;if(b=="init")for(var d=a.split("&"),c={},f=0;f<d.length;f++){var e=
d[f].split("=");c[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}return{command:b,message:a,config:c}}},dojox.io.proxy.xip._xhrObjOld=dojo._xhrObj,dojo._xhrObj=dojox.io.proxy.xip.createFacade,dojox.io.proxy.xip.XhrIframeFacade=function(a){this._requestHeaders={};this._allResponseHeaders=null;this._responseHeaders={};this.statusText=this.status=this.responseXML=this.responseText=this._bodyData=this._uri=this._method=null;this.readyState=0;this._ifpServerUrl=a;this._stateId=null},dojo.extend(dojox.io.proxy.xip.XhrIframeFacade,
{open:function(a,b){this._method=a;this._uri=b;this.readyState=1},setRequestHeader:function(a,b){this._requestHeaders[a]=b},send:function(a){this._bodyData=a;this._stateId=dojox.io.proxy.xip.send(this);this.readyState=2},abort:function(){dojox.io.proxy.xip.destroyState(this._stateId)},getAllResponseHeaders:function(){return this._allResponseHeaders},getResponseHeader:function(a){return this._responseHeaders[a]},_setResponseHeaders:function(a){if(a){this._allResponseHeaders=a;for(var a=a.replace(/\r/g,
""),a=a.split("\n"),b=0;b<a.length;b++)if(a[b]){var c=a[b].split(": ");this._responseHeaders[c[0]]=c[1]}}}});