/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.av.widget.Player"]||(dojo._hasResource["dojox.av.widget.Player"]=!0,dojo.provide("dojox.av.widget.Player"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.declare("dojox.av.widget.Player",[dijit._Widget,dijit._Templated],{playerWidth:"480px",widgetsInTemplate:!0,templateString:dojo.cache("dojox.av.widget","resources/Player.html",'<div class="playerContainer">\n\t<div class="PlayerScreen" dojoAttachPoint="playerScreen"></div>\n\t<table class="Controls">\n\t\t<tr>\n\t\t\t<td colspan="2" dojoAttachPoint="progressContainer"></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td class="PlayContainer" dojoAttachPoint="playContainer"></td>\n\t\t\t<td class="ControlsRight">\n\t\t\t<table class="StatusContainer">\n\t\t\t\t<tr dojoAttachPoint="statusContainer">\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td colspan="3" class="ControlsBottom" dojoAttachPoint="controlsBottom"></td>\n\t\t\t\t</tr>\n\t\t\t</table>\n\t\t</td>\n\t\t</tr>\n\t</table>\n</div>\n'),
_fillContent:function(){if(!this.items&&this.srcNodeRef){this.items=[];var a=dojo.query("*",this.srcNodeRef);dojo.forEach(a,function(a){this.items.push(a)},this)}},postCreate:function(){dojo.style(this.domNode,"width",this.playerWidth+(dojo.isString(this.playerWidth)?"":"px"));dojo.isString(this.playerWidth)&&this.playerWidth.indexOf("%")&&dojo.connect(window,"resize",this,"onResize");this.children=[];dojo.forEach(this.items,function(a,b){a.id=dijit.getUniqueId("player_control");switch(dojo.attr(a,
"controlType")){case "play":this.playContainer.appendChild(a);break;case "volume":this.controlsBottom.appendChild(a);break;case "status":this.statusContainer.appendChild(a);break;case "progress":case "slider":this.progressContainer.appendChild(a);break;case "video":this.mediaNode=a,this.playerScreen.appendChild(a)}this.items[b]=a.id},this)},startup:function(){this.media=dijit.byId(this.mediaNode.id);dojo.isAIR||(dojo.style(this.media.domNode,"width","100%"),dojo.style(this.media.domNode,"height",
"100%"));dojo.forEach(this.items,function(a){a!==this.mediaNode.id&&(a=dijit.byId(a),this.children.push(a),a&&a.setMedia(this.media,this))},this)},onResize:function(){var a=dojo.marginBox(this.domNode);if(this.media&&this.media.onResize!==null)this.media.onResize(a);dojo.forEach(this.children,function(b){if(b.onResize)b.onResize(a)})}}));