/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.av.widget.ProgressSlider"]||(dojo._hasResource["dojox.av.widget.ProgressSlider"]=!0,dojo.provide("dojox.av.widget.ProgressSlider"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.declare("dojox.av.widget.ProgressSlider",[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.av.widget","resources/ProgressSlider.html",'<div class="Progress" dojoAttachEvent="mousedown:startDrag">\n    \n    <div class="ProgressLoaded" dojoAttachPoint="progressLoaded"></div>\n    <div class="ProgressPosition" dojoAttachPoint="progressPosition"></div>\n\t<div class="ProgressHandle" dojoAttachPoint="handle" dojoAttachEvent="mouseover:handleOver, mouseout:handleOut"></div>\n</div>\n'),
postCreate:function(){this.seeking=!1;this.handleWidth=dojo.marginBox(this.handle).w;var a=dojo.coords(this.domNode);this.finalWidth=a.w;this.width=a.w-this.handleWidth;this.x=a.x;dojo.setSelectable(this.domNode,!1);dojo.setSelectable(this.handle,!1)},setMedia:function(a,b){this.playerWidget=b;this.media=a;dojo.connect(this.media,"onMetaData",this,function(a){if(a&&a.duration)this.duration=a.duration});dojo.connect(this.media,"onEnd",this,function(){dojo.disconnect(this.posCon);this.setHandle(this.duration)});
dojo.connect(this.media,"onStart",this,function(){this.posCon=dojo.connect(this.media,"onPosition",this,"setHandle")});dojo.connect(this.media,"onDownloaded",this,function(a){this.setLoadedPosition(a*0.01);this.width=this.finalWidth*0.01*a})},onDrag:function(a){a=a.clientX-this.x;a<0&&(a=0);a>this.width-this.handleWidth&&(a=this.width-this.handleWidth);this.media.seek(this.duration*(a/this.finalWidth));dojo.style(this.handle,"marginLeft",a+"px");dojo.style(this.progressPosition,"width",a+"px")},startDrag:function(){dojo.setSelectable(this.playerWidget.domNode,
!1);this.seeking=!0;this.cmove=dojo.connect(dojo.doc,"mousemove",this,"onDrag");this.cup=dojo.connect(dojo.doc,"mouseup",this,"endDrag")},endDrag:function(){dojo.setSelectable(this.playerWidget.domNode,!0);this.seeking=!1;this.cmove&&dojo.disconnect(this.cmove);this.cup&&dojo.disconnect(this.cup);this.handleOut()},setHandle:function(a){this.seeking||(a=a/this.duration*(this.width-this.handleWidth),dojo.style(this.handle,"marginLeft",a+"px"),dojo.style(this.progressPosition,"width",a+"px"))},setLoadedPosition:function(a){dojo.style(this.progressLoaded,
"width",this.finalWidth*a+"px")},handleOver:function(){dojo.addClass(this.handle,"over")},handleOut:function(){this.seeking||dojo.removeClass(this.handle,"over")},onResize:function(){this.finalWidth=dojo.coords(this.domNode).w}}));