/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.av.widget.VolumeButton"]||(dojo._hasResource["dojox.av.widget.VolumeButton"]=!0,dojo.provide("dojox.av.widget.VolumeButton"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dijit.form.Button"),dojo.declare("dojox.av.widget.VolumeButton",[dijit._Widget,dijit._Templated],{templateString:dojo.cache("dojox.av.widget","resources/VolumeButton.html",'<div class="Volume" dojoAttachEvent="mousedown:onShowVolume">\n\t<div class="VolumeSlider" dojoAttachPoint="volumeSlider">\n    \t<div class="VolumeSliderBack" dojoAttachPoint="volumeSliderBack"></div>\n    \t<div class="VolumeSliderHandle" dojoAttachPoint="handle" dojoAttachEvent="mousedown:startDrag, mouseup:endDrag, mouseover:handleOver, mouseout:handleOut"></div>\t\n    </div>\n    <div class="icon"></div>\n</div>\n'),
postCreate:function(){this.handleWidth=dojo.marginBox(this.handle).w;this.width=dojo.marginBox(this.volumeSlider).w;this.slotWidth=100;dojo.setSelectable(this.handle,!1);this.volumeSlider=this.domNode.removeChild(this.volumeSlider)},setMedia:function(a){this.media=a;this.updateIcon()},updateIcon:function(a){a=a===void 0?this.media.volume():a;a===0?dojo.attr(this.domNode,"class","Volume mute"):a<0.334?dojo.attr(this.domNode,"class","Volume low"):a<0.667?dojo.attr(this.domNode,"class","Volume med"):
dojo.attr(this.domNode,"class","Volume high")},onShowVolume:function(){if(this.showing==void 0)dojo.body().appendChild(this.volumeSlider),this.showing=!1;if(this.showing)this.onHideVolume();else{var a=this.media.volume(),b=this._getVolumeDim(),c=this._getHandleDim();this.x=b.x-this.width;dojo.style(this.volumeSlider,"display","");dojo.style(this.volumeSlider,"top",b.y+"px");dojo.style(this.volumeSlider,"left",this.x+"px");a*=this.slotWidth;dojo.style(this.handle,"top",2+c.w/2+"px");dojo.style(this.handle,
"left",a+7+c.h/2+"px");this.showing=!0;this.clickOff=dojo.connect(dojo.doc,"onmousedown",this,"onDocClick")}},onDocClick:function(a){if(!dojo.isDescendant(a.target,this.domNode)&&!dojo.isDescendant(a.target,this.volumeSlider))this.onHideVolume()},onHideVolume:function(){this.endDrag();dojo.style(this.volumeSlider,"display","none");this.showing=!1},onDrag:function(a){var b=this.handleWidth/2,c=b+this.slotWidth,a=a.clientX-this.x;a<b&&(a=b);a>c&&(a=c);dojo.style(this.handle,"left",a+"px");b=(a-b)/(c-
b);this.media.volume(b);this.updateIcon(b)},startDrag:function(){this.isDragging=!0;this.cmove=dojo.connect(dojo.doc,"mousemove",this,"onDrag");this.cup=dojo.connect(dojo.doc,"mouseup",this,"endDrag")},endDrag:function(){this.isDragging=!1;this.cmove&&dojo.disconnect(this.cmove);this.cup&&dojo.disconnect(this.cup);this.handleOut()},handleOver:function(){dojo.addClass(this.handle,"over")},handleOut:function(){this.isDragging||dojo.removeClass(this.handle,"over")},_getVolumeDim:function(){return this._domCoords?
this._domCoords:this._domCoords=dojo.coords(this.domNode)},_getHandleDim:function(){return this._handleCoords?this._handleCoords:this._handleCoords=dojo.marginBox(this.handle)},onResize:function(){this.onHideVolume();this._domCoords=null}}));