/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dijit.layout._LayoutWidget"])dojo._hasResource["dijit.layout._LayoutWidget"]=!0,dojo.provide("dijit.layout._LayoutWidget"),dojo.require("dijit._Widget"),dojo.require("dijit._Container"),dojo.require("dijit._Contained"),dojo.declare("dijit.layout._LayoutWidget",[dijit._Widget,dijit._Container,dijit._Contained],{baseClass:"dijitLayoutContainer",isLayoutContainer:!0,buildRendering:function(){this.inherited(arguments);dojo.addClass(this.domNode,"dijitContainer")},startup:function(){if(!this._started){this.inherited(arguments);
var a=this.getParent&&this.getParent();if(!a||!a.isLayoutContainer)this.resize(),this.connect(dojo.isIE?this.domNode:dojo.global,"onresize",function(){this.resize()})}},resize:function(a,d){var b=this.domNode;if(a){dojo.marginBox(b,a);if(a.t)b.style.top=a.t+"px";if(a.l)b.style.left=a.l+"px"}var c=d||{};dojo.mixin(c,a||{});if(!("h"in c)||!("w"in c))c=dojo.mixin(dojo.marginBox(b),c);var e=dojo.getComputedStyle(b),h=dojo._getMarginExtents(b,e),i=dojo._getBorderExtents(b,e),c=this._borderBox={w:c.w-(h.w+
i.w),h:c.h-(h.h+i.h)},h=dojo._getPadExtents(b,e);this._contentBox={l:dojo._toPixelValue(b,e.paddingLeft),t:dojo._toPixelValue(b,e.paddingTop),w:c.w-h.w,h:c.h-h.h};this.layout()},layout:function(){},_setupChild:function(a){dojo.addClass(a.domNode,this.baseClass+"-child "+(a.baseClass?this.baseClass+"-"+a.baseClass:""))},addChild:function(a,d){this.inherited(arguments);this._started&&this._setupChild(a)},removeChild:function(a){dojo.removeClass(a.domNode,this.baseClass+"-child"+(a.baseClass?" "+this.baseClass+
"-"+a.baseClass:""));this.inherited(arguments)}}),dijit.layout.marginBox2contentBox=function(a,d){var b=dojo.getComputedStyle(a),c=dojo._getMarginExtents(a,b),e=dojo._getPadBorderExtents(a,b);return{l:dojo._toPixelValue(a,b.paddingLeft),t:dojo._toPixelValue(a,b.paddingTop),w:d.w-(c.w+e.w),h:d.h-(c.h+e.h)}},function(){var a=function(a,b){var c=a.resize?a.resize(b):dojo.marginBox(a.domNode,b);c?dojo.mixin(a,c):(dojo.mixin(a,dojo.marginBox(a.domNode)),dojo.mixin(a,b))};dijit.layout.layoutChildren=function(d,
b,c,e,h){b=dojo.mixin({},b);dojo.addClass(d,"dijitLayoutContainer");c=dojo.filter(c,function(a){return a.region!="center"&&a.layoutAlign!="client"}).concat(dojo.filter(c,function(a){return a.region=="center"||a.layoutAlign=="client"}));dojo.forEach(c,function(c){var g=c.domNode,f=c.region||c.layoutAlign,d=g.style;d.left=b.l+"px";d.top=b.t+"px";d.position="absolute";dojo.addClass(g,"dijitAlign"+(f.substring(0,1).toUpperCase()+f.substring(1)));g={};e&&e==c.id&&(g[c.region=="top"||c.region=="bottom"?
"h":"w"]=h);f=="top"||f=="bottom"?(g.w=b.w,a(c,g),b.h-=c.h,f=="top"?b.t+=c.h:d.top=b.t+b.h+"px"):f=="left"||f=="right"?(g.h=b.h,a(c,g),b.w-=c.w,f=="left"?b.l+=c.w:d.left=b.l+b.w+"px"):(f=="client"||f=="center")&&a(c,b)})}}();