/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.layout._TabContainerBase"]||(dojo._hasResource["dijit.layout._TabContainerBase"]=!0,dojo.provide("dijit.layout._TabContainerBase"),dojo.require("dijit.layout.StackContainer"),dojo.require("dijit._Templated"),dojo.declare("dijit.layout._TabContainerBase",[dijit.layout.StackContainer,dijit._Templated],{tabPosition:"top",baseClass:"dijitTabContainer",tabStrip:!1,nested:!1,templateString:dojo.cache("dijit.layout","templates/TabContainer.html",'<div class="dijitTabContainer">\n\t<div class="dijitTabListWrapper" dojoAttachPoint="tablistNode"></div>\n\t<div dojoAttachPoint="tablistSpacer" class="dijitTabSpacer ${baseClass}-spacer"></div>\n\t<div class="dijitTabPaneWrapper ${baseClass}-container" dojoAttachPoint="containerNode"></div>\n</div>\n'),
postMixInProperties:function(){this.baseClass+=this.tabPosition.charAt(0).toUpperCase()+this.tabPosition.substr(1).replace(/-.*/,"");this.srcNodeRef&&dojo.style(this.srcNodeRef,"visibility","hidden");this.inherited(arguments)},buildRendering:function(){this.inherited(arguments);this.tablist=this._makeController(this.tablistNode);this.doLayout||dojo.addClass(this.domNode,"dijitTabContainerNoLayout");this.nested?(dojo.addClass(this.domNode,"dijitTabContainerNested"),dojo.addClass(this.tablist.containerNode,
"dijitTabContainerTabListNested"),dojo.addClass(this.tablistSpacer,"dijitTabContainerSpacerNested"),dojo.addClass(this.containerNode,"dijitTabPaneWrapperNested")):dojo.addClass(this.domNode,"tabStrip-"+(this.tabStrip?"enabled":"disabled"))},_setupChild:function(a){dojo.addClass(a.domNode,"dijitTabPane");this.inherited(arguments)},startup:function(){this._started||(this.tablist.startup(),this.inherited(arguments))},layout:function(){if(this._contentBox&&typeof this._contentBox.l!="undefined"){var a=
this.selectedChildWidget;if(this.doLayout){var b=this.tabPosition.replace(/-h/,"");this.tablist.layoutAlign=b;b=[this.tablist,{domNode:this.tablistSpacer,layoutAlign:b},{domNode:this.containerNode,layoutAlign:"client"}];dijit.layout.layoutChildren(this.domNode,this._contentBox,b);this._containerContentBox=dijit.layout.marginBox2contentBox(this.containerNode,b[2]);a&&a.resize&&a.resize(this._containerContentBox)}else{if(this.tablist.resize){b=this.tablist.domNode.style;b.width="0";var c=dojo.contentBox(this.domNode).w;
b.width="";this.tablist.resize({w:c})}a&&a.resize&&a.resize()}}},destroy:function(){this.tablist&&this.tablist.destroy();this.inherited(arguments)}}));