/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.layout.AccordionContainer"]||(dojo._hasResource["dijit.layout.AccordionContainer"]=!0,dojo.provide("dijit.layout.AccordionContainer"),dojo.require("dijit._Container"),dojo.require("dijit._Templated"),dojo.require("dijit._CssStateMixin"),dojo.require("dijit.layout.StackContainer"),dojo.require("dijit.layout.ContentPane"),dojo.require("dijit.layout.AccordionPane"),dojo.declare("dijit.layout.AccordionContainer",dijit.layout.StackContainer,{duration:dijit.defaultDuration,buttonWidget:"dijit.layout._AccordionButton",
baseClass:"dijitAccordionContainer",buildRendering:function(){this.inherited(arguments);this.domNode.style.overflow="hidden";dijit.setWaiRole(this.domNode,"tablist")},startup:function(){if(!this._started&&(this.inherited(arguments),this.selectedChildWidget)){var a=this.selectedChildWidget.containerNode.style;a.display="";a.overflow="auto";this.selectedChildWidget._wrapperWidget.set("selected",!0)}},layout:function(){var a=this.selectedChildWidget;if(a){var b=a._wrapperWidget.domNode,d=dojo._getMarginExtents(b),
b=dojo._getPadBorderExtents(b),c=a._wrapperWidget.containerNode,g=dojo._getMarginExtents(c),c=dojo._getPadBorderExtents(c),f=this._contentBox,e=0;dojo.forEach(this.getChildren(),function(b){b!=a&&(e+=dojo._getMarginSize(b._wrapperWidget.domNode).h)});this._verticalSpace=f.h-e-d.h-b.h-g.h-c.h-a._buttonWidget.getTitleHeight();this._containerContentBox={h:this._verticalSpace,w:this._contentBox.w-d.w-b.w-g.w-c.w};a&&a.resize(this._containerContentBox)}},_setupChild:function(a){a._wrapperWidget=new dijit.layout._AccordionInnerContainer({contentWidget:a,
buttonWidget:this.buttonWidget,id:a.id+"_wrapper",dir:a.dir,lang:a.lang,parent:this});this.inherited(arguments)},addChild:function(a,b){this._started?(dojo.place(a.domNode,this.containerNode,b),a._started||a.startup(),this._setupChild(a),dojo.publish(this.id+"-addChild",[a,b]),this.layout(),this.selectedChildWidget||this.selectChild(a)):this.inherited(arguments)},removeChild:function(a){a._wrapperWidget&&(dojo.place(a.domNode,a._wrapperWidget.domNode,"after"),a._wrapperWidget.destroy(),delete a._wrapperWidget);
dojo.removeClass(a.domNode,"dijitHidden");this.inherited(arguments)},getChildren:function(){return dojo.map(this.inherited(arguments),function(a){return a.declaredClass=="dijit.layout._AccordionInnerContainer"?a.contentWidget:a},this)},destroy:function(){this._animation&&this._animation.stop();dojo.forEach(this.getChildren(),function(a){a._wrapperWidget?a._wrapperWidget.destroy():a.destroyRecursive()});this.inherited(arguments)},_showChild:function(a){a._wrapperWidget.containerNode.style.display=
"block";return this.inherited(arguments)},_hideChild:function(a){a._wrapperWidget.containerNode.style.display="none";this.inherited(arguments)},_transition:function(a,b,d){dojo.isIE<8&&(d=!1);this._animation&&(this._animation.stop(!0),delete this._animation);var c=this;if(a){a._wrapperWidget.set("selected",!0);var g=this._showChild(a);this.doLayout&&a.resize&&a.resize(this._containerContentBox)}b&&(b._wrapperWidget.set("selected",!1),d||this._hideChild(b));if(d){var f=a._wrapperWidget.containerNode,
e=b._wrapperWidget.containerNode,d=a._wrapperWidget.containerNode,a=dojo._getMarginExtents(d),d=dojo._getPadBorderExtents(d),h=a.h+d.h;e.style.height=c._verticalSpace-h+"px";this._animation=new dojo.Animation({node:f,duration:this.duration,curve:[1,this._verticalSpace-h-1],onAnimate:function(a){a=Math.floor(a);f.style.height=a+"px";e.style.height=c._verticalSpace-h-a+"px"},onEnd:function(){delete c._animation;f.style.height="auto";b._wrapperWidget.containerNode.style.display="none";e.style.height=
"auto";c._hideChild(b)}});this._animation.onStop=this._animation.onEnd;this._animation.play()}return g},_onKeyPress:function(a,b){if(!this.disabled&&!(a.altKey||!b&&!a.ctrlKey)){var d=dojo.keys,c=a.charOrCode;if(b&&(c==d.LEFT_ARROW||c==d.UP_ARROW)||a.ctrlKey&&c==d.PAGE_UP)this._adjacent(!1)._buttonWidget._onTitleClick(),dojo.stopEvent(a);else if(b&&(c==d.RIGHT_ARROW||c==d.DOWN_ARROW)||a.ctrlKey&&(c==d.PAGE_DOWN||c==d.TAB))this._adjacent(!0)._buttonWidget._onTitleClick(),dojo.stopEvent(a)}}}),dojo.declare("dijit.layout._AccordionInnerContainer",
[dijit._Widget,dijit._CssStateMixin],{baseClass:"dijitAccordionInnerContainer",isContainer:!0,isLayoutContainer:!0,buildRendering:function(){this.domNode=dojo.place("<div class='"+this.baseClass+"'>",this.contentWidget.domNode,"after");var a=this.contentWidget,b=dojo.getObject(this.buttonWidget);this.button=a._buttonWidget=(new b({contentWidget:a,label:a.title,title:a.tooltip,dir:a.dir,lang:a.lang,iconClass:a.iconClass,id:a.id+"_button",parent:this.parent})).placeAt(this.domNode);this.containerNode=
dojo.place("<div class='dijitAccordionChildWrapper' style='display:none'>",this.domNode);dojo.place(this.contentWidget.domNode,this.containerNode)},postCreate:function(){this.inherited(arguments);var a=this.button;this._contentWidgetWatches=[this.contentWidget.watch("title",dojo.hitch(this,function(b,d,c){a.set("label",c)})),this.contentWidget.watch("tooltip",dojo.hitch(this,function(b,d,c){a.set("title",c)})),this.contentWidget.watch("iconClass",dojo.hitch(this,function(b,d,c){a.set("iconClass",
c)}))]},_setSelectedAttr:function(a){this._set("selected",a);this.button.set("selected",a);if(a&&(a=this.contentWidget,a.onSelected))a.onSelected()},startup:function(){this.contentWidget.startup()},destroy:function(){this.button.destroyRecursive();dojo.forEach(this._contentWidgetWatches||[],function(a){a.unwatch()});delete this.contentWidget._buttonWidget;delete this.contentWidget._wrapperWidget;this.inherited(arguments)},destroyDescendants:function(){this.contentWidget.destroyRecursive()}}),dojo.declare("dijit.layout._AccordionButton",
[dijit._Widget,dijit._Templated,dijit._CssStateMixin],{templateString:dojo.cache("dijit.layout","templates/AccordionButton.html","<div dojoAttachEvent='onclick:_onTitleClick' class='dijitAccordionTitle'>\n\t<div dojoAttachPoint='titleNode,focusNode' dojoAttachEvent='onkeypress:_onTitleKeyPress'\n\t\t\tclass='dijitAccordionTitleFocus' role=\"tab\" aria-expanded=\"false\"\n\t\t><span class='dijitInline dijitAccordionArrow' role=\"presentation\"></span\n\t\t><span class='arrowTextUp' role=\"presentation\">+</span\n\t\t><span class='arrowTextDown' role=\"presentation\">-</span\n\t\t><img src=\"${_blankGif}\" alt=\"\" class=\"dijitIcon\" dojoAttachPoint='iconNode' style=\"vertical-align: middle\" role=\"presentation\"/>\n\t\t<span role=\"presentation\" dojoAttachPoint='titleTextNode' class='dijitAccordionText'></span>\n\t</div>\n</div>\n"),
attributeMap:dojo.mixin(dojo.clone(dijit.layout.ContentPane.prototype.attributeMap),{label:{node:"titleTextNode",type:"innerHTML"},title:{node:"titleTextNode",type:"attribute",attribute:"title"},iconClass:{node:"iconNode",type:"class"}}),baseClass:"dijitAccordionTitle",getParent:function(){return this.parent},buildRendering:function(){this.inherited(arguments);var a=this.id.replace(" ","_");dojo.attr(this.titleTextNode,"id",a+"_title");dijit.setWaiState(this.focusNode,"labelledby",dojo.attr(this.titleTextNode,
"id"));dojo.setSelectable(this.domNode,!1)},getTitleHeight:function(){return dojo._getMarginSize(this.domNode).h},_onTitleClick:function(){this.getParent().selectChild(this.contentWidget,!0);dijit.focus(this.focusNode)},_onTitleKeyPress:function(a){return this.getParent()._onKeyPress(a,this.contentWidget)},_setSelectedAttr:function(a){this._set("selected",a);dijit.setWaiState(this.focusNode,"expanded",a);dijit.setWaiState(this.focusNode,"selected",a);this.focusNode.setAttribute("tabIndex",a?"0":"-1")}}));