/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dijit.layout.ScrollingTabController"]||(dojo._hasResource["dijit.layout.ScrollingTabController"]=!0,dojo.provide("dijit.layout.ScrollingTabController"),dojo.require("dijit.layout.TabController"),dojo.require("dijit.Menu"),dojo.require("dijit.form.Button"),dojo.require("dijit._HasDropDown"),dojo.declare("dijit.layout.ScrollingTabController",dijit.layout.TabController,{templateString:dojo.cache("dijit.layout","templates/ScrollingTabController.html",'<div class="dijitTabListContainer-${tabPosition}" style="visibility:hidden">\n\t<div dojoType="dijit.layout._ScrollingTabControllerMenuButton"\n\t\t\tclass="tabStripButton-${tabPosition}"\n\t\t\tid="${id}_menuBtn" containerId="${containerId}" iconClass="dijitTabStripMenuIcon"\n\t\t\tdropDownPosition="below-alt, above-alt"\n\t\t\tdojoAttachPoint="_menuBtn" showLabel="false">&#9660;</div>\n\t<div dojoType="dijit.layout._ScrollingTabControllerButton"\n\t\t\tclass="tabStripButton-${tabPosition}"\n\t\t\tid="${id}_leftBtn" iconClass="dijitTabStripSlideLeftIcon"\n\t\t\tdojoAttachPoint="_leftBtn" dojoAttachEvent="onClick: doSlideLeft" showLabel="false">&#9664;</div>\n\t<div dojoType="dijit.layout._ScrollingTabControllerButton"\n\t\t\tclass="tabStripButton-${tabPosition}"\n\t\t\tid="${id}_rightBtn" iconClass="dijitTabStripSlideRightIcon"\n\t\t\tdojoAttachPoint="_rightBtn" dojoAttachEvent="onClick: doSlideRight" showLabel="false">&#9654;</div>\n\t<div class=\'dijitTabListWrapper\' dojoAttachPoint=\'tablistWrapper\'>\n\t\t<div role=\'tablist\' dojoAttachEvent=\'onkeypress:onkeypress\'\n\t\t\t\tdojoAttachPoint=\'containerNode\' class=\'nowrapTabStrip\'></div>\n\t</div>\n</div>\n'),
useMenu:!0,useSlider:!0,tabStripClass:"",widgetsInTemplate:!0,_minScroll:5,attributeMap:dojo.delegate(dijit._Widget.prototype.attributeMap,{"class":"containerNode"}),buildRendering:function(){this.inherited(arguments);var a=this.domNode;this.scrollNode=this.tablistWrapper;this._initButtons();if(!this.tabStripClass)this.tabStripClass="dijitTabContainer"+this.tabPosition.charAt(0).toUpperCase()+this.tabPosition.substr(1).replace(/-.*/,"")+"None",dojo.addClass(a,"tabStrip-disabled");dojo.addClass(this.tablistWrapper,
this.tabStripClass)},onStartup:function(){this.inherited(arguments);dojo.style(this.domNode,"visibility","visible");this._postStartup=!0},onAddChild:function(a,b){this.inherited(arguments);dojo.forEach(["label","iconClass"],function(b){this.pane2watches[a.id].push(this.pane2button[a.id].watch(b,dojo.hitch(this,function(){this._postStartup&&this._dim&&this.resize(this._dim)})))},this);dojo.style(this.containerNode,"width",dojo.style(this.containerNode,"width")+200+"px")},onRemoveChild:function(a,b){if(this._selectedTab===
this.pane2button[a.id].domNode)this._selectedTab=null;this.inherited(arguments)},_initButtons:function(){this._btnWidth=0;this._buttons=dojo.query("> .tabStripButton",this.domNode).filter(function(a){return this.useMenu&&a==this._menuBtn.domNode||this.useSlider&&(a==this._rightBtn.domNode||a==this._leftBtn.domNode)?(this._btnWidth+=dojo._getMarginSize(a).w,!0):(dojo.style(a,"display","none"),!1)},this)},_getTabsWidth:function(){var a=this.getChildren();if(a.length){var b=a[this.isLeftToRight()?0:
a.length-1].domNode,a=a[this.isLeftToRight()?a.length-1:0].domNode;return a.offsetLeft+dojo.style(a,"width")-b.offsetLeft}else return 0},_enableBtn:function(a){var b=this._getTabsWidth(),a=a||dojo.style(this.scrollNode,"width");return b>0&&a<b},resize:function(a){if(this.domNode.offsetWidth!=0){this._dim=a;this.scrollNode.style.height="auto";this._contentBox=dijit.layout.marginBox2contentBox(this.domNode,{h:0,w:a.w});this._contentBox.h=this.scrollNode.offsetHeight;dojo.contentBox(this.domNode,this._contentBox);
this._buttons.style("display",this._enableBtn(this._contentBox.w)?"":"none");this._leftBtn.layoutAlign="left";this._rightBtn.layoutAlign="right";this._menuBtn.layoutAlign=this.isLeftToRight()?"right":"left";dijit.layout.layoutChildren(this.domNode,this._contentBox,[this._menuBtn,this._leftBtn,this._rightBtn,{domNode:this.scrollNode,layoutAlign:"client"}]);if(this._selectedTab){this._anim&&this._anim.status()=="playing"&&this._anim.stop();var b=this.scrollNode,c=this._convertToScrollLeft(this._getScrollForSelectedTab());
b.scrollLeft=c}this._setButtonClass(this._getScroll());this._postResize=!0;return{h:this._contentBox.h,w:a.w}}},_getScroll:function(){return this.isLeftToRight()||dojo.isIE<8||dojo.isIE&&dojo.isQuirks||dojo.isWebKit?this.scrollNode.scrollLeft:dojo.style(this.containerNode,"width")-dojo.style(this.scrollNode,"width")+(dojo.isIE==8?-1:1)*this.scrollNode.scrollLeft},_convertToScrollLeft:function(a){if(this.isLeftToRight()||dojo.isIE<8||dojo.isIE&&dojo.isQuirks||dojo.isWebKit)return a;else{var b=dojo.style(this.containerNode,
"width")-dojo.style(this.scrollNode,"width");return(dojo.isIE==8?-1:1)*(a-b)}},onSelectChild:function(a){var b=this.pane2button[a.id];if(b&&a){b=b.domNode;if(this._postResize&&b!=this._selectedTab){this._selectedTab=b;var c=this._getScroll();(c>b.offsetLeft||c+dojo.style(this.scrollNode,"width")<b.offsetLeft+dojo.style(b,"width"))&&this.createSmoothScroll().play()}this.inherited(arguments)}},_getScrollBounds:function(){var a=this.getChildren(),b=dojo.style(this.scrollNode,"width"),c=dojo.style(this.containerNode,
"width")-b,d=this._getTabsWidth();return a.length&&d>b?{min:this.isLeftToRight()?0:a[a.length-1].domNode.offsetLeft,max:this.isLeftToRight()?a[a.length-1].domNode.offsetLeft+dojo.style(a[a.length-1].domNode,"width")-b:c}:(a=this.isLeftToRight()?0:c,{min:a,max:a})},_getScrollForSelectedTab:function(){var a=this._selectedTab,b=dojo.style(this.scrollNode,"width"),c=this._getScrollBounds(),a=a.offsetLeft+dojo.style(a,"width")/2-b/2;return a=Math.min(Math.max(a,c.min),c.max)},createSmoothScroll:function(a){if(arguments.length>
0)var b=this._getScrollBounds(),a=Math.min(Math.max(a,b.min),b.max);else a=this._getScrollForSelectedTab();this._anim&&this._anim.status()=="playing"&&this._anim.stop();var c=this,d=this.scrollNode,e=new dojo._Animation({beforeBegin:function(){this.curve&&delete this.curve;var b=d.scrollLeft,f=c._convertToScrollLeft(a);e.curve=new dojo._Line(b,f)},onAnimate:function(a){d.scrollLeft=a}});this._anim=e;this._setButtonClass(a);return e},_getBtnNode:function(a){for(a=a.target;a&&!dojo.hasClass(a,"tabStripButton");)a=
a.parentNode;return a},doSlideRight:function(a){this.doSlide(1,this._getBtnNode(a))},doSlideLeft:function(a){this.doSlide(-1,this._getBtnNode(a))},doSlide:function(a,b){if(!b||!dojo.hasClass(b,"dijitTabDisabled")){var c=dojo.style(this.scrollNode,"width")*0.75*a,c=this._getScroll()+c;this._setButtonClass(c);this.createSmoothScroll(c).play()}},_setButtonClass:function(a){var b=this._getScrollBounds();this._leftBtn.set("disabled",a<=b.min);this._rightBtn.set("disabled",a>=b.max)}}),dojo.declare("dijit.layout._ScrollingTabControllerButtonMixin",
null,{baseClass:"dijitTab tabStripButton",templateString:dojo.cache("dijit.layout","templates/_ScrollingTabControllerButton.html",'<div dojoAttachEvent="onclick:_onButtonClick">\n\t<div role="presentation" class="dijitTabInnerDiv" dojoattachpoint="innerDiv,focusNode">\n\t\t<div role="presentation" class="dijitTabContent dijitButtonContents" dojoattachpoint="tabContent">\n\t\t\t<img role="presentation" alt="" src="${_blankGif}" class="dijitTabStripIcon" dojoAttachPoint="iconNode"/>\n\t\t\t<span dojoAttachPoint="containerNode,titleNode" class="dijitButtonText"></span>\n\t\t</div>\n\t</div>\n</div>\n'),
tabIndex:"",isFocusable:function(){return!1}}),dojo.declare("dijit.layout._ScrollingTabControllerButton",[dijit.form.Button,dijit.layout._ScrollingTabControllerButtonMixin]),dojo.declare("dijit.layout._ScrollingTabControllerMenuButton",[dijit.form.Button,dijit._HasDropDown,dijit.layout._ScrollingTabControllerButtonMixin],{containerId:"",tabIndex:"-1",isLoaded:function(){return!1},loadDropDown:function(a){this.dropDown=new dijit.Menu({id:this.containerId+"_menu",dir:this.dir,lang:this.lang});var b=
dijit.byId(this.containerId);dojo.forEach(b.getChildren(),function(a){this.dropDown.addChild(new dijit.MenuItem({id:a.id+"_stcMi",label:a.title,iconClass:a.iconClass,dir:a.dir,lang:a.lang,onClick:function(){b.selectChild(a)}}))},this);a()},closeDropDown:function(a){this.inherited(arguments);this.dropDown&&(this.dropDown.destroyRecursive(),delete this.dropDown)}}));