/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.lang.docs"]||(dojo._hasResource["dojox.lang.docs"]=!0,dojo.provide("dojox.lang.docs"),function(){function q(b){console.log("Warning, the API docs must be available at ../util/docscripts/api.json or ../util/docscripts/api/*.json in order for dojox.lang.docs to supply schema information, but it could not be loaded: "+b)}var f={},g=[],l=dojox.lang.docs._loadedDocs={},j=function(b,a){f[a]=b},o=function(b){var a=b.type||"",c,e=!1,d=!1,k,a=a.replace(/\?/,function(){e=!0;return""}),
a=a.replace(/\[\]/,function(){d=!0;return""});a.match(/HTML/)?a="string":a=="String"||a=="Number"||a=="Boolean"||a=="Object"||a=="Array"||a=="Integer"||a=="Function"?a=a.toLowerCase():a=="bool"?a="boolean":a?(c=dojo.getObject(a)||{},k=!0):c={};c=c||{type:a};d&&(c={items:c,type:"array"},k=!1);if(!k){if(e)c.optional=!0;if(/const/.test(b.tags))c.readonly=!0}return c},r=function(b,a){var c=l[a];if(c){b.description=c.description;b.properties={};b.methods={};if(c.properties)for(var e=c.properties,d=0,k=
e.length;d<k;d++)if(e[d].scope=="prototype")(b.properties[e[d].name]=o(e[d])).description=e[d].summary;if(c.methods){e=c.methods;d=0;for(k=e.length;d<k;d++)if((a=e[d].name)&&e[d].scope=="prototype"){var m=b.methods[a]={};m.description=e[d].summary;var h=e[d].parameters;if(h){m.parameters=[];for(var n=0,f=h.length;n<f;n++){var g=h[n],j=m.parameters[n]=o(g);j.name=g.name;j.optional="optional"==g.usage}}if((h=e[d]["return-types"])&&h[0])if(h=o(h[0]),h.type)m.returns=h}}(c=c.superclass)&&(b["extends"]=
dojo.getObject(c))}},p=function(b){g.push(b)},s=dojo.declare;dojo.declare=function(b){var a=s.apply(this,arguments);j(a,b);return a};dojo.mixin(dojo.declare,s);var t,u=dojo.require;dojo.require=function(b){p(b);return u.apply(this,arguments)};dojox.lang.docs.init=function(b){function a(){dojo.require=u;g=null;try{dojo.xhrGet({sync:!b,url:dojo.baseUrl+"../util/docscripts/api.json",handleAs:"text"}).addCallbacks(function(a){l=(new Function("return "+a))();j=r;for(var b in f)j(f[b],b);f=null},q)}catch(a){q(a)}}
if(t)return null;t=!0;var c=function(a,c){return dojo.xhrGet({sync:c||!b,url:dojo.baseUrl+"../util/docscripts/api/"+a+".json",handleAs:"text"}).addCallback(function(a){var a=(new Function("return "+a))(),b;for(b in a)l[b]||(l[b]=a[b])})};try{var e=g.shift();c(e,!0).addCallbacks(function(){p=function(a){if(!l[a])try{c(a)}catch(b){l[a]={}}};dojo.forEach(g,function(a){p(a)});g=null;j=r;for(i in f)j(f[i],i);f=null},a)}catch(d){a()}return null}}());