/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.mdnd.Moveable"]||(dojo._hasResource["dojox.mdnd.Moveable"]=!0,dojo.provide("dojox.mdnd.Moveable"),dojo.declare("dojox.mdnd.Moveable",null,{handle:null,skip:!0,dragDistance:3,constructor:function(a,b){this.node=dojo.byId(b);this.d=this.node.ownerDocument;a||(a={});this.handle=a.handle?dojo.byId(a.handle):null;if(!this.handle)this.handle=this.node;this.skip=a.skip;this.events=[dojo.connect(this.handle,"onmousedown",this,"onMouseDown")];if(dojox.mdnd.autoScroll)this.autoScroll=
dojox.mdnd.autoScroll},isFormElement:function(a){a=a.target;if(a.nodeType==3)a=a.parentNode;return" a button textarea input select option ".indexOf(" "+a.tagName.toLowerCase()+" ")>=0},onMouseDown:function(a){if(!this._isDragging&&(dojo.isIE?a.button==1:a.which==1))if(!this.skip||!this.isFormElement(a))this.autoScroll&&(this.autoScroll.setAutoScrollNode(this.node),this.autoScroll.setAutoScrollMaxPage()),this.events.push(dojo.connect(this.d,"onmouseup",this,"onMouseUp")),this.events.push(dojo.connect(this.d,
"onmousemove",this,"onFirstMove")),this._selectStart=dojo.connect(dojo.body(),"onselectstart",dojo.stopEvent),this._firstX=a.clientX,this._firstY=a.clientY,dojo.stopEvent(a)},onFirstMove:function(a){dojo.stopEvent(a);if((this._firstX-a.clientX)*(this._firstX-a.clientX)+(this._firstY-a.clientY)*(this._firstY-a.clientY)>this.dragDistance*this.dragDistance)this._isDragging=!0,dojo.disconnect(this.events.pop()),dojo.style(this.node,"width",dojo.contentBox(this.node).w+"px"),this.initOffsetDrag(a),this.events.push(dojo.connect(this.d,
"onmousemove",this,"onMove"))},initOffsetDrag:function(a){this.offsetDrag={l:a.pageX,t:a.pageY};a=dojo.position(this.node,!0);this.offsetDrag.l=a.x-this.offsetDrag.l;this.offsetDrag.t=a.y-this.offsetDrag.t;var b={x:a.x,y:a.y};this.size={w:a.w,h:a.h};this.onDragStart(this.node,b,this.size)},onMove:function(a){dojo.stopEvent(a);if(!(dojo.isIE==8&&new Date-this.date<20)){this.autoScroll&&this.autoScroll.checkAutoScroll(a);var b={x:this.offsetDrag.l+a.pageX,y:this.offsetDrag.t+a.pageY},c=this.node.style;
c.left=b.x+"px";c.top=b.y+"px";this.onDrag(this.node,b,this.size,{x:a.pageX,y:a.pageY});if(dojo.isIE==8)this.date=new Date}},onMouseUp:function(a){if(this._isDragging)dojo.stopEvent(a),this._isDragging=!1,this.autoScroll&&this.autoScroll.stopAutoScroll(),delete this.onMove,this.onDragEnd(this.node),this.node.focus();dojo.disconnect(this.events.pop());dojo.disconnect(this.events.pop())},onDragStart:function(){},onDragEnd:function(){},onDrag:function(){},destroy:function(){dojo.forEach(this.events,
dojo.disconnect);this.events=this.node=null}}));