/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.validate.br"])dojo._hasResource["dojox.validate.br"]=!0,dojo.provide("dojox.validate.br"),dojo.require("dojox.validate._base"),dojox.validate.br.isValidCnpj=function(a){if(!dojo.isString(a)){if(!a)return!1;for(a+="";a.length<14;)a="0"+a}if(dojox.validate.isNumberFormat(a,{format:["##.###.###/####-##","########/####-##","############-##","##############"]})){var a=a.replace("/","").replace(/\./g,"").replace("-",""),d=[],c=[],b,e,f;for(b=0;b<10;b++){f="";for(e=0;e<a.length;e++)f+=
""+b;if(a===f)return!1}for(b=0;b<12;b++)d.push(parseInt(a.charAt(b),10));for(b=12;b<14;b++)c.push(parseInt(a.charAt(b),10));a=[9,8,7,6,5,4,3,2,9,8,7,6].reverse();for(b=e=0;b<d.length;b++)e+=d[b]*a[b];b=e%11;if(b==c[0]){e=0;a=[9,8,7,6,5,4,3,2,9,8,7,6,5].reverse();d.push(b);for(b=0;b<d.length;b++)e+=d[b]*a[b];if(e%11===c[1])return!0}}return!1},dojox.validate.br.computeCnpjDv=function(a){if(!dojo.isString(a)){if(!a)return"";for(a+="";a.length<12;)a="0"+a}if(dojox.validate.isNumberFormat(a,{format:["##.###.###/####",
"########/####","############"]})){var a=a.replace("/","").replace(/\./g,""),d=[],c,b,e;for(c=0;c<10;c++){e="";for(b=0;b<a.length;b++)e+=""+c;if(a===e)return""}for(c=0;c<a.length;c++)d.push(parseInt(a.charAt(c),10));a=[9,8,7,6,5,4,3,2,9,8,7,6].reverse();for(c=b=0;c<d.length;c++)b+=d[c]*a[c];e=b%11;b=0;a=[9,8,7,6,5,4,3,2,9,8,7,6,5].reverse();d.push(e);for(c=0;c<d.length;c++)b+=d[c]*a[c];return""+e+b%11}return""},dojox.validate.br.isValidCpf=function(a){if(!dojo.isString(a)){if(!a)return!1;for(a+="";a.length<
11;)a="0"+a}if(dojox.validate.isNumberFormat(a,{format:["###.###.###-##","#########-##","###########"]})){var a=a.replace("-","").replace(/\./g,""),d=[],c=[],b,e,f;for(b=0;b<10;b++){f="";for(e=0;e<a.length;e++)f+=""+b;if(a===f)return!1}for(b=0;b<9;b++)d.push(parseInt(a.charAt(b),10));for(b=9;b<12;b++)c.push(parseInt(a.charAt(b),10));a=[9,8,7,6,5,4,3,2,1].reverse();for(b=e=0;b<d.length;b++)e+=d[b]*a[b];b=e%11;if(b==c[0]){e=0;a=[9,8,7,6,5,4,3,2,1,0].reverse();d.push(b);for(b=0;b<d.length;b++)e+=d[b]*
a[b];if(e%11===c[1])return!0}}return!1},dojox.validate.br.computeCpfDv=function(a){if(!dojo.isString(a)){if(!a)return"";for(a+="";a.length<9;)a="0"+a}if(dojox.validate.isNumberFormat(a,{format:["###.###.###","#########"]})){var a=a.replace(/\./g,""),d=[];for(i=0;i<10;i++){tmp="";for(j=0;j<a.length;j++)tmp+=""+i;if(a===tmp)return""}for(i=0;i<a.length;i++)d.push(parseInt(a.charAt(i),10));var a=[9,8,7,6,5,4,3,2,1].reverse(),c=0;for(i=0;i<d.length;i++)c+=d[i]*a[i];var b=c%11,c=0,a=[9,8,7,6,5,4,3,2,1,
0].reverse();d.push(b);for(i=0;i<d.length;i++)c+=d[i]*a[i];return""+b+c%11}return""};