/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.validate.regexp"])dojo._hasResource["dojox.validate.regexp"]=!0,dojo.provide("dojox.validate.regexp"),dojo.require("dojo.regexp"),dojo.mixin(dojox.validate.regexp,{ipAddress:function(a){a=typeof a=="object"?a:{};if(typeof a.allowDottedDecimal!="boolean")a.allowDottedDecimal=!0;if(typeof a.allowDottedHex!="boolean")a.allowDottedHex=!0;if(typeof a.allowDottedOctal!="boolean")a.allowDottedOctal=!0;if(typeof a.allowDecimal!="boolean")a.allowDecimal=!0;if(typeof a.allowHex!=
"boolean")a.allowHex=!0;if(typeof a.allowIPv6!="boolean")a.allowIPv6=!0;if(typeof a.allowHybrid!="boolean")a.allowHybrid=!0;var b=[];a.allowDottedDecimal&&b.push("((\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])");a.allowDottedHex&&b.push("(0[xX]0*[\\da-fA-F]?[\\da-fA-F]\\.){3}0[xX]0*[\\da-fA-F]?[\\da-fA-F]");a.allowDottedOctal&&b.push("(0+[0-3][0-7][0-7]\\.){3}0+[0-3][0-7][0-7]");a.allowDecimal&&b.push("(0|[1-9]\\d{0,8}|[1-3]\\d{9}|4[01]\\d{8}|42[0-8]\\d{7}|429[0-3]\\d{6}|4294[0-8]\\d{5}|42949[0-5]\\d{4}|429496[0-6]\\d{3}|4294967[01]\\d{2}|42949672[0-8]\\d|429496729[0-5])");
a.allowHex&&b.push("0[xX]0*[\\da-fA-F]{1,8}");a.allowIPv6&&b.push("([\\da-fA-F]{1,4}\\:){7}[\\da-fA-F]{1,4}");a.allowHybrid&&b.push("([\\da-fA-F]{1,4}\\:){6}((\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])");a="";b.length>0&&(a="("+b.join("|")+")");return a},host:function(a){a=typeof a=="object"?a:{};if(typeof a.allowIP!="boolean")a.allowIP=!0;if(typeof a.allowLocal!="boolean")a.allowLocal=!1;if(typeof a.allowPort!="boolean")a.allowPort=!0;if(typeof a.allowNamed!=
"boolean")a.allowNamed=!1;var b=a.allowPort?"(\\:\\d+)?":"",c="((?:(?:[\\da-zA-Z](?:[-\\da-zA-Z]{0,61}[\\da-zA-Z])?)\\.)+(?:[a-zA-Z](?:[-\\da-zA-Z]{0,6}[\\da-zA-Z])?)\\.?)";a.allowIP&&(c+="|"+dojox.validate.regexp.ipAddress(a));a.allowLocal&&(c+="|localhost");a.allowNamed&&(c+="|^[^-][a-zA-Z0-9_-]*");return"("+c+")"+b},url:function(a){a=typeof a=="object"?a:{};if(!("scheme"in a))a.scheme=[!0,!1];return dojo.regexp.buildGroupRE(a.scheme,function(a){return a?"(https?|ftps?)\\://":""})+dojox.validate.regexp.host(a)+
"(/(?:[^?#\\s/]+/)*(?:[^?#\\s/]+(?:\\?[^?#\\s/]*)?(?:#[A-Za-z][\\w.:-]*)?)?)?"},emailAddress:function(a){a=typeof a=="object"?a:{};if(typeof a.allowCruft!="boolean")a.allowCruft=!1;a.allowPort=!1;var b="([!#-'*+\\-\\/-9=?A-Z^-~]+[.])*[!#-'*+\\-\\/-9=?A-Z^-~]+@"+dojox.validate.regexp.host(a);a.allowCruft&&(b="<?(mailto\\:)?"+b+">?");return b},emailAddressList:function(a){a=typeof a=="object"?a:{};if(typeof a.listSeparator!="string")a.listSeparator="\\s;,";var b=dojox.validate.regexp.emailAddress(a);
return"("+b+"\\s*["+a.listSeparator+"]\\s*)*"+b+"\\s*["+a.listSeparator+"]?\\s*"},numberFormat:function(a){a=typeof a=="object"?a:{};if(typeof a.format=="undefined")a.format="###-###-####";return dojo.regexp.buildGroupRE(a.format,function(a){return dojo.regexp.escapeString(a,"?").replace(/\?/g,"\\d?").replace(/#/g,"\\d")})}}),dojox.validate.regexp.ca={postalCode:function(){return"([A-Z][0-9][A-Z] [0-9][A-Z][0-9])"},province:function(){return"(AB|BC|MB|NB|NL|NS|NT|NU|ON|PE|QC|SK|YT)"}},dojox.validate.regexp.us=
{state:function(a){a=typeof a=="object"?a:{};if(typeof a.allowTerritories!="boolean")a.allowTerritories=!0;if(typeof a.allowMilitary!="boolean")a.allowMilitary=!0;var b="AL|AK|AZ|AR|CA|CO|CT|DE|DC|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY";a.allowTerritories&&(b+="|AS|FM|GU|MH|MP|PW|PR|VI");a.allowMilitary&&(b+="|AA|AE|AP");return"("+b+")"}};