<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>PHProjekt</title>
    <link rel="shortcut icon" href="<?php echo $this->webPath; ?>img/favicon.ico" type="image/x-icon" />
    <style type="text/css">
        @import "<?php echo $this->webPath; ?>css/themes/phprojekt/phprojektCssCompiler.php";
    </style>
    <script type="text/javascript" src="<?php echo $this->webPath; ?>dojo/dojo/dojo.js"></script>
    <script type="text/javascript" src="<?php echo $this->webPath; ?>dojo/dojo/mydojo.js"></script>
    <script type="text/javascript">
        function getMaxHeight() {
            var availHeight = 0;

            if (document.layers) {
                availHeight = window.innerHeight + window.pageYOffset;
            } else if (document.all) {
                availHeight = document.documentElement.clientHeight + document.documentElement.scrollTop;
            } else if (document.getElementById) {
                availHeight = window.innerHeight + window.pageYOffset;
            }

            return availHeight;
        }

        function init() {
            availHeight = getMaxHeight();

            dojo.style(dojo.byId('completeContent'), "height", availHeight + "px");
            if (dijit.byId('completeContent')) {
                dijit.byId('completeContent').resize();
            }

            if (dojo.byId('completeCenterContent')) {
                dojo.style(dojo.byId('completeCenterContent'), "height", (availHeight - 55) + "px");
                if (dijit.byId('completeCenterContent')) {
                    dijit.byId('completeCenterContent').resize();
                }
            }
        }

        dojo.addOnLoad(function() {
            dojo.parser.parse();
            init();
        });

        window.onresize = function() {
            init();
        };
    </script>
</head>
<body class="phprojekt">

<div id="completeContent" dojoType="dijit.layout.BorderContainer" persist="true"
 style="width: 100%; height: 1000px;">
    <!-- Left Content -->
    <div id="navigation-container" dojoType="dijit.layout.ContentPane" region="left" splitter="false" minSize="180"
    maxSize="300"
    style="width: 15%; overflow: hidden;">
        <div region="center" dojoType="dijit.layout.ContentPane">
            <div id="tree-navigation">
                <div dojoType="dijit.layout.ContentPane" id="treeBox"
                 style="height: 100%;">
                </div>
            </div>
        </div>
    </div>

    <!-- Top Bar menu -->
    <div dojoType="dijit.layout.ContentPane" region="top" id="header"
    style="height: 55px; overflow: hidden;">
        <img class="left" src="<?php echo $this->webPath; ?>img/logo.png" alt="PHProjekt 6" />
        <div id="mainNavigation"  class="right align-right" dojoType="dijit.Toolbar">
        </div>
        <div id="loadingIcon" class="right align-right"
        style="margin-top: 5px; margin-bottom: 5px; display: none;">
            <img class="left" src="<?php echo $this->webPath; ?>img/ajax-loader.gif" alt="Loadding" />
        </div>
    </div>

    <!-- Center Content -->
    <div    id="completeCenterContent"
            dojoType="dijit.layout.ContentPane"
            region="center"
            style="height: 1000px;">
        <br/>
        <div class="prepend-0" id="content">
            <h2>Migration</h2>
            <p>
                Thank you for upgrading to Phprojekt <?php echo $this->newVersion; ?>.<br/>
                We're sorry to bother you, but we need to upgrade the database to the current version.<br/><br/>
                When you're ready, just click the button. Please note that the upgrade might take a few moments.
            </p><br/>
            <style type="text/css">
                .modulesTable, .modulesTable td, .modulesTable th {
                    border: medium solid rgb(239, 239, 239);
                }
            </style>
            <?php if ($this->modules): ?>
            <table class="modulesTable">
                <tr>
                    <th >Module</th><th>Old version</th><th>New version</th>
                </tr>
                <?php foreach ($this->modules as $module => $mdata): ?>
                <tr>
                    <td><?php echo $module; ?></td>
                    <td><?php echo $mdata['from'] ?: 'Not installed'; ?></td>
                    <td><?php echo $mdata['to']; ?></td>
                </tr>
                <?php endforeach; ?>
            </table><br/>
            <?php endif; ?>
            <form action="<?php echo $this->webPath; ?>index.php/Core/Upgrade/upgrade" method="post">
                <input type="submit" value="Upgrade now"/>
                <input type="hidden" value="<?php echo Phprojekt::createCsrfToken(); ?>"/>
            </form>
        </div>
    </div>
</div>
</body>
</html>
