/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo._base.lang"]||(dojo._hasResource["dojo._base.lang"]=!0,dojo.provide("dojo._base.lang"),function(){var c=dojo,k=Object.prototype.toString;dojo.isString=function(a){return typeof a=="string"||a instanceof String};dojo.isArray=function(a){return a&&(a instanceof Array||typeof a=="array")};dojo.isFunction=function(a){return k.call(a)==="[object Function]"};dojo.isObject=function(a){return a!==void 0&&(a===null||typeof a=="object"||c.isArray(a)||c.isFunction(a))};dojo.isArrayLike=
function(a){return a&&a!==void 0&&!c.isString(a)&&!c.isFunction(a)&&!(a.tagName&&a.tagName.toLowerCase()=="form")&&(c.isArray(a)||isFinite(a.length))};dojo.isAlien=function(a){return a&&!c.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))};dojo.extend=function(a,b){for(var d=1,e=arguments.length;d<e;d++)c._mixin(a.prototype,arguments[d]);return a};dojo._hitchArgs=function(a,b){var d=c._toArray(arguments,2),e=c.isString(b);return function(){var f=c._toArray(arguments),g=e?(a||c.global)[b]:
b;return g&&g.apply(a||this,d.concat(f))}};dojo.hitch=function(a,b){if(arguments.length>2)return c._hitchArgs.apply(c,arguments);b||(b=a,a=null);if(c.isString(b)){a=a||c.global;if(!a[b])throw['dojo.hitch: scope["',b,'"] is null (scope="',a,'")'].join("");return function(){return a[b].apply(a,arguments||[])}}return!a?b:function(){return b.apply(a,arguments||[])}};dojo.delegate=dojo._delegate=function(){function a(){}return function(b,d){a.prototype=b;var e=new a;a.prototype=null;d&&c._mixin(e,d);return e}}();
var h=function(a,b,c){return(c||[]).concat(Array.prototype.slice.call(a,b||0))},l=function(a,b,c){c=c||[];for(b=b||0;b<a.length;b++)c.push(a[b]);return c};dojo._toArray=c.isIE?function(a){return(a.item?l:h).apply(this,arguments)}:h;dojo.partial=function(a){return c.hitch.apply(c,[null].concat(c._toArray(arguments)))};var i=c._extraNames,j=i.length,g={};dojo.clone=function(a){if(!a||typeof a!="object"||c.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());
if(a instanceof RegExp)return RegExp(a);var b,d,e,f;if(c.isArray(a)){b=[];d=0;for(e=a.length;d<e;++d)d in a&&b.push(c.clone(a[d]))}else b=a.constructor?new a.constructor:{};for(f in a)if(e=a[f],!(f in b)||b[f]!==e&&(!(f in g)||g[f]!==e))b[f]=c.clone(e);if(j)for(d=0;d<j;++d)if(f=i[d],e=a[f],!(f in b)||b[f]!==e&&(!(f in g)||g[f]!==e))b[f]=e;return b};dojo.trim=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};var m=/\{([^\}]+)\}/g;dojo.replace=
function(a,b,d){return a.replace(d||m,c.isFunction(b)?b:function(a,d){return c.getObject(d,!1,b)})}}());