/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo._base.NodeList"]||(dojo._hasResource["dojo._base.NodeList"]=!0,dojo.provide("dojo._base.NodeList"),dojo.require("dojo._base.lang"),dojo.require("dojo._base.array"),dojo.require("dojo._base.connect"),dojo.require("dojo._base.html"),function(){var c=dojo,j=Array.prototype,g=j.slice,l=j.concat,m=function(a,b,d){a.sort||(a=g.call(a,0));d=d||this._NodeListCtor||c._NodeListCtor;a.constructor=d;dojo._mixin(a,d.prototype);a._NodeListCtor=d;return b?a._stash(b):a},i=function(a,b,d){b=
[0].concat(g.call(b,0));d=d||c.global;return function(e){b[0]=e;return a.apply(d,b)}},n=function(a,b){return function(){this.forEach(i(a,arguments,b));return this}},k=function(a,b){return function(){return this.map(i(a,arguments,b))}},p=function(a,b,d){return function(){var e=arguments,o=i(a,e,d);if(b.call(d||c.global,e))return this.map(o);this.forEach(o);return this}},q=function(a){return a.length==1&&typeof a[0]=="string"},r=function(a){var b=a.parentNode;b&&b.removeChild(a)};dojo.NodeList=function(){return m(Array.apply(null,
arguments))};var h=c._NodeListCtor=c.NodeList,f=h.prototype;h._wrap=f._wrap=m;h._adaptAsMap=k;h._adaptAsForEach=n;h._adaptAsFilter=function(a,b){return function(){return this.filter(i(a,arguments,b))}};h._adaptWithCondition=p;c.forEach(["slice","splice"],function(a){var b=j[a];f[a]=function(){return this._wrap(b.apply(this,arguments),a=="slice"?this:null)}});c.forEach(["indexOf","lastIndexOf","every","some"],function(a){var b=c[a];f[a]=function(){return b.apply(c,[this].concat(g.call(arguments,0)))}});
c.forEach(["attr","style"],function(a){f[a]=p(c[a],q)});c.forEach(["connect","addClass","removeClass","replaceClass","toggleClass","empty","removeAttr"],function(a){f[a]=n(c[a])});dojo.extend(dojo.NodeList,{_normalize:function(a,b){var d=a.parse===!0?!0:!1;if(typeof a.template=="string")var e=a.templateFunc||dojo.string&&dojo.string.substitute,a=e?e(a.template,a):a;e=typeof a;e=="string"||e=="number"?(a=dojo._toDom(a,b&&b.ownerDocument),a=a.nodeType==11?dojo._toArray(a.childNodes):[a]):dojo.isArrayLike(a)?
dojo.isArray(a)||(a=dojo._toArray(a)):a=[a];if(d)a._runParse=!0;return a},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(a,b,d,e){if(!(b.nodeType!=1&&d=="only"))for(var c,h=a.length,f=h-1;f>=0;f--){var g=e?this._cloneNode(a[f]):a[f];if(a._runParse&&dojo.parser&&dojo.parser.parse){c||(c=b.ownerDocument.createElement("div"));c.appendChild(g);dojo.parser.parse(c);for(g=c.firstChild;c.firstChild;)c.removeChild(c.firstChild)}f==h-1?dojo.place(g,b,d):b.parentNode.insertBefore(g,b);b=g}},
_stash:function(a){this._parent=a;return this},end:function(){return this._parent?this._parent:new this._NodeListCtor},concat:function(a){var b=c.isArray(this)?this:g.call(this,0),d=c.map(arguments,function(a){return a&&!c.isArray(a)&&(typeof NodeList!="undefined"&&a.constructor===NodeList||a.constructor===this._NodeListCtor)?g.call(a,0):a});return this._wrap(l.apply(b,d),this)},map:function(a,b){return this._wrap(c.map(this,a,b),this)},forEach:function(a,b){c.forEach(this,a,b);return this},coords:k(c.coords),
position:k(c.position),place:function(a,b){var d=c.query(a)[0];return this.forEach(function(a){c.place(a,d,b)})},orphan:function(a){return(a?c._filterQueryResult(this,a):this).forEach(r)},adopt:function(a,b){return c.query(a).place(this[0],b)._stash(this)},query:function(a){if(!a)return this;var b=this.map(function(b){return c.query(a,b).filter(function(a){return a!==void 0})});return this._wrap(l.apply([],b),this)},filter:function(a){var b=arguments,d=this,e=0;if(typeof a=="string"){d=c._filterQueryResult(this,
b[0]);if(b.length==1)return d._stash(this);e=1}return this._wrap(c.filter(d,b[e],b[e+1]),this)},addContent:function(a,b){for(var a=this._normalize(a,this[0]),c=0,e;e=this[c];c++)this._place(a,e,b,c>0);return this},instantiate:function(a,b){var d=c.isFunction(a)?a:c.getObject(a),b=b||{};return this.forEach(function(a){new d(b,a)})},at:function(){var a=new this._NodeListCtor;c.forEach(arguments,function(b){b<0&&(b=this.length+b);this[b]&&a.push(this[b])},this);return a._stash(this)}});h.events=["blur",
"focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];c.forEach(h.events,function(a){var b="on"+a;f[b]=function(a,c){return this.connect(b,a,c)}})}());