/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojo._base.query"]){dojo._hasResource["dojo._base.query"]=!0;var startDojoMappings=function(m){m.query=function(k,j,n){n=n||m.NodeList;return!k?new n:k.constructor==n?k:!m.isString(k)?new n(k):m.isString(j)&&(j=m.byId(j),!j)?new n:m.Sizzle(k,j,new n)};m._filterQueryResult=function(k,j){return m.Sizzle.filter(j,k)}},defineSizzle=function(m){function k(a,b,c,e){for(var d=0,g=e.length;d<g;d++){var f=e[d];if(f){for(var f=f[a],h=!1;f&&f.nodeType;){var i=f[c];if(i){h=e[i];break}f.nodeType===
1&&(f[c]=d);if(f.nodeName===b){h=f;break}f=f[a]}e[d]=h}}}function j(a,b,c,e){for(var d=0,g=e.length;d<g;d++){var f=e[d];if(f){for(var f=f[a],h=!1;f&&f.nodeType;){if(f[c]){h=e[f[c]];break}if(f.nodeType===1)if(f[c]=d,typeof b!=="string"){if(f===b){h=!0;break}}else if(i.filter(b,[f]).length>0){h=f;break}f=f[a]}e[d]=h}}}var n=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|[^[\]]+)+\]|\\.|[^ >+~,(\[]+)+|[>+~])(\s*,\s*)?/g,u=0,w=Object.prototype.toString,i=function(a,b,c,e){c=c||[];b=b||document;if(b.nodeType!==
1&&b.nodeType!==9)return[];if(!a||typeof a!=="string")return c;var d=[],g,f,t,k=!0;for(n.lastIndex=0;(g=n.exec(a))!==null;)if(d.push(g[1]),g[2]){t=RegExp.rightContext;break}if(d.length>1&&h.match.POS.exec(a))if(d.length===2&&h.relative[d[0]]){for(d="";g=h.match.POS.exec(a);)d+=g[0],a=a.replace(h.match.POS,"");g=i.filter(d,i(a,b))}else for(g=h.relative[d[0]]?[b]:i(d.shift(),b);d.length;){var r=[],a=d.shift();h.relative[a]&&(a+=d.shift());for(var l=0,m=g.length;l<m;l++)i(a,g[l],r);g=r}else{g=e?{expr:d.pop(),
set:o(e)}:i.find(d.pop(),d.length===1&&b.parentNode?b.parentNode:b);g=i.filter(g.expr,g.set);for(d.length>0?f=o(g):k=!1;d.length;){var j=d.pop(),r=j;h.relative[j]?r=d.pop():j="";r==null&&(r=b);h.relative[j](f,r)}}f||(f=g);if(!f)throw"Syntax error, unrecognized expression: "+(j||a);if(w.call(f)==="[object Array]")if(k)if(b.nodeType===1)for(l=0;f[l]!=null;l++)f[l]&&(f[l]===!0||f[l].nodeType===1&&x(b,f[l]))&&c.push(g[l]);else for(l=0;f[l]!=null;l++)f[l]&&f[l].nodeType===1&&c.push(g[l]);else c.push.apply(c,
f);else o(f,c);t&&i(t,b,c,e);return c};i.matches=function(a,b){return i(a,null,null,b)};i.find=function(a,b){var c,e;if(!a)return[];for(var d=0,g=h.order.length;d<g;d++){var f=h.order[d];if(e=h.match[f].exec(a)){var i=RegExp.leftContext;if(i.substr(i.length-1)!=="\\"&&(e[1]=(e[1]||"").replace(/\\/g,""),c=h.find[f](e,b),c!=null)){a=a.replace(h.match[f],"");break}}}c||(c=b.getElementsByTagName("*"));return{set:c,expr:a}};i.filter=function(a,b,c,e){for(var d=a,g=[],f=b,i,j;a&&b.length;){for(var k in h.filter)if((i=
h.match[k].exec(a))!=null){var l=h.filter[k],m=null,n=0,o,p;j=!1;f==g&&(g=[]);if(h.preFilter[k])if(i=h.preFilter[k](i,f,c,g,e)){if(i[0]===!0){m=[];p=null;for(var q,s=0;(q=f[s])!==void 0;s++)q&&p!==q&&(m.push(q),p=q)}}else j=o=!0;if(i)for(s=0;(p=f[s])!==void 0;s++)p&&(m&&p!=m[n]&&n++,o=l(p,i,n,m),q=e^!!o,c&&o!=null?q?j=!0:f[s]=!1:q&&(g.push(p),j=!0));if(o!==void 0){c||(f=g);a=a.replace(h.match[k],"");if(!j)return[];break}}a=a.replace(/\s*,\s*/,"");if(a==d)if(j==null)throw"Syntax error, unrecognized expression: "+
a;else break;d=a}return f};var h=i.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u0128-\uFFFF_-]|\\.)+)/,CLASS:/\.((?:[\w\u0128-\uFFFF_-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u0128-\uFFFF_-]|\\.)+)['"]*\]/,ATTR:/\[((?:[\w\u0128-\uFFFF_-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\]/,TAG:/^((?:[\w\u0128-\uFFFF\*_-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child\(?(even|odd|[\dn+-]*)\)?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)\(?(\d*)\)?(?:[^-]|$)/,PSEUDO:/:((?:[\w\u0128-\uFFFF_-]|\\.)+)(?:\((['"]*)((?:\([^\)]+\)|[^\2\(\)]*)+)\2\))?/},
attrMap:{"class":"className","for":"htmlFor"},relative:{"+":function(a,b){for(var c=0,e=a.length;c<e;c++){var d=a[c];if(d){for(d=d.previousSibling;d&&d.nodeType!==1;)d=d.previousSibling;a[c]=typeof b==="string"?d||!1:d===b}}typeof b==="string"&&i.filter(b,a,!0)},">":function(a,b){if(typeof b==="string"&&!/\W/.test(b))for(var b=b.toUpperCase(),c=0,e=a.length;c<e;c++){var d=a[c];if(d)d=d.parentNode,a[c]=d.nodeName===b?d:!1}else{c=0;for(e=a.length;c<e;c++)(d=a[c])&&(a[c]=typeof b==="string"?d.parentNode:
d.parentNode===b);typeof b==="string"&&i.filter(b,a,!0)}},"":function(a,b){var c="done"+u++,e=j;if(!b.match(/\W/))var d=b=b.toUpperCase(),e=k;e("parentNode",b,c,a,d)},"~":function(a,b){var c="done"+u++,e=j;if(typeof b==="string"&&!b.match(/\W/))var d=b=b.toUpperCase(),e=k;e("previousSibling",b,c,a,d)}},find:{ID:function(a,b){if(b.getElementById){var c=b.getElementById(a[1]);return c?[c]:[]}},NAME:function(a,b){return b.getElementsByName?b.getElementsByName(a[1]):null},TAG:function(a,b){return b.getElementsByTagName(a[1])}},
preFilter:{CLASS:function(a,b,c,e,d){for(var a=" "+a[1].replace(/\\/g,"")+" ",g=0;b[g];g++)d^(" "+b[g].className+" ").indexOf(a)>=0?c||e.push(b[g]):c&&(b[g]=!1);return!1},ID:function(a){return a[1]},TAG:function(a){return a[1].toUpperCase()},CHILD:function(a){if(a[1]=="nth"){var b=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(a[2]=="even"&&"2n"||a[2]=="odd"&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}a[0]="done"+u++;return a},ATTR:function(a){var b=a[1];h.attrMap[b]&&(a[1]=h.attrMap[b]);
a[2]==="~="&&(a[4]=" "+a[4]+" ");return a},PSEUDO:function(a,b,c,e,d){if(a[1]==="not")if(a[3].match(n).length>1)a[3]=i(a[3],null,null,b);else return a=i.filter(a[3],b,c,1^d),c||e.push.apply(e,a),!1;return a},POS:function(a){a.unshift(!0);return a}},filters:{enabled:function(a){return a.disabled===!1&&a.type!=="hidden"},disabled:function(a){return a.disabled===!0},checked:function(a){return a.checked===!0},selected:function(a){return a.selected===!0},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},
has:function(a,b,c){return!!i(c[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){return"text"===a.type},radio:function(a){return"radio"===a.type},checkbox:function(a){return"checkbox"===a.type},file:function(a){return"file"===a.type},password:function(a){return"password"===a.type},submit:function(a){return"submit"===a.type},image:function(a){return"image"===a.type},reset:function(a){return"reset"===a.type},button:function(a){return"button"===a.type||a.nodeName.toUpperCase()===
"BUTTON"},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)}},setFilters:{first:function(a,b){return b===0},last:function(a,b,c,e){return b===e.length-1},even:function(a,b){return b%2===0},odd:function(a,b){return b%2===1},lt:function(a,b,c){return b<c[3]-0},gt:function(a,b,c){return b>c[3]-0},nth:function(a,b,c){return c[3]-0==b},eq:function(a,b,c){return c[3]-0==b}},filter:{CHILD:function(a,b){var c=b[1],e=a.parentNode,d=b[0];if(e&&!e[d]){for(var g=1,f=e.firstChild;f;f=f.nextSibling)if(f.nodeType==
1)f.nodeIndex=g++;e[d]=g-1}if(c=="first")return a.nodeIndex==1;else if(c=="last")return a.nodeIndex==e[d];else if(c=="only")return e[d]==1;else if(c=="nth"){c=!1;e=b[2];d=b[3];if(e==1&&d==0)return!0;e==0?a.nodeIndex==d&&(c=!0):(a.nodeIndex-d)%e==0&&(a.nodeIndex-d)/e>=0&&(c=!0);return c}},PSEUDO:function(a,b,c,e){var d=b[1],g=h.filters[d];if(g)return g(a,c,b,e);else if(d==="contains")return(a.textContent||a.innerText||"").indexOf(b[3])>=0;else if(d==="not"){b=b[3];c=0;for(e=b.length;c<e;c++)if(b[c]===
a)return!1;return!0}},ID:function(a,b){return a.nodeType===1&&a.getAttribute("id")===b},TAG:function(a,b){return b==="*"&&a.nodeType===1||a.nodeName===b},CLASS:function(a,b){return b.test(a.className)},ATTR:function(a,b){var c=a[b[1]]||a.getAttribute(b[1]),e=c+"",d=b[2],g=b[4];return c==null?!1:d==="="?e===g:d==="*="?e.indexOf(g)>=0:d==="~="?(" "+e+" ").indexOf(g)>=0:!b[4]?c:d==="!="?e!=g:d==="^="?e.indexOf(g)===0:d==="$="?e.substr(e.length-g.length)===g:d==="|="?e===g||e.substr(0,g.length+1)===g+
"-":!1},POS:function(a,b,c,e){var d=h.setFilters[b[2]];if(d)return d(a,c,b,e)}}},v;for(v in h.match)h.match[v]=RegExp(h.match[v].source+/(?![^\[]*\])(?![^\(]*\))/.source);var o=function(a,b){a=Array.prototype.slice.call(a);return b?(b.push.apply(b,a),b):a};try{Array.prototype.slice.call(document.documentElement.childNodes)}catch(y){o=function(a,b){var c=b||[];if(w.call(a)==="[object Array]")Array.prototype.push.apply(c,a);else if(typeof a.length==="number")for(var e=0,d=a.length;e<d;e++)c.push(a[e]);
else for(e=0;a[e];e++)c.push(a[e]);return c}}(function(){var a=document.createElement("form"),b="script"+(new Date).getTime();a.innerHTML="<input name='"+b+"'/>";var c=document.documentElement;c.insertBefore(a,c.firstChild);if(document.getElementById(b))h.find.ID=function(a,b){if(b.getElementById){var c=b.getElementById(a[1]);return c?c.id===a[1]||c.getAttributeNode&&c.getAttributeNode("id").nodeValue===a[1]?[c]:void 0:[]}},h.filter.ID=function(a,b){var c=a.getAttributeNode&&a.getAttributeNode("id");
return a.nodeType===1&&c&&c.nodeValue===b};c.removeChild(a)})();(function(){var a=document.createElement("div");a.appendChild(document.createComment(""));if(a.getElementsByTagName("*").length>0)h.find.TAG=function(a,c){var e=c.getElementsByTagName(a[1]);if(a[1]==="*"){for(var d=[],g=0;e[g];g++)e[g].nodeType===1&&d.push(e[g]);e=d}return e}})();document.querySelectorAll&&function(){var a=i;i=function(b,c,e,d){c=c||document;if(!d&&c.nodeType===9)try{return o(c.querySelectorAll(b),e)}catch(g){}return a(b,
c,e,d)};i.find=a.find;i.filter=a.filter;i.selectors=a.selectors;i.matches=a.matches}();if(document.documentElement.getElementsByClassName)h.order.splice(1,0,"CLASS"),h.find.CLASS=function(a,b){return b.getElementsByClassName(a[1])};var x=document.compareDocumentPosition?function(a,b){return a.compareDocumentPosition(b)&16}:function(a,b){return a!==b&&(a.contains?a.contains(b):!0)};m.Sizzle=i};if(this.dojo){var defined=0;dojo.provide("dojo._base.query"),dojo.require("dojo._base.NodeList"),defineSizzle(dojo)}else defineSizzle(window)};