/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo._base.query"]||(dojo._hasResource["dojo._base.query"]=!0,function(){var B=function(d){var q=d.trim,t=d.forEach,h=d._NodeListCtor=d.NodeList,k=(d.isWebKit||d.isMozilla)&&d.doc.compatMode=="BackCompat",K=d.doc.firstChild.children?"children":"childNodes",m=!1,l=function(){return!0},H=function(a){a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var b=function(b,c){return q(a.slice(b,c))},c=[],e=-1,f=-1,g=-1,d=-1,C=-1,n=-1,y=-1,h="",o="",k,j=0,r=a.length,i=null,p=null,l=function(){if(n>=
0)i.id=b(n,j).replace(/\\/g,""),n=-1;if(y>=0){var a=y==j?null:b(y,j);i[">~+".indexOf(a)<0?"tag":"oper"]=a;y=-1}C>=0&&(i.classes.push(b(C+1,j).replace(/\\/g,"")),C=-1)};h=o,o=a.charAt(j),j<r;j++)if(h!="\\")if(i||(k=j,i={query:null,pseudos:[],attrs:[],classes:[],tag:null,oper:null,id:null,getTag:function(){return m?this.otag:this.tag}},y=j),e>=0)if(o=="]"){p.attr?p.matchFor=b(g||e+1,j):p.attr=b(e+1,j);if((e=p.matchFor)&&(e.charAt(0)=='"'||e.charAt(0)=="'"))p.matchFor=e.slice(1,-1);i.attrs.push(p);p=
null;e=g=-1}else{if(o=="=")g="|~^$*".indexOf(h)>=0?h:"",p.type=g+o,p.attr=b(e+1,j-g.length),g=j+1}else if(f>=0){if(o==")"){if(d>=0)p.value=b(f+1,j);d=f=-1}}else if(o=="#")l(),n=j+1;else if(o==".")l(),C=j;else if(o==":")l(),d=j;else if(o=="[")l(),e=j,p={};else if(o=="(")d>=0&&(p={name:b(d+1,j),value:null},i.pseudos.push(p)),f=j;else if(o==" "&&h!=o){l();d>=0&&i.pseudos.push({name:b(d+1,j)});i.loops=i.pseudos.length||i.attrs.length||i.classes.length;i.oquery=i.query=b(k,j);i.otag=i.tag=i.oper?null:
i.tag||"*";if(i.tag)i.tag=i.tag.toUpperCase();if(c.length&&c[c.length-1].oper)i.infixOper=c.pop(),i.query=i.infixOper.query+" "+i.query;c.push(i);i=null}return c},u=function(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}},v=function(a,b){var c=b||[];a&&c.push(a);return c},D=function(a){return 1==a.nodeType},w=function(a,b){return!a?"":b=="class"?a.className||"":b=="for"?a.htmlFor||"":b=="style"?a.style.cssText||"":(m?a.getAttribute(b):a.getAttribute(b,
2))||""},B={"*=":function(a,b){return function(c){return w(c,a).indexOf(b)>=0}},"^=":function(a,b){return function(c){return w(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+w(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+w(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){var c=" "+b+"-";return function(e){e=" "+w(e,a);return e==b||e.indexOf(c)==0}},"=":function(a,b){return function(c){return w(c,a)==b}}},E=typeof d.doc.firstChild.nextElementSibling==
"undefined",z=!E?"nextElementSibling":"nextSibling",J=!E?"previousElementSibling":"previousSibling",A=E?D:l,L=function(a){for(;a=a[J];)if(A(a))return!1;return!0},M=function(a){for(;a=a[z];)if(A(a))return!1;return!0},F=function(a){var b=a.parentNode,c=0,e=b[K],f=a._i||-1,g=b._l||-1;if(!e)return-1;e=e.length;if(g==e&&f>=0&&g>=0)return f;b._l=e;f=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[z])if(A(b))b._i=++c,a===b&&(f=c);return f},U=function(a){return!(F(a)%2)},V=function(a){return F(a)%2},I={checked:function(){return function(a){return!!("checked"in
a?a.checked:a.selected)}},"first-child":function(){return L},"last-child":function(){return M},"only-child":function(){return function(a){return!L(a)?!1:!M(a)?!1:!0}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;if(c===1||c==3)return!1}return!0}},contains:function(a,b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,b){var c=H(b)[0],e={el:1};if(c.tag!="*")e.tag=
1;if(!c.classes.length)e.classes=1;var f=s(c,e);return function(a){return!f(a)}},"nth-child":function(a,b){var c=parseInt;if(b=="odd")return V;else if(b=="even")return U;if(b.indexOf("n")!=-1){var e=b.split("n",2),f=e[0]?e[0]=="-"?-1:c(e[0]):1,g=e[1]?c(e[1]):0,d=0,h=-1;f>0?g<0?g=g%f&&f+g%f:g>0&&(g>=f&&(d=g-g%f),g%=f):f<0&&(f*=-1,g>0&&(h=g,g%=f));if(f>0)return function(a){a=F(a);return a>=d&&(h<0||a<=h)&&a%f==g};else b=g}var n=c(b);return function(a){return F(a)==n}}},W=d.isIE<9||dojo.isIE&&dojo.isQuirks?
function(a){var b=a.toLowerCase();b=="class"&&(a="className");return function(c){return m?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},s=function(a,b){if(!a)return l;var b=b||{},c=null;"el"in b||(c=u(c,D));"tag"in b||a.tag!="*"&&(c=u(c,function(b){return b&&b.tagName==a.getTag()}));"classes"in b||t(a.classes,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=u(c,function(a){return d.test(a.className)});c.count=b});"pseudos"in b||
t(a.pseudos,function(a){var b=a.name;I[b]&&(c=u(c,I[b](b,a.value)))});"attrs"in b||t(a.attrs,function(a){var b,d=a.attr;a.type&&B[a.type]?b=B[a.type](d,a.matchFor):d.length&&(b=W(d));b&&(c=u(c,b))});"id"in b||a.id&&(c=u(c,function(b){return!!b&&b.id==a.id}));c||"default"in b||(c=l);return c},X=function(a){return function(b,c,e){for(;b=b[z];)if(!E||D(b)){(!e||x(b,e))&&a(b)&&c.push(b);break}return c}},Y=function(a){return function(b,c,e){for(b=b[z];b;){if(A(b)){if(e&&!x(b,e))break;a(b)&&c.push(b)}b=
b[z]}return c}},Z=function(a){a=a||l;return function(b,c,e){for(var d=0,g=b[K];b=g[d++];)A(b)&&(!e||x(b,e))&&a(b,d)&&c.push(b);return c}},N={},O=function(a){var b=N[a.query];if(b)return b;var c=a.infixOper,c=c?c.oper:"",e=s(a,{el:1}),f="*"==a.tag,g=d.doc.getElementsByClassName;if(c){g={el:1};if(f)g.tag=1;e=s(a,g);"+"==c?b=X(e):"~"==c?b=Y(e):">"==c&&(b=Z(e))}else if(a.id)e=!a.loops&&f?l:s(a,{el:1,id:1}),b=function(b,c){var f=d.byId(a.id,b.ownerDocument||b);if(f&&e(f))if(9==b.nodeType)return v(f,c);
else{for(var g=f.parentNode;g;){if(g==b)break;g=g.parentNode}if(g)return v(f,c)}};else if(g&&/\{\s*\[native code\]\s*\}/.test(String(g))&&a.classes.length&&!k)var e=s(a,{el:1,classes:1,id:1}),h=a.classes.join(" "),b=function(a,b,c){for(var b=v(0,b),d,f=0,g=a.getElementsByClassName(h);d=g[f++];)e(d,a)&&x(d,c)&&b.push(d);return b};else!f&&!a.loops?b=function(b,c,e){for(var c=v(0,c),d=0,f=b.getElementsByTagName(a.getTag());b=f[d++];)x(b,e)&&c.push(b);return c}:(e=s(a,{el:1,tag:1,id:1}),b=function(b,
c,d){for(var c=v(0,c),f,g=0,h=b.getElementsByTagName(a.getTag());f=h[g++];)e(f,b)&&x(f,d)&&c.push(f);return c});return N[a.query]=b},P={},Q={},R=function(a){var b=H(q(a));if(b.length==1){var c=O(b[0]);return function(a){if(a=c(a,new h))a.nozip=!0;return a}}return function(a){for(var a=v(a),c,d,h=b.length,k,n,l=0;l<h;l++){n=[];c=b[l];d=a.length-1;if(d>0)k={},n.nozip=!0;d=O(c);for(var m=0;c=a[m];m++)d(c,n,k);if(!n.length)break;a=n}return n}},G=navigator.userAgent,G=d.isWebKit&&G.indexOf("WebKit/")>
0&&parseFloat(G.split("WebKit/")[1])>528,$=d.isIE?"commentStrip":"nozip",S=!!d.doc.querySelectorAll&&(!d.isSafari||d.isSafari>3.1||G),aa=/n\+\d|([^ ])?([>~+])([^ =])?/g,ba=function(a,b,c,d){return c?(b?b+" ":"")+c+(d?" "+d:""):a},T=function(a,b){a=a.replace(aa,ba);if(S){var c=Q[a];if(c&&!b)return c}if(c=P[a])return c;var c=a.charAt(0),e=-1==a.indexOf(" ");a.indexOf("#")>=0&&e&&(b=!0);if(S&&!b&&">~+".indexOf(c)==-1&&(!d.isIE||a.indexOf(":")==-1)&&!(k&&a.indexOf(".")>=0)&&a.indexOf(":contains")==-1&&
a.indexOf(":checked")==-1&&a.indexOf("|=")==-1){var f=">~+".indexOf(a.charAt(a.length-1))>=0?a+" *":a;return Q[a]=function(b){try{if(!(9==b.nodeType||e))throw"";var c=b.querySelectorAll(f);c[$]=!0;return c}catch(d){return T(a,!0)(b)}}}else{var g=a.split(/\s*,\s*/);return P[a]=g.length<2?R(a):function(a){for(var b=0,c=[],d;d=g[b++];)c=c.concat(R(d)(a));return c}}},r=0,ca=d.isIE?function(a){return m?a.getAttribute("_uid")||a.setAttribute("_uid",++r)||r:a.uniqueID}:function(a){return a._uid||(a._uid=
++r)},x=function(a,b){if(!b)return 1;var c=ca(a);return!b[c]?b[c]=1:0},da=function(a){if(a&&a.nozip)return h._wrap?h._wrap(a):a;var b=new h;if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(a.length<2)return b;r++;if(d.isIE&&m){var c=r+"";a[0].setAttribute("_zipIdx",c);for(var e=1,f;f=a[e];e++)a[e].getAttribute("_zipIdx")!=c&&b.push(f),f.setAttribute("_zipIdx",c)}else if(d.isIE&&a.commentStrip)try{for(e=1;f=a[e];e++)D(f)&&b.push(f)}catch(g){}else{a[0]&&(a[0]._zipIdx=r);for(e=1;f=a[e];e++)a[e]._zipIdx!=
r&&b.push(f),f._zipIdx=r}return b};d.query=function(a,b){h=d._NodeListCtor;if(!a)return new h;if(a.constructor==h)return a;if(typeof a!="string")return new h(a);if(typeof b=="string"&&(b=d.byId(b),!b))return new h;var b=b||d.doc,c=b.ownerDocument||b.documentElement;m=b.contentType&&b.contentType=="application/xml"||d.isOpera&&(b.doctype||c.toString()=="[object XMLDocument]")||!!c&&(d.isIE?c.xml:b.xmlVersion||c.xmlVersion);return(c=T(a)(b))&&c.nozip&&!h._wrap?c:da(c)};d.query.pseudos=I;d._filterQueryResult=
function(a,b,c){for(var e=new d._NodeListCtor,f=H(b),f=f.length==1&&!/[^\w#\.]/.test(b)?s(f[0]):function(a){return dojo.query(b,c).indexOf(a)!=-1},g=0,h;h=a[g];g++)f(h)&&e.push(h);return e}},J=function(){acme={trim:function(d){for(var d=d.replace(/^\s+/,""),k=d.length-1;k>=0;k--)if(/\S/.test(d.charAt(k))){d=d.substring(0,k+1);break}return d},forEach:function(d,k,q){if(d&&d.length)for(var m=0,l=d.length;m<l;++m)k.call(q||window,d[m],m,d)},byId:function(d,k){return typeof d=="string"?(k||document).getElementById(d):
d},doc:document,NodeList:Array};var d=navigator,q=d.userAgent,d=d.appVersion,t=parseFloat(d);acme.isOpera=q.indexOf("Opera")>=0?t:void 0;acme.isKhtml=d.indexOf("Konqueror")>=0?t:void 0;acme.isWebKit=parseFloat(q.split("WebKit/")[1])||void 0;acme.isChrome=parseFloat(q.split("Chrome/")[1])||void 0;if((q=Math.max(d.indexOf("WebKit"),d.indexOf("Safari"),0))&&!acme.isChrome)if(acme.isSafari=parseFloat(d.split("Version/")[1]),!acme.isSafari||parseFloat(d.substr(q+7))<=419.3)acme.isSafari=2;if(document.all&&
!acme.isOpera)acme.isIE=parseFloat(d.split("MSIE ")[1])||void 0;Array._wrap=function(d){return d};return acme};this.dojo?(dojo.provide("dojo._base.query"),dojo.require("dojo._base.NodeList"),dojo.require("dojo._base.lang"),B(this.queryPortability||this.acme||dojo)):B(this.queryPortability||this.acme||J())}());