/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojo._base.xhr"]||(dojo._hasResource["dojo._base.xhr"]=!0,dojo.provide("dojo._base.xhr"),dojo.require("dojo._base.Deferred"),dojo.require("dojo._base.json"),dojo.require("dojo._base.lang"),dojo.require("dojo._base.query"),function(){var c=dojo,m=c.config;dojo.fieldToObject=function(a){var b=null;if(a=c.byId(a)){var f=a.name,e=(a.type||"").toLowerCase();if(f&&e&&!a.disabled)if(e=="radio"||e=="checkbox"){if(a.checked)b=a.value}else a.multiple?(b=[],c.query("option",a).forEach(function(a){a.selected&&
b.push(a.value)})):b=a.value}return b};dojo.formToObject=function(a){var b={};c.forEach(dojo.byId(a).elements,function(a){var e=a.name,d=(a.type||"").toLowerCase();if(e&&d&&"file|submit|image|reset|button|".indexOf(d)==-1&&!a.disabled){a=c.fieldToObject(a);if(a!==null){var g=b[e];typeof g=="string"?b[e]=[g,a]:c.isArray(g)?g.push(a):b[e]=a}if(d=="image")b[e+".x"]=b[e+".y"]=b[e].x=b[e].y=0}});return b};dojo.objectToQuery=function(a){var b=encodeURIComponent,f=[],e={},d;for(d in a){var g=a[d];if(g!=
e[d]){var i=b(d)+"=";if(c.isArray(g))for(var h=0;h<g.length;h++)f.push(i+b(g[h]));else f.push(i+b(g))}}return f.join("&")};dojo.formToQuery=function(a){return c.objectToQuery(c.formToObject(a))};dojo.formToJson=function(a,b){return c.toJson(c.formToObject(a),b)};dojo.queryToObject=function(a){var b={},a=a.split("&"),f=decodeURIComponent;c.forEach(a,function(a){if(a.length){var d=a.split("="),a=f(d.shift()),d=f(d.join("="));typeof b[a]=="string"&&(b[a]=[b[a]]);c.isArray(b[a])?b[a].push(d):b[a]=d}});
return b};dojo._blockAsync=!1;var n=c._contentHandlers=dojo.contentHandlers={text:function(a){return a.responseText},json:function(a){return c.fromJson(a.responseText||null)},"json-comment-filtered":function(a){dojo.config.useCommentedJson||console.warn("Consider using the standard mimetype:application/json. json-commenting can introduce security issues. To decrease the chances of hijacking, use the standard the 'json' handler and prefix your json with: {}&&\nUse djConfig.useCommentedJson=true to turn off this message.");
var a=a.responseText,b=a.indexOf("/*"),f=a.lastIndexOf("*/");if(b==-1||f==-1)throw Error("JSON was not comment filtered");return c.fromJson(a.substring(b+2,f))},javascript:function(a){return c.eval(a.responseText)},xml:function(a){var b=a.responseXML;if(c.isIE&&(!b||!b.documentElement)){var f=function(a){return"MSXML"+a+".DOMDocument"},f=["Microsoft.XMLDOM",f(6),f(4),f(3),f(2)];c.some(f,function(c){try{var d=new ActiveXObject(c);d.async=!1;d.loadXML(a.responseText);b=d}catch(f){return!1}return!0})}return b},
"json-comment-optional":function(a){return a.responseText&&/^[^{\[]*\/\*/.test(a.responseText)?n["json-comment-filtered"](a):n.json(a)}};dojo._ioSetArgs=function(a,b,f,e){var d={args:a,url:a.url},g=null;if(a.form){var g=c.byId(a.form),i=g.getAttributeNode("action");d.url=d.url||(i?i.value:null);g=c.formToObject(g)}i=[{}];g&&i.push(g);a.content&&i.push(a.content);a.preventCache&&i.push({"dojo.preventCache":(new Date).valueOf()});d.query=c.objectToQuery(c.mixin.apply(null,i));d.handleAs=a.handleAs||
"text";var h=new c.Deferred(b);h.addCallbacks(f,function(a){return e(a,h)});var j=a.load;j&&c.isFunction(j)&&h.addCallback(function(b){return j.call(a,b,d)});var k=a.error;k&&c.isFunction(k)&&h.addErrback(function(b){return k.call(a,b,d)});var l=a.handle;l&&c.isFunction(l)&&h.addBoth(function(b){return l.call(a,b,d)});m.ioPublish&&c.publish&&d.args.ioPublish!==!1&&(h.addCallbacks(function(a){c.publish("/dojo/io/load",[h,a]);return a},function(a){c.publish("/dojo/io/error",[h,a]);return a}),h.addBoth(function(a){c.publish("/dojo/io/done",
[h,a]);return a}));h.ioArgs=d;return h};var p=function(a){a.canceled=!0;var b=a.ioArgs.xhr,c=typeof b.abort;(c=="function"||c=="object"||c=="unknown")&&b.abort();a=a.ioArgs.error;if(!a)a=Error("xhr cancelled"),a.dojoType="cancel";return a},q=function(a){a=n[a.ioArgs.handleAs](a.ioArgs.xhr);return a===void 0?null:a},r=function(a,b){b.ioArgs.args.failOk||console.error(a);return a},l=null,j=[],k=0,s=function(a){k<=0&&(k=0,m.ioPublish&&c.publish&&(!a||a&&a.ioArgs.args.ioPublish!==!1)&&c.publish("/dojo/io/stop"))},
o=function(){var a=(new Date).getTime();if(!c._blockAsync)for(var b=0,f;b<j.length&&(f=j[b]);b++){var e=f.dfd,d=function(){if(!e||e.canceled||!f.validCheck(e))j.splice(b--,1),k-=1;else if(f.ioCheck(e))j.splice(b--,1),f.resHandle(e),k-=1;else if(e.startTime&&e.startTime+(e.ioArgs.args.timeout||0)<a){j.splice(b--,1);var c=Error("timeout exceeded");c.dojoType="timeout";e.errback(c);e.cancel();k-=1}};if(dojo.config.debugAtAllCosts)d.call(this);else try{d.call(this)}catch(g){e.errback(g)}}s(e);j.length||
(clearInterval(l),l=null)};dojo._ioCancelAll=function(){try{c.forEach(j,function(a){try{a.dfd.cancel()}catch(c){}})}catch(a){}};c.isIE&&c.addOnWindowUnload(c._ioCancelAll);c._ioNotifyStart=function(a){m.ioPublish&&c.publish&&a.ioArgs.args.ioPublish!==!1&&(k||c.publish("/dojo/io/start"),k+=1,c.publish("/dojo/io/send",[a]))};c._ioWatch=function(a,b,c,e){var d=a.ioArgs.args;if(d.timeout)a.startTime=(new Date).getTime();j.push({dfd:a,validCheck:b,ioCheck:c,resHandle:e});l||(l=setInterval(o,50));d.sync&&
o()};var t=function(a){return a.ioArgs.xhr.readyState},u=function(a){return 4==a.ioArgs.xhr.readyState},v=function(a){var b=a.ioArgs.xhr;if(c._isDocumentOk(b))a.callback(a);else{var f=Error("Unable to load "+a.ioArgs.url+" status:"+b.status);f.status=b.status;f.responseText=b.responseText;a.errback(f)}};dojo._ioAddQueryToUrl=function(a){if(a.query.length)a.url+=(a.url.indexOf("?")==-1?"?":"&")+a.query,a.query=null};dojo.xhr=function(a,b,f){var e=c._ioSetArgs(b,p,q,r),d=e.ioArgs,g=d.xhr=c._xhrObj(d.args);
if(!g)return e.cancel(),e;"postData"in b?d.query=b.postData:"putData"in b?d.query=b.putData:"rawBody"in b?d.query=b.rawBody:(arguments.length>2&&!f||"POST|PUT".indexOf(a.toUpperCase())==-1)&&c._ioAddQueryToUrl(d);g.open(a,d.url,b.sync!==!0,b.user||void 0,b.password||void 0);if(b.headers)for(var i in b.headers)i.toLowerCase()==="content-type"&&!b.contentType?b.contentType=b.headers[i]:b.headers[i]&&g.setRequestHeader(i,b.headers[i]);g.setRequestHeader("Content-Type",b.contentType||"application/x-www-form-urlencoded");
(!b.headers||!("X-Requested-With"in b.headers))&&g.setRequestHeader("X-Requested-With","XMLHttpRequest");c._ioNotifyStart(e);if(dojo.config.debugAtAllCosts)g.send(d.query);else try{g.send(d.query)}catch(h){d.error=h,e.cancel()}c._ioWatch(e,t,u,v);return e};dojo.xhrGet=function(a){return c.xhr("GET",a)};dojo.rawXhrPost=dojo.xhrPost=function(a){return c.xhr("POST",a,!0)};dojo.rawXhrPut=dojo.xhrPut=function(a){return c.xhr("PUT",a,!0)};dojo.xhrDelete=function(a){return c.xhr("DELETE",a)}}());