/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.uuid.generateTimeBasedUuid"])dojo._hasResource["dojox.uuid.generateTimeBasedUuid"]=!0,dojo.provide("dojox.uuid.generateTimeBasedUuid"),dojox.uuid.generateTimeBasedUuid=function(d){return dojox.uuid.generateTimeBasedUuid._generator.generateUuidString(d)},dojox.uuid.generateTimeBasedUuid.isValidNode=function(d){var g=parseInt(d,16);return dojo.isString(d)&&d.length==12&&isFinite(g)},dojox.uuid.generateTimeBasedUuid.setNode=function(d){dojox.uuid.assert(d===null||this.isValidNode(d));
this._uniformNode=d},dojox.uuid.generateTimeBasedUuid.getNode=function(){return this._uniformNode},dojox.uuid.generateTimeBasedUuid._generator=new function(){function d(a){a[2]+=a[3]>>>16;a[3]&=65535;a[1]+=a[2]>>>16;a[2]&=65535;a[0]+=a[1]>>>16;a[1]&=65535;dojox.uuid.assert(a[0]>>>16===0)}function g(a){var c=[0,0,0,0];c[3]=a%65536;a-=c[3];a/=65536;c[2]=a%65536;a-=c[2];a/=65536;c[1]=a%65536;a-=c[1];a/=65536;c[0]=a;return c}function j(a,c){dojox.uuid.assert(dojo.isArray(a));dojox.uuid.assert(dojo.isArray(c));
dojox.uuid.assert(a.length==4);dojox.uuid.assert(c.length==4);var b=!1;a[0]*c[0]!==0&&(b=!0);a[0]*c[1]!==0&&(b=!0);a[0]*c[2]!==0&&(b=!0);a[1]*c[0]!==0&&(b=!0);a[1]*c[1]!==0&&(b=!0);a[2]*c[0]!==0&&(b=!0);dojox.uuid.assert(!b);b=[0,0,0,0];b[0]+=a[0]*c[3];d(b);b[0]+=a[1]*c[2];d(b);b[0]+=a[2]*c[1];d(b);b[0]+=a[3]*c[0];d(b);b[1]+=a[1]*c[3];d(b);b[1]+=a[2]*c[2];d(b);b[1]+=a[3]*c[1];d(b);b[2]+=a[2]*c[3];d(b);b[2]+=a[3]*c[2];d(b);b[3]+=a[3]*c[3];d(b);return b}function h(a,c){for(;a.length<c;)a="0"+a;return a}
this.GREGORIAN_CHANGE_OFFSET_IN_HOURS=3394248;var k=null,l=null,m=null,i=0,n=null,o=null;this.generateUuidString=function(a){if(a)dojox.uuid.assert(dojox.uuid.generateTimeBasedUuid.isValidNode(a));else if(dojox.uuid.generateTimeBasedUuid._uniformNode)a=dojox.uuid.generateTimeBasedUuid._uniformNode;else{if(!k){for(var a=(32768|Math.floor(Math.random()%1*Math.pow(2,15))).toString(16),c=Math.floor(Math.random()%1*Math.pow(2,32)).toString(16);c.length<8;)c="0"+c;k=a+c}a=k}l||(l=(32768|Math.floor(Math.random()%
1*Math.pow(2,14))).toString(16));var c=new Date,b=g(c.valueOf());if(!n){var e=g(3600),f=g(dojox.uuid.generateTimeBasedUuid._generator.GREGORIAN_CHANGE_OFFSET_IN_HOURS),e=j(f,e),f=g(1E3);n=j(e,f);o=g(1E4)}e=n;dojox.uuid.assert(dojo.isArray(e));dojox.uuid.assert(dojo.isArray(b));dojox.uuid.assert(e.length==4);dojox.uuid.assert(b.length==4);f=[0,0,0,0];f[3]=e[3]+b[3];f[2]=e[2]+b[2];f[1]=e[1]+b[1];f[0]=e[0]+b[0];d(f);b=j(f,o);if(c.valueOf()==m){if(b[3]+=i,d(b),i+=1,i==1E4)for(;c.valueOf()==m;)c=new Date}else m=
c.valueOf(),i=1;c=b[2].toString(16);e=b[3].toString(16);c=h(c,4)+h(e,4);e=b[1].toString(16);e=h(e,4);b=b[0].toString(16);b=h(b,3);a=c+"-"+e+"-1"+b+"-"+l+"-"+a;return a=a.toLowerCase()}};