/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.drawing.plugins.drawing.Silverlight"])dojo._hasResource["dojox.drawing.plugins.drawing.Silverlight"]=!0,dojo.provide("dojox.drawing.plugins.drawing.Silverlight"),dojox.drawing.plugins.drawing.Silverlight=dojox.drawing.util.oo.declare(function(e){if(dojox.gfx.renderer=="silverlight")this.mouse=e.mouse,this.stencils=e.stencils,this.anchors=e.anchors,this.canvas=e.canvas,this.util=e.util,dojo.connect(this.stencils,"register",this,function(a){var b,c,d,e,f,g=this;(function(){b=
a.container.connect("onmousedown",function(b){b.superTarget=a;g.mouse.down(b)})})();c=dojo.connect(a,"setTransform",this,function(){});d=dojo.connect(a,"onBeforeRender",function(){});e=dojo.connect(a,"onRender",this,function(){});f=dojo.connect(a,"destroy",this,function(){dojo.forEach([b,c,d,e,f],dojo.disconnect,dojo)})}),dojo.connect(this.anchors,"onAddAnchor",this,function(a){var b=a.shape.connect("onmousedown",this.mouse,function(b){b.superTarget=a;this.down(b)}),c=dojo.connect(a,"disconnectMouse",
this,function(){dojo.disconnect(b);dojo.disconnect(c)})}),this.mouse._down=function(a){var b=this._getXY(a),c=b.x-this.origin.x,d=b.y-this.origin.y;c*=this.zoom;d*=this.zoom;this.origin.startx=c;this.origin.starty=d;this._lastx=c;this._lasty=d;this.drawingType=this.util.attr(a,"drawingType")||"";b=this._getId(a);c={x:c,y:d,id:b};console.log(" > > > id:",b,"drawingType:",this.drawingType,"evt:",a);this.onDown(c);this._clickTime=(new Date).getTime();this._lastClickTime&&this._clickTime-this._lastClickTime<
this.doublClickSpeed&&(a=this.eventName("doubleClick"),console.warn("DOUBLE CLICK",a,c),this._broadcastEvent(a,c));this._lastClickTime=this._clickTime},this.mouse.down=function(a){clearTimeout(this.__downInv);this.util.attr(a,"drawingType")=="surface"?this.__downInv=setTimeout(dojo.hitch(this,function(){this._down(a)}),500):this._down(a)},this.mouse._getXY=function(a){if(a.pageX)return{x:a.pageX,y:a.pageY,cancelBubble:!0};console.log("EVT",a);for(var b in a);console.log("EVTX",a.x);return a.x!==void 0?
{x:a.x+this.origin.x,y:a.y+this.origin.y}:{x:a.pageX,y:a.pageY}},this.mouse._getId=function(a){return this.util.attr(a,"id")},this.util.attr=function(a,b,c){if(!a)return!1;try{var d;d=a.superTarget?a.superTarget:a.superClass?a.superClass:a.target?a.target:a;if(c!==void 0)return a[b]=c;if(d.tagName){if(b=="drawingType"&&d.tagName.toLowerCase()=="object")return"surface";var e=dojo.attr(d,b)}return e=d[b]}catch(f){return!1}}},{});