/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.drawing.ui.dom.Toolbar"]||(dojo._hasResource["dojox.drawing.ui.dom.Toolbar"]=!0,dojo.provide("dojox.drawing.ui.dom.Toolbar"),dojo.deprecated("dojox.drawing.ui.dom.Toolbar","It may not even make it to the 1.4 release.",1.4),function(){dojo.declare("dojox.drawing.ui.dom.Toolbar",[],{baseClass:"drawingToolbar",buttonClass:"drawingButton",iconClass:"icon",constructor:function(b,c){dojo.addOnLoad(this,function(){this.domNode=dojo.byId(c);dojo.addClass(this.domNode,this.baseClass);
this.parse()})},createIcon:function(b,c){var a=c&&c.setup?c.setup:{};if(a.iconClass){var f=a.iconClass?a.iconClass:"iconNone",a=dojo.create("div",{title:a.tooltip?a.tooltip:"Tool"},b);dojo.addClass(a,this.iconClass);dojo.addClass(a,f);dojo.connect(b,"mouseup",function(a){dojo.stopEvent(a);dojo.removeClass(b,"active")});dojo.connect(b,"mouseover",function(a){dojo.stopEvent(a);dojo.addClass(b,"hover")});dojo.connect(b,"mousedown",this,function(a){dojo.stopEvent(a);dojo.addClass(b,"active")});dojo.connect(b,
"mouseout",this,function(a){dojo.stopEvent(a);dojo.removeClass(b,"hover")})}},createTool:function(b){b.innerHTML="";var c=dojo.attr(b,"tool");this.toolNodes[c]=b;dojo.attr(b,"tabIndex",1);var a=dojo.getObject(c);this.createIcon(b,a);this.drawing.registerTool(c,a);dojo.connect(b,"mouseup",this,function(a){dojo.stopEvent(a);dojo.removeClass(b,"active");this.onClick(c)});dojo.connect(b,"mouseover",function(a){dojo.stopEvent(a);dojo.addClass(b,"hover")});dojo.connect(b,"mousedown",this,function(a){dojo.stopEvent(a);
dojo.addClass(b,"active")});dojo.connect(b,"mouseout",this,function(a){dojo.stopEvent(a);dojo.removeClass(b,"hover")})},parse:function(){var b=dojo.attr(this.domNode,"drawingId");this.drawing=dojox.drawing.util.common.byId(b);!this.drawing&&console.error("Drawing not found based on 'drawingId' in Toolbar. ");this.toolNodes={};var c;dojo.query(">",this.domNode).forEach(function(a,b){a.className=this.buttonClass;var d=dojo.attr(a,"tool");dojo.attr(a,"action");var e=dojo.attr(a,"plugin");if(d){if(b==
0||dojo.attr(a,"selected")=="true")c=d;this.createTool(a)}else if(e){d={name:e,options:{}};if(e=dojo.attr(a,"options"))d.options=eval("("+e+")");d.options.node=a;a.innerHTML="";this.drawing.addPlugin(d);this.createIcon(a,dojo.getObject(dojo.attr(a,"plugin")))}},this);this.drawing.initPlugins();dojo.connect(this.drawing,"setTool",this,"onSetTool");this.drawing.setTool(c)},onClick:function(b){this.drawing.setTool(b)},onSetTool:function(b){for(var c in this.toolNodes)c==b?(dojo.addClass(this.toolNodes[b],
"selected"),this.toolNodes[b].blur()):dojo.removeClass(this.toolNodes[c],"selected")}})}());