<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
<title><?php echo $this->title; ?></title>
</head>

<body>
<h1><?php echo $this->title; ?></h1>
<p><?php echo $this->description; ?></p>

<table border="1">
<thead>
<tr>
    <th><?php echo $this->txtNo; ?></th>
    <th><?php echo $this->txtType; ?></th>
    <th><?php echo $this->txtItem; ?></th>
</tr>
</thead>
<tbody>
<?php
foreach ($this->items as $item): ?>
<tr>
    <td><?php echo $item['topicId']; ?></td>
    <td><?php echo $item['topicType']; ?></td>
    <td><?php echo $item['display']; ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
</body>
</html>
