/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.drawing.ui.Toolbar"]||(dojo._hasResource["dojox.drawing.ui.Toolbar"]=!0,dojo.provide("dojox.drawing.ui.Toolbar"),dojo.require("dojox.drawing.library.icons"),dojo.declare("dojox.drawing.ui.Toolbar",[],{constructor:function(b,a){this.util=dojox.drawing.util.common;if(b.drawing)this.drawing=this.toolDrawing=b.drawing,this.width=this.toolDrawing.width,this.height=this.toolDrawing.height,this.strSelected=b.selected,this.strTools=b.tools,this.strPlugs=b.plugs,this._mixprops(["padding",
"margin","size","radius"],b),this.addBack(),this.orient=b.orient?b.orient:!1;else{var j=dojo.marginBox(a);this.width=j.w;this.height=j.h;this.strSelected=dojo.attr(a,"selected");this.strTools=dojo.attr(a,"tools");this.strPlugs=dojo.attr(a,"plugs");this._mixprops(["padding","margin","size","radius"],a);this.toolDrawing=new dojox.drawing.Drawing({mode:"ui"},a);this.orient=dojo.attr(a,"orient")}this.horizontal=this.orient?this.orient=="H":this.width>this.height;console.log("this.hor: ",this.horizontal,
" orient: ",this.orient);this.toolDrawing.ready?(this.makeButtons(),!this.strSelected&&this.drawing.defaults.clickMode&&this.drawing.mouse.setCursor("default")):dojo.connect(this.toolDrawing,"onSurfaceReady",this,function(){dojo.disconnect(b);this.drawing=dojox.drawing.getRegistered("drawing",dojo.attr(a,"drawingId"));this.makeButtons();if(!this.strSelected&&this.drawing.defaults.clickMode)var b=dojo.connect(this.drawing,"onSurfaceReady",this,function(){dojo.disconnect(b);this.drawing.mouse.setCursor("default")})})},
padding:10,margin:5,size:30,radius:3,toolPlugGap:20,strSelected:"",strTools:"",strPlugs:"",makeButtons:function(){this.buttons=[];this.plugins=[];var b=this.padding,a=this.padding,j=this.size,g=this.size,m=this.radius,k=this.margin,q=dojox.drawing.library.icons,n={place:"BR",size:2,mult:4};if(this.strTools){var l=[],f=dojox.drawing.getRegistered("tool"),o={},i;for(i in f){var h=this.util.abbr(i);o[h]=f[i];this.strTools=="all"&&(l.push(h),h=dojox.drawing.getRegistered("tool",i),h.secondary&&l.push(h.secondary.name))}this.strTools!=
"all"&&(f=this.strTools.split(","),dojo.forEach(f,function(a){a=dojo.trim(a);l.push(a);a=dojox.drawing.getRegistered("tool",o[a].name);a.secondary&&l.push(a.secondary.name)},this));dojo.forEach(l,function(d){var d=dojo.trim(d),c=!1;if(d.indexOf("Secondary")>-1){var c=d.substring(0,d.indexOf("Secondary")),c=dojox.drawing.getRegistered("tool",o[c].name).secondary,e=c.label;this[d]=c.funct;c.setup&&dojo.hitch(this,c.setup)();e=this.toolDrawing.addUI("button",{data:{x:b,y:a,width:j,height:g/2,r:m},toolType:d,
secondary:!0,text:e,shadow:n,scope:this,callback:this[d]});c.postSetup&&dojo.hitch(this,c.postSetup,e)();c=!0}else e=this.toolDrawing.addUI("button",{data:{x:b,y:a,width:j,height:g,r:m},toolType:d,icon:q[d],shadow:n,scope:this,callback:"onToolClick"});dojox.drawing.register(e,"button");this.buttons.push(e);if(this.strSelected==d)e.select(),this.selected=e,this.drawing.setTool(e.toolType);this.horizontal?b+=g+k:a+=c?g/2+k:g+k},this)}this.horizontal?b+=this.toolPlugGap:a+=this.toolPlugGap;if(this.strPlugs){var f=
[],h=dojox.drawing.getRegistered("plugin"),p={};for(i in h){var r=this.util.abbr(i);p[r]=h[i];this.strPlugs=="all"&&f.push(r)}this.strPlugs!="all"&&(f=this.strPlugs.split(","),dojo.map(f,function(a){return dojo.trim(a)}));dojo.forEach(f,function(d){var c=dojo.trim(d);if(p[d].button!=!1){var e=this.toolDrawing.addUI("button",{data:{x:b,y:a,width:j,height:g,r:m},toolType:c,icon:q[c],shadow:n,scope:this,callback:"onPlugClick"});dojox.drawing.register(e,"button");this.plugins.push(e);this.horizontal?
b+=g+k:a+=g+k}c={};p[d].button==!1?c={name:this.drawing.stencilTypeMap[d]}:c={name:this.drawing.stencilTypeMap[d],options:{button:e}};this.drawing.addPlugin(c)},this)}dojo.connect(this.drawing,"onRenderStencil",this,"onRenderStencil")},onRenderStencil:function(){if(this.drawing.defaults.clickMode)this.drawing.mouse.setCursor("default"),this.selected&&this.selected.deselect(),this.selected=null},addTool:function(){},addPlugin:function(){},addBack:function(){this.toolDrawing.addUI("rect",{data:{x:0,
y:0,width:this.width,height:this.size+this.padding*2,fill:"#ffffff",borderWidth:0}})},onToolClick:function(b){this.drawing.defaults.clickMode&&this.drawing.mouse.setCursor("crosshair");dojo.forEach(this.buttons,function(a){a.id==b.id?(a.select(),this.selected=a,this.drawing.setTool(b.toolType)):a.secondary||a.deselect()},this)},onPlugClick:function(){},_mixprops:function(b,a){dojo.forEach(b,function(b){this[b]=a.tagName?dojo.attr(a,b)===null?this[b]:dojo.attr(a,b):a[b]===void 0?this[b]:a[b]},this)}}));