/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.image.Badge"]||(dojo._hasResource["dojox.image.Badge"]=!0,dojo.provide("dojox.image.Badge"),dojo.experimental("dojox.image.Badge"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dojo.fx.easing"),dojo.declare("dojox.image.Badge",[dijit._Widget,dijit._Templated],{baseClass:"dojoxBadge",templateString:'<div class="dojoxBadge" dojoAttachPoint="containerNode"></div>',children:"div.dojoxBadgeImage",rows:4,cols:5,cellSize:50,cellMargin:1,delay:2E3,threads:1,
easing:"dojo.fx.easing.backOut",startup:function(){if(!this._started){if(dojo.isString(this.easing))this.easing=dojo.getObject(this.easing);this.inherited(arguments);this._init()}},_init:function(){var a=0,b=this.cellSize;dojo.style(this.domNode,{width:b*this.cols+"px",height:b*this.rows+"px"});this._nl=dojo.query(this.children,this.containerNode).forEach(function(c,f){var d=f%this.cols,e=this.cellMargin*2;dojo.style(c,{top:a*b+"px",left:d*b+"px",width:b-e+"px",height:b-e+"px"});d==this.cols-1&&a++;
dojo.addClass(c,this.baseClass+"Image")},this);for(var c=this._nl.length;this.threads--;)setTimeout(dojo.hitch(this,"_enbiggen",{target:this._nl[Math.floor(Math.random()*c)]}),this.delay*this.threads)},_getCell:function(a){a=this._nl.indexOf(a);if(a>=0)return{x:a%this.cols,y:Math.floor(a/this.cols),n:this._nl[a],io:a}},_getImage:function(){return"url('')"},_enbiggen:function(a){if(a=this._getCell(a.target||a)){var b=this.cellMargin,c=this.cellSize*2-b*2,c={height:c,width:c};if(a.x==this.cols-1||a.x>
0&&Math.round(Math.random()))c.left=this.cellSize*(a.x-b);if(a.y==this.rows-1||a.y>0&&Math.round(Math.random()))c.top=this.cellSize*(a.y-b);b=this.baseClass;dojo.addClass(a.n,b+"Top");dojo.addClass(a.n,b+"Seen");dojo.animateProperty({node:a.n,properties:c,onEnd:dojo.hitch(this,"_loadUnder",a,c),easing:this.easing}).play()}},_loadUnder:function(a,b){var c=a.io,g=b.left>=0,f=b.top>=0,d=this.cols,e=c+(g?-1:1);c+=f?-d:d;var h=this.baseClass;dojo.forEach([e,c,f?g?e-d:c+1:g?c-1:e+d],function(a){(a=this._nl[a])&&
dojo.hasClass(a,h+"Seen")&&dojo.removeClass(a,h+"Seen")},this);setTimeout(dojo.hitch(this,"_disenbiggen",a,b),this.delay*1.25)},_disenbiggen:function(a,b){b.top>=0&&(b.top+=this.cellSize);b.left>=0&&(b.left+=this.cellSize);var c=this.cellSize-this.cellMargin*2;dojo.animateProperty({node:a.n,properties:dojo.mixin(b,{width:c,height:c}),onEnd:dojo.hitch(this,"_cycle",a,b)}).play(5)},_cycle:function(a){var b=this.baseClass;dojo.removeClass(a.n,b+"Top");a=this._nl.filter(function(a){return!dojo.hasClass(a,
b+"Seen")});setTimeout(dojo.hitch(this,"_enbiggen",{target:a[Math.floor(Math.random()*a.length)]}),this.delay/2)}}));