/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.image.Gallery"]||(dojo._hasResource["dojox.image.Gallery"]=!0,dojo.provide("dojox.image.Gallery"),dojo.experimental("dojox.image.Gallery"),dojo.require("dojo.fx"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.require("dojox.image.ThumbnailPicker"),dojo.require("dojox.image.SlideShow"),dojo.declare("dojox.image.Gallery",[dijit._Widget,dijit._Templated],{imageHeight:375,imageWidth:500,pageSize:dojox.image.SlideShow.prototype.pageSize,autoLoad:!0,linkAttr:"link",
imageThumbAttr:"imageUrlThumb",imageLargeAttr:"imageUrl",titleAttr:"title",slideshowInterval:3,templateString:dojo.cache("dojox.image","resources/Gallery.html",'<div dojoAttachPoint="outerNode" class="imageGalleryWrapper">\n\t<div dojoAttachPoint="thumbPickerNode"></div>\n\t<div dojoAttachPoint="slideShowNode"></div>\n</div>\n'),postCreate:function(){this.widgetid=this.id;this.inherited(arguments);this.thumbPicker=new dojox.image.ThumbnailPicker({linkAttr:this.linkAttr,imageLargeAttr:this.imageLargeAttr,
imageThumbAttr:this.imageThumbAttr,titleAttr:this.titleAttr,useLoadNotifier:!0,size:this.imageWidth},this.thumbPickerNode);this.slideShow=new dojox.image.SlideShow({imageHeight:this.imageHeight,imageWidth:this.imageWidth,autoLoad:this.autoLoad,linkAttr:this.linkAttr,imageLargeAttr:this.imageLargeAttr,titleAttr:this.titleAttr,slideshowInterval:this.slideshowInterval,pageSize:this.pageSize},this.slideShowNode);var a=this;dojo.subscribe(this.slideShow.getShowTopicName(),function(b){a.thumbPicker._showThumbs(b.index)});
dojo.subscribe(this.thumbPicker.getClickTopicName(),function(b){a.slideShow.showImage(b.index)});dojo.subscribe(this.thumbPicker.getShowTopicName(),function(b){a.slideShow.moveImageLoadingPointer(b.index)});dojo.subscribe(this.slideShow.getLoadTopicName(),function(b){a.thumbPicker.markImageLoaded(b)});this._centerChildren()},setDataStore:function(a,b,c){this.thumbPicker.setDataStore(a,b,c);this.slideShow.setDataStore(a,b,c)},reset:function(){this.slideShow.reset();this.thumbPicker.reset()},showNextImage:function(){this.slideShow.showNextImage()},
toggleSlideshow:function(){dojo.deprecated("dojox.widget.Gallery.toggleSlideshow is deprecated.  Use toggleSlideShow instead.","","2.0");this.toggleSlideShow()},toggleSlideShow:function(){this.slideShow.toggleSlideShow()},showImage:function(a,b){this.slideShow.showImage(a,b)},resize:function(a){this.thumbPicker.resize(a)},_centerChildren:function(){var a=dojo.marginBox(this.thumbPicker.outerNode),b=dojo.marginBox(this.slideShow.outerNode),a=(a.w-b.w)/2;a>0?dojo.style(this.slideShow.outerNode,"marginLeft",
a+"px"):a<0&&dojo.style(this.thumbPicker.outerNode,"marginLeft",a*-1+"px")}}));