/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


if(!dojo._hasResource["dojox.image.LightboxNano"]){dojo._hasResource["dojox.image.LightboxNano"]=!0;dojo.provide("dojox.image.LightboxNano");dojo.require("dojo.fx");var abs="absolute",vis="visibility",getViewport=function(){var a=dojo.doc.compatMode=="BackCompat"?dojo.body():dojo.doc.documentElement,b=dojo._docScroll();return{w:a.clientWidth,h:a.clientHeight,l:b.x,t:b.y}};dojo.declare("dojox.image.LightboxNano",null,{href:"",duration:500,preloadDelay:5E3,constructor:function(a,b){var c=this;dojo.mixin(c,
a);if(b=c._node=dojo.byId(b)){if(!/a/i.test(b.tagName)){var d=dojo.create("a",{href:c.href,"class":b.className},b,"after");b.className="";d.appendChild(b);b=d}dojo.style(b,"position","relative");c._createDiv("dojoxEnlarge",b);dojo.setSelectable(b,!1);c._onClickEvt=dojo.connect(b,"onclick",c,"_load")}c.href&&setTimeout(function(){(new Image).src=c.href;c._hideLoading()},c.preloadDelay)},destroy:function(){var a=this._connects||[];a.push(this._onClickEvt);dojo.forEach(a,dojo.disconnect);dojo.destroy(this._node)},
_createDiv:function(a,b,c){return dojo.create("div",{"class":a,style:{position:abs,display:c?"":"none"}},b)},_load:function(a){a&&dojo.stopEvent(a);if(!this._loading){this._loading=!0;this._reset();var a=this._img=dojo.create("img",{style:{visibility:"hidden",cursor:"pointer",position:abs,top:0,left:0,zIndex:9999999}},dojo.body()),b=this._loadingNode,c=dojo.query("img",this._node)[0]||this._node,d=dojo.position(c,!0),e=dojo.contentBox(c),c=dojo._getBorderExtents(c);if(b==null){this._loadingNode=b=
this._createDiv("dojoxLoading",this._node,!0);var f=dojo.marginBox(b);dojo.style(b,{left:parseInt((e.w-f.w)/2)+"px",top:parseInt((e.h-f.h)/2)+"px"})}e.x=d.x-10+c.l;e.y=d.y-10+c.t;this._start=e;this._connects=[dojo.connect(a,"onload",this,"_show")];a.src=this.href}},_hideLoading:function(){this._loadingNode&&dojo.style(this._loadingNode,"display","none");this._loadingNode=!1},_show:function(){var a=getViewport(),b=this._img.width,c=this._img.height,d=parseInt((a.w-20)*0.9),e=parseInt((a.h-20)*0.9),
f=dojo.doc,g=this._bg=dojo.create("div",{style:{backgroundColor:"#000",opacity:0,position:abs,zIndex:9999998}},dojo.body());this._loadingNode&&this._hideLoading();dojo.style(this._img,{border:"10px solid #fff",visibility:"visible"});dojo.style(this._node,vis,"hidden");this._loading=!1;this._connects=this._connects.concat([dojo.connect(f,"onmousedown",this,"_hide"),dojo.connect(f,"onkeypress",this,"_key"),dojo.connect(window,"onresize",this,"_sizeBg")]);b>d&&(c=c*d/b,b=d);c>e&&(b=b*e/c,c=e);this._end=
{x:(a.w-20-b)/2+a.l,y:(a.h-20-c)/2+a.t,w:b,h:c};this._sizeBg();dojo.fx.combine([this._anim(this._img,this._coords(this._start,this._end)),this._anim(g,{opacity:0.5})]).play()},_sizeBg:function(){var a=dojo.doc.documentElement;dojo.style(this._bg,{top:0,left:0,width:a.scrollWidth+"px",height:a.scrollHeight+"px"})},_key:function(a){dojo.stopEvent(a);this._hide()},_coords:function(a,b){return{left:{start:a.x,end:b.x},top:{start:a.y,end:b.y},width:{start:a.w,end:b.w},height:{start:a.h,end:b.h}}},_hide:function(){dojo.forEach(this._connects,
dojo.disconnect);this._connects=[];dojo.fx.combine([this._anim(this._img,this._coords(this._end,this._start),"_reset"),this._anim(this._bg,{opacity:0})]).play()},_reset:function(){dojo.style(this._node,vis,"visible");dojo.destroy(this._img);dojo.destroy(this._bg);this._img=this._bg=null;this._node.focus()},_anim:function(a,b,c){return dojo.animateProperty({node:a,duration:this.duration,properties:b,onEnd:c?dojo.hitch(this,c):null})},show:function(a){a=a||{};this.href=a.href||this.href;var a=dojo.byId(a.origin),
b=getViewport();this._node=a||dojo.create("div",{style:{position:abs,width:0,hieght:0,left:b.l+b.w/2+"px",top:b.t+b.h/2+"px"}},dojo.body());this._load();a||dojo.destroy(this._node)}})};