/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.image.Lightbox"]||(dojo._hasResource["dojox.image.Lightbox"]=!0,dojo.provide("dojox.image.Lightbox"),dojo.experimental("dojox.image.Lightbox"),dojo.require("dojo.window"),dojo.require("dijit.Dialog"),dojo.require("dojox.fx._base"),dojo.declare("dojox.image.Lightbox",dijit._Widget,{group:"",title:"",href:"",duration:500,modal:!1,_allowPassthru:!1,_attachedDialog:null,startup:function(){this.inherited(arguments);var b=dijit.byId("dojoxLightboxDialog");b?this._attachedDialog=
b:(this._attachedDialog=new dojox.image.LightboxDialog({id:"dojoxLightboxDialog"}),this._attachedDialog.startup());this.store||(this._addSelf(),this.connect(this.domNode,"onclick","_handleClick"))},_addSelf:function(){this._attachedDialog.addImage({href:this.href,title:this.title},this.group||null)},_handleClick:function(b){this._allowPassthru||(b.preventDefault(),this.show())},show:function(){this._attachedDialog.show(this)},hide:function(){this._attachedDialog.hide()},disable:function(){this._allowPassthru=
!0},enable:function(){this._allowPassthru=!1},onClick:function(){},destroy:function(){this._attachedDialog.removeImage(this);this.inherited(arguments)}}),dojo.declare("dojox.image.LightboxDialog",dijit.Dialog,{title:"",inGroup:null,imgUrl:dijit._Widget.prototype._blankGif,errorMessage:"Image not found.",adjust:!0,modal:!1,errorImg:dojo.moduleUrl("dojox.image","resources/images/warning.png"),templateString:dojo.cache("dojox.image","resources/Lightbox.html",'<div class="dojoxLightbox" dojoAttachPoint="containerNode">\n\t<div style="position:relative">\n\t\t<div dojoAttachPoint="imageContainer" class="dojoxLightboxContainer" dojoAttachEvent="onclick: _onImageClick">\n\t\t\t<img dojoAttachPoint="imgNode" src="${imgUrl}" class="dojoxLightboxImage" alt="${title}">\n\t\t\t<div class="dojoxLightboxFooter" dojoAttachPoint="titleNode">\n\t\t\t\t<div class="dijitInline LightboxClose" dojoAttachPoint="closeButtonNode"></div>\n\t\t\t\t<div class="dijitInline LightboxNext" dojoAttachPoint="nextButtonNode"></div>\t\n\t\t\t\t<div class="dijitInline LightboxPrev" dojoAttachPoint="prevButtonNode"></div>\n\t\t\t\t<div class="dojoxLightboxText" dojoAttachPoint="titleTextNode"><span dojoAttachPoint="textNode">${title}</span><span dojoAttachPoint="groupCount" class="dojoxLightboxGroupText"></span></div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n'),
constructor:function(b){this._groups=this._groups||b&&b._groups||{XnoGroupX:[]}},startup:function(){this.inherited(arguments);this._animConnects=[];this.connect(this.nextButtonNode,"onclick","_nextImage");this.connect(this.prevButtonNode,"onclick","_prevImage");this.connect(this.closeButtonNode,"onclick","hide");this._makeAnims();this._vp=dojo.window.getBox();return this},show:function(b){var a=this;this._lastGroup=b;a.open||(a.inherited(arguments),a._modalconnects.push(dojo.connect(dojo.global,"onscroll",
this,"_position"),dojo.connect(dojo.global,"onresize",this,"_position"),dojo.connect(dojo.body(),"onkeypress",this,"_handleKey")),b.modal||a._modalconnects.push(dojo.connect(dijit._underlay.domNode,"onclick",this,"onCancel")));if(this._wasStyled){var c=dojo.create("img",null,a.imgNode,"after");dojo.destroy(a.imgNode);a.imgNode=c;a._makeAnims();a._wasStyled=!1}dojo.style(a.imgNode,"opacity","0");dojo.style(a.titleNode,"opacity","0");c=b.href;if(b.group&&b!=="XnoGroupX"||a.inGroup){if(!a.inGroup)a.inGroup=
a._groups[b.group],dojo.forEach(a.inGroup,function(c,e){if(c.href==b.href)a._index=e});if(!a._index)a._index=0,c=(c=a.inGroup[a._index])&&c.href||a.errorImg;a.groupCount.innerHTML=" ("+(a._index+1)+" of "+Math.max(1,a.inGroup.length)+")";a.prevButtonNode.style.visibility="visible";a.nextButtonNode.style.visibility="visible"}else a.groupCount.innerHTML="",a.prevButtonNode.style.visibility="hidden",a.nextButtonNode.style.visibility="hidden";if(!b.leaveTitle)a.textNode.innerHTML=b.title;a._ready(c)},
_ready:function(b){var a=this;a._imgError=dojo.connect(a.imgNode,"error",a,function(){dojo.disconnect(a._imgError);a.imgNode.src=a.errorImg;a.textNode.innerHTML=a.errorMessage});a._imgConnect=dojo.connect(a.imgNode,"load",a,function(){a.resizeTo({w:a.imgNode.width,h:a.imgNode.height,duration:a.duration});dojo.disconnect(a._imgConnect);a._imgError&&dojo.disconnect(a._imgError)});a.imgNode.src=b},_nextImage:function(){if(this.inGroup)this._index+1<this.inGroup.length?this._index++:this._index=0,this._loadImage()},
_prevImage:function(){if(this.inGroup)this._index==0?this._index=this.inGroup.length-1:this._index--,this._loadImage()},_loadImage:function(){this._loadingAnim.play(1)},_prepNodes:function(){this._imageReady=!1;this.inGroup&&this.inGroup[this._index]?this.show({href:this.inGroup[this._index].href,title:this.inGroup[this._index].title}):this.show({title:this.errorMessage,href:this.errorImg})},_calcTitleSize:function(){var b=dojo.map(dojo.query("> *",this.titleNode).position(),function(a){return a.h});
return{h:Math.max.apply(Math,b)}},resizeTo:function(b,a){var c=dojo.boxModel=="border-box"?dojo._getBorderExtents(this.domNode).w:0,d=a||this._calcTitleSize();this._lastTitleSize=d;if(this.adjust&&(b.h+d.h+c+80>this._vp.h||b.w+c+60>this._vp.w))this._lastSize=b,b=this._scaleToFit(b);this._currentSize=b;c=dojox.fx.sizeTo({node:this.containerNode,duration:b.duration||this.duration,width:b.w+c,height:b.h+d.h+c});this.connect(c,"onEnd","_showImage");c.play(15)},_scaleToFit:function(b){var a={},c={w:this._vp.w-
80,h:this._vp.h-60-this._lastTitleSize.h},d=b.w/b.h;d>=c.w/c.h?(a.h=c.w/d,a.w=c.w):(a.w=d*c.h,a.h=c.h);this._wasStyled=!0;this._setImageSize(a);a.duration=b.duration;return a},_setImageSize:function(b){var a=this.imgNode;a.height=b.h;a.width=b.w},_size:function(){},_position:function(b){this._vp=dojo.window.getBox();this.inherited(arguments);b&&b.type=="resize"&&(this._wasStyled?(this._setImageSize(this._lastSize),this.resizeTo(this._lastSize)):(this.imgNode.height+80>this._vp.h||this.imgNode.width+
60>this._vp.h)&&this.resizeTo({w:this.imgNode.width,h:this.imgNode.height}))},_showImage:function(){this._showImageAnim.play(1)},_showNav:function(){var b=dojo.marginBox(this.titleNode);b.h>this._lastTitleSize.h?this.resizeTo(this._wasStyled?this._lastSize:this._currentSize,b):this._showNavAnim.play(1)},hide:function(){dojo.fadeOut({node:this.titleNode,duration:200,onEnd:dojo.hitch(this,function(){this.imgNode.src=this._blankGif})}).play(5);this.inherited(arguments);this._index=this.inGroup=null},
addImage:function(b,a){b.href&&(a?(this._groups[a]||(this._groups[a]=[]),this._groups[a].push(b)):this._groups.XnoGroupX.push(b))},removeImage:function(b){dojo.every(this._groups[b.group||"XnoGroupX"],function(a,c,d){return a.href==b.href?(d.splice(c,1),!1):!0})},removeGroup:function(b){this._groups[b]&&(this._groups[b]=[])},_handleKey:function(b){if(this.open){var a=dojo.keys;switch(b.charOrCode){case a.ESCAPE:this.hide();break;case a.DOWN_ARROW:case a.RIGHT_ARROW:case 78:this._nextImage();break;
case a.UP_ARROW:case a.LEFT_ARROW:case 80:this._prevImage()}}},_makeAnims:function(){dojo.forEach(this._animConnects,dojo.disconnect);this._animConnects=[];this._showImageAnim=dojo.fadeIn({node:this.imgNode,duration:this.duration});this._animConnects.push(dojo.connect(this._showImageAnim,"onEnd",this,"_showNav"));this._loadingAnim=dojo.fx.combine([dojo.fadeOut({node:this.imgNode,duration:175}),dojo.fadeOut({node:this.titleNode,duration:175})]);this._animConnects.push(dojo.connect(this._loadingAnim,
"onEnd",this,"_prepNodes"));this._showNavAnim=dojo.fadeIn({node:this.titleNode,duration:225})},onClick:function(){},_onImageClick:function(b){if(b&&b.target==this.imgNode&&(this.onClick(this._lastGroup),this._lastGroup.declaredClass))this._lastGroup.onClick(this._lastGroup)}}));