/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.image.SlideShow"]||(dojo._hasResource["dojox.image.SlideShow"]=!0,dojo.provide("dojox.image.SlideShow"),dojo.require("dojo.string"),dojo.require("dojo.fx"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.declare("dojox.image.SlideShow",[dijit._Widget,dijit._Templated],{imageHeight:375,imageWidth:500,title:"",titleTemplate:'${title} <span class="slideShowCounterText">(${current} of ${total})</span>',noLink:!1,loop:!0,hasNav:!0,images:[],pageSize:20,autoLoad:!0,
autoStart:!1,fixedHeight:!1,imageStore:null,linkAttr:"link",imageLargeAttr:"imageUrl",titleAttr:"title",slideshowInterval:3,templateString:dojo.cache("dojox.image","resources/SlideShow.html",'<div dojoAttachPoint="outerNode" class="slideShowWrapper">\n\t<div style="position:relative;" dojoAttachPoint="innerWrapper">\n\t\t<div class="slideShowNav" dojoAttachEvent="onclick: _handleClick">\n\t\t\t<div class="dijitInline slideShowTitle" dojoAttachPoint="titleNode">${title}</div>\n\t\t</div>\n\t\t<div dojoAttachPoint="navNode" class="slideShowCtrl" dojoAttachEvent="onclick: _handleClick">\n\t\t\t<span dojoAttachPoint="navPrev" class="slideShowCtrlPrev"></span>\n\t\t\t<span dojoAttachPoint="navPlay" class="slideShowCtrlPlay"></span>\n\t\t\t<span dojoAttachPoint="navNext" class="slideShowCtrlNext"></span>\n\t\t</div>\n\t\t<div dojoAttachPoint="largeNode" class="slideShowImageWrapper"></div>\t\t\n\t\t<div dojoAttachPoint="hiddenNode" class="slideShowHidden"></div>\n\t</div>\n</div>\n'),
_imageCounter:0,_tmpImage:null,_request:null,postCreate:function(){this.inherited(arguments);var a=document.createElement("img");a.setAttribute("width",this.imageWidth);a.setAttribute("height",this.imageHeight);this.hasNav&&(dojo.connect(this.outerNode,"onmouseover",this,function(){try{this._showNav()}catch(a){}}),dojo.connect(this.outerNode,"onmouseout",this,function(a){try{this._hideNav(a)}catch(b){}}));this.outerNode.style.width=this.imageWidth+"px";a.setAttribute("src",this._blankGif);this.largeNode.appendChild(a);
this._tmpImage=this._currentImage=a;this._fitSize(!0);this._loadImage(0,dojo.hitch(this,"showImage",0));this._calcNavDimensions()},setDataStore:function(a,d,b){this.reset();var c=this;this._request={query:{},start:d.start||0,count:d.count||this.pageSize,onBegin:function(a){c.maxPhotos=a}};d.query&&dojo.mixin(this._request.query,d.query);b&&dojo.forEach(["imageLargeAttr","linkAttr","titleAttr"],function(a){b[a]&&(this[a]=b[a])},this);this.imageStore=a;this._request.onComplete=function(a){c.maxPhotos=
a.length;c._request.onComplete=null;c.autoStart?(c.imageIndex=-1,c.toggleSlideShow()):c.showImage(0)};this._request.start=0;this.imageStore.fetch(this._request)},reset:function(){dojo.query("> *",this.largeNode).orphan();this.largeNode.appendChild(this._tmpImage);dojo.query("> *",this.hiddenNode).orphan();dojo.forEach(this.images,function(a){a&&a.parentNode&&a.parentNode.removeChild(a)});this.images=[];this.isInitialized=!1;this._imageCounter=0},isImageLoaded:function(a){return this.images&&this.images.length>
a&&this.images[a]},moveImageLoadingPointer:function(a){this._imageCounter=a},destroy:function(){this._slideId&&this._stop();this.inherited(arguments)},showNextImage:function(a,d){if(a&&this._timerCancelled)return!1;if(this.imageIndex+1>=this.maxPhotos)if(a&&(this.loop||d))this.imageIndex=-1;else return this._slideId&&this._stop(),!1;this.showImage(this.imageIndex+1,dojo.hitch(this,function(){a&&this._startTimer()}));return!0},toggleSlideShow:function(){if(this._slideId)this._stop();else{dojo.toggleClass(this.domNode,
"slideShowPaused");this._timerCancelled=!1;var a=this.imageIndex;if(a<0||this.images[a]&&this.images[a]._img.complete)this.showNextImage(!0,!0)||this._stop();else{var d=dojo.subscribe(this.getShowTopicName(),dojo.hitch(this,function(b){setTimeout(dojo.hitch(this,function(){b.index==a&&(this.showNextImage(!0,!0)||this._stop(),dojo.unsubscribe(d))}),this.slideshowInterval*1E3)}));dojo.publish(this.getShowTopicName(),[{index:a,title:"",url:""}])}}},getShowTopicName:function(){return(this.widgetId||this.id)+
"/imageShow"},getLoadTopicName:function(){return(this.widgetId?this.widgetId:this.id)+"/imageLoad"},showImage:function(a,d){!d&&this._slideId&&this.toggleSlideShow();var b=this,c=this.largeNode.getElementsByTagName("div");this.imageIndex=a;var g=function(){if(b.images[a]){for(;b.largeNode.firstChild;)b.largeNode.removeChild(b.largeNode.firstChild);dojo.style(b.images[a],"opacity",0);b.largeNode.appendChild(b.images[a]);b._currentImage=b.images[a]._img;b._fitSize();dojo.fadeIn({node:b.images[a],duration:300,
onEnd:function(c,j,g){var e=b.images[a].firstChild;if(e.tagName.toLowerCase()!="img")e=e.firstChild;var f=e.getAttribute("title")||"";b._navShowing&&b._showNav(!0);dojo.publish(b.getShowTopicName(),[{index:a,title:f,url:e.getAttribute("src")}]);d&&d(c,j,g);b._setTitle(f)}}).play()}else b._loadImage(a,function(){b.showImage(a,d)})};c&&c.length>0?dojo.fadeOut({node:c[0],duration:300,onEnd:function(){b.hiddenNode.appendChild(c[0]);g()}}).play():g()},_fitSize:function(a){!this.fixedHeight||a?dojo.style(this.innerWrapper,
"height",this._currentImage.height+(this.hasNav?20:0)+"px"):dojo.style(this.largeNode,"paddingTop",this._getTopPadding()+"px")},_getTopPadding:function(){return!this.fixedHeight?0:(this.imageHeight-this._currentImage.height)/2},_loadNextImage:function(){if(this.autoLoad){for(;this.images.length>=this._imageCounter&&this.images[this._imageCounter];)this._imageCounter++;this._loadImage(this._imageCounter)}},_loadImage:function(a,d){if(!this.images[a]&&this._request){var b=a-a%(this._request.count||
this.pageSize);this._request.start=b;this._request.onComplete=function(c){var d=a-b;c&&c.length>d&&h(c[d])};var c=this,g=this.imageStore,h=function(b){var h=c.imageStore.getValue(b,c.imageLargeAttr),e=new Image,f=dojo.create("div",{id:c.id+"_imageDiv"+a});f._img=e;var i=c.imageStore.getValue(b,c.linkAttr);!i||c.noLink?f.appendChild(e):dojo.create("a",{href:i,target:"_blank"},f).appendChild(e);dojo.connect(e,"onload",function(){g==c.imageStore&&(c._fitImage(e),dojo.attr(f,{width:c.imageWidth,height:c.imageHeight}),
dojo.publish(c.getLoadTopicName(),[a]),setTimeout(function(){c._loadNextImage()},1),d&&d())});c.hiddenNode.appendChild(f);dojo.create("div",{className:"slideShowTitle"},f);c.images[a]=f;dojo.attr(e,"src",h);(b=c.imageStore.getValue(b,c.titleAttr))&&dojo.attr(e,"title",b)};this.imageStore.fetch(this._request)}},_stop:function(){this._slideId&&clearTimeout(this._slideId);this._slideId=null;this._timerCancelled=!0;dojo.removeClass(this.domNode,"slideShowPaused")},_prev:function(){this.imageIndex<1||
this.showImage(this.imageIndex-1)},_next:function(){this.showNextImage()},_startTimer:function(){var a=this.id;this._slideId=setTimeout(function(){dijit.byId(a).showNextImage(!0)},this.slideshowInterval*1E3)},_calcNavDimensions:function(){dojo.style(this.navNode,"position","absolute");dojo.style(this.navNode,"top","-10000px");dojo._setOpacity(this.navNode,1);this.navPlay._size=dojo.marginBox(this.navPlay);this.navPrev._size=dojo.marginBox(this.navPrev);this.navNext._size=dojo.marginBox(this.navNext);
dojo._setOpacity(this.navNode,0);dojo.style(this.navNode,{position:"",top:""})},_setTitle:function(a){this.titleNode.innerHTML=dojo.string.substitute(this.titleTemplate,{title:a,current:1+this.imageIndex,total:this.maxPhotos||""})},_fitImage:function(a){var d=a.width,b=a.height;if(d>this.imageWidth)b=Math.floor(b*(this.imageWidth/d)),a.height=b,a.width=d=this.imageWidth;if(b>this.imageHeight)d=Math.floor(d*(this.imageHeight/b)),a.height=this.imageHeight,a.width=d},_handleClick:function(a){switch(a.target){case this.navNext:this._next();
break;case this.navPrev:this._prev();break;case this.navPlay:this.toggleSlideShow()}},_showNav:function(a){if(!this._navShowing||a){dojo.style(this.navNode,"marginTop","0px");a=dojo.style(this.navNode,"width")/2-this.navPlay._size.w/2-this.navPrev._size.w;dojo.style(this.navPlay,"marginLeft",a+"px");dojo.marginBox(this.outerNode);a=this._currentImage.height-this.navPlay._size.h-10+this._getTopPadding();a>this._currentImage.height&&(a+=10);dojo[this.imageIndex<1?"addClass":"removeClass"](this.navPrev,
"slideShowCtrlHide");dojo[this.imageIndex+1>=this.maxPhotos?"addClass":"removeClass"](this.navNext,"slideShowCtrlHide");var d=this;this._navAnim&&this._navAnim.stop();if(!this._navShowing)this._navAnim=dojo.fadeIn({node:this.navNode,duration:300,onEnd:function(){d._navAnim=null}}),this._navAnim.play(),this._navShowing=!0}},_hideNav:function(a){if(!a||!this._overElement(this.outerNode,a)){var d=this;this._navAnim&&this._navAnim.stop();this._navAnim=dojo.fadeOut({node:this.navNode,duration:300,onEnd:function(){d._navAnim=
null}});this._navAnim.play();this._navShowing=!1}},_overElement:function(a,d){if(typeof dojo=="undefined")return!1;var a=dojo.byId(a),b={x:d.pageX,y:d.pageY},c=dojo._getBorderBox(a),g=dojo.coords(a,!0),h=g.x;return b.x>=h&&b.x<=h+c.w&&b.y>=g.y&&b.y<=top+c.h}}));