/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/


dojo._hasResource["dojox.image.ThumbnailPicker"]||(dojo._hasResource["dojox.image.ThumbnailPicker"]=!0,dojo.provide("dojox.image.ThumbnailPicker"),dojo.experimental("dojox.image.ThumbnailPicker"),dojo.require("dojox.fx.scroll"),dojo.require("dojo.fx.easing"),dojo.require("dojo.fx"),dojo.require("dijit._Widget"),dojo.require("dijit._Templated"),dojo.declare("dojox.image.ThumbnailPicker",[dijit._Widget,dijit._Templated],{imageStore:null,request:null,size:500,thumbHeight:75,thumbWidth:100,useLoadNotifier:!1,
useHyperlink:!1,hyperlinkTarget:"new",isClickable:!0,isScrollable:!0,isHorizontal:!0,autoLoad:!0,linkAttr:"link",imageThumbAttr:"imageUrlThumb",imageLargeAttr:"imageUrl",pageSize:20,titleAttr:"title",templateString:dojo.cache("dojox.image","resources/ThumbnailPicker.html",'<div dojoAttachPoint="outerNode" class="thumbOuter">\n\t<div dojoAttachPoint="navPrev" class="thumbNav thumbClickable">\n\t  <img src="" dojoAttachPoint="navPrevImg"/>    \n\t</div>\n\t<div dojoAttachPoint="thumbScroller" class="thumbScroller">\n\t  <div dojoAttachPoint="thumbsNode" class="thumbWrapper"></div>\n\t</div>\n\t<div dojoAttachPoint="navNext" class="thumbNav thumbClickable">\n\t  <img src="" dojoAttachPoint="navNextImg"/>  \n\t</div>\n</div>\n'),
_thumbs:[],_thumbIndex:0,_maxPhotos:0,_loadedImages:{},postCreate:function(){this.widgetid=this.id;this.inherited(arguments);this.pageSize=Number(this.pageSize);this._scrollerSize=this.size-102;var a=this._sizeProperty=this.isHorizontal?"width":"height";dojo.style(this.outerNode,"textAlign","center");dojo.style(this.outerNode,a,this.size+"px");dojo.style(this.thumbScroller,a,this._scrollerSize+"px");this.useHyperlink&&dojo.subscribe(this.getClickTopicName(),this,function(a){if(a=this.imageStore.getValue(a.data,
this.linkAttr))this.hyperlinkTarget=="new"?window.open(a):window.location=a});this.isClickable&&dojo.addClass(this.thumbsNode,"thumbClickable");this._totalSize=0;this.init()},init:function(){if(this.isInitialized)return!1;var a=this.isHorizontal?"Horiz":"Vert";dojo.addClass(this.navPrev,"prev"+a);dojo.addClass(this.navNext,"next"+a);dojo.addClass(this.thumbsNode,"thumb"+a);dojo.addClass(this.outerNode,"thumb"+a);dojo.attr(this.navNextImg,"src",this._blankGif);dojo.attr(this.navPrevImg,"src",this._blankGif);
this.connect(this.navPrev,"onclick","_prev");this.connect(this.navNext,"onclick","_next");this.isInitialized=!0;this.isHorizontal?(this._offsetAttr="offsetLeft",this._sizeAttr="offsetWidth",this._scrollAttr="scrollLeft"):(this._offsetAttr="offsetTop",this._sizeAttr="offsetHeight",this._scrollAttr="scrollTop");this._updateNavControls();this.imageStore&&this.request&&this._loadNextPage();return!0},getClickTopicName:function(){return(this.widgetId||this.id)+"/select"},getShowTopicName:function(){return(this.widgetId||
this.id)+"/show"},setDataStore:function(a,b,c){this.reset();this.request={query:{},start:b.start||0,count:b.count||10,onBegin:dojo.hitch(this,function(a){this._maxPhotos=a})};b.query&&dojo.mixin(this.request.query,b.query);c&&dojo.forEach(["imageThumbAttr","imageLargeAttr","linkAttr","titleAttr"],function(a){c[a]&&(this[a]=c[a])},this);this.request.start=0;this.request.count=this.pageSize;this.imageStore=a;this._loadInProgress=!1;this.init()||this._loadNextPage()},reset:function(){this._loadedImages=
{};dojo.forEach(this._thumbs,function(a){a&&a.parentNode&&dojo.destroy(a)});this._thumbs=[];this.isInitialized=!1;this._noImages=!0},isVisible:function(a){a=this._thumbs[a];if(!a)return!1;var b=this.isHorizontal?"offsetLeft":"offsetTop",c=this.isHorizontal?"offsetWidth":"offsetHeight",d=this.isHorizontal?"scrollLeft":"scrollTop",b=a[b]-this.thumbsNode[b];return b>=this.thumbScroller[d]&&b+a[c]<=this.thumbScroller[d]+this._scrollerSize},resize:function(){var a=this.isHorizontal?"w":"h",b=0;this._thumbs.length>
0&&dojo.marginBox(this._thumbs[0]).w==0||(dojo.forEach(this._thumbs,dojo.hitch(this,function(c){var d=dojo.marginBox(c.firstChild);b+=Number(d[a])+10;this.useLoadNotifier&&d.w>0&&dojo.style(c.lastChild,"width",d.w-4+"px");dojo.style(c,"width",d.w+"px")})),dojo.style(this.thumbsNode,this._sizeProperty,b+"px"),this._updateNavControls())},_next:function(){for(var a=this.isHorizontal?"offsetLeft":"offsetTop",b=this.isHorizontal?"offsetWidth":"offsetHeight",c=this.thumbsNode[a],d=this._thumbs[this._thumbIndex][a]-
c,e,f=this._thumbIndex+1;f<this._thumbs.length;f++)if(e=this._thumbs[f],e[a]-c+e[b]-d>this._scrollerSize){this._showThumbs(f);break}},_prev:function(){if(this.thumbScroller[this.isHorizontal?"scrollLeft":"scrollTop"]!=0){for(var a=this.isHorizontal?"offsetLeft":"offsetTop",b=this._thumbs[this._thumbIndex][a]-this.thumbsNode[a],c,d=this._thumbIndex-1;d>-1;d--)if(c=this._thumbs[d],b-c[a]>this._scrollerSize){this._showThumbs(d+1);return}this._showThumbs(0)}},_checkLoad:function(a,b){dojo.publish(this.getShowTopicName(),
[{index:b}]);this._updateNavControls();this._loadingImages={};this._thumbIndex=b;this.thumbsNode.offsetWidth-a.offsetLeft<this._scrollerSize*2&&this._loadNextPage()},_showThumbs:function(a){a=Math.min(Math.max(a,0),this._maxPhotos);if(!(a>=this._maxPhotos)){var b=this._thumbs[a];if(b){var c=b.offsetLeft-this.thumbsNode.offsetLeft,d=b.offsetTop-this.thumbsNode.offsetTop,e=this.isHorizontal?c:d;if(!(e>=this.thumbScroller[this._scrollAttr]&&e+b[this._sizeAttr]<=this.thumbScroller[this._scrollAttr]+this._scrollerSize))this.isScrollable?
dojox.fx.smoothScroll({target:this.isHorizontal?{x:c,y:0}:{x:0,y:d},win:this.thumbScroller,duration:300,easing:dojo.fx.easing.easeOut,onEnd:dojo.hitch(this,"_checkLoad",b,a)}).play(10):(this.isHorizontal?this.thumbScroller.scrollLeft=c:this.thumbScroller.scrollTop=d,this._checkLoad(b,a))}}},markImageLoaded:function(a){var b=dojo.byId("loadingDiv_"+this.widgetid+"_"+a);b&&this._setThumbClass(b,"thumbLoaded");this._loadedImages[a]=!0},_setThumbClass:function(a,b){this.autoLoad&&dojo.addClass(a,b)},
_loadNextPage:function(){if(!this._loadInProgress){this._loadInProgress=!0;for(var a=this.request.start+(this._noImages?0:this.pageSize),b=a;b<this._thumbs.length&&this._thumbs[b];)b++;var c=this.imageStore;this.request.onComplete=dojo.hitch(this,function(a){if(c==this.imageStore)if(a&&a.length){var e=0,f=dojo.hitch(this,function(){if(e>=a.length)this._loadInProgress=!1;else{var c=e++;this._loadImage(a[c],b+c,f)}});f();this._updateNavControls()}else this._loadInProgress=!1});this.request.onError=
dojo.hitch(this,function(){this._loadInProgress=!1;console.log("Error getting items")});this.request.start=a;this._noImages=!1;this.imageStore.fetch(this.request)}},_loadImage:function(a,b,c){var d=this.imageStore,e=d.getValue(a,this.imageThumbAttr),f=dojo.create("div",{id:"img_"+this.widgetid+"_"+b}),g=dojo.create("img",{},f);g._index=b;g._data=a;this._thumbs[b]=f;var h;this.useLoadNotifier&&(h=dojo.create("div",{id:"loadingDiv_"+this.widgetid+"_"+b},f),this._setThumbClass(h,this._loadedImages[b]?
"thumbLoaded":"thumbNotifier"));var b=dojo.marginBox(this.thumbsNode),i;this.isHorizontal?(h=this.thumbWidth,i="w"):(h=this.thumbHeight,i="h");b=b[i];i=this.thumbScroller.scrollLeft;var j=this.thumbScroller.scrollTop;dojo.style(this.thumbsNode,this._sizeProperty,b+h+20+"px");this.thumbScroller.scrollLeft=i;this.thumbScroller.scrollTop=j;this.thumbsNode.appendChild(f);dojo.connect(g,"onload",this,dojo.hitch(this,function(){if(d!=this.imageStore)return!1;this.resize();setTimeout(c,0);return!1}));dojo.connect(g,
"onclick",this,function(b){dojo.publish(this.getClickTopicName(),[{index:b.target._index,data:b.target._data,url:g.getAttribute("src"),largeUrl:this.imageStore.getValue(a,this.imageLargeAttr),title:this.imageStore.getValue(a,this.titleAttr),link:this.imageStore.getValue(a,this.linkAttr)}]);return!1});dojo.addClass(g,"imageGalleryThumb");g.setAttribute("src",e);(e=this.imageStore.getValue(a,this.titleAttr))&&g.setAttribute("title",e);this._updateNavControls()},_updateNavControls:function(){var a=function(a,
b){var c=b?"addClass":"removeClass";dojo[c](a,"enabled");dojo[c](a,"thumbClickable")},b=this.isHorizontal?"scrollLeft":"scrollTop",c=this.isHorizontal?"offsetWidth":"offsetHeight";a(this.navPrev,this.thumbScroller[b]>0);a(this.navNext,this.thumbScroller[b]+this._scrollerSize<this.thumbsNode[c])}}));